### ISSUE TITLE
Update the color of status bar in various screens

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1000]
The status bar color in various android screens is inconsistent. Update status bar color code as per the mocks and spreadsheet:
https://docs.google.com/spreadsheets/d/1XphP6nWoUdOZn9pY2kdgfqMWfJjMfKMb98MXM5rp2HY/edit#gid=0
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/

**Comment by SayantanBanerjee16** [comment]
@rt4914 Can I work on this issue?

**Comment by SayantanBanerjee16** [comment]
@rt4914 I searched a lot online but I haven't found a way in which we can supply `Status Bar content colors`. We can supply Status Bar Color and then supply a boolean FLAG to have dark content if the Status bar is Light (by default the contents are Light).

The pseudo-code being:-

   ```
 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
     if(status_bar_color_is_LIGHT){ 
       activity.window.decorView.systemUiVisibility = View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR 
     }
     activity.window.statusBarColor = ContextCompat.getColor(activity, R.color.white)
}
```
Also the approach should be to register the above pseudo-code in an Utility method and call that method from the respective Activity and Fragment Presenters with appropriate color. Is it correct?

**Comment by rt4914** [comment]
> @rt4914 I searched a lot online but I haven't found a way in which we can supply `Status Bar content colors`. We can supply Status Bar Color and then supply a boolean FLAG to have dark content if the Status bar is Light (by default the contents are Light).
> 
> The pseudo-code being:-
> 
> ```
> if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
>   if(status_bar_color_is_LIGHT){ 
>     activity.window.decorView.systemUiVisibility = View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR 
>   }
>   activity.window.statusBarColor = ContextCompat.getColor(activity, R.color.white)
> }
> ```
> 
> Also the approach should be to register the above pseudo-code in an Utility method and call that method from the respective Activity and Fragment Presenters with appropriate color. Is it correct?

@nikitamarysolomanpvt PTAL at this.

**Comment by SayantanBanerjee16** [comment]
@rt4914 @nikitamarysolomanpvt Okay I got the meaning of the column `Color of Background/Object Below Status Bar` in the spread-sheet. I misunderstood it previously. Creating a PR with the above-mentioned approach.
