### ISSUE TITLE
Common simple_toolbar.xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1001]
All xmls activities/fragments are using toolbars at various places but out of all these toolbars below mentioned design is the most common design.

<img width="381" alt="Screenshot 2020-04-20 at 11 47 28 AM" src="https://user-images.githubusercontent.com/9396084/79719709-c3688d80-82fc-11ea-9b54-dd9f64e9b787.png">

This design should have a common `simple_toolbar.xml` file which should be used in various activities/fragment and only the title of toolbar will be controlled from `kotlin`.

**Comment by NullByte08** [comment]
@rt4914 Can I work on this?

**Comment by rt4914** [comment]
> @rt4914 Can I work on this?

@NullByte08 Yeah sure. Just to be clear it will bring changes to a lot of files and also test case files possibly. So better fix this in multiple PRs.

**Comment by NullByte08** [comment]
@rt4914 ok

**Comment by anandwana001** [comment]
It will be included in the required `XML` files, so what will be the good suggested `id` for that `include` tag?

**Comment by NullByte08** [comment]
> It will be included in the required `XML` files, so what will be the good suggested `id` for that `include` tag?

`activity_name_back_arrow_toolbar` for include tag id. And `back_arrow_toolbar` for layout file perhaps?

**Comment by anandwana001** [comment]
Unassigning @NullByte08 as no update.

**Comment by varunvjha** [comment]
I want to work on this issue.

**Comment by rt4914** [comment]
@varunvjha Can you please pick some other issue. There is one PR going on which will create a lot of merge conflicts on the PR you might create. https://github.com/oppia/oppia-android/pull/2296

**Comment by anshbajpai** [comment]
@rt4914 can i work on this ?

**Comment by anshbajpai** [comment]
@rt4914 should this toolbar file also work for the home screen?

**Comment by rt4914** [comment]
> @rt4914 should this toolbar file also work for the home screen?

@anshbajpai Not exactly. The aim is to use this toolbar at maximum places. But considering that this issue is almost 1 year old please check and see will this issue make our codebase better to not.

**Comment by anshbajpai** [comment]
@rt4914 yeah, I did go through the code and observed that. a common toolbar file already exists and is being used in respective activity and fragments

**Comment by rt4914** [comment]
Ack. Closing this issue now.
