### ISSUE TITLE
High-fi Walkthrough

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1012]
Portrait: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/9bb5c0e5-f77e-4c28-8d79-18515d0e9711/WT-Walkthrough-1-3/

Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/2137efb6-6940-498d-8d7d-a8ea87e98410/UP-User-Profile-21/

Otter Image Link: https://drive.google.com/a/google.com/file/d/1Jsjfx2A1RWMr--tcKFH71Igh9pUSqMXP/view?usp=sharing

**Comment by aggarwalpulkit596** [comment]
@rt4914 in the mocks some ui takes up the whole space but that is only feasible for a smaller size phone i've attached screenshots for nexus s and pixel 3 XL.So should i modiy the code so it should look the same in all kind of screen sizes
<img width="376" alt="Screenshot 2020-05-02 at 1 17 45 PM" src="https://user-images.githubusercontent.com/29139786/80858521-51d2fc80-8c77-11ea-9e7e-84f8caea4acf.png">
<img width="301" alt="Screenshot 2020-05-02 at 1 17 59 PM" src="https://user-images.githubusercontent.com/29139786/80858528-5a2b3780-8c77-11ea-83b8-ce05361105f4.png">

**Comment by aggarwalpulkit596** [comment]
@rt4914 ??

**Comment by rt4914** [comment]
> @rt4914 in the mocks some ui takes up the whole space but that is only feasible for a smaller size phone i've attached screenshots for nexus s and pixel 3 XL.So should i modiy the code so it should look the same in all kind of screen sizes
> <img alt="Screenshot 2020-05-02 at 1 17 45 PM" width="376" src="https://user-images.githubusercontent.com/29139786/80858521-51d2fc80-8c77-11ea-9e7e-84f8caea4acf.png">
> <img alt="Screenshot 2020-05-02 at 1 17 59 PM" width="301" src="https://user-images.githubusercontent.com/29139786/80858528-5a2b3780-8c77-11ea-83b8-ce05361105f4.png">

@aggarwalpulkit596 You can write code as per mocks and test it only on `HDPI device` like `Galaxy Nexus` or maybe a Pixel Device. Do not test this for MDPI or LDPI devices.

**Comment by aggarwalpulkit596** [comment]
No i meant like should i use linear layouts with weights so that it takes up the whole UI

**Comment by rt4914** [comment]
> No i meant like should i use linear layouts with weights so that it takes up the whole UI

Actually this entire thing can be done using `ConstraintLayout` so I don't think we need a Linear Layout. Also, if by weight you mean to divide the screen vertically, then that is not efficient. Instead just use the margin/padding provided in the mocks. For example: There is a 16 dp margin between these two items.
 
<img width="425" alt="Screenshot 2020-05-04 at 10 24 04 AM" src="https://user-images.githubusercontent.com/9396084/80937126-75ba4d80-8df1-11ea-94cf-776c0a07c004.png">

**Comment by rt4914** [comment]
@aggarwalpulkit596 Check this out https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by aggarwalpulkit596** [comment]
@rt4914 I've left some comments for the mocks design can you please answer them?

**Comment by BenHenning** [comment]
@aggarwalpulkit596 removing this from you since it's not part of GSoC.

**Comment by BenHenning** [comment]
Note: we're scoping this out of alpha due to technical infeasibility. Also, we have people to help out with onboarding during alpha testing so this isn't as valuable.

**Comment by seanlip** [comment]
Since we are revamping the onboarding process, this issue is obsolete. Closing it.
