### ISSUE TITLE
Tutorial in Exploration

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1014]
Mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/57dac831-0f1d-4f27-b775-9491e2a29bfa/PM-TR-Message-1-

Also, to test the initial steps taken before tutorial you will need to change the launcher activity to `WalkthroughActivity` in manifest file.

Tutorial will be shown for first time users in the app which will start from `WalkthroughFinalFragment`. 
For this feature its fine if we introduce a library given the case that we can show the UI as per our mocks.
For this the first step will be to create a design doc rather than jumping directly into code. You can use this template to create a [design doc](https://github.com/oppia/oppia/wiki/Writing-design-docs) and share it for confirmation.

**Comment by aggarwalpulkit596** [comment]
How we are thinking to make the box for text with the triangle edge? we can try out material design edge treatment for this would be needing some maths skills though

**Comment by aggarwalpulkit596** [comment]
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomappbar/BottomAppBarTopEdgeTreatment.java this can help

**Comment by aggarwalpulkit596** [comment]
@BenHenning should we use the above or it would  9 patch images instead ?

**Comment by seanlip** [comment]
This is replaced by @JishnuGoyal's spotlight implementation. Closing.
