### ISSUE TITLE
Render svg images from Server.

### ISSUE THREAD

**Issue by veena14cs** [oppia/oppia-android#1020]
Introduce support for rendering .svg images from the Server.

**Comment by aggarwalpulkit596** [comment]
We can use glide for this

**Comment by aggarwalpulkit596** [comment]
I've already incorporated this thing in one of my projects and would like to take up this.

**Comment by rt4914** [comment]
@aggarwalpulkit596 @veena14cs has actually already finished this issue and it is in PR now.
