### ISSUE TITLE
Support for <ol> and indentation in HtmlParser

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1022]
Currently, HthmlParser does not support `<ol>` html tag and also nested indentation is also not supported. 
Add support for `<ol>` tags and nested indentation.

Reference for `<ol>` tag support: https://bitbucket.org/Kuitsi/android-textview-html-list/src/master/app/src/main/java/fi/iki/kuitsi/listtest/
Using the above reference you can easily add a tag handler for `<ol>` tag in Html Parser but this does not support indentation.

You will need to work on `utility` module to fix this issue.
For testing this, you can use `HtmlParserTestActivity` along with `faqs` `faq_answer_1` string resource. 
The outcome of this string should be like this:
<img width="367" alt="Screenshot 2020-04-27 at 2 17 38 PM" src="https://user-images.githubusercontent.com/9396084/80353063-6dfb2600-8892-11ea-91f8-7d88332d2585.png">

**Comment by rt4914** [comment]
@veena14cs Can you please prioritise this issue, as it is blocking work items related to FAQ content?

**Comment by BenHenning** [comment]
Given that this is mainly aesthetic and doesn't actually prevent us from displaying understandable content, pushing this to beta.
