### ISSUE TITLE
Exploration back flow is incorrect.

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1024]
Exploration can be opened from places:
1. Recently Played Stories
2. Topic-Lessons-Chapter Name
3. StoryActivity -> Chapter Item

All these different flows open exploration, but on click on back button, it should always open `TopicActivity` only. This has been implemented but now there seems inconsistency in that.

For example:
1. Go to Ratios topic - Lessons tab - expand an item and open exploration. Leave the exploration. You will notice two issues:
- (a.) Info tab is visible but ideally Lessons tab should be visible.
- (b.) Click on back again, you will see TopicActivity with Lessons Tab and the story list is duplicated.

2. Go to Ratios topic - Lessons tab - Click on Item to open `StoryActivity` (chapters with images). Open exploration. Leave exploration. Now you will notice `TopicActivity` appears which is correct. Click on back on this screen and you will see `StoryActivity` and click back again and you will see `TopicActivity`. This should not happen.

**Comment by rt4914** [comment]
@SayantanBanerjee16 PTAL at this issue, and if you think this can be your next work item, please self assign it.

**Comment by Sarthak2601** [comment]
@rt4914 Can I work on this ?

**Comment by rt4914** [comment]
> @rt4914 Can I work on this ?

@Sarthak2601 Yeah Sure. Thanks. @SayantanBanerjee16 I have assigned this issue to Sarthak for now.

**Comment by Sarthak2601** [comment]
@rt4914 Thanks !
