### ISSUE TITLE
Move app module test targets to the non-flaky queue in CircleCI [Blocked: #973]

### ISSUE THREAD

**Issue by vinitamurthi** [oppia/oppia-android#1028]
Currently there are several app module tests that are failing in robolectric. Due to this we have created a flaky_queue and a non_flaky_queue. We would like to fix all the app tests in robolectric so that we can move the app module tests to the non-flaky queue.
We will do this folder by folder for the app module tests, until we can move the entire app module.
The following folders need to be migrated:

- [ ] administratorcontrols

- [ ] completedstorylist

- [x] faq

- [x] help

- [ ] home

- [x] mydownloads

- [ ] onboarding

- [ ] ongoingtopiclist

- [ ] options

- [x] parser

- [ ] player

- [ ] profile

- [x] profileprogress

- [x] recyclerview

- [ ] settings/profile

- [x] splash

- [x] story

- [ ] testing

- [ ] topic

- [x] utility

- [ ] walkthrough

Blocked by #973

**Comment by veena14cs** [comment]
@vinitamurthi Splash and faq testcases are passing in roboelectric.

**Comment by veena14cs** [comment]
@vinitamurthi help testcases are passing in roboelectric.

**Comment by anandwana001** [comment]
@vinitamurthi can we update this issue? 
I guess we had shifted all the app module test cases to Non-Flaky!!
`sudo ./gradlew --full-stacktrace :app:testDebugUnitTest`

**Comment by vinitamurthi** [comment]
Yes thanks for pointing it out! Closing this
