### ISSUE TITLE
High-fi Reset Pin Margin Issue fix

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1040]
Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/6f83fcd9-e72d-4941-a16f-6754a869e083/RG-MN-Register-Empty-37/

If we scroll the layout in the mock, there is bottomMargin for the `Save` button. This issue is to make sure that margin is added in code.

Comment Reference: https://github.com/oppia/oppia-android/pull/1034#discussion_r417931326

**Comment by prathameshbhalekar** [comment]
I am looking for mi first open source contribution. Can i  work on this issue?

**Comment by aggarwalpulkit596** [comment]
This is already fixed @prathameshbhalekar can you try working on something else

**Comment by rt4914** [comment]
> I am looking for mi first open source contribution. Can i work on this issue?

Thank you for showing interest. First there are couple of steps which needs to be done before we can assign you some issues to work on:
[wiki](https://github.com/oppia/oppia-android/wiki) - This will help you in setting up the project and once you sign the CLA and fill the survey form we will assign you issues to work on.
