### ISSUE TITLE
Hints & solution revealed states should only affect ephemeral state

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1049]
When working on #500, I noticed that whether a hint is revealed is part of the actual State Hint/Solution structure. Those structures should be read-only since they're going to be stored on disk.

We should be storing temporary state like whether something has been revealed as part of the ephemeral state, not the persistent version of the state.

**Comment by rt4914** [comment]
@BenHenning This can be part of Milestone 3 mentioned in this [document](https://docs.google.com/document/d/1QSEzBhh_V7dtdnIs2kG2tRgADjBoYEPMzvvuwr0NjFc/edit?usp=sharing), what are your thought?

**Comment by BenHenning** [comment]
That seems reasonable to me.

**Comment by BenHenning** [comment]
This was resolved in #3668 with the introduction of https://github.com/oppia/oppia-android/blob/develop/domain/src/main/java/org/oppia/android/domain/hintsandsolution/HintHandler.kt and changes to the proto structure (all ephemeral hint/solution state is now part of a consolidated HelpIndex that's passed in EphemeralState).
