### ISSUE TITLE
Audio voiceovers will continue to play even after disabling them in some cases

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1054]
Repro steps:

1) Open exploration that has voiceover support
2) Enable audio playback
3) Wait for long audio to start being read out
4) Disable audio & quickly continue to the next state (probably requires an exploration with an initial 'Continue' interaction state)

Expected: audio should stop once the new state is loaded

Observed: audio continues playing on the next state despite the audio bar indicating it's disabled (though navigating away from that second state stops audio)

**Comment by rt4914** [comment]
Closing as this is duplicate issue. #1801
