### ISSUE TITLE
High-fi Profile Chooser Portrait UI

### ISSUE THREAD

**Issue by veena14cs** [oppia/oppia-android#1060]
Fix UI double line on Profile chooser page when no profile is added yet.

### Mock Reference
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/8cdde1f8-daae-438c-8fdd-084e5d227080/PC-SP-Profile-Chooser-v2

![Screenshot_20200512-115753](https://user-images.githubusercontent.com/16301028/81646270-949b8e00-9448-11ea-9188-ada9f21e9bfa.png)

**Comment by sajalasati** [comment]
@veena14cs I think this issue has already been resolved. I was using just using the latest version of the app and found that this particular extra line has been removed. You can check it too.

**Comment by rt4914** [comment]
Closed via #1254 & #1270
