### ISSUE TITLE
Introduce checkpointing

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1069]
Currently learner cannot save partial progress of an exploration. Introduce a mechanism through which whenever learner leaves the exploration in between the application should save the partial progress and whenever that exploration is visited again, start from where they left from.

**Comment by BenHenning** [comment]
This seems to be describing checkpointing which is a project we've started to spec out on web.

**Comment by viktoriias** [comment]
@rt4914 @BenHenning Can I work on this?

**Comment by rt4914** [comment]
@viktoriias  This will need discussion with @BenHenning and need to come up with possible solutions. Overall its almost a mini-project. You can start an email thread to start gathering information if interested.

**Comment by Victor-Titan** [comment]
> @Victor-Titan This will need discussion with @BenHenning and need to come up with possible solutions. Overall its almost a mini-project. You can start an email thread to start gathering information if interested.

@rt4914 I think you meant to tag @viktoriias ?

**Comment by rt4914** [comment]
Thanks @Victor-Titan . Updating my above comment for clarification.

**Comment by BenHenning** [comment]
We don't have a label for this at the moment, but this is actually a full project that will need a design document.

**Comment by BenHenning** [comment]
So for the sake of managing long-term projects, closing this now that lightweight checkpointing has been fully implementing. We may want to implement "full checkpointing" for parity with web in the future, but it's not currently on our roadmap.
