### ISSUE TITLE
Duplicate items are generated in the list in Lessons tab.

### ISSUE THREAD

**Issue by veena14cs** [oppia/oppia-android#1070]
When you play `Prototype Exploration` inside topic `First Topic`, after finishing exploration when you click  on `Return to Topic`. It reloads Lesson tab with duplicate items in the list.

![Screenshot_20200515-125416](https://user-images.githubusercontent.com/16301028/82024175-fceaa980-96ac-11ea-9c72-e043eb6ee326.png)

**Comment by rt4914** [comment]
Closing this issue as it is similar to #1024 on which @Sarthak2601 is working.
