### ISSUE TITLE
[Master tracking bug] [GSoC'20] Implement tablet support

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1075]
See https://github.com/oppia/oppia/wiki/Google-Summer-of-Code-2020#41-support-tablet-interfaces for the project details.

**Comment by BenHenning** [comment]
/cc @vinitamurthi 

@MohamedMedhat1998 can you add a link here to your finalized proposal once it's available?

**Comment by MohamedMedhat1998** [comment]
@BenHenning Of course!
Once @rt4914 approves it, I'll share the link.

**Comment by MohamedMedhat1998** [comment]
That is the link: https://docs.google.com/document/d/1axqaUsv8zQ1rtEv-mwS8HafZ8hVGBOsqeVfLnqkI8kw/edit
(Not reviewed yet)

**Comment by MohamedMedhat1998** [comment]
@rt4914 Thanks for the review
@BenHenning The proposal is ready now in the [same link](https://docs.google.com/document/d/1axqaUsv8zQ1rtEv-mwS8HafZ8hVGBOsqeVfLnqkI8kw/edit)

**Comment by rt4914** [comment]
> @rt4914 Thanks for the review
> @BenHenning The proposal is ready now in the [same link](https://docs.google.com/document/d/1axqaUsv8zQ1rtEv-mwS8HafZ8hVGBOsqeVfLnqkI8kw/edit)

@MohamedMedhat1998 Please share PDF link only. As per the discussion, the document with only view access will also work. Thanks for updating it.

**Comment by MohamedMedhat1998** [comment]
@BenHenning this card is in _"Awaiting Triage"_ state in [GSoC 2020 4.1: Support tablet interfaces project](https://github.com/oppia/oppia-android/projects/5?fullscreen=true), what should we do in this case?

**Comment by rt4914** [comment]
Closing this as we have finished this GSoC project and rest all tablet work has individual issues filed.
