### ISSUE TITLE
[Master tracking bug] [GSoC'20] Initial analytics support

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1076]
See https://github.com/oppia/oppia/wiki/Google-Summer-of-Code-2020#42-analytics-support for project details.

**Comment by BenHenning** [comment]
/cc @rt4914 

@Sarthak2601 can you add a link here to your finalized proposal once it's available?

**Comment by Sarthak2601** [comment]
[Finalised Proposal - Analytics Support](https://docs.google.com/document/d/1JuVnV9wkRfiRNQ17gvGpglqbh6W-tgDpcqeoU8WRrwM/edit?usp=sharing)

**Comment by rt4914** [comment]
@Sarthak2601 Does this needs to be closed? If not, what's pending and also can you un-assign youself?

**Comment by BenHenning** [comment]
This is complete since the analytics pipeline has been implemented & verified as working.
