### ISSUE TITLE
[Master tracking bug] [GSoC'20] Additional interaction types

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1077]
See https://github.com/oppia/oppia/wiki/Google-Summer-of-Code-2020#43-additional-interaction-types for project details.

**Comment by BenHenning** [comment]
@aggarwalpulkit596 can you add a link here to your finalized proposal once it's available?

**Comment by aggarwalpulkit596** [comment]
Here it is https://docs.google.com/document/d/1DAoYhppqlOVldqZcDemzzg4PRKnELOiWqiG7iMkFiOA/edit?usp=drivesdk

**Comment by aggarwalpulkit596** [comment]
@BenHenning Should I close this? Since there is no bug in the current implementation.

**Comment by seanlip** [comment]
Closing this since there is no TODO here.
