### ISSUE TITLE
Admin Pin hi fi fix 

### ISSUE THREAD

**Issue by nikitamarysolomanpvt** [oppia/oppia-android#1090]
Admin Pin hi fi fix
https://github.com/oppia/oppia-android/pull/1085#pullrequestreview-414994196
##  Mock
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/acdbeb30-745f-46da-b0fd-3d6a83f83937/PC-SP-Add-PIN-Dialog-Empty-

**Comment by rt4914** [comment]
Closed via https://github.com/oppia/oppia-android/pull/1093
