### ISSUE TITLE
Introduce interface for ExplorationDataController

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#121]
This is tracking introducing a stubbed interface for #113 without the real implementation being complete.

**Comment by BenHenning** [comment]
@vinitamurthi you mentioned that you were interested in working on this.

**Comment by BenHenning** [comment]
FYI @vinitamurthi we are planning to get this checked in by EOW. Please let me know if that's not feasible.

**Comment by vinitamurthi** [comment]
For now, a getExplorationById() should be sufficient

**Comment by BenHenning** [comment]
For references look at #177 and #174 for how to stub & test similar controllers.

**Comment by BenHenning** [comment]
For the stub, maybe we could pull in some of the demo explorations from the file system: https://github.com/oppia/oppia/tree/develop/data/explorations. We could convert a few of these over to JSON and include them in the app.
