### ISSUE TITLE
HighFi : Drag Drop Interaction

### ISSUE THREAD

**Issue by aggarwalpulkit596** [oppia/oppia-android#1224]
Hifi Drag-drop interaction which includes improving the view aspects and polishing the drag-drop functionality

**Target PR date**: 3 June 2020
**Target completion date**: 6 June 2020

**Comment by BenHenning** [comment]
@aggarwalpulkit596 what work is needed here that's not part of #1223?

**Comment by aggarwalpulkit596** [comment]
Just that border outline of the dragged item and some translation of element moving nothing else
