### ISSUE TITLE
Add ImageRegionSelection case in StateReceiver 

### ISSUE THREAD

**Issue by aggarwalpulkit596** [oppia/oppia-android#1227]
Add testing exploration file with handling rules for Image region selection in StateReciever

**Target PR date**: 8 June 2020
**Target completion date**: 10 June 2020

**Comment by BenHenning** [comment]
@aggarwalpulkit596 should this be moved back to milestone 2? I was assuming it was a stretch to get this done in milestone 1, and since that's wrapping up we should probably move this back.
