### ISSUE TITLE
When navigating to an earlier state, hints & solutions unexpectedly show up

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1252]
Repro:

1) Navigate to a state
2) Wait for a hint bulb to appear (e.g. wait 60 seconds)
3) Navigate to a previous state

Expected: the bulb should disappear OR show the previous state's hints, if any

Actual: the bulb still has an indicator for a new hint, and when pressing it opens an empty hints & solutions list. Navigating back to the latest state causes the correct hints to show up.

**Comment by BenHenning** [comment]
Note that I noticed this in the #500 branch which has some hints & solutions changes. I haven't checked this yet on develop.

**Comment by veena14cs** [comment]
I checked it with develop. And yes when I navigate to previous state, hint bulb is present but doesn't show up the hint list and when I navigate back to the present state it show's its hint list.

**Comment by veena14cs** [comment]
@BenHenning shall I fix this issue in develop?

**Comment by BenHenning** [comment]
Yes please, but can you wait until after #500 is submitted?
