### ISSUE TITLE
Onboarding Screen is not scrollable (Button Hides)

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1255]
`onboarding_slide_final.xml` 
The parent should be something scrollable. On the small screen, button hides under the dots section. 

**I had tested on API 28, 480x800 HDPI res. 
and API 28, 1080x1920 XXHDPI**

![Screenshot_1591352645](https://user-images.githubusercontent.com/25057618/83866286-357a2200-a745-11ea-9f0c-36a3f4470f1f.png)

![Screenshot_1591593900](https://user-images.githubusercontent.com/25057618/83995245-8f156300-a976-11ea-8a16-5bdde780936f.png)

**Comment by MohamedMedhat1998** [comment]
@anandwana001 Can you update the initial comment with the dimensions of the emulator you have used?

**Comment by nikitamarysolomanpvt** [comment]
@rt4914 are we focusing this screen size? We may work around if we know which is the smallest screen size now we are planning to support. @anandwana001 can’t we update the design in such a way that it works in all screen size in stead of scrolling.

**Comment by anandwana001** [comment]
> @rt4914 are we focusing this screen size? We may workaround if we know which is the smallest screen size now we are planning to support. @anandwana001 can’t we update the design in such a way that it works in all screen size instead of scrolling.

Yes, we can definitely do that.

**Comment by rt4914** [comment]
> @rt4914 are we focusing this screen size? We may work around if we know which is the smallest screen size now we are planning to support. @anandwana001 can’t we update the design in such a way that it works in all screen size in stead of scrolling.

@nikitamarysolomanpvt We are actually not working on such screens as we do not have mocks for smaller screens. But of this specific screen, I think we should fix this because if user is not able to click "Get Started" button they won't be able to pass to next screen. I think it should be kept as scrollable for being on safe side and when the screen size is good enough it will automatically work without scroll.

**Comment by rt4914** [comment]
Closed via https://github.com/oppia/oppia-android/pull/1269
