### ISSUE TITLE
Need end-to-end testing for the project

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1266]
Currently we have Roboelectric and Espresso Unit test cases.
We need end-to-end testing to make sure that the app is working smoothing across activities and code-layers.

**Comment by justdvnsh** [comment]
@rt4914 Can I take up this issue ??

**Comment by rt4914** [comment]
@justdvnsh This is actually not a small issue but kind of a big project. Suggest taking some other project. This in overall is part of GSoC this year.

**Comment by BenHenning** [comment]
E2e testing was technically completed during 2021 GSoC. We still need to incorporate these in our CI workflow, and determine how to expand them to cover all the cases that we're interested in, but I think that's worth filing as new issues once we want that.
