### ISSUE TITLE
UI structure: Introduce topic list on home screen

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#134]
This is tracking introducing the activity/fragment/view structures to hook up #117 to prepare for #10.

Two things needs to done in this:

- [x] Make promoted story a caraousel https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/d47aa8de-a7a8-4d25-b011-5baefc7b7098/HP-Home-Page-
(Filed a issue #389 )
- [x] Currently "All Topics" text is not visible below promoted stories - add that as an item. (@rt4914 Check #311 )

**Comment by BenHenning** [comment]
This is blocked on #117.

**Comment by rt4914** [comment]
Reopening this because of design changes

**Comment by rt4914** [comment]
@BenHenning @seanlip 
Currently on HomeFragment PromotedStory is a single tile and not a list, so should we close this issue and raise a new one of should be keep this issue open for now. Also, check issue description too.

**Comment by seanlip** [comment]
I need to defer to @BenHenning on this one, in order to ensure consistency in the scheme for organizing issues on this repo.

**Comment by BenHenning** [comment]
Agreed. I filed #389. This is complete per our original goals.
