### ISSUE TITLE
UI Structure: Topic activity/fragment

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#135]
This is tracking introducing the UI structure for the topic page, including constituent tabs: train, play, overview, and review. This does not track introducing the UIs for each tab. See later in this issue for issues blocking this (4 of them should be the corresponding structure issues for each tab).

See #23 for the issue corresponding to the high-fidelity topic page work.

- [ ] Basic implementation of TopicActivity (@nikitamarysolomanpvt )
- [ ] Click on `PromotedStory` in `Home` should open `TopicPlayFragment` and scroll to a specific story item.

**Comment by BenHenning** [comment]
This is blocked on #118 since the UI structure can't be built until there's a domain interface to consume.

**Comment by rt4914** [comment]
@nikitamarysolomanpvt This issues needs multiple fragments which I have already in #192 . You can now find that in develop too. 

For now, you just have to create 4 tabs which changes those fragments as desired.

Also, check email from Chantel, she has provided those tabs icons in one of her recent emails.

**Comment by nikitamarysolomanpvt** [comment]
> Chantel

I think she forgot to keep me in loop i never got any mails from Chantel.

**Comment by nikitamarysolomanpvt** [comment]
> @nikitamarysolomanpvt This issues needs multiple fragments which I have already in #192 . You can now find that in develop too.
> 
> For now, you just have to create 4 tabs which changes those fragments as desired.
> 
> Also, check email from Chantel, she has provided those tabs icons in one of her recent emails.

Okay
