### ISSUE TITLE
UI Structure: Topic overview tab fragment [Blocked: #135]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#136]
This is tracking introducing the UI structure for the topic overview tab.

**Comment by BenHenning** [comment]
This is blocked on #118 and #135 (since the topic activity and fragment need to be introduced before this tab can be filled out).

**Comment by rt4914** [comment]
@BenHenning PR #233 had title "Fix part of ..." because of introduced of topic-download functionality in subsequent PRs. So I think this issue has been resolved (except the topic-download functionality), should we close this issue?
