### ISSUE TITLE
Topic page load is lagging

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1379]
**Describe the bug**
The topic page lags slightly, causing an early layout to show.

**To Reproduce**
1. Force close the Oppia app

**Contributors working on this should first attempt to repro the issue using the emulator specified below and post a comment with the result.**

**Screenshots**
Slowed down capture:
![oppia_slow_topic_page](https://user-images.githubusercontent.com/12983742/85330324-083dab80-b489-11ea-9092-bc017c84fa4d.gif)

**Device**
- Device: Nexus 5X
- SDK: 29

**Comment by BenHenning** [comment]
Pushing back to be beta blocking, instead.

**Comment by TanishMoral11** [comment]
Hey @BenHenning , this issue is already solved . So kindly close it .

**Comment by adhiamboperes** [comment]
@TanishMoral11, could you please attach proof/ reasoning for your comment?

**Comment by TanishMoral11** [comment]
> @TanishMoral11, could you please attach proof/ reasoning for your comment? 

Yeah Sure[https://github.com/user-attachments/assets/993b4adb-b540-4e48-9b4f-a3e22bbe0627

**Comment by TanishMoral11** [comment]
Yeah Sure !!
https://github.com/user-attachments/assets/49ab4187-556f-4494-af2a-d34a79e41421

**Comment by adhiamboperes** [comment]
@TanishMoral11, your screen recording looks to be from a physical device as opposed to the emulator specified above.

**Comment by TanishMoral11** [comment]
hey @adhiamboperes, Sorry for late reply ..
But here is recording of virtual device ( Nexus 5X )

https://github.com/user-attachments/assets/aaea0d99-7f78-4373-9978-69b435d73591

**Comment by adhiamboperes** [comment]
Closing this as unreproducible.

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes ,  I noticed that the issue #1379 regarding the topic page load lag was closed an hour ago, but it has been assigned to me now. Could you please clarify if there's any further action needed on this issue? I just want to make sure I’m addressing the right concerns
Thanks !

**Comment by adhiamboperes** [comment]
Apologies - no further action required at this time.
