### ISSUE TITLE
Show confetti when learners get the answer correct

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1381]
Similar to Oppia web, we should show a brief confetti animation when users get an answer correct for both questions and inside of an exploration.

**Comment by prayutsu** [comment]
@BenHenning Can we use a third-party library for this?

**Comment by BenHenning** [comment]
@prayutsu it depends on the library. Did you have one in particular in mind?

**Comment by prayutsu** [comment]
May be [this](https://github.com/DanielMartinus/Konfetti)

**Comment by prayutsu** [comment]
@BenHenning Or we can go for Lottie

**Comment by BenHenning** [comment]
Ah, I've worked with Lottie before. Some concerns that come from it:
1. It's not very efficient on low-end devices (and I don't think it's meant to be)
2. It has a higher bar for entry to create animations (I think it requires Adobe Illustrator, but I suspect some open source editors might be viable)

It might be worth looking into if we had a lot of animations to add, but if it's only the confetti I think we should consider a native Android solution first and move toward a library if that's not feasible.

What do you think @prayutsu?

**Comment by prayutsu** [comment]
@BenHenning Sure, we could do that, but I managed to find [this](https://stackoverflow.com/questions/46782836/i-need-particle-animation-for-android-with-images-of-our-own-instead-of-canvas). Please check it out.
I am suggesting first solution of this link.

**Comment by BenHenning** [comment]
Thanks @prayutsu. To clarify, which specific solution are you proposing from that stackoverflow question, or are you suggesting that we should consider each of the proposed solutions?

**Comment by viktoriias** [comment]
@BenHenning Can we show a gif with transparent background?

**Comment by Mehul-Bisht** [comment]
@BenHenning @FareesHussain I can try either designing a custom animation for this using the object animator or converting the layout to a motion layout to define that transition.

**Comment by FareesHussain** [comment]
> @BenHenning @FareesHussain I can try either designing a custom animation for this using the object animator or converting the layout to a motion layout to define that transition. 

@Mehul-Bisht as there is a ongoing pr for this we can't assign this to you
