### ISSUE TITLE
Chat Bubble Width Different

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1386]
**Describe the bug**
While answering the questions in prototype exploration, sometimes the width of the bubble with the same text are different. Sometimes in the case where we show and hide the previously given answer. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open ` Prototype Exploration` or it says `First Topic`.
2. Give a few answers wrong
3. Click on show previous responses and compare the width of other responses on the screen.

**Expected behaviour**
Width of the same content/text/bubble should be the same

**Screenshots**
![Screenshot](https://lh3.googleusercontent.com/-E8WG5gMLM0M/XvGK1yTVCvI/AAAAAAAAuwk/Dj-B2THkY60NmpOpEq5eTV-_FJ7o3o-mwCK8BGAsYHg/s0/Screenshot_1592828855.png)
![Screenshot_2020-06-23-14-04-08-985_org oppia app](https://user-images.githubusercontent.com/25057618/85380475-9b92e180-b55a-11ea-978c-53ef25b416a2.jpg)
![Screenshot_2020-06-23-14-03-48-851_org oppia app](https://user-images.githubusercontent.com/25057618/85380505-a3eb1c80-b55a-11ea-8492-153aa52687a3.jpg)

**Device**
- Device/emulator being used
- API 28

**Comment by BenHenning** [comment]
@mschanteltc do you have any thoughts on the bug described here? Should the message bubbles in the exploration player wrap the content, be a fixed size, or some combination of the two? I'm concerned that some content simply won't fit if we fix the size, but I can see how the shrink-to-fit implementation here might look a bit off with multiple answers submitted.

**Comment by mschanteltc** [comment]
> @mschanteltc do you have any thoughts on the bug described here? Should the message bubbles in the exploration player wrap the content, be a fixed size, or some combination of the two? I'm concerned that some content simply won't fit if we fix the size, but I can see how the shrink-to-fit implementation here might look a bit off with multiple answers submitted.

For the question or first bubble of each exploration page, let's have a fixed width. Everything else such as the user responses or feedback would use bubbles that wrap the content. Would this cause any issues?

**Comment by imraghav20** [comment]
@anandwana001 I am interested in working on this issue.
Also, should I go with the approach as mentioned by @mschanteltc in previous comment? Even I agree with his approach.

**Comment by rt4914** [comment]
> @anandwana001 I am interested in working on this issue.
> Also, should I go with the approach as mentioned by @mschanteltc in previous comment? Even I agree with his approach.

@imraghav20 Yeah you can follow the approach mentioned by @mschanteltc

**Comment by rt4914** [comment]
Assigned to @imraghav20

**Comment by imraghav20** [comment]
What should be the fixed width given? Is `240dp` good?

**Comment by anandwana001** [comment]
> For the question or first bubble of each exploration page, let's have a fixed width. Everything else such as the user responses or feedback would use bubbles that wrap the content. Would this cause any issues?

@imraghav20 If I am not misunderstanding what @mschanteltc means here is the first bubble or question are the same thing, so all the other bubbles should have a wrap content width.

**Comment by imraghav20** [comment]
> > For the question or first bubble of each exploration page, let's have a fixed width. Everything else such as the user responses or feedback would use bubbles that wrap the content. Would this cause any issues?
> 
> @imraghav20 If I am not misunderstanding what @mschanteltc means here is the first bubble or question are the same thing, so all the other bubbles should have a wrap content width.

But, when I saw the source code, all the bubbles are already in `wrap-content`.
Here are the required files:
https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/layout/content_item.xml
https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/layout/feedback_item.xml

**Comment by anandwana001** [comment]
That's the issue, we need to figure out why the bubble is getting different width on screen.

**Comment by chrk2205** [comment]
@anandwana001 
I tried to reproduce this bug in my emulator but its not showing it !!
-tried in emulator Pixel 3 and normal mobile One Plus 6
can you please check if the the bug still pertains!!
Thanks

**Comment by anandwana001** [comment]
Yes, it looks fixed now. Closing this issue. Thanks for the update.
