### ISSUE TITLE
Show terms of service & privacy policy notices

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1390]
We should show links to the Oppia terms of service & privacy policy in each of the following circumstances:
- When a user logs into an account
- When a user creates a new profile & logs in for the first time (this is targeting the user who is using the profile)
- When a user opens the navigation drawer

In places where a user is signing in, we should make it clear that they are agreeing to the TOS & privacy policy when signing into their account & using the app.

**Comment by KolliAnitha** [comment]
Terms of service and Privacy policy is seen on logging in for the first time, Navigation bar
![Screenshot_2022-09-10-11-08-42-43_943a62cb4c6fb83e010e1c2e82766a17](https://user-images.githubusercontent.com/101634267/189470808-7135024e-993e-4dfb-9e55-84742573622e.jpg)
![Screenshot_2022-09-10-11-05-01-83_943a62cb4c6fb83e010e1c2e82766a17](https://user-images.githubusercontent.com/101634267/189470811-a7b33e66-6547-4a15-9dd8-a50ea5e278c0.jpg)
