### ISSUE TITLE
High-Fidelity work of Hints & Solution

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1394]
This issue is tracking the high-fi work of Hints & Solutions.

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/12c7159f-4c16-4c89-8311-59963c28c1e4/LM-Q5-HS-Hint-Dialog-Close-Hint-1-

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/e30e2de3-c9ad-429f-afc6-a39a2f67ef1b/LM-Q5-HS-Hint-Dialog-Opened-Hint-4-

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/ec19a6df-bfa1-4096-8c13-ad1192900185/LM-Q5-HS-Solution-Notification-Dot-End-

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/5362a633-73cb-4288-aa7d-8c69e4eef349/LM-Q5-HS-Hint-Dialog-Reveal-Solution-

## Landscape:
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/bc5aeca3-c985-4ea0-a42e-656f97ebd9f7/PM-Q2-IA-Answered-1-8

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/75c1e22e-bc57-4ad4-8e66-971698ad86aa/PM-Q2-IA-Answered-1-9

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/901ca209-3a2f-4543-9f8a-532828e55d8a/PM-Q2-IA-Answered-1-10

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/14cfec58-ebfa-488c-85d2-e3f8e9b1b5c3/PM-Q2-IA-Answered-1-11

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/33301d70-de88-4422-a3c2-695e1e28b944/PM-Q2-IA-Answered-1-12

**Comment by rt4914** [comment]
This issue has been finished and only the animation part is pending, which will be finished by Mohamed as part of his work. Keeping this open just to keep track of things.

**Comment by BenHenning** [comment]
@rt4914 can we move this to Mohamed's M3 milestone to track the remaining work, or split up accordingly?

**Comment by rt4914** [comment]
Closing this since the Highfi work was already finished by @veena14cs and @MohamedMedhat1998 . The only thing pending in this is animation, which will be done in https://github.com/oppia/oppia-android/issues/1539
