### ISSUE TITLE
Per-profile data storage system

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#14]
Individual profiles will need to have data associated with them directly. Such data requires a system to organize other file I/O systems based on the current profile that's selected. This system should interop directly with the other I/O systems described above rather than reimplement them. One possible manifestation of this might be a series of providers for the other I/O systems based on profile ID.

Note that this system is not responsible for managing the current profile logged in, though it should be designed with per-profile Takeout/Wipeout in mind.

**Comment by BenHenning** [comment]
This involves changing the sqlite and the persistent cache system. For that reason, this is blocked by #12 and #7.

**Comment by BenHenning** [comment]
NB: This is not blocked on #12 since for the prototype only the proto-based cache store is used for storage, so only that needs to be made per-profile.

**Comment by BenHenning** [comment]
This issue includes adding per-profile support for existing essential data stores, such as #14 and #15.

**Comment by rt4914** [comment]
@BenHenning Is this done ? Or can anyone work on this?

**Comment by BenHenning** [comment]
This is finished: https://github.com/oppia/oppia-android/blob/develop/data/src/main/java/org/oppia/android/data/persistence/PersistentCacheStore.kt#L308.
