### ISSUE TITLE
Follow ups on Github actions

### ISSUE THREAD

**Issue by vinitamurthi** [oppia/oppia-android#1407]
Github actions doesn't have a few features so we should add scripts to do the following:

- [x] Auto cancel redundant builds (We could potentially use an [existing action](https://github.com/technote-space/auto-cancel-redundant-job) for this)

- [x] Upload readable versions of the gradle test run reports. Right now they are in their default XML format but we could potentially upload it with the stacktrace

- [x] Consolidate some of the commands in the actions yaml into scripts instead so that it can be used in other places, and tested locally as well

**Comment by anandwana001** [comment]
@BenHenning I din't remember the PR, but I think we do have `Auto cancel redundant builds` in one of your ongoing PR?

**Comment by BenHenning** [comment]
I think we've done all of these at this point (though the last point we could do more of, but the current same-repo actions are very limited so there's not a lot we can do there at the moment).
