### ISSUE TITLE
App module tests not passing on Espresso

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1424]
**Describe the bug**
The test files in #1276 and #1420 run only on Robolectric and should pass in espresso as well.

**To Reproduce**
1. Pull any one of #1276 or #1420
2. Go to the test files present at `/Users/sarthak/Development/oppia-android/app/src/test/java/org/oppia/app`
3. Run the tests on Espresso.

**Expected behavior**
These kind of tests should run on robolectric as well as espresso.

**Screenshots**
![Screenshot 2020-06-29 at 8 23 00 AM](https://user-images.githubusercontent.com/53938155/85972499-d16a1700-b9ed-11ea-9d06-438d5770293f.png)

**Device**
- Emulator - Google Pixel 3 XL 
- SDK version - 28

**Comment by aggarwalpulkit596** [comment]
They are meant to be run on roboelectric only and not on espresso

**Comment by aggarwalpulkit596** [comment]
This exception which you're getting is just because of a build issue i guess, just rebuild your project

**Comment by vinitamurthi** [comment]
To be clear, tests in app/src/test should run only on robolectric. The main point of this issue is to get these kinds of tests (Tests where we fake out certain parts) running on espresso as well. I am not entirely sure if this is possible, this will need to be investigated a bit.

**Comment by BenHenning** [comment]
Given that this test isn't supposed to work on Espresso, this is working as intended. Thanks for filing @Sarthak2601!
