### ISSUE TITLE
Final UI: Topic review tab fragment [Blocked: #15, #142]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#143]
This is tracking implementing the high fidelity UI for the topic review tab.

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/1adacef0-f245-4115-a0e0-d1c2e7d5a0bb/TP-Revision-/

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/dad2a9ff-ce33-4f00-894a-ec07dbb12797/TP-Revision-

**Comment by BenHenning** [comment]
This is blocked on #142 for structure and #15 for full domain functionality.

**Comment by rt4914** [comment]
Opening this again as the design needs to be updated as per version v7.

**Comment by rt4914** [comment]
Assigning this to @Luffy18346
