### ISSUE TITLE
Incorrect answers in Prototype exploration

### ISSUE THREAD

**Issue by aggarwalpulkit596** [oppia/oppia-android#1432]
In Prototype exploration, the 7th and 8th questions have a theoretically wrong answer.
Right now correct answer is 
`3/5 0.5 0.35 0.46`
whereas it should be 
`3/5 0.5 0.46 0.35`

**Comment by aggarwalpulkit596** [comment]
@vinitamurthi @rt4914 should I fix this?

**Comment by BenHenning** [comment]
@aggarwalpulkit596 & @MohamedMedhat1998 is this fixed now?

**Comment by aggarwalpulkit596** [comment]
Yep

**Comment by aggarwalpulkit596** [comment]
Closing via #1469

**Comment by MohamedMedhat1998** [comment]
> @aggarwalpulkit596 & @MohamedMedhat1998 is this fixed now?

yes
