### ISSUE TITLE
Final UI: ReturnToTopicDialogFragment

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#144]
There needs to be a dialog fragment that's used to confirm that the user really wants to return to the topic from various locations within the topic. This dialog work can be done at any time, but it needs to be hooked up in all the correct places per the mocks.

Mock: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/40d6cf5f-f673-42c8-af15-035f711ef6b9/PM-IN-Introduction-

## Checklist
- [x] Low-fi to go to TopicActivity from ExplorationActivity (@rt4914 PR #317 )
- [ ] Low-fi to go to TopicActivity from QuestionActivity
- [x] High-fi work: Matching UI with mocks. (@rt4914)

**Comment by rt4914** [comment]
This has been finished as a part of #500
