### ISSUE TITLE
Drag & drop drag state resets after an incorrect answer

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1468]
**Describe the bug**
When using the drag & drop interaction, an incorrect answer results in the same drag state being shown.

**To Reproduce**
1. Start the Prototype Exploration on a dev build of the app
2. Play through it until the first drag & drop state
3. Drag the items to produce an incorrect answer
4. Submit the answer
5. Observe that the drag & drop order resets back to the original state

**Expected behavior**
The drag & drop order should stay the same after the incorrect answer.

**Screenshot**
![oppia_drag_drop_not_retaining_state](https://user-images.githubusercontent.com/12983742/87351606-846a6280-c50e-11ea-90b2-36d2d6757410.gif)

**Device**
- Device: Pixel XL
- SDK: 29

## Additional Information

Comment https://github.com/oppia/oppia-android/issues/1468#issuecomment-669301671 was addressed in https://github.com/oppia/oppia-android/pull/5478.

**Comment by BenHenning** [comment]
As discussed, since this needs to apply to all interactions we're not blocking M2 on this work item.

**Comment by BenHenning** [comment]
This probably also happens during configuration changes.

**Comment by anandwana001** [comment]
@aggarwalpulkit596 still working on this?

**Comment by aggarwalpulkit596** [comment]
This was something a bit out of scope with the current implementation of interactions and viewmodels. It won't be possible unless we move to hilt or something better.

**Comment by BenHenning** [comment]
I think we're solving this for the other interactions using a singleton that retrieves state from the assembler. See #2514 for specifics. @FareesHussain do you think that approach could work here?

**Comment by BenHenning** [comment]
Deassigning you @aggarwalpulkit596 since it seems that you're not actively working on this.

**Comment by FareesHussain** [comment]
> I think we're solving this for the other interactions using a singleton that retrieves state from the assembler. See #2514 for specifics. @FareesHussain do you think that approach could work here?

I'm not sure here, so far my implementation didn't give any desired result. I've completely forgotten my singleton pr. I will try once again using the setState similar to https://github.com/oppia/oppia-android/pull/2557

**Comment by aggarwalpulkit596** [comment]
@FareesHussain let me know if i can be of any help.

**Comment by adhiamboperes** [comment]
@TanishMoral11, PTAL.

**Comment by Rd4dev** [comment]
_Just adding for reference (not working and not approved):_ 

I tried to get the previous `pendingState.wrongAnswerList` to pass for computing the strings - [Code sample](https://github.com/Rd4dev/oppia-android/pull/14/files). However, I haven't yet figured a way to update the adapter with the same:

1. It always instantly fell back to the empty list, providing the default list since LiveData was gathered asynchronously.
2. To obtain and update the adapter into the content view model.

I’m adding this for future reference as I’m currently considering moving on to another issue.
