### ISSUE TITLE
Bug in Drag and Drop Interaction

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1483]
**Describe the bug**
In Drag and Drop Exploration, if I pin all options and click on submit nothing happens and submit button becomes inactive. 

**To Reproduce**
1. Go to 'ExplorationRetriever'
2. Map `drag_and_drop_test_exploration.json` (or) `test_exp_id_4 ` such that it can be opened from any story.
3. Now, pin all options such that it look similar to the screenshot
4. Click submit
4. See error - > Submit button will become inactive.

**Expected behavior**
Either there should be proper error message or some something to make sure that it does not look incomplete.

**Screenshots**
![Screenshot_1595004646](https://user-images.githubusercontent.com/25057618/87811124-c7fcfd80-c87b-11ea-8b4b-cf41919f48b4.png)

**Comment by aggarwalpulkit596** [comment]
@BenHenning if you remember there was a change in the name of one classifier rule https://github.com/oppia/oppia-android/blob/0b6b6f7f69151aa64a5f996054a01f91f6058f3f/domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputModule.kt#L39 and on the web we are still using the old name as per this json file
https://github.com/oppia/oppia-android/blob/0b6b6f7f69151aa64a5f996054a01f91f6058f3f/domain/src/main/assets/test_exp_id_4.json#L130

**Comment by BenHenning** [comment]
We should ensure web & Android are consistent here, and that all of Android's local files are correct.
