### ISSUE TITLE
Rich text image is cut-off

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1485]
**Describe the bug**

**To Reproduce**
1. Create Nexus-S 25API emulator
2. Run the app
3. Open Ratios Topic
4. Start `Equivalent Ratios` exploration
5. You will see that the content image is cut-off

**Expected behavior**
The rich text image should never get cut-off.

**Screenshots**
![Screenshot_1595010150](https://user-images.githubusercontent.com/9396084/87818799-d0a80080-c888-11ea-96f8-31ad7297d500.png)

**Device**
- Nexus S Emulator
- API 25

**Comment by anandwana001** [comment]
@rt4914  In `UrlImageParser.kt` file, line number 76
Our execution is not entering the if part, and we need to handle the else part. Below is the debug screenshot with the values on Nexus S - 28 API

<img width="1440" alt="Screenshot 2020-07-21 at 18 25 01" src="https://user-images.githubusercontent.com/25057618/88057325-8cb24580-cb7f-11ea-836b-b6803063c896.png">

**Comment by rt4914** [comment]
> @rt4914 In `UrlImageParser.kt` file, line number 76
> Our execution is not entering the if part, and we need to handle the else part. Below is the debug screenshot with the values on Nexus S - 28 API
> 
> <img alt="Screenshot 2020-07-21 at 18 25 01" width="1440" src="https://user-images.githubusercontent.com/25057618/88057325-8cb24580-cb7f-11ea-836b-b6803063c896.png">

It will enter the `if` part only if the image is too small. So the concept of `if` block is that if the image is quite small then we will actually enlarge the image so that it is visible on screen correctly. So that code you are mentioning in this screenshot is actually handling the small size images. But the issue is related to large sized images. So similar to this `if` block there will be another if block in which we first mention the `maximum` image size possible and if the original image is larger than the `maximum` image size possible, then we will make the original image smaller so that it fits the screen.

**Comment by anandwana001** [comment]
> > @rt4914 In `UrlImageParser.kt` file, line number 76
> > Our execution is not entering the if part, and we need to handle the else part. Below is the debug screenshot with the values on Nexus S - 28 API
> > <img alt="Screenshot 2020-07-21 at 18 25 01" width="1440" src="https://user-images.githubusercontent.com/25057618/88057325-8cb24580-cb7f-11ea-836b-b6803063c896.png">
> 
> It will enter the `if` part only if the image is too small. So the concept of `if` block is that if the image is quite small then we will actually enlarge the image so that it is visible on screen correctly. So that code you are mentioning in this screenshot is actually handling the small size images. But the issue is related to large sized images. So similar to this `if` block there will be another if block in which we first mention the `maximum` image size possible and if the original image is larger than the `maximum` image size possible, then we will make the original image smaller so that it fits the screen.

Yes, I was thinking to add else part in this if first, but mentioning the `maximum` image size and using it as a base for comparison will be a good idea. 
How can we determine the `maximum size`?
Currently, we have `minimum_image_size = 48dp`

**Comment by rt4914** [comment]
> > > @rt4914 In `UrlImageParser.kt` file, line number 76
> > > Our execution is not entering the if part, and we need to handle the else part. Below is the debug screenshot with the values on Nexus S - 28 API
> > > <img alt="Screenshot 2020-07-21 at 18 25 01" width="1440" src="https://user-images.githubusercontent.com/25057618/88057325-8cb24580-cb7f-11ea-836b-b6803063c896.png">
> > 
> > 
> > It will enter the `if` part only if the image is too small. So the concept of `if` block is that if the image is quite small then we will actually enlarge the image so that it is visible on screen correctly. So that code you are mentioning in this screenshot is actually handling the small size images. But the issue is related to large sized images. So similar to this `if` block there will be another if block in which we first mention the `maximum` image size possible and if the original image is larger than the `maximum` image size possible, then we will make the original image smaller so that it fits the screen.
> 
> Yes, I was thinking to add else part in this if first, but mentioning the `maximum` image size and using it as a base for comparison will be a good idea.
> How can we determine the `maximum size`?
> Currently, we have `minimum_image_size = 48dp`

I think for now you can use `200dp` and discuss with the team in today's meeting. We can always update this value in future.

**Comment by anandwana001** [comment]
> > > > @rt4914 In `UrlImageParser.kt` file, line number 76
> > > > Our execution is not entering the if part, and we need to handle the else part. Below is the debug screenshot with the values on Nexus S - 28 API
> > > > <img alt="Screenshot 2020-07-21 at 18 25 01" width="1440" src="https://user-images.githubusercontent.com/25057618/88057325-8cb24580-cb7f-11ea-836b-b6803063c896.png">
> > > 
> > > 
> > > It will enter the `if` part only if the image is too small. So the concept of `if` block is that if the image is quite small then we will actually enlarge the image so that it is visible on screen correctly. So that code you are mentioning in this screenshot is actually handling the small size images. But the issue is related to large sized images. So similar to this `if` block there will be another if block in which we first mention the `maximum` image size possible and if the original image is larger than the `maximum` image size possible, then we will make the original image smaller so that it fits the screen.
> > 
> > 
> > Yes, I was thinking to add else part in this if first, but mentioning the `maximum` image size and using it as a base for comparison will be a good idea.
> > How can we determine the `maximum size`?
> > Currently, we have `minimum_image_size = 48dp`
> 
> I think for now you can use `200dp` and discuss with the team in today's meeting. We can always update this value in future.

Sounds Good. Thanks :)
