### ISSUE TITLE
Story Text Size in other learner screens.

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1491]
Currently the story text size change in settings is getting reflected in exploration / `StateFragment` only. But I think it should get reflected in Concept Card as well as Hints & Solution because from user perspective they are also part of exploration only.

## Checklist
- [x] Implement in Hints & Solution
- [x] Implement in Concept Card
- [x] Implement in Question Player
- [x] Revision Card
- [x] Check that it is working on Hints & Solution of Question Player

**Comment by anandwana001** [comment]
Commenting for reference
We can take this issue once we resolve the current bug coming in text size setting from exploration screen. 
https://github.com/oppia/oppia-android/issues/1540

**Comment by anandwana001** [comment]
@rt4914 Based on Ben's comment - https://github.com/oppia/oppia-android/issues/1540#issuecomment-665774109 I think we should shift this issue to beta milestone.

**Comment by alokbharti** [comment]
Hi @rt4914 @anandwana001 , I would like to work on Concept Card screen in this issue.

**Comment by rt4914** [comment]
> Hi @rt4914 @anandwana001 , I would like to work on Concept Card screen in this issue.

@alokbharti Assigned in description.

**Comment by anandwana001** [comment]
@alokbharti any update on this?

**Comment by rt4914** [comment]
Assigned to @FareesHussain as it is blocked on his PR. #2274

**Comment by theMr17** [comment]
As per my findings, text size settings is working fine for _HintsAndSolutionDialogFragment_ inside an exploration. But this needs to be implemented for hints and solutions of question player.

https://github.com/oppia/oppia-android/assets/84731134/b6fe3bec-9133-4743-ac82-72c18b054106

**Comment by Rd4dev** [comment]
Hi @adhiamboperes, the existing implementation successfully updates the concept card text size along with changes in the reading text size, and I have included the recording for your reference. Is there anything specific that I may have overlooked or that still needs updating regarding the concept cards?

**Asset:**

https://github.com/oppia/oppia-android/assets/122200035/5684a244-df04-4edc-a29e-e5b92ecbd5a3

**Comment by adhiamboperes** [comment]
Thanks for testing this @theMr17 and @Rd4dev!

The only part of this left is to verify the  text size in question player, but this isn't in use at the moment.

**Comment by theMr17** [comment]
> The only part of this left is to verify the text size in question player, but this isn't in use at the moment.

I had tested that part as well by changing feature flag values. The text size in question player is not in sync with the settings.

**Comment by adhiamboperes** [comment]
Thanks @theMr17!

**Comment by Vishwajith-Shettigar** [comment]
This issue similar to https://github.com/oppia/oppia-android/issues/4362, Updating [PR](https://github.com/oppia/oppia-android/pull/5290) to fix this issue.
