### ISSUE TITLE
Remove kt_download_local_dev_dependencies() from WORKSPACE file once rules_kotlin() is released

### ISSUE THREAD

**Issue by miaboloix** [oppia/oppia-android#1535]
**Is your feature request related to a problem? Please describe.**
In order for Bazel to properly build Oppia Android, `rules_kotiln` must support data-binding. The current release of `rules_kotlin` does not include https://github.com/bazelbuild/rules_kotlin/pull/346, which adds this necessary support. Thus, we have created our own fork of `rules_kotlin` (https://github.com/oppia/rules_kotlin) and released this fork (https://github.com/oppia/rules_kotlin/releases/tag/legacy-1.4.0-rcx-oppia-exclusive-rc01) in order to import the most recent version of `rules_kotlin` in Oppia Android's WORKSPACE file. However, in doing this, it has become clear that our release is missing certain dependencies that the official `rules_kotlin` release includes. In order to include those dependencies, we added the following lines to our WORKSPACE file:
`load("@io_bazel_rules_kotlin//kotlin:dependencies.bzl", "kt_download_local_dev_dependencies")`
`kt_download_local_dev_dependencies()`

However, once `rules_kotlin` releases a  version with data-binding support, these lines will not be necessary. 

**Describe the solution you'd like**
Once `rules_kotlin` releases a version with data-binding support, we should delete the two lines mentioned above.

**Comment by FareesHussain** [comment]
@miaboloix 
I would like to work on this as the above mentioned pull request is merged and released a version [bazelbuild / Kotlin Rules 1.5.0 (Alpha 2)](https://github.com/bazelbuild/rules_kotlin/releases/tag/v1.5.0-alpha-2)
![image](https://user-images.githubusercontent.com/54740946/103621273-f4582380-4f5a-11eb-9596-10353ce25079.png)

**Comment by BenHenning** [comment]
Hey @FareesHussain. I think @jcqli might be working on this as part of #2431.

**Comment by FareesHussain** [comment]
> Hey @FareesHussain. I think @jcqli might be working on this as part of #2431.

Sure, I did'nt notice that miaboloix was already assigned

**Comment by aggarwalpulkit596** [comment]
@BenHenning this is done right?

**Comment by aggarwalpulkit596** [comment]
I mean the underlying work for this has been done we just need to remove the local dependency from workspace file now

**Comment by jcqli** [comment]
> I mean the underlying work for this has been done we just need to remove the local dependency from workspace file now

@aggarwalpulkit596 Removing `kt_download_local_dev_dependencies()` gives an error that `@com_google_protobuf//:javalite_toolchain` can't be found. `@com_google_protobuf` should be coming from our [rules_kotlin](https://github.com/bazelbuild/rules_kotlin/blob/69159daf2b49746706e2497e2fd272afe8a9afee/kotlin/internal/repositories/download.bzl#L52) so it might be an ordering issue, but in the current state we'll need to keep `kt_download_local_dev_dependencies`.

**Comment by rt4914** [comment]
@jcqli Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by BenHenning** [comment]
(Closing to trigger the TODO workflow).
