### ISSUE TITLE
"Tick Icon" in the QuestionPlayer disappears if the submitted answer is too long

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#1538]
**Describe the bug**
In the QuestionPlayer, the "Tick Icon" appears when the submitted answer is correct. But if the submitted answer TextView is long enough to fill its parent, it pushes the "Tick Icon" off the borders of its parent. So, it disappears.  

**To Reproduce**
1. Go to "Topic/Fractions/Practice"
2. Select the first 3 skills then click start
3. Play the questions till you reach "Amir says the shaded black ..." 
4. Select the correct answer "No, Amir needs to divide ..."
5. Notice that the "Tick Icon" doesn't appear.

**Expected behavior**
The "Tick Icon" should appear and the TextView width shouldn't push it off the layout.

**Screenshots**
![screenshot-2020-07-29_08 12 36 241](https://user-images.githubusercontent.com/8533363/88767487-fd59f300-d179-11ea-8e70-a3ae1bfd4a20.png)

**Device**
- Google Pixel C
- SDK version 25

**Comment by prayutsu** [comment]
@MohamedMedhat1998 I would like to take up this issue
