### ISSUE TITLE
GaeSolution's 'correct_answer' field should be 'Any?' instead of 'String?'

### ISSUE THREAD

**Issue by miaboloix** [oppia/oppia-android#1547]
**Is your feature request related to a problem? Please describe.**
According to [state_domain.py](https://github.com/oppia/oppia/blob/develop/core/domain/state_domain.py#L324), `correct_answer` in GaeSolution.kt should not be typecast as 'String' but as 'Any'.  

**Describe the solution you'd like**
The type declared in `GaeSolution.kt` for `correct_answer` must be changed to `Any?`. On top of this, in `exploration.proto` we must cast `correct_answer` to be an InteractionObject and must change `StateRetreiver.kt` in order to parse the field correctly.

**Comment by seanlip** [comment]
Actually, it should be cast to a union of possible answer types -- Any is a bit broad. Note that the typing in Oppia-Web (see link in the issue description) has been made stricter since this issue was filed.

**Comment by BenHenning** [comment]
This will actually become obsolete in #4885 because that will be removing the JSON endpoints from the app proper and basically shift the app entirely over to using protos only (which also are a bit non-specific in terms of solution typing, but that's fully fixed in https://github.com/oppia/oppia-proto-api/pull/1).

**Comment by seanlip** [comment]
@BenHenning #4885 is closed, is that intended?

Also, based on your comment, can we just close this issue, or add "Fix #1547" to the PR title of #4885 if we still want to keep it open?

**Comment by BenHenning** [comment]
@seanlip #4885 will be reopened once I have time to focus on it again, but I won't lose track of it (I'd rather not keep it open only to have Oppiabot close it again, though; currently load-balancing 7 PRs & counting).

I added a reference in the PR to this issue, and I will for sure update it once I finalize the PR to make it more clear (as I've done with past issues).

**Comment by seanlip** [comment]
OK, just having the reference is good enough so that this gets auto-closed at the right time. Thanks!
