### ISSUE TITLE
UI Structure: EndExplorationInteractionView [Blocked: #150]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#157]
This is tracking implementing the initial UI structure of the continue interaction being fully implemented in #35.

**Comment by BenHenning** [comment]
This is blocked on #118 for interaction with the domain layer, and #150 for the initial interaction UI structure.

**Comment by rt4914** [comment]
@BenHenning I think this has been finished but because both #156 and #157 were fixed together so only #156 was closed by github. 

Should be close this?

**Comment by rt4914** [comment]
Finished in #251
