### ISSUE TITLE
In `StoryTextSize` Options change font size to multiplier factor

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1584]
In Exploration we use `StoryTextSize` value as a multiplier, like if the font size is 18f and user preference is `StoryTextSize.SMALL_TEXT_SIZE`, we multiple the font size with 0.8f (18f * 0.8f) but in `StoryTextSizeActivity / Fragment` we are setting it to  `16f` directly. This needs to be changed to make sure that we are using multiplied factor in `StoryTextSizeActivity` also.

Reference for correct implementation: https://github.com/oppia/oppia-android/blob/892a0c36e6ea771e915059f79075f395e79aa704/app/src/main/java/org/oppia/app/utility/FontScaleConfigurationUtil.kt#L11

**Comment by rt4914** [comment]
I think, this does not affect the `Alpha` milestone a lot therefore adding this to `Beta` but if time allows, we should fix this.

**Comment by prayutsu** [comment]
@rt4914 I would like to work on this issue.

**Comment by aggarwalpulkit596** [comment]
@prayutsu Instead of commenting over every other issue try to stick to one or two at a time.
Try to fix one at a time or at max two, you can't work on all the issues at the same time and also some of the issues that you may want to work won't be that simple and may take few iterations.

**Comment by prayutsu** [comment]
> @prayutsu Instead of commenting over every other issue try to stick to one or two at a time.
> Try to fix one at a time or at max two, you can't work on all the issues at the same time and also some of the issues that you may want to work won't be that simple and may take few iterations.

Okay, I thought if I am stuck on one issue and till I receive any help with the mentors, I can work on other issues. As currently, I have only one issue assigned.

**Comment by aggarwalpulkit596** [comment]
But still i would suggest instead of commenting on each over other issues try to stick on one or two that you find you can do it with ease. Also start with some good first issue that i suggested you earlier.

**Comment by prayutsu** [comment]
> But still i would suggest instead of commenting on each over other issues try to stick on one or two that you find you can do it with ease. Also start with some good first issue that i suggested you earlier.

Thanks for your suggestions, I'll take care of that in future.

**Comment by prayutsu** [comment]
Thank you!
