### ISSUE TITLE
Naming consistency for DataProviderIds in domain layer.

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1589]
In `domain` layer all data provider ids should follow consistent pattern.
We should follow below mentioned style:

 - Name of constant & value should be the same (e.g. `QUESTION_DATA_PROVIDER_ID` and `"question_data_provider_id"`)
 - Constant name should be UPPER_SNAKE_CASE and value should be lower_snake_case
 - Use ID format: `<function_name>_<optional_context>_PROVIDER_ID` where the function_name is the exact function the provider used (expected to be just 1) and optional_context is used to disambiguate either when the ID is used in different functions or if the same function is overloaded

**Comment by rt4914** [comment]
Assigned to @Joydeepgill

**Comment by seanlip** [comment]
Deassigning @Joydeepgill since he will not be able to take this up after all (per email communication).

**Comment by The-Fuse** [comment]
@rt4914 I want to work on this issue.

**Comment by rt4914** [comment]
> @rt4914 I want to work on this issue.

Hello @The-Fuse Thanks for showing interest. Before we assign you issue to work on please sign the CLA and fill the survey form mentioned here https://github.com/oppia/oppia-android/wiki

Once done, we can assign you issues to work on.

**Comment by misterjedu** [comment]
Can I work on this? 

@BenHenning  @rt4914

**Comment by rt4914** [comment]
> Can I work on this?
> 
> @BenHenning @rt4914

Done. Thanks.

**Comment by misterjedu** [comment]
@rt4914 , thanks. 

I'm almost done but need a bit of clarification for some cases.

I didn't get the <optional_context> part. 

For example, a constant is used by five different functions, e.g moveToNextState() submitHintIsRevealed() ... and three others

How do I resolve the naming convention? 

There is also another case where one single function used two different constant values. 

Thanks...

**Comment by rt4914** [comment]
> @rt4914 , thanks.
> 
> I'm almost done but need a bit of clarification for some cases.
> 
> I didn't get the <optional_context> part.
> 
> For example, a constant is used by five different functions, e.g moveToNextState() submitHintIsRevealed() ... and three others
> 
> How do I resolve the naming convention?
> 
> There is also another case where one single function used two different constant values.
> 
> Thanks...

@misterjedu 
For first question:
If a constant is used by 5 different functions then you will need to update the code to use 5 different constants because a constant name is dependent on function name and therefore it cannot be used in multiple functions.

For second question:
That's exactly where the `optional_context` comes in place. If one function uses two different constants then you can differentiate between these two constants by adding some `optional_context` to the constant name.
