### ISSUE TITLE
Landscape support for Hints & Solution

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1593]
**Describe the bug**
Hints and Solution screen crashed on configuration changed

**To Reproduce**
1. Go to Fraactions
2. Skip initial states to go to first question.
3. Select option 1, twice.
4. You should see a Hint icon at the bottom-left
5. Click on hint
6. In hint screen, change mobile orientation.
7. Application crashes with following error:
<img width="857" alt="Screenshot 2020-08-10 at 5 49 38 PM" src="https://user-images.githubusercontent.com/9396084/89782059-27c08e80-db32-11ea-8d7d-b458a4b285cd.png">

**Expected behavior**
The application should not crash on configuration change in Hints&Solution.

**Comment by anandwana001** [comment]
This requires using `state` as a `Pacelable or Serializable` but nothing worked. 
Need some other workaround to save this state of `state` while configuration change.
`outState.putSerializable(STATE_SAVED_KEY, state)`
