### ISSUE TITLE
Landscape support for Input Interactions [Blocked on #1737]

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1594]
**Describe the bug**

**To Reproduce**
1. Go to `Fractions` -> `What is a Fraction?`
2. Skip to below mentioned state:
![Screenshot_1597062209](https://user-images.githubusercontent.com/9396084/89782231-7f5efa00-db32-11ea-8544-507007c1b818.png)

3. Enter some text
4. Change mobile configuration
5. The text disappears.

**Expected behavior**
This issue occurs in FractionInput, TextInput and NumberInput. So on configuration change the **text** as well as **error** both should be retained. Also, check this correct in **exploration** and **question** player

**Comment by prayutsu** [comment]
I want to work on this issue

**Comment by rt4914** [comment]
I have assigned you https://github.com/oppia/oppia-android/issues/1595 for now.

**Comment by rt4914** [comment]
Closing this because of duplicate issue: #4471
