### ISSUE TITLE
Landscape support for ItemSelectionInteraction [Blocked on #1737]

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1595]
**Describe the bug**
If learner has selected few options in `ItemSelectionInteraction` and does configuration change the selection disappears.

**To Reproduce**
1. Go to `Prototype Exploration`
2. Go to below mentioned state:
![Screenshot_1597062466](https://user-images.githubusercontent.com/9396084/89782617-48d5af00-db33-11ea-979e-9c3ca6dce4a8.png)

3. Select 2-3 options
4. Change device configuration
5. Notice that the selection resets.

**Expected behavior**
`ItemSelectionInteraction` should persist selected items on configuration change. Fix this for question and exploration player.

**Comment by prayutsu** [comment]
@rt4914 I want to work on this issue.

**Comment by rt4914** [comment]
@prayutsu This can be a tricky task but considering that you have finished almost 3 PRs, I am assigning this to you. If you get stuck feel free to mention and we will deassign you.

**Comment by prayutsu** [comment]
> @prayutsu This can be a tricky task but considering that you have finished almost 3 PRs, I am assigning this to you. If you get stuck feel free to mention and we will deassign you.

Thank you so much for assigning me the issue and yes, I will surely need your help @rt4914

**Comment by prayutsu** [comment]
@rt4914 If we could wrap the options selected in a LiveData object. Then the checkboxes will survive configuration change. I explored the directories and packages. But I need a little help in identifying the correct files (like SelectionInteractionViewModel, SelectionInteractionContentViewModel, QuestionPlayerViewModel, etc) where I should try making changes. It would be a pleasure if you could do some help

**Comment by aggarwalpulkit596** [comment]
@prayutsu things won't work with live data because they cannot retain values on configuration change.

**Comment by aggarwalpulkit596** [comment]
And you have to make changed ItemSelectionInteractionView

**Comment by prayutsu** [comment]
> @prayutsu things won't work with live data because they cannot retain values on configuration change.



> And you have to make changed ItemSelectionInteractionView

Thank you @aggarwalpulkit596 for your help.

**Comment by prayutsu** [comment]
@aggarwalpulkit596 
I searched the file "ItemSelectionInteractionView" and found only this most closely matched file -

**src/main/java/org/oppia/app/player/state/itemviewmodel/_SelectionInteractionViewModel.kt_**

Is this what you are referring to?

**Comment by aggarwalpulkit596** [comment]
Yes that's correct

**Comment by prayutsu** [comment]
> Yes that's correct

Thank you for that @aggarwalpulkit596 
I want an extra help.
I am trying to install ktlint and bufbuild on my ubuntu system and for ktlint my terminal says -
```
**error: The publisher of snap "ktlint" has indicated that they do not consider
       this revision to be of production quality and that it is only meant for
       development or testing at this point. As a consequence this snap will
       not refresh automatically and may perform arbitrary system changes
       outside of the security sandbox snaps are generally confined to, which
       may put your system at risk.
       If you understand and want to proceed repeat the command including
       --devmode; if instead you want to install the snap forcing it into
       strict confinement repeat the command including --jailmode.**
```

I also tried another command which is there on their official website - 
**curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.38.1/ktlint && chmod a+x ktlint**

But nothing happens, there's not any logs in the terminal and the command isn't executed completely.
![Screenshot from 2020-08-26 23-03-32](https://user-images.githubusercontent.com/54636525/91337202-a551f300-e7f0-11ea-8572-ed3cef3a5172.png)

**Comment by BenHenning** [comment]
@vinitamurthi or @anandwana001 is this something that you can help with?

**Comment by anandwana001** [comment]
> > Yes that's correct
> 
> Thank you for that @aggarwalpulkit596
> I want an extra help.
> I am trying to install ktlint and bufbuild on my ubuntu system and for ktlint my terminal says -
> 
> ```
> **error: The publisher of snap "ktlint" has indicated that they do not consider
>        this revision to be of production quality and that it is only meant for
>        development or testing at this point. As a consequence this snap will
>        not refresh automatically and may perform arbitrary system changes
>        outside of the security sandbox snaps are generally confined to, which
>        may put your system at risk.
>        If you understand and want to proceed repeat the command including
>        --devmode; if instead you want to install the snap forcing it into
>        strict confinement repeat the command including --jailmode.**
> ```
> 
> I also tried another command which is there on their official website -
> **curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.38.1/ktlint && chmod a+x ktlint**
> 
> But nothing happens, there's not any logs in the terminal and the command isn't executed completely.
> ![Screenshot from 2020-08-26 23-03-32](https://user-images.githubusercontent.com/54636525/91337202-a551f300-e7f0-11ea-8572-ed3cef3a5172.png)

As per the wiki [mentioned](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#commands), we are currently using 0.37.0 version of the ktlint. Please check with this version and let me know if the same issue occurs.

**Comment by prayutsu** [comment]
@aggarwalpulkit596 I am trying to solve this issue by using savedStateHandle in ```SelectionInterActionViewModel```
We can save the currently selected options in a key-value pair. And after configuration changes, when the ViewModel is created again, in the init block we can check if the state is not null, we use the stored values in ```selectedItems```. This should work, right?

**Comment by prayutsu** [comment]
@anandwana001 Even after trying version 0.37.0, still the same thing is happening.
![Screenshot from 2020-08-27 12-05-35](https://user-images.githubusercontent.com/54636525/91400673-ac631a80-e85d-11ea-9803-4b19fb7f643b.png)

**Comment by anandwana001** [comment]
> @anandwana001 Even after trying version 0.37.0, still the same thing is happening.
> ![Screenshot from 2020-08-27 12-05-35](https://user-images.githubusercontent.com/54636525/91400673-ac631a80-e85d-11ea-9803-4b19fb7f643b.png)

Just to confirm before I look into what's the issue, apart from ktlint does curl commands working on your machine?
Also, have you tried with brew - brew install ktlint

**Comment by prayutsu** [comment]
> > @anandwana001 Even after trying version 0.37.0, still the same thing is happening.
> > ![Screenshot from 2020-08-27 12-05-35](https://user-images.githubusercontent.com/54636525/91400673-ac631a80-e85d-11ea-9803-4b19fb7f643b.png)
> 
> Just to confirm before I look into what's the issue, apart from ktlint does curl commands working on your machine?
> Also, have you tried with brew - brew install ktlint

yes, they work

**Comment by anandwana001** [comment]
> > > @anandwana001 Even after trying version 0.37.0, still the same thing is happening.
> > > ![Screenshot from 2020-08-27 12-05-35](https://user-images.githubusercontent.com/54636525/91400673-ac631a80-e85d-11ea-9803-4b19fb7f643b.png)
> > 
> > 
> > Just to confirm before I look into what's the issue, apart from ktlint does curl commands working on your machine?
> > Also, have you tried with brew - brew install ktlint
> 
> yes, they work

ok let me see, The common issue always is this command sets up the file which requires stable and strong internet connection.

**Comment by prayutsu** [comment]
@anandwana001 Please take a look on this
![Screenshot from 2020-08-27 13-03-37](https://user-images.githubusercontent.com/54636525/91411338-cbfe4100-e865-11ea-9d9d-2d3a38439df8.png)

**Comment by anandwana001** [comment]
Could you try this one - https://snapcraft.io/install/ktlint/ubuntu

**Comment by prayutsu** [comment]
> Could you try this one - https://snapcraft.io/install/ktlint/ubuntu

![Screenshot from 2020-08-27 13-10-28](https://user-images.githubusercontent.com/54636525/91411963-b50c1e80-e866-11ea-8c2f-557a6f1c9277.png)

**Comment by anandwana001** [comment]
ah, snap doesn't have the latest version of ktlint and that's why ignoring to install the older version. 
This simply `curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.37.0/ktlint && chmod a+x ktlint` should work. Might be internet speed is a bit slow!! But, after running this command this will show you nothing, just start the next line to take input of other commands. 
Have you checked ktlint --version?

**Comment by aggarwalpulkit596** [comment]
> @aggarwalpulkit596 I am trying to solve this issue by using savedStateHandle in `SelectionInterActionViewModel`
> We can save the currently selected options in a key-value pair. And after configuration changes, when the ViewModel is created again, in the init block we can check if the state is not null, we use the stored values in `selectedItems`. This should work, right?

this should work but i don't think so it would that straight forward because we don't have state handle inside viewmodels also these view models are different from the view models that you might bee using in daily android development.

**Comment by prayutsu** [comment]
> ah, snap doesn't have the latest version of ktlint and that's why ignoring to install the older version.
> This simply `curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.37.0/ktlint && chmod a+x ktlint` should work. Might be internet speed is a bit slow!! But, after running this command this will show you nothing, just start the next line to take input of other commands.
> Have you checked ktlint --version?

I tried it says, 
![Screenshot from 2020-08-27 13-30-18](https://user-images.githubusercontent.com/54636525/91414837-c3f4d000-e86a-11ea-97cc-c56b207190b6.png)

**Comment by prayutsu** [comment]
> > @aggarwalpulkit596 I am trying to solve this issue by using savedStateHandle in `SelectionInterActionViewModel`
> > We can save the currently selected options in a key-value pair. And after configuration changes, when the ViewModel is created again, in the init block we can check if the state is not null, we use the stored values in `selectedItems`. This should work, right?
> 
> this should work but i don't think so it would that straight forward because we don't have state handle inside viewmodels also these view models are different from the view models that you might bee using in daily android development.

So, could you suggest some other better way @aggarwalpulkit596 ?

**Comment by anandwana001** [comment]
@prayutsu Give this a try, I tried in one of the ubuntu setups and works fine.  if this doesn't work let me check on a few other solutions. 
```
curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.37.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
```

**Comment by aggarwalpulkit596** [comment]
> > > @aggarwalpulkit596 I am trying to solve this issue by using savedStateHandle in `SelectionInterActionViewModel`
> > > We can save the currently selected options in a key-value pair. And after configuration changes, when the ViewModel is created again, in the init block we can check if the state is not null, we use the stored values in `selectedItems`. This should work, right?
> > 
> > 
> > this should work but i don't think so it would that straight forward because we don't have state handle inside viewmodels also these view models are different from the view models that you might bee using in daily android development.
> 
> So, could you suggest some other better way @aggarwalpulkit596 ?

That's probably the only way. There's no other way around for this problem.

**Comment by prayutsu** [comment]
@aggarwalpulkit596 Thanks for the help.

**Comment by aggarwalpulkit596** [comment]
It would lead to certain changes and wouldn't be easy to do especially when you're not familiar with project and that's why i suggested to take some up easy issue that will make you familiar with project but still if you'd like to take this one up i will be more than happy to help you. 🙂

**Comment by prayutsu** [comment]
> @prayutsu Give this a try, I tried in one of the ubuntu setups and works fine. if this doesn't work let me check on a few other solutions.
> 
> ```
> curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.37.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
> ```

Thank you so much @anandwana001. It worked.

**Comment by prayutsu** [comment]
> It would lead to certain changes and wouldn't be easy to do especially when you're not familiar with project and that's why i suggested to take some up easy issue that will make you familiar with project but still if you'd like to take this one up i will be more than happy to help you.

@aggarwalpulkit596 Thank you very much. So, should I push my changes once? So, you can have a look at it once.

**Comment by aggarwalpulkit596** [comment]
@prayutsu sure. https://proandroiddev.com/connecting-the-dots-44d8fa79f14 you could also read this thing if you want some context.

**Comment by aggarwalpulkit596** [comment]
@prayutsu https://github.com/hansenji/ViewModelInject this might be more appropriate but as we would be moving to dagger hilt idk doing this would be feasible or not. @rt4914 your thoughts?

**Comment by prayutsu** [comment]
@aggarwalpulkit596 Can you please take a look #1731

**Comment by aggarwalpulkit596** [comment]
Done.

**Comment by rt4914** [comment]
@anandwana001 @aggarwalpulkit596 @prayutsu 

Please avoid having conversations on issues, instead you can chat in [gitter](https://gitter.im/oppia/oppia-android) channel or on email.
Thanks

**Comment by prayutsu** [comment]
@rt4914 I am removing my assignment for this issue, so can you please assign me new issues?

**Comment by rt4914** [comment]
Duplicate #4472
