### ISSUE TITLE
Create custom macro to build app module in Bazel + Gradle 

### ISSUE THREAD

**Issue by miaboloix** [oppia/oppia-android#1597]
In order to build app module with Bazel + data-binding, manifest files with different packages had to be created for each library that enables data-binding. This change effects the import statements those files require. However, in Gradle's eyes, the packages of those files have not changed. So, Gradle cannot build if Bazel is building and vice versa. The workaround for this, however, is to create a custom macro that alters the import statements of files before Bazel builds them.

**Comment by BenHenning** [comment]
Fixed in #1582 and later PRs.
