### ISSUE TITLE
Write Bazel documentation for developers

### ISSUE THREAD

**Issue by miaboloix** [oppia/oppia-android#1598]

**Comment by anandwana001** [comment]
Step 1 for this Issue is, we need a started wiki page. I had added installation and a brief description regarding Bazel vocab. 
https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Guide

**Comment by BenHenning** [comment]
This seems like a good start--we can continue to refine the documentation during the migration. Since this issue didn't clearly outline what work we intended, considering it done.

**Comment by BenHenning** [comment]
Per https://docs.google.com/document/d/1_S27YFIwwMMX7kwEbXPK3nEbf4rcJF4tFVFSQsMChDc/edit# I think we cover most of the original intended documentation, sans Android Studio. I'll file a separate for AS.

**Comment by BenHenning** [comment]
This is now tracked in #2746.
