### ISSUE TITLE
Configure Bazel Android Studio plugin

### ISSUE THREAD

**Issue by miaboloix** [oppia/oppia-android#1599]
This will require configuring the plugin to use our forked version of Bazel. See https://github.com/bazelbuild/intellij/issues/405.

**Comment by Victor-Titan** [comment]
Can you please explain what entails in configuring the plugin? How exactly should on go about it?

**Comment by anandwana001** [comment]
@fsharpasharp Could you look into this issue if we required it or not?
Also, it will be helpful if we can update the issue description so it will help the contributor to complete the issue.

**Comment by fsharpasharp** [comment]
From the current description, I don't think this issue is relevant anymore since we're not running a custom fork of Bazel. Concerning Android Studio and Bazel, we have the [databinding issue](https://github.com/oppia/oppia-android/issues/2745).

Perhaps we could close this issue to avoid confusion?

**Comment by anandwana001** [comment]
@fsharpasharp Could you continue on this, on how to setup bazel plugin and use it in Android Studio?

**Comment by aggarwalpulkit596** [comment]
I'm working on this @anandwana001

**Comment by seanlip** [comment]
Removing @aggarwalpulkit596 due to inactivity.

**Comment by seanlip** [comment]
@BenHenning Could you please add more details here, or close the issue if it's not needed any more?

**Comment by BenHenning** [comment]
This is no longer relevant since we no longer use a custom Bazel build (we use Bazel's distribution for 4.x and 6.x).
