### ISSUE TITLE
Implement multi-user profile management system [Blocked: #14, #167]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#16]
A profile system needs to be implemented satisfying the requirements described in the Oppia PRD. This system should support storing a context of the currently logged-in profile, and support logging out that profile or logging in another profile. This system is responsible for the pin-based authentication described in the PRD.

Other systems might need to be updated to rely on this context rather than requiring a profile ID to be passed in to simplify them.

Note that for the prototype, it's essential that at least some portion of this system be implemented even if it just defaults to a single user without support for profile switching. Supporting profiles plays a central role in the design for the entire app architecture, so adding it late will be complex.

**Comment by BenHenning** [comment]
This is blocked on #14.

**Comment by BenHenning** [comment]
This is also blocked on #167.

**Comment by jamesxu0** [comment]
## List of future PRs

- [x] Introduce ProfileManagementController Interface and DirectoryManagementUtil
- [x] Introduce ProflieChooserFragment, AdminAuthActivity, and AddProfileActivity
- [x] Introduce ProfileListFragment, ProfileEditFragment, ProfileRenameActivity, ProfileRestPinActivity, and ProfileDeletionDialogFragment
- [x] Implement DirectoryManagementUtil
- [x] Implement ProfileManagementController
- [x] Integrate ProfileManagementController into PersistentCacheStore to use active profile’s directory
- [x] Implement ProfileInputView
- [x] Implement ProfileChooserFragment
- [x] Implement AdminAuthActivity
- [x] Implement AddProfileActivity
- [x] Implement PinPasswordActivity
- [x] Implement AdminSettingsDialogFragment and ResetPinDialogFragment
- [x] Implement ProfileListFragment
- [x] Implement ProfileEditFragment
- [x] Implement ProfileRenameActivity, ProfileRestPinActivity, ProfileDeletionDialogFragment
- [ ] Finalize PasswordInputView
- [ ] Finalize ProfileChooserFragment layout
- [ ] Finalize AdminAuthFragment and AddProfileFragment layouts
- [ ] Finalize PinPasswordActivity layouts
- [ ] Finalize ProfileListFragment layout
- [ ] Finalize ProfileEditFragment layout
- [ ] Finalize ProfileRenameFragment, ProfileRestPinFragment, ProfileDeletionDialogFragment layouts

**Comment by BenHenning** [comment]
This shouldn't have been closed @jamesxu0 since you still have pending PRs.

**Comment by BenHenning** [comment]
This appears complete with the most recent PRs submitted.
