### ISSUE TITLE
UI Structure: AudioFragment

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#162]
This is tracking implementing the UI structure for the audio bar fragment.

**Comment by BenHenning** [comment]
This is blocked on #123.

**Comment by jamesxu0** [comment]
I'm realized that ViewModels don't get recreated onConfigurationChanges, so the UI automatically retains it position and current play state through screen rotations. In onDestroy, I only release the MediaPlayer if it is not a configuration change. This allows constant audio to be playing for screen rotations.
