### ISSUE TITLE
Update `StoryTextSize` to `ReadingTextSize`

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1629]
Mock Link: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/2776cbb1-22b0-42c9-b70b-2136bdb361da/

Earlier in the app we were using `StoryTextSize` text in `OptionsActivity` as well as `ExplorationPlayer`. Now that text has been updated to `ReadingTextSize`.

This change should be made in all files, test cases, domain layer, proto layer, xml files, etc.

**Comment by prayutsu** [comment]
I want to work on this issue.

**Comment by rt4914** [comment]
@prayutsu You can work on this issue.
