### ISSUE TITLE
Fix ViewModels to not depend on View

### ISSUE THREAD

**Issue by miaboloix** [oppia/oppia-android#1633]
ViewModels to fix:
- ConceptCardViewModel
- RevisionCardViewModel
- ProfileEditViewModel

Before building app module with Bazel, the viewModels mentioned depended on bindings (for example, ConceptCardViewModel depended on ConceptCardFragmentBinding). However, the way app module needs to be split up to build with Bazel requires that viewModels do not depend on bindings - this is because the layout files need to be built after the viewModels. At the moment, we have circumvented this issue by instead having the fragment presenters use the binding to create a view that is then passed into the viewModels. So, the viewModels above depend on views instead of bindings. [ All of the changes mentioned were done in PR #1581 ]

However, having viewModels depend on views can present memory leaks and so view models shouldn't reference views directly. In this particular instance, leaks are prevented because @FragmentScope incorrectly recreates the view model.

**Comment by rt4914** [comment]
@miaboloix Can you add more details, references, labels to this issue so that we can assign it to new contributors?

**Comment by rt4914** [comment]
Assigning this to @alokbharti . Feel free to get back to us if you get stuck

**Comment by alokbharti** [comment]
Sure, thanks.

**Comment by anandwana001** [comment]
As all the required 3 ViewModels are done, closing this issue.
