### ISSUE TITLE
Full UI: StateCardFragment [Blocked: #17, #26, #28, #113, #115, #163]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#164]
There needs to be a fragment for representing the exploration state a user is currently playing, including audio voiceovers, and the content cards + interactions associated with that state. This is structurally similar to #27, except states allow for more complex responses. There may be some potential code reuse with questions.

**Comment by BenHenning** [comment]
This is blocked on #17, #26, #28, #113, #115, and #163.

**Comment by BenHenning** [comment]
@rt4914 can you clarify what remaining work needs to be done here?

**Comment by rt4914** [comment]
@BenHenning This one is blocked on #377

**Comment by rt4914** [comment]
This was finished as part of #40 and #42
