### ISSUE TITLE
Rename ic_hintbulb_whilte_24dp drawable file to ic_hint_bulb_white_24dp

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1645]
In `drawable` folder rename `ic_hintbulb_whilte_24dp ` to `ic_hint_bulb_white_24dp `

Also, make sure that this change is reflected in all files where this icon is used.

**Comment by prayutsu** [comment]
@rt4914 I want to work on this issue.

**Comment by prayutsu** [comment]
@rt4914 I am facing issues in installing linters. I use ubuntu. Please help me.

**Comment by rt4914** [comment]
> @rt4914 I am facing issues in installing linters. I use ubuntu. Please help me.

Please mention the issue that you are facing in detail in this group https://gitter.im/oppia/oppia-android
Currently from your message I don't have any idea about what all steps you tried and what error you got, so maybe add that information in gitter. Also adding @anandwana001 to this conversation so that he can help you out too.
