### ISSUE TITLE
Make dimens value follow one naming convention

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1646]
All `dimens` in app modules should follow below mentioned convention:

![1_66JEKhu7WqtPMkjegXMmgQ](https://user-images.githubusercontent.com/9396084/90195845-28824a80-dde8-11ea-8842-64940e869a58.png)

In this image, I suggest instead of using `padding_24dp` and `margin_24dp`, combining them to `space_24dp`.
So basically all padding/margins should be combined to `space_<value>`. This was we will have to add lesser values to dimens file.

[Image Reference](https://medium.com/mindorks/android-resource-naming-convention-42e4e8026614)

**Comment by prayutsu** [comment]
@rt4914 I want to work on this issue.

**Comment by rt4914** [comment]
@prayutsu This issue is blocked till september considering that it will bring changes to a lot files and we don't want to disturb gsoc contributors work just for this issue. Meanwhile, I will assign you new issues to work on in email.

**Comment by ranjsa** [comment]
@rt4914  Hey can I please work on this issue if no one else is working on it.

**Comment by rt4914** [comment]
> @rt4914 Hey can I please work on this issue if no one else is working on it.

Assigned.

**Comment by ranjsa** [comment]
@rt4914 Hey Rajat should I also replace all the hardcoded dimensions with dimens values

**Comment by BenHenning** [comment]
We should only use named dimensions for values that we plan to share across multiple components. Dimensions that aren't shared can be kept specific (note that additional dimensions increases the end binary size, so we generally want to avoid them unless we get some value from them).

**Comment by rt4914** [comment]
> @rt4914 Hey Rajat should I also replace all the hardcoded dimensions with dimens values

@ranjsa No, you should just focus on renaming the existing ones to match the convention correctly.
Also, I have updated the description, have a look.
