### ISSUE TITLE
FrameLayout for hints and Solution is missing in mobile portrait [Blocked on Highfi work]

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1647]
In `state_fragment.xml` file for portrait mobile screen, below mentioned code is missing

```
 <FrameLayout
      android:id="@+id/hints_and_solution_fragment_placeholder"
      android:layout_width="match_parent"
      android:layout_height="match_parent">
    </FrameLayout>
```

**Comment by anandwana001** [comment]
@rt4914 I had added this is my hints and solution PR - https://github.com/oppia/oppia-android/pull/1615/files

**Comment by rt4914** [comment]
Closed via https://github.com/oppia/oppia-android/pull/1615
