### ISSUE TITLE
LessonThumbnailImageView causes a "Render Problem" in Android studio

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#1658]
**Describe the bug**
The custom view `LessonThumbnailImageView` is causing a rendering problem in android studio when it is used in a layout file.  
If it is used in some layout file, you will not be able to see the layout preview. 

**To Reproduce**
1. Open Android Studio
2. Go to any xml file that contains `LessonThumbnailImageView` (e.g. `ongoing_story_card.xml`)
3. You will not be able to see the preview of the layout

**Error Log**
```
java.lang.IllegalStateException: View org.oppia.app.customview.LessonThumbnailImageView{79d58923 V.ED..... ......I. 0,0-0,0 #7f09016e app:id/lesson_thumbnail} does not have a Fragment set
	at androidx.fragment.app.FragmentManager.findFragment(FragmentManager.java:799)
	at org.oppia.app.customview.LessonThumbnailImageView.onAttachedToWindow(LessonThumbnailImageView.kt:101)
	at android.view.View.dispatchAttachedToWindow(View.java:19575)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:335)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:396)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:209)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:608)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$6(RenderTask.java:734)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
The preview should work correctly

**Screenshots**
![Screenshot from 2020-08-15 14-59-21](https://user-images.githubusercontent.com/8533363/90311033-599d7080-def7-11ea-8cd5-3707a635fd5a.png)

**Comment by Arjupta** [comment]
@MohamedMedhat1998 I just wanted to add one thing that, while trying to find a solution for this issue, I tried to re-type the whole LessonThumbnailImageView block of XML after removing it (removed it to check whether the other views are rendering correctly). While retyping this block of XML I saw all the views being rendered normally, but if the layout file is opened again then this issue arises.

I just mentioned this because it might be helpful to you.

**Comment by rt4914** [comment]
@ARJUPTA Thanks for mentioning this.

**Comment by MohamedMedhat1998** [comment]
> but if the layout file is opened again then this issue arises.

@ARJUPTA Have you tried to "refresh layout" in this case?  
Sometimes android studio can't render the layout correctly, but when you "refresh layout", it renders it well. But in the case of `LessonThumbnailImageView`, it can't render the layout even after refreshing.  
Can you check that, please?

**Comment by Arjupta** [comment]
![Screenshot 2020-10-07 16 47 39](https://user-images.githubusercontent.com/64064110/95324400-4be3e600-08bd-11eb-82d4-071efb54749f.png)

This is what I was able to see after Refreshing the layout. Means three behaviours are seen -

1.) When the block is typed for the first time, all views are rendered but LessonThumbnailImageView even after not being rendered doesn't block other views.
2.) After being refreshed other views are also not being rendered now but the background screen is white.
3.) Normally reopening the file containing LessonThumbnailImageView will show a black screen with no view

@MohamedMedhat1998

**Comment by MohamedMedhat1998** [comment]
> ![Screenshot 2020-10-07 16 47 39](https://user-images.githubusercontent.com/64064110/95324400-4be3e600-08bd-11eb-82d4-071efb54749f.png)
> 
> This is what I was able to see after Refreshing the layout. Means three behaviours are seen -
> 
> 1.) When the block is typed for the first time, all views are rendered but LessonThumbnailImageView even after not being rendered doesn't block other views.
> 2.) After being refreshed other views are also not being rendered now but the background screen is white.
> 3.) Normally reopening the file containing LessonThumbnailImageView will show a black screen with no view
> 
> @MohamedMedhat1998

Can you click on the "i" icon on the top right corner of the preview and share its output in each case, please?

**Comment by Arjupta** [comment]
@MohamedMedhat1998 only the last case of opening the file normally shows the error, it is same as you have posted earlier.

The first two cases as encountered by me just gives the warning that 

**Rendering errors might be caused by the new Layout Rendering Engine. Disabling it by clicking here may fix the issue. It can later be enabled again using the Settings > Experimental dialog.**

**Comment by MohamedMedhat1998** [comment]
> @MohamedMedhat1998 only the last case of opening the file normally shows the error, it is same as you have posted earlier.
> 
> The first two cases as encountered by me just gives the warning that
> 
> **Rendering errors might be caused by the new Layout Rendering Engine. Disabling it by clicking here may fix the issue. It can later be enabled again using the Settings > Experimental dialog.**

Well, if it is only a warning, it is ok. But if it is an error, we need to fix it, which is why we have this issue opened.

**Comment by etigoel** [comment]
I can start working on this.

**Comment by anandwana001** [comment]
@viktoriias As you are working around LessonThumbnailImageView, have you faced this issue?

**Comment by viktoriias** [comment]
> @viktoriias As you are working around LessonThumbnailImageView, have you faced this issue?

I don't remember getting such error messages.

**Comment by anandwana001** [comment]
@viktoriias could you add a screenshot just like above which shows that this issue is good to close?

**Comment by viktoriias** [comment]
> @viktoriias could you add a screenshot just like above which shows that this issue is good to close?

Actually, I just checked and I see the mentioned error.

**Comment by etigoel** [comment]
I can also see the mentioned error.

**Comment by anandwana001** [comment]
Thanks, @etigoel for confirming.
