### ISSUE TITLE
Stories in ProfileProgressActivity aren't clickable

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#1659]
**Describe the bug**
`RecentlyPlayedStorySummaryViewModel` doesn't have `onClick` function so that the stories aren't clickable.

**To Reproduce**
1. Go to Home
2. Click on Hamburger icon (navigation drawer)
3. Click on profile picture
4. Scroll to "Recently-Played Stories" 
5. Click on a story
6. Notice that nothing happens

**Expected behavior**
The story should open and the user should be able to play the story normally.

**Screenshots**
This is the screen where the problem exists
![Screenshot_2020-08-15-13-14-29](https://user-images.githubusercontent.com/8533363/90311273-691db900-def9-11ea-96a3-a057fd0a5fba.png)

**Comment by rt4914** [comment]
@mschanteltc Stories/Topics in following mocks should be clickable or not?
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/7fb5929e-4652-4412-bf8c-64d94f4159f9/

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/a80d1be8-d4b4-4fee-a46d-296b5aa6a110/

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/f54ae7d1-9530-44d6-8783-21559b13635c/

**Comment by mschanteltc** [comment]
Yes these are all clickable.

**Comment by mschanteltc** [comment]
Tapping a card under '[Recently Played Stories](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/7fb5929e-4652-4412-bf8c-64d94f4159f9/)' and '[Stories Completed](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/f54ae7d1-9530-44d6-8783-21559b13635c/)' transitions the page to the corresponding Topic Page, Lessons Tab. It auto scrolls to the Story card.

Tapping a card under '[Topics in Progress](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/a80d1be8-d4b4-4fee-a46d-296b5aa6a110/)' transitions the page to the corresponding Topic Page, Info Tab.
