### ISSUE TITLE
TextViewBindingAdapters uses string concatenation instead of multi-variable strings 

### ISSUE THREAD

**Issue by miaboloix** [oppia/oppia-android#1672]
**Describe the bug**
`TextViewBindingAdapters.java` uses string concatenation instead of using proper multi-variable strings. This will cause issues in the future when we attempt to RTL translate it.

**To Reproduce**
1. Go to `TextViewBindingAdapters.java`
2. Find this line: 
```
textView.getContext().getString(R.string.profile_last_used) + " " + getTimeAgo(
 ```

**Comment by BenHenning** [comment]
Actually, I think I might have been wrong about this in my comment. Plurals is meant for consecutive plurals, whereas here we're using range comparisons to select different strings. The current solution is probably ideal.

**Comment by prayutsu** [comment]
I want to work on this issue.

**Comment by rt4914** [comment]
I have assigned you #1629 and therefore lets work on this once that issue is finished.

**Comment by prayutsu** [comment]
@rt4914 Can I work on it now?
