### ISSUE TITLE
Add NetworkModule to ApplicationModule and tests once migrated off of Moshi

### ISSUE THREAD

**Issue by miaboloix** [oppia/oppia-android#1675]
Bazel doesn't support Moshi and, at the moment, Oppia Android's data module uses Moshi but is not functional. Files that were depending on NetworkModule were failing to build with Bazel because of this. So, NetworkModule has been removed from any files previously depending on it. Once data module is migrated off of Moshi and becomes fully functional with Bazel - these references will need to be re-populated.

**Comment by BenHenning** [comment]
Taking this. I was able to get Moshi to work in a separate Kotlin project that's going to download backend JSON structures & encode them in proto for the app. We either will outright remove Moshi, or update it to work based on that project (haven't decided yet).

**Comment by BenHenning** [comment]
Since this is blocking some of @jcqli's work, going to go ahead and patch the repository to properly hook into Moshi. Going to think about how to actually verify this is working, too (e.g. by introducing additional testing).
