### ISSUE TITLE
ProfileChooser crash on latest develop

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1687]
**Describe the bug**
As soon as we run the app on latest develop the application crashes because of inconsistency in `variable` name across xml files of `profile_chooser_profile_view`. Mainly there are two different types of variables introduced `wasProfileEverBeenAddedValue` and `hasProfileEverBeenAddedValue`.
But all variables should be `wasProfileEverBeenAddedValue` only. Its a minor typo but leads to crash.

This was introduced in latest commit: https://github.com/oppia/oppia-android/commit/68abd8907dd2d35f690b1383176481d853545c21#diff-29702622db8106a25b1087182a9c6bc2

**To Reproduce**
1. Run the app on latest develop
2. Go to `ProfileChooser` screen.
3. Application will crash.

**Expected behavior**
Application should not crash.

**Comment by rt4914** [comment]
I tried to fix this issue by changing the `hasProfileEverBeenAddedValue ` to `wasProfileEverBeenAddedValue` in all related xml files. After this when I tried to run the app (rebuild) I was actually facing the same issue which is
`<variable name='hasProfileEverBeenAddedValue' type='androidx.databinding.ObservableField'> is not defined consistently on alternative layout 'layout/profile_chooser_profile_view'`
 
Now, this from my understanding was because of the fact that `rebuild` uses gradle but we are using `bazel` for data binding now atleast in this xml file if not all.
So because this was bazel related, I contacted @anandwana001 considering that he has reviewed @miaboloix 's PRs and he might know something extra in this. 
@anandwana001 Can you mention the exact issue that you were facing while trying to solve it?

**Comment by anandwana001** [comment]
@rt4914 Actually, due to I get stuck in other issues, I haven't reviewed that particular PR, also I have to take few updates on bazel-databinding stuff. I tried this and what I see here is `hasProfileEverBeenAddedValue ` has been now a particular boolean value inside a layout, which is basically an `ObservableField<Boolean>` which should observe the value from the presenter. 
But what I see here is it is not observing and if we try to put value from presenter from our side it will work.
`binding.hasProfileEverBeenAddedValue = hasProfileEverBeenAddedValue`

**Comment by miaboloix** [comment]
@anandwana001 is correct - `ProfileChooserFragmentPresenter.kt` needs the following line: `binding.hasProfileEverBeenAddedValue = hasProfileEverBeenAddedValue`. Specifically, is should be placed inside `bindProfileView()` like so: 
```
private fun bindProfileView(
    binding: ProfileChooserProfileViewBinding,
    model: ProfileChooserUiModel
  ) {
    binding.viewModel = model
   binding.hasProfileEverBeenAddedValue = hasProfileEverBeenAddedValue  <----
    binding.profileChooserItem.setOnClickListener {
      if (model.profile.pin.isEmpty()) {
        profileManagementController.loginToProfile(model.profile.id).observe(
          fragment,
          Observer {
            if (it.isSuccess()) {
              activity.startActivity(
                (
                  HomeActivity.createHomeActivity(
                    activity,
                    model.profile.id.internalId
                  )
                  )
              )
            }
          }
        )
      } else { 
```
I am creating a PR to fix this!
