### ISSUE TITLE
Full UI: AudioFragment [Blocked: #162]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#17]
## Explanation
There needs to be a system for streaming and playing audio packs selected for a specific chapter by the user, leveraging the default audio language set for the current user's profile.

## Low-fi Checklist
- [x] Basic audio player UI 
- [x] Alert dialog for cellular network warning (https://xd.adobe.com/view/bee1fced-33bd-4f69-6a89-2c30fe1c4f65-c8d0/screen/d74f0571-471f-4ea6-a3a5-32e135253c56/Lesson-Introduction-4)
- [ ] Based on audio, content-card should get highlighted
- [x] Audio language selection
- [x] Play audio via MediaPlayer or ExoPlayer (https://github.com/google/ExoPlayer)

## High-fi Checklist
- [x] Seekbar and its animation
<img width="184" alt="Screenshot 2019-11-08 at 3 24 11 PM" src="https://user-images.githubusercontent.com/9396084/68467424-25947100-023c-11ea-89d2-74a745caaa35.png">

- [x] AudioBar along with Volume icon in toolbar
<img width="327" alt="Screenshot 2019-11-08 at 3 24 37 PM" src="https://user-images.githubusercontent.com/9396084/68467428-275e3480-023c-11ea-8915-0e8d074073ee.png">

- [x] CellularAlertDialog
<img width="268" alt="Screenshot 2019-11-08 at 3 24 58 PM" src="https://user-images.githubusercontent.com/9396084/68467443-3218c980-023c-11ea-901a-50b307ab83ff.png">

- [x] LanguageChangeDialog
<img width="278" alt="Screenshot 2019-11-08 at 3 24 45 PM" src="https://user-images.githubusercontent.com/9396084/68467450-36dd7d80-023c-11ea-8ecd-add5d55072b3.png">

- [x] Final touch including animations, positioning and Accessibility checks

## Test follow items too
- [x] Check how to audio bar changes on `en` and `hi-en` because this might change the seekbar length.
- [x] Shadow below the seekbar thumb (green circle)
- [x] The seekbar progress - white line has a sort of padding at start/end which needs to be removed.
- [x] The seekbar white progress line should be rounded at the end
- [ ]After the volume icon click, the “Language string like `HI` or `EN`” takes time to be visible which is not good for the UI.

**Comment by BenHenning** [comment]
This is blocked on #5.

**Comment by BenHenning** [comment]
It's not yet clear if we'll actually be persisting the audio files on disk, or if this will use the data source interface to expose the audio data.

**Comment by jamesxu0** [comment]
https://medium.com/androiddevelopers/building-a-simple-audio-app-in-android-part-1-3-c14d1a66e0f1

I found this articles for building a simple media player, which I'm going to base my implementation off of. I guess I'm confused on how to structure the code because the audio player should be a reusable component since it's used in a lot of places. It should be constructed with an audio source then the UI interacts with that source. I'm not sure if this should be a custom view, small fragment, or something else. Also, will the audio be from a uri?

**Comment by BenHenning** [comment]
This is technically blocked on #116 and #162.

**Comment by BenHenning** [comment]
@jamesxu0: yep, audio will come from a URI.

**Comment by jamesxu0** [comment]
List of future PRs:
- [] Introduce ProfileManagementController Interface and DirectoryManagementUtil
- [] Introduce ProflieChooserFragment, AdminAuthFragment, and AddProfileFragment
- [] Introduce ProfileListFragment and ProfileEditFragment
- [] Introduce ProfileRenameFragment, ProfileRestPinFragment, ProfileDeletionDialogFragment
- [] Implement DirectoryManagementUtil
- [] Implement ProfileManagementController
- [] Integrate ProfileManagementController into PersistentCacheStore to use active profile’s directory
- [] Implement PasswordInputView
- [] Implement ProfileAvatarView
- [] Implement ProfileChooserFragment
- [] Implement AdminAuthFragment
- [] Implement AddProfileFragment
- [] Implement ProfileListFragment
- [] Implement ProfileEditFragment
- [] Implement ProfileRenameFragment, ProfileRestPinFragment, ProfileDeletionDialogFragment
- [] Finalize PasswordInputView and ProfileAvatarView layout
- [] Finalize ProfileChooserFragment layout
- [] Finalize AdminAuthFragment and AddProfileFragment layouts
- [] Finalize ProfileListFragment layout
- [] Finalize ProfileEditFragment layout
- [] Finalize ProfileRenameFragment, ProfileRestPinFragment, ProfileDeletionDialogFragment layouts

**Comment by rt4914** [comment]
@jamesxu0 can you please verify what all has been finished in the above low-fi checklist.

**Comment by rt4914** [comment]
The only work item pending in this is #1383 

Rest all have been fixed via different PRs in https://github.com/oppia/oppia-android/pull/467 #495 #358 #356
