### ISSUE TITLE
Prevent binary files from being checked in

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1730]
Checking in binary files will significantly increase the repository size. We need a pre-commit check to prohibit binary files from being added, since we should never add them. In cases when binary files are needed, we should use Git LFS or an alternate solution.

**Comment by BenHenning** [comment]
Also: we should have a CI check to verify that across the entire commit log of a PR that no files are binary (otherwise it should start permanently failing since only a force push can remediate such a situation). This is the only time we should ever force push.

**Comment by BenHenning** [comment]
We may run into an issue with the CI check if it runs across the entirety of develop since there are some binary files in mainline, and we can't force push change those. We may need to build in exceptions for those files.

**Comment by BenHenning** [comment]
Note also that this issue unblocks opening write access to contributors who work on big projects and can thus benefit from PR chaining (otherwise https://github.com/isaacs/github/issues/959 prevents proper PR chaining when using forks).

**Comment by navneetsaluja** [comment]
May I work on this? From what I understand, we need to write a pre-commit shell script. I'm confused about which binary files which you are talking about though, could you give me an example?

**Comment by rt4914** [comment]
cc: @BenHenning
