### ISSUE TITLE
Move .idea folder to .gitignore [Blocked: #970]

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1734]
Move the `.idea` folder to `.gitignore` to prevent issues like deletion of `vcs.xml` or generation of any new file on local to get merge

**Comment by Arjupta** [comment]
@anandwana001 does this issue require only to add .idea folder to .gitignore? If it is so, can I do that?

**Comment by anandwana001** [comment]
This is blocked on other issue. We cannot work on this unless the other one gets finish. @ARJUPTA

**Comment by seanlip** [comment]
`.idea/` is already in .gitignore, so I'm closing this. Proof: https://github.com/oppia/oppia-android/blob/develop/.gitignore#L4
