### ISSUE TITLE
Add Java Linter to the project

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1735]
With the Bazel migration, we are now having java files in our codebase. We would like to add a linter that ensures all the Java files follow the same style.

- [ ] Run the linter on our existing Java files. Create a PR that fixes all lint problems that the linter catches

- [ ] Add steps in the linter job of our GitHub Action workflow (similar to the [Kotlin linting](https://github.com/oppia/oppia-android/blob/develop/.github/workflows/main.yml#L27) step) that will install and run the linter on our Java files

- [ ] Verify that the Android Studio auto-formatter is using the same rules as the linter configuration. If not, make changes to the code style of the Java files in Android Studio (that will create changes to the files present in the .idea/codeStyles/ directory). Create a PR that checks in the changes in these files.

- [ ] Add documentation on how to install the linter in the [prerequisites section of our wiki](https://github.com/oppia/oppia-android/wiki#prerequisites)

**Comment by BenHenning** [comment]
Note that we should also be enforcing & following the [Google Java Style Guide
](https://google.github.io/styleguide/javaguide.html).

**Comment by anandwana001** [comment]
> Note that we should also be enforcing & following the [Google Java Style Guide ](https://google.github.io/styleguide/javaguide.html).

Yes, I didn't mentioned it in the issue because of 2 points:
1. I am writing a documentation where I am describing more about GitHub's Super-Linter
2. Checkstyle is also one option

**Comment by yurilev** [comment]
After syncing, pushes fail with the following message:
```
bash: scripts/kotlin-lint-check.sh: No such file or directory
```

Something somewhere is still looking for the old filename, but I can't find it in the codebaes.

**Comment by yurilev** [comment]
Reopening. Paraphrasing @BenHenning + adding detail:

Devs who ran `scripts/setup.sh` before `ktlint_lint_check.sh` was renamed have the older version of `pre-push.sh` in `.git/hooks/pre-push`, and it still points to `scripts/kotlin-lint-check.sh`.

Workaround:
```
rm .git/hooks/pre-push
source scripts/setup.sh
```

Then `cd` back to `oppia-android` (the last step switches directories)

**Comment by yurilev** [comment]
Reopening.

**Comment by BenHenning** [comment]
Thanks @yurilev.

@anandwana001 can you send out an announcement to the mailing list & Gitter explaining how to work around this issue? It seems simple re-running setup.sh is the correct approach.

**Comment by anandwana001** [comment]
Yes, I was about to sent an announcement, once this little fix get's merged 
https://github.com/oppia/oppia-android/pull/2674 
@BenHenning

**Comment by anandwana001** [comment]
After discussing with multiple contributors yesterday I found very few are there who had setup the script till now. Will send a detail email.

**Comment by anandwana001** [comment]
Closing this issue. 
Sent an email update to all with all the required steps. Also, update on Gitter channel.
https://gitter.im/oppia/oppia-android
