### ISSUE TITLE
Singleton class in domain to manage configuration changes

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1737]
Currently in exploration player and question player, on orientation change the application does not retain the user input answer in `InputInteractions`.
To manage this effectively, we should introduce a singleton class in domain layer which will be linked to pending answer such that we can save information to this singleton class as soon as the input answer changes and again we can fetch this information back on configuration change.

**Comment by BenHenning** [comment]
NB: we should keep this solution specific to interactions now rather than developing a general-purpose replacement to savedInstanceState (since it's not clear that we actually want that yet).

**Comment by FareesHussain** [comment]
@rt4914 I would like to work on this, Is there any similar implementation for reference

**Comment by rt4914** [comment]
> @rt4914 I would like to work on this, Is there any similar implementation for reference

@FareesHussain No we don't have any similar implementation.

**Comment by FareesHussain** [comment]
@BenHenning I've tried to understand working of `StatePlayerRecyclerViewAssembler` 

Here in this issue we need to solve the following issues based on `addInteractionSupport` in `StatePlayerRecyclerViewAssembler`
 - text and error message in [FractionInteractionView.kt]
 - list of selected checkboxes in [SelectionInteractionView.kt]
 - text(integer) and error msg for [NumericInputInteractionView.kt]
 - text and error message for [RatioInputInteractionView.kt]
 - text for [TextInputInteractionView.kt]
 - list for drag & drop [DragDropSortInteractionView.kt]
 - list for drag & drop with merging [DragDropSortInteractionView.kt]
 - selected image in the [ImageRegionSelectionInteractionView.kt]

So for this issue i need to save and restore the above infomation using `onSavedInstance` in the `StateFragmentPresenter` and `StateFragment`

but how will i know the which type of InputInteraction is used in a particular `StateFragment`

**Comment by BenHenning** [comment]
I think we want to close this as 'Not planned' since it's being replaced by #4470 (which is a different solution) @vrajdesai78.
