### ISSUE TITLE
Lowfi update Walkthrough

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1739]
Currently Walkthrough implementation does work in develop but to implement the final UI correctly we will need to make changes to the UI first.
**References**
https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/92becc49-3a10-498b-885c-4cde95f73d51/
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/7f7a12db-2dde-442c-a236-5953e36ca840/

**Issue**
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/7f7a12db-2dde-442c-a236-5953e36ca840/
In the above mentioned link, the progress-bar and the `What do you want to lean?` consumes major part of the screen which does not look good in landscape.

**Suggested Solution**
When the user scrolls down, we hide the progress bar and move the "What do you want to learn?" heading to the top and stay fixed as the user scrolls. 

When the user scrolls back to the top of the page, the progress bar appears and the "What do you want to learn?" heading shifts a little bit down to make room for the progress bar. However if the user scrolls up and is not at the top of the page, only the heading will show. Although scrolling up, regardless of the user's placement on the screen, to see a header/menu/navbar is a common interaction on mobile apps, in this case, the user's call CTA is to browse through a list of topics and select one to learn. Having the progress bar appear as the user is searching for a topic obstructs their view and limits the number of topics they can see at a time.

**Changes needed**
1. In the `WalkthroughActivity` we will need to control `progress-bar` so that it goes out of screen (or hides) when user scrolls and it is not on top.
2. In the `WalkthroughTopicList` the `text` is actually the first item of recyclerview as `WalkthroughTopicHeaderViewModel` but because we want this text to stick to top when scrolled, we should move this out of recyerlerview and make it part of `WalkthroughTopicListFragment` directly.

**Comment by prayutsu** [comment]
Hello,
Sir, I am unable to sync my project with Gradle files due to which I am
unable to use the design editor, it would be beneficial if I could use
design editor.
Here is the screenshot of the error attached.
Also, where should I seek help if I face similar issues in the future?

Thanks,
Abhay

**Comment by seanlip** [comment]
This UI is obsolete, we're not planning to implement it. Closing this issue.
