### ISSUE TITLE
StateFragmentLocalTest tests are failing on develop

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1749]
Following test cases are failing on current develop

```
testStateFragment_nextState_viewSolution_noNewHintIsAvailable
testStateFragment_nextState_viewFourHints_submitWrongAnswer_wait10s_newHintIsAvailable
testStateFragment_nextState_viewSolution_submitWrongAnswer_wait10s_noNewHintIsAvailable
testStateFragment_nextState_viewFourHints_submitWrongAnswer_noNewHintIsAvailable
testStateFragment_nextState_viewFourHints_wait30seconds_newHintIsAvailable
testStateFragment_nextState_viewFourHints_wait10seconds_noNewHintIsAvailable
testStateFragment_nextState_viewFourHints_submitWrongAnswer_wait10s_canViewSolution
testStateFragment_nextState_submitThreeWrongAnswers_canViewOneHint
testStateFragment_nextState_viewFourHints_wait30seconds_canViewSolution
testStateFragment_nextState_viewSolution_wait30seconds_noNewHintIsAvailable
```

Needs more details and solution

**Comment by BenHenning** [comment]
Do we know what the root cause is? We should be reverting PRs that cause test breakages.

I plan on submitting #1630 soon which will make this impossible to happen again.

**Comment by rt4914** [comment]
> Do we know what the root cause is? We should be reverting PRs that cause test breakages.
> 
> I plan on submitting #1630 soon which will make this impossible to happen again.

The root cause is the index that is passed for testing in recyclerview. I have fixed that directly in this PR.

**Comment by BenHenning** [comment]
Ack. Moving forward we should revert, then fix, per the team policy: https://github.com/oppia/oppia-android/wiki/Revert-&-regression-policy. The test has been broken for the past few days as a result of waiting for a new fix. Reversion is a faster way to get the build back into a good state while we spend the time to investigate the underlying issue & fix it.
