### ISSUE TITLE
Create a prototype class that can take screenshots of the app

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#1752]
Create a class that can take screenshots of some screen of the app and exports it to the external storage of the device/emulator.

**Comment by BenHenning** [comment]
I suggest renaming this to be 'prototype' and considering it done. Please file another issue (if we don't already have one) to track introducing a screenshot testing framework for post-GSoC.

**Comment by BenHenning** [comment]
@rt4914  /cc

**Comment by MohamedMedhat1998** [comment]
> 
> 
> I suggest renaming this to be 'prototype' and considering it done. Please file another issue (if we don't already have one) to track introducing a screenshot testing framework for post-GSoC.

I have filed an issue for screenshot-testing. PTAL #1815  
Feel free to update the description if needed.

**Comment by BenHenning** [comment]
Is this resolved now?

**Comment by MohamedMedhat1998** [comment]
> Is this resolved now?

@BenHenning The mentioned class was created in #1743 but not merged because we need to have the whole picture of the screenshot-testing process first.

**Comment by BenHenning** [comment]
Ah, I'm aware of that but we also have #1815 to track the actual introduction of the framework. I think we can consider this issue resolved if we have a demo for screenshot testing--that demo doesn't actually need to be checked in (and probably shouldn't unless it can be cleanly integrated).

To that end, does #1743 work sufficiently to be considered a screenshot testing demo that we can use as a base for buiilding the rest of what's needed in #1815 @MohamedMedhat1998?

**Comment by MohamedMedhat1998** [comment]
@BenHenning in terms of taking a new screenshot and storing it at the external storage, yes it is sufficient.

**Comment by BenHenning** [comment]
Thanks @MohamedMedhat1998. In that case, considering this fixed since #1815 will be tracking the longer-term work that will be checked in.
