### ISSUE TITLE
NavigationDrawer cancel switch profile always mark home

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1762]
**Describe the bug**
After cancelling the exit profile dialog, home menu get's marked no matter on which menu I was on previously 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open nav drawer
2. click option
3. open nav drawer
4. click switch profile
5. click cancel
6. home gets marked but we are on the options screen

**Expected behaviour**
Mark that menu Item which was on the screen before opening the switch dialog not home as always

**Comment by prayutsu** [comment]
@anandwana001 Can I work on this?
