### ISSUE TITLE
Trying to input answers in landscape is impossible due to keyboard automatically dismissing.

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1767]
**Describe the bug**
When you try to input anything in landscape, the keyboard automatically dismisses.

**To Reproduce**
1. Open the app
2. Navigate to the prototype exploration
3. Rotate to landscape
4. Continue to the second state (fractions)
5. Select the fraction input box
6. Observe the soft keyboard open
7. Observe the soft keyboard immediately close

**Expected behavior**
The soft keyboard shouldn't be automatically closing.

**Screen recording**
![auto_close_keyboard](https://user-images.githubusercontent.com/12983742/91962322-3a595e00-ecc1-11ea-81f3-d9492df572c3.gif)

**Device**
- Device: Pixel XL
- SDK version: SDK 29

**Additional context**
This is definitely a regression since StateFragmentTest was passing 2 weeks ago (the last time I tried these scenarios).

**Comment by BenHenning** [comment]
Looks like this was introduced in 1bb1ffa97b2c14e002fa0371991f4f25351a79cd (#1653). @rt4914 FYI.

**Comment by BenHenning** [comment]
This PR is probably too large & too old to revert at this point, so I'm going to try and figure out what the underlying offending change was and try to revert just that part. Guessing it has something to do with the updated margins in landscape.

**Comment by BenHenning** [comment]
Seems like this might be revertable after all since it's pretty isolated.

@rt4914 did you play through an exploration in landscape when working on that PR, and are you able to repro this issue? I'm also wondering if it's device specific.

**Comment by BenHenning** [comment]
Reverted commit seems to fix the issue. Sending out a PR shortly to unblock state fragment test & alpha work.

**Comment by BenHenning** [comment]
Just added a screen recording in case folks have difficulty reproing it if it is screen-size specific.

**Comment by rt4914** [comment]
> Looks like this was introduced in [1bb1ffa](https://github.com/oppia/oppia-android/commit/1bb1ffa97b2c14e002fa0371991f4f25351a79cd) (#1653). @rt4914 FYI.

This is actually working correctly in Pixel 3A xl, this is device specific issue.

**Comment by rt4914** [comment]
Just tested this on Pixel XL (29) and it is working correctly.
![Screenshot_1599049607](https://user-images.githubusercontent.com/9396084/91980939-b1d0d100-ed45-11ea-911e-af7e86e79729.png)

**Comment by BenHenning** [comment]
This might not repro on emulators--I suspect it's more likely to be noticed on a real device.
