### ISSUE TITLE
Keyboard not at all visible (Portrait + Landscape) in API 19

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1772]
**Describe the bug**

**To Reproduce**
1. Create an emulator with small dimensions like `3.4 WQVGA` with `API 19`
2. Go to `Prototype Exploration`
3. Go to `State 2`
4. Click on edit text.
5. Keyboard is not visible

**Expected behavior**
Keyboard should be visible in API 19 and above.

**Device**
- 3.4 WQVGA
- SDK version = 19

**Comment by seanlip** [comment]
Per https://github.com/oppia/oppia-android/issues/5012, we are deprecating support for Android KitKat, so this issue is no longer valid.
