### ISSUE TITLE
Images are failing to load sometimes in the exploration player

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1781]
See https://github.com/oppia/oppia-android/pull/1637#issuecomment-686244303 for specifics. More investigation is needed.

**How to encounter this error?**

1. Using the **scripts** load the oppia-alpha assets.
2. Uninstall your previous app.
3. Go to `MRJeVrKafW6G.json` file and change "init_state_name" to `Recap 1`
4. Using this [function](https://gist.github.com/rt4914/9ca5798836e783ec29215dead870bc5b#file-storyprogresstesthelper-kt-L24) mark dummy progress.
5. Run the app.
6. Go to Multiplications
7. Go to `5. Multiplying by power of 10`
8. Enter 2 incorrect answer.
9. Click on hint -> reveal.
10. Notice it is empty.

**Expected Result**
This image should be visible in hint. https://storage.googleapis.com/oppiaserver-resources/exploration/MRJeVrKafW6G/assets/image/img_20200308_213016_u6ap4qq25c_height_313_width_490.png

**Comment by BenHenning** [comment]
@rt4914 found that UrlImageParser is posting a layout adjustment function for width that's racing against the layout steps in wrap_content cases which can result in a negative maximum image width being computed. Per our discussion, we should force text views in Oppia Android that use HtmlParser to specify a width or use match_parent. It's not yet clear if updating those text views will fix this issue, but it seems likely. Sending over to Rajat to see if this gets fixed with his solution.

**Comment by anandwana001** [comment]
Putting this video link here for issue reference - https://lh3.googleusercontent.com/Pp2LOc-FuR5ZvsxcEQ8Tt9Ikpqnp_TiQiGH0unuY2tCD54gXumCT4Sp3tK0SjVHefVruXSeSLcUwEJ4=m37

**Comment by BenHenning** [comment]
Ah, this might be slightly better with #1782 done, but I also realized that we're missing some caching logic for multiple choice options which is causing this to fail for offline cases. One PR should be coming for that.
