### ISSUE TITLE
Audio is not auto-playing & track is broken

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1784]
Note that this was reproed when using the place values & multiplication assets.

When playing an exploration & starting audio, the audio track/button would not indicate audio was playing and audio would not auto play for responses for new cards.

**Comment by rt4914** [comment]
@BenHenning I just tested this in develop with latest alpha content. I am not able to find any such issues.

Video Reference: https://drive.google.com/file/d/1cStXgm_G1qx0X88g-TYyWW18KazP5D0K/view?usp=sharing

Can you provide device information?

**Comment by BenHenning** [comment]
This was on my Pixel XL. I can't seem to repro with dev content, trying again in the context I hit it.

**Comment by BenHenning** [comment]
Unfortunately I can't repro. Closing for now; will reopen if I hit it again.
