### ISSUE TITLE
Selecting 'Memorizing Multiplication Expressions' breaks question player

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1785]
Note that this was found with the production multiplication topic.

Select Memorizing Multiplication Expressions & start a training session. Session fails to start & future sessions break until app restart.

I'm guessing this is because there aren't any questions associated with this skill? I haven't dug into it in detail yet.

**Comment by rt4914** [comment]
This subtopic is related to skillId: `a3QtIqWYO6WL` which unfortunately has not questions. Sharing more details on private chat because of alpha content.

**Comment by BenHenning** [comment]
All skills that are affected:
- Memorizing multiplication expressions (Multiplication topic)
- Rules to simplify multiplication (Multiplication topic)
- Naming numbers (Ratios topic)
- Rounding numbers (Ratios topic)

Let's go ahead and remove these for now. If students get stuck without these in place, we'll add them in a subsequent alpha launch. It is unfortunate that we lose the revision cards, though.

**Comment by rt4914** [comment]
Closing this PR as it has been done on private repo.
