### ISSUE TITLE
Add support for parameters in the exploration player

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#179]
For parity with Oppia web, we need support for parameters in the exploration player.

**Comment by seanlip** [comment]
Actually (FYI) this is very low priority and we might not need it at all. I
need to do a review of the parameter impl in the web view at some point and
I think it may end up changing quite a bit. We also (intentionally) don't
use this functionality in any of the curated lessons.

>

**Comment by BenHenning** [comment]
Per the comment above, closing this since it's unlikely that we'll actually need it (and haven't so far). Plus, once the new proto APIs are introduced in Oppia web to facilitate downloads we'll be able to explicitly prohibit allowing the client to have access to explorations with parameters.

**Comment by BenHenning** [comment]
The AI here is to remove the TODO from code so that the issue can be closed.

**Comment by seanlip** [comment]
Note to contributors: this is an extremely easy good first issue! It just involves removing the TODO.
