### ISSUE TITLE
AdminCreatePin Submit Button Not Active

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1791]
**Describe the bug**
Submit button not active after pin and confirm pin entered

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the app for the first time
2. From Profile chooser screen click administrator control
3. Enter pin and confirm pin -> submit button not active

**Expected behaviour**
Submit button should be active when both pin and confirm pin entered 

**Screenshots**
![Screenshot_1599196661](https://user-images.githubusercontent.com/25057618/92202423-a17f3a00-ee9c-11ea-80da-a98a79f47287.png)

**Comment by anandwana001** [comment]
@rt4914 You can repro this and let me know because now I am not getting this issue.

**Comment by rt4914** [comment]
> @rt4914 You can repro this and let me know because now I am not getting this issue.

I am not able to reproduce this.

**Comment by anandwana001** [comment]
> > @rt4914 You can repro this and let me know because now I am not getting this issue.
> 
> I am not able to reproduce this.

@rt4914  Okay, I think then we are good to close this issue
