### ISSUE TITLE
Toggling show/hide changes soft keyboard

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1792]
**Describe the bug**
When we are on the screen where we have to input admin pin, we have a show and hide button, toggling which changes the soft keyboard 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install app -> click on the admin profile
2. click on the show -> hide -> soft keyboard changes 

**Expected behaviour**
The soft keyboard should not change

**Video**
https://lh3.googleusercontent.com/2ACs5tLuu3JmS1V248M2flkFCL35GeI4ZaHaj2yXu-AIaXExQFbWXVDkkyeS8vCXBKIyU5RRxhQeJ08=m37

**Device**
- Redmi Note 5 Pro

**Comment by anandwana001** [comment]
As per the Library(com.chaos.view.PinView), we are using which have a different type of keyboard use when input is a pin or a password. 

Reference
![gif](https://github.com/ChaosLeung/PinView/blob/master/screenshots/input.gif?raw=true)

And what we are doing here is -> `android:inputType="@{viewModel.showPassword ? InputType.TYPE_CLASS_NUMBER : (InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_VARIATION_PASSWORD)}"`

@mschanteltc Will this looks good or we should be consistent to one type of soft keyboard when toggling between show and hide?

**Comment by mschanteltc** [comment]
We should be consistent with the keyboard. The second keyboard is the better choice because only the numbers, backspace, and enter buttons are necessary.

**Comment by anandwana001** [comment]
This issue can be solved directly from the user library. Needs to update to PinView - `1.4.4`

Reference - https://github.com/ChaosLeung/PinView/issues/55

**Comment by BenHenning** [comment]
It looks like the release has been completed, and that we just need to update to the latest version & use the correct filter.

**Comment by abhinav12k** [comment]
Hi @BenHenning I want to work on this issue.

**Comment by rt4914** [comment]
> Hi @BenHenning I want to work on this issue.

I have assigned this issue to you. 
cc/ @BenHenning

**Comment by Victor-Titan** [comment]
Can I work on this issue?

**Comment by anandwana001** [comment]
Sure @Victor-Titan, I will assign it to you.

**Comment by Austinepass** [comment]
@BenHenning, can I work on this issue?

**Comment by prayutsu** [comment]
@Austinepass This issue is already assigned to @ARJUPTA so you can look at other good first issues

**Comment by rt4914** [comment]
> @BenHenning, can I work on this issue?

@Austinepass Actually, It is already assigned. You can self-assign any issue to work on from this link: https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22good+first+issue%22

**Comment by Austinepass** [comment]
Okay, I'll look for another issue to work on.

Thanks.

**Comment by yk1ax** [comment]
I am working on this issue @anandwana001. Can I get assigned.

**Comment by prayutsu** [comment]
Assigning this to you @yk1ax
