### ISSUE TITLE
AdminPin screen lost after app minimize

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1793]
**Describe the bug**
When we are on the admin pin screen to create pin, and minimize the app and coming back will take us back to the profile chooser screen

**To Reproduce**
1. Install app -> open administrator controls from profile chooser screen
2. Minimize app and open app again from minimized stack ->  profile chooser screen will apear

**Expected behavior**
We should be back to admin pin screen after opening minimized app

**Comment by chrk2205** [comment]
can i work on this??
@rt4914 @BenHenning

**Comment by anandwana001** [comment]
@chrk2205 sure, please have a look at our onboarding instruction before continue the work. https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by chrk2205** [comment]
@anandwana001 
Thanks,
I already signed CLA and survey.
