### ISSUE TITLE
Add support for SDK 29 in tests [Blocked: #59]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1794]
**Is your feature request related to a problem? Please describe.**
The app needs to target SDK 29 for R8 compatibility when building the release app, but in #1789 we needed to limit Robolectric tests to SDK 28 since SDK 29 requires using Java 9+. As part of the Bazel migration (#59) we should ensure tests can run correctly with SDK 29.

**Comment by BenHenning** [comment]
This is outdated. #4183 upgraded tests to SDK 30, and #4748 is tracking moving tests to SDK 31. There's nothing more to do in this issue.

**Comment by adhiamboperes** [comment]
Hey @MohitGupta121, it sounds like the aim of the issue was to remove these `robolectric.properties` files once support for 29+ was achieved, so I'm not sure whether we want to close this issue without achieving that first.  Maybe you can keep your PR as a part of fix and then we can repurpose this issue @seanlip.

**Comment by adhiamboperes** [comment]
@MohitGupta121 could you please look into whether these files can be removed now?

**Comment by MohitGupta121** [comment]
> @MohitGupta121 could you please look into whether these files can be removed now?

By removing those `robolectric.properties` files?

**Comment by adhiamboperes** [comment]
The TODOs mention "Remove the need for this file & use SDK 29 at the project level." You would need to verify that our supported sdk version is compatible with our robolectric version. 

I think you can easily do that by removing this `line sdk=30` robolectric.properties and testing if the robolectric tests in that module run.

Some reference: https://stackoverflow.com/questions/56808485/robolectric-and-android-sdk-29

**Comment by MohitGupta121** [comment]
Okay Thanks @adhiamboperes I'll do that.
