### ISSUE TITLE
Track the spacing in images in Multiple choice questions

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1799]
**Describe the bug**
We have to check the explorations in which cases we are getting extra space between options

Here we have extra space after the first option 

![Screenshot_1599213928](https://user-images.githubusercontent.com/25057618/92228777-0602bf00-eec6-11ea-8e13-06073f813095.png)

**Comment by BenHenning** [comment]
#2459 needs to be reverted per #2527. Reopening this.
