### ISSUE TITLE
User activity tracking system

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#18]
A general system should exist to track the user's activity/inactivity in the app. Callers into this system are responsible for determining what is a user action. This system will have a timer that will keep track of when the last user action occurred. If that was longer than a fixed time ago (30 minutes), then the user should automatically be logged out.

**Comment by BenHenning** [comment]
This is blocked on #4.

**Comment by BenHenning** [comment]
This is also blocked on #7.

**Comment by adhiamboperes** [comment]
We've implemented various activity tracking systems so far in https://github.com/oppia/oppia-android/blob/develop/domain/src/main/java/org/oppia/android/domain/oppialogger/analytics/ApplicationLifecycleObserver.kt and https://github.com/oppia/oppia-android/blob/develop/domain/src/main/java/org/oppia/android/domain/exploration/ExplorationActiveTimeController.kt, and some session management work. @kkmurerwa is working on something to track foreground time in https://docs.google.com/document/d/1qm2ZkjvWltsw4M8ZQ0KDJoL917KJz1WBx7TiJqeAFog/edit#heading=h.d9ym5hmnlf8u.

I think we need to update this issue to clarify what else is needed. @BenHenning.

**Comment by seanlip** [comment]
Closing since, per discussion with @BenHenning, we probably don't need this any more. Thanks for flagging @adhiamboperes!
