### ISSUE TITLE
Reading text size not scrollable or flexible 

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1802]
**Describe the bug**
Reading Text Size screen not fitting the flexible text

**To Reproduce**
1. Open reading text size screen from options
2. Change text size and see the text size changing above

**Expected behavior**
The complete text should be visible

Mock link - https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/2eaf085a-c2a7-4b1d-b515-5b32f8642669/specs/

**Screenshots**
![Screenshot_2020-09-04-19-03-03-426_org oppia app](https://user-images.githubusercontent.com/25057618/92245167-94d10500-eee1-11ea-956a-30b6cab3b22a.jpg)

**Device**
- Device/emulator being used
- SDK version

**Additional context**

**Comment by anandwana001** [comment]
@prayutsu would you like to work on this?

**Comment by prayutsu** [comment]
> @prayutsu would you like to work on this?

Definitely
