### ISSUE TITLE
Click on Chapter Item in alpha app crash

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1803]
**To Reproduce**
1. Install the alpha apk and setup the app.
2. Click on `Place Values`
3. Click on `Lessons`
4. Click on `Story Item` to go to `StoryAcitivty`
5. Click on `Chapter` item
6. Crash.

**Expected behavior**
Crash should not happen and it should start the exploration.

**Comment by rt4914** [comment]
cc: @BenHenning @anandwana001

**Comment by anandwana001** [comment]
For reference mentioning here 
I tried on the physical device, didn't crash for me.

**Comment by BenHenning** [comment]
Do you have the stack trace for reference?

**Comment by rt4914** [comment]
> Do you have the stack trace for reference?

@BenHenning @anandwana001 

Actually I was just playing it on mobile directly and therefor I do not have the stack trace. 
Also, now I am not even able to encounter this.

Closing this issue as we are not able to reproduce this but will have to keep in might that this might happen again.
