### ISSUE TITLE
Fix StoryFragmentTest.testStoryFragment_clickOnToolbarNavigationButton_closeActivity

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1804]
This test was recently ignored because we realized it wasn't asserting anything, and adding the assertion triggered a failure so the test isn't actually set up correctly.

**Comment by alokbharti** [comment]
@BenHenning can I work on this issue?

**Comment by rt4914** [comment]
> @BenHenning can I work on this issue?

Hello @alokbharti I have sent you one email and I have assigned this issue to you. Thanks.
