### ISSUE TITLE
Lowfi Implementation of My Downloads

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1806]
Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/531223c5-b64d-4d61-a21b-22045e915515/

This issue is tracking the lowfi work of My Downloads.

This will remain blocked until we have full topic-download support ready.

**Comment by BenHenning** [comment]
@rt4914 can you add the issue that this is blocked by (broader downloads support) in the issue title?

**Comment by anandwana001** [comment]
Closing this Issue as I will be creating sub-issues.
