### ISSUE TITLE
Click on "Cancel" in Reveal Solution Dialog, shows the solution

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1809]
This issue can be reproduced.

1. In `Fractions` go to the below mentioned state.
![Screenshot_1599254251](https://user-images.githubusercontent.com/9396084/92285552-34ae8300-ef22-11ea-880e-28a200a5f624.png)

2. Answer incorrectly to get hints. 
3. Reveal all 4 hints.
4. Answer incorrectly again to get "Solution".
5. Click on `Reveal Solution`
6. In the dialog, click on `Cancel`.
7. Notice that it still reveals the solution.

**Expected Result**
Click on `Cancel` should just close the dialog without revealing any solution.

**Comment by BenHenning** [comment]
@rt4914 how hard is this to fix? I'm willing to push this to the beta milestone otherwise.

**Comment by rt4914** [comment]
> @rt4914 how hard is this to fix? I'm willing to push this to the beta milestone otherwise.

So as of now I have spent 40 or so and the solution is not that straight forward right now. Because we have to make sure that even test cases are written and passes properly. I think it will take more time as of now. So lets shift this to Beta.

**Comment by BenHenning** [comment]
Sounds good. This is enough of an edge case that it probably won't majorly impact the learner's experience so deferring it sounds reasonable.
