### ISSUE TITLE
Renaming the admin profile creates a new one

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1810]
**Describe the bug**
Renaming the admin profile creates a new one

**To Reproduce**
1. Log into the account account
2. Open nav drawer
3. Go to admin controls
4. Go to edit profiles
5. Select admin profile
6. Rename the profile
7. Navigate back to the profile chooser
8. Observe there are now two admin accounts (note that both of these have administrator privileges, too)

**Expected behavior**
Renaming shouldn't duplicate accounts, especially the administrator (it seems to work correctly for regular profiles).

**Device**
- Device: Pixel XL
- SDK version: 29

**Comment by BenHenning** [comment]
Doesn't seem bad enough to be an alpha blocker--marking for beta.

**Comment by ranjsa** [comment]
@BenHenning  Can I work on this issue?

**Comment by rt4914** [comment]
@ranjsa I have assigned this PR to you. Thanks.

**Comment by chrk2205** [comment]
@rt4914 
can i work on this??
and also can oppia-android has two admin profiles!!?

**Comment by rt4914** [comment]
@chrk2205 It is already assigned to @ranjsa 
Also, two admin profiles only in the case when you have a very old version of app already installed. Just re-install the app and it should work.

Also, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by chrk2205** [comment]
@rt4914 i already signed it during gsoc20 selections am i supposed to do it again??
@ranjsa can i work on this??
thankyou for reply

**Comment by chrk2205** [comment]
@rt4914 
i already signed it during gsoc20 selections am i supposed to do it again??
thankyou for reply

**Comment by BenHenning** [comment]
@chrk2205 did you fill out the contributor survey? I see that you signed the CLA back in March, but I don't see a record of you filling out the survey.

**Comment by chrk2205** [comment]
> @chrk2205 did you fill out the contributor survey? I see that you signed the CLA back in March, but I don't see a record of you filling out the survey.

@BenHenning 
yes, i filled the survey form!!

**Comment by rt4914** [comment]
> @chrk2205 did you fill out the contributor survey? I see that you signed the CLA back in March, but I don't see a record of you filling out the survey.

Just saw that he was onboarded but I am not able see his entry in the document. https://github.com/oppia/oppia-android/pulls?q=is%3Apr+author%3Achrk2205+

**Comment by rt4914** [comment]
> > @chrk2205 did you fill out the contributor survey? I see that you signed the CLA back in March, but I don't see a record of you filling out the survey.
> 
> Just saw that he was onboarded but I am not able see his entry in the document. https://github.com/oppia/oppia-android/pulls?q=is%3Apr+author%3Achrk2205+

@chrk2205 and @BenHenning Actually it was not needed to sign/fill the CLA again. It was my mistake, I missed your entry in our records.

**Comment by chrk2205** [comment]
Cause of Bug::
https://github.com/oppia/oppia-android/blob/43295cabc654fce6c93d951c1a8b79054cde65f4/app/src/main/java/org/oppia/android/app/profile/ProfileChooserActivityPresenter.kt#L19

`profileManagementController.addProfile(
      name = "Admin",
      pin = "",
      avatarImagePath = null,
      allowDownloadAccess = true,
      colorRgb = -10710042,
      isAdmin = true
    )`

Every time ProfileChooserActivity is opened a new Admin profile is being added, but because of same name i.e., "Admin" the database returns an error, but when we change admin name and reopen the profile chooser a new admin is getting added, which is named as "Admin"

@rt4914 @BenHenning @ranjsa

**Comment by rt4914** [comment]
> Cause of Bug::
> https://github.com/oppia/oppia-android/blob/43295cabc654fce6c93d951c1a8b79054cde65f4/app/src/main/java/org/oppia/android/app/profile/ProfileChooserActivityPresenter.kt#L19
> 
> `profileManagementController.addProfile( name = "Admin", pin = "", avatarImagePath = null, allowDownloadAccess = true, colorRgb = -10710042, isAdmin = true )`
> 
> Every time ProfileChooserActivity is opened a new Admin profile is being added, but because of same name i.e., "Admin" the database returns an error, but when we change admin name and reopen the profile chooser a new admin is getting added, which is named as "Admin"
> 
> @rt4914 @BenHenning @ranjsa

@chrk2205 Your reasoning is correct. But I think instead of solving it at app-module level we should focus on solving this at domain-level module.
We can do this by checking if the admin already exists or not at in `addProfile` function.

**Comment by chrk2205** [comment]
> > Cause of Bug::
> > https://github.com/oppia/oppia-android/blob/43295cabc654fce6c93d951c1a8b79054cde65f4/app/src/main/java/org/oppia/android/app/profile/ProfileChooserActivityPresenter.kt#L19
> > 
> > `profileManagementController.addProfile( name = "Admin", pin = "", avatarImagePath = null, allowDownloadAccess = true, colorRgb = -10710042, isAdmin = true )`
> > Every time ProfileChooserActivity is opened a new Admin profile is being added, but because of same name i.e., "Admin" the database returns an error, but when we change admin name and reopen the profile chooser a new admin is getting added, which is named as "Admin"
> > @rt4914 @BenHenning @ranjsa
> 
> @chrk2205 Your reasoning is correct. But I think instead of solving it at app-module level we should focus on solving this at domain-level module.
> We can do this by checking if the admin already exists or not at in `addProfile` function.

@rt4914 instead we can check if a user exists or not!!
if at least a single user exists  he will be a admin.

**Comment by chrk2205** [comment]
@BenHenning @rt4914 can i take this issue!?
