### ISSUE TITLE
Verify that the alpha build is working & deployed from Play Store

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1811]
This is a process issue to verify that the deployment from the Play Store was successful.

**Comment by BenHenning** [comment]
This was blocked on #1833 since we decided to re-deploy, but now I can re-launch then verify.

**Comment by anandwana001** [comment]
@BenHenning as #1833 is done, can we close this issue?

**Comment by BenHenning** [comment]
Aha, yes! Thanks @anandwana001. I confirmed a week ago that the alpha build is now available on the Play Store for opted in users.

**Comment by BenHenning** [comment]
This also concludes the alpha milestone.
