### ISSUE TITLE
10MB Size for both alpha topics

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1812]
Both Alpha topics `Place Values` and `Multiplication` show `10MB`. This can be correct but still need to check this because the `Place Values` contain `4 explorations` and `Multiplication` contains `7 explorations` and therefore I am assuming that it should have been different.

**Comment by BenHenning** [comment]
This is a good point--I wonder if we're adding the sizes together since I think the full asset directory is around 10MB uncompressed right now.

**Comment by rt4914** [comment]
The topic size is getting correctly displayed in `Info` tab. Tested on `0.8-alpha-091b45a188`
