### ISSUE TITLE
Highfi of Profile Picture Selection Dialog is not correct

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1813]
The Highfi of Profile Picture Dialog looks like this:
![profile_picture_eror](https://user-images.githubusercontent.com/9396084/92289775-4ea29280-ef2f-11ea-8ffb-4444dd9cff4e.png)

Instead it should like this: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/7fcddeef-4d62-4565-b763-81e89f064a5d/

**Comment by prayutsu** [comment]
@rt4914 So, do we only want changes in DialogBox or we want a blank background (light or dark corresponding to the chosen theme on the device)?

**Comment by rt4914** [comment]
> @rt4914 So, do we only want changes in DialogBox or we want a blank background (light or dark corresponding to the chosen theme on the device)?

We should focus only on the alignment of the texts, like the left alignment of all texts should be same. Everything else should  be avoided in terms of UI.
