### ISSUE TITLE
Add support for refresher explorations in the exploration player

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#182]
For parity with Oppia web, we need to add support for jumping the learner back to another exploration as a refresher if they are struggling with an exploration. It's not clear currently if their progress in the current exploration should be saved, or if they need to start over.

The current ExplorationProgressController is being modeled such that progress always resets when you leave the exploration.

**Comment by rt4914** [comment]
@BenHenning Is this issue blocked on clarification or someone can work on this?

**Comment by BenHenning** [comment]
I think this was going away in favor of concept cards, but it needs confirmation with Sean.

**Comment by seanlip** [comment]
It is going away in favour of concept cards.

**Comment by BenHenning** [comment]
Ninja response. :) Thanks @seanlip. In that case, we can drop this.
