### ISSUE TITLE
How to approach Bugs? - Documentation

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1820]
We should mention in wiki about how we should approach a bug by following below mentioned points:

1. First try to find the exact reasons of the bugs.
2. Once you have identified the reason, write a test case which actually fails because of the bug. (This will be needed in future).
3. Now work towards solution.
4. Now, the test cases which were written in (2.) should pass and that way we can be sure that the bug has been fixed.
So at this stage you should focus on step 1.

**Comment by BenHenning** [comment]
I was going to suggest you add this as documentation after seeing you give this advice on the other thread. Probably worth prioritizing this as part of the onboarding workflow.

**Comment by seanlip** [comment]
@MohitGupta121 PTAL and triage for the wiki updates as needed. Thanks!

**Comment by MohitGupta121** [comment]
@seanlip sure, I will add this in my list.
