### ISSUE TITLE
Lowfi: Tablet: StoryActivity Landscape + Portrait

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1824]
This issue is tracking the full low-fi work of `StoryActivity` Tablet (Landscape + Portrait)

Mock: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/64ef596d-f0ee-48fe-afc2-2ae40367e382/
https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/d70a3ade-826a-4ac6-95e6-907a24d7b896/

Major work items:
- [ ] Vertical dash line with progress
- [x] Inactive card - lock/blur effect.
- [ ] RTL Supportive
**Note : Please test UI for RTL support, prior to merging this fix.**

**Comment by rt4914** [comment]
@prayutsu Thanks. I will refer to your PRs whenever I work on it.

**Comment by veena14cs** [comment]
**Note : Please test UI for RTL support, prior to merging this fix.**
