### ISSUE TITLE
Question player progress bar & hint bulb overlap unexpectedly

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1839]
Question player progress bar & hint bulb overlap unexpectedly. See screenshot:

<img src="https://user-images.githubusercontent.com/12983742/95254165-55455380-07d4-11eb-99bf-00e6f1586f38.png" width="250" />

Ideally, we should make sure there's sufficient separation between the question progress bar & hint bulbs so that they don't overlap.

Note that this also seems to happen in the question player.

Final Solution as per below mentioned conversation.

**Scale Progress Bar to Fit** 
<img src="https://user-images.githubusercontent.com/22177674/95289733-5603d700-0820-11eb-8d01-66d625b51510.png" width="250" />

"Scale Progress Bar to Fit" will animate to the right once the hint button appears, which looks more natural flowing than if it were to move up.
As per the image above the `Progress Bar` size will change when the hint bulb appears and the `Progress Bar` size will change (going back to normal) once the hint bulb disappears. Note that this change should have animation in place so that it does not look abrupt change.

Reference: https://github.com/oppia/oppia-android/issues/1839#issuecomment-704698704

**Comment by BenHenning** [comment]
TODO: fill this in with more detial.

**Comment by BenHenning** [comment]
Notice in the mocks that there should be enough space in the exploration player for the hint button: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/e789f7c6-c677-4c76-b3e5-d603fd84d1e1/.

@mschanteltc should we also be guaranteeing enough space for the question progress bar to not overlap with hints?

**Comment by mschanteltc** [comment]
Great question, and thank you for catching this case. There are two ways I came up with that can solve this problem:

**Move Progress Bar Above Hint Button**
![PM Q5 (Numeric Input, No Answer) – 1](https://user-images.githubusercontent.com/22177674/95289737-57350400-0820-11eb-87b2-0a2247add648.png)

**Scale Progress Bar to Fit** 
![PM Q5 (Numeric Input, No Answer) – 2](https://user-images.githubusercontent.com/22177674/95289733-5603d700-0820-11eb-8d01-66d625b51510.png)

"Scale Progress Bar to Fit" appears to be the better choice because it'll animate to the right once the hint button appears, which looks more natural flowing than if it were to move up. In "Move Progress Bar Above Hint Bar," there is a significant amount of empty space below the progress bar that makes the spacing looks awkward. 

@seanlip Do you have any opinions on these designs?

**Comment by seanlip** [comment]
I do lean slightly towards the second option (assuming at most one lightbulb shows at a time?) -- I don't have a strong reason, it just feels a bit better to me. But I don't really have strong feelings in either direction, so happy to defer to y'all on this. 

Btw, why is it "Practic Mode" in the navbar? That looks like a misspelling.

**Comment by mschanteltc** [comment]
Thanks for the input Sean! And I fixed the typos and updated the [mocks](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/c4b0dfb3-53b4-491e-a759-818e096183fd/). @BenHenning It looks like we'll be using the second option. Is there anything else that needs consideration?

**Comment by misterjedu** [comment]
@BenHenning 
How do I get to this screen from my emulator? Which fragment?

I want to be assigned to this issue.

**Comment by BenHenning** [comment]
Thanks @mschanteltc & Sean. Chantel: to be clear, should we always size & position the progress bar in perspective of the second screen (even if the hint bulb is not showing), or should we only make it smaller when the bulb is showing?

**Comment by BenHenning** [comment]
@misterjedu you may want to wait until Chantel and I finish finalizing the UX before working on this. :) I suggest looking at other starter issues that are currently unassigned.

That being said, you can navigate to this screen by:
1. Opening the app
2. Selecting the default (admin) profile to open the home screen
3. Navigating to the fractions topic
4. Switch to the 'Practice' tab
5. Select one or more skills via the checkboxes
6. Click 'start' to start a practice session

That will bring you to the actual training flow where the progress bar will show up. Once there, in order to make the hint bulb show enter two consecutively wrong answers and it should appear in the lower left (if it doesn't, provide a correct answer and try the same twice-wrong approach on a different question since not all questions in the test lessons have hints).

**Comment by mschanteltc** [comment]
We should only make it smaller when the bulb is showing. The progress bar should animate either before or simultaneously when the hint button appears.

**Comment by ForgottenProgramme** [comment]
Hey, @BenHenning and @mschanteltc! 
I am Mahe from India. 
I was going through your conversation above and I would like to make a suggestion. 

From what I observed, the hint button appears when the user has attempted a question wrongly the second time. 
Along with the hint button, warning text also appears saying "No. That's not correct! (Some more text related to the question.)" 

I feel, it makes more sense if the hint button is placed immediately after this warning text. 
The user is more likely to notice the appearance of the hint button (the bulb symbol) if it appears near the text (which is nearer to the center of the screen) than the progress bar which is at the bottom. 
![hint](https://user-images.githubusercontent.com/65779580/97293775-22422d00-1873-11eb-8844-3fefacece40b.png)

And perhaps, if we add the hint button at the end of the warning text, we can change the button to be a golden/yellow bulb symbol without any background.

**Comment by rt4914** [comment]
> Hey, @BenHenning and @mschanteltc!
> I am Mahe from India.
> I was going through your conversation above and I would like to make a suggestion.
> 
> From what I observed, the hint button appears when the user has attempted a question wrongly the second time.
> Along with the hint button, warning text also appears saying "No. That's not correct! (Some more text related to the question.)"
> 
> I feel, it makes more sense if the hint button is placed immediately after this warning text.
> The user is more likely to notice the appearance of the hint button (the bulb symbol) if it appears near the text (which is nearer to the center of the screen) than the progress bar which is at the bottom.
> ![hint](https://user-images.githubusercontent.com/65779580/97293775-22422d00-1873-11eb-8844-3fefacece40b.png)
> 
> And perhaps, if we add the hint button at the end of the warning text, we can change the button to be a golden/yellow bulb symbol without any background.

Thanks @ForgottenProgramme 
@BenHenning  and @mschanteltc will get back to you on this.
Also, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can know what you are interested working on.

**Comment by ForgottenProgramme** [comment]
Hey, @rt4914 ! Okay. Will do. :)

**Comment by mschanteltc** [comment]
Thanks for the suggestion @ForgottenProgramme! An additional reason why the hint button would be triggered is if the learner has not attempted to submit an answer after 30 seconds have elapsed. There are usually multiple hints tied to a single problem, so after another 30 seconds have passed, another hint would appear.

This would mean that even if the user has not attempted to answer the problem, a hint would still be available to them. So because of that, we won't be able to have the hint button near the feedback since there is none available.

**Comment by ForgottenProgramme** [comment]
Hello, @mschanteltc. Thanks for telling me that. 
Something comes to my mind; 
If 30 secs pass and the user hasn't attempted to answer the question, we might, along with the hint button, display a feedback message, "You haven't attempted to answer the question. Would you like a hint?" *   a hint button here  * 
What do you think?

**Comment by mschanteltc** [comment]
If feedback were to appear, it might distract the user while they read and focus on the question. A sudden appearance of a textbox might cause the user to shift their attention to the feedback to read it. The hint button would be less invasive because it's an identifiable icon that does not need too much attention.

**Comment by ForgottenProgramme** [comment]
Hey @mschanteltc ,
I see what you are trying to say. 
But the user has already spent 30 sec reading and focusing on the question. They are clearly in need of help/hint. 
The feedback message is only one(or two) sentence. Not a paragraph that would make the user 'forget' the question they were reading. 
And if the hint button is not invasive enough and doesn't get attention, it is not of much use. 

Anyway, the point remains, the hint button should appear at a location on the screen where the user is currently focusing (the center-ish place on the screen where the question and the answer options appear) so that it can be promptly noticed.

**Comment by seanlip** [comment]
@ForgottenProgramme, please note that:
- Some questions take longer than 30 sec to answer.
- We are still thinking through how prominent we want the hint button to be. It is not the case that we necessarily want students to use it as soon as it appears, and we don't want it to be invasive. Sometimes the questions require thinking and we do want the students to try and figure things out on their own, and only reach for the hint button when stuck.

We are currently thinking through the hint functionality more (at least for the Web version, where there really is more of a discoverability problem), but for the moment, we are not planning to change this along the lines you suggest, for the reasons given above -- at least, not without clearer evidence/feedback from students who are using the lessons that such a change wouldn't be distracting.

**Comment by ForgottenProgramme** [comment]
Hey, @seanlip ! 

> * We are still thinking through how prominent we want the hint button to be. It is not the case that we necessarily want students to use it as soon as it appears, and we don't want it to be invasive. Sometimes the questions require thinking and we do want the students to try and figure things out on their own, and only reach for the hint button when stuck.

Yes. This makes sense. The purpose of this app is to make the students learn. Therefore the app should let the student brainstorm to some degree before displaying hints. Learning and growth is faster when the student is compelled to think hard for the solution of a problem.   

> but for the moment, we are not planning to change this along the lines you suggest, for the reasons given above -- at least, not without clearer evidence/feedback from students who are using the lessons that such a change wouldn't be distracting.

Yes. That will be the best. We make changes based on the feedback from user who'll actually be using this app to learn.

**Comment by rt4914** [comment]
Updated issue description.

**Comment by navneetsaluja** [comment]
May I work on this?

**Comment by prayutsu** [comment]
@rt4914 @BenHenning Is this still a good first issue?

**Comment by FareesHussain** [comment]
> @rt4914 @BenHenning Is this still a good first issue?

I think it is as we just need to add constraints to the progress bar

**Comment by aishapervin** [comment]
I would like to work on this.Please assign me this work.

**Comment by aishapervin** [comment]
I have fixed this.Shall i create a pr for this?

**Comment by FareesHussain** [comment]
@aishapervin Thanks for showing interest in Oppia.
Before you start Please have a look at [wiki](https://github.com/oppia/oppia-android/wiki#onboarding-instructions) which will help you in setting up the project and once you sign the CLA and fill the survey we can assign this to you

**Comment by aishapervin** [comment]
Done.
