### ISSUE TITLE
Replace Language code with icon in AudioBar

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1845]
Currently Audio Bar in exploration has a language code, as shown below:
![Screenshot_1600232780](https://user-images.githubusercontent.com/9396084/93294598-9b784a00-f808-11ea-9395-2b6ba008b2c4.png)

We should replace the language code to [icon](https://drive.google.com/file/d/1jPRimZBxcPHeEHwlmTUcLrDcwZyVt0gl/view?usp=sharing) as shown below:
<img width="359" alt="Screenshot 2020-09-16 at 10 37 42 AM" src="https://user-images.githubusercontent.com/9396084/93294642-bb0f7280-f808-11ea-8409-a78c463c312f.png">

Reference: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/d74f0571-471f-4ea6-a3a5-32e135253c56/

The tests in AudioFragmentTest need to be updated (see the TODOs there).

**Comment by MaskedCarrot** [comment]
Hello, can I work on this issue?

**Comment by aggarwalpulkit596** [comment]
@MaskedCarrot sure go ahead

**Comment by MaskedCarrot** [comment]
I tried creating a pr but the bot closes it every time and I can't figure out the reason for this from the documentation. Can you please help me.

**Comment by aggarwalpulkit596** [comment]
https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up you have to follow the steps here first. Have you completed all of the steps mentioned here ?

**Comment by rt4914** [comment]
> I tried creating a pr but the bot closes it every time and I can't figure out the reason for this from the documentation. Can you please help me.

@MaskedCarrot Thats because you haven't filled the forms on this link: 
https://github.com/oppia/oppia-android/wiki#onboarding-instructions

Also, if you are fully sure that you have filled both the forms - CLA and contributor survey, then when you finish it just take screenshot and share it with us and maybe we can look into the issue. But in most cases it happens if the student does not fill all the details.

**Comment by rt4914** [comment]
Adding @seanlip and @BenHenning if further investigation is needed.

**Comment by seanlip** [comment]
@rt4914 This seems fine now, I think? I see a PR [here](https://github.com/oppia/oppia-android/pull/1860).

**Comment by anandwana001** [comment]
@rt4914 quick question, If we are moving towards icon this means the check the current language a user has to click on the icon and check on the dialog box which language is currently selected. 

Or are we going to have multiple icons which shows language translations? For example with the above icon which shows English and Japanese or may be Chinese, should we go for icons like English to Hindi and for all other translations? 
Because what I think here is the icon say translating from English to Japanses and the audio is in Hindi.

**Comment by rt4914** [comment]
> @rt4914 This seems fine now, I think? I see a PR [here](https://github.com/oppia/oppia-android/pull/1860).

@seanlip Thanks. Everything is correct now.

**Comment by rt4914** [comment]
> @rt4914 quick question, If we are moving towards icon this means the check the current language a user has to click on the icon and check on the dialog box which language is currently selected.
> 
> Or are we going to have multiple icons which shows language translations? For example with the above icon which shows English and Japanese or may be Chinese, should we go for icons like English to Hindi and for all other translations?
> Because what I think here is the icon say translating from English to Japanses and the audio is in Hindi.

@anandwana001 What you have mentioned it actually correct but this was finalised after the user study and as per results, students are not thinking that its audio change from `English to Japanese`, instead its interpreted as `Change Language` option, which makes more sense here. Does this help?

**Comment by anandwana001** [comment]
> > @rt4914 quick question, If we are moving towards icon this means the check the current language a user has to click on the icon and check on the dialog box which language is currently selected.
> > Or are we going to have multiple icons which shows language translations? For example with the above icon which shows English and Japanese or may be Chinese, should we go for icons like English to Hindi and for all other translations?
> > Because what I think here is the icon say translating from English to Japanses and the audio is in Hindi.
> 
> @anandwana001 What you have mentioned it actually correct but this was finalised after the user study and as per results, students are not thinking that its audio change from `English to Japanese`, instead its interpreted as `Change Language` option, which makes more sense here. Does this help?

Yes, sounds good to me.

**Comment by BenHenning** [comment]
@MaskedCarrot are you still working on this issue?

**Comment by MaskedCarrot** [comment]
@BenHenning I think this is blocked because audioFragmentTest are failing.

**Comment by anandwana001** [comment]
> @BenHenning I think this is blocked because audioFragmentTest are failing.

It's merged. You can continue the work, if you need any help in testing part let's connect over Gitter.
