### ISSUE TITLE
Remove voiceover from test_exp_id_0.json

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1846]
**Describe the bug**
In the last `state` of `Third Exploration`, toolbar shows `audio-icon` but it does not work because the audio reference is incorrect in json files.

**To Reproduce**
1. Go to `First Test Topic`
2. Finish `Second Exploration`
3. Go to `Third Exploration`
4. Go to `END` state as shown in below image
![Screenshot_1600233703](https://user-images.githubusercontent.com/9396084/93295828-923cac80-f80b-11ea-81e1-4d83c1f55a2c.png)

5. Click on `Audio-icon` in toolbar and play audio
6. Audio is not playable.

**Expected behavior**
Either the audio should be playable or we should remove the audio itself. 
We will remove the audio because everywhere else we are using `What is a Ratio?` exploration for audio related testing.

Update `test_exp_id_0.json` file to remove the voiceover from `END` state.

**Comment by rasacharjee** [comment]
I removed the recorded_voiceovers from the file test_exp_id_0.json. A screenshot is attached below, which shows the change.
@rt4914 can i make a pr.
![oppia-audio_removed](https://user-images.githubusercontent.com/53570696/93638618-33e31a00-fa15-11ea-9509-928d6e9e8c97.jpeg)

**Comment by rasacharjee** [comment]
@rt4914 sir, if it's okay please help me to make my first contribution in the project

**Comment by rt4914** [comment]
> @rt4914 sir, if it's okay please help me to make my first contribution in the project

Hello @rasacharjee Yes you can create a PR. I have sent you one email with steps to create a successful PR. If you need any further help feel free to reply back to that email. Thanks!

**Comment by anandwana001** [comment]
@rasacharjee Are you still working on this issue?

**Comment by misterjedu** [comment]
@anandwana001, can I work on this?

Please, assign this to me

**Comment by anandwana001** [comment]
@misterjedu Done

**Comment by misterjedu** [comment]
@anandwana001 PTAL
