### ISSUE TITLE
Resolve ktlint max line in app module test

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1855]
**Describe the bug**
As we have ktlint setup on actions check, we have one of the checks which check if there are more than 100 char length and we are disabling this check, in some places, like name of the test functions. 

**Expected behavior**
We want to remove this check by resolving the char length limit to not more than 100 char long. We want to abbreviate a few names in the test functions name to make this issue solve.  

Reach out to me(@anandwana001)  in case you want to work on this.

**Comment by rasacharjee** [comment]
Hello @anandwana001 sir, I want to work on the issue, can you please help me

**Comment by anandwana001** [comment]
> Hello @anandwana001 sir, I want to work on the issue, can you please help me

@rasacharjee Sure, Thanks for showing interest. I suggest you start with [onboarding instructions first](https://github.com/oppia/oppia-android/wiki#onboarding-instructions). 
Then we can connect over Gitter and you can start working on this issue.

**Comment by rasacharjee** [comment]
@anandwana001 Sir, I have followed the on boarding instructions but have some doubts in the linters section. I have placed a query over gitter on that and looking forward to the journey.

**Comment by rt4914** [comment]
Added to SLoP-25 points but can be shifted to SLoP-75 if there are changes in too many files. Needs discussion.

**Comment by soamOne** [comment]
Hey @anandwana001 can I work on this?

**Comment by soamOne** [comment]
![Screenshot from 2020-10-02 01-06-36](https://user-images.githubusercontent.com/65867928/94855107-a1e30480-044b-11eb-822e-e7b10088c95b.png)

**Comment by soamOne** [comment]
@anandwana001 are we aiming to resolve this check in all these files:
![Screenshot from 2020-10-02 01-06-36](https://user-images.githubusercontent.com/65867928/94855257-dbb40b00-044b-11eb-9bde-04707cb09502.png)

**Comment by BenHenning** [comment]
That includes some non test files, but we do want to fix that everywhere @soamOne.

**Comment by soamOne** [comment]
@BenHenning so should I go ahead and fix all these files in one PR only? Also, is there any standard format we should follow for abbreviating?

**Comment by BenHenning** [comment]
I thinking fixing them all in one PR is fine. For abbreviating, we generally want to break at the higher syntactical element (think left to right, break at the first symbol you encounter rather than one later on). See: https://developer.android.com/kotlin/style-guide#where_to_break.

If you’re unsure, you could start with fixing a few lines and send me the draft PR. I can verify if whether you’re wrapping the code correctly before you attempt all of them.

**Comment by soamOne** [comment]
Okay @BenHenning, that sounds good:)

**Comment by nskirkey** [comment]
Hello @anandwana001 , I was hoping to be assigned this issue.

**Comment by anandwana001** [comment]
@nskirkey Any update on this?
If you haven't started working on it, I am thinking to split this issue into multiple sub-issues as this will create a large change.

**Comment by anandwana001** [comment]
unassigning @nskirkey and splitting this issue into sub-issues.

**Comment by anandwana001** [comment]
closing this issue as I had created sub-issues.

**Comment by nskirkey** [comment]
Sorry, didn't see this until now. I'll take a look at the sub issues.
