### ISSUE TITLE
Fix app module tests in topic for Robolectric 

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1868]
Currently, the app module test cases in topic are passing on Espresso but they should also pass on Robolectric. Fix these below mentioned files to make sure that the tests pass on Robolectric.

You can run robolectric tests by following these steps: https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-roboelectric-tests

Fixing test cases will need to introduce TextApplicationComponent. This can be seen [here](https://github.com/oppia/oppia-android/pull/1680/commits/4729d551b86282ce617e1d53f2762416758785a1). 

- [x] ConceptCardFragmentTest - https://github.com/oppia/oppia-android/pull/2075
- [x] TopicFragmentTest - https://github.com/oppia/oppia-android/pull/2072
- [x] TopicInfoFragmentTest - https://github.com/oppia/oppia-android/pull/2104
    - [x] `testTopicInfoFragment_loadFragment_configurationLandscape_imageViewNotDisplayed `
    - [x] Few ignored test cases due to `maxLines()` timing in robolectric
- [x] TopicLessonsFragmentTest - https://github.com/oppia/oppia-android/pull/2104
    - [x] `testLessonsPlayFragment_loadRatiosTopic_chapterListIsNotVisible `
   - [x] `testLessonsPlayFragment_loadRatiosTopic_clickExpandListIconIndex1_clickExpandListIconIndex2_chapterListForIndex1IsNotDisplayed `
- [x] TopicPracticeFragmentTest - https://github.com/oppia/oppia-android/pull/2104
    - [x] `testTopicPracticeFragment_loadFragment_selectSubtopics_clickStartButton_skillListTransferSuccessfully ` Flaky for espresso, All are passing for Robolectric
- [x] TopicRevisionFragmentTest
    - [x] `testTopicRevisionFragment_loadFragment_configurationChange_checkSpanCount_isThree`

**Comment by anandwana001** [comment]
Closing this issue as it is done.
