### ISSUE TITLE
Fix DragDropTestActivityTest for Robolectric

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1869]
Currently, DragDropTestActivityTest are passing on Espresso but they should also pass on Robolectric. Fix these below mentioned files to make sure that the tests pass on Robolectric.

You can run robolectric tests by following these steps: https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-roboelectric-tests

Fixing test cases will need to introduce TextApplicationComponent. This can be seen [here](https://github.com/oppia/oppia-android/pull/1680/commits/4729d551b86282ce617e1d53f2762416758785a1).

**Comment by rt4914** [comment]
@Sarthak2601 I think we should split these tests into separate issues? WDYT?

**Comment by Sarthak2601** [comment]
> @Sarthak2601 I think we should split these tests into separate issues? WDYT?

Yes, good point. I'll split them up.

**Comment by anandwana001** [comment]
@Sarthak2601 @rt4914 we are good to close this issue. 

<img width="1440" alt="Screenshot 2020-11-06 at 14 01 23" src="https://user-images.githubusercontent.com/25057618/98343948-94b3c980-2038-11eb-90f1-d6685a7186fc.png">
