### ISSUE TITLE
Fix app module tests in settings.profile for Robolectric 

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1870]
Currently, the app module test cases in the settings.profile file are passing on Espresso but they should also pass on Robolectric. Fix these below mentioned files to make sure that the tests pass on Robolectric.

You can run robolectric tests by following these steps: https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-roboelectric-tests

Fixing test cases will need to introduce TextApplicationComponent. This can be seen [here](https://github.com/oppia/oppia-android/pull/1680/commits/4729d551b86282ce617e1d53f2762416758785a1). 

- [x]  ProfileEditActivityTest - https://github.com/oppia/oppia-android/pull/1925
- [x]   ProfileRenameActivityTest - https://github.com/oppia/oppia-android/pull/2067

**Comment by alokbharti** [comment]
Assigning this to myself as I had already made a PR (#1925 ) related to ProfileEditViewModel and it requires fixing ProfileEditActivityTest

**Comment by rt4914** [comment]
> Assigning this to myself as I had already made a PR (#1925 ) related to ProfileEditViewModel and it requires fixing ProfileEditActivityTest

Thanks @alokbharti

**Comment by anandwana001** [comment]
@alokbharti Unassigning you as you are solving only a part of it, not the complete issue. This blocks the issue to be taken for other contributors.

**Comment by alokbharti** [comment]
Test cases in ProfileEditActivityTest class are fixed. @Sarthak2601 please mark it complete and I think this issue can be closed now.

**Comment by anandwana001** [comment]
closing this issue as it is fixed in multiple PR's
