### ISSUE TITLE
Fix OnboardingFragmentTest for Robolectric

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1873]
Currently, the tests in OnboardingFragmentTest are passing on Espresso but they should also pass on Robolectric. Fix this file to make sure that the tests pass on Robolectric.

You can run robolectric tests by following these steps: https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-roboelectric-tests

Fixing test cases will need to introduce TextApplicationComponent. This can be seen [here](https://github.com/oppia/oppia-android/pull/1680/commits/4729d551b86282ce617e1d53f2762416758785a1).

**Comment by BenHenning** [comment]
@Sarthak2601 & @rt4914 I suggest splitting these to be per-test for better parallelization. Also, please make the titles consistent with the work being done--at the moment it's a bit difficult to find specifics about the issue from the title itself.

**Comment by Sarthak2601** [comment]
> @Sarthak2601 & @rt4914 I suggest splitting these to be per-test for better parallelization. Also, please make the titles consistent with the work being done--at the moment it's a bit difficult to find specifics about the issue from the title itself.

Done.

**Comment by prayutsu** [comment]
@MohamedMedhat1998 I want to work on this

**Comment by prayutsu** [comment]
@anandwana001 Actually, I was working on the PR and I was waiting for your or @rt4914 response on it. I was a bit stucked so can you please help me here?
