### ISSUE TITLE
Fix app module tests in home and administrator controls for Robolectric

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1874]
Currently, the app module test cases in home and administrator controls folders are passing on Espresso but they should also pass on Robolectric. Fix these below mentioned files to make sure that the tests pass on Robolectric.

You can run robolectric tests by following these steps: https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-roboelectric-tests

Fixing test cases will need to introduce TextApplicationComponent. This can be seen [here](https://github.com/oppia/oppia-android/pull/1680/commits/4729d551b86282ce617e1d53f2762416758785a1). 

- [x]   HomeActivityTest
    - [x] `testHomeActivity_configurationChange_checkSpanForItem0_spanSizeIsThreeOrFour` - https://github.com/oppia/oppia-android/pull/2154
    - [x] Other test are fixed here - https://github.com/oppia/oppia-android/pull/2086
- [x]   RecentlyPlayedFragmentTest
    - [ ] `testRecentlyPlayedTestActivity_configurationChange_checkSpanForItem2_spanSizeIsThreeOrFour` - https://github.com/oppia/oppia-android/pull/2156
    - [ ] `testRecentlyPlayedTestActivity_configurationChange_checkSpanForItem0_spanSizeIsThreeOrFour` - https://github.com/oppia/oppia-android/pull/2156
    - [x] other tests are handled in https://github.com/oppia/oppia-android/pull/2071
- [x]  AdministratorControlsActivityTest - https://github.com/oppia/oppia-android/pull/2084

**Comment by anandwana001** [comment]
Closing this issue as it is completed in sub-prs.
