### ISSUE TITLE
Fix OngoingTopicListActivityTest for Robolectric

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1877]
Currently, the tests in OngoingTopicListActivityTest are passing on Espresso but they should also pass on Robolectric. Fix this file to make sure that the tests pass on Robolectric.

You can run robolectric tests by following these steps: https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-roboelectric-tests

Fixing test cases will need to introduce TextApplicationComponent. This can be seen [here](https://github.com/oppia/oppia-android/pull/1680/commits/4729d551b86282ce617e1d53f2762416758785a1).

**Comment by prayutsu** [comment]
@Sarthak2601 Tests are already passing on robolectric and espresso, please confirm it once

**Comment by Sarthak2601** [comment]
Yes, confirming that these tests pass on both robolectric and espresso. Hence, closing this issue. Thanks @prayutsu!
