### ISSUE TITLE
Thoroughly test FractionInputHasDenominatorEqualToRuleClassifier

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1880]
Since the FractionInputHasDenominatorEqualToRuleClassifier was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality. 

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by TheRealJessicaLi** [comment]
@BenHenning Can I take this?

**Comment by BenHenning** [comment]
@TheRealJessicaLi normally we don’t encourage having more than two issues simultaneously, but since all of this work is related I think that’s fine.
