### ISSUE TITLE
Thoroughly test FractionInputHasFractionalPartExactlyEqualToRuleClassifier

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1881]
Since the FractionInputHasFractionalPartExactlyEqualToRuleClassifier was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality. 

Useful reference -https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by TheRealJessicaLi** [comment]
@BenHenning Can I take this? All the fraction classifier tests should be relatively straightforward now that we merged my PR for #1898

**Comment by BenHenning** [comment]
@TheRealJessicaLi sure! Assigning this over to you.
