### ISSUE TITLE
Shift NumericInput Rules test to separate sub-package

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1882]
`NumericInputEqualsRuleClassifierProviderTest.kt`
`NumericInputIsLessThanRuleClassifierProviderTest.kt`
`NumericInputIsLessThanOrEqualToRuleClassifierProviderTest.kt`
`NumericInputIsInclusivelyBetweenRuleClassifierProviderTest.kt`
`NumericInputIsGreaterThanRuleClassifierProviderTest.kt`
`NumericInputIsGreaterThanOrEqualToRuleClassifierProviderTest.kt`

Shift all these to separate package named `numberinput` in https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by soamOne** [comment]
Hello @rt4914, I would like to work on this issue if possible.

**Comment by rt4914** [comment]
@BenHenning I have assigned this PR to @soamOne on request.

**Comment by soamOne** [comment]
Thanks @rt4914 .

**Comment by soamOne** [comment]
Hey @rt4914, I cannot find 'tree' inside the repo. Clicking on the given link also returns 404.

**Comment by BenHenning** [comment]
This isn't fully fixed, see: https://github.com/oppia/oppia-android/pull/1909#issuecomment-700407121 and https://github.com/oppia/oppia-android/pull/1909#issuecomment-700409975.

**Comment by BenHenning** [comment]
Also, it was moved to the incorrect place: we are using org/oppia/android/domain not org/oppia/domain.

**Comment by BenHenning** [comment]
Remaining things that should be done per my quick review of the PR:
1. The package of the tests needs to match their directory structure
2. The tests should be under org/oppia/android/domain nor org/oppia/domain
3. The domain module's BUILD.bazel file should be updated to point to the correct test files if they've moved
4. The new package name should be ``numericinput`` not ``numberinput`` for consistency with the interaction name

**Comment by rt4914** [comment]
> * The domain module's BUILD.bazel file should be updated to point to the correct test files if they've moved

@BenHenning Just checked this on latest develop too and confirmed that it was done incorrectly.

I have doubt in point 3.
- Why did all the test cases pass because BUILD.bazel was not updated. Its because of incorrect PR or the test cases are not dependent on this?

**Comment by BenHenning** [comment]
@rt4914 we don't run or build Bazel tests in CI currently. Strictly speaking, #3 isn't a hard requirement. I actually only noticed these issues because I was building the Bazel tests locally and it took me a bit to figure out why they weren't building. :) We should fix the Bazel file now that we know it's not setup correctly anymore, and try to keep them up-to-date when we remember.

I'm working on adding the builds to CI, but it's running into some performance hiccups: https://github.com/oppia/oppia-android/pull/1904.

Does this help clarify?

**Comment by rt4914** [comment]
> @rt4914 we don't run or build Bazel tests in CI currently. Strictly speaking, #3 isn't a hard requirement. I actually only noticed these issues because I was building the Bazel tests locally and it took me a bit to figure out why they weren't building. :) We should fix the Bazel file now that we know it's not setup correctly anymore, and try to keep them up-to-date when we remember.
> 
> I'm working on adding the builds to CI, but it's running into some performance hiccups: #1904.
> 
> Does this help clarify?

Makes sense. My only concern was about missing changes in bazel file. Thanks for clarification.
