### ISSUE TITLE
Thoroughly test FractionInputHasIntegerPartEqualToRuleClassifier

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1883]
Since the FractionInputHasIntegerPartEqualToRuleClassifier was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality. 

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by prayutsu** [comment]
@MohamedMedhat1998 I would like to work on it

**Comment by MohamedMedhat1998** [comment]
> @MohamedMedhat1998 I would like to work on it

Let's merge #1938 first. It is failing in github checks.

**Comment by MohamedMedhat1998** [comment]
@prayutsu you can start working on this because your work is done in #1938
