### ISSUE TITLE
Thoroughly test TexInputCaseSensitiveEqualsRuleClassifier

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1884]
Since the `TexInputCaseSensitiveEqualsRuleClassifier` was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by alokbharti** [comment]
@anandwana001 , can you assign me on this issue?

**Comment by prayutsu** [comment]
@alokbharti Apologies, you may continue your work, Thanks for informing
