### ISSUE TITLE
Thoroughly test FractionInputHasNumeratorEqualToRuleClassifier

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1887]
Since the FractionInputHasNumeratorEqualToRuleClassifier was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by TheRealJessicaLi** [comment]
@BenHenning Can I take this?

**Comment by BenHenning** [comment]
Sure, assigning.
