### ISSUE TITLE
Throughly test `TexInputStartsWithRuleClassifier`

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1888]
Since the `TexInputStartsWithRuleClassifier` was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by Victor-Titan** [comment]
Can I work on this issue? Also there's a spelling mistake in the title.

**Comment by MaskedCarrot** [comment]
Can I work on this issue?

**Comment by BenHenning** [comment]
Sure @MaskedCarrot. Assigning to you.
