### ISSUE TITLE
Throughly test `NumericInputIsWithinToleranceRuleClassifier`

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1889]
Since the `NumericInputIsWithinToleranceRuleClassifier` was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by prayutsu** [comment]
@rt4914 I would like to take up this issue as a SLoP participant

**Comment by rt4914** [comment]
cc: @MohamedMedhat1998
