### ISSUE TITLE
Thoroughly test FractionInputIsEquivalentToAndInSimplestFormRuleClassifier

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1890]
Since the FractionInputIsEquivalentToAndInSimplestFormRuleClassifier was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by Florence-Njeri** [comment]
I am working on this.

**Comment by jcqli** [comment]
I'd like to work on this, thanks!

**Comment by BenHenning** [comment]
Done @jcqli (fyi @anandwana001).
