### ISSUE TITLE
Throughly add tests for NumberWithUnitsInputIsEqualToRuleClassifier

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1891]
Since the `NumberWithUnitsInputIsEqualToRuleClassifier` was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by peculiaruc** [comment]
I am working on this already
