### ISSUE TITLE
Thoroughly test FractionInputIsEquivalentToRuleClassifier

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1892]
Since the FractionInputIsEquivalentToRuleClassifier was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by peculiaruc** [comment]
I am working on this already

**Comment by peculiaruc** [comment]
@rt4914 PTAL. 
My lint checks are failing but I have intended my codes correctly, please advice
