### ISSUE TITLE
Throughly add tests for NumberWithUnitsInputIsEquivalentToRuleClassifier

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1895]
Since the `NumberWithUnitsInputIsEquivalentToRuleClassifier` was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by Aditiwebd** [comment]
I would like to work on this @rt4914
