### ISSUE TITLE
Thoroughly test ItemSelectionInputContainsAtLeastOneOfRuleClassifier

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1896]
Since the ItemsSelectionInputContainsAtLeastOneOfRuleClassifier was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by navneetsaluja** [comment]
Hi! Can I be assigned to this? I'm going to use the tips suggested by Ben [here](https://github.com/oppia/oppia-android/issues/1900#issuecomment-707509170). 
Thanks in advance!

**Comment by BenHenning** [comment]
@navneetsaluja are you actively working on this?

**Comment by navneetsaluja** [comment]
@BenHenning yes I am! Unfortunately due to college exams I wasn'table to work on this during the weekdays, but I'll send a PR within the next 2 days. Sorry for the delay.

**Comment by rt4914** [comment]
> @BenHenning yes I am! Unfortunately due to college exams I wasn'table to work on this during the weekdays, but I'll send a PR within the next 2 days. Sorry for the delay.

@navneetsaluja Ben won't be available for sometime. In your PRs you can mention my username. Thanks.

**Comment by navneetsaluja** [comment]
@rt4914 Sorry, I saw his mail after mentioning him in the comment (it was the same day)

**Comment by rt4914** [comment]
> @rt4914 Sorry, I saw his mail after mentioning him in the comment (it was the same day)

No issues. Thanks.
