### ISSUE TITLE
Thoroughly test ItemSelectionInputDoesNotContainAtLeastOneOfRuleClassifier

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1897]
Since the `ItemSelectionInputDoesNotContainAtLeastOneOfRuleClassifier` was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by JudeUk** [comment]
hello @BenHenning I will like to take this up. can you please provide some useful resources as I might need help successfully completing this thank you.

**Comment by rt4914** [comment]
> hello @BenHenning I will like to take this up. can you please provide some useful resources as I might need help successfully completing this thank you.

@JudeUk Thanks for showing interest in Oppia. Before we start assigning you issues checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by JudeUk** [comment]
hello @rt4914 I have gone through the set up already.

**Comment by JudeUk** [comment]
> > hello @BenHenning I will like to take this up. can you please provide some useful resources as I might need help successfully completing this thank you.
> 
> @JudeUk Thanks for showing interest in Oppia. Before we start assigning you issues checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

I have already

**Comment by rt4914** [comment]
> > > hello @BenHenning I will like to take this up. can you please provide some useful resources as I might need help successfully completing this thank you.
> > 
> > 
> > @JudeUk Thanks for showing interest in Oppia. Before we start assigning you issues checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.
> 
> I have already

Great. I have assigned it to you. Thanks.

**Comment by BenHenning** [comment]
@JudeUk are you working on this?

**Comment by JudeUk** [comment]
> @JudeUk are you working on this?

yes I will make a draft Pr shortly

**Comment by anandwana001** [comment]
unassigning @JudeUk as no update.

**Comment by fsharpasharp** [comment]
I can work on this.

**Comment by anandwana001** [comment]
> I can work on this.

Hi, @fsharpasharp just to confirm before start contributing, Did you completed with the Onboarding process?
https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by fsharpasharp** [comment]
Yes, I have! :)

**Comment by anandwana001** [comment]
> Yes, I have! :)

It looks like you had signed the CLA, but haven't filled the Contributor Survey yet. Please fill the contributor survey from the onboarding instruction before starting with the contribution.

**Comment by fsharpasharp** [comment]
I thought I did, but I've filled the survey for sure now. Let me know if it shows up.
