### ISSUE TITLE
Thoroughly test FractionInputIsExactlyEqualToRuleClassifier

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1898]
Since the `FractionInputIsExactlyEqualToRuleClassifier` was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by TheRealJessicaLi** [comment]
@rt4914 Can I work on this issue?

**Comment by rt4914** [comment]
@aggarwalpulkit596 Thanks.
