### ISSUE TITLE
Thoroughly test ItemsSelectionInputEqualsRuleClassifier

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1899]
Since the ItemsSelectionInputEqualsRuleClassifier was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by peculiaruc** [comment]
I am working on this already

**Comment by peculiaruc** [comment]
@BenHenning    Here I am testing if a set of Html is equal, I have tested for uppercase and lowercase text, please can I also test text with numbers here?

**Comment by BenHenning** [comment]
@peculiaruc can you clarify what you mean by testing with numbers? If you're thinking of adding tests for different cases including plain text, html, and numbers, that sounds good. You should be able to just pass in the inputs & answer strings formatted however you want to the classifier to verify that it handles different cases as expected.

I suggest looking at other rule classifier tests in the codebase for an idea of how to set these tests up.
