### ISSUE TITLE
Rename "DefaultAudioFragment" to "AudioLanguageFragment"

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#1901]
Rename everything related to audio language from "DefaultAudio" to "AudioLanguage"  
By everything we mean:
- Activities
- Xml Files
- Variable Names
- Resources

**Comment by soamOne** [comment]
Hello @MohamedMedhat1998  Sir. I would like to work on this issue if possible.

**Comment by rt4914** [comment]
> Hello @MohamedMedhat1998 Sir. I would like to work on this issue if possible.

@soamOne I have already assigned you https://github.com/oppia/oppia-android/issues/1882 so please start with that issue first. Thanks.

**Comment by MohamedMedhat1998** [comment]
> 
> 
> Hello @MohamedMedhat1998 Sir. I would like to work on this issue if possible.

I agree with @rt4914

**Comment by Arjupta** [comment]
Can I take up with this issue?

**Comment by soamOne** [comment]
Sure @MohamedMedhat1998 @rt4914 .

**Comment by erwinkaaa** [comment]
Hi! I would like to work on this issue if possible!

**Comment by aggarwalpulkit596** [comment]
@erwinkaaai think @soamOne is already working on it.In the meantime you can start with some other good first issu

**Comment by rt4914** [comment]
> Can I take up with this issue?

Assigning this issue to @ARJUPTA as it was available when the contributor commented. 

cc: @BenHenning

**Comment by rt4914** [comment]
> Hi! I would like to work on this issue if possible!

Hello @erwinkaaa . Welcome to Oppia.
Before we assign you any issues to work on have a look at [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by Arjupta** [comment]
Sir after refactoring the code from default audio to audio language , the dagger test component were not recognized by Android studio ,when I tried rebuilding it the build was successfully done but the error persists. Maybe that's the reason my PR is failing. Kindly help @MohamedMedhat1998
