### ISSUE TITLE
Create text based styles in styles.xml

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1914]
The current UI contains a lot of common views and therefore we should define those common styles in `styles.xml` file.
The styles should be defined for following items as a start and can be added more as we start updating the UI.

<img width="394" alt="Screenshot 2020-09-29 at 11 15 23 AM" src="https://user-images.githubusercontent.com/9396084/94517366-670f7f80-0245-11eb-8c1a-3bc21e23454f.png">

**Comment by Arjupta** [comment]
@rt4914 sir can I work on this issue? I will need some help though.

**Comment by rt4914** [comment]
> @rt4914 sir can I work on this issue? I will need some help though.

@ARJUPTA Have a look at the `Assignees` section, if there is a person mentioned that means its already assigned. In this case it is assigned to me.
You can pick any issues from this link: https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22good+first+issue%22

**Comment by Arjupta** [comment]
> > @rt4914 sir can I work on this issue? I will need some help though.
> 
> @ARJUPTA Have a look at the `Assignees` section, if there is a person mentioned that means its already assigned. In this case it is assigned to me.
> You can pick any issues from this link: https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22good+first+issue%22

Ok got it
