### ISSUE TITLE
"Tick icon" disappears on configuration change in QuestionPlayer

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#1930]
**Describe the bug**
"Tick icon" disappears on configuration change in QuestionPlayer

**To Reproduce**
1. Go to 'HomeScreen'
2. Scroll to 'Fractions Topic' and click on it
3. Go to 'Practice'
4. Check any checkbox and click start
5. Choose the correct answer for any question
6. Rotate the screen and notice that the "tick icon" disappeared

**Expected behavior**
The "tick icon" should stay visible for the correct answer

**Comment by ranjsa** [comment]
Hello @MohamedMedhat1998 @anandwana001 @rt4914  
Can I work on this issue

**Comment by anandwana001** [comment]
@ranjsa Sure, you can.

**Comment by anandwana001** [comment]
@ranjsa Any update on this?

**Comment by chrk2205** [comment]
I checked the reason for it!!
in `SubmittedAnswerViewModel` the observable filed `isCorrectAnswer` is turning False ( maybe the default value ) , when there is a configuration change.

If we enter the answer in Landscape mode the tick is visible and after rotating the screen it disappears.
but i cant find why it is happening!!
@rt4914 @MohamedMedhat1998  @anandwana001

**Comment by MohamedMedhat1998** [comment]
> I checked the reason for it!!
> in `SubmittedAnswerViewModel` the observable filed `isCorrectAnswer` is turning False ( maybe the default value ) , when there is a configuration change.
> 
> If we enter the answer in Landscape mode the tick is visible and after rotating the screen it disappears.
> but i cant find why it is happening!!
> @rt4914 @MohamedMedhat1998 @anandwana001

@chrk2205 reading `StatePlayerRecyclerViewAssembler` kdocs may give you more information, please check it.

**Comment by chrk2205** [comment]
@MohamedMedhat1998 @rt4914 
Where can I find the docs ??
Thankyou.

**Comment by anandwana001** [comment]
unassigning @ranjsa as no updates are there.

**Comment by MohamedMedhat1998** [comment]
> @MohamedMedhat1998 @rt4914
> Where can I find the docs ??
> Thankyou.

@chrk2205 here you are: https://github.com/oppia/oppia-android/blob/ec2524cc45ed8b0a0116c8aa4b923cc937365ffa/app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt#L97

**Comment by Russ741** [comment]
I'd like to work on this issue.

**Comment by BenHenning** [comment]
Assigning to you @Russ741. Thanks!

**Comment by anandwana001** [comment]
@Russ741 any update on this?

**Comment by Russ741** [comment]
@anandwana001 I haven't had a chance to look at it yet.

**Comment by MaskedCarrot** [comment]
i am working on this
