### ISSUE TITLE
We should be semantically naming all dimensions.

### ISSUE THREAD

**Issue by ranjsa** [oppia/oppia-android#1944]
**Is your feature request related to a problem? Please describe.**

This issue is explained in this comments.

https://github.com/oppia/oppia-android/pull/1936#issuecomment-704559424
https://github.com/oppia/oppia-android/pull/1936#issuecomment-704996261

**Comment by ranjsa** [comment]
Hello @BenHenning  can you please explain a bit more about the issue you mentioned here https://github.com/oppia/oppia-android/pull/1936#issuecomment-704559424  

Did you mean reordering of space_#dp in dimens.xml in ascending order?

**Comment by BenHenning** [comment]
Apologies @ranjsa I missed your comment from earlier. Has this been resolved?

**Comment by anandwana001** [comment]
Unassigning @ranjsa as no further update.

**Comment by rt4914** [comment]
Closing this PR as all the dimension names have been fixed in current develop by @ARJUPTA
