### ISSUE TITLE
Optimise code in onboarding_slide_final.xml

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1949]
This issue is tracking the optimisation work of `onboarding_slide_final.xml`

1. Make sure that the layout uses `ConstraintLayout` and there is minimal nesting of views. If this view already uses `ConstraintLayout` then it's fine.

2. Make sure that all textviews use the style from `styles.xml` file like `Heading1`, `TextFieldLabel`, `Body`, etc. whichever suits best.

3. If needed introduce common styles too in style.xml file.

While making the above changes the UI should not get affected and the end result should still be same as before (or an optimised version of UI).

If there are multiple files with the same name, update them all.

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by KMaragh** [comment]
I'll pick this up!

**Comment by BenHenning** [comment]
Welcome @KMaragh! Please follow the instructions listed here to go through the onboarding process: https://github.com/oppia/oppia-android/wiki#onboarding-instructions. Once you sign the CLA & fill out the contributor survey, you can start working on this issue.
