### ISSUE TITLE
Optimise code in help_item.xml

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1950]
This issue is tracking the optimisation work of `help_item.xml`

1. Make sure that all textviews use the style from `styles.xml` file like `Heading1`, `TextFieldLabel`, `Body`, etc. whichever suits best.

While making the above changes the UI should not get affected and the end result should still be same as before (or an optimised version of UI).

If there are multiple files with the same name, update them all.

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by Arjupta** [comment]
@rt4914 can I work on this?

**Comment by rt4914** [comment]
> @rt4914 can I work on this?

@ARJUPTA Assigned. Thanks. Also, in future, you can check if no one is working on the issue (by checking assignees section and comments), you can self assign issue to yourself or leave a comment like `I am working on this.`
