### ISSUE TITLE
Optimise hints_summary.xml

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1951]
This issue is tracking the optimisation work of `hints_summary.xml`

1. Make sure that the layout uses `ConstraintLayout` and there is minimal nesting of views. If this view already uses `ConstraintLayout` then it's fine.

2. Make sure that all textviews use the style from `styles.xml` file like `Heading1`, `TextFieldLabel`, `Body`, etc. whichever suits best.

While making the above changes the UI should not get affected and the end result should still be same as before (or an optimised version of UI).

If there are multiple files with the same name, update them all.

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by secjedi** [comment]
I am working on this

**Comment by rt4914** [comment]
@secjedi Do you need to close this PR as this was recreated here: https://github.com/oppia/oppia-android/pull/2006

??

**Comment by ShridharGoel** [comment]
I would like to work on this.

**Comment by priyanka0906** [comment]
may I work on this?

**Comment by rt4914** [comment]
> may I work on this?

@priyanka0906 Assigning you this. For your reference to test this PR once you have made changes follow these steps: https://www.youtube.com/watch?v=iRzGOj1RWoQ&feature=youtu.be

**Comment by priyanka0906** [comment]
> > may I work on this?
> 
> @priyanka0906 Assigning you this. For your reference to test this PR once you have made changes follow these steps: https://www.youtube.com/watch?v=iRzGOj1RWoQ&feature=youtu.be

okay.. thankyou

**Comment by anandwana001** [comment]
@priyanka0906 any update on this?

**Comment by priyanka0906** [comment]
> @priyanka0906 any update on this?

@anandwana001 not yet..

**Comment by anandwana001** [comment]
@priyanka0906 any update on this?

**Comment by arinarora18** [comment]
May I work on this?

**Comment by ArchitJain1201** [comment]
@bkaur-bkj  Can you please assign me this issue?

**Comment by ArchitJain1201** [comment]
@rt4914 Can I also merge all the four files together?

**Comment by rt4914** [comment]
@ArchitJain1201 If the before/after output is exactly same than you can. Basically we aim at merging all files to one but the output UI should not change.

**Comment by ArchitJain1201** [comment]
@rt4914 Can you please check the Heading4 textSize is defined as 18sp but it should be 16sp. ( should I make the necessary changes )

**Comment by sorinmircea** [comment]
I do want to take this task.

**Comment by seanlip** [comment]
@msorins Go for it! I've assigned you :)

**Comment by sorinmircea** [comment]
Taking a look at the current state of hints_summary.xml, it already contains a ConstraintLayout with minimal view nesting and the two TextViews have "@style/TextViewStart" attached to it.

Would there be anything more to be done here or can this issue just be closed?

**Comment by BenHenning** [comment]
@rt4914 can you weigh in on @msorins's question above? I'm not as familiar with what we've done in the past for layout optimization work.

**Comment by rt4914** [comment]
@msorins That's correct. This issue is already fixed in develop and therefore closing this issue now. Thanks @msorins
