### ISSUE TITLE
Fix tools:context in home_activity.xml

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1952]
`home_activity.xml` shows error in `tools:context` because of incorrect path. It should be updated.

**Comment by static-var** [comment]
Is the issue up for grabs?

**Comment by rt4914** [comment]
> Is the issue up for grabs?

@unused-variable 
Welcome to Oppia. Before we can assign you any issue, please have a look at our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by static-var** [comment]
Done!

**Comment by rt4914** [comment]
> Done!

@unused-variable
Have you done both? CLA and survey form? Before I am not able to find your entry in our database.

https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by rt4914** [comment]
> Done!

Assigned. Thanks.
