### ISSUE TITLE
Optimise code in profile_chooser_fragment.xml

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#1954]
This issue is tracking the optimization work of `profile_chooser_fragment.xml`

1. Make sure that the layout uses `ConstraintLayout` and there is minimal nesting of views. If this view already uses `ConstraintLayout` then it's fine.

2. Make sure that all TextViews use the style from `styles.xml` file like `Heading1`, `TextFieldLabel`, `Body`, etc. whichever suits best.

While making the above changes the UI should not get affected and the end result should still be the same as before (or an optimized version of UI).

If there are multiple files with the same name, update them all.

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by peculiaruc** [comment]
Hi! I am interested in this issue. Please assign it to me.

**Comment by MohamedMedhat1998** [comment]
Welcome to Oppia, @peculiaruc!  
Thanks for your interest in contributing to Oppia.  
Please make sure to read the [home wiki page](https://github.com/oppia/oppia-android/wiki) and sign the CLA. Once you do that, we can directly assign issues to you.

**Comment by peculiaruc** [comment]
I have done those please

**Comment by peculiaruc** [comment]
This task will involve me changing Linearlayout used by making it a constraint layout and add necessary constraints. For  TextView I will maintain the ID but modify if need be. Can I go-ahead, please?
