### ISSUE TITLE
 Optimise code in profile_chooser_add_view.xml 

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#1956]
This issue is tracking the optimization work of `profile_chooser_add_view.xml`

1. Make sure that the layout uses `ConstraintLayout` and there is minimal nesting of views. If this view already uses `ConstraintLayout` then it's fine.

2. Make sure that all TextViews use the style from `styles.xml` file like `Heading1`, `TextFieldLabel`, `Body`, etc. whichever suits best.

While making the above changes the UI should not get affected and the end result should still be the same as before (or an optimized version of UI).

If there are multiple files with the same name, update them all.

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by Arjupta** [comment]
I will work on this .

**Comment by MohamedMedhat1998** [comment]
> I will work on this .

@ARJUPTA Before we assign you this one, can you finalize #1042 first, please?  
If you are facing difficulties with #1042 we can remove your assignment there and assign you this one.  
What would you prefer?

**Comment by Arjupta** [comment]
I am working on the #1042, but as @rt4914 suggested to look upon the rest Slop issues as that issue will take time , so I started working on this too. I will take the #1042 if have to choose between one.

**Comment by MohamedMedhat1998** [comment]
Ok no issues, you can work on both. I'll assign this one to you too.

**Comment by arinarora18** [comment]
May I work on this?

**Comment by MohamedMedhat1998** [comment]
> May I work on this?

@rt4914 @Sarthak2601 @aggarwalpulkit596

**Comment by rt4914** [comment]
@arinarora18 Suggest working on #3556 first and then work on this issue.

**Comment by Uticodes** [comment]
Hi @MohitGupta121,
I'd like to work on this issue.
Thank you 🙏

**Comment by MohitGupta121** [comment]
@Uticodes assigned go ahead. 
If you have any query feel free to ask me.

**Comment by Uticodes** [comment]
Alright, thank you.
I'll review the screens, then go through the instructions again, if I have
any questions, I'll let you know.
