### ISSUE TITLE
Fix ImageRegionSelectionInteractionViewTest for Robolectric

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1965]
Currently, the ImageRegionSelectionInteractionViewTest are passing on Espresso but they should also pass on Robolectric. Fix these below mentioned files to make sure that the tests pass on Robolectric.

You can run robolectric tests by following these steps: https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-roboelectric-tests

Fixing test cases will need to introduce TextApplicationComponent. This can be seen [here](https://github.com/oppia/oppia-android/pull/1680/commits/4729d551b86282ce617e1d53f2762416758785a1).

**Comment by aggarwalpulkit596** [comment]
This would be a bit too much for slop as it requires changes into roboelectric framework

**Comment by Sarthak2601** [comment]
> This would be a bit too much for slop as it requires changes into roboelectric framework

This issue was already present for SLoP under #1869. However I think @aggarwalpulkit596 is right here. 
@BenHenning @rt4914 thoughts?

**Comment by rt4914** [comment]
> > This would be a bit too much for slop as it requires changes into roboelectric framework
> 
> This issue was already present for SLoP under #1869. However I think @aggarwalpulkit596 is right here.
> @BenHenning @rt4914 thoughts?

@Sarthak2601 I agree with you. Let's remove this from SLoP, considering we already have good number of issues.

**Comment by anandwana001** [comment]
@rt4914 @aggarwalpulkit596 This issue is Duplicate for https://github.com/oppia/oppia-android/issues/1611

**Comment by rt4914** [comment]
> @rt4914 @aggarwalpulkit596 This issue is Duplicate for #1611

@anandwana001 I not fully sure here.

**Comment by anandwana001** [comment]
> > @rt4914 @aggarwalpulkit596 This issue is Duplicate for #1611
> 
> @anandwana001 I not fully sure here.

@rt4914 All the test case are marked with #1611 issue only

**Comment by rt4914** [comment]
Duplicate. #1611
