### ISSUE TITLE
Fix TestFontScaleConfigurationUtilActivityTest for Robolectric

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1967]
Currently, TestFontScaleConfigurationUtilActivityTest are passing on Espresso but they should also pass on Robolectric. Fix these below mentioned files to make sure that the tests pass on Robolectric.

You can run robolectric tests by following these steps: https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-roboelectric-tests

Fixing test cases will need to introduce TextApplicationComponent. This can be seen [here](https://github.com/oppia/oppia-android/pull/1680/commits/4729d551b86282ce617e1d53f2762416758785a1).

**Comment by prayutsu** [comment]
@Sarthak2601 I think tests are already passing, please confirm.
![Screenshot from 2020-10-09 21-01-35](https://user-images.githubusercontent.com/54636525/95602699-e9cce180-0a72-11eb-8213-00c003d3b5fa.png)

**Comment by anandwana001** [comment]
Thanks @prayutsu 
closing this issue.
