### ISSUE TITLE
Action Bar Text Size Variation

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#1975]
**Describe the bug**
The size of the text varies for two different screens (until now discovered this problem in the FAQ section). It might be a mistake in the layout

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the Drawer and go to the Help Tab.
2. Click on Frequently Asked Questions, a list of questions will appear.
3. Open any Question while observing the Action Bar.
4. We will see that text size changes abruptly.

**Expected behaviour**
Text size must not vary so that it doesn't look like a glitch

**Screenshots**
Preview of Issue

![ezgif-3-a9d4c0492a72](https://user-images.githubusercontent.com/64064110/95672749-0414d580-0bc1-11eb-9c7a-922f5fd2ed82.gif)

**Device**
- Device/emulator being used : Real Device (Real me 3)
- SDK version : Android 10

**Comment by BenHenning** [comment]
Nice catch @ARJUPTA, this does seem like a bug. We should probably have a consistent style for all action bar titles throughout the codebase unless the mocks have some inconsistencies here.

/cc @rt4914
