### ISSUE TITLE
Optimize code in administrator_controls_app_information_view.xml

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#1979]
This issue is tracking the optimization work of `administrator_controls_app_information_view.xml`

1. Make sure that the layout uses `ConstraintLayout` and there is minimal nesting of views. If this view already uses `ConstraintLayout` then it's fine.

2. Make sure that all TextViews use the style from `styles.xml` file like `Heading1`, `TextFieldLabel`, `Body`, etc. whichever suits best.

While making the above changes the UI should not get affected and the end result should still be the same as before (or an optimized version of UI).

If there are multiple files with the same name, update them all.

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by JudeUk** [comment]
hello @MohamedMedhat1998 I'll like to help fix this. Getting to work on it immediately

**Comment by BenHenning** [comment]
@JudeUk I think @secjedi is already working on this (see the 'linked pull requests' section). Could you find another open 'good first issue' to work on, instead?

**Comment by JudeUk** [comment]
@BenHenning I can see a lot of pull requests but no comments on this.

**Comment by secjedi** [comment]
@BenHenning Please could you assign this issue to me? Thanks

**Comment by rt4914** [comment]
> @BenHenning I can see a lot of pull requests but no comments on this.

@JudeUk Yes, this was by mistake and ideally everyone should always comment first and then work on the issue. 
@secjedi is already working on this.
