### ISSUE TITLE
Optimize code in ongoing_story_card.xml 

### ISSUE THREAD

**Issue by aggarwalpulkit596** [oppia/oppia-android#1987]
This issue is tracking the optimization work of `ongoing_story_card.xml`

1. Make sure that the layout uses `ConstraintLayout` and there is minimal nesting of views. If this view already uses `ConstraintLayout` then it's fine.

2. Make sure that all TextViews use the style from `styles.xml` file like `Heading1`, `TextFieldLabel`, `Body`, etc. whichever suits best.

While making the above changes the UI should not get affected and the end result should still be the same as before (or an optimized version of UI).

If there are multiple files with the same name, update them all.

## References
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by lingarajsankaravelu** [comment]
@aggarwalpulkit596 I like to take this up

**Comment by rt4914** [comment]
> @aggarwalpulkit596 I like to take this up

Hello @lingarajsankaravelu Welcome to Oppia. Before we get started, can you please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by JudeUk** [comment]
I am working on this @rt4914 @aggarwalpulkit596 where is the option to assign this to myself please?

**Comment by JudeUk** [comment]
I understand an admin has to assign me to an issue hi mentors @rt4914 @aggarwalpulkit596 kindly assign me to this issue thanks

**Comment by BenHenning** [comment]
@JudeUk I've assigned this to you. Feel free to start working on it. :)

**Comment by lingarajsankaravelu** [comment]
> > @aggarwalpulkit596 I like to take this up
> 
> Hello @lingarajsankaravelu Welcome to Oppia. Before we get started, can you please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

done

**Comment by rt4914** [comment]
@BenHenning Actually @Florence-Njeri has already started working on this. Therefore it cannot be assigned to @JudeUk 

Also, @Florence-Njeri in future please make sure that you always mention or self assign issue.

**Comment by BenHenning** [comment]
Thanks @rt4914, I missed the linked PR. I think @Florence-Njeri needs to comment on this issue before it can be assigned. We should block the PR submission on that to make sure the issues are being assigned correctly to avoid confusion.

@JudeUk apologies for the churn! Please feel free to look for another unassigned issue in the meantime.

**Comment by Florence-Njeri** [comment]
> @BenHenning Actually @Florence-Njeri has already started working on this. Therefore it cannot be assigned to @JudeUk
> 
> Also, @Florence-Njeri in future please make sure that you always mention or self assign issue.

I will. Sorry for the inconvenience I caused.

**Comment by JudeUk** [comment]
@rt4914 hello, ongoing-story-card.xml design is not displaying
<img width="1440" alt="Screenshot 2020-10-14 at 11 34 26" src="https://user-images.githubusercontent.com/31444432/96028010-ab5b6c00-0e50-11eb-9fe2-75b9d7b7c113.png">
 on android studio

**Comment by JudeUk** [comment]
@rt4914 okay no problem, however I would still like to know why I was getting the above situation, @Florence-Njeri did you experience this?

**Comment by rt4914** [comment]
@JudeUk Can you click on red-icon just below `Design` word on right side. This will show an error, can you share that?

Thanks.

**Comment by Florence-Njeri** [comment]
No I did not. I think it's a problem on your end.
