### ISSUE TITLE
Add support for SetOfNormalizedString for TextInput

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#2001]
See https://github.com/oppia/oppia/pull/10882 for context. We should make these changes on Android, too, though it will require updating our test & production exploration files (the latter of which needs to be done by @rt4914 or myself).

**Comment by BenHenning** [comment]
@rt4914 might be nice as a SLoP project. It has less details than a second issue, and is therefore more targeted for more established contributors that can figure this out from the reference PR.

**Comment by anandwana001** [comment]
@rt4914 could you please confirm if this is similar - https://github.com/oppia/oppia-android/issues/3200

**Comment by rt4914** [comment]
Looks similar.

**Comment by BenHenning** [comment]
This was fixed in #3796.
