### ISSUE TITLE
Separate out Robolectric Check Provider

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2021]
**Is your feature request related to a problem? Please describe.**
Currently, the  Robolectric Check Provider is present in the `TestDispatcherModule`. 

**Describe the solution you'd like**
Separate it out. Creating a different provider for it, as this is something which can use commonly in other modules/tests also.

**Comment by anandwana001** [comment]
unassigning @Florence-Njeri as no further update.

**Comment by FareesHussain** [comment]
@anandwana001 
I would like to work on this, can you provide further details regarding this

**Comment by anandwana001** [comment]
`TestDispatcherModule` module is providing `provideIsOnRobolectric`. We need to create a separate module for `provideIsOnRobolectric`. So, it can be provided without providing all the items from `TestDispatcherModule`
