### ISSUE TITLE
Add Code of Conduct to Project

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2028]
Similar to oppia-web we should add a code-of-conduct to oppia-android too.

Reference: https://github.com/oppia/oppia/blob/develop/.github/CODE_OF_CONDUCT.md

**Comment by Victor-Titan** [comment]
Can I work on this issue? All I have to do is copy the Code of Conduct on [this](https://github.com/oppia/oppia/blob/develop/.github/CODE_OF_CONDUCT.md) into a readme file in the project right?

**Comment by rt4914** [comment]
@Victor-Titan 
I am assigning this issue to you.
Actually it won't go in readme. instead it will go to `.github` folder on the project. Similar to oppia-web - https://github.com/oppia/oppia/tree/develop/.github

**Comment by Victor-Titan** [comment]
@rt4914 The code of conduct has already been added to the android project in the location you've specified. https://github.com/oppia/oppia-android/blob/develop/.github/CODE_OF_CONDUCT.md

**Comment by rt4914** [comment]
@Victor-Titan Ohh, I missed that. Closing this issue now.
