### ISSUE TITLE
Fix file formatting under dragAndDropSortInput package

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2035]
**Describe the bug**
All the files, under the package `domain/src/test/java/org/oppia/android/domain/classify/rules/dragAndDropSortInput` are not in the correct format. 

**Expected behavior**
File format should be follow from this file - [TextInputEqualsRuleClassifierProviderTest](https://github.com/oppia/oppia-android/blob/develop/domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt
)

**Correct Order**
Constant values
Dagger injection
Local variables
Test Before setup
Tests
Dagger Setup

**Comment by Aarkin7** [comment]
I will work on this

**Comment by anandwana001** [comment]
@Aarkin7 I will assign it to you, once you completed with the OnBoarding instructions. 
Check our wiki page here - https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by Aarkin7** [comment]
@anandwana001 I have completed the onboarding instructions previously.

**Comment by ShridharGoel** [comment]
I would like to work on this.
