### ISSUE TITLE
Fix file formatting under fractioninput package

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2036]
**Describe the bug**
All the files, under the package `domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput` are not in the correct format. 

**Expected behavior**
File format should be follow from this file - [TextInputEqualsRuleClassifierProviderTest](https://github.com/oppia/oppia-android/blob/develop/domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt
)

**Correct Order**
Constant values
Dagger injection
Local variables
Test Before setup
Tests
Dagger Setup

**Comment by MaskedCarrot** [comment]
I am working on this.
