### ISSUE TITLE
Fix file formatting under ratioinput package

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2039]
**Describe the bug**
All the files, under the package `domain/src/test/java/org/oppia/android/domain/classify/rules/ratioinput` are not in the correct format. 

**Expected behavior**
File format should be follow from this file - [TextInputEqualsRuleClassifierProviderTest](https://github.com/oppia/oppia-android/blob/develop/domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt
)

**Correct Order**
Constant values
Dagger injection
Local variables
Test Before setup
Tests
Dagger Setup

**Comment by MaskedCarrot** [comment]
I am working on this.

**Comment by MaskedCarrot** [comment]
Would it be meaningful to name a ratio 1:2:3 as `RATIO_VALUE_TEST_1_2_3` ?

**Comment by anandwana001** [comment]
> Would it be meaningful to name a ratio 1:2:3 as `RATIO_VALUE_TEST_1_2_3` ?

@MaskedCarrot Let's discuss these points in PR for reference.
