### ISSUE TITLE
Back button from the nav drawer breaks highlight

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#2055]
Repro:

(1) Start at the home screen
(2) Open the nav drawer
(3) Select a different page (e.g. Options)
(4) Press system back button to return to the home screen
(5) Open nav drawer

Expected: the navigation drawer should show 'Home' highlighted.

Observed: the 'Options' menu item is highlighted even though that was the previous page that was opened.

**Comment by anandwana001** [comment]
Duplicate of https://github.com/oppia/oppia-android/issues/1762
