### ISSUE TITLE
Check the Intent Key for the AdminPinActivity and AdminAuthActivity in ProfileChooserFragmentTest

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2058]
**Is your feature request related to a problem? Please describe.**
Need to test the passing intent key from the ProfileChooserActivity to `AdminPinActivity ` and `AdminAuthActivity `

**Describe the solution you'd like**
`AdminAuthEnum.PROFILE_ADD_PROFILE` - clicking on add profile item, If the admin pin is already set it will open to add profile screen
`AdminAuthEnum.PROFILE_ADMIN_CONTROLS` - clicking on admin controls item in the profile chooser screen, check If the admin pin is already set it will open the admin controls

**Comment by chrk2205** [comment]
@anandwana001 
where should we write this tests in `ProfileChooserFragmentTest` or in `AdminAuthActivityTest`
i see that the test are already present in  `ProfileChooserFragmentTest` but are ignored
`testProfileChooserFragment_clickAddProfile_checkOpensAdminAuthActivity_onBackButton_opensProfileChooserFragment`

**Comment by anandwana001** [comment]
Once this pr https://github.com/oppia/oppia-android/pull/2045 get's merged, you can get a clear view to work on it. You had mentioned the correct test. But, we are breaking this test into parts and need to put in `AdminAuthActivityTest ` from where we need to check pressing back will satisfy both the conditions mentioned in the issue above.

**Comment by FareesHussain** [comment]
This can't be done in `AdminAuthActivityTest` right? as on back press the current activity i.e AdminAuthActivity would be destroyed and the test fails with a message

    androidx.test.espresso.NoActivityResumedException: Pressed back and killed the app

May be we need to add tests in `ProfileChooserActivity` and `AdministratorControlsActivity`

**Comment by anandwana001** [comment]
@FareesHussain Correct, as in the test we are launching `AdminAuthActivityTest ` standalone, so we cannot move back. 
Let's do one thing:
We have two ways to open `AdminAuthActivity` 
 - `AdminAuthEnum.PROFILE_ADD_PROFILE` - clicking on add profile item, If the admin pin is already set it will open to add profile screen
 - `AdminAuthEnum.PROFILE_ADMIN_CONTROLS` - clicking on admin controls item in the profile chooser screen check If the admin pin is already set it will open the admin controls 

So, could you update the test cases in `ProfileChooserFragmentTest` to check hasExtras has these required keys or not?
Also, for the AdminPin as well.
