### ISSUE TITLE
Create color & icon profiles for thumbnails

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#206]
We currently define thumbnails based on a single color and an entry in a drawable enum, however there are other aspects necessary to define for rendering thumbnails:
- Drawable padding/size (centerCrop works well for rendering these, but extra whitespace causes them to look a bit inconsistent)
- Background/foreground panel colors (these should be set such that they look correct with certain drawables, have proper contrast, and fit our theme)
- Text color if certain text colors don't work with certain background/foreground panel colors
- Dark mode adjustments

These properties need to be defined in a way that has some consistency with Oppia web, but without the backend needing to understand all of these properties.

**Comment by Victor-Titan** [comment]
@anandwana001 can I work on this issue?

**Comment by Victor-Titan** [comment]
@BenHenning @anandwana001 Can some references be given for the thumbnails which we need to mimic in the app?

**Comment by anandwana001** [comment]
@Victor-Titan If you had checked how the thumbnail looks in the Oppia web portal https://www.oppia.org/learner-dashboard, we need to have a similar look here in android too. Need to work on all the points given in the issue description.

**Comment by Victor-Titan** [comment]
@anandwana001 can you please direct me where in the project can I find the files for the thumbnails? I can't find them

**Comment by anandwana001** [comment]
@Victor-Titan PTAL `ProfileChooserFragmentPresenter` here you will find `COLORS_LIST`, we are creating profile icon using random colors and circle image view in ui.

**Comment by viktoriias** [comment]
@rt4914 @mschanteltc What are the latest requirements for this task?

**Comment by rt4914** [comment]
@BenHenning Can you provide some screenshots for this? I am unable to understand what is the exact issue here.

**Comment by BenHenning** [comment]
I think this might not be an issue anymore since we picked colors carefully to work in the few places where the profile image shows up. This issue was filed back when a lot of these flows weren't yet finalized. The dark mode consideration is probably still valid, but we can assess that as part of a separate dark mode project.

I think this was also focused on non-picture profile avatars, and so it's not considering making sure photos fit properly.

Closing this since it's not clear if there's actual work needed to be done here anymore.

**Comment by BenHenning** [comment]
Ah, there's actually work to do here: @viktoriias can you verify that all places where there's a TODO for this issue is actually dead code now? It should be. If any places rely on the temporary darkening logic we added we will need to fix those places.

Hopefully this issue just involves removing a bunch of TODOs and dead code paths.
