### ISSUE TITLE
Remove injected TestCoroutineDispatchers if not in use

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2080]
**Describe the bug**
There are some test files where we are injecting `TestCoroutineDispatchers` but not using it. 

**Expected behavior**
Remove injected `TestCoroutineDispatchers` if not in use. 

**How to Fix this Issue**
1. Check the injected `TestCoroutineDispatchers` is used in test cases or not. If it is not in use you will find only we place where it is defined as a) variable init, b) inside `setUp` and c) inside `tearDown`. 
2. Remove these 3 initialisation and function calling of `TestCoroutineDispatchers`.
3. Run the test in Espresso and Robolectric to check all test are passing. Wiki reference - https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing
4. If the test cases are failing without `TestCoroutineDispatchers`, we don't need to change that particular file. This will be a rare edge case. 
4. When you send a PR for this issue, also attach both the screenshot showing the tests are passing in both Espresso and Robolectric. 
5. If there are tests `@Ignore` leave them unchanged.

## List of FIles:
- [ ] `FAQSingleActivityTest` 
- [ ] `FAQListFragmentTest` 
- [ ] `HelpFragmentTest` 
- [ ] `MyDownloadsFragmentTest` 
- [ ] `HtmlParserTest`

**Comment by ShridharGoel** [comment]
I'm working on this.

**Comment by ShridharGoel** [comment]
I would like to work on this.

**Comment by anandwana001** [comment]
@ShridharGoel Thanks for showing interest in contributing. 
Please check our onboarding instructions before contributing - https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by ShridharGoel** [comment]
@anandwana001 Sure.
