### ISSUE TITLE
use higher order functions for null check in NetworkInterceptor

### ISSUE THREAD

**Issue by prudhvir3ddy** [oppia/oppia-android#2090]
current code uses bang bang operator though with null check 

<img width="701" alt="Screenshot 2020-11-06 at 8 50 39 AM" src="https://user-images.githubusercontent.com/20471162/98322318-273e7380-200d-11eb-9171-8ae566fe6b76.png">

we can use let higher order function to avoid this.

**Comment by anandwana001** [comment]
@prudhvir3ddy Thanks for showing interest in contributing to Oppia. 
As you had already filled the CLA, could you also please complete the other points in our onboarding instruction. 
https://github.com/oppia/oppia-android/wiki#onboarding-instructions

As per this issue, We recommend choosing either bug report or feature request when filing a new issue, there's a template to follow. 

It will be always easy to discuss things in our Gitter channel first before creating an issue which is more inclined towards a feature request or some formating, this helps to keep the team in sync and contributors and core team members can discuss over either we need any modification or not. 

Gitter channel - https://gitter.im/oppia/oppia-android
