### ISSUE TITLE
Dialog disappears on orientation change

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2092]
**Describe the bug**
In `ProfileEdit` screen on orientation change if the dialog is already shown, it will disappear.

**To Reproduce**
1. Go to ProfileChooser screen and create atleast 2 profiles.
2. In `ProfileChooser` screen click on `Administrator Controls`
3. Enter your pin and go to `AdministratorControlsActivity`
4. Click `Edit Profiles`
5. Select `non-admin` profile.
6. Scroll and click on `Profile Deletion`
7. Once the alert dialog appears, change the orientation to landscape.
8. Notice that the alert dialog disappears.

**Expected behavior**
Alert dialog should persist on orientation change. Also add test for the same in respective file.

**Comment by prudhvir3ddy** [comment]
i want to pick it up @rt4914

**Comment by rt4914** [comment]
> i want to pick it up @rt4914

Assigned. Thanks @prudhvir3ddy

**Comment by prathamk22** [comment]
@rt4914 @anandwana001 can I work on this?

**Comment by anandwana001** [comment]
@prathamk22 Before starting with the contribution, please follow the onboarding instructions https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by prathamk22** [comment]
@anandwana001 I have gone through all the onboarding instruction and filled both google forms. Can I start working on this?

**Comment by anandwana001** [comment]
@prathamk22 any update on this?

**Comment by prathamk22** [comment]
@anandwana001 I am on them. Actually first my code was not running and then I got the exams. Will push a PR asap.

**Comment by Scarlet0103** [comment]
@rt4914  can I work on this?

**Comment by ArpitShukIa** [comment]
@anandwana001 Can I work on this?
