### ISSUE TITLE
[Mobile-Landscape] High-fi StoryActivity Updated UI

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2093]
The `StoryActivity`  UI has been updated a lot which is available here. https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/cce938d6-e079-4761-bac0-8bde22ac6348/

Major changes:
- [ ] The inactive card content formation is updated.
- [ ] RTL Supportive

**Note : Please test UI for RTL support, prior to merging this fix.**

**Follow this guide**: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by Aditiwebd** [comment]
Please assign this to me @Sarthak2601

**Comment by rt4914** [comment]
Un-assigning Aditi as there is no update.

**Comment by ReCodee** [comment]
@rt4914 Hello, I'm new to oppia and I'd love to work on this issue. Please assign this to me :)

**Comment by anandwana001** [comment]
@ReCodee As you had closed the PR, unassigning you.

**Comment by anshbajpai** [comment]
@rt4914 can you please assign this to me?

**Comment by anandwana001** [comment]
@anshbajpai any update on this?

**Comment by E13ctron** [comment]
@rt4914  just a doubt should we make the progress bar in the StoryActivity?

**Comment by rt4914** [comment]
@Amar-2003 Which progress bar? The mock does not contain any bar in this.

Also I think the mocks have changed slightly so will inform Chantel to update them.

@mschanteltc I think this mock needs to be updated: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/cce938d6-e079-4761-bac0-8bde22ac6348/

This should match with the text of inactive card in this mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/5abb0ace-19ee-48b8-8154-919154f924d2/

Also, just for consistency can you check tablet mocks too if they need any change or not?

**Comment by E13ctron** [comment]
@rt4914 I didn't understand what are we meant to do for this issue. :)

**Comment by rt4914** [comment]
> @rt4914 I didn't understand what are we meant to do for this issue. :)

Two things:
1. In this comment: https://github.com/oppia/oppia-android/issues/2093#issuecomment-809058181 you have mentioned `progress bar` but the mock link does not contact progress bar, so what is it about?
2. Mocks might change a bit so I have informed Chantel to share the latest mocks, which means you will need to wait for her reply because working on it.

**Comment by E13ctron** [comment]
> > @rt4914 I didn't understand what are we meant to do for this issue. :)
> 
> Two things:
> 
> 1. In this comment: [#2093 (comment)](https://github.com/oppia/oppia-android/issues/2093#issuecomment-809058181) you have mentioned `progress bar` but the mock link does not contact progress bar, so what is it about?
> 2. Mocks might change a bit so I have informed Chantel to share the latest mocks, which means you will need to wait for her reply because working on it.

ok fine @rt4914

**Comment by E13ctron** [comment]
I saw a comment there in the mock saying about progress bar , thats why I asked about it . Sorry for the mistake @rt4914

**Comment by mschanteltc** [comment]
> @Amar-2003 Which progress bar? The mock does not contain any bar in this.
> 
> Also I think the mocks have changed slightly so will inform Chantel to update them.
> 
> @mschanteltc I think this mock needs to be updated: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/cce938d6-e079-4761-bac0-8bde22ac6348/
> 
> This should match with the text of inactive card in this mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/5abb0ace-19ee-48b8-8154-919154f924d2/
> 
> Also, just for consistency can you check tablet mocks too if they need any change or not?

Just to make sure, are we able to create the "scroll to" action when the chapter name is tapped on? The animation can been seen in the portrait mobile [mock](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/5abb0ace-19ee-48b8-8154-919154f924d2/) when "Chapter 2: The Meaning of 'Equal Parts'" is tapped on from the Chapter 3 card.

**Comment by rt4914** [comment]
> > @Amar-2003 Which progress bar? The mock does not contain any bar in this.
> > Also I think the mocks have changed slightly so will inform Chantel to update them.
> > @mschanteltc I think this mock needs to be updated: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/cce938d6-e079-4761-bac0-8bde22ac6348/
> > This should match with the text of inactive card in this mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/5abb0ace-19ee-48b8-8154-919154f924d2/
> > Also, just for consistency can you check tablet mocks too if they need any change or not?
> 
> Just to make sure, are we able to create the "scroll to" action when the chapter name is tapped on? The animation can been seen in the portrait mobile [mock](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/5abb0ace-19ee-48b8-8154-919154f924d2/) when "Chapter 2: The Meaning of 'Equal Parts'" is tapped on from the Chapter 3 card.

@mschanteltc Yes we can do the `scroll to` action.

**Comment by mschanteltc** [comment]
> 
> @mschanteltc Yes we can do the `scroll to` action.

Sounds good, I update the landscape [mock](https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/cce938d6-e079-4761-bac0-8bde22ac6348/) and applied the change elsewhere in the original portrait mocks. Let me know what you think!

**Comment by rt4914** [comment]
@Amar-2003 You can now work on this new mock.

**Comment by E13ctron** [comment]
@rt4914 I will go through the mocks and will inform you when I am ready to do it :).

**Comment by E13ctron** [comment]
The current screen is like this right??
![Screenshot_20210402-081717_Oppia](https://user-images.githubusercontent.com/73783193/113375041-304d2a00-938c-11eb-964a-626b4f1f6d71.jpg)
And I will have to change it into as in mock right ?? @rt4914

**Comment by E13ctron** [comment]
> The current screen is like this right??
> ![Screenshot_20210402-081717_Oppia](https://user-images.githubusercontent.com/73783193/113375041-304d2a00-938c-11eb-964a-626b4f1f6d71.jpg)
> And I will have to change it into as in mock right ?? @rt4914

@rt4914

**Comment by E13ctron** [comment]
> The current screen is like this right??
> ![Screenshot_20210402-081717_Oppia](https://user-images.githubusercontent.com/73783193/113375041-304d2a00-938c-11eb-964a-626b4f1f6d71.jpg)
> And I will have to change it into as in mock right ?? @rt4914

@rt4914

**Comment by rt4914** [comment]
@Amar-2003 Yes you need to change this as per mocks.

**Comment by E13ctron** [comment]
@rt4914 I may not be able to do this as I am busy with exams, so if someone else comes you may assign this to them or if none comes I will claim later

**Comment by jonathanalvares9009** [comment]
@rt4914 the mock is not loading

**Comment by anandwana001** [comment]
@jonathanalvares9009 any update on this?
The mock is opening for me.

**Comment by rt4914** [comment]
> @rt4914 the mock is not loading

@jonathanalvares9009 It is loading for me. Can you please retry?

**Comment by anandwana001** [comment]
unassigning as no further update

**Comment by veena14cs** [comment]
**Note : Please test UI for RTL support, prior to merging this fix.**

**Comment by viktoriias** [comment]
RTL support was fixed in https://github.com/oppia/oppia-android/issues/3656.

**Comment by viktoriias** [comment]
@rt4914 Are the mock in the description most current?
