### ISSUE TITLE
Edittext focus issue in Add Profile Screen

### ISSUE THREAD

**Issue by prudhvir3ddy** [oppia/oppia-android#2094]
**Describe the bug**
there are two edittexts in add profile screen. entering text in one edittext the keyboard ime shows go to next edittext but on clicking that the keyboard control doesn't go to the next edittext

**To Reproduce**
1. open the app and complete the intro
2. now in select your profile screen click setup multiple profiles
3. now you can observe the issue mentioned, refer the video below.

**Expected behavior**
once clicked on the keyboard next button the keyboard control should be going to next edittext.

**Screenshots**

https://photos.app.goo.gl/mQbstr3JjRx4LtPt9

**Device**
- emulator PIXEL 2
- 29

**Comment by anandwana001** [comment]
Possible duplicate - https://github.com/oppia/oppia-android/issues/962

**Comment by prudhvir3ddy** [comment]
closing this issue
