### ISSUE TITLE
Fix package names in the kdocs for RuleQualifiers class

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#2098]
We have refactored our package name to `org.oppia.android` but some of the package names in the kotlin docs were didn't change while refactoring.  
An example for that is `RuleQualifiers.kt` class found under: `org.oppia.android.domain.classify.rules`  

**ToDo**: rename all the kdocs packages from `org.oppia.domain.classify.RuleClassifier` to `org.oppia.android.domain.classify.RuleClassifier`

**Comment by KMaragh** [comment]
I'll take this!

**Comment by FareesHussain** [comment]
Sorry I didn't see it was assigned when I created this PR

**Comment by anandwana001** [comment]
@FareesHussain as @KMaragh is already assigned to this issue, you need to close your PR.

Also, I suggest joining our Gitter channel for all the communication - https://gitter.im/oppia/oppia-android
