### ISSUE TITLE
Thoroughly test prototype rule classifiers

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#210]
Since the rule classifiers were copied from Oppia web, they didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

## Fraction Input 
- [ ] HasDenominatorEqualToRuleClassifier
- [ ] HasFractionalPartExactlyEqualToRuleClassifier
- [ ] HasIntegerPartEqualToRuleClassifier
- [ ] HasNoFractionalPartRuleClassifier
- [ ] HasNumeratorEqualToRuleClassifier
- [ ] IsEquivalentToAndInSimplestFormRuleClassifier
- [ ] IsEquivalentToRuleClassifier
- [ ] IsExactlyEqualToRuleClassifier
- [ ] IsGreaterThanRuleClassifier
- [ ] IsLessThanRuleClassifier
## Items Selection Input
- [ ] ContainsAtLeastOneOfRuleClassifier
- [ ] DoesNotContainAtLeastOneOfRuleClassifier
- [ ] EqualsRuleClassifier
- [ ] IsProperSubsetOfRuleClassifier
## Multiple Choice Input
- [x] EqualsRuleClassifier (#1112)
## Number With Units 
- [ ] IsEqualToRuleClassifier
- [ ] IsEquivalentToRuleClassifier
## Numeric Input 
- [x] EqualsRuleClassifier (@miaboloix)
- [x] IsGreaterThanOrEqualToRuleClassifier
- [x] IsGreaterThanRuleClassifier
- [x] IsInclusivelyBetweenRuleClassifier
- [x] IsLessThanOrEqualToRuleClassifier
- [x] IsLessThanRuleClassifier
- [ ] IsWithinToleranceRuleClassifier
## Text Input 
- [ ] CaseSensitiveEqualsRuleClassifier
- [x] ContainsRuleClassifier (@miaboloix)
- [x] EqualsRuleClassifier (@miaboloix)
- [ ] FuzzyEqualsRuleClassifier
- [ ] StartsWithRuleClassifier

**Comment by BenHenning** [comment]
@micchickenburger are you interested in taking this work item?

**Comment by BenHenning** [comment]
I suggest starting with TextInput. See [Oppia web](https://github.com/oppia/oppia/blob/develop/extensions/interactions/TextInput/directives/text-input-rules.service.spec.ts) for how we test TextInput now, and [ExplorationProgressControllerTest](https://github.com/oppia/oppia-android/blob/develop/domain/src/test/java/org/oppia/domain/exploration/ExplorationProgressControllerTest.kt) for how we write Robolectric tests in Android.

**Comment by aggarwalpulkit596** [comment]
@prayutsu this is something you can start with.

**Comment by aggarwalpulkit596** [comment]
@prayutsu one classifier should only have one PR. You can take a look at existing tests for this

**Comment by prayutsu** [comment]
@aggarwalpulkit596 I looked into it carefully. Can you please suggest for which classifier test should I go? Perhaps the easiest one

**Comment by aggarwalpulkit596** [comment]
You can start with anyone you feel like there is no such thing as easiest one

**Comment by Sarthak2601** [comment]
This issue has been divided into multiple small issues [ #1880, #1881, #1883, #1884, #1885, #1886, #1887, #1888, #1889, #1890, #1891, #1892, #1893, #1894, #1895, #1896, #1897, #1898, #1899, #1900 ]. Hence, closing this issue.
