### ISSUE TITLE
Introduce pre push hook for Bazel

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2107]
**Is your feature request related to a problem? Please describe.**
As we are migrating towards the bazel, we have a bunch of bazel files coming on our way, we are adding a linter to github action at pr https://github.com/oppia/oppia-android/pull/2048 so we also require to prevent any error before pushing. 

**Describe the solution you'd like**
Introducing pre-push will prevent nit errors and contributors can fix before pushing.

Pre-push hook is introducing in #2002 pr.

Tried few steps to introduce pre-push in the PR https://github.com/oppia/oppia-android/pull/2048

Things that don't worked out:
1. Local `buildifier` file is not working correctly
2. Need to test on windows - https://github.com/oppia/oppia-android/pull/2048#issuecomment-759427721

If you would like to work on this issue, please reach out to @anandwana001

**Comment by BenHenning** [comment]
We should also add a script to perform the linting check (including reliably finding all files to run through buildifier).

**Comment by BenHenning** [comment]
I think this is completed at this point. We run buildifier as part of static_checks.sh: https://github.com/oppia/oppia-android/blob/0ef7a460ce1e41546f2ba1510ff12bbf88ad8177/scripts/static_checks.sh#L40
