### ISSUE TITLE
[Tablet] Highfi AddProfile

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2117]
Currently `AddProfile` screen does not have dedicated tablet layout design in develop.
Implement the `AddProfile` for landscape and portrait mode for tablet devices.
Mock Link: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/271b428d-7d98-40b4-b74e-f2a5266b0587/

Reference: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by FareesHussain** [comment]
Please assign this to me

**Comment by FareesHussain** [comment]
Please review this @rt4914
