### ISSUE TITLE
[Tablet] Highfi AdminAuthActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2119]
Currently `AdminAuthActivity` screen does not have dedicated tablet layout design in develop.
Implement the `AdminAuthActivity` for landscape and portrait mode for tablet devices.
Mock Link: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/f2b8acef-b71a-40c3-a4f4-e426e6be563f/

Reference: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by prayutsu** [comment]
@rt4914 please confirm if this issue has to be assigned to me or arjun
