### ISSUE TITLE
[Tablet] Highfi PinPasswordActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2120]
Currently `PinPasswordActivity` screen does not have dedicated tablet layout design in develop.
Implement the `PinPasswordActivity` for landscape and portrait mode for tablet devices.
Mock Link: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/f59ad764-df4d-4a1b-8ff2-0cf8f7a47bf8/

Reference: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by MohamedMedhat1998** [comment]
@prayutsu You can work on this.
