### ISSUE TITLE
[Tablet] Highfi Revision Card

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2126]
Currently `RevisionCard` screen does not have dedicated tablet layout design in develop.
Implement the `RevisionCard` for landscape and portrait mode for tablet devices.
Mock Link: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/a2d04ed0-de4e-40fe-8a83-824663b30d3f/

Reference: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by FareesHussain** [comment]
Please assign this to me

I need to make changes in revision_card_fragment.xml right?

**Comment by rt4914** [comment]
> Please assign this to me
> 
> I need to make changes in revision_card_fragment.xml right?

@FareesHussain Let's first focus on finishing the other two PR's that you started first. That helps keep things organised and more focused. Once one of them is merged we can come back to this issue and assign you back.

**Comment by MaskedCarrot** [comment]
I am working on this

**Comment by prayutsu** [comment]
@MohamedMedhat1998 Can I take this up?

**Comment by MohamedMedhat1998** [comment]
> @MohamedMedhat1998 Can I take this up?

@rt4914 Is it ok?

**Comment by FareesHussain** [comment]
> > Please assign this to me
> > 
> > I need to make changes in revision_card_fragment.xml right?
> 
> @FareesHussain Let's first focus on finishing the other two PR's that you started first. That helps keep things organised and more focused. Once one of them is merged we can come back to this issue and assign you back.
> 

Can I work on this now?

**Comment by rt4914** [comment]
> > > Please assign this to me
> > > I need to make changes in revision_card_fragment.xml right?
> > 
> > 
> > @FareesHussain Let's first focus on finishing the other two PR's that you started first. That helps keep things organised and more focused. Once one of them is merged we can come back to this issue and assign you back.
> 
> Can I work on this now?

Assigned now.

**Comment by FareesHussain** [comment]
@rt4914 I have to follow the same as #2124 right? 

minWidth=360dp

**Comment by rt4914** [comment]
> @rt4914 I have to follow the same as #2124 right?
> 
> minWidth=360dp

@FareesHussain No actually. It should be followed as per the mocks.
