### ISSUE TITLE
Progress Bar is present when keyboard is active

### ISSUE THREAD

**Issue by mschanteltc** [oppia/oppia-android#2131]
Only display the Progress Bar when the keyboard is inactive. By removing the progress bar while keyboard is active, the learner can view more content and the "Submit" button is not cropped.

**How to reproduce?**
1. Open the app.
2. Click on `Fractions` topic.
3. Click on `Practice` tab.
4. Select a couple of skills.
5. Click Start.

Note: The questions in `Practice Mode` are randomised and therefore whenever you start the session you might encounter different set of questions. 

<img src="https://user-images.githubusercontent.com/22177674/99840262-11f33a00-2b21-11eb-8763-7d3305c8aea5.jpg" width="250" />
<img src="https://user-images.githubusercontent.com/22177674/99842131-2258e400-2b24-11eb-8f94-039a05924705.jpg" width="250" />

**Update**:
We will have to keep the progress bar even when keyboard is visible but we need to optimise on this UI so that it looks a bit more correct (a.) add bottom-padding to submit button (b.) use gradient background for the progress bar so that the button is visible with opacity and does not cut abruptly.

**Comment by yk1ax** [comment]
Can I get assigned for this issue @mschanteltc

**Comment by mschanteltc** [comment]
@rt4914

**Comment by yk1ax** [comment]
@anandwana001 here we only need to hide the progressbar right ? I mean the hint pop up should stay above the keyboard as it is.

**Comment by anandwana001** [comment]
> @anandwana001 here we only need to hide the progressbar right ? I mean the hint pop up should stay above the keyboard as it is.

Yes, All we need here is no progress bar when the keyboard is active.

**Comment by yk1ax** [comment]
@anandwana001 should I try setting some sort of listener for soft keyboard and from that hide the progressBar. And I checked that the functionality for checking if the keyboard is active was added in android 11 and it is not backward compatible as of now. So what method should I use for having the listener functionality.

**Comment by anandwana001** [comment]
@yk1ax You can send a draft PR so we can discuss over the approach. 
I think we can check the visibility using `InputMethodManager ` which I guess supports our lower API level as well.

**Comment by yk1ax** [comment]
@anandwana001  I am trying to do the required task of hiding the progress by setting a focusChangeListener for the editText where we input the answer . But I saw it was using StatePlayerRecyclerViewAssembler to manage the submitted answers for a question. I tried to access the edittext from the databinding object but it seems a bit obfuscated to me because I cannot understand how is it binding the view. Can you provide any help on this.

**Comment by yk1ax** [comment]
> @anandwana001 I am trying to do the required task of hiding the progress by setting a focusChangeListener for the editText where we input the answer . But I saw it was using StatePlayerRecyclerViewAssembler to manage the submitted answers for a question. I tried to access the edittext from the databinding object but it seems a bit obfuscated to me because I cannot understand how is it binding the view. Can you provide any help on this.

@anandwana001 can you have a look at this once and guide me bit

**Comment by anandwana001** [comment]
@yk1ax for binding you can check the RecyclerView finding file, we bind the data to the list using app:list or app:data via Binding adapter. Let's connect over Gitter for further discussion or also a draft pr will be helpful to review the approach and complete the issue.

**Comment by yk1ax** [comment]
> @yk1ax for binding you can check the RecyclerView finding file, we bind the data to the list using app:list or app:data via Binding adapter. Let's connect over Gitter for further discussion or also a draft pr will be helpful to review the approach and complete the issue.

I didn't draft a PR because I don't have single change to push but now I understood why you were telling me to do so. I'll just make PR on a fresh branch.

**Comment by ArpitShukIa** [comment]
How to reproduce this issue?

**Comment by rt4914** [comment]
Unassigning @yk1ax and assigning @ArpitShukIa

**Comment by rt4914** [comment]
@ArpitShukIa Please take a look at the description again. I have updated it.

**Comment by ArpitShukIa** [comment]
@anandwana001 @rt4914 We need to hide only the progress bar or the progress label ("Question 2 of 8") as well?

**Comment by rt4914** [comment]
> @anandwana001 @rt4914 We need to hide only the progress bar or the progress label ("Question 2 of 8") as well?

Progress bar as well as label.

**Comment by rt4914** [comment]
**Reference**: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/8f1fdcb8-4cdf-4869-ac93-87f571737f36/specs/
