### ISSUE TITLE
Chapter List Page Issues

### ISSUE THREAD

**Issue by mschanteltc** [oppia/oppia-android#2132]
- There is no outline of inactive Chapter cards. Make sure there is still a shadow to each card. Do not decrease its opacity.
- The description gets cut off after the fourth line. Since the Chapter description is not available elsewhere, make sure the full description is visible. 
- Update the inactive Chapter cards to blur thumbnails and hide descriptions ([mock](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/5abb0ace-19ee-48b8-8154-919154f924d2/))

![Screenshot_20201120-004517_Oppia](https://user-images.githubusercontent.com/22177674/99840652-d1e08700-2b21-11eb-8feb-798533af88c4.jpg)
![Screenshot_20201120-004508_Oppia](https://user-images.githubusercontent.com/22177674/99840358-44049c00-2b21-11eb-94cb-41d7817d255d.jpg)

**Comment by viktoriias** [comment]
I would like to work on this.

**Comment by anandwana001** [comment]
@mschanteltc Regarding the second and the third point we only need description in the active card and for the inactive card, the description should not be visible, right?

The tasks we need to do on this issue:
1. We need elevation to the inactive cards
2. Full description should be visible
3. Inactive card should not have a description

**Comment by viktoriias** [comment]
Ok, I found "Matthew Goes to Bakery" screen. Do I need to blur thumbnails, like shown in the mock?

**Comment by mschanteltc** [comment]
The tasks that need to be done are:

- Elevate the inactive cards
- Full description of active cards should show full description.
- Inactive cards should be at full opacity
- Inactive cards should show Chapter name and description should show prerequisites to unlock it. 
- Blur thumbnails of inactive cards

**Comment by viktoriias** [comment]
I imagine I'd need a new image to blur inactive cards?

**Comment by mschanteltc** [comment]
> I imagine I'd need a new image to blur inactive cards?

For inactive cards, you would need the [lock icon](https://material.io/resources/icons/?search=lock&icon=lock&style=baseline) and to blur out the card's thumbnail image. Blur it by overlaying a container that is the exact color of the thumbnail's background, drop the opacity to 50%, and apply a blur.

**Comment by viktoriias** [comment]
I will be working on a second part of this issue - blurring and locking the image.

**Comment by viktoriias** [comment]
> > I imagine I'd need a new image to blur inactive cards?
> 
> For inactive cards, you would need the [lock icon](https://material.io/resources/icons/?search=lock&icon=lock&style=baseline) and to blur out the card's thumbnail image. Blur it by overlaying a container that is the exact color of the thumbnail's background, drop the opacity to 50%, and apply a blur.

@mschanteltc What if background is white? Wouldn't it make the lock less visible?

**Comment by rt4914** [comment]
> > > I imagine I'd need a new image to blur inactive cards?
> > 
> > 
> > For inactive cards, you would need the [lock icon](https://material.io/resources/icons/?search=lock&icon=lock&style=baseline) and to blur out the card's thumbnail image. Blur it by overlaying a container that is the exact color of the thumbnail's background, drop the opacity to 50%, and apply a blur.
> 
> @mschanteltc What if background is white? Wouldn't it make the lock less visible?

@viktoriias Background won't be white in production app. It will contain an image always.
