### ISSUE TITLE
Concept Card Name Broken

### ISSUE THREAD

**Issue by mschanteltc** [oppia/oppia-android#2134]
A Concept Card link in Lesson Player was presented incorrectly. This occurred in the topic **Place Value**, story **Jaime's Adventures in the Arcade**, in **Chapter 3: Comparing Numbers**. On other occasions where I triggered a Concept Card, this did not occur. It might be because the Concept Card is empty. [[Video](https://drive.google.com/file/d/1fFQUzUh9dTlPwUOlREag-OGh5JmWTrvq/view?usp=sharing)]

![Screenshot_20201120-005220_Oppia](https://user-images.githubusercontent.com/22177674/99841930-cdb56900-2b23-11eb-835b-42ecaaebc0ae.jpg)

**Comment by chrk2205** [comment]
@mschanteltc 
i would like to work on this but i cannot find the topic in my app!!

**Comment by viktoriias** [comment]
@mschanteltc Could you point out what is broken? 
Are you referring to an error-like looking concept card at 0:11? Or bad HTML rendering in the hint: `&quote;concept card&quote;`?

**Comment by mschanteltc** [comment]
@viktoriias I am referring to the bad HTML rendering `&quote;concept card&quote;` which I would assume causes the empty concept card. If that does not cause the empty concept card, should I file a separate issue for that?

**Comment by viktoriias** [comment]
@anandwana001 Do you have an advice on reproducing this issue?

**Comment by anandwana001** [comment]
> @anandwana001 Do you have an advice on reproducing this issue?

@viktoriias this is not available in the current develop app, need to modify json files a bit. Adding @rt4914 for required steps.

**Comment by BenHenning** [comment]
Taking this as part of the next alpha release.

**Comment by BenHenning** [comment]
Aha, I just fixed this in my local alpha work. I actually thought I caused this--glad to see it fixed.
