### ISSUE TITLE
Change Label from "Train Mode" to "Practice Mode"

### ISSUE THREAD

**Issue by mschanteltc** [oppia/oppia-android#2135]
In the navbar, change "Train Mode" to "Practice Mode" ([mock](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/8fbb663a-39aa-4be1-83bd-73bde6f85dcc/))

![Screenshot_20201120-011331_Oppia](https://user-images.githubusercontent.com/22177674/99842208-44526680-2b24-11eb-8a31-219bbd2de683.jpg)

**Comment by FareesHussain** [comment]
Please assign this to me.
