### ISSUE TITLE
Practice Tab - Top Align Subtopic Name and Checkmark

### ISSUE THREAD

**Issue by mschanteltc** [oppia/oppia-android#2138]
Currently subtopic names are vertically aligned with the checkbox. However checkboxes need to be top aligned with the Subtopic name.

![Screenshot_20201119-213417_Oppia](https://user-images.githubusercontent.com/22177674/99846764-d3af4800-2b2b-11eb-87e4-24e74259acc9.jpg)

**Comment by 7phalange7** [comment]
May I work on this issue?

**Comment by chrk2205** [comment]
@mschanteltc 
I don't see a reason to have vertical alignment for check boxes. With the present code its working as it should be.
Incase if you find that UI is not accurate then we can change it else the present code is a better as its optimized.
@rt4914

**Comment by rt4914** [comment]
> May I work on this issue?

Hello @7phalange7 Welcome to Oppia. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by rt4914** [comment]
> @mschanteltc
> I don't see a reason to have vertical alignment for check boxes. With the present code its working as it should be.
> Incase if you find that UI is not accurate then we can change it else the present code is a better as its optimized.
> @rt4914

@chrk2205 The argument that @mschanteltc is making is correct. The checkbox should be top-aligned. Consider a case where the subtopic names goes to `3-4 lines` then the checkbox will be in centre-vertically which looks odd. It should be top-left aligned.

**Comment by rt4914** [comment]
> > May I work on this issue?
> 
> Hello @7phalange7 Welcome to Oppia. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

@7phalange7 Assigned. Thanks.
