### ISSUE TITLE
Download Banner Not Available

### ISSUE THREAD

**Issue by mschanteltc** [oppia/oppia-android#2139]
Despite the Topic being downloaded, there is no "Downloaded" Banner on the respective Topic card. Make sure to include the banner on the card if the Topic is downloaded.

![Screenshot_20201119-213452_Oppia](https://user-images.githubusercontent.com/22177674/99846898-06594080-2b2c-11eb-92e4-3c74decaff0d.jpg)
![Screenshot_20201119-213457_Oppia](https://user-images.githubusercontent.com/22177674/99846906-09543100-2b2c-11eb-9317-579ab2d2178d.jpg)

**Comment by rt4914** [comment]
@mschanteltc This `Topic Downloaded` is currently hard-coded and is not dynamic. The download support is not yet implemented.
@BenHenning Should we close this PR ?

**Comment by BenHenning** [comment]
I agree with @rt4914's earlier message--but this is technically even less relevant now since we've hidden the 'info' screen from the topic page.
