### ISSUE TITLE
User's Name is Cutoff in Home Page

### ISSUE THREAD

**Issue by mschanteltc** [oppia/oppia-android#2140]
Start name on a new line if the name is too long. If the user's name is too long and does not have a space that allows it to break it into a new line, ellipsize the name.

![Screenshot_20201119-213611_Oppia](https://user-images.githubusercontent.com/22177674/99846959-238e0f00-2b2c-11eb-9500-f5e03bba22ae.jpg)

**Comment by coder2699** [comment]
Can I work on this issue ?

**Comment by rt4914** [comment]
> Can I work on this issue ?

@coder2699 Thanks for showing interest in Oppia. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by coder2699** [comment]
@rt4914 Thanks for your response. I have already signed the CLA and filled the form. I have also set up the project on my device.

**Comment by rt4914** [comment]
> @rt4914 Thanks for your response. I have already signed the CLA and filled the form. I have also set up the project on my device.

@coder2699 Assigned. Thanks.

**Comment by prayutsu** [comment]
@rt4914 I want to take this up.

**Comment by rt4914** [comment]
> @rt4914 I want to take this up.

@prayutsu You can always self-assign issues as you are a collaborator.

**Comment by prayutsu** [comment]
> > @rt4914 I want to take this up.
> 
> @prayutsu You can always self-assign issues as you are a collaborator.

Thanks, @rt4914 
Actually, I don't self-assign issues so that I can have your suggestion as well to take the issue or leave it for others.
