### ISSUE TITLE
FAQs Page needs Proper Spacing

### ISSUE THREAD

**Issue by mschanteltc** [oppia/oppia-android#2141]
Numbered and bulleted lists need to be indented. Bullet points need to have adequate space on its right side.

![Screenshot_20201119-214032_Oppia](https://user-images.githubusercontent.com/22177674/99846969-2983f000-2b2c-11eb-8bf1-cda98d44640f.jpg)

**Comment by chrk2205** [comment]
it looks good fine in my mobile!!
can you specify the mobile version your using!!
@mschanteltc 

![WhatsApp Image 2020-11-21 at 22 55 26](https://user-images.githubusercontent.com/44704035/99883315-baea8380-2c4c-11eb-83c1-7f984f92a4d4.jpeg)

**Comment by rt4914** [comment]
@mschanteltc and @chrk2205 Can you please mention the device and Android version that you have tested this on.

**Comment by chrk2205** [comment]
> @mschanteltc and @chrk2205 Can you please mention the device and Android version that you have tested this on.

OnePlus 6 @rt4914

**Comment by krishnakeshan** [comment]
Has this issue been fixed? It seems to be working fine on an ASUS_X01BDA as well.
![device-2020-11-29-201012](https://user-images.githubusercontent.com/23151728/100544934-23ee7e80-327f-11eb-9598-be836074e61e.png)

**Comment by rt4914** [comment]
**NOTE TO ALL**

This might have happened that the app that Chantel is testing on (which is alpha) is old and the issue has already been closed but keeping it open for now. Will consult with Chantel and get it tested on latest apk.

**Comment by BenHenning** [comment]
The actionable item here is to check the app at the version Chantel was using (which should be https://github.com/oppia/oppia-android/tree/release-0.4 against tip-of-tree to verify that the issue no longer exists). Checking the release version is important to ensure we understand the issue Chantel is reporting.

**Comment by etigoel** [comment]
I can start working on this

**Comment by anandwana001** [comment]
@etigoel any update on this?

**Comment by etigoel** [comment]
Facing few issues in android setup. Trying to resolve ASAP.

**Comment by etigoel** [comment]
On latest version of the App not facing the above issue.

Used pixel 3a and Pie as android version

**Comment by anandwana001** [comment]
@etigoel The bullet should be indented as like sub points. 
@FareesHussain You are working on a similar issue, is this a duplicate issue?

**Comment by FareesHussain** [comment]
@anandwana001 This issue is regarding the spacing between the lines
I'm working on Indentation for the Bullet points

**Comment by FareesHussain** [comment]
> The actionable item here is to check the app at the version Chantel was using (which should be https://github.com/oppia/oppia-android/tree/release-0.4 against tip-of-tree to verify that the issue no longer exists). Checking the release version is important to ensure we understand the issue Chantel is reporting.

@anandwana001 I'm sorry i was a little confused
I've tested it on release-0.4 as ben mentioned
and what chantel mentioned was to add identation for bullets and numbered lists
which were divided into two issues 
#2228 (in progress)
#2316 (yet to be discussed)

So i think this needs to be closed
![image](https://user-images.githubusercontent.com/54740946/103547988-20c45f00-4ecb-11eb-843e-18e3087a834a.png)

**Comment by etigoel** [comment]
Got it.
