### ISSUE TITLE
[RTL] Highfi CompletedStoryList

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2146]
`CompletedStoryList` needs RTL support as shown in below screen.
![UP (Stories Completed)](https://user-images.githubusercontent.com/9396084/99870791-c5c8f800-2bfb-11eb-87e8-aabf461d4ab4.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by FareesHussain** [comment]
I would like to work on this.

Is there any previous RTL implementation for reference in other layouts
also how to change to RTL (is it using force RTL in developer options)

**Comment by rt4914** [comment]
> I would like to work on this.
> 
> Is there any previous RTL implementation for reference in other layouts
> also how to change to RTL (is it using force RTL in developer options)

@FareesHussain Actually there is no previous reference.
For testing you will have to force it from `developer options`.

**Comment by FareesHussain** [comment]
@rt4914 why completed_story_item.xml does'nt show preview

![image](https://user-images.githubusercontent.com/54740946/100238567-5e41de00-2f56-11eb-9ebd-366a8dc315c9.png)
