### ISSUE TITLE
[RTL] High fi TopicPractice tab.

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2147]
`Topic-Practice` needs RTL support as shown in below screen.
![TP (Practice, Unchecked)](https://user-images.githubusercontent.com/9396084/99870806-e6914d80-2bfb-11eb-89ec-e8291826f554.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by FareesHussain** [comment]
Please assign this to me
