### ISSUE TITLE
[RTL] High fi Topic-Info tab

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2148]
`Topic-Info` needs RTL support as shown in below screen.
![TP (Overview)](https://user-images.githubusercontent.com/9396084/99870832-0d4f8400-2bfc-11eb-95e0-9645dfc2b7ef.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by MaskedCarrot** [comment]
i am working on this

**Comment by rt4914** [comment]
> i am working on this

Thanks.
