### ISSUE TITLE
[RTL] Highfi Topic tabs & toolbar

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2149]
`Topic-Tabs and Toolbar` needs RTL support as shown in below screen.
![TP (Practice, Unchecked)](https://user-images.githubusercontent.com/9396084/99870806-e6914d80-2bfb-11eb-89ec-e8291826f554.png)

NOTE: Just focus on tabs and toolbar and not the content below.

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by FareesHussain** [comment]
Please assign this to me

**Comment by FareesHussain** [comment]
I've tried this in RTL and found that the only change required was in the revision tab icon 
the only thing weird here is swiping in viewpager so, here viewpager directions needs to be fixed in this issue I guess
![image](https://user-images.githubusercontent.com/54740946/100295375-74c85380-2faf-11eb-9e89-236f58e9e399.png)

**Comment by FareesHussain** [comment]
This can be automatically solved by migrating to [viewpager2](https://developer.android.com/jetpack/androidx/releases/viewpager2#1.0.0-alpha01) as it has RTL support
![image](https://user-images.githubusercontent.com/54740946/100299651-31271700-2fba-11eb-8513-6fea342dd328.png)

**Comment by rt4914** [comment]
> This can be automatically solved by migrating to [viewpager2](https://developer.android.com/jetpack/androidx/releases/viewpager2#1.0.0-alpha01) as it has RTL support
> ![image](https://user-images.githubusercontent.com/54740946/100299651-31271700-2fba-11eb-8513-6fea342dd328.png)

The PR for this is already in progress. #2104

**Comment by FareesHussain** [comment]
> The PR for this is already in progress. #2104

@rt4914 Yes I noticed that
So this issue needs to be closed right as there are no further changes needed

**Comment by BenHenning** [comment]
@anandwana001 does #2104 address this?

**Comment by anandwana001** [comment]
> @anandwana001 does #2104 address this?

Yes, That PR is solving this issue. 

![Screenshot_1606883988](https://user-images.githubusercontent.com/25057618/100829130-a6955a80-3486-11eb-9e1d-bd3b76776e13.png)

**Comment by FareesHussain** [comment]
> > @anandwana001 does #2104 address this?
> 
> Yes, That PR is solving this issue.
> 
> ![Screenshot_1606883988](https://user-images.githubusercontent.com/25057618/100829130-a6955a80-3486-11eb-9e1d-bd3b76776e13.png)

Can you also check swiping in the  viewpager

**Comment by anandwana001** [comment]
@FareesHussain scrolling working fine
