### ISSUE TITLE
[RTL] Highfi Revision Card

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2150]
`Revision Card` needs RTL support as shown in below screen.
![RM (Revision Mode)](https://user-images.githubusercontent.com/9396084/99870884-61f2ff00-2bfc-11eb-8ff3-fddb77b6ff28.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by Aditiwebd** [comment]
Please assign this to me @rt4914
