### ISSUE TITLE
Change dp to sp in TestFontScaleConfigurationUtilActivityTest

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2155]
In `TestFontScaleConfigurationUtilActivityTest` we should check the fontsize in sp instead of dp.

Reference: https://github.com/oppia/oppia-android/blob/b29fcbcdfaf1a4839ebcc7d0fc54cf7010368f92/app/src/sharedTest/java/org/oppia/android/app/testing/TestFontScaleConfigurationUtilActivityTest.kt#L98

**Comment by rt4914** [comment]
@BenHenning WDYT?

**Comment by ForgottenProgramme** [comment]
@rt4914 , this sounds easy enough. 
Can I please do it?

**Comment by rt4914** [comment]
> @rt4914 , this sounds easy enough.
> Can I please do it?

@ForgottenProgramme Assigned. Thanks.

**Comment by ForgottenProgramme** [comment]
> > @rt4914 , this sounds easy enough.
> > Can I please do it?
> 
> @ForgottenProgramme Assigned. Thanks.

@rt4914 , Should I change dp to sp in all the places in this file? Or only in line 98?

**Comment by rt4914** [comment]
> > > @rt4914 , this sounds easy enough.
> > > Can I please do it?
> > 
> > 
> > @ForgottenProgramme Assigned. Thanks.
> 
> @rt4914 , Should I change dp to sp in all the places in this file? Or only in line 98?

Wherever we are taking about the font size.

**Comment by ForgottenProgramme** [comment]
Yes. Right. Okay.

**Comment by ForgottenProgramme** [comment]
@rt4914 

![dptosp](https://user-images.githubusercontent.com/65779580/100369295-bea24f80-302a-11eb-83d2-36346997e044.png)

Should I create a dimen value resource?

**Comment by rt4914** [comment]
@ForgottenProgramme Apologies for the inconvenience, but I dig deeper into the code and saw that this is correct implementation. We cannot change this further. Therefore closing the PR and the issue.
