### ISSUE TITLE
[RTL] High-fi Profile List

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2176]
`Profile List` needs RTL support as shown in below screen.
![Profile List RTL](https://user-images.githubusercontent.com/9396084/100345108-d9170180-3007-11eb-8fc3-3fe48dd044e3.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by ForgottenProgramme** [comment]
@rt4914 , Where do I find this 'Profiles' section?

**Comment by rt4914** [comment]
> @rt4914 , Where do I find this 'Profiles' section?

1. Start with `Profile Chooser Screen`
2. Click on `Administrator Controls` option
3. Click on `Edit Profiles`
You will see the list of profiles.

**Comment by ForgottenProgramme** [comment]
@rt4914 

I made changes in the profile_list_profile_view.xml film in layout and layout-land folder. 
But I could not find this file in layout-sw600dp-port and layout-sw600dp-land folders. 

The results look fine for mobile. 
![port_mob](https://user-images.githubusercontent.com/65779580/100392711-78b2af00-305d-11eb-8161-8643c662b9c7.png)

![land_mob](https://user-images.githubusercontent.com/65779580/100392715-7b150900-305d-11eb-9e80-fb700e28809b.png)


But in tab it looks like this: 

![port_tab](https://user-images.githubusercontent.com/65779580/100392722-81a38080-305d-11eb-85bf-3a50036f94d8.png)

![land_tab](https://user-images.githubusercontent.com/65779580/100392727-85370780-305d-11eb-85e7-36dc14a05bc9.png)

**Comment by ForgottenProgramme** [comment]
Please assign it to me @rt4914 .
Also, please clarify whether the screen is supposed to look like this in tab ?

**Comment by ForgottenProgramme** [comment]
> ![port_tab](https://user-images.githubusercontent.com/65779580/100392722-81a38080-305d-11eb-85bf-3a50036f94d8.png)
> 
> ![land_tab](https://user-images.githubusercontent.com/65779580/100392727-85370780-305d-11eb-85e7-36dc14a05bc9.png)

@rt4914 , Would you please confirm that the 'Administrator Controls' screen is supposed to look this in a tablet?

**Comment by rt4914** [comment]
> @rt4914
> 
> I made changes in the profile_list_profile_view.xml film in layout and layout-land folder.
> But I could not find this file in layout-sw600dp-port and layout-sw600dp-land folders.
> 
> The results look fine for mobile.
> ![port_mob](https://user-images.githubusercontent.com/65779580/100392711-78b2af00-305d-11eb-8161-8643c662b9c7.png)
> 
> ![land_mob](https://user-images.githubusercontent.com/65779580/100392715-7b150900-305d-11eb-9e80-fb700e28809b.png)
> 
> But in tab it looks like this:
> 
> ![port_tab](https://user-images.githubusercontent.com/65779580/100392722-81a38080-305d-11eb-85bf-3a50036f94d8.png)
> 
> ![land_tab](https://user-images.githubusercontent.com/65779580/100392727-85370780-305d-11eb-85e7-36dc14a05bc9.png)

@ForgottenProgramme There are only two files for `profile_list_profile_view.xml` and therefore you have to make changes in that file only. Also the tablet implementation is bit different but you don't need to worry about that. You can just fix this from mobile perspective and it will work in tablet too.

**Comment by ForgottenProgramme** [comment]
@rt4914 , Okay. Got it now.
Thankyou, Rajat. 
I made a PR.

**Comment by ForgottenProgramme** [comment]
Also, @rt4914 

![port_tab](https://user-images.githubusercontent.com/65779580/100718246-1fda7200-33e1-11eb-867c-2cf4aebd83b7.png)

The parts I have unclosed in red, also needs RTL. Isn't it?

**Comment by rt4914** [comment]
> Also, @rt4914
> 
> ![port_tab](https://user-images.githubusercontent.com/65779580/100718246-1fda7200-33e1-11eb-867c-2cf4aebd83b7.png)
> 
> The parts I have unclosed in red, also needs RTL. Isn't it?

@ForgottenProgramme No. Only the Profile List needs RTL. Rest all will be done separately.
