### ISSUE TITLE
[RTL] High-fi Help Screen

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2177]
`Help` needs RTL support as shown in below screen.
![Profile List RTL](https://user-images.githubusercontent.com/9396084/100345108-d9170180-3007-11eb-8fc3-3fe48dd044e3.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by ForgottenProgramme** [comment]
@rt4914 , I think you have attached the wrong screenshot by mistake.

**Comment by ForgottenProgramme** [comment]
@rt4914 , I solved this. 
Please assign it to me. 
Thankyou. :)
