### ISSUE TITLE
[RTL] High-fi FAQ Single

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2180]
`FAQ Single` needs RTL support as shown in below screen.
![FAQ Single RTL](https://user-images.githubusercontent.com/9396084/100345836-ed0f3300-3008-11eb-8a4b-4389ed28d92d.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by ForgottenProgramme** [comment]
@rt4914 , How do I reach the FAQ section?

**Comment by ForgottenProgramme** [comment]
okay, found it

**Comment by ForgottenProgramme** [comment]
@rt4914 , Please assign this to me. 
I solved it.
