### ISSUE TITLE
Profile Deletion in Tablet opens a different layout

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2192]
**Describe the bug**
Profile Deletion Opens a list of profiles without toolbar

**To Reproduce**
1. Go to 'Administrator Controls'
2. Within 'Edit profiles' select a profile and delete the profile
3. Opens a list of profiles and onBack press shows a empty profile info as given below

**Expected behavior**
Go back to Edit Profiles section in Adminstrator Controls

**Screenshots**
Edit Profile | Selected Profile | Deleting profile | List of profiles without toolbar | Empty Profile Info 
--- | --- | --- | --- | ---
![Screenshot_1606578255](https://user-images.githubusercontent.com/54740946/100519799-2c33b480-31c0-11eb-8176-19ba7933f26c.png) | ![Screenshot_1606578255](https://user-images.githubusercontent.com/54740946/100519799-2c33b480-31c0-11eb-8176-19ba7933f26c.png) | ![Screenshot_1606578259](https://user-images.githubusercontent.com/54740946/100519800-2ccc4b00-31c0-11eb-9d95-afb0dad40a8f.png) | ![Screenshot_1606578264](https://user-images.githubusercontent.com/54740946/100519803-2dfd7800-31c0-11eb-98c2-5c4ea85ada2b.png) | ![Screenshot_1606578268](https://user-images.githubusercontent.com/54740946/100519798-2b028780-31c0-11eb-9de7-08223291a85d.png)

**Device**
- Device/emulator being used - Nexus 7
- SDK version - 29

**Additional context**
 for more than one profile

**Comment by FareesHussain** [comment]
Please assign this to me

I fixed this using activity.finish() instead of creating a intent as I does the same as pressing back button but using intent causes problem in  tablet
![image](https://user-images.githubusercontent.com/54740946/100520586-8898d300-31c4-11eb-89c0-79391450c1b2.png)

**Comment by anandwana001** [comment]
> Please assign this to me
> 
> I fixed this using activity.finish() instead of creating a intent as I does the same as pressing back button but using intent causes problem in tablet
> ![image](https://user-images.githubusercontent.com/54740946/100520586-8898d300-31c4-11eb-89c0-79391450c1b2.png)

@FareesHussain For this, you also need to write test cases which should pass on both Espresso and Robolectric and should fail without your implementation.

**Comment by FareesHussain** [comment]
@anandwana001 Ok i'll try
but how to vary robolectric tests for mobiles and tablets

**Comment by anandwana001** [comment]
@FareesHussain Checkpoint 2 here - https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#performance-exceptionruntime-exception-failure
Such things are already set up in the already written test files.

**Comment by FareesHussain** [comment]
> ![image](https://user-images.githubusercontent.com/54740946/100520586-8898d300-31c4-11eb-89c0-79391450c1b2.png)

This Implementation works for both mobiles and tablets but the espresso test case is closed so I had to go with some other implementation
