### ISSUE TITLE
[RTL] High-fi Bullet Points

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2193]
Custom Bullet Points needs RTL support as shown in below screen.
![FAQ Single RTL](https://user-images.githubusercontent.com/9396084/100345836-ed0f3300-3008-11eb-8a4b-4389ed28d92d.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## How to Test
1. Go to `Help` in `Navigation Drawer`
2. Click on `FAQs`
3. Click on `1st` FAQ
4. See the bullets.

## File Reference:

https://github.com/oppia/oppia-android/blob/9221c80f33d94c38a69bf055dbde5d3138ec5ada/utility/src/main/java/org/oppia/android/util/parser/CustomBulletSpan.kt#L20

https://github.com/oppia/oppia-android/blob/9221c80f33d94c38a69bf055dbde5d3138ec5ada/utility/src/main/java/org/oppia/android/util/parser/HtmlParser.kt#L92

**Comment by coder2699** [comment]
@rt4914 I want to fix this issue.

**Comment by ForgottenProgramme** [comment]
I am trying to solve this.

**Comment by ForgottenProgramme** [comment]
@rt4914 , would you please give me some pointers? 
I checked the file references you have added.

**Comment by rt4914** [comment]
> @rt4914 , would you please give me some pointers?
> I checked the file references you have added.

In current RTL the bullets appear on left side only, shown in below screenshot but instead it should on the right side as shown in issue description.

![Screenshot_1607114373](https://user-images.githubusercontent.com/9396084/101212611-05352100-369f-11eb-8d75-353cfb3217d7.png)

**Comment by anandwana001** [comment]
I think for this issue, we might need a different set or strings like `<li dir="rtl">` and need to parse it in the HtmlParser. 
As for now, we are parsing the li tags in another way using `BulletTagHandler`
This issue is a bit big enough which needs a lot or workaround.

**Comment by anandwana001** [comment]
@ForgottenProgramme any update on this?

**Comment by rt4914** [comment]
> @ForgottenProgramme any update on this?

@anandwana001 The contributor has not been active lately. So un-assigning her.

**Comment by BenHenning** [comment]
Assigning to myself per https://github.com/oppia/oppia-android/pull/3320#issuecomment-902999806.
