### ISSUE TITLE
Onboarding Fragment needs to be updated to ViewPager2

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2194]
In `OnboardingFragment` we are currently using `ViewPager` because of which it does not support RTL automatically, instead we should use `ViewPager2` and make it RTL compatible.

**Comment by FareesHussain** [comment]
can i work on this

**Comment by rt4914** [comment]
> can i work on this

@FareesHussain Actually @prayutsu and @anandwana001 are already working on some part of it. So its better if we assign it to them. 

Just give me some time and I will be adding more issues soon. Mostly by end-of-day.

**Comment by FareesHussain** [comment]
ok got it
