### ISSUE TITLE
Introduce pre push hook for Kotlin

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2198]
**Is your feature request related to a problem? Please describe.**
We are linting our kotlin files using ktlint and there are quite a number of times when we have ktlint failure in GitHub checks. 

**Describe the solution you'd like**
pre-push will prevent all such failures.

**Comment by ForgottenProgramme** [comment]
Hey, @anandwana001 ! 
I don't think I'll be able to solve this with my current knowledge. 
Would you please suggest me some resources from I can read and learn what needs to be done to solve this issue? 
Thankyou. :)
