### ISSUE TITLE
Last used text is misaligned on the profile page

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#2205]
**Describe the bug**
The 'last used XXX' string on the profile page isn't aligned correctly anymore. This appears to be a regression in the past few weeks.

**To Reproduce**
1. Open the app
2. If a profile hasn't yet been selected, select the 'Admin' profile
3. Press 'back' to go back to the profile selection screen or restart the app
4. Observe that the 'Last used just now' text isn't aligned correctly

**Expected behavior**
The 'last used just now' text should be aligned per the mocks: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/8cdde1f8-daae-438c-8fdd-084e5d227080/.

**Screenshots**
![image](https://user-images.githubusercontent.com/12983742/100809128-510b7000-33ea-11eb-8705-1568a488f428.png)

**Device**
- Device: Pixel XL
- SDK: 29

**Comment by BenHenning** [comment]
@rt4914 or @anandwana001 have either of you noticed this? I can also repro it on a really large emulator screen, though having some difficulties getting actual smaller emulators started.

**Comment by Russ741** [comment]
I'd like to work on this one.

**Comment by BenHenning** [comment]
Assigned!

**Comment by BenHenning** [comment]
From discussion today, it seems like 'Administrator' is also missing from the portrait view.

**Comment by anandwana001** [comment]
@Russ741 any update on this?

**Comment by Russ741** [comment]
@anandwana001 Yeah, I've been able to dig into this one; it looks like we're using a LinearLayout in a way that it doesn't really support. We can either try to do without it (just using the ConstraintLayout) or nest another LinearLayout inside; @BenHenning has indicated a preference for the former.

**Comment by rt4914** [comment]
@Russ741 Any updates ?

**Comment by anandwana001** [comment]
unassigning @Russ741 as no further update.

**Comment by Russ741** [comment]
@anandwana001 , I apologize for my delay in replying; I was on vacation. Could I have another day to work on this? I'm meeting with @BenHenning tomorrow to sort out my remaining issues.

**Comment by Russ741** [comment]
Updated plan:

* Cleanup work on alternate versions of profile_chooser_profile_view.xml
  * Where attributes are using literal values, add values resources for them to use instead
    * e.g. profile_avatar_img layout_width
  * Where the same attribute is set to a different resource in alternate layouts, change those layouts to use the same resource
    * e.g. dimen/profile_view_not_added_margin vs. dimen/profile_chooser_profile_view_margin_top_profile_not_added
  * Where an attribute is set in an alternate layout but probably doesn't need to be, remove it
    * e.g. profile_chooser_item profile:ignore
* Remove LinearLayout and make icon/text immediate children of ConstraintLayout
* If possible, create separate files for OOBE and added-profile layouts
  * i.e. https://riggaroo.dev/constraintlayout-constraintlayoutstates/

**Comment by anandwana001** [comment]
Are you creating a pr for this issue?

**Comment by Russ741** [comment]
@anandwana001 Yes; the branch I'm working on is https://github.com/Russ741/oppia-android/tree/profile-chooser-oobe-fixes
