### ISSUE TITLE
Changes in Admin Pin Activity [A11y]

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2206]
**Describe the bug**

Admin Pin Activity Screens are not fully compatible with some users from the Accessibility point of view.
Issue 1 - No Item Label present in both the profile input view when no data are typed in it ie. in the inactive state
Issue 2 - Multiple items have the same Description as that of Profile Input View when some data is entered in it ie. active state
Issue 3 - The Contrast ratio of the text (foreground and background) inside the Submit button is 2.58 (in inactive state) but the required one 4.50 

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and scan the screenshots with the Accessibility Scanner
3. You will see the tests that are not passed by that screen
4. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

| Issue 1  |    Issue 2    |  Issue 3 |
|:--------:|:-------------:|:---------:|
|![Screenshot_2020-12-02-10-49-03-67_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/100835383-90da6200-3493-11eb-85a6-eac3cc73644b.jpg) |![Screenshot_2020-12-02-10-52-27-12_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/100835391-92a42580-3493-11eb-9fae-ad630c124a80.jpg)|  ![Screenshot_2020-12-02-10-49-41-05_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/100835398-959f1600-3493-11eb-85ef-1ac0665411cd.jpg)   |

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

**Comment by Arjupta** [comment]
Currently, views are marked as non-clickable in the inactive state which causes the contrast issue, they should be marked enabled/disabled based on their state which will prevent the scanner to detect it as an error

**Comment by Arjupta** [comment]
### Checklist
 (Contributors can take one issue at a time)
* [ ]  `Issue-1` (not assigned to anyone)
* [x]  `Issue-2` (assigned to @ARJUPTA )
* [x]  `Issue-3` (assigned to @ARJUPTA )

**Comment by Mehul-Bisht** [comment]
@ARJUPTA it seems that all the EditTexts have been replaced with TextInputEditTexts now so now the only issue should be with the contrast ratios I believe?

**Comment by Arjupta** [comment]
> @ARJUPTA it seems that all the EditTexts have been replaced with TextInputEditTexts now so now the only issue should be with the contrast ratios I believe?

Will test and discuss about this with team

**Comment by rt4914** [comment]
@mschanteltc 
The below image shows the contrast color error for border of the editexts. What should be the border color to fix this?

<img src="https://user-images.githubusercontent.com/9396084/106925834-77c18c00-6736-11eb-9b05-d1033c46d278.png" width="250" />

**Comment by mschanteltc** [comment]
Let's make the border #666666.
