### ISSUE TITLE
[A11y] Changes in Admin Controls Download Permissions View

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2210]
**Describe the bug**

Admin Control Download Permission View is not fully compatible with some users from the Accessibility point of view.
![Screenshot_2020-12-02-11-13-39-64_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/100836753-de57ce80-3495-11eb-946a-5c39b4af8a8a.jpg)
Issue 1 - The Size of Switch button must be larger ( minimum 48dpX48dp) 
Issue 2 - Multiple items have the same Description as that of Switch Button
Issue 3 - The Contrast ratio of the text (foreground and background) inside the TextViews is 2.68 but the required one 4.50 

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and scan the screenshots with the Accessibility Scanner
3. You will see the tests that are not passed by that screen
4. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

| Issue 1  |    Issue 2    |  Issue 3 |
|:--------:|:-------------:|:---------:|
|![Screenshot_2020-12-02-11-13-18-10_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/100837105-91282c80-3496-11eb-9ef7-8e41a72e975d.jpg)|![Screenshot_2020-12-02-11-13-28-16_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/100837585-e2382080-3496-11eb-85c2-3ca4fa7dd5df.jpg) | ![Screenshot_2020-12-02-11-13-04-76_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/100837062-7b1a6c00-3496-11eb-886c-ce35babcc0aa.jpg) |  

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

**Comment by 7phalange7** [comment]
Hello @ARJUPTA , I'm working on the issue. Please assign me the issue.

**Comment by Arjupta** [comment]
@7phalange7 assigned it to you

**Comment by 7phalange7** [comment]
@ARJUPTA to fix the above issues I need to add min height/weight and text color, So should I use `hardcoded` values or make new entries in `@dimens` and `@color` resources and use them?

**Comment by Arjupta** [comment]
> @ARJUPTA to fix the above issues I need to add min height/weight and text color, So should I use `hardcoded` values or make new entries in `@dimens` and `@color` resources and use them?

You must use dimens and color files for resolving any issue.

**Comment by Arjupta** [comment]
### Checklist
 (Contributors can take one issue at a time)
* [x]  `Issue-1` (assigned to @7phalange7 )
* [ ]  `Issue-2` (not assigned to anyone)
* [x]  `Issue-3` (assigned to @ARJUPTA )

**Comment by 7phalange7** [comment]
@ARJUPTA please assign me `Issue-2` (or `Issue-1` any one is fine) . Just to confirm, is this issue ready to be worked upon?

**Comment by Arjupta** [comment]
> @ARJUPTA please assign me `Issue-2` (or `Issue-1` any one is fine) . Just to confirm, is this issue ready to be worked upon?

Issue -1 is ready to be worked upon. Assigned it to you. Try attaching a screenshot of before changes , after changes and test scans also in your Pull Request

**Comment by Arjupta** [comment]
Reopening it as it got closed automatically by merging a PR which solved only a part of this Issue

**Comment by rt4914** [comment]
Closing as it will get solved in #2618
