### ISSUE TITLE
Changes in Fragments under Options Menu [A11y]

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2215]
**Describe the bug**

All three Fragments under Options Menu have certain views which are not fully compatible from the Accessibility point of view.

Issue 1 - Multiple items have the same Description as that of small "**A**" present in the  **reading_text_size_fragment**

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and scan the screenshots with the Accessibility Scanner
3. You will see the tests that are not passed by that screen
4. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

| Issue 1  |    Issue 2    |
|:--------:|:-------------:|
|![Screenshot_2020-12-03-15-32-43-26_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/101000846-69af8d80-3584-11eb-89be-0a227ec4bca6.jpg)| ![Screenshot_2020-12-03-15-29-16-32_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/101000782-57355400-3584-11eb-9a70-cb211de9d774.jpg)|
 | ![Screenshot_2020-12-03-15-32-35-06_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/101001074-abd8cf00-3584-11eb-8007-aa37b882f04d.jpg)| ![Screenshot_2020-12-03-15-32-00-92_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/101000824-64ead980-3584-11eb-95e4-6bf093d5867e.jpg)|

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

**Comment by Arjupta** [comment]
### Checklist
 (Contributors can take one issue at a time)
* [x]  `Issue-1` assigned to @Mehul-Bisht )
* [ ]  `Issue-2` (not assigned to anyone)

**Comment by justdvnsh** [comment]
@ARJUPTA I'd like to take up the second sub part of this issue !!

**Comment by rt4914** [comment]
@justdvnsh Second part is already getting solved in #2784 . And first part is assigned to Arjun. I will assign the complete issue to Arjun to avoid confusion

**Comment by rt4914** [comment]
Closing this as issue one is already solved.
