### ISSUE TITLE
Changes in Profile List View [A11y] [BLOCKED]

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2217]
**Describe the bug**(Considering only admin profile)

The Profile List Fragment under Edit profiles option of Administrator Controls have certain views which are not fully compatible from the Accessibility point of view.

Issue 1 - The Contrast ratio (foreground to background) of text inside **profile_list_profie_view** is 2.68 but the suggested one is 4.50 (under profile_list_fragment)
Issue 2 - Multiple items have the same Description as that of textview inside the toolbar present in the profile_edit_activity 

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and scan the screenshots with the Accessibility Scanner
3. You will see the tests that are not passed by that screen
4. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

| Issue 1  |    Issue 2    |
|:--------:|:-------------:|
| ![Screenshot_2020-12-03-15-36-55-72_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/101004613-9cf31c00-3586-11eb-9800-fbf3deb04cb7.jpg) |  ![Screenshot_2020-12-03-15-37-17-27_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/101014155-6bc91a80-358b-11eb-9953-2e831dbb7be4.jpg)|

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

**Comment by Arjupta** [comment]
@mschanteltc can you give some description on how to resolve this

**Comment by mschanteltc** [comment]
> @mschanteltc can you give some description on how to resolve this

Let's change the subtext to #555555. LMK what contrast ratio that would make it and if it is sufficient enough.

**Comment by Arjupta** [comment]
### Checklist
 (Contributors can take one issue at a time)
* [x]  `Issue-1` (assigned to @ARJUPTA)
* [ ]  `Issue-2` (not assigned to anyone)

**Comment by Arjupta** [comment]
Reopening it as it got closed automatically by merging a PR which solved only a part of this Issue
