### ISSUE TITLE
Changes in Profile Rename Activity [A11y]

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2218]
**Describe the bug**(Considering only admin profile)

The Profile Rename Activity under Edit profiles option of Administrator Controls have certain views which are not fully compatible from the Accessibility point of view.

Issue 1 - The ProfileInputView doesn't have a label when it is in inactive state.
Issue 2 - The Contrast ratio (foreground to background) of text inside SAVE Button is 2.59 but the suggested one is 4.50

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and scan the screenshots with the Accessibility Scanner
3. You will see the tests that are not passed by that screen
4. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

| Issue 1  |    Issue 2    |
|:--------:|:-------------:|
| ![Screenshot_2020-12-03-15-37-45-45_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/101014730-56082500-358c-11eb-993f-1c87ac5897ff.jpg) |  ![Screenshot_2020-12-03-15-37-53-05_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/101014802-71733000-358c-11eb-8db6-cc66d81a6597.jpg)|

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

**Comment by BenHenning** [comment]
From talking to a previous colleague of mine, @ARJUPTA is the save button in this case being marked as disabled or not clickable? Per my colleague, marking buttons as disabled should result in their contrast not being checked by the scanner. Can you verify?

**Comment by Arjupta** [comment]
@BenHenning this the code which is related to this view. It is made non-clickable when there is no input given to the profileInputView.
```
<Button
          android:id="@+id/profile_rename_save_button"
          style="@style/StateButtonActive"
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          android:layout_marginTop="16dp"
          android:layout_marginEnd="28dp"
          android:background="@{viewModel.inputName.length > 0 ? @drawable/state_button_primary_background :@drawable/start_button_transparent_background}"
          android:clickable="@{viewModel.inputName.length > 0}"
          android:text="@string/profile_rename_save"
          android:textAllCaps="true"
          android:textColor="@{viewModel.inputName.length > 0 ? @color/white : @color/submitButtonInactiveText }"
          android:textSize="14sp"
          app:layout_constraintEnd_toEndOf="parent"
          app:layout_constraintTop_toBottomOf="@id/input_name" />
```

**Comment by Arjupta** [comment]
Currently, views are marked as non-clickable in the inactive state which causes the contrast issue, they should be marked enabled/disabled based on their state which will prevent the scanner to detect it as an error

**Comment by Arjupta** [comment]
### Checklist
 (Contributors can take one issue at a time)
* [ ]  `Issue-1` (not assigned to anyone)
* [ ]  `Issue-2` (not assigned to anyone)

**Comment by rt4914** [comment]
Closing this issue as it is obsolete now.
