### ISSUE TITLE
Changes in Profile Reset Pin Activity [A11y]

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2219]
**Describe the bug**(Considering only admin profile)

The Profile Reset Pin Activity under Edit profiles option of Administrator Controls have certain views which are not fully compatible from the Accessibility point of view.

Issue 1 - The Contrast ratio (foreground to background) of text inside SAVE Button is 2.59 but the suggested one is 4.50
Issue 2 - The ProfileInputView doesn't have a label when it is in inactive state.
Issue 3 - Multiple items have same description as that of ProfileInput View when present in active state.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and scan the screenshots with the Accessibility Scanner
3. You will see the tests that are not passed by that screen
4. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

| Issue 1  |    Issue 2    | Issue 3 |
|:--------:|:-------------:|:---:|
| ![Screenshot_2020-12-03-15-38-27-54_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/101015728-d54a2880-358d-11eb-9395-2b1ef584ef2f.jpg) |![Screenshot_2020-12-03-15-38-22-60_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/101015650-bba8e100-358d-11eb-8d65-c9b8d0062e98.jpg)|![Screenshot_2020-12-03-15-39-13-37_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/101015551-9c11b880-358d-11eb-9a3e-54d45413e19b.jpg)|

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

**Comment by Arjupta** [comment]
Currently, views are marked as non-clickable in the inactive state which causes the contrast issue, they should be marked enabled/disabled based on their state which will prevent the scanner to detect it as an error.

**Comment by Arjupta** [comment]
### Checklist
 (Contributors can take one issue at a time)
* [ ]  `Issue-1` (not assigned to anyone)
* [ ]  `Issue-2` (not assigned to anyone)
* [ ]  `Issue-3` (not assigned to anyone)

**Comment by Arjupta** [comment]
@rt4914 do we also have something for the content description here in the app or we should ask @mschanteltc

**Comment by rt4914** [comment]
@ARJUPTA Please update the issue with latest develop code because `ProfileInputView` has been removed from the code now.

**Comment by Arjupta** [comment]
Okay I will.

**Comment by Arjupta** [comment]
@rt4914 this issue is not reproduceable on both emulator and real device so we can close this issue now

**Comment by rt4914** [comment]
This issue is obsolete.
