### ISSUE TITLE
Profile Name is going out of bounds

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2227]
**Describe the bug**
![Screenshot_1607072477](https://user-images.githubusercontent.com/9396084/101143945-a25f6d80-363d-11eb-9097-4a77c6cee195.png)

In the above image we can see that the Profile name is going out of screen.

**Device**
Use `Nexus 9` in portrait mode

**To Reproduce**
1. Add a profile with max characters.
2. Click on AdminControls
3. Click on Edit Profiles
4. Select the added profile.
5. Check that name is going out of bounds

**Expected behavior**
The text should shift to next line. The text should be fully visible.
Also, check this on tablet landscape and mobile device too.
Write a test case which passes on both Espresso and Robolectric.

**Comment by arnoob16** [comment]
Hey can I work on this issue?

**Comment by anandwana001** [comment]
@arnoob16 Please check the Onboarding Instructions before starting with the contribution. 
https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by anandwana001** [comment]
@arnoob16 Any update on this?

**Comment by arnoob16** [comment]
I am still working on this. Will try to make a PR in a day or two.

**Comment by anandwana001** [comment]
Thanks for the update.

**Comment by dipu989** [comment]
Can I work upon this?

**Comment by anandwana001** [comment]
@dipu989 As you are already on other good-first-issues, I suggest looking for harder issues.

**Comment by dipu989** [comment]
@anandwana001 Sure, I will!
 I was trying to get comfortable with project's codebase and grasp Kotlin, coming from Java background.

**Comment by rawlin** [comment]
Hey, can I be assigned this issue

**Comment by rt4914** [comment]
Duplicate #2529
