### ISSUE TITLE
Increase start-indentation for bullets

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2228]
![Screenshot_1606821079](https://user-images.githubusercontent.com/54740946/100750704-6e513600-340c-11eb-8bbb-5a8952034895.png)

In the above screenshot the bullets are aligned to the above text but instead the start margin should be more similar to what we normally see in google documents.

**Comment by FareesHussain** [comment]
@mschanteltc i've tried solve this please check if you were referring to any them

![Screenshot_1607152038](https://user-images.githubusercontent.com/54740946/101236399-e8c4d300-36f6-11eb-991c-bffb499d9541.png)
![Screenshot_1607152214](https://user-images.githubusercontent.com/54740946/101236429-17db4480-36f7-11eb-8d1b-ad34cd710bff.png)

**Comment by mschanteltc** [comment]
Thank you @FareesHussain. The second picture is more like what I'm describing. A few changes in your second image though:

- Indent the bullet points more like the placement of the bullet points in the first image is. 
- Make sure the textboxes are left aligned. In the second image, the words in the second bullet point "Profile" and "progress" are not aligned.

**Comment by anandwana001** [comment]
![Screenshot_2020-12-10-22-49-06-376_org oppia android](https://user-images.githubusercontent.com/25057618/101806480-069c9880-3b3a-11eb-8629-3f00b91fbe40.jpg)

**Comment by mschanteltc** [comment]
@anandwana001 The listed item needs to be a separate textbox from the number or the bullet. For example, "1. From the Profile Chooser..." has its second line start at the same point as "1." when it should actually be aligned with the word "From". 

All listed items, numerical or bulleted, need to have a larger left indent than the body text. For example, the bullet points and numbered list need to start on a further x-axis than "If it is your first time.." and "If you have created a..."

**Comment by FareesHussain** [comment]
> Thank you @FareesHussain. The second picture is more like what I'm describing. A few changes in your second image though:
> 
> * Indent the bullet points more like the placement of the bullet points in the first image is.
> * Make sure the textboxes are left aligned. In the second image, the words in the second bullet point "Profile" and "progress" are not aligned.

@mschanteltc please check

![Screenshot_1608314664](https://user-images.githubusercontent.com/54740946/102646293-c799c300-4189-11eb-8a9b-7c3919826ae4.png)

**Comment by mschanteltc** [comment]
Thank you @FareesHussain. The bullet points look great. I'm not sure if this is the right issue to say this, but can we apply the same formatting to the number list as well?

**Comment by FareesHussain** [comment]
> Thank you @FareesHussain. The bullet points look great. I'm not sure if this is the right issue to say this, but can we apply the same formatting to the number list as well?

@mschanteltc sorry for the delay, Actually here bullets uses a separate class `CustomBulletSpan` which is only applied for the bullet spans. So for the number lists is not for this issue. I'll look into it and try to solve it

**Comment by FareesHussain** [comment]
@mschanteltc One more doubt check this the indentation also reflects for Exploration Topics, please check if it looks good

Bullet span with indentation | Bullet span without Indentation 
--- | --- 
<img src="https://user-images.githubusercontent.com/54740946/103138269-e0a8f380-46f6-11eb-82ab-a8952d46b4a5.png" align="center" width="100%"/> | <img src="https://user-images.githubusercontent.com/54740946/103138272-e1da2080-46f6-11eb-8954-0b56248604bf.png" align="center" width="100%"/>

**Comment by mschanteltc** [comment]
Thank you for the update @FareesHussain. Should we file a separate issue for the number list? And the left image (Bullet span with indentation) looks better if we are able to use that.

**Comment by FareesHussain** [comment]
@mschanteltc Thanks, I've created a pull request for the left image it will be merged soon
I've filled a issue regarding indentation in numbered lists #2316 
I'm trying to solve it also i need to discuss it with ben too
