### ISSUE TITLE
Shift assertThrows function in Testing Module

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2234]
**Is your feature request related to a problem? Please describe.**
We are using `assertThrows` function in multiple places in app/domain/testing/utility module. 

**Describe the solution you'd like**
Shift this function under the testing module and use wherever needed. 
One reference of the `assertThrows` function
https://github.com/oppia/oppia-android/blob/f616e8570ee6c791250a0675e0b728204b96b1d1/domain/src/test/java/org/oppia/android/domain/audio/AudioPlayerControllerTest.kt#L440

This issue can be done in parts:
- [x] introduce assertThrows in the testing module and then continue with the other parts
- [x] shift `assertThrows` functions in the app module to the testing module 
- [x] shift `assertThrows` functions in the domain module to the testing module 
- [x] shift `assertThrows` functions in the utility module to the testing module 
- [x] use `assertThrows` helper function in the testing module 

To work on this issue, please comment on which part you want to work.

**Comment by ShridharGoel** [comment]
I would like to work on all parts of this issue.

**Comment by anandwana001** [comment]
> I would like to work on all parts of this issue.

I suggest completing the last part first, as it requires to create a helper class and then all other parts can use that helper class.

**Comment by BenHenning** [comment]
@anandwana001 isn't it the case that once we introduce assertThrows in the testing module then it can be used everywhere else? I suggest indicating that's the plan here & clarifying the dependency and expectations for the other modules.

**Comment by BenHenning** [comment]
@ShridharGoel assigned to you. :)

**Comment by ShridharGoel** [comment]
@BenHenning Thanks. :)

**Comment by ShridharGoel** [comment]
This has been done, hence closing.
