### ISSUE TITLE
Remove orientation attribute from ConstraintLayout and FrameLayout in the project

### ISSUE THREAD

**Issue by ShridharGoel** [oppia/oppia-android#2237]
ConstraintLayout and FrameLayout do not need orientation.

Hence, orientation attribute should be removed wherever it has been used in these layouts.

**Example:**

https://github.com/oppia/oppia-android/blob/f616e8570ee6c791250a0675e0b728204b96b1d1/app/src/main/res/layout/onboarding_slide.xml#L20-L23

Here, `android:orientation="vertical"` is not required.

**Comment by fsharpasharp** [comment]
I can take this task.
