### ISSUE TITLE
Add all missing test in domain/BUILD.bazel

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2239]
**Is your feature request related to a problem? Please describe.**
As per the Bazel, we need to mention all the test files which are inside the domain module, under the BUILD.bazel file of domain module. Some of the test files are missing. 

**Describe the solution you'd like**
1. Find all the test files in the domain module which are not added in the BUILD.bazel file. 
https://github.com/oppia/oppia-android/blob/f616e8570ee6c791250a0675e0b728204b96b1d1/domain/BUILD.bazel#L78

2. Add all the missing files
Example - 
```bazel
domain_test(
    name = "NumericInputEqualsRuleClassifierProviderTest",
    srcs = ["src/test/java/org/oppia/android/domain/classify/rules/numericinput/NumericInputEqualsRuleClassifierProviderTest.kt"],
    test_class = "org.oppia.android.domain.classify.rules.numericinput.NumericInputEqualsRuleClassifierProviderTest",
    deps = TEST_DEPS,
)
```

**Comment by FareesHussain** [comment]
Please assign this to me
