### ISSUE TITLE
[RTL] High-Fi Alert dialogs 

### ISSUE THREAD

**Issue by ForgottenProgramme** [oppia/oppia-android#2245]
**Describe the bug**
All alert dialogs need RTL support. 

**To Reproduce**
1. Force RTL layout on your device from developer options.
2. Launch the app
3. Click on any profile to choose it
4. On home screen, click on the back button  

**Expected behavior**
The exit profile dialogue box asks for confirmation to exit from profile. The text and the buttons are on the left, they should be on the right in RTL Layout.

**Screenshots**
![rtl_dialogue](https://user-images.githubusercontent.com/65779580/101679163-f1196700-3a84-11eb-8039-9a567ba88025.jpg)

**Device**
- Pixel 2
- API 28 2

The issue has been explained using just one alert dialog as example. All other alert dialogs also need RTL support.

**Comment by FareesHussain** [comment]
@rt4914 PTAL
<img src="https://user-images.githubusercontent.com/54740946/103193651-1cb0a400-4903-11eb-8657-28e86e648523.png" align="center" width="25%"/>

**Comment by rt4914** [comment]
Introducing pseudoLocale fixes this issue https://github.com/oppia/oppia-android/issues/2245#issuecomment-752937435
