### ISSUE TITLE
Fix flacky test in ProfileChooserFragmentTest

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2248]
**Describe the bug**
Flacky test case in ProfileChooserFragmentTest

**To Reproduce**
1. Go to 'ProfileChooserFragmentTest.kt'
2. Run the test case `testProfileChooserFragment_afterVisitingHomeActivity_showsJustNowText` it passes
3. Run the  test file `ProfileChooserFragmentTest.kt`
4. The test `testProfileChooserFragment_afterVisitingHomeActivity_showsJustNowText` failes

**Expected behavior**
`testProfileChooserFragment_afterVisitingHomeActivity_showsJustNowText` must pass in both cases

**Screenshots**
Running All tests
![image](https://user-images.githubusercontent.com/54740946/101732201-d70e7180-3ae2-11eb-9c0d-24dc236d235b.png) 

Runing individual test
![image](https://user-images.githubusercontent.com/25057618/101736111-e4c6f580-3ae8-11eb-9834-aa5ed2022817.png)

*I'm working on this*

**Comment by FareesHussain** [comment]
@anandwana001 this issue was caused when I added the AdiminAuth intent check 
but when I removed them as per [review](https://github.com/oppia/oppia-android/pull/2247#pullrequestreview-548919585) it works 

So shall I close this.

**Comment by anandwana001** [comment]
Ah, That's Great. Thanks for he update.
