### ISSUE TITLE
Rich-Text support for StoryChapterView [BLOCKED ON #2132, #2013]

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2252]
**Describe the bug**
The description of the chapter card is not supporting styling. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any Topic
2. Click on Lesson Tab -> Click on Story Name
3. Check the last item of the list 

**Expected behaviour**
The text should be styled as per the requirement. ([mock](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/5abb0ace-19ee-48b8-8154-919154f924d2/))

**Screenshots**
##### Requirement
![Screenshot 2020-12-12 at 08 58 06](https://user-images.githubusercontent.com/25057618/101971562-2c1fc400-3c58-11eb-860a-1360aec55404.png)

**Additional context**
Ben - It's a non-starter issue since it requires someone to add a custom view somewhere in this recycler view hierarchy & hook it up to the ViewComponent in order to support injecting HtmlParser and using it.

**Comment by BenHenning** [comment]
Also blocked on #2013 (most likely since this is a bit tricky to do without that).

**Comment by rt4914** [comment]
Closing this as it has been implemented in develop.
