### ISSUE TITLE
Changes needed in Pin Password Activity [A11y] [BLOCKED]

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2256]
**Describe the bug**

Pin Password Activity is not fully compatible with some users from the Accessibility point of view.

Issue 1 - The pinView inside the pin_password_activity.xml does not have any content label (inactive state)
Issue 2 - The reset pin dialog box has a profile input view which also misses a label.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and try to login as a user. 
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen
5. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

| Issue 1  |    Issue 2    |
|:--------:|:-------------:|
|![Screenshot_2020-12-06-23-55-11-56_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/102044620-3c24d880-3dfd-11eb-8a6e-ab8a949d052b.jpg)|  ![Screenshot_2020-12-06-23-54-15-94_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/102044640-48a93100-3dfd-11eb-9787-99130b2ab76e.jpg) | 
|![Screenshot_2020-12-06-23-53-09-67_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/102044627-3dee9c00-3dfd-11eb-9568-77d0154a6abc.jpg)| |

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

**Comment by rt4914** [comment]
Closing this as per https://github.com/oppia/oppia-android/pull/3060#issuecomment-816720244
