### ISSUE TITLE
Turn off split apks

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#2259]
We should disable split apks since they don't seem to be workable, and we'll do this better/more properly with Bazel in #2276.

**Comment by rt4914** [comment]
@ForgottenProgramme Have a look at this issue. This is related to MDPI project too.

**Comment by ForgottenProgramme** [comment]
@rt4914  yes, thankyou. 
@BenHenning , yes, I have been trying to run the app on an mdpi device, when I ran into this issue. 
I'll try solving this.

**Comment by BenHenning** [comment]
Thanks for looking into this @ForgottenProgramme & @rt4914. I think we'll just need to turn this off and fix it in an environment that's easier to work with (Bazel): #2276.
