### ISSUE TITLE
Few tests using EditTextInputAction are freezing on Espresso

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2260]
**Describe the bug**
Some of the tests using `EditTextInputAction` are failing as the EditText is not getting focus and not able to set the text to it. All the tests are passing earlier but now they are failing.

**Expected behavior**
Need to investigate why they are failing now on Espresso. 

The possible solution is to perform all three actions click to get focus, set the text and close the keyboard. This solution works in most of the robolectric part as well. But need a few things to investigate.
```kotlin
.perform(click(), replaceText("1234"), closeSoftKeyboard())
```

1. How many tests are failing? Is it limited to only some screens or all the tests using `EditTextInputAction` are failing on espresso?
2. Need to find a better solution which sustains for a longer period and works on both Espresso and Robolectric. 

Files using `EditTextInputAction`
1. `QuestionPlayerActivityLocalTest` - Only Robolectric, all are passing
2. `ProfileRenameActivityTest` - 
3. `ProfileResetPinActivityTest` -

**Comment by anandwana001** [comment]
Migration to TextInputLayout fixing the freezing test cases as well as IME actions related test cases too. 
https://github.com/oppia/oppia-android/pull/2265

although we cannot use the `EditTextInputAction` for espresso as it doesn't have click action to bring the view in focus and appending text doesn't seem to work now. 
relying on `.perform(click(), replaceText("1234"), closeSoftKeyboard())` which works on both the espresso and robolectric.

**Comment by BenHenning** [comment]
@anandwana001 what has changed to lead to the Espresso tests freezing? That seems like a regression, so we should find the PR(s) that introduced the issue to better help identify _why_.

**Comment by anandwana001** [comment]
Duplicate of https://github.com/oppia/oppia-android/issues/2299
