### ISSUE TITLE
[RTL] High-fi AdminPinVerification [BLOCKED]

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2266]
`AdminPinVerification` needs RTL support as shown in below screen.

![PC AP (Empty) – RTL](https://user-images.githubusercontent.com/9396084/102312344-8b514180-3f94-11eb-89c0-aa54279de8bc.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

**Do not focus on keyboard, we are using native android keyboard.**

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by RaghavAwasthi** [comment]
@rt4914 Hey can you assign this issue to me

**Comment by rt4914** [comment]
> @rt4914 Hey can you assign this issue to me

@RaghavAwasthi Thanks for showing interest in Oppia. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by rt4914** [comment]
@RaghavAwasthi This will help. https://github.com/oppia/oppia-android/wiki/RTL-Guidelines
