### ISSUE TITLE
[RTL] High-fi ProfileProgress

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2267]
`ProfileProgress` needs RTL support as shown in below screen.
![UP (User Profile) – RTL](https://user-images.githubusercontent.com/9396084/102312890-8e98fd00-3f95-11eb-99d6-33bfb656775f.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by lakshaygarg128** [comment]
I would like to work upon it ... pl. assign it to me
@rt4914
