### ISSUE TITLE
[RTL] High-fi ReadingDisplaySize

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2269]
`ReadingDisplaySize` needs RTL support as shown in below screen.
![OP (Story Text Size) – RTL](https://user-images.githubusercontent.com/9396084/102315016-6ad7b600-3f99-11eb-8bd6-4bf3aea9bbe6.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by harsh-hash** [comment]
I'd like to work on this issue. Please assign it to me.

**Comment by FareesHussain** [comment]
> I'd like to work on this issue. Please assign it to me.

As the mentors are busy I'm replying on their behalf

Hello @harsh-hash Thanks for showing interest in Oppia. Before we start please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by harsh-hash** [comment]
Thank you for providing this information and I have signed the CLA.

**Comment by harsh-hash** [comment]
I am working on this issue. I am unable to test it . I followed the video
by @rt4914 for testing rtl. But there is no language like cibarA[XB] so
that i can test it. Is there any other option to test rtl?

**Comment by FareesHussain** [comment]
@harsh-hash is your emulator set to Developer options

**Comment by harsh-hash** [comment]
Yeah

**Comment by FareesHussain** [comment]
@rt4914 for this as the only change required here is to invert the `seekbar` inverting it would be enough right? (using rotateY)
![image](https://user-images.githubusercontent.com/54740946/103512983-b93cee00-4e8f-11eb-8b14-89ea294ea953.png)

**Comment by rt4914** [comment]
> @rt4914 for this as the only change required here is to invert the `seekbar` inverting it would be enough right? (using rotateY)
> ![image](https://user-images.githubusercontent.com/54740946/103512983-b93cee00-4e8f-11eb-8b14-89ea294ea953.png)

That sounds correct but once the PR is out we will need to check this throughly.

**Comment by FareesHussain** [comment]
Closing this as per https://github.com/oppia/oppia-android/pull/2448#issuecomment-758125792
