### ISSUE TITLE
[RTL] High-fi Audio/App Language

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2270]
`Audio/App Language` needs RTL support as shown in below screen.
![OP (Default Audio Language) – RTL](https://user-images.githubusercontent.com/9396084/102315100-8fcc2900-3f99-11eb-88b5-4fb5d6b91cf0.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by coder2699** [comment]
@rt4914 I want to do this task. Please assign me.

**Comment by imraghav20** [comment]
@rt4914 I am a new contributor and this issue looks like a perfect issue to start with. Can I work on this issue?

**Comment by rt4914** [comment]
> @rt4914 I am a new contributor and this issue looks like a perfect issue to start with. Can I work on this issue?

Hello @imraghav20 Thanks for showing interest. Before we start please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

Once this is done you will receive and email from the team and you can get started after that. Thanks.

**Comment by imraghav20** [comment]
Thank you very much for the info @rt4914

**Comment by imraghav20** [comment]
@rt4914 I have gone through the steps you informed me and have even started working on this issue. I will be glad if you assign this to me.
Thank you.
