### ISSUE TITLE
[RTL] High-fi Admin Controls Profile Rename

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2279]
`Admin Controls Profile Rename` needs RTL support as shown in below screen.
![AC EP (Rename) – RTL](https://user-images.githubusercontent.com/9396084/102454936-c9b63180-4064-11eb-81c2-01b8a3d81d37.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by ShridharGoel** [comment]
Since here only `ProfileInputView` needs RTL support, this will also get done when #2287 is merged.

**Comment by rt4914** [comment]
> Since here only `ProfileInputView` needs RTL support, this will also get done when #2287 is merged.

Thanks @ShridharGoel for mentioning this.

**Comment by FareesHussain** [comment]
@rt4914 This can be closed now (Screenshot for reference)
![image](https://user-images.githubusercontent.com/54740946/103401557-4f5ed480-4b6f-11eb-82b4-57b7f2f3a8d6.png)

**Comment by rt4914** [comment]
Closing this as per this comment https://github.com/oppia/oppia-android/issues/2279#issuecomment-752885925
