### ISSUE TITLE
[RTL] High-fi AppVersion

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2281]
`AppVersion` needs RTL support as shown in below screen.
![AC AV (App Version) – RTL](https://user-images.githubusercontent.com/9396084/102455937-73e28900-4066-11eb-8969-8c5e77651f32.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by varunvjha** [comment]
I'd like to work on this issue.

**Comment by FareesHussain** [comment]
@rt4914 PTAL
This needs to be closed according to `pseudolocale`
![image](https://user-images.githubusercontent.com/54740946/103401800-6651f680-4b70-11eb-8bf0-21ea77c47bad.png)

**Comment by rt4914** [comment]
Closing this as per this comment https://github.com/oppia/oppia-android/issues/2281#issuecomment-752887870
