### ISSUE TITLE
[RTL] High-fi Topic Lessons Tab

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2282]
`Topic Lessons` needs RTL support as shown in below screen.
![TP (Lessons, Auto-Scroll Top) – RTL](https://user-images.githubusercontent.com/9396084/102462887-65996a80-4070-11eb-9c96-c8b16a3ddb27.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by priyanka0906** [comment]
@rt4914  can I work on this?

**Comment by FareesHussain** [comment]
@priyanka0906, Sure go ahead.

**Comment by lakshaygarg128** [comment]
is this still open ??

**Comment by rt4914** [comment]
> is this still open ??

@lakshaygarg128 Its assigned to @priyanka0906

**Comment by anandwana001** [comment]
@priyanka0906 any update on this?

**Comment by priyanka0906** [comment]
@anandwana001 not yet

**Comment by FareesHussain** [comment]
@rt4914 It seems we don't need RTL support for Topic Lesson Tab 
I guess this can be closed now
![image](https://user-images.githubusercontent.com/54740946/105060354-4c843f00-5a9e-11eb-8b91-9e814533e1dc.png)

**Comment by rt4914** [comment]
@FareesHussain This will need changes because the progress is not RTL supportive yet.

<img src="https://user-images.githubusercontent.com/9396084/105062730-ed73f980-5aa0-11eb-9c63-c6838c7ebae8.png" width="250" />

**Comment by FareesHussain** [comment]
Thanks for mentioning this

**Comment by anandwana001** [comment]
@priyanka0906 You can mention here in issue if you need any help.
Let me know if you are not working on this issue any more and looking for another issue.

**Comment by priyanka0906** [comment]
> @priyanka0906 You can mention here in issue if you need any help.
> Let me know if you are not working on this issue any more and looking for another issue.

I am working on this.
