### ISSUE TITLE
[RTL] High-fi Topic Tabs Icons

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2283]
`Topic Tabs Icons` needs to properly converted to RTL layout as per below guidelines.

1. Info - **Not Mirrored**
2. Lessons - **Not Mirrored**
3. Practice - **Not Mirrored**
4. Revision - **Mirrored**

Also, make sure this solution works on API 19, API 21 and API 29.

# LTR View
<img width="358" alt="Tabs-LTR" src="https://user-images.githubusercontent.com/9396084/102479832-6e486b80-4085-11eb-8360-c81044ae5ed0.png">

# RTL View
<img width="358" alt="Screenshot 2020-12-17 at 4 31 58 PM" src="https://user-images.githubusercontent.com/9396084/102479801-64bf0380-4085-11eb-8cb0-b472f9493140.png">

**Comment by mschanteltc** [comment]
LGTM!

**Comment by viktoriias** [comment]
@rt4914  Can I work on this?

**Comment by viktoriias** [comment]
Result:
<img width="378" alt="Screen Shot 2020-12-26 at 1 59 50 PM" src="https://user-images.githubusercontent.com/10843277/103160379-3ded8500-4789-11eb-87dd-f058e16c3ecb.png">
