### ISSUE TITLE
Keyboard not showing all input options that are needed for the answer

### ISSUE THREAD

**Issue by yk1ax** [oppia/oppia-android#2290]
**Describe the bug**
'/', ' ' are not being shown as an input option on the keyboard despite the required input being of the type 'p/q' of 'r p/q'

**To Reproduce**
1. Open the App and start the exploration on First Test Topic 
2. Click on 'Prototype Exploration'
3. First question is 'What fraction represents half of something?'
4. Keyboard only shows inputs -> 0123456789

**Expected behaviour**
The keyboard is also supposed to show space (' ') and 'forward slash ('/') as input options.

**Screenshots**
<img src="https://user-images.githubusercontent.com/54735451/102616362-7378e980-415d-11eb-8fb8-dc4102b56d3f.jpg" width="300"> <img src="https://user-images.githubusercontent.com/54735451/102616375-78d63400-415d-11eb-8423-cb426b2fb2e7.jpg" width="300">

**Device**
- Samsung A50
- SDK version 29

**Additional context**
Important point to notice here is that it seems to occur **only** on Samsung keyboard. It worked fine when I download Gboard and tried it on that. But many users who use the default samsung keyboard may get stuck on similar cases.

**Comment by FareesHussain** [comment]
I guess this can only be solved using Custom Key board (bottom sheet) according to [this](https://stackoverflow.com/a/41491692)

**Comment by imraghav20** [comment]
So @FareesHussain you mean the numeric keypad should be replaced by alphanumeric keypad?

**Comment by FareesHussain** [comment]
> So @FareesHussain you mean the numeric keypad should be replaced by alphanumeric keypad?

I'm not sure how to solve this.
I think this is not an issue with the app

**Comment by arjunrkaushik** [comment]
@yk1ax Can I work on this issue?

**Comment by rt4914** [comment]
@arjunrkaushik Assigned. Thanks.

**Comment by BenHenning** [comment]
Taking this issue since it's relevant to alpha: #3075.

**Comment by BenHenning** [comment]
@arjunrkaushik please let us know if you'd like to work on another issue.
