### ISSUE TITLE
[RTL] High-Fi Administrator Controls Screen

### ISSUE THREAD

**Issue by ForgottenProgramme** [oppia/oppia-android#2292]
**Describe the bug**
The administrator control screen requires RTL support.

**To Reproduce**
1. Force RTL Layout on device
2. Launch App
3. At the bottom click on 'Administrator Controls' 

**Expected behavior**
The text within should be aligned according to RTL layout 

**Screenshots**
![admin](https://user-images.githubusercontent.com/65779580/102686331-f311c180-420c-11eb-9053-b16f62e11952.png)

**Device**
Nexus 7 
API 30

**Comment by priyanka0906** [comment]
@ForgottenProgramme  can I work on this issue?

**Comment by ForgottenProgramme** [comment]
> @ForgottenProgramme can I work on this issue?

Yes, sure! Go ahead. :)

**Comment by rt4914** [comment]
> @ForgottenProgramme can I work on this issue?

Hello @priyanka0906 Thanks for showing interest in Oppia. Before we start please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by priyanka0906** [comment]
@rt4914 done.

**Comment by priyanka0906** [comment]
@ForgottenProgramme  thankyou

**Comment by priyanka0906** [comment]
@ForgottenProgramme  would you please clarify if it is the expected behaviour or something is missing??
![ss](https://user-images.githubusercontent.com/56197993/102917678-a5ff4b00-44ab-11eb-81c2-e83b40d1ff85.jpeg)

**Comment by ForgottenProgramme** [comment]
Nice try there, @priyanka0906 ! 
Make a PR for now.
If there is something that needs more tweaking, we'll tell you.
