### ISSUE TITLE
Migration to TextInputLayout from ProfileInputView

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2294]
**Is your feature request related to a problem? Please describe.**
Currently, we are using `ProfileInputView` which seems not able to perform a few things like testing for IME action and a `ProfileInputView` is itself a custom view which makes it hard to modify or introduce new features. 

**Describe the solution you'd like**
Introducing `TextInputLayout` seems promising. 

**How to submit PR for this issue**
 - Update all the XML files related to its screen (port/land/sw600dp/sw600dp-land)
 - Add all the screenshots (port/land/sw600dp/sw600dp-land) for (showing hint/softkeyboard visible/input/error)
 - Add Video (now GitHub support uploading of `.mp4` or `.mov`)
 - Add kdocs wherever needed, reference - https://kotlinlang.org/docs/reference/kotlin-doc.html
 - Run Test of screen-specific file on both Espresso and Robolectric and all test cases should pass including tests if there are any ignored saying ignored because of IME actions 

**Screens to migrate**
 - [x] AdminAuth (@anandwana001)
 - [x] AddProfile (@FareesHussain)
 - [x] ProfileRename (@FareesHussain)
 - [x] AdminPin (@prayutsu)
 - [x] AdminSettings (@FareesHussain)
 - [x] ProfileResetPin (@FareesHussain)
 - [x] ResetPinDialog (@FareesHussain)
... more to add

**Comment by ShridharGoel** [comment]
List of screens to migrate:
- AdminAuth
- AddProfile
- ProfileRename
- AdminPin
- AdminSettings
- ProfileResetPin
- ResetPinDialog

**Comment by FareesHussain** [comment]
@anandwana001 Can I work on this?

**Comment by rt4914** [comment]
@FareesHussain Yes. But take one screen at a time.

**Comment by prayutsu** [comment]
@anandwana001 I am taking `AdminPin`

**Comment by MaskedCarrot** [comment]
@anandwana001 I am working on `AdminSettings`

**Comment by FareesHussain** [comment]
I'm working on `ProfileResetPin`

**Comment by FareesHussain** [comment]
@anandwana001 
AdminSettings and ResetPinDialog are the same right 
I've already created a pull request for that #2349, please check

**Comment by FareesHussain** [comment]
> @anandwana001 I am working on `AdminSettings`

@MaskedCarrot Please wait for @anandwana001's response for `AdminSettings`

**Comment by anandwana001** [comment]
ah, It looks like `AdminSettings ` and `ResetPinDialog ` both covered in PR https://github.com/oppia/oppia-android/pull/2349

**Comment by prayutsu** [comment]
@anandwana001 I feel we have included all files that use `ProfileInputView`
