### ISSUE TITLE
Establish consistency of the "View All" button for promoted stories [Blocked: need clarification, #2272]

### ISSUE THREAD

**Issue by jcqli** [oppia/oppia-android#2297]
The current behavior of the View All button for the promoted stories list on the Home Fragment is inconsistent across mobile and tablet, as well as portrait and landscape orientations on tablet.

Right now:
- Mobile always displays the "View All" button
- Tablet in portrait orientation will display the "View All" button if there are more than two promoted stories
- Tablet in landscape orientation will display the "View All" button if there are more than three promoted stories

We want to clarify:
- Expected behavior of the "View All" button on the Home Activity's promoted stories
- Establish consistent behavior across all devices and orientations for the "View All" button
- Take into consideration the various types of stories that can be displayed in the promoted story list (see #2272)

Possible options:
1. The "View All" is always be visible on all devices in all orientations for all lists
2. The "View All" button is displayed only when we cannot display entire list of promoted stories for all types of promoted stories (e.g. since a landscape tablet can currently display the maximum number of four promoted stories in the Home Activity, we don't display the "View All" button on tablet in landscape orientation; if there are only two promoted stories that are all visible from the Home Activity, we will not display the "View All" button)
3. Other suggestions?

**Comment by BenHenning** [comment]
@jcqli can you clarify what we specifically need clarification on here? @mschanteltc should be able to help provide design clarity, but I'm not actually sure what we need clarity on. :)

**Comment by jcqli** [comment]
> @jcqli can you clarify what we specifically need clarification on here? @mschanteltc should be able to help provide design clarity, but I'm not actually sure what we need clarity on. :)

@BenHenning Added more detail -- is this clearer?

**Comment by mschanteltc** [comment]
"View All" should be consistent across all devices. Since we plan on adding "Recommended" Stories cards to the carousel, most of the time the learner will see three Promoted Stories. 

Even in edge cases where the learner will see one or two Story Cards, we should leave the "View All" button. Tapping it redirects the learner to a page where the story cards are reformatted, letting the learner view more story cards within a viewport compared to the Home Page. Even though most of the page will be white space, learners should still access this any time there are promoted Stories.

**Comment by BenHenning** [comment]
@mschanteltc I think one of the concerns we had was how to handle the case when the list of stories in the home fragment are a combination of recently played & recommended. What do we show in the 'View All' page in that case?

/cc @veena14cs & @rt4914 since this was an open question the last time we met.

**Comment by mschanteltc** [comment]
> @mschanteltc I think one of the concerns we had was how to handle the case when the list of stories in the home fragment are a combination of recently played & recommended. What do we show in the 'View All' page in that case?
> 
> /cc @veena14cs & @rt4914 since this was an open question the last time we met.

I was thinking that we can display them in the same way we categorize the Story cards by [recency](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/2b6c8e95-5ac7-4472-bc2b-1c318a3f7e5c/). One heading can be named "Recently Played" while the other would be named "Recommended." WDYT?

**Comment by rt4914** [comment]
> > @mschanteltc I think one of the concerns we had was how to handle the case when the list of stories in the home fragment are a combination of recently played & recommended. What do we show in the 'View All' page in that case?
> > /cc @veena14cs & @rt4914 since this was an open question the last time we met.
> 
> I was thinking that we can display them in the same way we categorize the Story cards by [recency](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/2b6c8e95-5ac7-4472-bc2b-1c318a3f7e5c/). One heading can be named "Recently Played" while the other would be named "Recommended." WDYT?

@mschanteltc For `RecentlyPlayedScreen` we can do that. But what will be the label in `HomeScreen` when the carousel contains mixed items like recently played & recommended?

**Comment by mschanteltc** [comment]
Let's change the heading for the carousel to be "Stories for You." This would also be the name of the page that "View All" navigates to.

**Comment by BenHenning** [comment]
Ack, thanks @mschanteltc!

@veena14cs assigning this over to you. This seems like something we should address as part of #2320.

**Comment by BenHenning** [comment]
@veena14cs checking, are you actively working on this?

**Comment by veena14cs** [comment]
I have already done as we had discussed this earlier in one of our meetings.
For a combination of Recently-Played and Recommended Stories we show a
label as "Stories For You" on the Home Page.
On Recently-Played Activity we are diving the screen into Recently-Played
and Recommended Stories. If there are OlderStories then it is divided into
3 section accordingly. #2320 covers this issue.

**Comment by BenHenning** [comment]
Thanks @veena14cs. Can you update #2320  to mark this issue as fixed also?

**Comment by rt4914** [comment]
Closing as it was finished in #2320
