### ISSUE TITLE
Changes in Content Item View [A11y]

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2309]
**Describe the bug**

Content Item View is not fully compatible with some users from the Accessibility point of view.

Issue - The height of the text view inside a content_item.xml is 22dp where for a clickable view the required height is 48dp

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and start First Test Topic Exploration
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen
5. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

|  |  | 
|:-------:|:-------:|
| ![Screenshot_2020-12-17-11-04-27-58_80a9469f53bfe75dbc6e8989be28e2f0 (2)](https://user-images.githubusercontent.com/64064110/103092611-cf3fe880-461d-11eb-83f1-03b25f0a969b.jpg) | ![Screenshot_2020-12-17-11-05-08-10_80a9469f53bfe75dbc6e8989be28e2f0 (1)](https://user-images.githubusercontent.com/64064110/103092693-14fcb100-461e-11eb-90ac-49aa0007692a.jpg) |

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Certain Views does not have the correct contrast ratios (Inactive state) as mentioned in the screenshots. To solve this, one must find a way to make the views disabled instead of being in non-clickable state only

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

**Comment by Arjupta** [comment]
@rt4914 we can solve this issue in two ways
 - by making the textview non-clickable so that it passes the scan or
 - increase the textview size

Increasing the size will make the content item boxes very different from what we see right now. What do you suggest?

**Comment by rt4914** [comment]
> @rt4914 we can solve this issue in two ways
> 
> * by making the textview non-clickable so that it passes the scan or
> * increase the textview size
> 
> Increasing the size will make the content item boxes very different from what we see right now. What do you suggest?

@ARJUPTA Make its non-clickable. But also make sure that it does not break the **Concept Card** functionlity.

See description to know how to open concept card: https://github.com/oppia/oppia-android/pull/1637#issue-467120880

**Comment by Arjupta** [comment]
@rt4914 I have tried setting `android:clickable="false"` in [content_item.xml](https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/layout/content_item.xml)
- for the Parent Frame Layout
- for the Text View inside it
- for both of them together

but still the scanner tests failed.

Setting the minHeight of TextView to be 48dp solved the issue but broke the UI. What should we do now?

**Comment by rt4914** [comment]
> @rt4914 I have tried setting `android:clickable="false"` in [content_item.xml](https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/layout/content_item.xml)
> 
> * for the Parent Frame Layout
> * for the Text View inside it
> * for both of them together
> 
> but still the scanner tests failed.
> 
> Setting the minHeight of TextView to be 48dp solved the issue but broke the UI. What should we do now?

Have you tried using making it `disabled`? That should work similar to button. @ARJUPTA

**Comment by Arjupta** [comment]
> > @rt4914 I have tried setting `android:clickable="false"` in [content_item.xml](https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/layout/content_item.xml)
> > 
> > * for the Parent Frame Layout
> > * for the Text View inside it
> > * for both of them together
> > 
> > but still the scanner tests failed.
> > Setting the minHeight of TextView to be 48dp solved the issue but broke the UI. What should we do now?
> 
> Have you tried using making it `disabled`? That should work similar to button. @ARJUPTA

Frame Layout and TextView doesn't have the disabled property

**Comment by rt4914** [comment]
Confirming that @ARJUPTA did test the `importantForAccessibility="no"` and it did pass.
@BenHenning Does this make sense considering that ScreenReaders and also the in-app audio player will be useful in this case.

**Comment by rt4914** [comment]
Completed in #3148
