### ISSUE TITLE
Changes in the Fraction Interaction Item [A11y]

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2310]
**Describe the bug**

FractionInteraction Item is not fully compatible with some users from the Accessibility point of view.

Issue 1 - The contrast ratio of the fraction interaction view does not match the standard ones, both in the active and inactive states. (assigned to @ARJUPTA)

Issue 2 - There is no content label present for the view when it is first clicked to enter a value (Obsolete Issue)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and start First Test Topic Exploration
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen
5. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

| Issue 1  | Issue 2 | 
|:-------:|:-------:|
| ![Screenshot_2020-12-17-11-05-59-83_80a9469f53bfe75dbc6e8989be28e2f0 (1)](https://user-images.githubusercontent.com/64064110/103095984-70cc3780-4628-11eb-9ee1-4b4a442b44be.jpg) | ![Screenshot_2020-12-17-11-06-22-04_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/103095985-7164ce00-4628-11eb-9f7d-cf8814691949.jpg) |
| ![Screenshot_2020-12-17-11-06-34-67_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/103095986-7295fb00-4628-11eb-92ec-cfe690f840d4.jpg) |
 |

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Certain Views does not have the correct contrast ratios (Inactive state) as mentioned in the screenshots. To solve this, one must find a way to make the views disabled instead of being in non-clickable state only

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

**Comment by Arjupta** [comment]
### Checklist
 (Contributors can take one issue at a time)
* [x]  `Issue-1` (assigned to @ARJUPTA)
* [ ]  `Issue-2` (not assigned to anyone)

**Comment by Arjupta** [comment]
Reopening it as it got closed mistakenly by github bug

**Comment by Arjupta** [comment]
@rt4914 same explanation can be applied here for closing this issue as we have done with Ratio Input Interaction

**Comment by rt4914** [comment]
> @rt4914 same explanation can be applied here for closing this issue as we have done with Ratio Input Interaction

@ARJUPTA yes.
