### ISSUE TITLE
Changes Feedback Item [A11y]

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2311]
**Describe the bug**

Feedback Item is not fully compatible with some users from the Accessibility point of view.

Issue - This view has a similar issue as this one - [#2309](https://github.com/oppia/oppia-android/issues/2309)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and start First Test Topic Exploration
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen
5. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

|  |  | 
|:-------:|:-------:|
| ![Screenshot_2020-12-17-11-06-51-43_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/103096505-2055d980-462a-11eb-8adb-d2d730295867.jpg) | ![Screenshot_2020-12-17-11-09-16-38_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/103096507-20ee7000-462a-11eb-99d7-5cb12c25f5eb.jpg) |

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Certain Views does not have the correct contrast ratios (Inactive state) as mentioned in the screenshots. To solve this, one must find a way to make the views disabled instead of being in non-clickable state only

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

**Comment by Mehul-Bisht** [comment]
@ARJUPTA @Srikanth-Kb Is this issue `Blocked` or I may start working on this?

**Comment by srikanthkb** [comment]
> @ARJUPTA @Srikanth-Kb Is this issue `Blocked` or I may start working on this?

I have assigned it to you. You can work on it.
