### ISSUE TITLE
Changes in Numeric Input Interaction Item [A11y]

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2314]
**Describe the bug**

Numeric Input Interaction Item is not fully compatible with some users from the Accessibility point of view.

Issue 1 - There is an ambiguity in the case of the NumericInputInteractionView, it has a content description attribute which will be read by screen readers instead of the content inside the NumericInputInteractionView (Obsolete Issue)

Issue 2 - The Contrast Ratio of the view doesn't match the standard one. (assigned to @ARJUPTA)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and start First Test Topic Exploration
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen
5. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**
| Issue 1 | Issue 2 |
|:-:|:-:|
| ![Screenshot_2020-12-17-11-10-51-41_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/103098602-5cd90380-4631-11eb-977f-76ee45bc2fbf.jpg) | ![Screenshot_2020-12-17-11-11-29-08_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/103098612-6498a800-4631-11eb-8295-f3b8af54319e.jpg) |
| ![Screenshot_2020-12-17-11-11-05-96_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/103098604-5ea2c700-4631-11eb-9d72-cf5afa326a4f.jpg) | |

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

**Comment by rt4914** [comment]
<img src="https://user-images.githubusercontent.com/9396084/105173837-9b39e380-5b47-11eb-8e0a-d1f42db68c6a.png" width="250" />

I tested this in A11y scanner but I was not able to find issue related to contrast. Can you please check this again and confirm.

**Comment by Arjupta** [comment]
> <img alt="" width="250" src="https://user-images.githubusercontent.com/9396084/105173837-9b39e380-5b47-11eb-8e0a-d1f42db68c6a.png">
> 
> I tested this in A11y scanner but I was not able to find issue related to contrast. Can you please check this again and confirm.

<img alt="" width="250" src="https://user-images.githubusercontent.com/64064110/105179809-c58f9f00-5b4f-11eb-8e4b-bd77586cc6e0.png">

I am able to reproduce this error here and was able to solve it too by the our discussion over Chantel's suggestion. Will be creating a PR if you are also able to reproduce it

**Comment by rt4914** [comment]
@ARJUPTA This is based on different device. Considering that you have mentioned the device I will have to try to reproduce on some other device. Lets keep this solution open for now but and also we don't have a solution yet for this.

**Comment by ARJUPTA** [comment]
@mschanteltc PTAL at Issue 1 mentioned here

**Comment by Arjupta** [comment]
@rt4914 we can close this issue too as the label are going to be presented in the prod app

**Comment by rt4914** [comment]
@ARJUPTA please update the description and then we can close. Also remove `BLOCKED` from title

**Comment by Arjupta** [comment]
> @ARJUPTA please update the description and then we can close. Also remove `BLOCKED` from title

@rt4914 Done
