### ISSUE TITLE
Increase start-indentation for Numbered lists

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2316]
To add start-indentation for Numbered Lists in FAQs

**Comment by FareesHussain** [comment]
One solution is to add `<ul>` and `<ol>` tags and implement custom indented lists for tags `<li>`
Numbered list for `<ol>`
and CustomBulletSpan for `<ul>`

**Comment by lakshaygarg128** [comment]
is this issue open ? or anyone working ?

**Comment by lakshaygarg128** [comment]
@FareesHussain Pl. assign it to me

**Comment by FareesHussain** [comment]
@lakshaygarg128 this issue is not yet discussed and it is a bit hard. I recommend you to start with [good-first-issues](https://github.com/oppia/oppia-android/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee)

Also checkout the [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form so that we can assign you issues to work on.

**Comment by lakshaygarg128** [comment]
@FareesHussain ok

**Comment by FareesHussain** [comment]
Closing this as it is a duplicate of #1022
