### ISSUE TITLE
Changes in Ratio Input Interaction Item [A11y]

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2321]
**Describe the bug**

Ratio Input Interaction Item is not fully compatible with some users from the Accessibility point of view.

Issue 1 - In the inactive state, the contrast ratio of the hint text does not match the standard one (assigned to @ARJUPTA)

Issue 2 - Missing Content labels when there is no text inside the the interaction layout (Obsolete issue)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and start First Test Topic Exploration
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen
5. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**
|Issue 1|Issue 2|
|:-:|:-:|
|![Screenshot_2020-12-17-11-11-47-47_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/103153096-f2040580-47b3-11eb-87d0-77d8ccd2486f.jpg)| ![Screenshot_1612510700](https://user-images.githubusercontent.com/64064110/107003907-84d09080-67b3-11eb-9c57-a10b9a917f16.png)|
||![Screenshot_1612510659](https://user-images.githubusercontent.com/64064110/107003905-8306cd00-67b3-11eb-9b0f-b2a5370e1f49.png)|

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Certain Views does not have the correct contrast ratios (Inactive state) as mentioned in the screenshots. To solve this, one must find a way to make the views disabled instead of being in non-clickable state only

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

**Comment by Arjupta** [comment]
@mschanteltc PTAL at Issue 2 mentioned here

**Comment by rt4914** [comment]
> @mschanteltc PTAL at Issue 2 mentioned here

@ARJUPTA You can remove `Issue 2` because labels will be provided by json files / backend. This is dummy state which does not have a label and thats fine.

**Comment by Arjupta** [comment]
> > @mschanteltc PTAL at Issue 2 mentioned here
> 
> @ARJUPTA You can remove `Issue 2` because labels will be provided by json files / backend. This is dummy state which does not have a label and thats fine.

Oh! ok

**Comment by Arjupta** [comment]
@rt4914 then this issue can be closed

**Comment by rt4914** [comment]
> @rt4914 then this issue can be closed

@ARJUPTA Update the description to mention only the issue which you have solved and then we can close this.

**Comment by Arjupta** [comment]
@rt4914 Done
