### ISSUE TITLE
Changes in Submitted Answer List Items [A11y]

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2324]
**Describe the bug**

List items inside the submitted_html_answer_recycler_view (under  **submitted_answer_list_item.xml**) are not fully compatible with some users from the Accessibility point of view.

Issue - Multiple TextViews have a same content description , this is because we have same values inside both correct and incorrect submitted answer text boxes which causes the scans to detect duplicte content descriptions. We need a way to differentiate the content description for incorrect and correct answer, like prepending Incorrect Submitted Answer and Correct Submitted Answer to the current description we provide.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and start First Test Topic Exploration
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen
5. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**
![Screenshot_2020-12-17-11-17-58-76_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/103154318-b3267d80-47bc-11eb-9f08-a6f399f55441.jpg)

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

**Comment by yashraj-01** [comment]
@ARJUPTA can I work on this issue?

**Comment by Arjupta** [comment]
@yashraj-iitr you can work on this, but before proceeding further we will be needing some views from @mschanteltc too. Till then you can propose the way ( in a comment ) you will solve it and then wait for any review you get over it.

**Comment by mschanteltc** [comment]
From my understanding, does it not pass the accessibility checker because 0.35 is shown twice? (once in the submitted answer, again in the drag & drop interaction)

**Comment by Arjupta** [comment]
> From my understanding, does it not pass the accessibility checker because 0.35 is shown twice? (once in the submitted answer, again in the drag & drop interaction)

Yes , this is a part of a broader issue related to failing content description tests. If we do not take care of these descriptions on our own then the screen readers will take up the value of the text inside that view. This might not cause error in some cases but for cases like same **text value** or multiple **checkboxes at same state** will fail the test

**Comment by yashraj-01** [comment]
@ARJUPTA I scanned the app using Accessibility Scanner before submitting the answer and after submitting the answer. I found that this error was only coming after submitting. I think the reason is same as mentioned by @mschanteltc . So, how do you propose I should move forward?

**Comment by Arjupta** [comment]
@rt4914 @yashraj-iitr Is this content description issue reproduceable by you on Pixel 3A emulator. I am able to reproduce only in Real Device

**Comment by yashraj-01** [comment]
> @rt4914 @yashraj-iitr Is this content description issue reproduceable by you on Pixel 3A emulator. I am able to reproduce only in Real Device

No, I also reproduced it on a real device.

**Comment by rt4914** [comment]
> @rt4914 @yashraj-iitr Is this content description issue reproduceable by you on Pixel 3A emulator. I am able to reproduce only in Real Device

@ARJUPTA I am unable to run A11y on emulator as it is taking too much resources. I will have to do the setup process again. But I tried this on real device Pixel 3 and it is reproducible.

**Comment by Arjupta** [comment]
> > @rt4914 @yashraj-iitr Is this content description issue reproduceable by you on Pixel 3A emulator. I am able to reproduce only in Real Device
> 
> @ARJUPTA I am unable to run A11y on emulator as it is taking too much resources. I will have to do the setup process again. But I tried this on real device Pixel 3 and it is reproducible.

I also tried using TalkBack here, it read 3/5 as Three-fifths and also other decimal values were read correctly as the text inside them is unique (Still the scans fail in real device). @yashraj-iitr try to keep this checks in mind while solving this. This issue might be hard for you so feel free to draft a PR and assign us for discussion.

**Comment by rt4914** [comment]
> > > @rt4914 @yashraj-iitr Is this content description issue reproduceable by you on Pixel 3A emulator. I am able to reproduce only in Real Device
> > 
> > 
> > @ARJUPTA I am unable to run A11y on emulator as it is taking too much resources. I will have to do the setup process again. But I tried this on real device Pixel 3 and it is reproducible.
> 
> I also tried using TalkBack here, it read 3/5 as Three-fifths and also other decimal values were read correctly as the text inside them is unique (Still the scans fail in real device). @yashraj-iitr try to keep this checks in mind while solving this. This issue might be hard for you so feel free to draft a PR and assign us for discussion.

@ARJUPTA `Talkback` and `A11y Scanner` can be independent of each other. `A11y Scanner` fails because `3/5` in `submitted answer` and `3/5` in `DragAndDropInteraction` on screen are same that's why.

**Comment by Arjupta** [comment]
> > > > @rt4914 @yashraj-iitr Is this content description issue reproduceable by you on Pixel 3A emulator. I am able to reproduce only in Real Device
> > > 
> > > 
> > > @ARJUPTA I am unable to run A11y on emulator as it is taking too much resources. I will have to do the setup process again. But I tried this on real device Pixel 3 and it is reproducible.
> > 
> > 
> > I also tried using TalkBack here, it read 3/5 as Three-fifths and also other decimal values were read correctly as the text inside them is unique (Still the scans fail in real device). @yashraj-iitr try to keep this checks in mind while solving this. This issue might be hard for you so feel free to draft a PR and assign us for discussion.
> 
> @ARJUPTA `Talkback` and `A11y Scanner` can be independent of each other. `A11y Scanner` fails because `3/5` in `submitted answer` and `3/5` in `DragAndDropInteraction` on screen are same that's why.

@rt4914 in that case we should be able to differentiate between both of these. I believe we should change the description programmatically after the user submits a wrong answer. This new description should mention that the wrong answer you gave is this and the right answer is this. Just a vague plan. WDYT?

**Comment by rt4914** [comment]
> > > > > @rt4914 @yashraj-iitr Is this content description issue reproduceable by you on Pixel 3A emulator. I am able to reproduce only in Real Device
> > > > 
> > > > 
> > > > @ARJUPTA I am unable to run A11y on emulator as it is taking too much resources. I will have to do the setup process again. But I tried this on real device Pixel 3 and it is reproducible.
> > > 
> > > 
> > > I also tried using TalkBack here, it read 3/5 as Three-fifths and also other decimal values were read correctly as the text inside them is unique (Still the scans fail in real device). @yashraj-iitr try to keep this checks in mind while solving this. This issue might be hard for you so feel free to draft a PR and assign us for discussion.
> > 
> > 
> > @ARJUPTA `Talkback` and `A11y Scanner` can be independent of each other. `A11y Scanner` fails because `3/5` in `submitted answer` and `3/5` in `DragAndDropInteraction` on screen are same that's why.
> 
> @rt4914 in that case we should be able to differentiate between both of these. I believe we should change the description programmatically after the user submits a wrong answer. This new description should mention that the wrong answer you gave is this and the right answer is this. Just a vague plan. WDYT?

@ARJUPTA Sounds good. But I will investigate in more detail about how other apps does this and then we can finalise how to solve this.

**Comment by BenHenning** [comment]
Ah. I don't think it's wrong as-is (since the two copies have different contexts), but the interesting bit here is that we might not be providing very much context that the submitted answer is actually the submitted answer. We rely on a visual indication for that today (e.g. box color/alignment) which is a violation of that particular accessibility guideline. I don't think adding an 'answer' text header is needed here, and past user studies on web have indicated users aren't confused that the submitted answer is their answer.

Perhaps the best way to address this is to prepend something like: "Submitted answer <answer text>" in this case. WDYT?

@mschanteltc do you have any thoughts on this?

**Comment by mschanteltc** [comment]
> Ah. I don't think it's wrong as-is (since the two copies have different contexts), but the interesting bit here is that we might not be providing very much context that the submitted answer is actually the submitted answer. We rely on a visual indication for that today (e.g. box color/alignment) which is a violation of that particular accessibility guideline. I don't think adding an 'answer' text header is needed here, and past user studies on web have indicated users aren't confused that the submitted answer is their answer.
> 
> Perhaps the best way to address this is to prepend something like: "Submitted answer " in this case. WDYT?
> 
> @mschanteltc do you have any thoughts on this?

I agree, adding a description before the submitted answer would provide better context for the learner. We can use "Incorrect submitted answer" and "Correct submitted answer" for more clarity.

**Comment by rt4914** [comment]
@ARJUPTA Can you please update the description to mention the improvements suggested by Ben and Chantel.

**Comment by ARJUPTA** [comment]
agree, adding a description before the submitted answer would provide better context for the learner. We can use "Incorrect submitted answer" and "Correct submitted answer" for more clarity.

**Comment by Arjupta** [comment]
> @ARJUPTA Can you please update the description to mention the improvements suggested by Ben and Chantel.

Done.
@rt4914 @mschanteltc @BenHenning
this solution will only work if we have only one incorrect response, when we will have two or more incorrect responses then there will be no difference between those two incorrect submissions.

|||
|:-:|:-:|
|![Screenshot_2021-02-20-20-51-47-65_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/108600746-ebae9600-73be-11eb-94c3-e35b1ea08142.jpg)|![Screenshot_2021-02-20-20-51-43-93_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/108600747-ec472c80-73be-11eb-9f9c-a117ae7533eb.jpg)|

**Comment by yashraj-01** [comment]
@ARJUPTA is it necessary to show all the submitted answers? I mean showing only the last submitted answer would be sufficient in my opinion. WDYT?

**Comment by Arjupta** [comment]
@yashraj-iitr yes, in current implementation we show the latest submitted answer only. But there is a feature of previous answer. By clicking on that you can view all your previous answers, so this is something we should also handle

**Comment by yashraj-01** [comment]
> @yashraj-iitr yes, in current implementation we show the latest submitted answer only. But there is a feature of previous answer. By clicking on that you can view all your previous answers, so this is something we should also handle

Okay. But there should be a way to differentiate between previous responses and the last submitted one. As of now, all the responses are followed by the text "Not quite. Try again." I think we should group all the previous responses under one heading to differentiate it from the last submitted response. WDYT @ARJUPTA ?

**Comment by rt4914** [comment]
@ARJUPTA That's fine. For repetition this failure can be avoided.

**Comment by yashraj-01** [comment]
From what I have learnt so far, I believe that we need to add `contentDescription` to `submitted_answer_container` mentioning whether the submitted answer was correct or incorrect.

@rt4914 @ARJUPTA please tell me if I'm thinking in the right direction or not.

**Comment by rt4914** [comment]
@yashraj-iitr Check [this](https://github.com/oppia/oppia-android/issues/2324#issuecomment-780799146) and its below content. Basically you have to append contentDescription to the entire UI in such cases. Also, this apply not only to this interaction but other interactions too.
