### ISSUE TITLE
Changes in Views related to Audio Player [A11y] [BLOCKED]

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2325]
**Describe the bug**

Some Views related to Audio Player are not fully compatible with some users from the Accessibility point of view.

Issue 1 - The Audio Player Icon in the ToolBar of Exploration Activity does not have a content label 
Issue 2 - The checkbox inside cellular data dialog box has a height of 41dp which is less than the standard one (48dp)
Issue 3 - The SeekBar which shows the progress of Audio that is being played, does not have a content label

Probable Solution for -
Issue 1) The screen reader should say 'Audio, OFF, Double-tap to activate'
Isseu 3) Audio scrub, STATE (ex: Audio scrub, PAUSED)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and start Fraction Exploration
3. Try to play the audio to encounter the dialog box and the audio icon
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen
5. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**
|Issue 1|Issue 2|Issue 3|
|:-:|:-:|:-:|
|![Screenshot_2020-12-17-11-24-53-65_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/103154486-93438980-47bd-11eb-82dc-497653c9c204.jpg)|![Screenshot_2020-12-17-11-25-18-23_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/103154485-92aaf300-47bd-11eb-9214-75fe1a26230d.jpg)|![Screenshot_2020-12-17-11-25-40-87_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/64064110/103154678-f124a100-47be-11eb-8caf-dec366c43710.jpg)|

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

**Comment by rt4914** [comment]
Opening this again as it should not have been closed. @ARJUPTA In description always write this exact words: `Fixes part of #XX` and this won't close the PR.

**Comment by Arjupta** [comment]
@mschanteltc PTAL at Issue 1 and Issue 2 mentioned here

**Comment by mschanteltc** [comment]
1. The screen reader should say 'Audio, OFF, Double-tap to activate'
2. Can we add 4 dp top and bottom padding?

**Comment by Arjupta** [comment]
> 1. The screen reader should say 'Audio, OFF, Double-tap to activate'
> 2. Can we add 4 dp top and bottom padding?

@mschanteltc pardon me , i meant to say look over Issue 1 and Issue 3

**Comment by mschanteltc** [comment]
3. Audio scrub, STATE (ex: Audio scrub, PAUSED)

Is there a document keeping track of all these unique item labels?

**Comment by Arjupta** [comment]
> 1. Audio scrub, STATE (ex: Audio scrub, PAUSED)
> 
> Is there a document keeping track of all these unique item labels?

@rt4914 PTAL

**Comment by rt4914** [comment]
> 1. Audio scrub, STATE (ex: Audio scrub, PAUSED)
> 
> Is there a document keeping track of all these unique item labels?

@mschanteltc No actually because everything is getting tracked in issues only.

**Comment by Arjupta** [comment]
@rt4914 i think this is mentioned in the excel sheet i shared with you earlier

**Comment by rt4914** [comment]
> @rt4914 i think this is mentioned in the excel sheet i shared with you earlier

@ARJUPTA In that sheet we haven't mentioned the solutions for the content description that we are doing in issues only.
