### ISSUE TITLE
Incorrect indexes in `ProfileAvatar` proto

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2331]
`ProfileAvatar` proto indexing is incorrect. Instead of `5` and `6`, it should be `1` and `2`.

Reference: https://github.com/oppia/oppia-android/blob/634a49f593faa41541bbd5db6b5abfe896e7ce20/model/src/main/proto/profile.proto#L74

**Comment by coder2699** [comment]
@rt4914 I want to fix this issue. Please assign it to me.
