### ISSUE TITLE
Click on Admin Controls crash in Admin Controls

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2333]
**Describe the bug**
If we are in `Administrator Controls` screen and select `Administrator Controls` from Navigation Drawer again, it crashes the app.

**To Reproduce**
1. Select `Admin` profile.
2. Open `Navigation Drawer`
3. Select `Administrator Controls`
4. Open `Navigation Drawer`
5. Select `Administrator Controls`
The application will crash.

**Expected behavior**
The application should not crash and the navigation drawer should be closed.

**Screenshot**
<img width="1175" alt="Screenshot 2020-12-29 at 11 26 48 AM" src="https://user-images.githubusercontent.com/9396084/103261812-d6257d00-49c8-11eb-944b-9cc027451832.png">

**Comment by lakshaygarg128** [comment]
@rt4914  I would like to work over it pl. assign it to me
