### ISSUE TITLE
Convert all ViewModels to ObservableViewModel

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#234]
There is inconsistency in terms of usage of ViewModel and ObservableViewModel only if there is something to observe in that file, so to bring consistency to code convert all ViewModels to ObservableViewModels.

**Comment by rt4914** [comment]
@BenHenning Is this correct?

**Comment by BenHenning** [comment]
This is probably reasonable in the medium term. I filed #1051 to track the broader effort around improving our view data management. This may be included as part of that, though we could reasonably make this change first since it's a bit orthogonal to that issue.
