### ISSUE TITLE
Remove constraints from ScrollView in profile_reset_pin_activity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2346]
Remove constraints from ScrollView in profile_reset_pin_activity both landscape and portrait xml files.

https://github.com/oppia/oppia-android/blob/2511715a4770cda65df593cf6821b17b7f8f3d28/app/src/main/res/layout/profile_reset_pin_activity.xml#L55

**Comment by lakshaygarg128** [comment]
can i work over it ?

**Comment by lakshaygarg128** [comment]
pl. assign it to me
