### ISSUE TITLE
Change fragment implementation from directly xml code to better kotlin code [Blocked on #42, #163]

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#235]
In some cases xml files are using `fragment` tag directly to display a particular fragment.
This implementation needs to be changed and the xml should have a `FrameLayout` as container and kotlin files should initialize the corresponding fragment.

This change is needed in following cases for now:
- [ ] exploration_fragment.xml
- [ ] state_fragment.xml

**Comment by rt4914** [comment]
@BenHenning I have added this as an issue so that we do get a lot of merge conflicts in other PRs, we can solve this once StateFragmentCard implementation is finished. Blocked on #42 #163

**Comment by rt4914** [comment]
@veena14cs Assigning you `state_fragment`

**Comment by BenHenning** [comment]
Seems sensible. Thanks for filing this.
