### ISSUE TITLE
Update Ktlint version from "0.37.0" to "0.37.1"

### ISSUE THREAD

**Issue by srikanthkb** [oppia/oppia-android#2352]
Error running Ktlint vesion "0.37.0" for android files on Windows 10 OS.

**To Reproduce**
1. Download the ktlint version - "0.37.0" using Git Bash terminal on Windows with the instructions: https://github.com/pinterest/ktlint#installation 
2. After installation, run the commands here [https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#commands](url) 
3. Observe the following error when running on android files:
Reference: https://github.com/pinterest/ktlint/issues/761#issue-630042183 

![image](https://user-images.githubusercontent.com/36214903/103353273-74e7d180-4ace-11eb-9f2f-b26a9242cb6b.png)

**Expected behavior**
Following image shows the expected results from the linter, (Klinter version - "0.37.1"):
![image](https://user-images.githubusercontent.com/36214903/103397111-ce96dd00-4b5c-11eb-825c-34343de92522.png)

**Additional context**
We can upgrade the Ktlint version from "0.37.0" to "0.37.1" to fix this issue. (Results in screenshot above)

**Comment by FareesHussain** [comment]
@anandwana001 I don't think we need to update the workflow for this as it works fine.
We just need to update the wiki guiding the windows users to install the version `0.37.1`

What do you think?

**Comment by anandwana001** [comment]
The version should be in consistency everywhere

**Comment by srikanthkb** [comment]
With version `0.37.1` , the problem is solved on Windows 10 OS, and the results are as **expected** from the linter. Check the result below:
![image](https://user-images.githubusercontent.com/36214903/103394242-3e9d6700-4b4d-11eb-89a4-ba70326ed513.png)

**Comment by FareesHussain** [comment]
@Srikanth-Kb please update the title and description here
