### ISSUE TITLE
Shift helper functions `hasErrorText` and `hasNoErrorText` to central utility testing file

### ISSUE THREAD

**Issue by prayutsu** [oppia/oppia-android#2355]
**Is your feature request related to a problem? Please describe.**
Helper functions `hasErrorText` and `hasNoErrorText` is being used frequently in test files like `AdminAuthActivityTest` and it will be used in more files in future. 

**Describe the solution you'd like**
We should shift these to a central file rather than including them every time in the test files.

**Comment by prayutsu** [comment]
@anandwana001 WDYT?

**Comment by anandwana001** [comment]
Sounds good, let's block this issue till whole of the migration is done and we can open this issue then.
Also, could you please check if we are missing any other screen which needs migration, confirm the list of screens from the migration issue?

**Comment by prayutsu** [comment]
@anandwana001 Sure, I'll try finding more screens that need migration from `ProfileInputView` to `TextInputLayout`

**Comment by prayutsu** [comment]
This issue is available now.

**Comment by coder2699** [comment]
@anandwana001 I want to take this.

**Comment by coder2699** [comment]
@anandwana001 What I have done is, I have made a new file "HelperFunctions" and then I am accessing functions `hasErrorText` and `hasNoErrorText` from there in the following files:
`AddProfileActivityTest`, `AdminAuthActivityTest`, `AdminPinActivityTest` & `PinPasswordActivityTest`.

Is that all needed?

**Comment by anandwana001** [comment]
Yes, also you can take reference from EditInputAction file from testing module. The new file naming should be something so anyone can understand that this file is the reason where we can find helper functions for TextInputLayout.

**Comment by prayutsu** [comment]
@coder2699 I guess we may want to shift these helper methods in `EditTextInputAction` only as these are also related to `editText`.
@anandwana001 can confirm this.

**Comment by anandwana001** [comment]
Sounds good to me.

**Comment by coder2699** [comment]
Thanks @anandwana001 and @prayutsu , I will do as suggested.

**Comment by anandwana001** [comment]
Any update on this?

**Comment by Akshat-gour** [comment]
@anandwana001 can i work on this

**Comment by Akshat-gour** [comment]
> Yes, also you can take reference from EditInputAction file from testing module. The new file naming should be something so anyone can understand that this file is the reason where we can find helper functions for TextInputLayout.
>
@anandwana001 There is no file named EditInputAction . Do you mean EditTextInputAction .
Actually I don't know how can i  access **_context** and **TextInputLayout_** inside **_EditTextInputAction_** 
![2](https://user-images.githubusercontent.com/60266468/107266193-2df4e080-6a6b-11eb-884c-97b9a64bd673.PNG)

**Comment by anandwana001** [comment]
Adding @prayutsu for helping here.

**Comment by prayutsu** [comment]
I believe we can bring in the `context` by passing it as a parameter in the constructor of the `EditTextInputAction` Class itself. @anandwana001 But I am not sure why we are unable to import the `TextInputLayout` in the file? Can we only import the widgets from AndroidX?

**Comment by anandwana001** [comment]
a constructor can be injected. 

```kotlin
class TextInputLayoutAction @Inject constructor(
  val context: Context
) { }
```

importing `TextInputLayout` issue is more of Gradle sync issue.

**Comment by Akshat-gour** [comment]
> a constructor can be injected.
> 
> ```kotlin
> class TextInputLayoutAction @Inject constructor(
>   val context: Context
> ) { }
> ```
> 
> importing `TextInputLayout` issue is more of Gradle sync issue.

>
importing **TextInputLayout** issue is not solve even after Gradle sync , so how can i solve this

@prayutsu 
@anandwana001

**Comment by anandwana001** [comment]
multiple options:
1. invalidate cache and restart
2. clean and rebuild
3. Gradle sync 

if Gradle creates a lot of problems, then cloning is the last option

**Comment by Akshat-gour** [comment]
@anandwana001 I tried all 3 options but doesn't help .
what's cloning here means .

**Comment by anandwana001** [comment]
try clone the repo again.

**Comment by Akshat-gour** [comment]
@anandwana001 
@prayutsu 
No, that doesn't helps after cloning the repo again i tried invalidate cache and restart , clean and rebuild
and Gradle sync and also tried with newer gradle version 4.1.2 .

**Comment by Akshat-gour** [comment]
@anandwana001 
@prayutsu 
cannot import TextInputLayout in EditTextInputAction.
tried doing **invalidate cache and restart**, **clean and rebuild**, **Gradle sync**
and also cloning the repo again and also tried with newer gradle version 4.1.2

**Comment by prayutsu** [comment]
@anandwana001 I am also unable to import the TextInputLayout. It is really weird, can you try this once?

**Comment by prayutsu** [comment]
@Akshat-gour @anandwana001 Got the issue, we are unable to import this in the testing module because we don't have the material dependency in the BUILD.bazel and and build.gradle files of testing modules. 
So, you'll need to add the dependencies there.

**Comment by anandwana001** [comment]
Ah, I thought it was added, hard to catch such things without pr. 
@Akshat-gour I hope things will work fine from here now.

**Comment by Akshat-gour** [comment]
@prayutsu 
i have updated dependency in build.gradle file its working now but I cannot find Build.bazel file
Do I have to setup bazel for that .

**Comment by anandwana001** [comment]
You have to mention the dependency in the Build.bazel file which is in the testing module directly, as we are adding dependency in the gradle file of testing module.

**Comment by Akshat-gour** [comment]
@anandwana001 
@prayutsu 
like this  i have to write the dependency inside **BUILD.bazel** in block of **deps** = **artifact("com.google.android.material:material:1.2.0-alpha02")**

do I have to add this in **TEST_DEPS** block also.

**Comment by anandwana001** [comment]
I don't think so, because we are not using text input layout in any of the test files of testing module, so we don't need to add the dependency into the test deps.

**Comment by ayush0402** [comment]
@prayutsu Can I work on this?
