### ISSUE TITLE
Update tools:context in my_downloads_activity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2365]
Update tools:context in `my_downloads_activity`

Update to:
`tools:context=".app.mydownloads.MyDownloadsActivity"`

**Comment by ayaazansari** [comment]
Please assign this to me. I would like to work on this

**Comment by FareesHussain** [comment]
@ayaazansari Thanks for showing interest in Oppia.
Before you start Please have a look at [wiki](https://github.com/oppia/oppia-android/wiki#onboarding-instructions) which will help you in setting up the project and once you sign the CLA and fill the survey we can assign this to you

**Comment by ayaazansari** [comment]
@FareesHussain done
