### ISSUE TITLE
Update tools:context in profile_progress_activity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2367]
Update tools:context in profile_progress_activity

Update to:
`tools:context=".app.profileprogress.ProfileProgressActivity"`

**Comment by varunvjha** [comment]
I have fixed this. Assign this to me.

**Comment by FareesHussain** [comment]
@varunvjha did you complete the CLA?

**Comment by varunvjha** [comment]
> @varunvjha did you complete the CLA?

Yes I did

**Comment by FareesHussain** [comment]
Sure go ahead
