### ISSUE TITLE
Remove xmlns:tools from submitted_html_answer_item

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2372]
Remove xmlns:tools from submitted_html_answer_item

**Comment by Garvnanwani** [comment]
I want to work on this

**Comment by FareesHussain** [comment]
@Garvnanwani Thanks for showing interest in Oppia.
Before you start Please have a look at [wiki](https://github.com/oppia/oppia-android/wiki#onboarding-instructions) which will help you in setting up the project and once you sign the CLA and fill the survey we can assign this to you

**Comment by Garvnanwani** [comment]
done

**Comment by rt4914** [comment]
> done

@Garvnanwani I think you have not filled it completely either the survey form or the CLA. Can you please fill them once again?

**Comment by Garvnanwani** [comment]
submitted the survey @rt4914
