### ISSUE TITLE
Fix audio test cases in StateFragmentTest, AudioFragmentTest and CellularDataFragmentTest

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#239]
@jamesxu0 @BenHenning 

@veena14cs has updated the implementation of AudioFragment. Earlier, we were controlling the visibility of audio fragment inside StateFragment but practically the AudioFragment was always created.

So we have updated this implementation to creating or removing the AudioFragment only when needed.

Because of these changes test cases related to AudioFragment are failing.
@jamesxu0 can you have a look at them and update accordingly?

**Comment by BenHenning** [comment]
We should try to avoid breaking tests when checking in PRs (ie I would normally expect these to have been fixed as part of the PR that broke them rather than checking them in broken). Be aware that in the future we will block PR submission on all tests passing.
