### ISSUE TITLE
Use LessonThumbnailImageView in walkthrough_topic_summary_view

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2395]
Currently `walkthrough_topic_summary_view` uses `ImageView` and because of which the topic thumbnails are not correct as per below screenshot.

Use `LessonThumbnailImageView` in `walkthrough_topic_summary_view` to fix this issue.

You can reach this screen by making `WalkthroughActivity` as LAUNCHER in `AndroidManifest.xml` file.

![Screenshot_1609850340](https://user-images.githubusercontent.com/9396084/103647763-cdf9ae80-4f81-11eb-82f6-39d7664429a7.png)

**Comment by FareesHussain** [comment]
How do I reach this activity?

**Comment by rt4914** [comment]
> How do I reach this activity?

Updated Description

**Comment by coder2699** [comment]
@FareesHussain if you are not working on it, I would like to take it up.

**Comment by FareesHussain** [comment]
I'm working on this.

**Comment by FareesHussain** [comment]
@rt4914 I've tried this refering to `topic_summary_view`, I'm I doing it the right way?
![image](https://user-images.githubusercontent.com/54740946/103734975-0ac1b600-5013-11eb-8099-b31ddc84e57a.png)

![image](https://user-images.githubusercontent.com/54740946/103734941-fc739a00-5012-11eb-8f2b-88e74d96caf3.png)

**Comment by rt4914** [comment]
> @rt4914 I've tried this refering to `topic_summary_view`, I'm I doing it the right way?
> ![image](https://user-images.githubusercontent.com/54740946/103734975-0ac1b600-5013-11eb-8099-b31ddc84e57a.png)
> 
> ![image](https://user-images.githubusercontent.com/54740946/103734941-fc739a00-5012-11eb-8f2b-88e74d96caf3.png)

Yeah your approach seems correct @FareesHussain
