### ISSUE TITLE
Reformatting required in dimension file for better structure

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2399]
Currently the dimensions in the **dimens.xml files** are segregated in groups (all having same values). The file is too large so we must rearrange the dimensions to form the groups on the base of their name, so that we find all the the dimensions related to a particular category at once. 

**Reference**
Category structure - https://github.com/oppia/oppia-android/pull/2111#discussion_r523663618

**Comment by Roshan13046** [comment]
I would like to make a PR for this issue.
> Category structure - [#2111 (comment)](https://github.com/oppia/oppia-android/pull/2111#discussion_r523663618)
Should I Rearrange in only 5 categories as mentioned below?
> ```
> 
> 
> 
> 
> 
> ...
> ...
> ...
> ```

**Comment by Arjupta** [comment]
> I would like to make a PR for this issue.
> 
> > Category structure - [#2111 (comment)](https://github.com/oppia/oppia-android/pull/2111#discussion_r523663618)
> > Should I Rearrange in only 5 categories as mentioned below?
> > ```
> > 
> > 
> > 
> > 
> > 
> > ...
> > ...
> > ...
> > ```

Assigning it to you

**Comment by Roshan13046** [comment]
> > I would like to make a PR for this issue.
> > > Category structure - [#2111 (comment)](https://github.com/oppia/oppia-android/pull/2111#discussion_r523663618)
> > > Should I Rearrange in only 5 categories as mentioned below?
> > > ```
> > > 
> > > 
> > > 
> > > 
> > > 
> > > ...
> > > ...
> > > ...
> > > ```
> 
> Assigning it to you

Should I Rearrange in only 5 categories only?
Are there more categories?

**Comment by Arjupta** [comment]
> > > I would like to make a PR for this issue.
> > > > Category structure - [#2111 (comment)](https://github.com/oppia/oppia-android/pull/2111#discussion_r523663618)
> > > > Should I Rearrange in only 5 categories as mentioned below?
> > > > ```
> > > > 
> > > > 
> > > > 
> > > > 
> > > > 
> > > > ...
> > > > ...
> > > > ...
> > > > ```
> > 
> > 
> > Assigning it to you
> 
> Should I Rearrange in only 5 categories only?
> Are there more categories?

@Roshan13046 try to do it for these 5 categories first and then if you find some dimensions left after that , then consider to find more ways to group them. But if you are unable to do so then create a PR and ask me for a review.

**Comment by Arjupta** [comment]
@Roshan13046 any update on this Issue?

**Comment by Arjupta** [comment]
Removing the assignment as there is no further update from previous contributor

**Comment by kartikeysaran** [comment]
I am working on this issue

**Comment by dmdbilal** [comment]
Is this issue still open ?

**Comment by BenHenning** [comment]
Can you confirm @rt4914?

**Comment by Yashsomalkar** [comment]
@MohitGupta121  I would like to work on this issue.

**Comment by MohitGupta121** [comment]
@Yashsomalkar assigned go ahead.
If you have any query feel free to ask me or in GitHub Discussion.

**Comment by Yashsomalkar** [comment]
Sorry for the delay. The file had a lot of content and was also busy with some college stuff.

**Comment by MohitGupta121** [comment]
> Sorry for the delay. The file had a lot of content and was also busy with some college stuff.

Okay sure, no problem now please continue your PR.

**Comment by MohitGupta121** [comment]
@Yashsomalkar are you still woking on this issue? If you blocked somewhere please feel free to ask. or we unassign you this issue if you not working on this?

**Comment by Yashsomalkar** [comment]
> @Yashsomalkar are you still woking on this issue? If you blocked somewhere please feel free to ask. or we unassign you this issue if you not working on this?
> 
> 

I am working there is an issue i have mentioned you in PR please check that out

**Comment by MohitGupta121** [comment]
@Yashsomalkar please link your PR with the issue by adding #tag issue number in PR description

**Comment by Yashsomalkar** [comment]
> @Yashsomalkar please link your PR with the issue by adding #tag issue number in PR description

Yes i have did it its above over conversations. Should i tag it again ?

**Comment by MohitGupta121** [comment]
> 

No it's good.
