### ISSUE TITLE
Final UI: ConceptCardFragment [Blocked: #15, #160]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#24]
The concept card should provide background information on the skill it corresponds to, including worked examples. It should also provide the option for the user to work through practice questions to learn more about that skill. See the PRD for specifics.

Note: from the mocks, this is an inline component within the content card view, though it can also be viewed when reviewing concepts from the topic.

Mock: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/2ee531cf-c358-4a7d-b9dd-b772b51c3d3c/PM-Q2-Concept-Card-

## Checklist
- [ ] Toolbar
<img width="329" alt="Screenshot 2019-11-08 at 4 02 20 PM" src="https://user-images.githubusercontent.com/9396084/68469978-34315700-0241-11ea-85bd-6a5d7d5c3715.png">

- [ ] Content
<img width="326" alt="Screenshot 2019-11-08 at 4 02 24 PM" src="https://user-images.githubusercontent.com/9396084/68469987-35fb1a80-0241-11ea-8c5f-095863ca81c2.png">

- [ ] Final touch up with padding, margin, animations and Accessibility Scanner test

**Comment by BenHenning** [comment]
This is blocked on #15.

**Comment by BenHenning** [comment]
This is also blocked on #160.

**Comment by rt4914** [comment]
This issue has been finished. It can be closed now.
