### ISSUE TITLE
Resolve ktlint max line in player test package

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2403]
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name. 
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the function name under 100 char length. 

Where to start?
https://github.com/oppia/oppia-android/blob/d2d55013605d318965594932b9224578cbc9a586/app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt#L291

**Comment by nskirkey** [comment]
I was hoping to assigned to this. I was assigned the unsplit PR and had been working on a script to help me go thru and fix the fun names.

**Comment by anandwana001** [comment]
@nskirkey any update on this?

**Comment by som23ya** [comment]
@anandwana001 can I work on this?

**Comment by som23ya** [comment]
@anandwana001 Doubt regarding shortening the length of names:
Can I change words like CONFIGURATION to CONFIG and LANGUAGE to LANG.

 eg, :-

-testStateFragment_loadExp_changeConfiguration_buttonIsNotVisible()
+testState_loadExp_changeConfig_buttonIsNotVisible()

-testAudioFragment_HindiAudioLanguageProfile_showsHindiAudioLanguage() 
+testAudio_HindiAudioLangProfile_showsHindiAudioLang()

**Comment by anandwana001** [comment]
we use `configChange`, `IsDisplayed` in place of shows. 

```kotlin
fun testStateFragment_loadExp_configChange_buttonIsNotDisplayed()
fun testAudioFragment_hindiAudioLangProfile_hindiAudioLangIsDisplayed()
```

A draft PR will be helpful for such a discussion.

**Comment by som23ya** [comment]
#2640 Drafted a pull request for player package.

**Comment by pravesh00** [comment]
@anandwana001 Can I work on this?
