### ISSUE TITLE
Resolve ktlint max line in profile test package

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2404]
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name. 
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the function name under 100 char length.

**Comment by zyberg2091** [comment]
Can you assign me this issue?

**Comment by MaskedCarrot** [comment]
@zyberg2091 assigning this to you. You have to follow all steps mentioned on https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started.

**Comment by rt4914** [comment]
> @zyberg2091 assigning this to you. You have to follow all steps mentioned on https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up to get started.

Thanks @MaskedCarrot for helping out.

**Comment by varunvjha** [comment]
I'd like to work on this since the previously assigned person unassigned himself. Assign me please if it's okay.
