### ISSUE TITLE
Resolve ktlint max line in topic test package

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2408]
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name. 
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the function name under 100 char length.

**Comment by varunvjha** [comment]
Please assign me this issue.

**Comment by varunvjha** [comment]
@anandwana001 Could you help me in navigating to the issue?

**Comment by anandwana001** [comment]
Reference - https://github.com/oppia/oppia-android/blob/83e409a64bbff8c1e724c4e52dfed71f8a70ec40/app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt#L279

As you can see here we are putting a comment ktlint, this comment is preventing the ktlint to check the 100 char length for this particular code line. We need to remove this comment and shorten the function name so that the code line will have maximum 100 char so that ktlint can be pass on this.

**Comment by varunvjha** [comment]
@anandwana001 PTAL.
