### ISSUE TITLE
Logout Dialog disappears on orientation change

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2427]
**Describe the bug**
In `Adminstrator Controls` screen logout dialog on orientation change disappears 

**To Reproduce**
1. Go to 'Administrator Controls'
2. Click on 'Log Out'
3. Rotate to Landscape
4. Dialog disappears

**Expected behavior**
Alert dialog should persist on orientation change. Also add test for the same in respective file.

**Video**
<img src="https://user-images.githubusercontent.com/54740946/103887266-c9abcd80-5108-11eb-85b9-b525289cd0f6.gif" width="32%"/>

**Comment by GowthamGoush** [comment]
May I work on this?

**Comment by chrk2205** [comment]
can i work on this??
@GowthamGoush 
@FareesHussain

**Comment by FareesHussain** [comment]
@GowthamGoush any updates on this?

**Comment by GowthamGoush** [comment]
I started understanding the code base but I am still elated to get help on this issue on where to get started.

**Comment by FareesHussain** [comment]
@GowthamGoush Adding references on how to fix this
`AdministratorControlsAccountActionsViewmodel.kt` this is where the `AlertDialog` is being created

Take a look at https://github.com/oppia/oppia-android/pull/2458 on how to solve the issue

Reach out if you face any issues regarding this

**Comment by FareesHussain** [comment]
> can i work on this??
> @GowthamGoush
> @FareesHussain

@chrk2205 I think @GowthamGoush will be working on this meanwhile please take a look at other issues

And @GowthamGoush if you are not interested in this issue it is also fine I will unassign you and you can take a look at other issues please reach out if you are struck at any point

**Comment by GowthamGoush** [comment]
Thanks for the support and hope I will be able to fix this soon.

**Comment by GowthamGoush** [comment]
I am confused with which activity should be set as the observer. Could you help me out?

**Comment by FareesHussain** [comment]
> I am confused with which activity should be set as the observer. Could you help me out?

`AdminstratorControlsActivity` is the only activity associated with Log out

**Comment by GowthamGoush** [comment]
I tried my best but I couldn't figure it out. Could you help with the step by step procedure?

**Comment by chrk2205** [comment]
@GowthamGoush 
maybe you can start writing with a test case which fails for this bug??
for reference https://github.com/oppia/oppia-android/pull/2458/files#r555591990

**Comment by chrk2205** [comment]
@GowthamGoush
https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAccountActionsViewModel.kt
This is the View Model responsible for showing the  Logout dialog
This being called from `AdministratorControlsFragment`  for this maybe you can use `onPause` and state to check if the dialog has appeared and `OnResume` use it to show the dialog again.
Hope this helps

**Comment by chrk2205** [comment]
@rt4914 
@FareesHussain 
@BenHenning 
for this, we should the function inside ViewModel so the dialog still shows up after orientation change.
So I am not sure if we can trigger the function of ViewModel from the fragment Presenter.?
thanks

**Comment by anandwana001** [comment]
unassigning, as no further update.

**Comment by Sparsh1212** [comment]
I would like to work on this.

**Comment by anandwana001** [comment]
@Sparsh1212 As you had already solved multiple Good First Issue, I suggest you look for a bit harder issues. It helps you grow learning towards codebase too.

**Comment by Sparsh1212** [comment]
> @Sparsh1212 As you had already solved multiple Good First Issue, I suggest you look for a bit harder issues. It helps you grow learning towards codebase too.

Sure! I will look for harder issues.

**Comment by ArpitShukIa** [comment]
I would like to work on this issue.

**Comment by FareesHussain** [comment]
@ArpitShukIa as you've already worked on few issues. I suggest looking for a bit harder issues. This will help you in learning and get to know more about the codebase.

https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+milestone%3ABeta+no%3Aassignee+-label%3A%22good+first+issue%22+NOT+a11y+NOT+blocked

**Comment by sakshampruthi** [comment]
I would like to try this out

**Comment by sakshampruthi** [comment]
I have found a workaround for this issue. Since the function is being directly called from the XML using data binding I am unable to figure out a way to store the orientation state. Upon research, I found a flag `configChanges` for the activity to be implemented in AndroidManifest. Setting the flag allows the dialog to remain on the screen when the device is rotated and doesn't get detached from the activity and is working perfectly fine

**Comment by ArpitShukIa** [comment]
@sakshampruthi Are you talking about disabling configuration change for the activity?

**Comment by sakshampruthi** [comment]
@ArpitShukIa No, I am not disabling orientation. Orientation works as expected. I am setting the flag as orientation|screenSize. So putting that in the configuration file avoids the system to destroy the AdministratorControlsActivity. Instead, it invokes the onConfigurationChanged(Configuration) method. Here is the output:

https://user-images.githubusercontent.com/43927531/111260870-96754580-8647-11eb-8c0e-0a8fa763f6ae.mp4

**Comment by ArpitShukIa** [comment]
@sakshampruthi Preventing the activity from being destroyed won't be a nice thing to do I think.
https://developer.android.com/guide/topics/resources/runtime-changes#HandlingTheChange

Maybe you should try to override `AdministratorControlsActivity's` `onSaveInstanceState()` and store whether the dialog is open or not in the `bundle`.
Then in `onCreate()` you can check `savedInstanceState` to see if the dialog needs to be recreated.

**Comment by sakshampruthi** [comment]
@ArpitShukIa I am understood what needs to be done but I am unable to recreate the dialog as I am unable to get the reference of `onLogOutClicked()` from `AdministratorControlsAccountActionsViewModel`. It would be great if you could help me out

**Comment by ArpitShukIa** [comment]
@sakshampruthi Since it's the `AdministratorControlsAccountActionsViewModel` which is creating the dialog, `AdministratorControlsActivity` needs to ask that ViewModel whether the dialog is being currently shown or not, and also tell it to show when needed.

Now that the activity is not having a direct reference to the ViewModel, you will need to create functions to get and give the information.
AdministratorControlsActivity -> AdministratorControlsActivityPresenter -> AdministratorControlsFragment -> AdministratorControlsFragmentPresenter -> AdministratorControlsViewModel -> AdministratorControlsAccountActionsViewModel

Create two functions in the in-between classes, one which will get dialog status from next class and return it to the previous one, and a second function which will ask the next class to show the dialog.
(Here, `next` and `previous` are in the context of above chain that I mentioned.

**Comment by sakshampruthi** [comment]
Okay understood. I will try this and get back soon ✌️

**Comment by sakshampruthi** [comment]
@rt4914 
@FareesHussain 
My approach till now is that I have created a live data variable in `AdministratorControlsAccountActionsViewModel` to be set when the dialog box is opened and when it's dismissed. The problem I am facing where should I observe it (in which activity or fragment) as `AdministratorControlsAccountActionsViewModel` requires arguments to be passed to create its reference

**Comment by FareesHussain** [comment]
@sakshampruthi sorry for the delay. I suggest you try to fix this first by trying it in both activity or fragment and once it is fixed create a pull request. 
If you are stuck at some point you can create a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

**Comment by sakshampruthi** [comment]
> No, I am not disabling orientation. Orientation works as expected. I am setting the flag as orientation|screenSize. So putting that in the configuration file avoids the system to destroy the AdministratorControlsActivity. Instead, it invokes the onConfigurationChanged(Configuration) method. Here is the output:
> 
>  Screen_Recording_20210316-110311_Oppia_1.mp4

@FareesHussain Won't this work since this activity doesn't need to update resources during a specific configuration change and will be used just to log out and open the edit profiles which is once in a while action. I am only suggesting this because the parameters required by 'AdministratorControlsAccountActionsViewModel' are not present in either the activity or fragment

**Comment by FareesHussain** [comment]
@sakshampruthi Sounds good to me. Please create a PR for this.

Rather than confirming the approach in the issue, It is suggested to create a PR and discuss the approach there.

**Comment by ArpitShukIa** [comment]
@rt4914 Can I take this up?

**Comment by ArpitShukIa** [comment]
@rt4914 Can u suggest which approach should be taken? Does it require a new DialogFragment or shall I just use the onSaveInstanceState() in the Activity?

**Comment by rt4914** [comment]
@ArpitShukIa Suggest using `DialogFragment` similar to `AdminSettingsDialogFragment ` instead of AlertDialog. That will take care of lifecycle.
