### ISSUE TITLE
Create multiple build flavors in Bazel

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#2432]
While we don't yet have compile-time feature gating, we should be introducing different flavors of the app in Bazel builds. Specifically, we should have:
- oppia_dev: a developer-only build with native multidex and no proguard optimizations
- oppia_prod: a production-facing build with legacy multidex and with proguard optimizations including 3-pass optimization (this needs to be verified as working since we've run into dex limit issues with databinding)

Longer-term, we will likely want alpha/beta/ga versions of the prod build. Ideally, these would also be Android app bundles rather than APKs, but that's blocked on https://github.com/bazelbuild/bazel/issues/11497.

**Comment by navneetsaluja** [comment]
I can try making the builds. Could you point me to any references/ resources which can be helpful?

**Comment by FareesHussain** [comment]
> I can try making the builds. Could you point me to any references/ resources which can be helpful?

I think this is blocked on some issue 
@BenHenning is this open to work now ?

**Comment by BenHenning** [comment]
This requires some design. It could be done now, but part of this issue is defining the flavors and and how they should be built/what they should contain. It might be best to wait until feature gating is done before starting this.

**Comment by BenHenning** [comment]
https://github.com/bazelbuild/bazel/issues/11497#issuecomment-855094406 is promising. We could try this out soon and see if bundles can build.

**Comment by BenHenning** [comment]
Ah. We may need to change that TODO or resolve it as part of your PR @anandwana001.
