### ISSUE TITLE
Ship 0.5-alpha version of Oppia Android [Blocked: #2436]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#2437]
This is the master tracking issue for shipping version 0.5 alpha version of Oppia Android for current PM team members, and for upcoming user studies.

**Comment by BenHenning** [comment]
@vinitamurthi assigning this to you to start. Please assign back to me with details around which specific topics you've confirmed that we should be including in the 0.5 release of the app. Per #2436 my plan is to include as many topics as we can, but if there's any additional work needed (e.g. inclusion of a topic not yet supported by the app or manual introduction of questions) please let me know.

**Comment by vinitamurthi** [comment]
If possible I would like to have the following topics:
1) Place Values
2) Multiplication

Atleast one of these topics should have 10 questions. I think the previous alpha already had questions for multiplication. We could potentially reuse them.

**Comment by BenHenning** [comment]
This has been completed since this version of the app has been shipped.
