### ISSUE TITLE
Remove waitForTheView() from ProfileProgressFragmentTest

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2445]
**Describe the bug**
`waitForTheView` is defined in `ProfileProgressFragmentTest` which is of no use. 

**Expected behavior**
We should not use such delays like `waitForTheView` as we are using `testCoroutineDispatchers` for delays.

#### Steps to solve this issue:
1. Run test cases on Espresso and check if all test cases are passing or not
2. Run test cases on Robolectric and check if all test cases are passing or not
3. Remove all the use of `waitForTheView` and function.
4. Run test cases on Espresso and check if all test cases are passing or not
5. Run test cases on Robolectric and check if all test cases are passing or not

Add screenshots of test results in the PR description. 
[How to run test on Robolectric?](https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-robolectric-tests)

**Comment by varunvjha** [comment]
Can I work on this issue? Also, do enlighten me on how to run test cases on Espresso and Roboelectric.

**Comment by khushal1707** [comment]
If not already assigned, I like to work on the issue.

**Comment by anandwana001** [comment]
> Can I work on this issue? Also, do enlighten me on how to run test cases on Espresso and Roboelectric.

We personally suggest to onboarded contributors to go for more harder issues than good first issues.

**Comment by anandwana001** [comment]
> If not already assigned, I like to work on the issue.

Please start with the Onboarding process
https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by khushal1707** [comment]
> > If not already assigned, I like to work on the issue.
> 
> Please start with the Onboarding process
> https://github.com/oppia/oppia-android/wiki#onboarding-instructions

Already did!

**Comment by khushal1707** [comment]
This is already solved in develop branch, hence not required.

**Comment by anandwana001** [comment]
Thanks @khushal1707 for confirming. CLosing this issue.
