### ISSUE TITLE
Improving the code coverage for .java files

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2449]
**Describe the bug**
While translating to java, some of the lines break
example - https://github.com/oppia/oppia-android/blob/70c486f733a63a8e6367ae0c8e71876379f659c9/app/src/main/java/org/oppia/android/app/databinding/ImageViewBindingAdapters.java#L59
It's fixed in https://github.com/oppia/oppia-android/pull/2101 

**Expected behavior**
Need a track improving the code coverage in all `.java` files.  

**Additional context**
Reference - https://github.com/oppia/oppia-android/pull/2101#discussion_r528055704

**Comment by FareesHussain** [comment]
I am working on this

**Comment by ayan-biswas0412** [comment]
@anandwana001 is there anyone working on this issue ? Can I take this ? if yes can you elaborate what to do actually

**Comment by anandwana001** [comment]
Closing this issue as it is something we had covered in the App module testing for UI.
