### ISSUE TITLE
Fix test testRecentlyPlayedTestActivity_clickOnToolbarNavigationButton_closeActivity [Testing]

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2450]
**Describe the bug**
The test `testRecentlyPlayedTestActivity_clickOnToolbarNavigationButton_closeActivity` is only performing action.
Find this test in `RecentlyPlayedFragmentTest` app module.

**Expected behavior**
3 components of Espresso test 
1. ViewMatchers
2. ViewActions
3. ViewAssertions

There are no ViewAssertions in this test case, which means this test is checking nothing. As per the test name, we need to test the activity is closing or not.

**Comment by lakshaygarg128** [comment]
pl. assign it to me . I would like to work upon it

**Comment by anandwana001** [comment]
As you had already done good-first-issue, we recommend looking for harder issues to work on.

**Comment by rohanakut** [comment]
Hey, I would like to work on this issue. I have filled the CLI and contributions survey

**Comment by anandwana001** [comment]
@rohanakut Any update on this? Also, pleae join our Gitter channel for all the communication. https://gitter.im/oppia/oppia-android

**Comment by alwin48** [comment]
I would like to work on this.

**Comment by rt4914** [comment]
> I would like to work on this.

@alwin48 Assigned. Thanks.

**Comment by alwin48** [comment]
I still have to learn more about testing. Sorry

**Comment by FareesHussain** [comment]
> I still have to learn more about testing. Sorry

You can have a look at other test cases and implement similar to them. Feel free to ask here

**Comment by alwin48** [comment]
> > I still have to learn more about testing. Sorry
> 
> You can have a look at other test cases and implement similar to them. Feel free to ask here

Okay, thanks

**Comment by anandwana001** [comment]
@alwin48 https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing This might help

**Comment by harsh-hash** [comment]
can i work on this?

**Comment by Sparsh1212** [comment]
@anandwana001 Please assign this to me if it is available.

**Comment by FareesHussain** [comment]
@Sparsh1212 as you are assigned to [4 other issues](https://github.com/oppia/oppia-android/issues/assigned/Sparsh1212). I would recommend you to wait for those to get merged first.
