### ISSUE TITLE
Optimise TextInputLayout in profile_rename_activity

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2461]
Remove `android:textDirection="locale"` in `TextInputLayout` from the following files
 - layout/profile_rename_activity
 - layout-land/profile_rename_activity

**Comment by GowthamGoush** [comment]
I would like to work in this.
Can you assign this to me?

**Comment by FareesHussain** [comment]
> I would like to work in this.
> Can you assign this to me?

@GowthamGoush Thanks for showing interest in oppia. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by GowthamGoush** [comment]
I have filled that sir
