### ISSUE TITLE
Optimise TextInputLayout in admin_pin_activity 

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2462]
Remove `android:textDirection="locale"` in `TextInputLayout` from the following files
 - layout/admin_pin_activity
 - layout-land/admin_pin_activity
 - sw600dp/admin_pin_activity
 - sw600dp-land/admin_pin_activity

**Comment by som23ya** [comment]
Can I work on this?

**Comment by FareesHussain** [comment]
> Can I work on this?

@som23ya Thanks for showing interest in oppia. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by dipu989** [comment]
Can I work upon this?

**Comment by priyanka0906** [comment]
Can I work on this?

**Comment by som23ya** [comment]
@FareesHussain  hey, I have completed the onboarding instructions, signed the CLA, and have set up the project. I saw this as a good first issue so I had asked to work on it. 😅

**Comment by rt4914** [comment]
> @FareesHussain hey, I have completed the onboarding instructions, signed the CLA, and have set up the project. I saw this as a good first issue so I had asked to work on it. 😅

@som23ya This issue is assigned to @priyanka0906 . You can pick other issue from https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22good+first+issue%22

**Comment by FareesHussain** [comment]
> @FareesHussain hey, I have completed the onboarding instructions, signed the CLA, and have set up the project. I saw this as a good first issue so I had asked to work on it.

@som23ya There was no response for 14 days so I had to assign it to Priyanka. You can pick other issues I'll be adding a bunch of good-first-issues soon
