### ISSUE TITLE
Optimise TextInputLayout in profile_reset_pin_activity

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2463]
Remove `android:textDirection="locale"` in `TextInputLayout` from the following files
 - layout/profile_reset_pin_activity
 - layout-land/profile_reset_pin_activity

**Comment by alwin48** [comment]
I would like to work on this issue

**Comment by rt4914** [comment]
> I would like to work on this issue

@alwin48 Please check our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by alwin48** [comment]
> > I would like to work on this issue
> 
> @alwin48 Please check our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

I will check out the wiki once more. I have already signed the CLA and have filled the survey form

**Comment by rt4914** [comment]
> > > I would like to work on this issue
> > 
> > 
> > @alwin48 Please check our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.
> 
> I will check out the wiki once more. I have already signed the CLA and have filled the survey form

Can you please check that you have signed the CLA and filled the survey correctly/completely? Because if it would have been correct I would have received an automated email.

**Comment by alwin48** [comment]
> > > > I would like to work on this issue
> > > 
> > > 
> > > @alwin48 Please check our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.
> > 
> > I will check out the wiki once more. I have already signed the CLA and have filled the survey form
> 
> Can you please check that you have signed the CLA and filled the survey correctly/completely? Because if it would have been correct I would have received an automated email.

Okay I'll check it.

**Comment by alwin48** [comment]
> > > > I would like to work on this issue
> > > 
> > > 
> > > @alwin48 Please check our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.
> > 
> > 
> > I will check out the wiki once more. I have already signed the CLA and have filled the survey form
> 
> Can you please check that you have signed the CLA and filled the survey correctly/completely? Because if it would have been correct I would have received an automated email.

I looked into it but its saying I have already submitted the form

**Comment by rt4914** [comment]
> > > > > I would like to work on this issue
> > > > 
> > > > 
> > > > @alwin48 Please check our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.
> > > 
> > > 
> > > I will check out the wiki once more. I have already signed the CLA and have filled the survey form
> > 
> > 
> > Can you please check that you have signed the CLA and filled the survey correctly/completely? Because if it would have been correct I would have received an automated email.
> 
> I looked into it but its saying I have already submitted the form

Sounds good
