### ISSUE TITLE
Optimise TextInputLayout in admin_settings_dialog

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2465]
Remove `android:textDirection="locale"` in `TextInputLayout` from the following files
 - layout/admin_settings_dialog
 - layout-land/admin_settings_dialog

**Comment by arhamathar** [comment]
I would like to work on this, please assign this to me.

**Comment by lakshaygarg128** [comment]
@arhamathar please complete the onboarding instructions before starting with the contributions. 
https://github.com/oppia/oppia-android/wiki

**Comment by rt4914** [comment]
> I would like to work on this, please assign this to me.

@arhamathar Please check our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by dipu989** [comment]
Can you please assign this issue to me?

**Comment by arhamathar** [comment]
> > I would like to work on this, please assign this to me.
> 
> @arhamathar Please check our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

DONE !


> > I would like to work on this, please assign this to me.
> 
> @arhamathar Please check our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

Done !

**Comment by arhamathar** [comment]
> > I would like to work on this, please assign this to me.
> 
> @arhamathar Please check our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

Done !
