### ISSUE TITLE
Use profileId as property [Testing]

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2468]
**Describe the bug**
Currently, `profileId` is an immutable variable in `@Before`, which creates every time before called up. 

https://github.com/oppia/oppia-android/blob/022b4c6d242d28e5c8dc2e030abef8b16f2b55c6/app/src/sharedTest/java/org/oppia/android/app/completedstorylist/CompletedStoryListActivityTest.kt#L106

**Expected behavior**
Use `profileId` as an immutable property 

**Additional Reference**
[What is a property in kotlin?](https://kotlinlang.org/docs/reference/properties.html)

Comment below if you want to work on this, please don't self-assign.

**Comment by chrk2205** [comment]
i would like to work on this?
@anandwana001

**Comment by dipu989** [comment]
@anandwana001 Can I work upon this issue?

**Comment by anandwana001** [comment]
Assigning @dipu989 as he is the first-time contributor and @chrk2205 is already an onboarded contributor so I suggest looking for a bit harder issues.
