### ISSUE TITLE
Add support for early ending question assessements

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#248]
When playing through a question assessment, it should be possible for the assessment to end prematurely if the learner has sufficiently demonstrated proficiency in the topic. This is supported by the question assessment progress controller API, but the implementation does not yet provide this functionality.

**Comment by rt4914** [comment]
@BenHenning Is this issue and #501 issue is same?

**Comment by BenHenning** [comment]
@rt4914 is correct that this is a duplicate of #501.

**Comment by BenHenning** [comment]
The AI here is to remove the TODO & close this issue.
