### ISSUE TITLE
Spacing issue in `colors` folder xml files

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2483]
In below mentioned folder(s) there are 4 files which contains nit spacing issue. There should be one blank space just before `/>`.

https://github.com/oppia/oppia-android/tree/develop/app/src/main/res/color
https://github.com/oppia/oppia-android/tree/develop/app/src/main/res/color-sw600dp-port
https://github.com/oppia/oppia-android/tree/develop/app/src/main/res/color-sw600dp-land

You can also fix this by using reformatting shortcut: https://github.com/oppia/oppia-android/wiki/Coding-style-guide#code-formatting

**Comment by Manikant25** [comment]
Can I fix it?
