### ISSUE TITLE
Required reformatting for some individual xml files

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2487]
The following files require reformatting
 - audio_fragment.xml
 - profile_picture_edit_dialog.xml
 - submitted_html_answer_item.xml
 - test_text_view_for_int_no_data_binding.xml
 - test_text_view_for_int_with_data_binding.xml
 - test_text_view_for_string_no_data_binding.xml
 - test_text_view_for_string_with_data_binding.xml

Recommended to setup [Macros](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros) to solve this issue

References 
 - https://github.com/oppia/oppia-android/wiki/Coding-style-guide#code-formatting
 - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros

**Comment by Mehul-Bisht** [comment]
May I work on this issue?
