### ISSUE TITLE
Required Reformatting for administrator_controls_general_view.xml

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2488]
The following files require reformatting
 - layout/administrator_controls_general_view.xml
 - layout-land/administrator_controls_general_view.xml
 - layout-sw600dp/administrator_controls_general_view.xml 

Recommended to set up [Macros](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros) to solve this issue

References
 - https://github.com/oppia/oppia-android/wiki/Coding-style-guide#code-formatting
 - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros

**Comment by Mehul-Bisht** [comment]
May I work on this issue?

**Comment by FareesHussain** [comment]
> May I work on this issue?

As you've been assigned to more than 2 `good-first-issues`, I recommend you to go for harder issues.

**Comment by chrk2205** [comment]
can i work on this??
