### ISSUE TITLE
Required Reformatting for administrator_controls_download_permissions_view.xml

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2489]
The following files require reformatting
 - layout/administrator_controls_download_permissions_view.xml
 - layout-land/administrator_controls_download_permissions_view.xml
 - layout-sw600dp/administrator_controls_download_permissions_view.xml 

Recommended to set up [Macros](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros) to solve this issue

References
 - https://github.com/oppia/oppia-android/wiki/Coding-style-guide#code-formatting
 - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros

**Comment by dipu989** [comment]
Would like to work on this! Never worked with Macros before.

**Comment by FareesHussain** [comment]
> Would like to work on this! Never worked with Macros before.

@dipu989 as you have worked on more than 2 `good-first-issues` it is recommended to go for harder issues. 
You'll be using macros for the harder issues too

**Comment by Mehul-Bisht** [comment]
Can I start working on this issue?
