### ISSUE TITLE
Required Reformatting for administrator_controls_app_information_view.xml

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2490]
The following files require reformatting
 - layout/administrator_controls_app_information_view.xml
 - layout-land/administrator_controls_app_information_view.xml
 - layout-sw600dp/administrator_controls_app_information_view.xml 

Recommended to set up [Macros](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros) to solve this issue

References
 - https://github.com/oppia/oppia-android/wiki/Coding-style-guide#code-formatting
 - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros

**Comment by Mehul-Bisht** [comment]
Can I work on this issue?

**Comment by Mehul-Bisht** [comment]
Hey! Should I never be committing the changes that android studio generates inside the Project.xml file?

**Comment by FareesHussain** [comment]
> Hey! Should I never be committing the changes that android studio generates inside the Project.xml file?

yes
