### ISSUE TITLE
Required Reformatting for administrator_controls_account_actions_view.xml

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2491]
The following files require reformatting
 - layout/administrator_controls_account_actions_view.xml
 - layout-land/administrator_controls_account_actions_view.xml
 - layout-sw600dp/administrator_controls_account_actions_view.xml 

Recommended to set up [Macros](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros) to solve this issue

References
 - https://github.com/oppia/oppia-android/wiki/Coding-style-guide#code-formatting
 - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros

**Comment by Manikant25** [comment]
Can I work on this?

**Comment by FareesHussain** [comment]
> Can I work on this?

@Manikant25 Thanks for showing interest in oppia. Please check out our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by Manikant25** [comment]
I have gone through this before.

**Comment by Manikant25** [comment]
![Screenshot from 2021-01-17 02-51-58](https://user-images.githubusercontent.com/55659857/104823311-4f4d1d00-586f-11eb-8403-1fd49801e6ea.png)
This folder named oppia-android-tools is made but Ktlint is not there.  Please check if there is an error.

**Comment by Manikant25** [comment]
We have to set up one macro and it can be used in all XML files. Please correct me if I am wrong

**Comment by FareesHussain** [comment]
> We have to set up one macro and it can be used in all XML files. Please correct me if I am wrong

Yes you can use the same macro for all xml files
