### ISSUE TITLE
Error message disappears on configuration changes for AddProfileActivity

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2496]
**Describe the bug**
Error message in TextInputLayout disappears on configuration changes for AddProfileActivity

same for the AdminPinActivity, ProfileRename, AdminSettings, ProfileResetPin

**Expected behavior**
Error message should remain same after orientation change

**Comment by FareesHussain** [comment]
@anandwana001 for this do we have to go through the reversion process https://github.com/oppia/oppia-android/pull/2344

btw this issue was not found in https://github.com/oppia/oppia-android/pull/2344

**Comment by prayutsu** [comment]
@FareesHussain Can you please add some screenshots or a video for a better understanding?

**Comment by FareesHussain** [comment]
<img src="https://user-images.githubusercontent.com/54740946/104834774-a1219180-58c7-11eb-9c73-05031ce18302.gif" width="33%"/>

**Comment by khushal1707** [comment]
I think we are unable to retain `nameErrorMsg` from `AddProfileViewModel.kt` during the orientation change when activity restarts. Can I work on this issue?

**Comment by FareesHussain** [comment]
@prayutsu can you have a look at this 
In this issue is at some point all the tests related to Migration to TextInputLayout fails now in espresso can you please help to find out the cause here

**Comment by chrk2205** [comment]
i would like to work on this!!
@FareesHussain

**Comment by FareesHussain** [comment]
> i would like to work on this!!
> @FareesHussain

I think the cause needs to be discussed before working on this as the tests were passing at that time

**Comment by chrk2205** [comment]
> > i would like to work on this!!
> > @FareesHussain
> 
> I think the cause needs to be discussed before working on this as the tests were passing at that time

actually the bug is not in showing in my application!!

**Comment by FareesHussain** [comment]
@chrk2205 can you verify if your branch is up-to-date and also add a video for that

**Comment by chrk2205** [comment]
> @chrk2205 can you verify if your branch is up-to-date and also add a video for that

No I am updating that @FareesHussain

**Comment by prayutsu** [comment]
> @prayutsu can you have a look at this
> In this issue is at some point all the tests related to Migration to TextInputLayout fails now in espresso can you please help to find out the cause here

Yes, this is weird, this was not happening when we were migrating.

**Comment by prayutsu** [comment]
@FareesHussain I am trying to find out the reason for this, will update you if I find something.

**Comment by FareesHussain** [comment]
Will fill a separate issue after discussing this issue
