### ISSUE TITLE
Tests Failing on Espresso in Landscape with small screen size or bug

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2502]
**Describe the bug**
After the migration to `TextInputLayout`, few test cases are failing on Espresso with small screen size.

**Expected behavior**
All the test case should pass on multiple device screen size. Pixel, Pixel XL, Nexus 4, Tablet.

**How to submit PR**
Add test result screenshot for Espresso and Robolectric on devices mentioned above. 

**Additional context**
```kotlin

// possibly scrolling issue 
(@FareesHussain )
fun testAddProfileActivity_inputPin_inputDifferentConfirmPin_clickCreate_changeConfiguration_checkErrorMessageDisplayed() 

// possibly scrolling issue 
(@FareesHussain )
fun testAddProfileActivity_inputNotUniqueName_clickCreate_changeConfiguration_checkErrorMessageDisplayed()

// here, the error message is not displayed after orientation change. Need to investigate why this is passing earlier and why this is failing now. 
(@FareesHussain )
fun testProfileRenameActivity_inputOldName_clickSave_changeConfiguration_errorIsVisible() 

// Also confirm, can we update this layout file with using Neste Scroll View? 
(@prayutsu )
fun testAdminPinActivity_configurationChange_inputPin_inputWrongConfirmPin_clickImeActionButton_checkConfirmWrongError()

(@prayutsu )
fun testAdminPinActivity_inputPin_inputWrongConfirmPin_clickSubmit_configurationChange_checkConfirmWrongError()

(@prayutsu )
fun testAdminPinActivity_inputPin_inputWrongConfirmPin_clickImeActionButton_configurationChange_checkConfirmWrongError()
```

**Comment by prayutsu** [comment]
@anandwana001 I think they are not only failing on small screen devices, they are failing on all devices on espresso.
![Screenshot from 2021-01-18 15-13-15](https://user-images.githubusercontent.com/54636525/104898554-cb468280-599f-11eb-99a2-9aa22017cd8a.png)

**Comment by prayutsu** [comment]
@FareesHussain I guess they are failing for other similar test files too except one?

**Comment by prayutsu** [comment]
@anandwana001 I tested these test cases after removing data binding code from XML files
And all the test cases passed.
![Screenshot from 2021-01-18 15-33-49](https://user-images.githubusercontent.com/54636525/104900879-a1db2600-59a2-11eb-962b-a85e44b2f239.png)

**Comment by FareesHussain** [comment]
> Need to investigate why this is passing earlier and why this is failing now. 

I guess the added screenshots were before adding the data-binding and we didn't check the espresso tests after that and all of the failing tests are related to disappearing error message after configuration change

so we can solve this using onSavedInstance similar to `AdminAuthActivity`

do this makes sense?

**Comment by prayutsu** [comment]
@FareesHussain Yes, after making changes I didn't run tests on ESPRESSO, I only ran for Robolectric.
But I didn't get your point of using `onSavedInstance()` to solve this issue. Can you please explain?

**Comment by FareesHussain** [comment]
> @FareesHussain Yes, after making changes I didn't run tests on ESPRESSO, I only ran for Robolectric.
> But I didn't get your point of using `onSavedInstance()` to solve this issue. Can you please explain?

Adding Reference - 
https://github.com/anandwana001/oppia-android/blob/462f7fcab7637b0fe1083a254863cf32f528c60b/app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt#L115

**Comment by prayutsu** [comment]
@anandwana001 One test case of `AdminAuthActivityTest` is also failing on ESPRESSO.
I ran it two times, can you check if it is passing on your local machine (on the latest develop)?
![Screenshot from 2021-01-19 16-08-25](https://user-images.githubusercontent.com/54636525/105023330-d61d1800-5a70-11eb-829d-f1f5a8593246.png)

**Comment by prayutsu** [comment]
Also, we need to introduce test cases similar to below mentioned - 
```
testAdminPinActivity_configurationChange_inputPin_inputWrongConfirmPin_clickImeActionButton_checkConfirmWrongError()
testAdminPinActivity_inputPin_inputWrongConfirmPin_clickSubmit_configurationChange_checkConfirmWrongError()
testAdminPinActivity_inputPin_inputWrongConfirmPin_clickImeActionButton_configurationChange_checkConfirmWrongError()
```

**Comment by prayutsu** [comment]
@anandwana001 3 tests in `AdminPinActivityTest` are failing correctly, i.e the actual app isn't behaving as expected - 

https://user-images.githubusercontent.com/54636525/105025408-4af15180-5a73-11eb-9e4e-00ba04e80388.mp4

**Comment by anandwana001** [comment]
@prayutsu Could you file a separate issue for this with the video mentioned above?

**Comment by prayutsu** [comment]
@anandwana001 Aren't we covering it in this issue only?

**Comment by anandwana001** [comment]
ah, Let's update the issue description. Also, Farees is handling the admin auth thing too in the current PR.

**Comment by prayutsu** [comment]
Yup, so should I make a PR for `AdminPinActivityTest`?

**Comment by anandwana001** [comment]
> Yup, so should I make a PR for `AdminPinActivityTest`?

@FareesHussain are you working on this? else you can assign to Abhay.

**Comment by FareesHussain** [comment]
> > Yup, so should I make a PR for `AdminPinActivityTest`?
> 
> @FareesHussain are you working on this? else you can assign to Abhay. 

It's fine then I'll leave `AdminPinActivity` and make changes for all other activities

**Comment by rt4914** [comment]
Looks like this entire issue has been solved. @anandwana001 @prayutsu @FareesHussain Can you please confirm and close this issue if needed. Thanks.

**Comment by anandwana001** [comment]
Yes, Thanks for merging. Closing this issue.
