### ISSUE TITLE
Nit code change in HomeActivityTest.kt

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2504]
`HomeActivityTest.kt` needs to be updated as per this comment 
https://github.com/oppia/oppia-android/pull/2246#discussion_r559335629

**Comment by yurilev** [comment]
Can I work on this issue?

**Comment by FareesHussain** [comment]
@yurilev Thanks for showing interest in oppia. Please check out our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by yurilev** [comment]
Hi Farees, I already did all that.

**Comment by yurilev** [comment]
Which tablet image is recommended when running Espresso tests in an emulator?

**Comment by yurilev** [comment]
The nit was for `testHomeActivity_allTopicsCompleted_displaysAllTopicCards()`, which appears to be broken on tablets, expecting the wrong number of columns. Similar tests in the same file have 4 versions, for mobile/tablet and portrait/landscape.

May I fix the test and make related improvements as part of this, or should I file a separate issue?

**Comment by yurilev** [comment]
> The nit was for `testHomeActivity_allTopicsCompleted_displaysAllTopicCards()`, which appears to be broken on tablets, expecting the wrong number of columns. Similar tests in the same file have 4 versions, for mobile/tablet and portrait/landscape.
> 
> May I fix the test and make related improvements as part of this, or should I file a separate issue?

Filed #2587.
