### ISSUE TITLE
Update literals to named arguments in TopicLessonsFragmentTest.kt

### ISSUE THREAD

**Issue by srikanthkb** [oppia/oppia-android#2515]
**Is your feature request related to a problem? Please describe.**
Update the literals passed as argument to named arguments. This improves code readability and provides better context to the readers. One such instance is shown as an example below.

**Describe the solution you'd like**
Update the argument in line 246 below:
https://github.com/oppia/oppia-android/blob/bb7351b4c0700b3dadd1a51edd99e8e51c696eb4/app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt#L244-L248

to the following code:
```        
        atPositionOnView(
          R.id.story_summary_recycler_view,
          position = 1,
          R.id.chapter_recycler_view
        )
```

**Additional context**
1. Identify other instances of such changes in `TopicLessonsFragmentTest`, update the code with named arguments. 
2. Identify other files/classes where such changes, update with named arguments for better readability.

**Comment by harshpatel63** [comment]
I'll like to work on it. Can you assign me this issue??

**Comment by srikanthkb** [comment]
@Sci3fic Have you completed the onboarding procedures from here? https://github.com/oppia/oppia-android/wiki 
Let us know if all of the procedures and setup is complete.

**Comment by harshpatel63** [comment]
> @Sci3fic Have you completed the onboarding procedures from here? https://github.com/oppia/oppia-android/wiki
> Let us know if all of the procedures and setup is complete.

Done with the procedures and setup.

Just for clarification: I need to check each and every Kotlin file for the issue. Right??

**Comment by srikanthkb** [comment]
Yes. Currently, we have few pre-push git hooks, which warns you if there are any linting errors before you push it to your branch. If you see any errors/warnings, the push will fail, and you will be asked to fix the errors.

**Comment by anandwana001** [comment]
I suggest creating multiple sub issues for this. Tracking in one issue might be complex.

**Comment by srikanthkb** [comment]
> I suggest creating multiple sub issues for this. Tracking in one issue might be complex.

Agreed. On what basis should we split these into sub issues or should we create independent good-first-issues for the identified files ?

**Comment by anandwana001** [comment]
we can create package wise. Are we including test files too? and what all modules we are covering in this?

**Comment by srikanthkb** [comment]
I thought this would be a good first issue, for all of the Tests (Ex: `TopicLessonsFragmentTest`,`AdministratorControlsActivity `etc) in `app` module, **specifically** related to `RecyclerView` as it would contain the argument `position` in the `scrollToPosition` method.
But if you think, we should pursue this for the entire codebase, then maybe creating independent issues for different modules will make it easier to track the changes. What do you think ?

**Comment by anandwana001** [comment]
yes, let's create issues package vice.

**Comment by srikanthkb** [comment]
> yes, let's create issues package vice.

Renamed this issue specifically for `TopicLessonsFragmentTest`. I will create new issues for tracking changes at the package level.
