### ISSUE TITLE
Fractions topic, exploration 1: correct answer not recognized

### ISSUE THREAD

**Issue by jcqli** [oppia/oppia-android#2526]
**Describe the bug**
In the Fractions topic, story 1, chapter 1, the correct answer is not recognized as the correct answer (see image below).
The [JSON file](https://github.com/oppia/oppia-android/blob/develop/domain/src/main/assets/umPkwp0L1M0-.json#L6521) records the chosen options as the correct answer.
This is thought to be caused by #2459 where the JSON file was updated but the classifier input was not updated to match the changes to the answer string.

**To Reproduce**
1. Go to the "Fractions" topic
2. Click on "Lessons" tab
3. Click on the first exploration "What is a Fraction?"
4. Play through until the question "Which of the fractions shown have a denominator of 3? There might be more than one."
5. Click on the first and third answer choices.

**Expected behavior**
Correct answer should be submitted and the "Correct!" banner should display.

**Screenshots**
![Screenshot_1611182924](https://user-images.githubusercontent.com/40325757/105251943-51de9980-5b31-11eb-8e99-22463c29130d.png)

**Device**
- Pixel 3a emulator

**Comment by rt4914** [comment]
Reopened now.

**Comment by rt4914** [comment]
Actually reopened by confusion. Closing this again.
