### ISSUE TITLE
Check and fix Profile Name across all screens

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2529]
Profile Name is shown in below mentioned screens and we should make sure that a name with maximum characters is clearly visible.
- Profile Chooser Screen
- Navigation Drawer Header
- Home Screen Salutaion
- Profile Progress
- Profile List (in Admin Controls)
- Profile View (in Admin Controls)

These needs to be tested and fixed on mobile-landscape, mobile-portrait, tablet-landscape and  tablet-portrait.

**Comment by khushal1707** [comment]
I like to work on this issue, but in most of the screens name with max character length is correctly visible. The only place where I encounter problem is Profile View (in Admin Controls) with mobile-portrait, correct me if I'm wrong.

**Comment by rt4914** [comment]
> I like to work on this issue, but in most of the screens name with max character length is correctly visible. The only place where I encounter problem is Profile View (in Admin Controls) with mobile-portrait, correct me if I'm wrong.

You might be correct. Once you PR is out I will check this on all screens and see if we can improve further. Thanks.
