### ISSUE TITLE
Double line issue in Profile Chooser in Tablets.

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2530]
<img src="https://user-images.githubusercontent.com/72242656/105118143-af67dd00-5a82-11eb-8107-65fd7dc3d8e2.png" width=250 /> 
<img src="https://user-images.githubusercontent.com/72242656/105118138-aecf4680-5a82-11eb-9657-677750af28aa.png" width=250 />

**Comment by Mehul-Bisht** [comment]
@rt4914 I have found the cause of this issue. May I send a Pull Request for the fix or are you working on it?

**Comment by rt4914** [comment]
@Mehul-Bisht Assigned you
