### ISSUE TITLE
Introduce a central utility for matching item in RecyclerView [Testing]

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2536]
**Is your feature request related to a problem? Please describe.**
While writing test cases in the app module for testing, if the item matches the RecyclerView's item, we use `atPositionOnView` heavily. 

**Describe the solution you'd like**
Create a central utility which we can directly use in our test files. 
As for this issue, after creating this central utility, use it in the `AdministratorControlsActivityTest` only. 

**Additional context**
In some of the file, we had created helper functions,
example -  `verifyItemDisplayedOnAdministratorControlListItem` in `AdministratorControlsActivityTest`

**Comment by ayan-biswas0412** [comment]
@anandwana001 Can you elaborate more ? I want to work in this issue . this seems interesting but don't know how to proceed

**Comment by anandwana001** [comment]
Thanks @ayan-biswas0412 for showing interest. 
Please complete the onboarding and installation steps before starting
https://github.com/oppia/oppia-android/wiki

If you see test files in the app Module, one file referenced in the description above, we use to test alot about if the item is visible on the particular index in RecyclerView. So instead of writing this multiple times, we need a new file, a central utility, something like EditTextInputAction, where we can put our main function of checking items in RecyclerView, and just use it wherever required.

**Comment by ayan-biswas0412** [comment]
> Thanks @ayan-biswas0412 for showing interest.
> Please complete the onboarding and installation steps before starting
> https://github.com/oppia/oppia-android/wiki
> 
> If you see test files in the app Module, one file referenced in the description above, we use to test alot about if the item is visible on the particular index in RecyclerView. So instead of writing this multiple times, we need a new file, a central utility, something like EditTextInputAction, where we can put our main function of checking items in RecyclerView, and just use it wherever required.

sure I will complete the onboarding first

**Comment by Sparsh1212** [comment]
I would love to work on this. @anandwana001 Shall I assign this to myself ?

**Comment by Sparsh1212** [comment]
@anandwana001 As per what I have understood, I am required to shift this helper function to a new file and make it generic to use the `id` of any RecyclerView. If I have misinterpreted, then please correct me.

Helper Function in `AdministratorControlsActivityTest`
```kotlin
  private fun verifyItemDisplayedOnAdministratorControlListItem(
    itemPosition: Int,
    targetView: Int
  ) {
    onView(
      atPositionOnView(
        recyclerViewId = R.id.administrator_controls_list,
        position = itemPosition,
        targetViewId = targetView
      )
    ).check(matches(isDisplayed()))
  }
```

Generalize this to: in a new central utility file

```kotlin
  private fun verifyItemDisplayedOnRecyclerView(
    recyclerView: Int,
    itemPosition: Int,
    targetView: Int
  ) {
    onView(
      atPositionOnView(
        recyclerViewId = recyclerView,
        position = itemPosition,
        targetViewId = targetView
      )
    ).check(matches(isDisplayed()))
  }
```

**Comment by Sparsh1212** [comment]
@anandwana001 Please confirm this.

**Comment by anandwana001** [comment]
Sounds good to me @Sparsh1212

**Comment by Sparsh1212** [comment]
@anandwana001 I am facing problem while importing `atPositionOnView` when shifting the function to the central utility.

`import org.oppia.android.app.recyclerview.RecyclerViewMatcher.Companion.atPositionOnView`

And I think its not a gradle sync issue, do we have to add any dependency in the `build.gradle` and `BUILD.bazel` files of the `testing` module in order to use `atPositionOnView`? Please guide me on this.

**Comment by anandwana001** [comment]
Yes, as testing is a new module so you have to check if the required dependency is already there or not, if not we have to add it.

**Comment by deonwaju** [comment]
Hi @adhiamboperes,
I worked on the below functions renaming the title and adding an argument for the recyclerviewId to each function to make it reusable, I also added kdocs to help understand the functions.
P.S:- I created the functions in the RecyclerviewMatcher class.
 
Please check the below screenshots if they align with the specifications so I can go ahead and continue with other functions and then make a PR. 

**Before**
![Screenshot 2024-04-10 at 14 07 44](https://github.com/oppia/oppia-android/assets/54560535/bf8146ca-dd7b-478d-9363-76a29bfd4634)

![Screenshot 2024-04-10 at 14 07 51](https://github.com/oppia/oppia-android/assets/54560535/3fa8a779-80e4-43fc-a695-f73bb3f55a3f)

**After**
![Screenshot 2024-04-10 at 13 17 38](https://github.com/oppia/oppia-android/assets/54560535/a86dc452-6d16-40ba-95d7-f3a0b948c622)

![Screenshot 2024-04-10 at 13 18 00](https://github.com/oppia/oppia-android/assets/54560535/53743130-8abc-403d-b571-b277fcd13005)

![Screenshot 2024-04-10 at 13 17 53](https://github.com/oppia/oppia-android/assets/54560535/cdb4ecdb-615a-4f43-9923-10ec15511cdc)

**Comment by deonwaju** [comment]
Hello @adhiamboperes
