### ISSUE TITLE
Include Java requirement in onboarding instructions

### ISSUE THREAD

**Issue by Russ741** [oppia/oppia-android#2539]
**Describe the bug**
kotlin-lint-check.sh requires Java (specifically, the java executable) to be on the user's path, and fails if it is not. This failure occurs for Windows-based developers, as the JRE may only be present as part of the Android Studio installation, with no corresponding PATH entry.

I believe other tools may have the same requirement, though I don't remember which offhand.

**Expected behavior**
It would be good to include a step in https://github.com/oppia/oppia-android/wiki#installation to check if the java executable is on the path, and a recommendation as to what type/version of Java to install and configure.

**Comment by anandwana001** [comment]
@Russ741 We had added a possible error which can occur to a contributor and a brief solution.
`If you find any error which says java: command not found, please check you have Java installed correctly in your machine and environment path variable is also set up.`
Do we need to add more on this?

**Comment by Russ741** [comment]
Ah, looks like you have it covered already. Optional: is there a recommended Java to install (JRE/JDK, version, Open/Oracle, etc.)? If so, saying what it is would be good.

**Comment by anandwana001** [comment]
@Russ741 Added point 3
https://github.com/oppia/oppia-android/wiki#installation

Let me know if it helps or needs any more description.

**Comment by BenHenning** [comment]
@anandwana001 are those Java instructions correct for Linux, too?

**Comment by anandwana001** [comment]
Yes, I think, 
There are only two steps:
1. Java must be installed
2. If a contributor is on Windows they need to set environment path too. 

And good to go. 

@FareesHussain Could you please confirm if you performed any extra steps to set up Java on Linux?

**Comment by FareesHussain** [comment]
@anandwana001 No, I just installed the android studio and cloned the project as soon as I setup linux and it was working.
I had no issues with Java.

**Comment by anandwana001** [comment]
We haven't seen a Java issue so far from the contributors, so I guess we can close this issue. I will keep an eye on any issues over installations.
