### ISSUE TITLE
Wrong answers not showing in a Prototype exploration

### ISSUE THREAD

**Issue by chrk2205** [oppia/oppia-android#2541]
**Describe the bug**
In Prototype exploration when a wrong input is given for a question it is supposed show that the input is wrong.
but instead submit button is getting disabled.
**To Reproduce**
1. Go to 'Prototype Exploration' and to the Question 11*11
2. Click on answer and type a random input and click submit.
3. See error

**Expected behavior**
instead of of submit button getting disabled the input should show up as a wrong answer.

https://user-images.githubusercontent.com/44704035/105478091-ba13b380-5cc8-11eb-9bf3-b1ec8bf85cd6.mp4

**Device**
- OnePlus 6

**Comment by FareesHussain** [comment]
@chrk2205 This has been fixed can you please update your branch and re-check if it still exists
I'm unable to reproduce this anymore

**Comment by chrk2205** [comment]
@FareesHussain 
yeah sorry its fixed
