### ISSUE TITLE
Stop confetti when going back from the end of exploration screen

### ISSUE THREAD

**Issue by jcqli** [oppia/oppia-android#2545]
**Describe the bug**
When we reach the end of exploration and then navigate back a screen, the confetti still falls instead of stopping.

**To Reproduce**
1. Complete an exploration to the end
2. When the confetti appears, click back to the previous screen
3. Confetti will continue to fall after leaving the end of exploration screen

**Expected behavior**
Confetti should stop when navigating away from the last screen of the exploration

**Screenshots**
![end confetti back and forth](https://user-images.githubusercontent.com/40325757/105524964-3c828000-5c95-11eb-8eff-433c9c296976.gif)

**Device**
- Pixel 3a emulator

**Comment by chrk2205** [comment]
i would like to work on this.
@jcqli

**Comment by jcqli** [comment]
> i would like to work on this.
> @jcqli

Hi @chrk2205, sorry for the confusion but this is actually a part of my project that I will be fixing -- just added myself (accidentally removed you as well, but I hope this makes sense!)
