### ISSUE TITLE
Rename OngoingStory to PromotedStory

### ISSUE THREAD

**Issue by jcqli** [oppia/oppia-android#2546]
Since changing promoted stories to include recently played stories, older played stories, and suggest stories, we want to rename instances of `OngoingStory` to be called `PromotedStory` as per [this review](https://github.com/oppia/oppia-android/pull/2320#pullrequestreview-574479490).

In `RecentlyPlayedFragmentPresenter`:
- `ongoingStoryListSummaryResultLiveData` => `promotedStoryListSummaryResultLiveData`
- `fun subscribeToOngoingStoryList` => `fun subscribeToPromotedStoryList`
In `OngoingStoryViewModel`:
- class name `OngoingStoryViewModel` => `PromotedStoryViewModel` (and also it's usages elsewhere)

**Comment by priyanka0906** [comment]
May I work  on this?

**Comment by jcqli** [comment]
As a note, when it comes time I'd recommend waiting until after #2320 is merged to merge this since this follows-up on some changes from that earlier PR.

**Comment by priyanka0906** [comment]
@jcqli  Okay.

**Comment by priyanka0906** [comment]
> As a note, when it comes time I'd recommend waiting until after #2320 is merged to merge this since this follows-up on some changes from that earlier PR.

Okay.

**Comment by priyanka0906** [comment]
@FareesHussain  @jcqli  Till then can I look for any other issue?

**Comment by FareesHussain** [comment]
Sure

**Comment by FareesHussain** [comment]
@jcqli please update the title as `[blocked on #2320]`

**Comment by veena14cs** [comment]
@priyanka0906 since #2320 is merged, this is unblocked and you can work on this.

**Comment by priyanka0906** [comment]
> @priyanka0906 since #2320 is merged, this is unblocked and you can work on this.

@jcqli  all instances of ongoingStory has to be changed in promotedStory like ongoingStoryClickListener and ongoingListAdapter?

**Comment by jcqli** [comment]
> @jcqli all instances of ongoingStory has to be changed in promotedStory like ongoingStoryClickListener and ongoingListAdapter?

Yes, for clarity and consistency that would be best.

**Comment by priyanka0906** [comment]
> > @jcqli all instances of ongoingStory has to be changed in promotedStory like ongoingStoryClickListener and ongoingListAdapter?
> 
> Yes, for clarity and consistency that would be best.

okay. Thankyou

**Comment by Rohit1173** [comment]
May I work on this

**Comment by prayutsu** [comment]
@Rohit1173 Assigning this to you.

**Comment by Akshatkamboj14** [comment]
can you assign me this issue?

**Comment by Akshatkamboj14** [comment]
@rishidyno

**Comment by pandayed** [comment]
Can you please assign this to me? Thanks.

**Comment by rishidyno** [comment]
Assigned this to @xpandeyed.

**Comment by rt4914** [comment]
Removing it from good-first-issue because it actually requires a lot of context about the project to rename things correctly.
