### ISSUE TITLE
Parameters in the comments doesn't match with the actual parameters

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2562]
The parameters mentioned in the comments don't match with the actual parameters in `StoryProgressTestHelper`

For example here the comment(timestampOlderThanOneWeek) doesn't match with the actual parameter(timestampOlderThanAWeek)
https://github.com/oppia/oppia-android/blob/9bc61d89c950dde5cf0b5be0b6232dc16e2c6357/domain/src/main/java/org/oppia/android/domain/topic/StoryProgressTestHelper.kt#L23-L29

**Comment by OBITORASU** [comment]
Can I pick this up? Willing to fix all the comments so that they match the parameters actually being passed.

**Comment by FareesHussain** [comment]
> Can I pick this up? Willing to fix all the comments so that they match the parameters actually being passed.

@OBITORASU  Thanks for showing interest in oppia. Please check out our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by OBITORASU** [comment]
I have filled up the survey as best as I could and the CLA.
