### ISSUE TITLE
Fix layout margins in exploration player's state fragment

### ISSUE THREAD

**Issue by jcqli** [oppia/oppia-android#2564]
**Describe the bug**
The exploration player containers are not reflective of the desired UIs as shown in the [mock](https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/1ec6f401-6d2e-4c47-b8aa-31517818be9a/specs/)
We need to adjust the tablet landscape layouts for these containers so that they are properly staggered as shown.

**To Reproduce**
1. Start any exploration
2. The question text container is aligned towards the right and the answer options are center

**Expected behavior**
The question text container should have a right margin slightly larger than its left margin, and the answer options should have a right margin smaller than the left margin so that it is visibly staggered

**Screenshots**
![Screenshot_1611703585](https://user-images.githubusercontent.com/40325757/105920202-cdd25900-5feb-11eb-82f9-2db92a1208c5.png)

**Device**
- Pixel C Emulator

**Additional context**
Follow the margin values laid out in mocks.
The question text can likely be adjusted using the `content_item` [layout](https://github.com/oppia/oppia-android/blob/ac29306265c5438838cd0b837f73e240db6ea38f/app/src/main/res/layout-sw600dp-land/content_item.xml) but each interaction item's layout may need to updated individually for the different types of answer interactions (e.g. `selection_interaction_item`, `ratio_input_interaction_item`, etc.)

**Comment by kartikeysaran** [comment]
I am working on this issue

**Comment by rt4914** [comment]
@kartikeysaran Please don't work on this. I was currently working on some other issue and coincidently it got fixed in my PR so I am assigning it to myself.

**Comment by rt4914** [comment]
@kartikeysaran For you reference: https://github.com/oppia/oppia-android/pull/2608#discussion_r569493500

**Comment by kartikeysaran** [comment]
@rt4914 Okay , I will work on some other issue
