### ISSUE TITLE
Fix test testAudioFragment_withHindiAudioLanguageProfile_showsHindiAudioLanguage [Testing]

### ISSUE THREAD

**Issue by MaskedCarrot** [oppia/oppia-android#2568]
**Describe the bug**
The test `testAudioFragment_withHindiAudioLanguageProfile_showsHindiAudioLanguage` passes on espresso but fails on robolectric
This test is present in `AudioFragmentTest` app module.

**Expected behavior**
The test should pass on both espresso and robolectric.

**Comment by soamOne** [comment]
Hey @MaskedCarrot can I work on this?

**Comment by MaskedCarrot** [comment]
@soamOne assigning this to you

**Comment by rt4914** [comment]
Thanks @soamOne and @MaskedCarrot

**Comment by anandwana001** [comment]
@soamOne any update on this?

**Comment by Vishwajith-Shettigar** [comment]
`testAudioFragment_withHindiAudioLanguageProfile_showsHindiAudioLanguage` test doesn't exists in `AudioFragmentTest`.
@adhiamboperes,This issue can be closed.

**Comment by adhiamboperes** [comment]
Thanks @Vishwajith-Shettigar. I confirmed that we don't have this test anywhere.
