### ISSUE TITLE
Fix typos and errors for the following files

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2570]
1. In KeyboardHelper - there is a typo in `softinputkeybord` (3 changes)
     https://github.com/oppia/oppia-android/blob/74db288b9ac25fb942a8feb35e918bcd7e94e55c/app/src/main/java/org/oppia/android/app/utility/KeyboardHelper.kt#L7
2. In StartSnapHelper - 'Throws' is not imported (1 change)
    https://github.com/oppia/oppia-android/blob/5fc69fffb97e0c8a0d529238926f3e078cf88b09/app/src/main/java/org/oppia/android/app/recyclerview/StartSnapHelper.kt#L18
3. In StateAssemblerMarginBindingAdapters - typo in `split-veiw` (1 change)
     https://github.com/oppia/oppia-android/blob/5fc69fffb97e0c8a0d529238926f3e078cf88b09/app/src/main/java/org/oppia/android/app/databinding/StateAssemblerMarginBindingAdapters.java#L9

**Comment by riturajjain2000** [comment]
Can I work on this?

**Comment by sawantvikram** [comment]
I want to work on this issue.. is this still available???

**Comment by FareesHussain** [comment]
@sawantvikram Thanks for showing interest in oppia. Please check out our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

This issue is assigned to @riturajjain2000 . You can pick other issue from [here](https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22good+first+issue%22)
