### ISSUE TITLE
Create a BUILD file for viewmodel/

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#2585]
This task is part of the build system migration from Gradle to Bazel. A prerequesite before working on this issue is that you are able to build Oppia using Bazel. Check out [Oppia Bazel guide](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Guide) for Bazel terminology and more of what it does.

Create a BUILD.bazel file in 

`app\src\main\java\org\oppia\android\app\viewmodel`

This package does not depend on any other packages inside of Oppia itself. Create a target for each file in the package, if possible, and add the dependency artifacts that are required based on the imports in the file.

Here's a non-exhaustive list of potential candidates that should be used as dependencies for the targets.
```
        artifact("androidx.appcompat:appcompat"),
        artifact("androidx.databinding:databinding-adapters"),
        artifact("androidx.databinding:databinding-common"),
        artifact("androidx.databinding:databinding-runtime"),
        artifact("androidx.lifecycle:lifecycle-extensions:2.2.0"),
        artifact("androidx.lifecycle:lifecycle-livedata-core:2.2.0"),
        artifact("androidx.lifecycle:lifecycle-livedata-ktx:2.2.0"),
        artifact("javax.annotation:javax.annotation-api:jar"),
```
## Create the targets

Because ObservableArrayList.kt does not depend on any of the other files in the package, we can create a target containing only that file. In our BUILD.bazel file we would have

```BUILD
load("@rules_jvm_external//:defs.bzl", "artifact")
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")

kt_android_library(
    name = "observable_array_list",
    srcs = [
        "ObservableArrayList.kt",
        ],
    deps = [
        artifact("androidx.databinding:databinding-adapters"),
        ],
    )
```

We added the deps dependency `artifact("androidx.databinding:databinding-adapters")` since the file contains two imports that are provided by the artifact.

Add the rest of the targets and add the deps dependencies accordingly by matching the imports. There will be a intrapackage dependency in addition to the artifacts

## Confirm that the package builds

When you've added the targets, confirm that you can build the package by using Bazel to build the targets. If you're in the viewmodel directory in your terminal, run

`bazel build :all` 

to build all your targets.

## Remove srcs dependencies from the module BUILD file

In the app BUILD.bazel file, remove 

```
    "src/main/java/org/oppia/android/app/viewmodel/ObservableArrayList.kt",
    "src/main/java/org/oppia/android/app/viewmodel/ObservableViewModel.kt",
```

from the view_models variable and add your newly targets to the `view_models` kt_android_library target.

## Confirm that the app builds

Now you can confirm that the package works by building the app successfuly.

**Comment by fsharpasharp** [comment]
@BenHenning can you take a look and see if this is a good starting point?

**Comment by BenHenning** [comment]
Some thoughts:
- List an example BUILD file that looks more or less like what we want to introduce here
- Example needs to show what "create a target for each file" means in practice
- I think more information is needed on how to find the dependency artifacts that are required (e.g. map imports to WORKSPACE maven dependencies?). Also, consider how to tie back to non-Maven dependencies. Maybe an add-on to the wiki on how to generally manage dependencies.
- Needs more detail on how to build the package to check it.
- Title seems a bit off: this isn't blocked on anything
- How do you want the final structure to be? Is it just 1 android_library with all of the dependencies, or is it split up in some other way? Suggest being specific here since this will be especially important both for utility packages & for large packages in the future
- Maybe link a FAQ that you can keep up-to-date as people run into issues

Otherwise, can confirm that /app/viewmodel seems like a leaf node per the build graph.

**Comment by FareesHussain** [comment]
@fsharpasharp can I work on this? I've created the Bazel environment and I'm able to build and install the Oppia app using Bazel

**Comment by fsharpasharp** [comment]
Of course, let me know if you run into any problems. Any feedback will be helpful for creating future issues as well.

**Comment by FareesHussain** [comment]
Thanks @fsharpasharp I have few doubts regarding this issue
the artifacts i need to add are the dependencies from which the imports are derived in a viewmodel right?

**Comment by fsharpasharp** [comment]
@FareesHussain. To clarify, we're going to add a BUILD file in

`app\src\main\java\org\oppia\android\app\viewmodel`

You'll have to look at the imports of a file to decide which `artifact("...")` dependencies you need to have for the target in question. You'll know if you have all of them when the target builds and finds all the imports they require.

**Comment by FareesHussain** [comment]
Thanks, @fsharpasharp I've created a PR #2648 I'm not sure how to add the kt_android_libraries for each file and I don't know how it works Please have a look

https://github.com/oppia/oppia-android/pull/2648#issuecomment-774548755
