### ISSUE TITLE
Open Navigation Drawer from Exploration

### ISSUE THREAD

**Issue by chrk2205** [oppia/oppia-android#2592]
**Describe the bug**

**To Reproduce**
1. Go to 'exploration'
2. Click on 'option button' in top right of screen
3. Select 'Options' or 'Help'
4. Slide on screen to right ( so you can open Navigation Drawer)

**Expected behavior**
Navigation Drawer should not be operated from Exploration Activity because on Opening Navigation Drawer we can go to Home and which leads to the app-crash
**Screenshots**
https://user-images.githubusercontent.com/44704035/106388962-d8835880-6406-11eb-8008-c47a3a6078b8.mp4

**Comment by chrk2205** [comment]
@rt4914 @BenHenning 
 can you confirm if it's a bug or not??
thanks!!

**Comment by rt4914** [comment]
@chrk2205 Nice catch. I can reproduce this error.

**Comment by chrk2205** [comment]
` activity.findViewById<DrawerLayout>(R.id.options_activity_drawer_layout).setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);`
adding this in the `OptonActivityPresenter`  will  remove the bug
should i write test case for this bug??
@rt4914

**Comment by rt4914** [comment]
> ` activity.findViewById<DrawerLayout>(R.id.options_activity_drawer_layout).setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);`
> adding this in the `OptonActivityPresenter` will remove the bug
> should i write test case for this bug??
> @rt4914

@chrk2205 yes . Bugs should always contain test cases such that if the implementation fails the test case should fail.

**Comment by rt4914** [comment]
Summary:
Two solutions discussed:
Solution 1:
```
activity.findViewById<DrawerLayout>(R.id.options_activity_drawer_layout)     .setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED)
```

Solution 2:
Create separate xml file like `options_without_drawer_activity.xml` and control this file and the original xml from presenter using `isFromNavigationDrawer`.


Need to check which solution is better for A11y. @rt4914

**Comment by rt4914** [comment]
> Summary:
> Two solutions discussed:
> Solution 1:
> 
> ```
> activity.findViewById<DrawerLayout>(R.id.options_activity_drawer_layout)     .setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED)
> ```
> 
> Solution 2:
> Create separate xml file like `options_without_drawer_activity.xml` and control this file and the original xml from presenter using `isFromNavigationDrawer`.
> 
> Need to check which solution is better for A11y. @rt4914

@chrk2205 Let's go with solution 2 as it seems to be more readable and maintainable.

**Comment by chrk2205** [comment]
@rt4914  we should do the same for the help fragment too!!
so totally 3 files for `options_activity` and 2 files for `help_activity` will be added!!
