### ISSUE TITLE
Update Data item list as per the Backend

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2596]
**Describe the bug**
For the `GaeStateClassifier.kt`, the data items are changed in the Backend. 

**Expected behaviour**
Update `GaeStateClassifier` as per the items coming from the Backend. 
Backend - https://github.com/oppia/oppia/blob/develop/core/controllers/reader.py#L239

**Additional context**
Check https://github.com/oppia/oppia/blob/develop/core/domain/state_domain.py#L1461 for the reference of data items in the `data/src/main/java/org/oppia/android/data/backends/gae/model/GaeWrittenTranslation.kt`

**Comment by Akshat-gour** [comment]
can I try it

**Comment by MaskedCarrot** [comment]
@Akshat-gour have you filled the CLA?

**Comment by Akshat-gour** [comment]
yes i did

**Comment by Akshat-gour** [comment]
can I get a help its been difficult to identify which variable to update in GaeStateClassifier.
do ,I have to update All class and function Variable present In Reader.py
**Or Just these Classes Variables**
class StatsEventsHandler
class StateHitEventHandler
class StateCompleteEventHandler
@FareesHussain 
@anandwana001

**Comment by MaskedCarrot** [comment]
@Akshat-gour what I understand is you have to change the JSON fields in `GaeStateClassifier` as they have changed in the backend(`Reader.py`) 
@anandwana001 PTAL

**Comment by MaskedCarrot** [comment]
@Akshat-gour what I understand is you have to change the JSON fields in `GaeStateClassifier` as they have changed in the backend(`Reader.py`)

**Comment by BenHenning** [comment]
@anandwana001 we shouldn't be working on GAE layer issues since we're not confident that we're keeping the GAE interop layer, or what we specifically need to download. I also don't think any of it's hooked up right now, so there's no way to debug it.

**Comment by BenHenning** [comment]
@Akshat-gour sorry for the noise--can you maybe find another starter issue to work on?
