### ISSUE TITLE
Full UI: ContentCardView [Blocked: #161]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#26]
In various locations, content cards will need to be displayed with rich-text. Android TextViews support rendering a subset HTML, though the default rich-text provided by the Oppia backend may need to be processed before simply being passed to the TextView. See the web rich-text component for specifics.

Mock: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/40d6cf5f-f673-42c8-af15-035f711ef6b9/PM-IN-Introduction-

## Checklist

- [ ] ContentCard (Left side)
<img width="327" alt="Screenshot 2019-11-08 at 3 50 19 PM" src="https://user-images.githubusercontent.com/9396084/68469848-ff250480-0240-11ea-82aa-818300668169.png">

- [ ] Learner Answer (Right side)
<img width="101" alt="Screenshot 2019-11-08 at 4 00 25 PM" src="https://user-images.githubusercontent.com/9396084/68469854-01875e80-0241-11ea-9a78-f8a7bef302dd.png">

- [ ] Final touch up with padding, margin, animations and Accessibility Scanner test

**Comment by BenHenning** [comment]
This is blocked by #15 to retrieve exploration content data, but it can be designed & mostly built as soon as #4 is completed.

**Comment by BenHenning** [comment]
To simplify, this only needs to support basic HTML elements (li/b/etc.) + images.

**Comment by seanlip** [comment]
Note: links as well. (This includes links to other lessons within the app.)

**Comment by rt4914** [comment]
@veena14cs @nikitamarysolomanpvt Check the comments here.

**Comment by BenHenning** [comment]
After talking with @veena14cs over chat today, one consideration for implementation is: https://stackoverflow.com/a/36528149/3689782.

**Comment by BenHenning** [comment]
This is blocked on #161 for the card's initial structural implementation. Although no data controllers block this work, it should be fully tested with real Oppia HTML examples to avoid complicating downstream work items.

**Comment by veena14cs** [comment]
This is been fixed in PR #338 .
