### ISSUE TITLE
Use string from strings.xml file in MyDownloadFragmentTest

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2602]
Below mentioned line of code is using hard-coded string instead this string should be referenced from `strings.xml` file

https://github.com/oppia/oppia-android/blob/ffacea694d5876ed0dd3fae12d57ef68f3e3efb7/app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsFragmentTest.kt#L88

**Comment by FareesHussain** [comment]
@kartikeysaran before creating a PR please drop a comment on the issue ("I am working on this").

**Comment by kartikeysaran** [comment]
From next time I will make sure that I do comment before working on an issue , Thankyou !
