### ISSUE TITLE
[A11y] Profile Chooser First Time Flow

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2614]
## Current Output

https://user-images.githubusercontent.com/9396084/106887527-48495a00-670b-11eb-8727-6b3b37917e29.mp4

## Issues Identified
- [ ] Talkback does not read the "Profile Image". Mark it as **not** importantForAccessibility.
- [ ] Talkback does not read the "+" image. Mark it as **not** importantForAccessibility.
- [ ] Mark Settings icon as **not** importantForAccessibility.

All these issues can be solved in one single PR.

These issues are same for mobile-landscape, mobile-portrait, tablet-landscape and tablet-portrait.

Note: To understand the above issue(s) completely, it is recommended that you setup Talkback and play with the app keeping it on and that will give you better context.

**Accessibility Guide**: https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide

**Comment by mschanteltc** [comment]
Correct, talkback does not need to read the "Profile Image" or the "+" image but information regarding the user's profile or the action would be [redundant](https://webaim.org/techniques/alttext/). So, no description here is needed.

**Comment by rt4914** [comment]
Updated the overall issue.

**Comment by som23ya** [comment]
@rt4914 can i work on this?

**Comment by rt4914** [comment]
Unassigned @som23ya because of inactivity.
