### ISSUE TITLE
[A11y] Admin Add Pin Screen

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2615]
## Current Output

https://user-images.githubusercontent.com/9396084/106889293-cf97cd00-670d-11eb-96ba-9834145cc169.mp4

https://user-images.githubusercontent.com/9396084/106889297-d1fa2700-670d-11eb-8ad5-a28f9801d2cb.mp4

## Issues Identified
- [x] There are two texts at top and learner requires two separate actions to output both. Confirmed: Current implementation is already correct.
- [x] There are two cases where pins do not match (a.) both are equal length but mismatch (b.) both are of unequal length. Confirmed: Current implementation is already correct.
- [ ] Inconsistency in output of **Close** button
In case of **Admin Add Pin** screen the close button outputs "Navigate Up, Button" and in **Admin Auth Pin** screen the output is "Close, Button". Use **Close, Button** at both places.
- [x] Inactive submit button outputs "SUBMIT, Button" instead it should output "SUBMIT, Button, disabled" (finished in #2626 )

These issues are same for mobile-landscape, mobile-portrait, tablet-landscape and tablet-portrait.

Note: To understand the above issue(s) completely, it is recommended that you setup Talkback and play with the app keeping it on and that will give you better context.

**Accessibility Guide**: https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide

**Comment by mschanteltc** [comment]
- Both texts should be separate. It's best to keep them in small chunks so the user can easily navigate between blocks of text.
- Error should be the same in both cases.
- Use "Close, Button"

**Comment by rt4914** [comment]
Thanks @mschanteltc . Updated overall issue.

**Comment by som23ya** [comment]
@rt4914 can i work on this?

**Comment by nskirkey** [comment]
@rt4914 I would like to work on this if som23ya ends up working on one of the other issues he asked to work on.

**Comment by rt4914** [comment]
@som23ya Assigned you two other PRs. Assigning this one to @nskirkey

**Comment by rt4914** [comment]
Any updates on this @nskirkey  ?

**Comment by nskirkey** [comment]
Yes. Just got it. I'll start making a PR.
