### ISSUE TITLE
[A11y] Admin Auth Screen

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2616]
## Current Output
https://user-images.githubusercontent.com/9396084/106889301-d4f51780-670d-11eb-90f7-7d0968c6e9d9.mp4

## Issues Identified
- [x] Inconsistency in output of **Close** button
In case of **Admin Add Pin** screen the close button outputs "Navigate Up, Button" and in **Admin Auth Pin** screen the output is "Close, Button". Use "Close, Button" for both cases. (Assigned to @Sparsh1212)
- [x] Inactive submit button outputs "SUBMIT, Button" instead it should output "SUBMIT, Button, disabled" (Assigned to @ARJUPTA )

These issues are same for mobile-landscape, mobile-portrait, tablet-landscape and tablet-portrait.

Note: To understand the above issue(s) completely, it is recommended that you setup Talkback and play with the app keeping it on and that will give you better context.

**Accessibility Guide**: https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide

**Comment by mschanteltc** [comment]
- Both texts should be separate. Heading and description serve different purposes, thus it would be better to have them to have their own output.
- Use "Close, Button"

**Comment by Sparsh1212** [comment]
@mschanteltc  I would like to work on this issue. Please assign this to me if it is up for grab.

**Comment by rt4914** [comment]
> @mschanteltc I would like to work on this issue. Please assign this to me if it is up for grab.

@Sparsh1212 

Yes but suggest you checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

Once this is done. Comment again so that I can assign you this issue. Thanks.

**Comment by Sparsh1212** [comment]
I have signed the CLA, filled the survey form, and have read the wiki too. Please assign this to me.

**Comment by rt4914** [comment]
@Sparsh1212 I have updated the description. I have assigned you only the first part of this issue. Second part will get done by Arjun in his current PRs.

**Comment by rt4914** [comment]
Closing this as both the issues have been solved in parts.
