### ISSUE TITLE
[A11y] Add Profile Flow

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2617]
## Current Output

https://user-images.githubusercontent.com/9396084/106892736-8138fd00-6712-11eb-82c4-236e793136a8.mp4

## Issues Identified
- [x] Profile Image is not labelled. Add `contentDescription` as : `Current profile picture` (Assigned to @yashraj-iitr)
- [x] Edit Image is not labelled. Add `contentDescription` as : `Edit profile picture` (Assigned to @yashraj-iitr)
- [x] ***Required** texts output is "Asterisk Required" which I think does not make sense. Add `contentDescription` as : `Fields marked with an * are required.` (Assigned to @yashraj-iitr)
- [x] Need label for **Info** icon. Add `contentDescription` as : "More information on 3-digit PINs". (Assigned to @yashraj-iitr)
- [ ] Allow Download Access Merge talkback content
Currently talkback reads step by steps for this section: "Allow Download Access", "User is ... PIN.", "not checked, OFF, Switch". This also adds two extra steps for the learner. Instead it can be reduced to single output as per below screenshot.
<img src="https://user-images.githubusercontent.com/9396084/106898165-daf0f580-6719-11eb-9ffe-6d14250ec204.png" width="250" />

Note: To understand the above issue(s) completely, it is recommended that you setup Talkback and play with the app keeping it on and that will give you better context.

**Accessibility Guide**: https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide

**Comment by mschanteltc** [comment]
- Profile picture in the "Profile page" should be labelled "Current profile picture"
- The edit image button should be labeled "Edit profile picture, Button" 
- For the asterisk description, use "Fields marked with an asterisk (*) are required."
- For the info button, use "More information on 3-digit PINs, Button"

**Comment by rt4914** [comment]
Thanks @mschanteltc Updated the overall issue. Note for `Fields marked with an asterisk (*) are required.` I have used `Fields marked with an * are required.` as the talkback with read `*` as `asterisk` and it because easy to localise to other languages too.

**Comment by yashraj-01** [comment]
@mschanteltc if this issue is up for grab then I would love to work on it. Please assign this to me.

**Comment by rt4914** [comment]
@yashraj-iitr

Yes but suggest you checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

Once this is done. Comment again so that I can assign you this issue. Thanks.

**Comment by yashraj-01** [comment]
> @yashraj-iitr
> 
> Yes but suggest you checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.
> 
> Once this is done. Comment again so that I can assign you this issue. Thanks.

I have signed the CLA and also filled the survey form. I have also read the wiki and I am ready to contribute.

**Comment by rt4914** [comment]
@FareesHussain This issue contains a checklist so I will be assigning @yashraj-iitr to only parts of this issue. Also, this will be followed in all A11y related issues so I will take care of assigning them the issues. Thanks.

**Comment by rt4914** [comment]
@yashraj-iitr Please take a look at the issue description, I have assigned you 4 tasks and not all, so suggest finish these four first. You can do that in a single Pr. https://github.com/oppia/oppia-android/issues/2617#issue-801277785

**Comment by FareesHussain** [comment]
> @FareesHussain This issue contains a checklist so I will be assigning @yashraj-iitr to only parts of this issue. Also, this will be followed in all A11y related issues so I will take care of assigning them the issues. Thanks.

Sure thanks
