### ISSUE TITLE
[A11y] Administrator Controls

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2618]
## Current Output

https://user-images.githubusercontent.com/9396084/106899922-f1984c00-671b-11eb-8cbe-43bb2a431709.mp4

## Issues Identified
- [x] Overall structure of items output is incorrect. Need to find the correct way. Expected output format: `Profile Management, 2 of 5` → `Edit Profiles, Double tap to activate`
- [x] Merged Switch Compact Output
Expected Output Format: Download Permissions, 3 of 5 → Download and update only on Wifi; Topics will be download...queued. → checked, Switch → Double tap to toggle -> unchecked

Reference: https://github.com/oppia/oppia-android/issues/2618#issuecomment-784540419

Note: To understand the above issue(s) completely, it is recommended that you setup Talkback and play with the app keeping it on and that will give you better context.

**Accessibility Guide**: https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide

**Comment by mschanteltc** [comment]
Order it as so (each new line represents its own navigation):

- List heading, then number of listing (ex: "General, 1 of 5 items in list")

   - If no toggle switch, then read out item name, then option to navigate (ex: "Edit profiles, double-tap to activate")

   - If toggle switch available, read out item name, description, state (ex: "Automatically update topics; Download topics that have new content available will automatically update.; OFF;")
      - Navigate to switch. Provide option to change (ex: "Double tap to turn [ON/OFF] '[ITEM NAME]'")

So an example flow would be:
General, 1 of 5 items in list → Edit account, double-tap to activate →
Profile Management, 2 of 5 items in list → Edit profiles, double-tap to activate → 
Download Permissions, 3 of 5 items in list → Download and update only on Wifi; Topics will be download...queued; OFF → Double tap to turn ON "Download and update only on Wi-fi" → Automatically update topics; Downloaded topics... update; ON → Double tap to turn OFF "Automatically update topics" → 
App Information, 4 of 5 items in list → ...

Is it possible for the user to circle back to the navbar if they reached the end of the list? For example, can the user navigate from "Log out, double-tap to activate" back to "Navigation Menu Open, Button, Administrator Controls"?

**Comment by rt4914** [comment]
@mschanteltc For `Download Permissions` switch related options I am unable to customise as per the steps you mentioned. Also technically we can do that but we don't want to write any custom code as it should be something which can easily be controlled by any app-reader.

I was able to produce following output. Focus on Download Permissions section only:


https://user-images.githubusercontent.com/9396084/108243303-edd0e480-7173-11eb-8b02-dad7a4489f37.mp4

The output will be as follows:
`Download Permissions, 3 of 5` → `Download and update only on Wifi; Topics will be download...queued.` → `checked, Download and update only on Wifi (**Or any custom description that we want**), Switch` 

This solution and the solution that you suggested both are used by android mobile in general.

**Comment by BenHenning** [comment]
@mschanteltc if we want those extra details for buttons & options, should we maybe include them as explicit labels in the UI so that sighted users also get that context? In general I think the recommended pattern is to try to keep the information presented to sighted & accessible users essentially the same so much as possible. TalkBack is actually designed under this assumption, and we often don't need to take additional measures to support conveying extra information if everything is presented naturally to sighted users (plus, the information is generally useful to both anyway). WDYT?

@rt4914 this might also be a good design principle to incorporate in our in-development accessibility principles.

**Comment by mschanteltc** [comment]
> @mschanteltc if we want those extra details for buttons & options, should we maybe include them as explicit labels in the UI so that sighted users also get that context? In general I think the recommended pattern is to try to keep the information presented to sighted & accessible users essentially the same so much as possible. TalkBack is actually designed under this assumption, and we often don't need to take additional measures to support conveying extra information if everything is presented naturally to sighted users (plus, the information is generally useful to both anyway). WDYT?
> 
> @rt4914 this might also be a good design principle to incorporate in our in-development accessibility principles.

Let's not add extra labels in the UI because it would crowd the page with too much information. The extra details I suggested for TalkBack were meant to assist those who are visually impaired, which is why I thought it would be clearer to describe what 'double-tapping' the switch would do instead of mentioning that a switch is present. If we assume that users with TalkBack enabled are aware of how toggle switches are presented, then we can stick with the default and not include additional information.

**Comment by rt4914** [comment]
> > @mschanteltc if we want those extra details for buttons & options, should we maybe include them as explicit labels in the UI so that sighted users also get that context? In general I think the recommended pattern is to try to keep the information presented to sighted & accessible users essentially the same so much as possible. TalkBack is actually designed under this assumption, and we often don't need to take additional measures to support conveying extra information if everything is presented naturally to sighted users (plus, the information is generally useful to both anyway). WDYT?
> > @rt4914 this might also be a good design principle to incorporate in our in-development accessibility principles.
> 
> Let's not add extra labels in the UI because it would crowd the page with too much information. The extra details I suggested for TalkBack were meant to assist those who are visually impaired, which is why I thought it would be clearer to describe what 'double-tapping' the switch would do instead of mentioning that a switch is present. If we assume that users with TalkBack enabled are aware of how toggle switches are presented, then we can stick with the default and not include additional information.

@mschanteltc Just sharing another video for confirmation which shows "Double tap to toggle".
Download Permissions, 3 of 5 → Download and update only on Wifi; Topics will be download...queued. → checked, Download and update only on Wifi (**Or any custom description that we want**), Switch → Double tap to toggle

https://user-images.githubusercontent.com/9396084/108303672-56e44680-71cc-11eb-9587-15ef03c57bed.mp4

Also, this solution is used by android settings too and therefore Talkback users will be familiar with this solution too.

WDYT?

Also, @BenHenning I agree that we should keep things simple for talkback purposes and let the screen reader apps manage extra things.

**Comment by mschanteltc** [comment]
The order sounds good. I would change "check"/"not checked" to "On"/"Off" since toggle switches are usually described with those states.

**Comment by rt4914** [comment]
@mschanteltc and @BenHenning I have found following proofs because of which I think that `checked` and `not-checked` is something new and is common.
1. By default `Talkback` outputs `checked` and `not-checked` which means the `Talkback` must had been configured to output this.
2. Whatsapp, Instagram and Truecaller are some famous apps which uses `checked/not-checked` instead of `ON/OFF`
3. 
https://user-images.githubusercontent.com/9396084/108913265-bbc9f180-764f-11eb-92b2-2e108f0870e7.mp4

https://user-images.githubusercontent.com/9396084/108913293-c5535980-764f-11eb-8cf7-af3d331ae5dd.mp4

https://user-images.githubusercontent.com/9396084/108913299-c71d1d00-764f-11eb-9eae-282291174ab1.mp4

3. Checked it for `IMDb` app too and it also uses `checked/not-checked` instead of `ON/OFF`
4. Checked it for `Twitter` app too and it also uses `checked/not-checked` **along with** `ON/OFF`
However there is one important point too. In google apps I have found `ON/OFF` only and not `checked/not-checked`. But mostly thats because those screens are using `PreferenceActivity` and not `Switch/ SwitchCompat` View directly.

**Comment by mschanteltc** [comment]
Thanks for doing this research Rajat. Since it's prevalent in other apps, let's use `checked/not checked` instead of 'ON/OFF`. By the way, do all of these apps use `not-checked` with a hyphen?

**Comment by rt4914** [comment]
> Thanks for doing this research Rajat. Since it's prevalent in other apps, let's use `checked/not checked` instead of 'ON/OFF`. By the way, do all of these apps use `not-checked` with a hyphen?

Apologies for `hyphen`. It does not show hyphen.

**Comment by BenHenning** [comment]
Thanks for the added artifact @rt4914. That really helps. It does seem like making the whole box clickable should work fine if it's a known artifact of other apps (plus I suppose it is easy to undo mistakes if one is made, and these aren't destructive actions). Given that it simplifies the TalkBack solution, this seems reasonable.

**Comment by rt4914** [comment]
Closing as it was finished in #3412
