### ISSUE TITLE
[A11y] Profile Edit Screen

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2620]
## Current Output

https://user-images.githubusercontent.com/9396084/106901966-4dfc6b00-671e-11eb-9305-0532a38acdfc.mp4

## Issues Identified
- [x] User name is repetitive
Whenever talkback shifts to new screen the talkback by default outputs the title of the screen (Example: "Rajat"), then once learner swipes it will again say the title because that item is selected explicitly (Example: "Rajat"). Till this point is is correct and expected behaviour. But after this when learner swipes again the talkback outputs internal text "Rajat" and at this point it becomes too much repetition. Suggestions: We should skip the third output in this case. 
- [ ] Allow Download Access Merge talkback content
Currently talkback reads step by steps for this section: "Allow Download Access", "User is ... PIN.", "not checked, OFF, Switch". This also adds two extra steps for the learner. Instead it can be reduced to two output as per below flow.
`Allow Download Access, User is ... PIN.` -> **User Swipes** `not checked, OFF, Switch, Double tap to toggle` -> **User double taps** -> `checked`

Note: To understand the above issue(s) completely, it is recommended that you setup Talkback and play with the app keeping it on and that will give you better context.

**Accessibility Guide**: https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide

**Comment by mschanteltc** [comment]
@rt4914 Updated:
- No label for the profile picture in this instance. 
- Skip repeated name.

**Comment by rt4914** [comment]
@mschanteltc Second item is also blocked in this list.
