### ISSUE TITLE
[A11y] Pin Verification Screen

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2627]
## Current Output

https://user-images.githubusercontent.com/9396084/107003150-543c2700-67b2-11eb-97f0-636b2bd4db10.mp4

## Issues Identified
- [ ] If there is incorrect PIN the talkback does not shift to error and does not say that it was incorrect therefore the learner won't know what went wrong. Ideally as soon as error is show it should get highlighted. (For reference: In this [video](https://github.com/oppia/oppia-android/issues/2616) as soon as we enter incorrect answer the talkback automatically focuses on error.)
- [ ] If PIN area is selected, on swipe to next talkback shifts to **FORGOT MY PIN** but instead it should shift to **Show/Hide** Icon.
- [ ] Output for **Show/Hide View** is following: 
(a) Password [shown/hidden] icon
(b.) [SHOW/HIDE]
(c.) Double-tap to activate

Note: To understand the above issue(s) completely, it is recommended that you setup Talkback and play with the app keeping it on and that will give you better context.

**Accessibility Guide**: https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide

**Comment by mschanteltc** [comment]
- Let's leave it as a keyboard because in most cases, users would want to put in their PIN instead of reading the description. If a user has a PIN, they would need to set it up beforehand, so it's possible that they may be more understanding of why this screen exists and why a keyboard is immediately available. 
- I prefer the first suggestion "Show/Hide password icon, [STATE]" because it's similar to the way the toggle switch is described in the Administrator Controls (#2618). Can we also add "Double tap to [SHOW/HIDE] password" since it is also a button?

**Comment by rt4914** [comment]
> * Let's leave it as a keyboard because in most cases, users would want to put in their PIN instead of reading the description. If a user has a PIN, they would need to set it up beforehand, so it's possible that they may be more understanding of why this screen exists and why a keyboard is immediately available.
> * I prefer the first suggestion "Show/Hide password icon, [STATE]" because it's similar to the way the toggle switch is described in the Administrator Controls (#2618). Can we also add "Double tap to [SHOW/HIDE] password" since it is also a button?

@mschanteltc Actually we cannot control the `Double Tap` related statement as it is controlled by `Talkback` directly.

**Comment by rt4914** [comment]
> * Let's leave it as a keyboard because in most cases, users would want to put in their PIN instead of reading the description. If a user has a PIN, they would need to set it up beforehand, so it's possible that they may be more understanding of why this screen exists and why a keyboard is immediately available.
> * I prefer the first suggestion "Show/Hide password icon, [STATE]" because it's similar to the way the toggle switch is described in the Administrator Controls (#2618). Can we also add "Double tap to [SHOW/HIDE] password" since it is also a button?

@mschanteltc Actually we cannot control the `Double Tap` related statement as it is controlled by `Talkback` directly.

**Comment by mschanteltc** [comment]
> @mschanteltc Actually we cannot control the `Double Tap` related statement as it is controlled by `Talkback` directly.

How would the user know that the 'Show/Hide' button is clickable? If there is no label for this button or to show that it can be toggled, is there any way that we can?

**Comment by rt4914** [comment]
> > @mschanteltc Actually we cannot control the `Double Tap` related statement as it is controlled by `Talkback` directly.
> > How would the user know that the 'Show/Hide' button is clickable? If there is no label for this button or to show that it can be toggled, is there any way that we can?

It would read like this:
`Show/Hide password icon, SHOW, Double-tap to activate`. @mschanteltc

**Comment by mschanteltc** [comment]
Is it possible we can use "Double-tap to hide" (or show)? Or is "Double-tap to activate" the default we must use?

**Comment by Arjupta** [comment]
> > > @mschanteltc Actually we cannot control the `Double Tap` related statement as it is controlled by `Talkback` directly.
> > > How would the user know that the 'Show/Hide' button is clickable? If there is no label for this button or to show that it can be toggled, is there any way that we can?
> 
> It would read like this:
> `Show/Hide password icon, SHOW, Double-tap to activate`. @mschanteltc

@rt4914 
- Why can't we just go with `Show Password, Button` as a response because by default the Pin is in hidden state.
 - We can make the Show/Hide Icon to be a Button with that image and a textview just below showing the current state (ie HIDE or SHOW) and mark this textview not important for accessibility. WDYT? 
- The Show hide icon is read after forgot pin because it is mentioned after the Forgot Pin textview in the layout file.

**Comment by rt4914** [comment]
> Is it possible we can use "Double-tap to hide" (or show)? Or is "Double-tap to activate" the default we must use?

@mschanteltc So basically there are three parts to this: 
(a.) `Show/Hide password icon`
(b.) `SHOW`
(c.) `Double-tap to activate`

So in this we can control only (a.) and (b.). Part (c.) is controlled by readers and therefore we cannot control it.

**Comment by rt4914** [comment]
> > > > @mschanteltc Actually we cannot control the `Double Tap` related statement as it is controlled by `Talkback` directly.
> > > > How would the user know that the 'Show/Hide' button is clickable? If there is no label for this button or to show that it can be toggled, is there any way that we can?
> > 
> > 
> > It would read like this:
> > `Show/Hide password icon, SHOW, Double-tap to activate`. @mschanteltc
> 
> @rt4914
> 
> * Why can't we just go with `Show Password, Button` as a response because by default the Pin is in hidden state.
> * We can make the Show/Hide Icon to be a Button with that image and a textview just below showing the current state (ie HIDE or SHOW) and mark this textview not important for accessibility. WDYT?
> * The Show hide icon is read after forgot pin because it is mentioned after the Forgot Pin textview in the layout file.

Okay so in that case what would be the final output from talkback? @ARJUPTA

**Comment by mschanteltc** [comment]
Current, Adobe XD mock (with confusing icon and label):
![PC NP (Filled)](https://user-images.githubusercontent.com/22177674/108423251-7be8b180-71ec-11eb-986c-dbac1f385fb4.png)

Looking at the current output, the current Adobe XD mock (above image), and the screenshot in the [PRD](https://docs.google.com/document/d/1Ae587Q1ggfoca0j5j44LO3VFx_Z35oklyTcPZbz2w3I/edit?ts=5d02d804#heading=h.bt837l6gv2b6), there seems to be inconsistencies with the UI/UX.

I'm thinking of the following solution, based on NN Group's [recommendation](https://www.nngroup.com/articles/state-switch-buttons/) on state-switch controls (scroll to "Recommendations"):

- Have the icon reflect the current state of the PIN's visibility
- The label indicates what will happen if the user will tap on that control

**PIN Shown** (Talkback: _Password shown icon, Hide, Double-tap to activate_)
![PIN, shown](https://user-images.githubusercontent.com/22177674/108425402-41ccdf00-71ef-11eb-8ff4-82fecbcfef84.png)

**PIN Hidden** (Talkback: _Password hidden icon, Show, Double-tap to activate_)
![PIN, hidden](https://user-images.githubusercontent.com/22177674/108425405-42657580-71ef-11eb-8a6c-ae986a147d8e.png)


With these in mind, the following can be read: 
(a) `Password [shown/hidden] icon`
(b.) `[SHOW/HIDE]`
(c.) `Double-tap to activate`

WDYT?

**Comment by rt4914** [comment]
> Current, Adobe XD mock (with confusing icon and label):
> ![PC NP (Filled)](https://user-images.githubusercontent.com/22177674/108423251-7be8b180-71ec-11eb-986c-dbac1f385fb4.png)
> 
> Looking at the current output, the current Adobe XD mock (above image), and the screenshot in the [PRD](https://docs.google.com/document/d/1Ae587Q1ggfoca0j5j44LO3VFx_Z35oklyTcPZbz2w3I/edit?ts=5d02d804#heading=h.bt837l6gv2b6), there seems to be inconsistencies with the UI/UX.
> 
> I'm thinking of the following solution, based on NN Group's [recommendation](https://www.nngroup.com/articles/state-switch-buttons/) on state-switch controls (scroll to "Recommendations"):
> 
> * Have the icon reflect the current state of the PIN's visibility
> * The label indicates what will happen if the user will tap on that control
> 
> **PIN Shown** (Talkback: _Password shown icon, Hide, Double-tap to activate_)
> ![PIN, shown](https://user-images.githubusercontent.com/22177674/108425402-41ccdf00-71ef-11eb-8ff4-82fecbcfef84.png)
> 
> **PIN Hidden** (Talkback: _Password hidden icon, Show, Double-tap to activate_)
> ![PIN, hidden](https://user-images.githubusercontent.com/22177674/108425405-42657580-71ef-11eb-8a6c-ae986a147d8e.png)
> 
> With these in mind, the following can be read:
> (a) `Password [shown/hidden] icon`
> (b.) `[SHOW/HIDE]`
> (c.) `Double-tap to activate`
> 
> WDYT?

@mschanteltc Sounds good. We can implement this.

**Comment by mschanteltc** [comment]
Updated the [mocks](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/454ed2a6-6f9d-465e-bb35-5425fd7445f0/) to reflect the new changes.

**Comment by rt4914** [comment]
https://user-images.githubusercontent.com/9396084/125650089-1b3ec369-a478-404b-8d0b-0edd1830ee43.mp4

This is just a demo for reference fore new pin view which will help us control RTL and A11y in much better way and also we can remove the 3rd party library which we are using right now.

**Comment by rt4914** [comment]
@yash10019coder Any updates on this?
