### ISSUE TITLE
[A11y] Reading Text Size

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2628]
## Current Output

https://user-images.githubusercontent.com/9396084/107005369-a03c9b00-67b5-11eb-97b9-e6e2c96a830d.mp4

## Issues Identified
- [ ] The talkback reads this screen as **Oppia** at start, instead it should be **Reading Text Size**
- [ ] Seekbar should be replaced with simple options list like: "Small", "Medium", "Large", "Extra Large".  [Mock](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/2eaf085a-c2a7-4b1d-b515-5b32f8642669/)

Note: To understand the above issue(s) completely, it is recommended that you setup Talkback and play with the app keeping it on and that will give you better context.

**Accessibility Guide**: https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide

**Comment by Arjupta** [comment]
@rt4914 while going through this screen with the help of talkback it is very hard to understand the correct purpose of seekbar so it is better to give four variants of textsize in a group of radio button.

**Comment by mschanteltc** [comment]
I agree that it would be better to label each option as a word description like "Small," Medium," "Large," and "Extra Large." Numbers/Percentage might skew the user's perception on how it affects the text size.

**Comment by Arjupta** [comment]
@rt4914 doing this would include changes in both layout and kotlin files. Can I work on this? will be needing some guidance though.

**Comment by rt4914** [comment]
@mschanteltc can you prepare mocks for this case so that it's easier for Arjun to work on it ?

**Comment by rt4914** [comment]
@ARJUPTA assigned to you but wait for Chantel's mocks.

**Comment by mschanteltc** [comment]
Let's show the options as radio buttons, with `Small` as default. Each selection's font size should be reflected in their respective options so users have a visual reference for which size suits them best. WDYT? ([mock](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/2eaf085a-c2a7-4b1d-b515-5b32f8642669/))

![OP (Reading Display Size)](https://user-images.githubusercontent.com/22177674/107837600-8a4f4d00-6d56-11eb-92de-4c322121122f.png)

**Comment by Arjupta** [comment]
> Let's show the options as radio buttons, with `Small` as default. Each selection's font size should be reflected in their respective options so users have a visual reference for which size suits them best. WDYT? ([mock](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/2eaf085a-c2a7-4b1d-b515-5b32f8642669/))
> 
> ![OP (Reading Display Size)](https://user-images.githubusercontent.com/22177674/107837600-8a4f4d00-6d56-11eb-92de-4c322121122f.png)

Looks good to me

**Comment by rt4914** [comment]
> Let's show the options as radio buttons, with `Small` as default. Each selection's font size should be reflected in their respective options so users have a visual reference for which size suits them best. WDYT? ([mock](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/2eaf085a-c2a7-4b1d-b515-5b32f8642669/))
> 
> ![OP (Reading Display Size)](https://user-images.githubusercontent.com/22177674/107837600-8a4f4d00-6d56-11eb-92de-4c322121122f.png)

@mschanteltc This mock is really nice and to the point. Thanks.

**Comment by Sparsh1212** [comment]
@rt4914 Can I work on this issue, if @ARJUPTA is not working currently on this.

**Comment by rt4914** [comment]
@ARJUPTA Have a look and if you are not working assign it to @Sparsh1212

**Comment by Arjupta** [comment]
> @ARJUPTA Have a look and if you are not working assign it to @Sparsh1212

@rt4914 pardon for the delay I will be resolving this issue by the end of this week, hope this doesn't block your work.
