### ISSUE TITLE
[A11y] Options Language Screen

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2631]
## Current Output

https://user-images.githubusercontent.com/9396084/107033302-1a334b00-67db-11eb-94aa-6a77dd318e78.mp4

## Issues Identified
- [ ] The talkback reads this screen as **Oppia** at start, instead it should be either **Default Audio Language** or **App Language** 
- [ ] When any particular item is selected the output should be : **French, checked, 2 of 4** or **French, 2 of 4, checked** and checkbox should bot be selected separately. This will reduce one step for the learner.
Note: To understand the above issue(s) completely, it is recommended that you setup Talkback and play with the app keeping it on and that will give you better context.

**Accessibility Guide**: https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide

**Comment by Prince-kushwaha** [comment]
I want to work on this issue

**Comment by rt4914** [comment]
@Prince-kushwaha Any updates on this?

**Comment by abhinav12k** [comment]
@rt4914 Can i work on this issue?

**Comment by rt4914** [comment]
@abhinav12k I am assigning this to you but currently this issue is under time constraint. So if you are unable to make progress by Friday, I will have to self assign. Apologies for this inconvenience but I have to finish this project this month thats why.

**Comment by abhinav12k** [comment]
I will inform you if I am not able to make any further progress.

**Comment by rt4914** [comment]
> I will inform you if I am not able to make any further progress.

@abhinav12k Thanks a lot.
