### ISSUE TITLE
[A11y] FAQ Single

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2632]
## Current Output

https://user-images.githubusercontent.com/9396084/107034119-43a0a680-67dc-11eb-8b8d-3601ae5e4428.mp4

## Issues Identified
- [ ] The talkback reads this screen as **Oppia** at start, instead it should be **FAQs**

Note: To understand the above issue(s) completely, it is recommended that you setup Talkback and play with the app keeping it on and that will give you better context.

**Accessibility Guide**: https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide

**Comment by Prince-kushwaha** [comment]
I want to work on this issue

**Comment by som23ya** [comment]
@rt4914 can i work on this?

**Comment by rt4914** [comment]
Assigning this to @som23ya considering I have just assigned two issues to @Prince-kushwaha

**Comment by yashraj-01** [comment]
@rt4914 can I work on this issue? If it is still available then please assign it to me.

**Comment by rt4914** [comment]
@yashraj-iitr Already assigned. Please make sure that issue is not assigned to anyone else before commenting so that you can be assigned to an issue quickly.

**Comment by yashraj-01** [comment]
> @yashraj-iitr Already assigned. Please make sure that issue is not assigned to anyone else before commenting so that you can be assigned to an issue quickly.

okay.

**Comment by yashraj-01** [comment]
@rt4914 there is no response on this issue. I would like to work on this issue if it is still available. Please assign it to me.

**Comment by rt4914** [comment]
@yashraj-iitr Any updates on this issue?

**Comment by rt4914** [comment]
> @yashraj-iitr Any updates on this issue?

On second thought, can you please work on some other issue which is not related to A11y as I might have to prioritise this issue. I am assigning this to myself.

**Comment by yashraj-01** [comment]
> @yashraj-iitr Any updates on this issue?

actually I saw a PR which was very similar to this one. So, I was waiting for it to get merged. Then, I would have followed a similar approach.

**Comment by rt4914** [comment]
> > @yashraj-iitr Any updates on this issue?
> 
> actually I saw a PR which was very similar to this one. So, I was waiting for it to get merged. Then, I would have followed a similar approach.

No issues. It might take time. I will just create and merge this. Thanks.

**Comment by rt4914** [comment]
Closing this as it will get fixes in #2743
