### ISSUE TITLE
[A11y] Overflow Menu [Blocked]

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2638]
## Current Output
https://user-images.githubusercontent.com/9396084/107036003-f70a9a80-67de-11eb-94d7-fb7f6d38f4d7.mp4

## Issues Identified
Overflow menu gets stuck between two options and learner is unable to cancel the popup.

Overflow menu is present in following screens: Revision Card, Exploration, Question Player

Note: To understand the above issue(s) completely, it is recommended that you setup Talkback and play with the app keeping it on and that will give you better context.

**Accessibility Guide**: https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide

**Comment by Prince-kushwaha** [comment]
I want to work on this issue

**Comment by rt4914** [comment]
> I want to work on this issue

@Prince-kushwaha I have assigned you two issues right now. So not assigning you this issue for now. Let's wait for your other PRs to get merged.

**Comment by rt4914** [comment]
Considering that this is the behaviour across other apps too I am closing this issue.
I have checked this on `Whatsapp`, `Gmail App - Settings` and also `Settings` inside android phone.


https://user-images.githubusercontent.com/9396084/119275815-cedf6400-bc34-11eb-9523-db4ad69eea87.mp4
