### ISSUE TITLE
Fix data module tests & add them to CI

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#2642]
At some point, we deleted the TestMessage proto that was used specifically in tests without updating PersistentCacheStoreTest. That means that test is currently failing, and needs to be fixed. This also illustrates the need to add our data module tests to our CI workflow. This issue is tracking:
1. Running all [data](https://github.com/oppia/oppia-android/tree/develop/data) module tests locally & noting which ones are failing
2. Fix all of the failing tests (e.g. [PersistentCacheStoreTest](https://github.com/oppia/oppia-android/blob/develop/data/src/test/java/org/oppia/android/data/persistence/PersistentCacheStoreTest.kt) & any others that are failing)
3. Update our [CI workflow](https://github.com/oppia/oppia-android/blob/develop/.github/workflows/main.yml#L48) to also run the data module tests

**Comment by rawlin** [comment]
Hi @BenHenning, could you assign me this issue

**Comment by Akshat-gour** [comment]
@BenHenning 
@anandwana001 
can you assign me this issue

**Comment by BenHenning** [comment]
@rawlin are you currently working on this?

**Comment by BenHenning** [comment]
Reopening due to #2871. @prayutsu when creating a new PR that reintroduces the tests, please make sure to verify that the tests aren't flaky & introduce proof (e.g. a screenshot of running them ~100 times without a failure). You will need to dig into what the underlying cause is as the flake is a blocker for introducing data module tests into CI.

**Comment by BenHenning** [comment]
Also removing the 'good second issue' label since this has become harder now.

**Comment by FareesHussain** [comment]
Reopening as this was accidentally closed with https://github.com/oppia/oppia-android/pull/2871.

**Comment by prayutsu** [comment]
> Reopening due to #2871. @prayutsu when creating a new PR that reintroduces the tests, please make sure to verify that the tests aren't flaky & introduce proof (e.g. a screenshot of running them ~100 times without a failure). You will need to dig into what the underlying cause is as the flake is a blocker for introducing data module tests into CI.

Actually, I ran all the tests 3 times and then took the screenshots, so I assumed they were not flaky but will look into this today and make a fresh PR to avoid the flakiness.
