### ISSUE TITLE
`Switch Profile` NavDrawer Menu Item gets unchecked on changing Configuration

### ISSUE THREAD

**Issue by prayutsu** [oppia/oppia-android#2650]
**Describe the bug**
When the exit profile dialog appears via checking `Switch Profile` from Navigation Drawer, on changing the configuration of the device,  `Switch Profile` gets unchecked, and `Administrator Controls` gets checked in the Navigation Drawer.

**To Reproduce**
1. Go to Administrator Controls
2. Open Navigation Drawer and Click on `Switch Profile`
3. Change the configuration
4. Notice that in the background, `Switch Profile` gets unchecked, and `Administrator Controls` gets checked.

**Expected behavior**
Until the user clicks `Cancel`, the `Switch Profile` menu item should remain checked, and `Administrator Controls` should not get checked on changing the configuration.

**Screenshots**

https://user-images.githubusercontent.com/54636525/107144975-9016ee00-6964-11eb-9ffb-3dbdcea119b5.mp4

**Device**
- Redmi K20 Pro
- SDK version - 29

**Comment by prayutsu** [comment]
Consider claiming this issue when #1816 gets merged.

**Comment by anandwana001** [comment]
@prayutsu I think we should fix this in https://github.com/oppia/oppia-android/pull/1816 itself.
