### ISSUE TITLE
Create a BUILD.bazel file in utility/src/main/java/org/oppia/android/util/system

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#2657]
This task is part of the build system migration from Gradle to Bazel. A prerequesite before working on this issue is that you are able to build Oppia using Bazel. Check out [Oppia Bazel guide](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Guide) for Bazel terminology and more of what it does.

Create a BUILD.bazel file in 

`utility/src/main/java/org/oppia/android/util/system`

This package does not depend on any other packages inside of Oppia itself. Create a library for each file in the package, if possible, and add the dependency artifacts that are required based on the imports in the file.

## Create the libraries

Create the following libraries:

```BUILD
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")
load("@rules_jvm_external//:defs.bzl", "artifact")

kt_android_library(
    name = "oppia_date_time_formatter",
    srcs = ["OppiaDateTimeFormatter.kt"],
    visibility = ["//visibility:public"],
    deps = [
        artifact("com.google.firebase:firebase-crashlytics"),
    ],
)


kt_android_library(
    name = "oppia_clock",
    srcs = ["OppiaClock.kt"],
    visibility = ["//visibility:public"],
    deps = [
        artifact("androidx.annotation:annotation"),
        artifact("com.google.firebase:firebase-crashlytics"),
    ],
)
```

## Confirm that the package builds

When you've added the libraries, confirm that you can build the package by using Bazel to build the libraries. If you're in the  directory in your terminal, run

`bazel build :all` 

to build all your libraries. Alternatively, if you're standing in the root directory, run

`bazel build //utility/src/main/java/org/oppia/android/util/system:all`

to build all your libraries.

## Replace srcs dependencies in the module BUILD files

In the utility BUILD.bazel file, we have a glob for all the kotlin files in the utility library.

The glob function takes a second parameter, in which we can use to exclude the files we just turned into libraries. Exclude the entire system directory and add the required deps dependencies.

## Confirm that the app builds

Now you can confirm that the package works by building the app successfuly.

**Comment by anandwana001** [comment]
![Screenshot 2021-02-09 at 10 14 25](https://user-images.githubusercontent.com/25057618/107316907-9cfc2480-6abf-11eb-963e-6bb6c99b8d86.png)

**Comment by anandwana001** [comment]
![Screenshot 2021-02-09 at 10 14 25](https://user-images.githubusercontent.com/25057618/107317724-35df6f80-6ac1-11eb-8739-da9d90d02fc6.png)

![Screenshot 2021-02-09 at 10 24 31](https://user-images.githubusercontent.com/25057618/107317730-3972f680-6ac1-11eb-9579-17c350c41d7b.png)

@fsharpasharp How we can exclude these kotlin file from `srcs = glob(["src/main/java/org/oppia/android/util/**/*.kt"]),`?

**Comment by anandwana001** [comment]
did a mistake in the above screenshot, cleaning in this one with building an app.
@fsharpasharp Let me know if this looks good to you?


![Screenshot 2021-02-09 at 10 54 53](https://user-images.githubusercontent.com/25057618/107319770-7d67fa80-6ac5-11eb-825e-16918f0ab2a6.png)

![Screenshot 2021-02-09 at 10 58 41](https://user-images.githubusercontent.com/25057618/107320019-e3ed1880-6ac5-11eb-851e-af45d036f700.png)

**Comment by FareesHussain** [comment]
> @fsharpasharp How we can exclude these kotlin file from `srcs = glob(["src/main/java/org/oppia/android/util/**/*.kt"]),`?

@anandwana001 You can try this Reference - https://docs.bazel.build/versions/master/be/functions.html#glob
![image](https://user-images.githubusercontent.com/54740946/107324212-ac826a00-6acd-11eb-921d-2bce77c0c262.png)

**Comment by anandwana001** [comment]
Awesome, will send a pr.

**Comment by fsharpasharp** [comment]
Thanks @FareesHussain for providing the reference and @anandwana001 for working on this.

**Comment by anandwana001** [comment]
unassigning myself as I will not be available to work on this for one or two week, making it available if any other contributor wants to work on this issue.
