### ISSUE TITLE
Enable Dagger graph access for BindableAdapter

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#2658]
[BindableAdapter](https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/recyclerview/BindableAdapter.kt)s are created using one of two builders (single type & multi type), each of which has its own ``newBuilder`` function:
- https://github.com/oppia/oppia-android/blob/eb137fb/app/src/main/java/org/oppia/android/app/recyclerview/BindableAdapter.kt#L247
- https://github.com/oppia/oppia-android/blob/eb137fb/app/src/main/java/org/oppia/android/app/recyclerview/BindableAdapter.kt#L379

However, there are two drawbacks to this approach:
1. It doesn't allow us to easily gain access to Dagger-bound objects like OppiaLogger (which we probably will want to use in the future to add warnings logs when something breaks in the adapter
2. It requires passing in objects that could be automatically retrieved for better safety, such as the Fragment for [setting the LifecycleOwner](https://github.com/oppia/oppia-android/blob/eb137fb/app/src/main/java/org/oppia/android/app/recyclerview/BindableAdapter.kt#L120) of the builder

This issue is tracking:
1. Introducing a Factory class for each of the types of builders & making this injectable (similar to [StatePlayerRecyclerViewAssembler](https://github.com/oppia/oppia-android/blob/ef29201/app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt#L1338)
2. Having each factory inject an AndroidX fragment & automatically set that as the lifecycle owner (requires noting in the factories' documentation that they can only be used in fragment-bound classes)
3. Updating all places in code that use the builders today to instead inject factories
4. Removing the old ``newBuilder`` functions since they've been functionally replaced with a factory
5. Removing setLifecycleOwner since it will become an automatic mechanism, instead (which should also subsequently simplify the tests slightly, and lets us remove BaseBuilder in favor of a helper or extension function for retrieving the lifecycle owner

**Comment by Sparsh1212** [comment]
@anandwana001 @BenHenning 
I would love to work on this. Also, if possible then please guide me on how to get started with this issue.

**Comment by Akshat-gour** [comment]
@BenHenning is it still available, please assign me

**Comment by Akshat-gour** [comment]
@BenHenning 
@anandwana001 
If this issue is available. please assign to me.

**Comment by anandwana001** [comment]
Assigning to @Sparsh1212 as he has asked it earlier. 
You can start by creating a dependency - dependent graph, look for what are the dependencies for `BindableAdapter` and dependent of `BindableAdapter`. The five points mentioned above are good to start with.

**Comment by Sparsh1212** [comment]
> Assigning to @Sparsh1212 as he has asked it earlier.
> You can start by creating a dependency - dependent graph, look for what are the dependencies for `BindableAdapter` and dependent of `BindableAdapter`. The five points mentioned above are good to start with.

Okay thankyou. I will start working on this ASAP.

**Comment by Sparsh1212** [comment]
@anandwana001 I tried working hard on this but I am facing some trouble understanding this, so that might take some more time. So, if it is urgent, then you can assign this to any other contributor.
