### ISSUE TITLE
Migrate all third party dependencies to a dedicated top-level third_party folder

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#2659]
In order to simplify third-party dependency management, we should migrate all of our Maven artifacts to dedicated third party wrapper libraries with a shared list for versions. This has the following benefits:
1. It lets us centralize versions in a single file to make upgrading easier
2. It keeps all dependencies queryable through a third party folder
3. This aligns with Bazel [best practices](https://docs.bazel.build/versions/master/best-practices.html#third-party-dependencies)
4. It allows buildifier to properly sort dependencies in deps lists (since it doesn't like macros like ``artifact``)
5. It normalizes dependencies to be entirely in-workspace (rather than referencing external deps) for most build files

See https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Guide for instructions on setting up & using Bazel locally.

**Comment by BenHenning** [comment]
I will be following up with an example PR before opening this for public contribution.

/cc @fsharpasharp in case you have any thoughts on this. This came up as part of a project @prayutsu is working on.

@prayutsu can you add a link to the part of your design document explaining this to the main comment thread? While that project isn't finished being designed yet, I think we can go ahead and provide this as an issue for new contributors to help out with (to help support both the Bazel migration & your project).

**Comment by BenHenning** [comment]
Welp I just went ahead and fixed this in its entirety. :) Creating a generally usable library made more sense, and the changes after that were pretty quick.

**Comment by prayutsu** [comment]
I guess I will not be able to edit the main comment as I am only a collaborator, so mentioning the link to the design doc here - https://docs.google.com/document/d/11QlvnWqyJMu0MmuJ57ZwT0nM0kYc2HX65zvN96oSWas/
