### ISSUE TITLE
Wrong Tab selected on configuration change in TopicFragment

### ISSUE THREAD

**Issue by MaskedCarrot** [oppia/oppia-android#2667]
**Describe the bug**
Lesson Tab is selected on configuration change without changing the fragment of the viewpager

**To Reproduce**

1.Select First Test Topic from Home Carousel.
2. Select the practice tab
3. change the orientation
4. See the error

**Expected behavior**
The fragment should remain what it was before orientation change

**Screenshots**

https://user-images.githubusercontent.com/53645584/107349593-68ec2800-6aee-11eb-8276-a43e564bef55.mp4

**Device**
- Device/emulator being used: Real device Oneplus 7
- SDK version 29

**Comment by harsh-hash** [comment]
Can i work on this?

**Comment by MaskedCarrot** [comment]
@harsh-hash I am already working on this. I forgot to assign this to myself.

**Comment by rt4914** [comment]
@MaskedCarrot I am unable to reproduce this error. Can you check if you are checking this on latest develop code?

**Comment by MaskedCarrot** [comment]
@rt4914 I checked and i am still able to reproduce this error. My develop branch is even with oppia's.

**Comment by rt4914** [comment]
Actually in the steps just add one more step first:
Select `First Test Topic` from Home Carousel. 

Only then we can reproduce this error otherwise select `First Test Topic` from `All Topics` section does not produce this error.

**Comment by MaskedCarrot** [comment]
> Actually in the steps just add one more step first:
> Select `First Test Topic` from Home Carousel.
> 
> Only then we can reproduce this error otherwise select `First Test Topic` from `All Topics` section does not produce this error.

**Comment by MaskedCarrot** [comment]
accidentally closed so reopening

**Comment by anandwana001** [comment]
@MaskedCarrot Could you please confirm is this issue exist in the latest the develop branch. I cannot repro this issue.

**Comment by MaskedCarrot** [comment]
@anandwana001 Yes this issue exists in the latest develop branch. This issue can be reproduced by selecting `First Test Topic` from the Home Carousel.

**Comment by anandwana001** [comment]
This is weird, it's working correctly for me. 
@Srikanth-Kb @prayutsu Could you please confirm this?

**Comment by prayutsu** [comment]
@anandwana001 I am unable to repro the issue.

https://user-images.githubusercontent.com/54636525/107512285-9c9d7f80-6bcc-11eb-8742-8995c90b5b57.mp4

**Comment by MaskedCarrot** [comment]
@prayutsu @anandwana001  @Srikanth-Kb Please note this issue can only be reproduced when the topic is chosen from the `Recently-played stories` and not from `all topics`

**Comment by FareesHussain** [comment]
> @prayutsu @anandwana001 @Srikanth-Kb Please note this issue can only be reproduced when the topic is chosen from the `Recently-played stories` and not from `all topics`

I tried navigating through Promoted stories and I was able to reproduce this.

**Comment by prayutsu** [comment]
> @prayutsu @anandwana001 @Srikanth-Kb Please note this issue can only be reproduced when the topic is chosen from the `Recently-played stories` and not from `all topics`

Noted, I am also able to repro this now.

**Comment by srikanthkb** [comment]
> @prayutsu @anandwana001 @Srikanth-Kb Please note this issue can only be reproduced when the topic is chosen from the `Recently-played stories` and not from `all topics`

Yes, able to reproduce this issue with this procedure.

**Comment by anandwana001** [comment]
Ah, got the error. Can we check why it is happening, as we are landing on the same page either from Topic or from recently played, what's creating a difference here?
