### ISSUE TITLE
Remove :event_logger_java_proto_lite export from the model library

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#2673]
This task is part of the build system migration from Gradle to Bazel. A prerequesite before working on this issue is that you are able to build Oppia using Bazel. Check out [Oppia Bazel guide](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Guide) for Bazel terminology and more on what Bazel does.

## 1. Remove the export

In 

`/oppia-android/model/BUILD.bazel`

Remove :event_logger_java_proto_lite from the list of exports in the model library

```BUILD
android_library(
    name = "model",
    visibility = ["//visibility:public"],
    exports = [
        ":event_logger_java_proto_lite", # <-- Remove this line
        ":exploration_java_proto_lite",
        ":interaction_object_java_proto_lite",
        ":onboarding_java_proto_lite",
        ":profile_java_proto_lite",
        ":question_java_proto_lite",
        ":subtitled_html_java_proto_lite",
        ":subtitled_unicode_java_proto_lite",
        ":thumbnail_java_proto_lite",
        ":topic_java_proto_lite",
        ":translation_java_proto_lite",
        ":voiceover_java_proto_lite",
    ],
)
```

## 2. Add public visibility to the java_lite_proto_library

Add 

`    visibility = ["//visibility:public"],`

to the java_lite_proto_library that has the name event_logger_java_proto_lite.

## 3. Build the app using Bazel

Libraries that are indirectly depending on `event_logger_java_proto_lite` will now fail to build.  Try to build the app with Bazel and add the deps dependency

`//model:event_logger_java_proto_lite,`

to all the libraries that are now failing to build. You will have to look around for BUILD.bazel files that have libraries that require this replaced dependency.

These libraries will already have the //model dependency and since we removed the :event_logger_java_proto_lite from the model library itself, they will need to add the newly available public library directly as a dependency. (Not all libraries with the //model dependency may require the newly available library)

Once the app builds, you're done!

**Comment by Sparsh1212** [comment]
I would love to work on this. Please assign this to me.

**Comment by Sparsh1212** [comment]
@fsharpasharp When I am building the app with Bazel, the build is failing with these errors. Can you please tell,  how should I resolve them?
![image](https://user-images.githubusercontent.com/55937724/107574097-4fdd9700-6c14-11eb-95fb-ca49ec9d71f2.png)

**Comment by fsharpasharp** [comment]
Hey @Sparsh1212, is this after you made the changes? In that case you seem to be on step 3, try building again with --verbose_failures to see which libraries you will have to update.

**Comment by Sparsh1212** [comment]
@fsharpasharp No, I am actually trying to build the app using Bazel. I am on the prerequisite step. I haven't made any changes to the model.
Can this error be because of using the wrong version of Bazel? I am currently using the 3.7.2 version. Please tell me if this version is inappropriate for this use case.

**Comment by fsharpasharp** [comment]
Check out the instructions here

https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions
