### ISSUE TITLE
[Documentation] Added sublinks for the wiki as a summary for Android-UI-based github workflow

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2677]
1. Add sublinks to the titles in the wiki [Android-UI-based github workflow](https://github.com/oppia/oppia-android/wiki/Android-Studio-UI-based-Github-workflow)

Example - 
 ### Summary 
  - [Clone Oppia-Android using Android Studio](https://github.com/oppia/oppia-android/wiki/Android-Studio-UI-based-Github-workflow)
  - [Create new branch](https://github.com/oppia/oppia-android/wiki/Android-Studio-UI-based-Github-workflow)
  - [Push Changes](https://github.com/oppia/oppia-android/wiki/Android-Studio-UI-based-Github-workflow#push-changes)
      - [How to fix Push Failures](https://github.com/oppia/oppia-android/wiki/Android-Studio-UI-based-Github-workflow#push-changes)
  - [Pull changes from Develop](https://github.com/oppia/oppia-android/wiki/Android-Studio-UI-based-Github-workflow#push-changes)
  - [Merge and resolve conflict](https://github.com/oppia/oppia-android/wiki/Android-Studio-UI-based-Github-workflow#push-changes)  

2. Add numbered list as steps in each part

**Comment by seanlip** [comment]
The wiki has evolved so much in the past couple years that all the links in the original issue are obsolete, so I'm closing this issue. (I don't think this needs to be tracked separately anyway.)
