### ISSUE TITLE
Remove :interaction_object_java_proto_lite from the model library

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#2680]
This task is part of the build system migration from Gradle to Bazel. A prerequesite before working on this issue is that you are able to build Oppia using Bazel. Check out [Oppia Bazel guide](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Guide) for Bazel terminology and more on what Bazel does.

## 1. Remove the export

In 

`/oppia-android/model/BUILD.bazel`

Remove :interaction_object_java_proto_lite from the list of exports in the model library

```BUILD
android_library(
    name = "model",
    visibility = ["//visibility:public"],
    exports = [
        ":event_logger_java_proto_lite",
        ":exploration_java_proto_lite",
        ":interaction_object_java_proto_lite",
        ":onboarding_java_proto_lite",
        ":profile_java_proto_lite",
        ":question_java_proto_lite",
        ":subtitled_html_java_proto_lite",
        ":subtitled_unicode_java_proto_lite",
        ":thumbnail_java_proto_lite",
        ":topic_java_proto_lite",
        ":translation_java_proto_lite",
        ":voiceover_java_proto_lite",
    ],
)
```

## 2. Add public visibility to the java_lite_proto_library

Add 

`    visibility = ["//visibility:public"],`

to the java_lite_proto_library that has the name interaction_object_java_proto_lite.

## 3. Build the app using Bazel

Libraries that are indirectly depending on `interaction_object_java_proto_lite` will now fail to build.  Try to build the app with Bazel and add the deps dependency

`//model:interaction_object_java_proto_lite,`

to all the libraries that are now failing to build. You will have to look around for BUILD.bazel files that have libraries that require this replaced dependency.

These libraries will already have the //model dependency and since we removed the :interaction_object_java_proto_lite from the model library itself, they will need to add the newly available public library directly as a dependency. (Not all libraries with the //model dependency may require the newly available library)

Once the app builds, you're done!

**Comment by yashraj-01** [comment]
I would like to work on this issue. Please assign this to me.
