### ISSUE TITLE
Finish community profile

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#2684]
This came up in a discussion within #2682. Our [community page](https://github.com/oppia/oppia-android/community) is currently missing the following (checkboxes indicate whether it's been fixed):
- [ ] README (this is intermittently missing)
- [ ] Code of conduct (see https://github.com/oppia/oppia-android/pull/2770#issuecomment-784829036 for plan)
- [ ] Contributing guidelines
- [ ] Pull request template
- [x] Accepting content reports

The problem is that we actually have the [first four](https://github.com/oppia/oppia-android/tree/develop/.github) in our .github folder. This seems to be a GitHub bug, so I'm going to follow up with a report. It seems the code of conduct [must exactly match](https://github.community/t/code-of-conduct-is-present-in-repo-but-insights-community-tab-doesnt-detect-it/1534/7) the text of the corresponding covenant selected, and ours is very slightly modified. I might look into reverting these extra changes, but first we need to understand why GitHub seems to be looking in the wrong place for these files.

We should probably enable content reports, so going ahead and turning that on.

This is generally a low-priority effort since it's mainly a means to demonstrate a certain community quality bar (which we seem to meet given that we do have all of the things suggested minus the last one).

**Comment by BenHenning** [comment]
https://github.community/t/community-profile-items-not-recognized/160414 is tracking the issue. It seems GitHub staff is aware of the issue & is looking into it.

**Comment by anandwana001** [comment]
As we have issue template folder and template inside it, can we have a similar folder for pull request too, it might catch in community profile!!
https://github.com/oppia/oppia-android/tree/develop/.github/ISSUE_TEMPLATE

**Comment by BenHenning** [comment]
Ah interesting. Per https://github.blog/2018-01-25-multiple-issue-and-pull-request-templates/ it is possible to create multiple PR templates. Seems worthwhile to try that, at least. Will send out a PR soon.

**Comment by BenHenning** [comment]
@2765 did not solve the issue. :( I suspect, then, that the PR template flake is also due to the other bugs GitHub seems to have around community profile. We'll just need to wait and see if their fixes address our issues.

**Comment by anandwana001** [comment]
https://github.com/oppia/oppia-android/community

Community Page detects all of the things except Pull Request Template, I guess reverting our earlier PR template folder moving might fix this. Looks like this detection working is correcting from the GitHub side.

**Comment by anandwana001** [comment]
@BenHenning  All seems done in the community profile. good to close.

**Comment by BenHenning** [comment]
Ah, just noticed that @anandwana001. It seems GitHub fixed their issue. :)
