### ISSUE TITLE
Recently played story item not aligned in landscape mode

### ISSUE THREAD

**Issue by prayutsu** [oppia/oppia-android#2686]
**Describe the bug**
The recently played story item is not properly aligned for landscape layout.

**To Reproduce**
1. Go to HomeActivity
2. Change configuration to landscape
3. Observe that there's a little extra space before the recently played story item

**Expected behavior**
There should be no extra space before the story item.

**Screenshots**
Landscape (To be fixed)

<img src="https://user-images.githubusercontent.com/54636525/107632532-9e2e7c80-6c8c-11eb-8315-a65ea3837fdc.jpg" width="400">
<img src="https://user-images.githubusercontent.com/54636525/107632542-a1c20380-6c8c-11eb-8397-a57dd73a5c83.jpg" width="600">

Portrait-

<img src="https://user-images.githubusercontent.com/54636525/107632902-2876e080-6c8d-11eb-8d01-2376602d2e61.jpg" width="300">

**Device**
- Device - Redmi K20 Pro
- API Level -29

**Comment by prayutsu** [comment]
@rt4914 Please confirm this.

**Comment by rt4914** [comment]
@prayutsu Issue is correct. They should been aligned.

**Comment by prayutsu** [comment]
@rt4914 Thanks for confirming.

**Comment by Akshat-gour** [comment]
@prayutsu assign me

**Comment by Akshat-gour** [comment]
@prayutsu 
can i work on this

**Comment by prayutsu** [comment]
@Akshat-gour Assigned this to you, please go ahead :)
