### ISSUE TITLE
Not able to submit answer in Second Test Topic.

### ISSUE THREAD

**Issue by veena14cs** [oppia/oppia-android#2689]
**Describe the bug**
There is one option missing in the exploration` test_exp_id_4` of `test_topic_id_1`
**To Reproduce**
1. Go to Second Test Topic on HomeScreen.
2. Click on First chapter 
3. Re-arrange the correct options and submit the answer

**Expected behavior**
There is a need to add all the correct options in `test_exp_id_4.json` file in `IsEqualToOrdering` field which accepts the correct ordering of options.

**Screenshots**
![Screenshot_20210211_215153](https://user-images.githubusercontent.com/16301028/107665846-df865280-6cb3-11eb-8cfd-41950d65d296.jpg)

**Device**
- Vivo v3 
- API level - 21

**Additional context**
This fix has to be done in `StateRetrieverTest` too.

**Comment by anshbajpai** [comment]
@rt4914 can you please assign this to me?
