### ISSUE TITLE
Answer is not displayed on sdk 19

### ISSUE THREAD

**Issue by MaskedCarrot** [oppia/oppia-android#2698]
**Describe the bug**
The answer is not displayed in First Topic Test

**To Reproduce**
1. Click on First Test Topic
2. go to the lessons tab
3. Answer till you reach `what are the primary colors of light?`
4. Answer correctly (green, blue, red)
5. see the error

**Expected behavior**
The answer should be displayed.

**Screenshots**

<img src="https://user-images.githubusercontent.com/53645584/107746293-95e14a80-6d3b-11eb-976d-3e41c7203ec6.png" alt="error" width="200" height="400">

**Device**
- Device/emulator being used: Emulator Pixel 4 
- SDK version sdk 19

**Additional context**

**Debugging doc**
https://docs.google.com/document/d/1lrPGjFy_u7FLOUvzvd9prBcpw-ZKZj5GOS8JBqDZF5Q/edit?usp=sharing

**Comment by varunvjha** [comment]
Can I work on this issue?

**Comment by varunvjha** [comment]
I was able to reproduce the bug, but would you be able to help me navigate to the issue and maybe give some suggestions, if possible.

**Comment by rt4914** [comment]
> I was able to reproduce the bug, but would you be able to help me navigate to the issue and maybe give some suggestions, if possible.

@varunvjha Not sure but you can start by looking at `HtmlParser` in `utility` module.

**Comment by nskirkey** [comment]
Was hoping to be assigned this issue.

**Comment by FareesHussain** [comment]
@varunvjha Are you working on this?

**Comment by rt4914** [comment]
@nskirkey Assigned.

**Comment by veena14cs** [comment]
This issue was assigned to me, as I was working on supporting nested list tags (`<ul>` &`<li>`) that weren't handled correctly in SDK 19 and was causing crash. I have found the fix for it [reference](https://docs.google.com/document/d/1VqvDSxlWJkLfxknOa2nmcVeuXIbCcKQTFGUFoz3GOrk/edit?usp=sharing). 
We assumed that the solution proposed for list tags, would also fix this issue but it didn't reflect any changes. So un-assigning myself.

**Comment by addy-zero** [comment]
I would like to give this a shot :)

**Comment by rt4914** [comment]
@adizcode Its a bit complicated and we are currently unaware of the solution. You can try this out but I suggest that not to give a lot of time. If you think you are unable to find solution, please un-assign yourself and leave a comment mentioning what all things you have tried and why it did not work.

**Comment by adizcode** [comment]
@rt4914 Got it 👍

**Comment by addy-zero** [comment]
@rt4914 Un-assigning myself as it's taking me a lot of time in understanding the many moving parts involved. You can assign this to someone else.

**Comment by rt4914** [comment]
@adizcode Thanks. You can pick any other issue by commenting on it.

**Comment by seanlip** [comment]
Per https://github.com/oppia/oppia-android/issues/5012, we are deprecating support for Android KitKat, so this issue is no longer valid.
