### ISSUE TITLE
Incorrect highlighting in Drawer items

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2704]
**Describe the bug**

**To Reproduce**
1. Go to Home
2. Open Navigation Drawer
3. Click on `Admin Controls`
4. Click default back button
5. Open Navigation Drawer

Notice that both `Home` and `Admin Controls` are highlighted.

**Expected behavior**
Only `Home` screen should remain highlighted in this case.
The similar error occurs for other items too like `Options`, `Help`.

![untitled](https://user-images.githubusercontent.com/9396084/107778433-14ed7780-6d6a-11eb-9858-285594fcd78c.gif)

**Comment by harsh-hash** [comment]
can i work on this issue?

**Comment by rt4914** [comment]
@harsh-hash Thanks for showing interest. This is actually something similar to what @prayutsu is working on therefore assigning it to him.
Also before we can assign you issues please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by prayutsu** [comment]
@rt4914 Should we update the issue description (e.g we face this issue for all the menu items)?

**Comment by anandwana001** [comment]
Aren't we fixing this in #2671 ?
https://github.com/oppia/oppia-android/pull/2671#issuecomment-777409385 ?

**Comment by rt4914** [comment]
> @rt4914 Should we update the issue description (e.g we face this issue for all the menu items)?

@prayutsu Done

**Comment by rt4914** [comment]
> Aren't we fixing this in #2671 ?
> [#2671 (comment)](https://github.com/oppia/oppia-android/pull/2671#issuecomment-777409385) ?

Yes.
