### ISSUE TITLE
Resolve ktlint max line in ImageRegionSelectionInteractionView

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2716]
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name.
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the line of code under 100 char length.

Where to start?
1. Complete all installation steps before starting with this issue - https://github.com/oppia/oppia-android/wiki#installation
2. 
https://github.com/oppia/oppia-android/blob/d2d55013605d318965594932b9224578cbc9a586/app/src/main/java/org/oppia/android/app/player/state/ImageRegionSelectionInteractionView.kt#L162

Possible fix for this issue
```kotlin
    this.addOnLayoutChangeListener {
      _,
      left,
      top,
      right,
      bottom,
      oldLeft,
      oldTop,
      oldRight,
      oldBottom ->
      // Update the regions, as the bounds have changed
```

**Comment by Akshat-gour** [comment]
@anandwana001 
can i work on this

**Comment by abhinav12k** [comment]
Hi @anandwana001, Can I work on this issue if it's available?

**Comment by anandwana001** [comment]
@Akshat-gour I don't suggest you this issue because it's a good first issue and you already working on 3 good first issues. We recommend to go for bit harder issues to work on.
