### ISSUE TITLE
Resolve ktlint max line in DragAndDropItemFacilitator

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2717]
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name.
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the line of code under 100 char length.

Where to start?
1. Complete all installation steps before starting with this issue - https://github.com/oppia/oppia-android/wiki#installation
2. 
https://github.com/oppia/oppia-android/blob/d2d55013605d318965594932b9224578cbc9a586/app/src/main/java/org/oppia/android/app/recyclerview/DragAndDropItemFacilitator.kt#L12

Possible fix for this issue
```kotlin
class DragAndDropItemFacilitator(
  private val onItemDragListener: OnItemDragListener,
  private val onDragEndedListenr: OnDragEndedListener
) : ItemTouchHelper.SimpleCallback(
  ItemTouchHelper.UP or ItemTouchHelper.DOWN,
  /* swipeDirs= */ 0
) {
```

**Comment by Sparsh1212** [comment]
If this is up for grab, then please assign it to me.

**Comment by adit19shah** [comment]
I'm interested in working on this issue.

**Comment by anandwana001** [comment]
@Sparsh1212 I don't recommend this issue to you because you had already assigned 3 good first issues and we recommend to go for bit harder issues.
