### ISSUE TITLE
Resolve ktlint max line in DragDropTestActivity

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2718]
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name.
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the line of code under 100 char length.

Where to start?
1. Complete all installation steps before starting with this issue - https://github.com/oppia/oppia-android/wiki#installation
2. 
https://github.com/oppia/oppia-android/blob/d2d55013605d318965594932b9224578cbc9a586/app/src/main/java/org/oppia/android/app/testing/DragDropTestActivity.kt#L11

Possible fix for this issue
```kotlin
class DragDropTestActivity :
  InjectableAppCompatActivity(),
  OnItemDragListener,
  OnDragEndedListener {
```

**Comment by yashraj-01** [comment]
I would like to work on this issue. Please assign this to me.
