### ISSUE TITLE
Resolve ktlint max line in ViewModelBridgeFactory

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2719]
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name.
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the line of code under 100 char length.

Where to start?
1. Complete all installation steps before starting with this issue - https://github.com/oppia/oppia-android/wiki#installation
2. 
https://github.com/oppia/oppia-android/blob/d2d55013605d318965594932b9224578cbc9a586/app/src/main/java/org/oppia/android/app/viewmodel/ViewModelBridgeFactory.kt#L21

Possible fix for this solution
```kotlint
    check(modelClass.isAssignableFrom(viewModel.javaClass)) {
      "Cannot convert between injected generic type and " +
        "runtime assumed generic type for bridge factory."
    }
```

**Comment by Sparsh1212** [comment]
I would like to work on this issue. Please assign it to me.
