### ISSUE TITLE
Issues with Administrator Controls

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2728]
**Describe the bug**

**To Reproduce**
1. Go to 'Home`
2. Open navigation drawer
3. Click `Options`
4. Open navigation drawer
5. Click `Admin Controls`
6. Click back 
7. `Home` screen is visible

**Expected behavior**
Whatever is last screen that should be opened in this case `Options`

**Screenshots**
![untitled](https://user-images.githubusercontent.com/9396084/107948967-8facd180-6fba-11eb-910f-3cb9265166f7.gif)

**Additional context**
The current behavior might be correct. Waiting for confirmation from @mschanteltc

**Comment by rt4914** [comment]
@mschanteltc PTAL and confirm if this is actually a bug or the current behaviour is correct.

**Comment by prayutsu** [comment]
@rt4914 So, ideally we may want to return to the Options Fragment after pressing back from Admin Controls?

**Comment by rt4914** [comment]
> @rt4914 So, ideally we may want to return to the Options Fragment after pressing back from Admin Controls?

@prayutsu Actually I am not sure.

**Comment by Arjupta** [comment]
@rt4914 I faced a similar bug.
Steps -
- Enter admin profile
- Open drawer
- Click on Administrator Controls
- Press Back
- Open Drawer again

you will see both home and administer control to be highlighted in yellow like they both are selected

**Comment by prayutsu** [comment]
> @rt4914 I faced a similar bug.
> Steps -
> 
> * Enter admin profile
> * Open drawer
> * Click on Administrator Controls
> * Press Back
> * Open Drawer again
> 
> you will see both home and administer control to be highlighted in yellow like they both are selected

This is fixed in PR #2671.

**Comment by Arjupta** [comment]
> > @rt4914 I faced a similar bug.
> > Steps -
> > 
> > * Enter admin profile
> > * Open drawer
> > * Click on Administrator Controls
> > * Press Back
> > * Open Drawer again
> > 
> > you will see both home and administer control to be highlighted in yellow like they both are selected
> 
> This is fixed in PR #2671.

This is latest fetch from develop 
![Screenshot_1613409618](https://user-images.githubusercontent.com/64064110/107977092-91898b80-6fe0-11eb-8d1d-1f5bb3894453.png)

**Comment by prayutsu** [comment]
@ARJUPTA Actually the PR has not been merged yet, it has been approved by all the code owners and it will be merged soon.

**Comment by mschanteltc** [comment]
> @mschanteltc PTAL and confirm if this is actually a bug or the current behaviour is correct.

The selected page should change in the background first before the menu slides back. 

So from the Home Page, if I as a user tap the hamburger menu and select "Options," the page that is a layer below the side menu should change/fade to  the Options page, and then the side menu hides. ([mock](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/d47aa8de-a7a8-4d25-b011-5baefc7b7098/))

**Comment by rt4914** [comment]
> The selected page should change in the background first before the menu slides back.
> 
> So from the Home Page, if I as a user tap the hamburger menu and select "Options," the page that is a layer below the side menu should change/fade to the Options page, and then the side menu hides. ([mock](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/d47aa8de-a7a8-4d25-b011-5baefc7b7098/))

@mschanteltc The issue that you have mentioned is different and I have filed a new issue for the same. 
In this issue as mentioned in the description, its about the screens which should be shown under different scenarios.

**Comment by anandwana001** [comment]
Is this blocked?

**Comment by rt4914** [comment]
> Is this blocked?

@anandwana001 Yes. Waiting for another reply from @mschanteltc

**Comment by mschanteltc** [comment]
> > Is this blocked?
> 
> @anandwana001 Yes. Waiting for another reply from @mschanteltc

Ah I see, yes this flow is correct. If the app is on a navigation drawer page that is not the Home Page, tapping the 'back' button navigates the learner to the Home Page.

**Comment by rt4914** [comment]
Okay. Thanks @mschanteltc 
Closing this issues considering this is the expected behaviour of the app.
