### ISSUE TITLE
Add tests for score and mastery calculations

### ISSUE THREAD

**Issue by TheRealJessicaLi** [oppia/oppia-android#2738]
Need to write tests for [score and mastery calculation feature](https://docs.google.com/document/d/1ISuqvKs6b0xdE0-aEIHXYG7oDbCmDBcgUia0TiR9GpQ/edit?usp=sharing) after the calculation portion has been implemented. Tests should be checking the correctness of the final score and mastery degrees, since those are the only things relevant to the UI.

**Comment by kartikeysaran** [comment]
Can i work on this issue

**Comment by rt4914** [comment]
cc: @BenHenning and @TheRealJessicaLi

**Comment by TheRealJessicaLi** [comment]
This issue is blocked and won't be ready until the calculations portion of the feature has been done (which will probably be in April), so I'd recommend picking up something else!

**Comment by anandwana001** [comment]
@TheRealJessicaLi is this issue is now available?

**Comment by TheRealJessicaLi** [comment]
@anandwana001 I will be implementing the testing as I write the feature, and it's currently in progress! Sorry about that

**Comment by anandwana001** [comment]
Thanks for the update. Should I assign this to you?

**Comment by TheRealJessicaLi** [comment]
Sure, I just self-assigned it to avoid any confusion. Thanks!
