### ISSUE TITLE
Add ComponentGuide to Wiki

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2751]
Add ComponentGuide to Wiki

https://xd.adobe.com/view/dfe8ccd4-39eb-414d-a0b2-b5674357f966-8abb/grid

**Comment by seanlip** [comment]
Added to design team README. https://github.com/oppia/design-team/blob/develop/.github/README.md

**Comment by seanlip** [comment]
(Also, more generally, let's use the design-team repo as the source of truth for design stuff -- better to link there instead rather than duplicate things in this repo.)
