### ISSUE TITLE
Add Admin Pin Screen Content

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2754]
Currently `Add Admin Pin` screen is visible from two different places.

### Flow 1
1. Install fresh copy of app so that it contains only admin profile without any PIN.
2. Click on `Add Profiles` in Profile Chooser screen.
3. You will see below mentioned screenshot.

### Flow 2
1. Install fresh copy of app so that it contains only admin profile without any PIN.
2. Click on `Admin Controls` in Profile Chooser screen.
3. You will see below mentioned screenshot.

### Screenshot
<img src="https://user-images.githubusercontent.com/9396084/108831162-c2288100-75ef-11eb-8b8a-c103582c2fd7.png" width="250" />

### Solution
We do not show `Add Admin Pin` if there is only admin profile available when learner clicks on `Admin Controls` it should directly open `Admin Controls Activity` . This solution seems correct because if leaner selects the `Admin` profile, open `NavigationDrawer` and click `Admin Controls`, in this flow learner do not need to add any pin.

### Reference: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/8cdde1f8-daae-438c-8fdd-084e5d227080/

**Comment by anandwana001** [comment]
@rt4914 Just to understand, what if a learner(not admin) is on the profile chooser screen, they can enter into admin controls too!! right? because When we are on the Profile Chooser, we don't know the user is an admin or learner?

**Comment by rt4914** [comment]
> @rt4914 Just to understand, what if a learner(not admin) is on the profile chooser screen, they can enter into admin controls too!! right? because When we are on the Profile Chooser, we don't know the user is an admin or learner?

@anandwana001 They cannot use `Admin Controls`. Only the admin who has never added a PIN (means never created any profile too) can access `Admin Controls` directly. Otherwise in every other situation authentication is needed.

**Comment by anandwana001** [comment]
just a use case:
1. fresh copy, on Profile Chooser screen
2. click on the admin profile
3. home screen visible

close the app. 

till here we always have a possibility that anyone can enter into the admin controls!! right?

**Comment by rt4914** [comment]
> just a use case:
> 
> 1. fresh copy, on Profile Chooser screen
> 2. click on the admin profile
> 3. home screen visible
> 
> close the app.
> 
> till here we always have a possibility that anyone can enter into the admin controls!! right?

Yes. but its not **anyone** its actually **admin** because that is the only available profile.
