### ISSUE TITLE
High fi StoryActivity Inactive Card

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2756]
The mock for inactive card in `StoryActivity` has been updated to include clickable text to start the previous chapter.

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/5abb0ace-19ee-48b8-8154-919154f924d2/

**Comment by yashraj-01** [comment]
@rt4914 I would like to work on this issue. Please assign this to me.

**Comment by rt4914** [comment]
I am assigning you this and un-assigning you from #2324 as that issue will need more context.

**Comment by yashraj-01** [comment]
@rt4914 in the mock, this feature works on clicking on the entire card. So, do I need to make the whole card clickable or just the text?

**Comment by rt4914** [comment]
> @rt4914 in the mock, this feature works on clicking on the entire card. So, do I need to make the whole card clickable or just the text?

Only the text. @yashraj-iitr . For reference you can check how `Concept Cards` work in our app.

**Comment by yashraj-01** [comment]
@rt4914 I explored the app, and I think that I need to update the logic in the function `onExplorationClicked()` inside `StoryChapterSummaryViewModel.kt`. 

Please tell me if I am thinking right. If not, then please guide me where to look. Thanks.

**Comment by rt4914** [comment]
> @rt4914 I explored the app, and I think that I need to update the logic in the function `onExplorationClicked()` inside `StoryChapterSummaryViewModel.kt`.
> 
> Please tell me if I am thinking right. If not, then please guide me where to look. Thanks.

@yashraj-iitr Actually thats not correct.

1. You don't have to update the `onExplorationClicked ` logic because for inactive/locked cards this function won't work.
2. Also, as per UI, you only need to make the text clickable and that too not entirely, just the `Chapter 2: The Meaning of “Equal Parts”` which is in green color.

This is similar to `Concept Card` that we use in Exploration.
You can open concept card by following steps mentioned here: https://github.com/oppia/oppia-android/pull/1637#issue-467120880

**Comment by yashraj-01** [comment]
As per https://github.com/oppia/oppia-android/pull/1637#issue-467120880 , I think that using `clickableSpan` would make part of the text clickable. But I couldn't figure out where to implement this.

@rt4914 could you guide me further or may be provide a reference?
