### ISSUE TITLE
Remove :thumbnail_java_proto_lite from the list of exports in the model library

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#2763]
This task is part of the build system migration from Gradle to Bazel. 

## Prerequesites

- Make sure you are able to build Oppia using Bazel
- Follow the [Oppia Bazel Setup instructions](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions) to setup Bazel and learn the terminology.
- Read the [Gradle Bazel Migration Best Practies and FAQ](https://github.com/oppia/oppia-android/wiki/Gradle--Bazel-Migration-Best-Practices-and-FAQ) for more context and see if there's an answer there to any question you have.

## 1. Remove the export

In 

`/oppia-android/model/BUILD.bazel`

Remove :thumbnail_java_proto_lite from the list of exports in the model library

```BUILD
android_library(
    name = "model",
    visibility = ["//visibility:public"],
    exports = [
        ... # <- Remove it from this list.
    ],
)
```

## 2. Add public visibility to the java_lite_proto_library

Add 

`    visibility = ["////:oppia_api_visibility"],`

to the java_lite_proto_library that has the name thumbnail_java_proto_lite.

## 3. Build the app using Bazel and run the tests

Libraries that are indirectly depending on `thumbnail_java_proto_lite` will now fail to build. Try to build the entire app with Bazel and add the deps dependency

`//model:thumbnail_java_proto_lite,`

to all the libraries that are now failing to build. You will have to look around for BUILD.bazel files that have libraries that require this replaced dependency.

These libraries will already have the //model dependency and since we removed the :thumbnail_java_proto_lite from the model library itself, they will need to add the newly available public library directly as a dependency. (Not all libraries with the //model dependency may require the newly available library)

Once the app builds and all tests pass, you're done!

**Comment by imraghav20** [comment]
@fsharpasharp I would like to work on this issue but I am unable to find the "Oppia Bazel Guide" in the link you mentioned.
Please help me out.

**Comment by fsharpasharp** [comment]
@imraghav20, take another look. I've updated some of the out of date instructions.

**Comment by imraghav20** [comment]
Thanks @fsharpasharp I will try setting up Bazel and then comment to assign the issue.
