### ISSUE TITLE
Remove :translation_java_proto_lite from the list of exports in the model library

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#2767]
This task is part of the build system migration from Gradle to Bazel. A prerequesite before working on this issue is that you are able to build Oppia using Bazel. Check out [Oppia Bazel guide](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Guide) for Bazel terminology and more on what Bazel does.

## 1. Remove the export

In 

`/oppia-android/model/BUILD.bazel`

Remove :translation_java_proto_lite from the list of exports in the model library

```BUILD
android_library(
    name = "model",
    visibility = ["//visibility:public"],
    exports = [
        ... # <- Remove it from this list.
    ],
)
```

## 2. Add public visibility to the java_lite_proto_library

Add 

`    visibility = ["//visibility:public"],`

to the java_lite_proto_library that has the name translation_java_proto_lite.

## 3. Build the app using Bazel and run the tests

Libraries that are indirectly depending on `translation_java_proto_lite` will now fail to build. Try to build the entire app with Bazel and add the deps dependency

`//model:translation_java_proto_lite,`

to all the libraries that are now failing to build. You will have to look around for BUILD.bazel files that have libraries that require this replaced dependency.

These libraries will already have the //model dependency and since we removed the :translation_java_proto_lite from the model library itself, they will need to add the newly available public library directly as a dependency. (Not all libraries with the //model dependency may require the newly available library)

Once the app builds and all tests pass, you're done!

**Comment by adrishyantee** [comment]
I want to work on this issue. While I was going through the guide. I found that installing Bazel is not mentioned for Windows. But I have Windows operating system what can I do about this?

**Comment by rt4914** [comment]
@anandwana001 Can you have a look? (Maybe something that needs to be mentioned in wiki.)

**Comment by adrishyantee** [comment]
@rt4914 Do you know how to install Bazel in Windows? I want to contribute to this section of the app but I am not getting such help from the Bazel installation guide.

**Comment by anandwana001** [comment]
@adrishyantee If you take a look at out Bazel installation steps here - https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions#installation

> We don't officially support Windows for now so the Windows instructions may not be complete and may require additional tweaking.

Also, in the first step where you can find the install link which will take you to the official Bazel website - https://docs.bazel.build/versions/master/install.html

Then, you can follow the same commands, but keep note of the warning we had added on top

> We don't officially support Windows for now so the Windows instructions may not be complete and may require additional tweaking.

**Comment by adrishyantee** [comment]
@anandwana001 I tried building Bazel on Windows and I found that there's a need to update the ~/.bazelrc file. Hope after this, the environment will be all set.

**Comment by anandwana001** [comment]
So, is it building correctly? `//:oppia`

**Comment by adrishyantee** [comment]
I am actually stuck after this I tried but it's not building.
 The problem now is at this point, that is, [here](https://github.com/oppia/oppia-bazel-tools) at the point where we have to
 
 ---
 Update your ~/.bazelrc file to override the Android tools repository to point to this new location, and enable AndroidX testing. Or, just run this command (note that this overrides your profile-level bazelrc file, so you may want to copy this manually if you have other configurations already setup for Bazel):



 echo build --override_repository=android_tools="$(cd "$(dirname "$HOME/opensource/oppia-bazel-tools")"; pwd)/$(basename "$HOME/opensource/oppia-bazel-tools")" > ~/.bazelrc
echo build --android_databinding_use_androidx >> ~/.bazelrc

----

I am unable to understand how to implement the above changes in the file. From where do I need to make the changes or manually need to mention them in the bazelrc file. Can you help me how are we supposed to do this?

**Comment by anandwana001** [comment]
We had updated the wiki page a bit, could you take a look at this - https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions#installation

**Comment by adrishyantee** [comment]
Okay, I get it! Maybe switching to Linux will help to a large extent. I will install Ubuntu then and then start contributing! I will require a day for the setup and I will be back. Thanks a lot!

**Comment by adrishyantee** [comment]
@anandwana001 I installed Ubuntu and reached the same state of adding the oppia-bazel-tools. Can you help me now with how to do this step where I was stuck at? I am referring to this section:

---

Update your ~/.bazelrc file to override the Android tools repository to point to this new location, and enable AndroidX testing. Or, just run this command (note that this overrides your profile-level bazelrc file, so you may want to copy this manually if you have other configurations already setup for Bazel):

echo build --override_repository=android_tools="$(cd "$(dirname "$HOME/opensource/oppia-bazel-tools")"; pwd)/$(basename "$HOME/opensource/oppia-bazel-tools")" > ~/.bazelrc
echo build --android_databinding_use_androidx >> ~/.bazelrc
