### ISSUE TITLE
Remove model library from model/BUILD.bazel [BLOCKED]

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#2769]
This model library is now redundant since it does not export any libraries.

**Comment by jonathanalvares9009** [comment]
@fsharpasharp can I work on this?

**Comment by fsharpasharp** [comment]
This one is still blocked.

**Comment by jonathanalvares9009** [comment]
@fsharpasharp can you give me some bazel issues to work on?

**Comment by fsharpasharp** [comment]
Do you want to pick up https://github.com/oppia/oppia-android/issues/2760?

I'm going to file some more issues later this week, feel free to pick those up.
