### ISSUE TITLE
Optimise test case and use ActivityScenarioRule in AdminControls and AppVersion

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2785]
Optimise test case and use ActivityScenarioRule in AdministratorControlsActivity and AppVersionActivityTest

Advantages of using `ActivityScenarioRule` is that we don't need to launch the activity in each test case and thus reducing one level of nesting as well as reducing the code.

**Comment by adhiamboperes** [comment]
Closing due to ActivityScenarioRule  being deprecated. See https://github.com/oppia/oppia-android/issues/5308 for details.
