### ISSUE TITLE
[A11y] Add label for StoryActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2808]
## Task
Introduce label for `StoryActivity` as `Chapter List`.

Reference PR: https://github.com/oppia/oppia-android/pull/2750

When you create a PR for this, make sure you add test to check the functionality. Also, suggest working on this PR only if its your first or second PR to Oppia-Android project.

## General Explanation
When `Talkback` is on, whenever we click on any option which leads to new screen the reader will automatically read the `label` associated with that screen first. If in case label in not present then it will read app name i.e. `Oppia`.

### Example

https://user-images.githubusercontent.com/9396084/108906068-78b75080-7646-11eb-943e-212e29fc3e98.mp4

In this above video as soon as we double-tap `Battery`, new screen is opened. 
The reader first outputs `Battery` followed by `Navigate up, Button` and finally `Battery` again. In this the first `Battery` output is the `label` of this new screen which indicates the learner which screen is opened. The second `Battery` is because we selected the title in the screen and it's just reading that text.
So we need `labels` for various screens general which matches the title but if the title is dynamic then we need static label.

**Comment by justdvnsh** [comment]
@rt4914 Can I take up this issue ???

**Comment by justdvnsh** [comment]
@rt4914 This would be my 3rd first issue for this org. Can you please point me out to some higher level issue ?

**Comment by rt4914** [comment]
> @rt4914 This would be my 3rd first issue for this org. Can you please point me out to some higher level issue ?

@justdvnsh Sent you an email.

**Comment by justdvnsh** [comment]
@rt4914 Thank you for the email. I have read and replied to it. Thanks
