### ISSUE TITLE
[A11y] Add label for ProfileListActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2823]
## Task
Introduce label for `ProfileListActivity` as `Profile List`.

Reference PR: https://github.com/oppia/oppia-android/pull/2750

When you create a PR for this, make sure you add test to check the functionality. Also, suggest working on this PR only if its your first or second PR to Oppia-Android project.

## General Explanation
When `Talkback` is on, whenever we click on any option which leads to new screen the reader will automatically read the `label` associated with that screen first. If in case label in not present then it will read app name i.e. `Oppia`.

### Example

https://user-images.githubusercontent.com/9396084/108906068-78b75080-7646-11eb-943e-212e29fc3e98.mp4

In this above video as soon as we double-tap `Battery`, new screen is opened. 
The reader first outputs `Battery` followed by `Navigate up, Button` and finally `Battery` again. In this the first `Battery` output is the `label` of this new screen which indicates the learner which screen is opened. The second `Battery` is because we selected the title in the screen and it's just reading that text.
So we need `labels` for various screens general which matches the title but if the title is dynamic then we need static label.

**Comment by AnubhavPabby** [comment]
@rt4914 Hey can you assign this issue to me

**Comment by arjunrkaushik** [comment]
@rt4914 I would like to work on this issue, as suggested to me by Abhay Garg

**Comment by prayutsu** [comment]
@arjunrkaushik As @AnubhavPabby claimed it first, we should assign this issue to him, but I am assigning you #2819 which is almost similar to this. Can you please add a comment there so can I assign that issue to you?

**Comment by Karanjot-singh** [comment]
Can I work on this issue? @prayutsu I might need some help in testing as I am fairly new to contributing.

**Comment by rt4914** [comment]
> Can I work on this issue? @prayutsu I might need some help in testing as I am fairly new to contributing.

@Karanjot-singh This issue is already assigned to @AnubhavPabby

**Comment by pravesh00** [comment]
@rt4914 is this issue resolved? Can I work on this?

**Comment by rt4914** [comment]
> @rt4914 is this issue resolved? Can I work on this?

@pravesh00 Thanks for your interest. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.
