### ISSUE TITLE
[A11y] Add label for RecentlyPlayedActivity [Blocked on #3095] 

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2824]
## Task
Introduce label for `RecentlyPlayedActivity` as either `Stories for you` or `Recently played stories`. 

Reference PR: https://github.com/oppia/oppia-android/pull/2750

When you create a PR for this, make sure you add test to check the functionality. Also, suggest working on this PR only if its your first or second PR to Oppia-Android project.

## General Explanation
When `Talkback` is on, whenever we click on any option which leads to new screen the reader will automatically read the `label` associated with that screen first. If in case label in not present then it will read app name i.e. `Oppia`.

### Example

https://user-images.githubusercontent.com/9396084/108906068-78b75080-7646-11eb-943e-212e29fc3e98.mp4

In this above video as soon as we double-tap `Battery`, new screen is opened. 
The reader first outputs `Battery` followed by `Navigate up, Button` and finally `Battery` again. In this the first `Battery` output is the `label` of this new screen which indicates the learner which screen is opened. The second `Battery` is because we selected the title in the screen and it's just reading that text.
So we need `labels` for various screens general which matches the title but if the title is dynamic then we need static label.

**Comment by IAmJaishree** [comment]
@rt4914 I would like to work on it, could you please assign it to me?

**Comment by rt4914** [comment]
@IAmJaishree I have assigned you two similar issues. Also I will be working on this as it involves some discussion with teammates. Thanks.

**Comment by shankarpriyank** [comment]
I would like to work on this could you please assign this to me @bkaur-bkj

**Comment by bkaur-bkj** [comment]
@rt4914 can this issue be assigned to @shankarpriyank ?

**Comment by rt4914** [comment]
@bkaur-bkj Actually no. I just removed good-first-issue label from it.

**Comment by bkaur-bkj** [comment]
> @bkaur-bkj Actually no. I just removed good-first-issue label from it.

okay

**Comment by rishidyno** [comment]
@rt4914 @BenHenning can I work on this issue, as I am quite interested?

**Comment by rt4914** [comment]
@rishidyno Suggest doing following things:
1. Play with current app to see what is the behaviour of screen-reader on this screen under various cases where title changes for the toolbar.
2. Check this PR https://github.com/oppia/oppia-android/pull/3065
3. Once you have understand the problem and the PR that I had worked on, please mention the approach that you will be following to solve this issue. 

Actually this issue is not like any other `Add Label` issue. Its a bit complicated and will need changes mainly in how we work around intents.
