### ISSUE TITLE
Update var to val in AdministratorControlsDownloadPermissionsViewModel

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2827]
Inside `AdministratorControlsDownloadPermissionsViewModel` we are using `var` but we should be using `val` for following values:

`isTopicWifiUpdatePermission` and `isTopicAutoUpdatePermission`

**Comment by adit19shah** [comment]
I'm interested in working on this issue.

**Comment by MaskedCarrot** [comment]
@adit19shah assigning this to you.

**Comment by rt4914** [comment]
Thanks @MaskedCarrot

**Comment by rt4914** [comment]
@adit19shah 
Thanks for showing interest. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by adit19shah** [comment]
@rt4914 already done !
