### ISSUE TITLE
Update comment in RouteToAppVersionListener

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2829]
Update comment in RouteToAppVersionListener

Update to: `/** Listener for when an activity should route to [AppVersionActivity]. */`

**Comment by nlok5923** [comment]
@rt4914 i would like to work on it please assign it to me

**Comment by FareesHussain** [comment]
@nlok5923  Thanks for showing interest in oppia. Please check out our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the *CLA* and fill the *survey form* we can assign you issues to work on.

**Comment by nlok5923** [comment]
@FareesHussain i had already signed CLA and filled survey form.
