### ISSUE TITLE
Add missing named argument

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2833]
**Describe the bug**
We are passing arguments without specifying their names.

**Expected behavior**
Look for the below-mentioned test files and add all the missing named arguments 

- [x] AdministratorControlsActivityTest (@dishantvyas15 )
- [x] AppVersionActivityTest (@darshanhande11)
- [x] CompletedStoryListActivityTest (@techjd)
- [x] FAQListFragmentTest (@ksog66)
- [x] HelpFragmentTest (@ravi9607)
- [x] RecentlyPlayedFragmentTest (@techjd)
- [x] OngoingTopicListActivityTest (@nlok5923)
- [x] OptionsFragmentTest  (@yashyon)
- [x] ProfileChooserFragmentTest (@mrwhoknows55)
- [x] ProfileProgressFragmentTest (@Arnold2381)
- [x] BindableAdapterTest (@jkugsiya)
- [x] ProfileEditActivityTest (@ArpitShukIa)
- [x] ProfileListFragmentTest (@Naman-1234)
- [x] SplashActivityTest (@darshanhande11)
- [x] StoryActivityTest (@jkugsiya)
- [x] StoryFragmentTest (@ChiragKalra)
- [x] DragDropTestActivityTest (@sakshampruthi)
- [x] ImageRegionSelectionInteractionViewTest (@Karanjot-singh)
- [x] TopicTestActivityForStoryTest (@nlok5923)
- [x] TopicInfoFragmentTest (@darshanhande11)
- [x] TopicLessonsFragmentTest (@Amar-2003)
- [x] TopicPracticeFragmentTest (@Karanjot-singh)
- [x] TopicRevisionFragmentTest (@justdvnsh)

**Additional context**
What is Named Arguments? 
https://kotlinlang.org/docs/functions.html#named-arguments

**How to work on this issue**
Comment below "I want to work on [FILE_NAME]", mention the file name from the above list you want to work on. 
Please work on only one file at a time. 

If you are a First Time Contributor to Oppia-Android, Start [here](https://github.com/oppia/oppia-android/wiki#onboarding-instructions).

**Note: Don't assign this issue to anyone as this issue should be done in a multiple PR fashion "single file, single PR"**

**Comment by dishantvyas15** [comment]
Hello!
I want to work on the 'AdministratorControlsActivityTest' file.

**Comment by techjd** [comment]
I want to work on "CompletedStoryListActivityTest"

**Comment by ravi9607** [comment]
I want to work on the 'HelpFragmentTest'

**Comment by mrwhoknows55** [comment]
I want to work on "ProfileChooserFragmentTest"

**Comment by nlok5923** [comment]
@anandwana001 i would like to work on "OngoingTopicListActivityTest" please assign it to me.

**Comment by Naman-1234** [comment]
I want to work on "ProfileListFragmentTest".

**Comment by rt4914** [comment]
Reopening this as it was incorrectly closed by #2842

**Comment by techjd** [comment]
I want to work on "RecentlyPlayedFragmentTest"

**Comment by rt4914** [comment]
> I want to work on "RecentlyPlayedFragmentTest"

@techjd It has been assigned to you. Thanks.

**Comment by nlok5923** [comment]
@rt4914  @anandwana001 i would like to work on `TopicTestActivityForStoryTest` please assign it to me

**Comment by nskirkey** [comment]
I was hoping to work on `FAQListFragmentTest`.

**Comment by Victor-Titan** [comment]
I want to work on `DragDropTestActivityTest`

**Comment by anandwana001** [comment]
@Victor-Titan as you had already worked on multiple good first issues, we suggest you to look for much harder issues.

**Comment by nskirkey** [comment]
> I was hoping to work on `FAQListFragmentTest`.

Was I going to be assigned this, or should I look for something else? @anandwana001

**Comment by Naman-1234** [comment]
I want to work on 'DragDropTestActivityTest'.

**Comment by anandwana001** [comment]
> > I was hoping to work on `FAQListFragmentTest`.
> 
> Was I going to be assigned this, or should I look for something else? @anandwana001

It looks like you already worked on two Good first issues, so we suggest you look for bit harder issues in the bucket list. This helps you in learning and more understanding towards the codebase.

**Comment by ksog66** [comment]
I want to work FAQListFragmentTest

**Comment by anandwana001** [comment]
@ksog66 Start from here - https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by arinarora18** [comment]
I want to work on "CustomBulletSpanTest"

**Comment by justdvnsh** [comment]
@anandwana001 I want to work on TopicRevisionFragmentTest

**Comment by prayutsu** [comment]
@anandwana001 Can you please assign @arinarora18 CustomBulletSpanTest? 
@arinarora18 When you get assigned to CustomBulletSpanTest, you can go ahead and make a PR.

**Comment by justdvnsh** [comment]
@anandwana001 I want to work on "TopicPracticeFragmentTest". I have already made a PR for TopicRevisionFragmentTest #2899

**Comment by arinarora18** [comment]
> @anandwana001 Can you please assign @arinarora18 CustomBulletSpanTest?
> @arinarora18 When you get assigned to CustomBulletSpanTest, you can go ahead and make a PR.

Haven't been assigned this yet, should I move to some other issue?

**Comment by FareesHussain** [comment]
@arinarora18 you can start working on this and create a pr as soon as you get assigned

**Comment by jkugsiya** [comment]
I want to work on 'StoryActivityTest'.

**Comment by arjunrkaushik** [comment]
I want to work on "AppVersionActivityTest"

**Comment by anandwana001** [comment]
> @anandwana001 I want to work on "TopicPracticeFragmentTest". I have already made a PR for TopicRevisionFragmentTest #2899

@justdvnsh Could you please mention the PR solving `TopicRevisionFragmentTest`?

**Comment by sakshampruthi** [comment]
Hi, I wish to work on "DragDropTestActivityTest"

**Comment by sakshampruthi** [comment]
> Hi, I wish to work on "DragDropTestActivityTest"

I am getting the following error while push
scripts/buf_lint_check.sh: line 13: ../oppia-android-tools/buf-Darwin-x86_64: No such file or directory

I have followed all the steps for installation from the wiki
(for reference I am using a MacBook with the m1 chip)

Edit 1:
I have created a pull request using my windows system but I am still facing this error on my macbook m1 and it seems that it is due to M1 chip only since it shows a x86 file missing. Would love to help if it needs to be resolved since apple silicon systems might increase in coming months

**Comment by anandwana001** [comment]
@sakshampruthi have you run the script correctly as mentioned in the installation steps? 
M1 chip under the hood has Darwin system I guess, what's the uname for M1 chip?

**Comment by sakshampruthi** [comment]
> @sakshampruthi have you run the script correctly as mentioned in the installation steps?
> M1 chip under the hood has Darwin system I guess, what's the uname for M1 chip?

@anandwana001 Yes I followed the installation steps correctly 
running `uname -a` gives this:

```Darwin Sakshams-MacBook-Air.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64```

To validate my issue I will try to get hands-on an intel-based mac system. If the same steps don't produce this error then it might be some compatibility issue with m1 as it's not an x86 processor

**Comment by anandwana001** [comment]
It looks like the issue is `RELEASE_ARM64_T8101 arm64`.

**Comment by anandwana001** [comment]
Also, @sakshampruthi could you confirm do you have this file `/oppia-android-tools/buf-Darwin-x86_64` or not?

**Comment by sakshampruthi** [comment]
@anandwana001 No this file is not getting generated. I tried again and again but was not able to generate the file. The file being generated is `buf-Darwin-arm64` This might be due to the fact that x86 files are dealt with using rosetta2. I will try to generate this file again in the terminal this time using rosetta and will update you here

**Comment by anandwana001** [comment]
@sakshampruthi The required file will not generate, because we use the `uname` of the system and as it's arm for your's it will not give you x86 one. I will fix the script which can prevent error for such cases. 
Thanks for bringing this in light.

**Comment by sakshampruthi** [comment]
@anandwana001 I was able to successfully generate `/oppia-android-tools/buf-Darwin-x86_64` file using `bash scripts/setup.sh` given the terminal is open with Rosetta 2. Without this it generates `buf-Darwin-arm64` 

For the time being you may mention this in the wiki

**Comment by anandwana001** [comment]
Sounds helpful, could you try running `bash scripts/buf_lint_check.sh` from AS terminal? Let's see if it works.

**Comment by sakshampruthi** [comment]
@anandwana001 Working perfectly with and without Rosetta 2 because `buf-Darwin-x86_64` is now available in oppia-android-tools folder

**Comment by anandwana001** [comment]
Could you please add steps on how did you manage to download this file. This will help other contributors facing the similar issue.

**Comment by sakshampruthi** [comment]
Step 1: Locate Terminal in Finder
Step 2: Right-click and create a duplicate Terminal (and rename it accordingly say Terminal x86 to avoid confusion)
Step 3: For the Terminal x86 right-click and click Get info and check the option  `Open using Rosetta`
Step 4: Now run `bash scripts/setup.sh` in Terminal x86 and all the required files will be generated as they should

**Comment by anandwana001** [comment]
Thanks, @sakshampruthi for helping us here.

**Comment by arinarora18** [comment]
@anandwana001 I would like to work on TopicInfoFragmentTest.

**Comment by ChiragKalra** [comment]
I would like to work on StoryFragmentTest.

**Comment by ChiragKalra** [comment]
I would like to work on StoryFragmentTest.

**Comment by Karanjot-singh** [comment]
I would like to work on TopicPracticeFragmentTest @prayutsu

**Comment by anandwana001** [comment]
> @anandwana001 I would like to work on TopicInfoFragmentTest.

@arinarora18 any update on this?

**Comment by pankajpoply45** [comment]
I want to work on OptionsFragmentTest File

**Comment by ArpitShukIa** [comment]
@anandwana001 I want to work on ProfileEditActivityTest

**Comment by E13ctron** [comment]
@anandwana001 I would like to work on TopicLessonsFragmentTest

**Comment by rt4914** [comment]
> @anandwana001 I want to work on ProfileEditActivityTest

@ArpitShukIa done. Thanks.

**Comment by Arnold2381** [comment]
@rt4914 i want to work on ProfileProgressFragmentTest

**Comment by Karanjot-singh** [comment]
@anandwana001 I would like to work on ImageRegionSelectionInteractionViewTest

**Comment by Arnold2381** [comment]
working on BindableAdapterTest!

**Comment by darshanhande11** [comment]
@rt4914 @anandwana001 I would like to work on TopicInfoFragmentTest

**Comment by yashyon** [comment]
@rt4914 @anandwana001 I would like to work on OptionsFragmentTest.

**Comment by darshanhande11** [comment]
@anandwana001 I would like to work on AppVersionActivityTest.

**Comment by darshanhande11** [comment]
@anandwana001 I would like to work on SplashActivityTest.

**Comment by rt4914** [comment]
> @anandwana001 I would like to work on SplashActivityTest.

Thanks for showing interest @darshanhande11 . Please, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by darshanhande11** [comment]
> > @anandwana001 I would like to work on SplashActivityTest.
> 
> Thanks for showing interest @darshanhande11 . Please, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

@rt4914 I have completed all the above steps already and would be glad to fix this if assigned 😄

**Comment by jkugsiya** [comment]
I would like to work on BindableAdapterTest.

**Comment by rt4914** [comment]
Closing this as the checklist is complete.
