### ISSUE TITLE
Add correct lambda function argument name

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2834]
**Describe the bug**
In most of the places we are using `it` for the lambda function argument. `it` is not readable and not helps to understand what it represents. 

**Expected behavior**
Look for the below-mentioned test files and Replace `it` with the correct names

- [x] PromotedStoryListViewModelTest (@Abhinavtdk )
- [x] PromotedStoryViewModelTest (@jonathanalvares9009)
- [x] TopicSummaryViewModelTest (@nskirkey)
- [x] WelcomeViewModelTest (@ravi9607 )

**Additional context**
Kotlin lambda function - https://kotlinlang.org/docs/lambdas.html#higher-order-functions

**How to work on this issue**
Comment below "I want to work on [FILE_NAME]", mention the file name from the above list you want to work on.
Please work on only one file at a time.

**Note: Don't assign this issue to anyone as this issue should be done in a multiple PR fashion "single file, single PR"**

**Comment by adit19shah** [comment]
I am interested in working on "WelcomeViewModelTest" for this issue.

**Comment by Abhinavtdk** [comment]
I want to work on "PromotedStoryListViewModelTest"

**Comment by nskirkey** [comment]
I would like to work on TopicSummaryViewModelTest.

**Comment by nskirkey** [comment]
I would like a bit more information on what would be correct as far as what we are renaming `it` to. Is there an objective correct name or is this something that we're coming up with?

**Comment by anandwana001** [comment]
> I am interested in working on "WelcomeViewModelTest" for this issue.

It looks like you already solved 3 Good-First_issues, so I recommend you to look for bit harder issues. Let me know if you are interested in any other issue to work on.

**Comment by anandwana001** [comment]
> I want to work on "PromotedStoryListViewModelTest"

Start from here - https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by anandwana001** [comment]
> I would like a bit more information on what would be correct as far as what we are renaming `it` to. Is there an objective correct name or is this something that we're coming up with?

@nskirkey Taking an example from `TopicSummaryViewModelTest`
https://github.com/oppia/oppia-android/blob/1711a35d59b3fed1a9a16903360b502e58bca8fb/app/src/sharedTest/java/org/oppia/android/app/home/TopicSummaryViewModelTest.kt#L99
It's not readable just reading this line of code that what we are passing in the function, but if we look this code in the Android Studio we  get the suggestions
<img width="845" alt="Screenshot 2021-03-04 at 06 42 01" src="https://user-images.githubusercontent.com/25057618/109895198-d554e400-7cb4-11eb-9ac7-f2ac7383cc4e.png">
either we can use the suggestion or if you have anything better and more understandable term we can use, you can send a draft PR for review. 

```kotlin
it.onActivity {
        setUpTestFragment(it)
}

it.onActivity { homeFragmentTestActivity ->
        setUpTestFragment(homeFragmentTestActivity)
}
```

**Comment by ravi9607** [comment]
I want to work on "WelcomeViewModelTest"

**Comment by ravi9607** [comment]
I want to work on "WelcomeViewModelTest"

**Comment by jonathanalvares9009** [comment]
I would like to work on PromotedStoryViewModelTest. Can I start with it?

**Comment by anandwana001** [comment]
Closing this issue as all four test files are fixed.
