### ISSUE TITLE
Introduce Configuration File for Issue Template

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2863]
**Is your feature request related to a problem? Please describe.**
GitHub by default allows having a blanked issue.

**Describe the solution you'd like**
We need to prevent the blank issue from filing.

`.github/ISSUE_TEMPLATE/config.yml`
```yml
# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false  # default: true
```

**Comment by anandwana001** [comment]
@vinitamurthi Are you in favour of this or any thoughts on this?

**Comment by vinitamurthi** [comment]
I like this idea!

**Comment by nlok5923** [comment]
@anandwana001 sir i would like to work on it.

**Comment by anandwana001** [comment]
Hi @nlok5923 as you had already worked on a few Good First Issues, I suggest looking for a bit harder issues. This will help you in learning and get to know more about the codebase. 

https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+milestone%3ABeta+no%3Aassignee+-label%3A%22good+first+issue%22+NOT+a11y+NOT+blocked

**Comment by HeySitam** [comment]
Sir I am new to open source and want to contribute.... May I start with this issue?

**Comment by anandwana001** [comment]
@sitamadex11 You can start here - https://github.com/oppia/oppia-android/wiki#onboarding-instructions

Update me when you are done, I will assign you this issue.

**Comment by justdvnsh** [comment]
@anandwana001 Hi. I'd like to take up this issue. I am new to this organisation. I have already read an completed the on-boarding instructions. I also have the project setup locally ready to contribute.

**Comment by BenHenning** [comment]
I don't think this is actually what we want to do @anandwana001. Not all issues will fit our templates (I actually use the blank template far more than the other ones), and disabling it will limit us. For reference, [Oppia web](https://github.com/oppia/oppia/issues/new/choose) also retains support for filing a blank issue.

**Comment by FareesHussain** [comment]
I think we need this.
When creating the issue if anyone is not willing to follow with the template they can add their own description but the labels will be added automatically based on feature or bug.

**Comment by anandwana001** [comment]
Agree with Farees, also there is one issue with the labels I see, `status: not started` even though the PR is created for that issue the label is still there.

**Comment by BenHenning** [comment]
Let's discuss this during the team meeting this week. We need a triage process to solve the label issue, I think--I don't think we should rely on the reporter to understand which labels to assign.

Also, are there specific issues that are causing us problems that lead to needing this? That context is important to ensure we're solving the problem correctly.

**Comment by anandwana001** [comment]
As per the discussion in a team meeting, we don't require this feature as we do need a blank template sometimes, I am closing this issue.
