### ISSUE TITLE
Create a BUILD.bazel file for the datetime package in the utility module

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#2866]
This task is part of the build system migration from Gradle to Bazel. 

## Prerequesites

- Make sure you are able to build Oppia using Bazel
- Follow the [Oppia Bazel Setup instructions](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions) to setup Bazel and learn the terminology.
- Read the [Gradle Bazel Migration Best Practies and FAQ](https://github.com/oppia/oppia-android/wiki/Gradle--Bazel-Migration-Best-Practices-and-FAQ) for more context and see if there's an answer there to any question you have.

## Task

1. Create a BUILD.bazel file in

`src/main/java/org/oppia/android/util/datetime/`

2. Define a single kt_android_library

This library will have the single kotlin file as its srcs dependency and will also depend on parts of the system package of the utility module.

Figure out which deps dependencies you need to add and add them. This will also include third_party dependencies. See `third_party/versions.bzl` for the full list of third_party dependencies and use the minimal set required to build this library based on the imports.

The library should also have a single file in its resource_files field

`    resource_files = ["src/main/res/values/strings.xml"],`

Run
```
bazel build :all
```
inside the directory, to verify that the libraries build.

3. Add the directory to the MIGRATED_PROD_FILES of the module's root BUILD.bazel file

4. Set the appropriate visibility of the library and add the library to the list of deps dependencies in the targets that require the library

The visibility will depend on where the library is used. See useful links below to see a list of available visibilities. Use the most restrictive and relevant one that you can.

5. Clean up any unused deps dependencies

6. Verify that the app builds

## Useful links

- [BUILD.bazel files](https://github.com/oppia/oppia-android/search?q=filename%3ABUILD.bazel&type=code)
- [Visibilities](https://github.com/oppia/oppia-android/blob/76dc13dba3ad77aecd2218a5372949d6551f12fe/BUILD.bazel)
- [third_party dependencies](https://github.com/oppia/oppia-android/blob/a70d9b016f0d77dd30c4939041f82ea02ee28d1d/third_party/versions.bzl)

**Comment by FareesHussain** [comment]
@fsharpasharp Can I work on this?

**Comment by fsharpasharp** [comment]
Of course @FareesHussain .
