### ISSUE TITLE
Create a BUILD.bazel file for the gcsresource package in the utility module

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#2879]
This task is part of the build system migration from Gradle to Bazel. 

## Prerequesites

- Make sure you are able to build Oppia using Bazel
- Follow the [Oppia Bazel Setup instructions](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions) to setup Bazel and learn the terminology.
- Read the [Gradle Bazel Migration Best Practies and FAQ](https://github.com/oppia/oppia-android/wiki/Gradle--Bazel-Migration-Best-Practices-and-FAQ) for more context and see if there's an answer there to any question you have.

## Task

1. Create a BUILD.bazel file in

`src/main/java/org/oppia/android/util/gcsresource/`

2. Rename GcsResouceAnnotations.kt to GcsResourceAnnotations.kt

3. Define the kt_android_library libraries

Based on the imports in the Kotlin files, add the required third_party dependencies to make the libraries build. Check the Useful links section for a list of third_party dependencies.

You can start with the following stub

```
load("@dagger//:workspace_defs.bzl", "dagger_rules")
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")

kt_android_library(
    name = "annotations",
    srcs = [
        "GcsResourceAnnotations.kt",
    ],
    visibility = ["//:oppia_api_visibility"],
)

kt_android_library(
    name = "prod_module",
    srcs = [
        "GcsResourceModule.kt",
    ],
    deps = [
        ":dagger",
    ],
)

dagger_rules()
```

3. Add the directory to the MIGRATED_PROD_FILES of the module's root BUILD.bazel file

4. Add the libraries to the list of deps dependencies in the targets that require the library

5. Clean up any unused deps dependencies

6. Verify that the app builds

## Useful links

- [BUILD.bazel files](https://github.com/oppia/oppia-android/search?q=filename%3ABUILD.bazel&type=code)
- [Visibilities](https://github.com/oppia/oppia-android/blob/76dc13dba3ad77aecd2218a5372949d6551f12fe/BUILD.bazel)
- [third_party dependencies](https://github.com/oppia/oppia-android/blob/a70d9b016f0d77dd30c4939041f82ea02ee28d1d/third_party/versions.bzl)

**Comment by Akshat-gour** [comment]
@fsharpasharp Assign to me

**Comment by fsharpasharp** [comment]
Thanks @Akshat-gour.

**Comment by Akshat-gour** [comment]
@fsharpasharp 
need help regarding building the app through bazel
causing this error
![1](https://user-images.githubusercontent.com/60266468/111501931-64f59a80-876b-11eb-8854-19c54e321e4d.png)
![2](https://user-images.githubusercontent.com/60266468/111501942-66bf5e00-876b-11eb-88b4-7f4d193b08fc.png)

**Comment by Akshat-gour** [comment]
**i setup every thing as asked in instruction
my .bazelrc file**
![image](https://user-images.githubusercontent.com/60266468/111502602-01b83800-876c-11eb-8730-ec6a71f51638.png)
**my .bashrc file**
![image](https://user-images.githubusercontent.com/60266468/111502818-35935d80-876c-11eb-941e-2532c158ba59.png)

**Comment by Akshat-gour** [comment]
@fsharpasharp Please help

**Comment by fsharpasharp** [comment]
I'll take a look later today. Are you on the latest version of the repository?
