### ISSUE TITLE
Create a BUILD.bazel file for the threading package in the utility module

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#2880]
This task is part of the build system migration from Gradle to Bazel. 

## Prerequesites

- Make sure you are able to build Oppia using Bazel
- Follow the [Oppia Bazel Setup instructions](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions) to setup Bazel and learn the terminology.
- Read the [Gradle Bazel Migration Best Practies and FAQ](https://github.com/oppia/oppia-android/wiki/Gradle--Bazel-Migration-Best-Practices-and-FAQ) for more context and see if there's an answer there to any question you have.

## Task

1. Create a BUILD.bazel file in

`src/main/java/org/oppia/android/util/threading/`

2. Define the kt_android_library libraries

Based on the imports in the Kotlin files, add the required third_party dependencies to make the libraries build. 

Run
```
bazel build :all
```
inside the directory, to verify that the libraries build.

Check the Useful links section for a list of third_party dependencies.

You can start with the following stub

```
load("@dagger//:workspace_defs.bzl", "dagger_rules")
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")

kt_android_library(
    name = "annotations",
    srcs = [
        "BackgroundDispatcher.kt",
        "BlockingDispatcher.kt",
    ],
    visibility = ["//:oppia_api_visibility"],
)

kt_android_library(
    name = "prod_module",
    srcs = [
        "DispatcherModule.kt",
    ],
    deps = [
        ":dagger",
    ],
)

kt_android_library(
    name = "concurrent_collections",
    srcs = [
        "ConcurrentCollections.kt",
    ],
    visibility = ["//:oppia_api_visibility"],
)

dagger_rules()
```

3. Add the directory to the MIGRATED_PROD_FILES of the module's root BUILD.bazel file

4. Add the libraries to the list of deps dependencies in the targets that require the library

5. Clean up any unused deps dependencies

6. Verify that the app builds

## Useful links

- [BUILD.bazel files](https://github.com/oppia/oppia-android/search?q=filename%3ABUILD.bazel&type=code)
- [Visibilities](https://github.com/oppia/oppia-android/blob/76dc13dba3ad77aecd2218a5372949d6551f12fe/BUILD.bazel)
- [third_party dependencies](https://github.com/oppia/oppia-android/blob/a70d9b016f0d77dd30c4939041f82ea02ee28d1d/third_party/versions.bzl)

**Comment by jonathanalvares9009** [comment]
Can you assign me this issue @fsharpasharp ?

**Comment by fsharpasharp** [comment]
Try to get https://github.com/oppia/oppia-android/pull/2919 merged first. I can assign you after that.

**Comment by yashraj-01** [comment]
@fsharpasharp can I work on this issue?

**Comment by fsharpasharp** [comment]
Thanks @yashraj-iitr. Let me know if you have any questions.

**Comment by yashraj-01** [comment]
@fsharpasharp I,m having trouble interpreting this error. Please help me to understand it.
![Screenshot from 2021-03-22 01-59-41](https://user-images.githubusercontent.com/63469151/111919988-84196280-8ab2-11eb-8adc-0a5e238bb20d.png)

**Comment by fsharpasharp** [comment]
Create a pull request to make it easier to diagnose. For this one, you need to add the annotations as a dependenc
y to prod_module.

```
    deps = [
        ":annotations",
        ":dagger",
    ],
```
