### ISSUE TITLE
Repeated line in installation section of Wiki

### ISSUE THREAD

**Issue by ArpitShukIa** [oppia/oppia-android#2896]
There is a repeated line in the [Installation](https://github.com/oppia/oppia-android/wiki#installation) section of Wiki.

![Repeated Line](https://user-images.githubusercontent.com/51705072/110962921-80316600-8377-11eb-95b7-6a640227bb8d.png)

Consider removing it.

**Comment by anandwana001** [comment]
Done, Thanks @ArpitShukIa for bringing this into light.
