### ISSUE TITLE
Create a BUILD.bazel file for the extensions package in the utility module

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#2917]
This task is part of the build system migration from Gradle to Bazel. 

## Prerequesites

- Make sure you are able to build Oppia using Bazel
- Follow the [Oppia Bazel Setup instructions](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions) to setup Bazel and learn the terminology.
- Read the [Gradle Bazel Migration Best Practies and FAQ](https://github.com/oppia/oppia-android/wiki/Gradle--Bazel-Migration-Best-Practices-and-FAQ) for more context and see if there's an answer there to any question you have.

## Task

1. Create a BUILD.bazel file in

`src/main/java/org/oppia/android/util/extensions/`

2. Define the kt_android_library library/libraries

Based on the imports in the Kotlin files, add the required third_party dependencies to make the libraries build. Check the Useful links section for a list of third_party dependencies.

You can start with the following BUILD.bazel stub

```
"""
Add a description of the package here
"""

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")

kt_android_library(
    name = "bundle_extensions",
    srcs = [
        "BundleExtensions.kt",
    ],
)

kt_android_library(
    name = "live_data_ext",
    srcs = [
        "LiveDataExt.kt",
    ],
)
```

> Note: live_data_ext might not be used anywhere.

3. Add the directory to the MIGRATED_PROD_FILES of the module's root BUILD.bazel file

4. Add the libraries to the list of deps dependencies in the targets that require the library

You will have to set the apropriate visbility. See the list of visibilities in the link below.

5. Clean up any unused deps dependencies

6. Verify that the app builds

## Useful links

- [BUILD.bazel files](https://github.com/oppia/oppia-android/search?q=filename%3ABUILD.bazel&type=code)
- [Visibilities](https://github.com/oppia/oppia-android/blob/76dc13dba3ad77aecd2218a5372949d6551f12fe/BUILD.bazel)
- [third_party dependencies](https://github.com/oppia/oppia-android/blob/a70d9b016f0d77dd30c4939041f82ea02ee28d1d/third_party/versions.bzl)

**Comment by Victor-Titan** [comment]
@fsharpasharp I'd like to work on this.

**Comment by fsharpasharp** [comment]
Sounds good to me.

**Comment by Victor-Titan** [comment]
@fsharpasharp I can't find protobuff dependencies [here](https://github.com/oppia/oppia-android/blob/a70d9b016f0d77dd30c4939041f82ea02ee28d1d/third_party/versions.bzl#L26) and they're required for the BundleExtensions.kt file. Can you suggest some source for these third party dependencies?

**Comment by FareesHussain** [comment]
@Victor-Titan You can use `//model` target as a dep here 
Reference
https://github.com/oppia/oppia-android/blob/a70d9b016f0d77dd30c4939041f82ea02ee28d1d/utility/BUILD.bazel#L22

**Comment by fsharpasharp** [comment]
That's possible, @FareesHussain, but we are also looking to remove the model library. Ideally, we want to have the dependency that only pertains to the imports

```
import com.google.protobuf.ByteString
import com.google.protobuf.InvalidProtocolBufferException
import com.google.protobuf.MessageLite
```

I think adding any proto from model as a dependency is going to work as it indirectly seems to expose those, but we'd optimally want to only depend on something that provides those three imports.

**Comment by fsharpasharp** [comment]
I think we need to add 

```com.google.protobuf:protoc:3.0.0```

and/or

```
com.google.protobuf:protoc-gen-javalite:3.0.0
```

to versions.bzl and add that as the dependency.

**Comment by FareesHussain** [comment]
@fsharpasharp I feel like the above dependencies are not going to work they are related to protoc i.e, to build the proto_library (.proto files) and what we need here is protobuf

Let me know if I'm missing something here.

@Victor-Titan try this incase the above dependencies doesn't work
```
"com.google.protobuf:protobuf-lite": "3.0.0"
```

**Comment by Victor-Titan** [comment]
> @fsharpasharp I feel like the above dependencies are not going to work they are related to protoc i.e, to build the proto_library (.proto files) and what we need here is protobuf
> 
> Let me know if I'm missing something here.
> 
> @Victor-Titan try this incase the above dependencies doesn't work
> 
> ```
> "com.google.protobuf:protobuf-lite": "3.0.0"
> ```

Ok @FareesHussain

**Comment by fsharpasharp** [comment]
> @fsharpasharp I feel like the above dependencies are not going to work they are related to protoc i.e, to build the proto_library (.proto files) and what we need here is protobuf
> 
> Let me know if I'm missing something here.
> 
> @Victor-Titan try this incase the above dependencies doesn't work
> 
> ```
> "com.google.protobuf:protobuf-lite": "3.0.0"
> ```

Yeah, that looks right. Thanks for finding the underlying dependency.

**Comment by Victor-Titan** [comment]
@fsharpasharp @FareesHussain I tried both dependencies and both gave me [this](https://gist.github.com/Victor-Titan/609c43616bc4697d071abbe9d3d5c2eb) error. I'll make a draft PR so that you can just double check if I've modified the other bazel files properly or not.

**Comment by fsharpasharp** [comment]
That look good. Now add the new library as a dependency to where it is needed.

**Comment by Victor-Titan** [comment]
I figured making the visibility public and adding the library in the utility/BUILD.bazel would make sure no error was caused because the utility file is imported everywhere.

**Comment by FareesHussain** [comment]
can you create a draft pr to avoid confusion here.
I tried using `"com.google.protobuf:protobuf-lite": "3.0.0"` it worked for me when I ran `bazel build :all`

**Comment by Victor-Titan** [comment]
I'm sorry, I found my mistake. I forgot to convert the '.' and the ':' to '_'. The app builds now. Will make a PR shortly.

**Comment by fsharpasharp** [comment]
Yes, the format of the third party dependencies is not obvious. I can update the instructions next time to include their converted names.

**Comment by Victor-Titan** [comment]
@fsharpasharp the instructions for that are given in the [third_party dependencies](https://github.com/oppia/oppia-android/blob/a70d9b016f0d77dd30c4939041f82ea02ee28d1d/third_party/versions.bzl). It was my fault for forgetting to do that.

**Comment by FareesHussain** [comment]
> Yes, the format of the third party dependencies is not obvious. I can update the instructions next time to include their converted names.

Yes, It's already mentioned here. 
https://github.com/oppia/oppia-android/blob/0a374bdde6b9d73f50ea800ebade891aa23e888e/third_party/versions.bzl#L10-L13
