### ISSUE TITLE
Modularize/organize package org.oppia.android.data.backends.gae

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#2931]

**Comment by ihrishix** [comment]
Hey there, I'm new to open source. Can you tell me what to do exactly in this ? @fsharpasharp

**Comment by fsharpasharp** [comment]
Hi @rushikeshsuryawanshi. This issue is assigned already. Please read https://github.com/oppia/oppia-android/wiki for the onboarding instructions.
