### ISSUE TITLE
Test cases are flaking in the FakeOppiaClockTest

### ISSUE THREAD

**Issue by prayutsu** [oppia/oppia-android#2947]
**Describe the bug**
The test cases `testGetCurrentCalendar_wallClockMode_returnsCalendarWithCurrentTimeMillis()` and `testGetCurrentTimeMs_wallClockMode_returnsCurrentTimeMillis ` are flaky.

Failure error - 
```
expected to be in range: (1616173019436..1616173019440)
but was                : 1616173019440

	at org.oppia.android.testing.time.FakeOppiaClockTest.isWithin(FakeOppiaClockTest.kt:262)
	at org.oppia.android.testing.time.FakeOppiaClockTest.testGetCurrentCalendar_wallClockMode_returnsCalendarWithCurrentTimeMillis(FakeOppiaClockTest.kt:194)
```

**Expected behavior**
The test cases should always pass.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
When run 100 times, the test case failed 1 time - 
![Screenshot from 2021-03-19 20-43-41](https://user-images.githubusercontent.com/54636525/111802534-1c1d1d80-88f4-11eb-8efc-fcf7cfda25cb.png)

Sometimes failing on CI checks -
![Screenshot from 2021-03-19 20-47-03](https://user-images.githubusercontent.com/54636525/111802722-54bcf700-88f4-11eb-92b9-d9f4efddc17a.png)

**Comment by anandwana001** [comment]
@prayutsu It will be helpful if you add the failure result.

**Comment by BenHenning** [comment]
Thanks for filing this @prayutsu! 1% flaky isn't too bad, but this might be an easy issue to fix. Going to try a 1000x run locally to see what the failure rate is for me.

**Comment by BenHenning** [comment]
Ah, wow it is almost exactly 1%. I also see 10/1000 runs failing. There are 2 tests that I see failing:
- testGetCurrentCalendar_wallClockMode_returnsCalendarWithCurrentTimeMillis (9/1000)
- testGetCurrentTimeMs_wallClockMode_returnsCurrentTimeMillis (1/1000)

Going to see if the first one fails when run in isolation. To get a 90% repro rate, we will need to run the test 255 times (77 times is enough for 50% failure chance).

**Comment by BenHenning** [comment]
Ah, interesting. When run in isolation, testGetCurrentCalendar_wallClockMode_returnsCalendarWithCurrentTimeMillis fails 100% of the time. That almost means that the test is dependent on test order/other test state, so if it doesn't get the state it needs (e.g. out of order or run on its own) it fails.

testGetCurrentTimeMs_wallClockMode_returnsCurrentTimeMillis failed 4/10 times when run in isolation, so this is probably systemic in the suite.

**Comment by BenHenning** [comment]
After auditing the class, I'm fairly certain these will be the only tests that cause issues since they're the ones dealing with real system time.

**Comment by BenHenning** [comment]
My best guess: if either of the tests are the first to run in the suite they will fail due to extra delay when loading Robolectric dependencies (e.g. when calling into the system clock) which causes a bigger delay than the test expects (4ms).

**Comment by BenHenning** [comment]
Based on the above, I think we can just increase the delay by a lot (e.g. to ~100ms) and that should provide a lot more safety in running the test. Note that it may also be the case that this test flakes more often in slower environments, but given how tight the time range is it still may not be that noticeable.

**Comment by prayutsu** [comment]
> My best guess: if either of the tests are the first to run in the suite they will fail due to extra delay when loading Robolectric dependencies (e.g. when calling into the system clock) which causes a bigger delay than the test expects (4ms).

Yes, I got the same behavior, the tests failed more times if run in isolation.

**Comment by prayutsu** [comment]
> Based on the above, I think we can just increase the delay by a lot (e.g. to ~100ms) and that should provide a lot more safety in running the test. Note that it may also be the case that this test flakes more often in slower environments, but given how tight the time range is it still may not be that noticeable.

I also thought on similar lines but I just thought of increasing the delay by 20 ms.

**Comment by BenHenning** [comment]
I think the main thing we need to check here is that the test _has_ a value since it's real clock time. A buffer of 100 milliseconds should be fine so long as the value is larger than what a fake value would be (as a proxy for using "correct time").

**Comment by prayutsu** [comment]
> I think the main thing we need to check here is that the test _has_ a value since it's real clock time. A buffer of 100 milliseconds should be fine so long as the value is larger than what a fake value would be (as a proxy for using "correct time").

@BenHenning Sounds good to me.

**Comment by Karanjot-singh** [comment]
I would like to work on this @prayutsu but I might need some help as I don't understand the reason for flaky tests yet

**Comment by prayutsu** [comment]
@Karanjot-singh If you carefully take a look at the assertion of the test - 
```    
assertThat(reportedTimeMs).isWithin((currentTimeMs - 2)..(currentTimeMs + 2))
```
you can see that we check that if reportedTime lies in the range [ currentTime-2, currentTime+2 ] or not, which is a very small range, although currentTime and reportedTime are initialized one after another but the difference between their actual values can vary more than that.
So, the current buffer range for the reportedTime is 4 ms, but we want to increase it to 100 ms.
Does that make sense?

**Comment by prayutsu** [comment]
Also, you should verify that the test cases are always passing by running these flaky test cases about 100 times each in isolation.
E.g - 
And you should also verify that these test cases also pass when the whole test file is run 100 times.
So, you need to attach 3 screenshots of passing test cases to your PR description.

To run the test case 100 times, you need to follow these steps - 
When you will create the test for a class or method in robolectric, you will see an option `Repeat`, you can choose N times there and set N to 100.
![Screenshot from 2021-03-24 12-44-53](https://user-images.githubusercontent.com/54636525/112269866-ef278c80-8c9e-11eb-9913-8b814473250a.png)

**Comment by Karanjot-singh** [comment]
@prayutsu Yes, That makes sense!
