### ISSUE TITLE
Lesson thumbnails are not size-to-fit

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#2962]
**Describe the bug**
Certain lesson thumbnails (which are especially evident for the new alpha lessons) are not properly fitting within their box.

**To Reproduce**
1. Load up the alpha version of the app with alpha lessons
2. Create a new profile or log into an unplayed profile
3. Notice 'What are the Place Values' thumbnail does not fit (as compared with [web](https://www.oppia.org/learn/math/place-values/story/jaimes-adventures-in-arcade))

**Expected behavior**
The thumbnail should fit as much space either vertically or horizontally that it can

**Screenshots**
App screenshot (which is wrong):
![image](https://user-images.githubusercontent.com/12983742/111924169-50ade800-8a60-11eb-9ffe-c6b2ea3695cf.png)

Web screenshot (which is correct):
![correct_web_place_values_thumbnail](https://user-images.githubusercontent.com/12983742/111924212-91a5fc80-8a60-11eb-9f3a-fef46f263171.png)

**Device**
- Device/emulator being used: Nexus 5X (real device)
- SDK version: 27

**Additional context**
I haven't yet tried to repro this with the local develop lessons which means this may not be easily reproducible for community members to investigate.

**Comment by BenHenning** [comment]
Also: note that the issue is with **story** thumbnails (which is why the web color is different--that's a chapter thumbnail). To see how the story thumbnail looks on web, see: https://www.oppia.org/learn/math/place-values.

**Comment by rt4914** [comment]
This might have been fixed but we need to verify this with Alpha content.

**Comment by rt4914** [comment]
I have checked this with alpha app on following screen and the images do fit correctly.
- Home screen-topics & promoted stories
- Recently Played screen
- Profile Chooser
- OngoingTopicList
- CompletedTopicList
- RevisionCard Tab
- StoryActivity
- ResumeLesson


Closing this now.
