### ISSUE TITLE
Typo in `versions.bzl`

### ISSUE THREAD

**Issue by prayutsu** [oppia/oppia-android#2969]
There's a typo in a comment in the versions.bzl at line number 8 - https://github.com/oppia/oppia-android/blob/75c25b8094a9a84197397cd40887a491f8118d0f/third_party/versions.bzl#L8

Solution - 
Replace "mutli" with "multi".

**Comment by pankajpoply45** [comment]
@prayutsu  I want to work on this issue

**Comment by prayutsu** [comment]
@pankajpoply45 We do not recommend taking up this issue as your first issue because it is just a simple fix. You can claim to fix a file in issue #2833 as your first issue. Also, please got through our [wiki](https://github.com/oppia/oppia-android/wiki) before contributing. 
Thanks!
