### ISSUE TITLE
Create a BUILD.bazel file for the time package in the testing module 

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#2989]
This task is part of the build system migration from Gradle to Bazel. 

## Prerequesites

- Make sure you are able to build Oppia using Bazel
- Follow the [Oppia Bazel Setup instructions](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions) to setup Bazel and learn the terminology.
- Read the [Gradle Bazel Migration Best Practies and FAQ](https://github.com/oppia/oppia-android/wiki/Gradle--Bazel-Migration-Best-Practices-and-FAQ) for more context and see if there's an answer there to any question you have.

## Task

1. Create a BUILD.bazel file in

`testing/src/main/java/org/oppia/android/testing/time`

2. Define the kt_android_library library/libraries

Based on the imports in the Kotlin files, add the required third_party dependencies to make the libraries build. Check the Useful links section for a list of third_party dependencies. You will also need to add the non third_party dependencies.

3. Remove the directory from the srcs glob in the testing library (testing/BUILD.bazel).

Create a variable to collect all the migrated packages in one place. See https://github.com/oppia/oppia-android/blob/develop/utility/BUILD.bazel for an example of this.
 
4. Add the libraries to the list of deps dependencies in the targets that require the library

You will have to set the apropriate visbility. See the list of visibilities in the link below. Since this is part of the testing module, the apropriate visibility should be oppia_testing_visibility.

5. Clean up any unused deps dependencies

6. Verify that the app builds

## Useful links

- [BUILD.bazel files](https://github.com/oppia/oppia-android/search?q=filename%3ABUILD.bazel&type=code)
- [Visibilities](https://github.com/oppia/oppia-android/blob/76dc13dba3ad77aecd2218a5372949d6551f12fe/BUILD.bazel)
- [third_party dependencies](https://github.com/oppia/oppia-android/blob/a70d9b016f0d77dd30c4939041f82ea02ee28d1d/third_party/versions.bzl)

**Comment by BenHenning** [comment]
@Victor-Titan are you actively working on this? I might need to take it over since it's blocking work I'm doing locally. (will self-assign if I get a PR out soon).

**Comment by Victor-Titan** [comment]
> @Victor-Titan are you actively working on this? I might need to take it over since it's blocking work I'm doing locally. (will self-assign if I get a PR out soon).

@BenHenning no issues, I've only just created a new branch for this issue till now. You can take over

**Comment by BenHenning** [comment]
Ack thanks!
