### ISSUE TITLE
Update ExplorationProgressControllerTest to support protos

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3007]
#2978 is adding support for loading text protos in place of JSON, and this is going to be enabled in ExplorationDataControllerTest, TopicControllerTest, and TopicListControllerTest. As part of this work, old explorations that couldn't easily be migrated were dropped (one of which is test_exp_id_0 that ExplorationProgressControllerTest heavily depends on). Since the progress controller is primarily interested in verifying an end-to-end playing experience & ensuring all interactions are working, the prototype exploration should be a suitable replacement: test_exp_id_2.

This issue is tracking migrating ExplorationProgressControllerTest over to using test_exp_id_2 & then enabling proto tests in Bazel. Note that the main test work here can be done entirely Gradle & verified in Bazel to make things easier.

**Comment by Akshat-gour** [comment]
@BenHenning i would like to work on this

**Comment by prayutsu** [comment]
@Akshat-gour Are you working on this?

**Comment by rt4914** [comment]
Considering that there is no progress on this issue for 23 days and also there is no PR. I am assigning this to @prayutsu

**Comment by BenHenning** [comment]
This is actually a really involved issue @prayutsu and I'm going to address it as part of #2985 since I need to rewrite much of ExplorationProgressControllerTest in there, anyway. Please follow up if you already dug into this--I hope not to waste any work here.
