### ISSUE TITLE
Audio Language preferences reset upon changing the display orientation

### ISSUE THREAD

**Issue by Karanjot-singh** [oppia/oppia-android#3008]
**Describe the bug**
Language preferences for audio are reset to English on changing the display orientation from portrait to landscape and vice-versa

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'Topic: Fractions'
2. Click on 'Lessons'
3. Head to "Mathew Goes to the bakery"
4. Enable audio from the top and select "Hindi" or "Hinglish"
5. Rotate the device
6. Play the audio again to observe the bug

**Expected behavior**
The audio language preference should remain the same during the lesson irrespective of the device orientation

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

Please enable audio for the video below

https://user-images.githubusercontent.com/55680995/112419759-fc518380-8d51-11eb-90e3-92c10ac4e9b2.mp4

**Device**
Oneplus6
SDK Version 29

**Additional context**

**Comment by Karanjot-singh** [comment]
@rt4914 Could you please verify if this issue is not duplicate?

**Comment by jonathanalvares9009** [comment]
Can I work on this issue?

**Comment by jonathanalvares9009** [comment]
@Karanjot-singh this bug only resets the audio to the start. It doesn't change the language. I have tested it on an emulator and also on a physical device.

**Comment by jonathanalvares9009** [comment]
@anandwana001 Can I work on this issue?

**Comment by imraghav20** [comment]
@FareesHussain I guess this issue can be solved in #2557 itself.

Currently, [this function](https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt#L82) is executed again on screen rotation and language settings are changed.

On using `onSavedInstance` method as being used in #2557 we can try saving the selected language.

**Comment by FareesHussain** [comment]
> @FareesHussain I guess this issue can be solved in #2557 itself.
> 
> Currently, [this function](https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt#L82) is executed again on screen rotation and language settings are changed.
> 
> On using `onSavedInstance` method as being used in #2557 we can try saving the selected language.

@imraghav20 Thanks for the update, if possible I would like other contributors to work on this once it is merged.
and yes this issue will be blocked on #2557 in that case.

**Comment by imraghav20** [comment]
> > @FareesHussain I guess this issue can be solved in #2557 itself.
> > Currently, [this function](https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt#L82) is executed again on screen rotation and language settings are changed.
> > On using `onSavedInstance` method as being used in #2557 we can try saving the selected language.
> 
> @imraghav20 Thanks for the update, if possible I would like other contributors to work on this once it is merged.
> and yes this issue will be blocked on #2557 in that case.

Sure @FareesHussain . Even I would love to take up this issue once your PR is merged.

**Comment by rt4914** [comment]
Closing this as it will get covered as part of #2514 and #56
