### ISSUE TITLE
Audio stops playing when the orientation of the device is changed

### ISSUE THREAD

**Issue by jonathanalvares9009** [oppia/oppia-android#3020]
**Describe the bug**
When the orientation is changed the audio stops playing. When you click on the play button it starts playing the audio from the beginning.

**To Reproduce**
1.Go to 'Topic: Fractions'
2.Click on 'Lessons'
3.Head to "Mathew Goes to the bakery"
3. Click on the audio play button
4. Rotate the phone

**Expected behavior**
The drive should keep on playing the audio and it should not play from the start.

**Device**
- Emulator being used: Pixel 2
- SDK version: 29

- Device being used: Realme 5
- SDK version: 30

**Comment by jonathanalvares9009** [comment]
@anandwana001 Can you assign me this issue? So that I can start working on it.

**Comment by anandwana001** [comment]
duplicate - https://github.com/oppia/oppia-android/issues/3008
