### ISSUE TITLE
Glide loading small image

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3031]
**Describe the bug**
Earlier, we use to load drawable using `setImageResource`. Shifting to Glide, causes a bug of smaller image size in Topic Revision Screen only

**To Reproduce**
1. Click on Fractions card on Home Screen
2. Go to Revision Tab

**Expected behavior**
| Currently | What it should be |
| -- | -- |
| ![](https://user-images.githubusercontent.com/74007627/113136221-b78d8700-9240-11eb-8211-ba594b892fe4.png) | ![](https://user-images.githubusercontent.com/74007627/113136256-c83dfd00-9240-11eb-9b67-ba498657d92a.png) |

Look into `LessonThumbnailImageView` on how to load a drawable. 

https://github.com/oppia/oppia-android/blob/1be8ccde14c25d763c10dd8902ec7f5a2fa6f99e/app/src/main/java/org/oppia/android/app/customview/LessonThumbnailImageView.kt#L86

**Additional context**
The commit which cause this bug - https://github.com/oppia/oppia-android/commit/2bcd5114eb614e06f590ec759fde4b6bf28149ce#diff-a37faf8490754f9ab5367852640b3631eea31a197d74a0d5b8dbc8a0ad5e1c6e

**How to send a Pull Request**
1. Run `TopicRevisionFragmentTest` test on Espresso
2. Add a screenshot in Pull Request description showing all the tests are passing

**Comment by jonathanalvares9009** [comment]
@anandwana001 can I work on this issue?

**Comment by isarojgupta** [comment]
@anandwana001  can I work on this issue?

**Comment by jonathanalvares9009** [comment]
@isarojgupta I'm working on it. I almost completed it

**Comment by jonathanalvares9009** [comment]
@anandwana001 two tests are failing before and after the changes

**Comment by jonathanalvares9009** [comment]
@anandwana001 but the bug has been solved
