### ISSUE TITLE
Wrong keyboard for Entering Answer

### ISSUE THREAD

**Issue by E13ctron** [oppia/oppia-android#3041]
**Describe the bug**
The type of answer to be answered is of the form x/x, but the given keyboard doesn't support.This issue happened only in this device mentioned below

**To Reproduce**
1.Open topic Fractions
2. Open Chapter 1
3. Check for the question shown in screenshot.

**Expected behavior**
A keyboard which will have "/" key should show up

**Screenshots**
![oppia-bug](https://user-images.githubusercontent.com/73783193/113584741-e0e75200-9648-11eb-81d0-5460ea0495ba.jpg)

**Device**
- Device being used : Samsung Galaxy On6
-  SDK version : 29

**Comment by MaskedCarrot** [comment]
This is a duplicate issue https://github.com/oppia/oppia-android/issues/2290

**Comment by E13ctron** [comment]
Ok, I am closing this issue @MaskedCarrot

**Comment by E13ctron** [comment]
Closed since a duplicate Issue
