### ISSUE TITLE
Create the frontend moderator dashboard for feedback reporting

### ISSUE THREAD

**Issue by jcqli** [oppia/oppia-android#3045]
Fix part of #53 
Create and implement a frontend dashboard on Oppia Web that allows moderators to triage incoming reports.
This includes viewing reports, create and viewing tickets, add associated Github issues to tickets, and archive tickets.
The dashboard also displays the aggregate report and ticket statistics.

[Dashboard product design](https://docs.google.com/document/d/1_RTzad6u4m-ZFn0VTWNddp4bc0fCYrMk-ABIVYVJ7gU/edit?ts=602dfda3&pli=1#heading=h.jf21n1ac0i1g)

**Comment by seanlip** [comment]
Closing this, it's a web issue and should be handled there. The dashboard design is being evolved and would likely be simpler than what's described here.

**Comment by BenHenning** [comment]
@seanlip is there an issue tracking this on the web side? Would be nice to have continuity here.

**Comment by seanlip** [comment]
The design for this is being redone, and it is currently going through the full PRD process. (I think our eventual plan is to go with a simpler UI here.)
