### ISSUE TITLE
Implement domain objects and services for web reports

### ISSUE THREAD

**Issue by jcqli** [oppia/oppia-android#3049]
The backend domain objects and services currently only process Android feedback reports. Web report domain objects will need to be defined and implemented in domain layer.

**Comment by seanlip** [comment]
Closing this. We'll track it on Web as needed.

**Comment by BenHenning** [comment]
Ditto here--is there an existing issue to track the work on web @seanlip?

**Comment by seanlip** [comment]
Yup, integrated into https://github.com/oppia/product-operations-team/issues/51
