### ISSUE TITLE
Create the backend controller for the moderator dashboard

### ISSUE THREAD

**Issue by jcqli** [oppia/oppia-android#3050]
Fix part of #53
Create the backend controller that received request from the frontend dashboard, makes the backend service requests, and passes the response back to the dashbaord.
[Dashboard product design](https://docs.google.com/document/d/1_RTzad6u4m-ZFn0VTWNddp4bc0fCYrMk-ABIVYVJ7gU/edit?ts=602dfda3&pli=1#heading=h.jf21n1ac0i1g)

**Comment by seanlip** [comment]
I'm closing this. Firstly, it's really a Web issue and the issue should be filed on Oppia Web instead. Secondly, we're rethinking this project, especially as we include Web use cases in it, so the final functionality of the dashboard may be different (probably simpler).
