### ISSUE TITLE
Create MIGRATED_PROD_FILES list in the domain BUILD.bazel file

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#3058]
This change will create a setup for modularizing the packages in the domain module.

See https://github.com/oppia/oppia-android/blob/develop/utility/BUILD.bazel for an example of the setup.

1. Define the list using a glob of an empty list for now.

```
MIGRATED_PROD_FILES = glob([])
```

2. Update the library to exclude these files

```python
kt_android_library(
    name = "domain",
    srcs = glob(
        ["src/main/java/org/oppia/android/domain/**/*.kt"],
        exclude = [MIGRATED_PROD_FILES, "src/main/java/org/oppia/android/domain/testing/**/*.kt"],
    ),
```

Now, whenever somone migrates a package, they can add the package to the MIGRATED_PROD_FILES glob.

**Comment by KartikeySharma** [comment]
Hi. I would like to work on this issue.

**Comment by fsharpasharp** [comment]
Thanks @KartikeySharma!

**Comment by KartikeySharma** [comment]
HI. I am actually facing some error while building the project using Bazel. I am trying to fix those, but even after following the steps mentioned in #2950 , I am not able to resolve them. I am unassigning myself so that others can contribute to this issue if they want to.

**Comment by KartikeySharma** [comment]
Hi.. I have set up my bazel properly this time and am able to build the project using it. Could you please assign it to me again?
