### ISSUE TITLE
Use Interface to call startActivity in OngoingTopicItemViewModel [Blocked on #3095]

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3069]
**Is your feature request related to a problem? Please describe.**
Currently, we are calling `startActivity` from a view model. 

**Describe the solution you'd like**
We need to call `startActivity` from view models related activity/fragment

**Additional context**
https://github.com/oppia/oppia-android/blob/77c877a298c5007ded600f42b1f3e7a82f0aa696/app/src/main/java/org/oppia/android/app/ongoingtopiclist/OngoingTopicItemViewModel.kt#L31

**Comment by Pranav-Bobde** [comment]
Which interface are you telling to use? How to do it?

**Comment by anandwana001** [comment]
Required to create a new interface

**Comment by yashbansal130** [comment]
@anandwana001 I want to work on this issue, but can you provide me with an example or reference to what it actually means and why is it important

**Comment by anandwana001** [comment]
@rt4914 Could you please confirm if this is still required?

**Comment by yashbansal130** [comment]
@anandwana001 any updates to if I can work on this one?

**Comment by anandwana001** [comment]
Let me ping Rajat over chat.

**Comment by rt4914** [comment]
No this is not required because in practice we will change this entire thing to use protos and a central file to route to different activities.
