### ISSUE TITLE
Remove context initialization in RevisionCardFragmentTest

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3089]
**Describe the bug**
In file`RevisionCardFragmentTest` context is intialising in function `setUp()` But we are also injecting it through dagger. 

**Expected behavior**
As we are injecting it through dagger, no need for initialization. 

### How to send a PR 
1. Run test file on espresso
2. Add a screenshot in the PR description showing all the test in this file are passing.

**Comment by Pranav-Bobde** [comment]
can i be assigned this issue

**Comment by rt4914** [comment]
@Pranav-Bobde I have noticed that you have signed the CLA but haven't filled the Survey form yet. Can you please fill the survey form: https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by Pranav-Bobde** [comment]
Sorry about that. Done now.

**Comment by Pranav-Bobde** [comment]
![image](https://user-images.githubusercontent.com/66965591/116228904-820e8780-a773-11eb-8c77-8e0372a73bf5.png)

Sir, how to resolve this unresolved reference error?
