### ISSUE TITLE
Remove context initialization in ExplorationActivityTest

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3090]
**Describe the bug**
In file`ExplorationActivityTest` context is intialising in function `setUp()` But we are also injecting it through dagger. 

**Expected behavior**
As we are injecting it through dagger, no need for initialization. 

### How to send a PR 
1. Run test file on espresso
2. Add a screenshot in the PR description showing all the test in this file are passing.

**Comment by sierisimo** [comment]
I can work on this, already created a fork and a branch for it!
