### ISSUE TITLE
Full UI: MultipleChoiceInteractionView [Blocked: #15, #153]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#31]
This is tracking implementing the fully polished UI version of the multiple choice interaction.

See the web frontend for details on how the multiple choice interaction works.

Mock: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/40d6cf5f-f673-42c8-af15-035f711ef6b9/PM-IN-Introduction-

## Checklist
- [ ] Radio Buttons along with text and entire background
<img width="321" alt="Screenshot 2019-11-08 at 3 50 36 PM" src="https://user-images.githubusercontent.com/9396084/68469694-af463d80-0240-11ea-8f0c-6cff75b5a8fc.png">

- [ ] Final touch up with padding, margin, animations and Accessibility Scanner test

**Comment by BenHenning** [comment]
This is blocked on #28 to introduce the general interaction architecture.

**Comment by BenHenning** [comment]
This is blocked on #15 for a full domain controller implementation and #153 for the initial structure introduction for this interaction.

**Comment by veena14cs** [comment]
This is been fixed in PR #335 .
