### ISSUE TITLE
Move buf.yml file to model package

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3106]
Move https://github.com/oppia/oppia-android/blob/develop/buf.yaml to https://github.com/oppia/oppia-android/tree/develop/model and ensure nothing gets broken in CI check.

**Comment by AkinchanKushwaha** [comment]
Hi, Can I work on this issue?

**Comment by anandwana001** [comment]
Hi @AkinchanKushwaha Start here - https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by AkinchanKushwaha** [comment]
@anandwana001 I have acknowledged the Onboarding instructions and filled the survey and signed the CLA form.

**Comment by AkinchanKushwaha** [comment]
![image](https://user-images.githubusercontent.com/66404345/119173273-ac0e4d80-ba84-11eb-8b6c-343895acab58.png)
@anandwana001 How can I fix this problem? 
I have already tried doing "invalidate and restart" and also looked it on StackOverflow but nothing worked.

**Comment by anandwana001** [comment]
clean and rebuild might help, also keep the internet connection stable thought the process. 
Also, you can discuss such errors in our gitter channel too - https://gitter.im/oppia/oppia-android

**Comment by mahendra1290** [comment]
Hi @anandwana001 can I work on this?

**Comment by yashbansal130** [comment]
@yash10019coder assign me this issue please

**Comment by anandwana001** [comment]
Closing this issue as the moving of file is no more required.
