### ISSUE TITLE
Tablet Drawer UI Difference

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3108]
**Describe the bug**
The width of Navigation drawer in tablet is different.

**To Reproduce**
1. Open the app on a tablet
2. Open navigation drawer while on Home Menu 
3. Click Help
4. Open the navigation drawer and see the drawer width is different 

**Expected behavior**
The width should be the same 

**Screenshots**
<img src="https://user-images.githubusercontent.com/25057618/115521212-94d31900-a2a8-11eb-9ce2-3f1c23d0604c.png" width="400" />  <img src="https://user-images.githubusercontent.com/25057618/115521238-98ff3680-a2a8-11eb-880c-edf895697e44.png" width="400" />

**Solution**
In all xml files which are using NavigationDrawer use a fixed width of `304dp`. Also define this as `navigation_drawer_width` in dimens value.

**Mock References**
https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/6138b324-a09c-42cd-9a23-98aec305aca4/
https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/3a43a3ce-597a-4e4b-b509-3eafd4249528/
https://xd.adobe.com/view/3dca36c2-5115-419c-b25e-0f10526b077c-6899/screen/479649d5-6aec-49f1-b4d0-f446bad0f2bb/specs/

**Device**
- emulator being used
- SDK version -  Pixel C API 28

**Comment by rt4914** [comment]
Assigning this to @UttaranDas considering a part of it is getting solved in https://github.com/oppia/oppia-android/pull/3597

**Comment by rt4914** [comment]
@UttaranDas Any updates?
