### ISSUE TITLE
Force first letter of the username to be uppercase

### ISSUE THREAD

**Issue by prayutsu** [oppia/oppia-android#3121]
When creating a new profile, we should force the name's first letter to be always uppercase.
![Screenshot_2021-04-27-11-29-32-386_org oppia android](https://user-images.githubusercontent.com/54636525/116195571-03542300-a750-11eb-9e62-a36d39fa1e31.jpg)

**Comment by BenHenning** [comment]
Note that this was found while testing alpha MR2 but is determined to not be a blocker.

**Comment by AnubhavPabby** [comment]
@prayutsu Can I work on this issue?

**Comment by prayutsu** [comment]
@BenHenning @rt4914 Is this issue available?

**Comment by rt4914** [comment]
Yes. Assigned to @AnubhavPabby

**Comment by AnubhavPabby** [comment]
@prayutsu Can we do that if the name entered by user contains lowercase for first character so can we directly convert it to uppercase on our side and then save?

**Comment by rt4914** [comment]
@prayutsu @AnubhavPabby This has been confirmed with @mschanteltc we should not force user to type first character capital as in some cases(/languages) the name can start from small character. Instead we can show the keyboard which starts the first character capital and rest all small but in this case too if user wants to change the first character to small they can do it.

**Comment by prayutsu** [comment]
@rt4914 Sounds good, thanks for the clarification.

**Comment by rt4914** [comment]
Closing this as per https://github.com/oppia/oppia-android/issues/3121#issuecomment-837898253
