### ISSUE TITLE
Modularize the parser directory of the utility module.

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#3127]
**Is your feature request related to a problem? Please describe.**
The parser directory consists of a lot of files, which makes it more difficult to organize and make into a Bazel package. It will also unblock parts of the Bazel migration with a split into packages that have no blocked dependencies.

**Describe the solution you'd like**
Create subdirectories to group up the files. e.g. image, html, svg.

**Comment by FareesHussain** [comment]
@fsharpasharp Can I work on this?

**Comment by fsharpasharp** [comment]
Sure!

**Comment by FareesHussain** [comment]
@fsharpasharp I have some confusion regarding this.

Among all files in the parser package, I've decided to split them as follows. As this brings up a lot of changes when I create a pr I thought I would confirm it first.

#### HTML
- BulletTagHandler
- ConceptCardTagHandler
- CustomBulletSpan
- CustomHtmlContentHandler
- ExplorationHtmlParserEntityType
- HtmlParser
- HtmlParserEntityTypeModule
- ImageTagHandler
- MathTagHandler
#### Image
- BitmapBlurrer
- BitmapBlurTranformation
- BlockPictureDrawable
- GlideImageLoader
- GlideImageLoaderModule
- ImageAssetFetcher
- ImageLoader
- ImageParsingAnnotations
- ImageParsingModule
- ImageTargets
- RespositoryGlideModule
- RespositoryModelLoader
- TestGlideImageLoader
- TextPictureDrawable
- UrlImageParser
#### SVG
- BlockSvgDrawableTranscoder
- ScalableVectorGraphic
- SvgBlurTransformation
- SvgDecoder
- SvgPictureDrawable
- TestSvgDrawableTranscoder

**Comment by FareesHussain** [comment]
I think we need to create a new subdirectory for glide

**Comment by fsharpasharp** [comment]
I think that looks good!
