### ISSUE TITLE
Hints are available automatically

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3128]
**Describe the bug**
In one of the alpha state, if you just wait for 60 sec it will make the hint available even without entering the first incorrect answer.

**To Reproduce**
1. Load Alpha App
2. Visit `What is a Fraction?` exploration
3. Press three times `Continue` to visit the first question.
4. Do not do anything, wait for 60 sec.
5. The hint will be available

**Expected behavior**
First hint should only be available if learner has answered incorrectly and then have either waited for 60 secs or have entered another incorrect answer. [Reference](https://github.com/oppia/oppia-android/blob/d285fe98287384119a60632e661e9bd8381125e7/app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt#L1415)

**Comment by MaskedCarrot** [comment]
@rt4914 I think this behavior is expected according to the flowchart. When the user starts an exploration they are on `no hint released state`, without any interaction they should go to `hint available` state after 60 seconds.

**Comment by rt4914** [comment]
> @rt4914 I think this behavior is expected according to the flowchart. When the user starts an exploration they are on `no hint released state`, without any interaction they should go to `hint available` state after 60 seconds.

@MaskedCarrot But I think that's the case only if there is 1 incorrect answer first. If there is no incorrect answer then there is no point in showing hint.

**Comment by FareesHussain** [comment]
@rt4914 I agree with @MaskedCarrot as it doesn't mention any interaction as per the below Documentation. 

https://github.com/oppia/oppia-android/blob/ef2920163b024db232c1a15674cb7bfc999be562/app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt#L1413-L1439

Can we close this?

**Comment by rt4914** [comment]
I will confirm this with @BenHenning . Actually you might be right and I might be confused here but lets confirm before closing it.

**Comment by rt4914** [comment]
Closing as this is the expected behaviour.
