### ISSUE TITLE
Add Profile toggle radio buttons by clicking on the complete item

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#3131]
**Describe the bug**
Make the radio button with text a clickable to toggle the radio button (Allow Download Access) in the Add Profile 

**To Reproduce**
1. Go to 'Add Profile'
2. Click on Text on the left of radio button
3. See that the radio button is not changed

**Expected behavior**
Toggle radio button by clicking on its corresponding text.
**Screenshots**

![Screenshot_2021-04-27-18-17-24-71](https://user-images.githubusercontent.com/54740946/116243846-fdc50000-a784-11eb-95bd-b5568849f73b.jpg)

**Comment by rt4914** [comment]
@FareesHussain I think this is the desired behaviour to make only `Switch` clickable and not the test. I don't think this is a bug.

**Comment by FareesHussain** [comment]
This was found in while testing alpha MR2 and I had to use the bug tracker template as per the instructions.
I will change the label now.

**Comment by AnubhavPabby** [comment]
@FareesHussain Can I work on this issue?

**Comment by rt4914** [comment]
@FareesHussain Is this issue workable? In my understanding this is not an issue and it is a desired behavior. 
@mschanteltc Can you check this issue description and confirm do we need this change or we should keep only `Switch/ToggleButton` clickable and not the text?

**Comment by rt4914** [comment]
@AnubhavPabby I have unassigned you until we finalize if its a desired change.

**Comment by FareesHussain** [comment]
> @FareesHussain Is this issue workable? In my understanding this is not an issue and it is a desired behavior.
> @mschanteltc Can you check this issue description and confirm do we need this change or we should keep only `Switch/ToggleButton` clickable and not the text?

I did confirm this issue with @BenHenning while filing these issues. will wait for @mschanteltc's approval to unblock this

**Comment by mschanteltc** [comment]
If I understand correctly, we should make the whole item clickable, meaning that if the "Allow Download Access" text and description is tapped, then the toggle will change.

**Comment by FareesHussain** [comment]
> If I understand correctly, we should make the whole item clickable, meaning that if the "Allow Download Access" text and description is tapped, then the toggle will change.

Yes

**Comment by mschanteltc** [comment]
> > If I understand correctly, we should make the whole item clickable, meaning that if the "Allow Download Access" text and description is tapped, then the toggle will change.
> 
> Yes

SGTM

**Comment by FareesHussain** [comment]
@AnubhavPabby you can take this issue now.

**Comment by rt4914** [comment]
@FareesHussain and @AnubhavPabby Actually I will have to self assign this issue as this will affect the Accessibility too.
