### ISSUE TITLE
TextInputLayout text cursor is not visible when the text is empty

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#3133]
**Describe the bug**
TextInputLayout in Create Pin, Add profile and other activities doesn't display cursor when there is no input

**To Reproduce**
1. Go to 'Add Profile in Profile Selection Activity'
2. Click on 'Administrator's Pin (TextInputLayout)'
3. See that the cursor is not displayed.

**Expected behavior**
To show the cursor when the TextInputLayout is focused.

**Video**

https://user-images.githubusercontent.com/54740946/116243261-68297080-a784-11eb-8637-4b1bae3f8f2c.mp4

**Comment by AnubhavPabby** [comment]
@FareesHussain Can I work on this issue?

**Comment by rishidyno** [comment]
@AnubhavPabby  are you still working on this issue if not @FareesHussain  please assign me this task. Also, I am a beginner so, please guide me through.

**Comment by yash10019coder** [comment]
@FareesHussain please assing this issue to me

**Comment by rawlin** [comment]
@FareesHussain  could you assign me this issue?

**Comment by rawlin** [comment]
@rt4914 Could you assign this issue to me?

**Comment by yash10019coder** [comment]
@rawlin Are you still working on this?

**Comment by rawlin** [comment]
Yes, I am. Just a minor change left to merge to PR

**Comment by yash10019coder** [comment]
Ok
