### ISSUE TITLE
AdminSettingDialogFragment doesn’t show error message when the input is empty

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#3134]
**Describe the bug**
Submit button doesn't show error message when the text in the AdminSettingDialogFragment is empty

**To Reproduce**
1. Go to a 'User profile' with pin
2. Click on 'I FORGOT MY PIN'
3. Click submit
4. No error message displayed

**Expected behavior**
Show error message describing that the input is empty

**Video**

https://user-images.githubusercontent.com/54740946/116250573-762ebf80-a78b-11eb-89b9-fc43858bd9f6.mp4

**Comment by Arnold2381** [comment]
Can i work on this?
