### ISSUE TITLE
Search in FAQs and Administrator controls doesn’t work

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#3135]
**Describe the bug**
Search in FAQ is not working

**To Reproduce**
1. Open navigation drawer
2. Click on 'Help'
3. Open FAQs
4. Click on search icon on top right
5. see that the search button doesn't work

**Expected behavior**
Opens a search functionality in the Action bar

**Comment by FareesHussain** [comment]
@mschanteltc Can you check if this is necessary now, I checked the mocks but it seems like the search functionality is not planned yet.

**Comment by mschanteltc** [comment]
Search is not available yet as a feature. We probably need to revisit this as I'm not sure what would be the most optimal way to search would be. Do you have any suggestions?

**Comment by FareesHussain** [comment]
For administrator controls, we can make it similar to any other android settings search which can search the present items or within the present times. like in the search it can display all the clickables `Edit profile`, `Download and update`, `Automatically update topics`, `App version`, `Log out` and the users within the `Edit Profiles`.

Same for FAQs too but in case we are implementing the search functionality I think we should rather add it in the `Help` section instead of the FAQs

**Comment by BenHenning** [comment]
The search icon was removed in #3736 as we're not planning to introduce search functionality for the foreseeable future.
