### ISSUE TITLE
Shift Instrumentation test written in Unit Test directory for AdministratorControlsFragmentTest

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3140]
**Describe the bug**
There are some test cases written in `src/test/java/org/oppia/android/app/testing/administratorcontrols/AdministratorControlsFragmentTest.kt` which are instrumentation test but the file exist in unit test folder. (i.e. app/src/test)

**Expected behavior**
Look for the instrumentation tests in this file and shift them to the instrumentation test directory (i.e. app/src/sharedTest). 

**Additional context**
[How to test on Espresso?](https://developer.android.com/codelabs/advanced-android-kotlin-training-testing-basics#4)

**How to send a Pull Request for this Issue**
Add screenshot showing shifted tests are passing on Espresso.

**Comment by ravi9607** [comment]
I can give it a try!

**Comment by FareesHussain** [comment]
@ravi9607 go ahead

**Comment by anandwana001** [comment]
unassigning as no further update.

**Comment by jkugsiya** [comment]
@anandwana001  Can I work on this?

**Comment by rawlin** [comment]
Hey guys, can I be assigned to this task?

**Comment by Rohit1173** [comment]
Can I work on this

**Comment by yash10019coder** [comment]
Hi @Rohit1173  assigning you this issue.

**Comment by BenHenning** [comment]
FYI: I updated the main comment to reference the relevant directories for where the Espresso tests should go to ensure there isn't any potential confusion that these tests should go under instrumentation/.
