### ISSUE TITLE
Shift Instrumentation test written in Unit Test directory for OptionsFragmentTest

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3141]
**Describe the bug**
There are some test cases written in `src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt` which are instrumentation test but the file exist in unit test folder. 

**Expected behavior**
Look for the instrumentation tests in this file and shift them to the instrumentation test directory. 

**Additional context**
[How to test on Espresso?](https://developer.android.com/codelabs/advanced-android-kotlin-training-testing-basics#4)

**How to send a Pull Request for this Issue**
Add screenshot showing shifted tests are passing on Espresso.

**Comment by Arnold2381** [comment]
I can give it a try!
