### ISSUE TITLE
No use of espresso.intent in ProfileChooserFragmentLocalTest

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3142]
**Describe the bug**
There is no use of intents in the `ProfileChooserFragmentLocalTest`. 

**Expected behavior**
Remove the use on Intents.

**Comment by Sudeep152** [comment]
Sir i want to fix this  but i never contribute in open source can u help i will fix this

**Comment by MaskedCarrot** [comment]
@Sudeep152 Take a look at https://github.com/oppia/oppia-android/wiki for the onboarding instruction.
Once you are ready, comment here so that someone can assign this issue to you.

**Comment by jkugsiya** [comment]
@anandwana001  Can I work on this?

**Comment by anandwana001** [comment]
@jkugsiya As per my suggestion, you had worked on multiple good first issues, so I suggest looking for a bit harder issues from now. This will help you in your learning and helps you grow with the codebase too. 
If you still want to work on this issue, let me know I will assign it to you.

**Comment by jkugsiya** [comment]
> @jkugsiya As per my suggestion, you had worked on multiple good first issues, so I suggest looking for a bit harder issues from now. This will help you in your learning and helps you grow with the codebase too. 
> If you still want to work on this issue, let me know I will assign it to you. 

Yes, I have worked on multiple starter issues, I'll look for some harder issues or you can suggest me some. Thanks!

**Comment by pravesh00** [comment]
Can I work on this? @anandwana001
