### ISSUE TITLE
Create a generic utility for filtering enums

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3146]
**Is your feature request related to a problem? Please describe.**
Currently, in all our enum files, we usually use similar items filtering. 

Some examples of filtering include: https://github.com/oppia/oppia-android/blob/d0c8b81566c956c6edf6a7c19c14f8c8391dd939/app/src/main/java/org/oppia/android/app/survey/surveyitemviewmodel/UserTypeItemsViewModel.kt#L146

https://github.com/oppia/oppia-android/blob/d0c8b81566c956c6edf6a7c19c14f8c8391dd939/domain/src/main/java/org/oppia/android/domain/oppialogger/analytics/PerformanceMetricsController.kt#L132

https://github.com/oppia/oppia-android/blob/d0c8b81566c956c6edf6a7c19c14f8c8391dd939/app/src/main/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentPresenter.kt#L162

**Describe the solution you'd like**
Generalize filtering which can be used by all the enum. 

**Describe alternatives you've considered**
```kt
interface EnumWithKey<T : Enum<T>, K> {
  val T.key: K
}
inline fun <reified T : Enum<T>, K> EnumWithKey<T, K>.getValue(key: K): T {
  return enumValues<T>().find { it.key == key }
    ?: throw IllegalStateException("In the enum ${T::class.java} " +
      "there should be at least one enumeration")
}
```

**Additional context**
Look here for learning purpose - https://gist.github.com/programmerr47/e1a62f912c735249c89c3f5c44b6b366#file-enum-kt

**Comment by whyash8** [comment]
I want to work on this issue.

**Comment by adhiamboperes** [comment]
@whyash8, Please feel free to put up a draft PR with a solution.

**Comment by whyash8** [comment]
Ok sir

**Comment by whyash8** [comment]
i have found a solution for  the issue and i need some guidance. please help!

**Comment by adhiamboperes** [comment]
Hi @whyash8, please let us know how we can help. What challenge are you experiencing?

**Comment by whyash8** [comment]
i made some changes in the code. Now i need help in testing the changes. Please help

**Comment by adhiamboperes** [comment]
@whyash8, could you please create a PR with the code changes so that we can better help with the required tests?

**Comment by whyash8** [comment]
Ok

**Comment by whyash8** [comment]
I am getting this  issues while pushing
 Error: Invalid or corrupt jarfile ../oppia-android-tools/ktlint
********************************
Ktlint issue found.
Please help !!

**Comment by adhiamboperes** [comment]
Hi @whyash8, go to your project folder >  oppia-android-tools > delete the ktlint file. Then on you terminal inside the project root, run `bash setup.sh` again. Should this not resolve your issue, please use the discussions tab to share more details on the issue with a screenshot of the error.

**Comment by whyash8** [comment]
Ok! thank you

**Comment by whyash8** [comment]
i made a PR . please help me to proceed further.

**Comment by whyash8** [comment]
Start of log, file at /home/yash/.cache/bazel/_bazel_yash/db52bb717a1cf633739c99ed9da2b8d8/bazel-workers/worker-8-Desugar.log ---8<---8<---
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000600000000, 8589934592, 0) failed; error='Not enough space' (errno=12)
---8<---8<--- End of log ---8<---8<---
Target //:oppia failed to build// I am getting this issue after building bazel manytimes ! please help

**Comment by adhiamboperes** [comment]
@whyash8, if facing an issue that's not related to the issue, please post under the affected PR or  discussions to avoid loss of context and cluttering the issue thread
