### ISSUE TITLE
Answer text box clears on orientation change

### ISSUE THREAD

**Issue by MaskedCarrot** [oppia/oppia-android#3155]
**Describe the bug**
In an exploration, if the user types the answer in the text box and then changes the device orientation, the answer is cleared. 

**To Reproduce**
1. Go to First Test Topic
2. Start Prototype Exploration
2. Click on continue
3. Write anything in the text box 
4. Change device orientation 
5. See error

**Expected behavior**
The answer should not be cleared on orientation change.

**Video**

https://user-images.githubusercontent.com/53645584/116810697-e5792a80-ab62-11eb-8455-49a174c7ed7b.mp4

**Device**
- Device/emulator being used Real device OnePlus 7
- SDK version 30

**Comment by anandwana001** [comment]
Duplicate - https://github.com/oppia/oppia-android/issues/1594
