### ISSUE TITLE
Bazel Build Maven Fetch Error

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3157]
**Describe the bug**
Currently, Bazel build is causing error while fetching Maven dependencies on GitHub actions as well as on local Bazel build. 

**Expected behavior**
Bazel build should fetch Maven dependencies without throwing any error.

**Additional context**
```console
ERROR: /home/runner/work/oppia-android/oppia-android/third_party/BUILD.bazel:22:17: 
//third_party:javax_inject_javax_inject depends on @maven//:javax_inject_javax_inject in 
repository @maven which failed to fetch. no such package '@maven//': Error while fetching 
artifact with coursier: Exception in thread "main" java.lang.NumberFormatException: For input string: "intot"
```

```console
ERROR: /home/runner/work/oppia-android/oppia-android/third_party/BUILD.bazel:22:17: 
//third_party:androidx_appcompat_appcompat depends on 
@maven//:androidx_appcompat_appcompat in repository @maven which failed to fetch. no such 
package '@maven//': Error while fetching artifact with coursier: Exception in thread "main" 
java.lang.NumberFormatException: For input string: "intot"
```

Digging deep
```
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_akshaynandwana/0e0a7569f455d331a530cc35527abf40/external/rules_jvm_external/coursier.bzl", line 710, column 38, in _coursier_fetch_impl
                dep_tree = make_coursier_dep_tree(
        File "/private/var/tmp/_bazel_akshaynandwana/0e0a7569f455d331a530cc35527abf40/external/rules_jvm_external/coursier.bzl", line 649, column 13, in make_coursier_dep_tree
                fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Exception in thread "main" java.lang.NumberFormatException: For input string: "intot"
```

`/private/var/tmp/_bazel_akshaynandwana/0e0a7569f455d331a530cc35527abf40/external/rules_jvm_external/coursier.bzl`
```
exec_result = repository_ctx.execute(
        cmd,
        timeout = timeout,
        environment = environment,
        quiet = not _is_verbose(repository_ctx))
    if (exec_result.return_code != 0):
        fail("Error while fetching artifact with coursier: " + exec_result.stderr)
```

**Comment by anandwana001** [comment]
@fsharpasharp Are you also facing this issue?

**Comment by fsharpasharp** [comment]
I am also facing this issue @anandwana001.

**Comment by BenHenning** [comment]
Given that Bazel mostly guarantees a deterministic build graph, my best initial guess is that something change on the Maven repo's side that's causing our maven_install rule to fail. Unfortunately, it seems that no one has reported this yet or I'm having difficulty tracking down an issue number for it.

**Comment by BenHenning** [comment]
Hmm still not sure why this is a new issue, but it appears to be a bug with Coursier (which rules_jvm uses underneath): #1972. Need to find a version of rules_jvm to upgrade to to get that fix.

**Comment by anandwana001** [comment]
Right now, my bazel running on below, it might work. 

```json
"rules_jvm": {
        "sha": "f04b1466a00a2845106801e0c5cec96841f49ea4e7d1df88dc8e4bf31523df74",
        "version": "2.7",
    },
```

```Bazel
maven_install(
    artifacts = DAGGER_ARTIFACTS + get_maven_dependencies(),
    fetch_sources = True,
    repositories = DAGGER_REPOSITORIES + [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
```

**update**
The above config, not giving me the fetch error. Trying on the original rules_jvm version, skipping `"https://bintray.com/bintray/jcenter",` and ` "https://maven.fabric.io/public",` from maven_install `repositories`.

**Comment by BenHenning** [comment]
Hmm--I thought we needed jcenter for some of our dependencies per #2923. We should be also migrating Gradle off of jcenter to avoid disparity between the two (especially since some dependencies will need to be migrated to make this work).

**Comment by anandwana001** [comment]
Checking on the list of all the dependencies for which we need JCenter:
1. https://github.com/ChaosLeung/PinView#mavencentral
2. ...
3. ...

**Comment by anandwana001** [comment]
Bintray is no more a repository source in rules jvm - https://github.com/bazelbuild/rules_jvm_external/issues/517
