### ISSUE TITLE
Button state does not change in DragAndDrop

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3160]
**Describe the bug**

**To Reproduce**
1. Start Accessibility Scanner in your mobile. [Reference](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide#using-a11y-scanner-in-android)
2. Open `Prototype Exploration` from `First Test Topic`
3. Answer correctly to reach `DragAndDropInteraction` shown below
4. Select the first-item in list and drag directly to last position.
5. You will notice that the arrow-icons state has not changed.

**Expected behavior**
The `up-icon` for top item should always remain disable.
The `down-icon` for last item should always remain disable.
All in between icons should be enable.

**Screenshots**
<img src="https://user-images.githubusercontent.com/9396084/117049202-7b62b000-ad31-11eb-970f-ce8f4d03911b.png" width="250" />

**Notes**
Overall this issue explains the problem but solving this issue is a bit complicated because we have a Parent-RecyclerView which shows all the content in this screen, inside which we have another Child-RecyclerView which shows these drag and drop interaction and communicating from `StateFragment` to these two-level nested recyclerviews requires some good debugging skills.

**Comment by priyanka0906** [comment]
@rt4914 may I assign this to myself?

**Comment by rt4914** [comment]
@priyanka0906 This might become too complicated so for now I have assigned you #3169 once that is done you can work on this issue. Thanks.

**Comment by rt4914** [comment]
This is actually not an issue. If you notice the steps mentioned in issue description, the steps are for a sighted person, it means that they cannot use `DRAG` functionality and will need to rely on click/double-tap on arrows via screen-reader and therefore this issue can never arise for a valid user.
The main problem was that we were using this screen as a non-sighted person and as well as a sighted person which is incorrect.
