### ISSUE TITLE
ItemSelectionInteraction text change on selection

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3169]
**EDIT** (by @seanlip): See updated description here -- https://github.com/oppia/oppia-android/issues/3169#issuecomment-1225305069

----------------------

**Previous description**

[Mock1](https://xd.adobe.com/view/dfe8ccd4-39eb-414d-a0b2-b5674357f966-8abb/screen/722a0d0b-737d-4f07-95aa-0cfa7db06530/)

As per Mock1, by default the text is `Please select atleast one choice.`. If atleast one option is selected we hide this text and if the option is deselected then we show this text again.

Add this functionality and its relevant test.

## Expected Cases:

1. No item selected - Default Text - `Please select one or more choices.`
2. If total selection count is atleast 1 and less than allowable selections, change text to `You may select more choices.`
3. If total selection count is equal to allowable selections, change text to `No more than 4 choices may be selected.`

You can experiment similar cases on [What is a Fraction?](https://www.oppia.org/explore/umPkwp0L1M0-) . You will need to answer a lot of states before you will reach a state where you will find this interaction where you can select multiple options.

**Comment by rt4914** [comment]
@mschanteltc Can you answer the question mentioned in the issue?

**Comment by mschanteltc** [comment]
I'm thinking we should remove the "You may select more choices" altogether because it sounds awkward, and it would be contradicting to leave it there if all options were selected. 

Let's keep "Please select at least one choice" there and remove it when the user selects their first choice. If the user deselects the one selected option, the label appears again. WDYT?

**Comment by rt4914** [comment]
> I'm thinking we should remove the "You may select more choices" altogether because it sounds awkward, and it would be contradicting to leave it there if all options were selected.
> 
> Let's keep "Please select at least one choice" there and remove it when the user selects their first choice. If the user deselects the one selected option, the label appears again. WDYT?

@mschanteltc Sounds good. Will apply this. Thanks.

**Comment by anandwana001** [comment]
@priyanka0906 any update on this?

**Comment by priyanka0906** [comment]
> @priyanka0906 any update on this?

@anandwana001 not yet.

**Comment by anandwana001** [comment]
@priyanka0906 Let me know if you are still working on this, or we can unassign and look for other interesting issues.

**Comment by priyanka0906** [comment]
> @priyanka0906 Let me know if you are still working on this, or we can unassign and look for other interesting issues.

@anandwana001 I am currently not working on this.

**Comment by sanchi0204** [comment]
Can I work on this?

**Comment by rt4914** [comment]
@sanchi0204 Any updates?

**Comment by sanchi0204** [comment]
> @sanchi0204 Any updates?
Hey @rt4914, sorry for the delay, but my university exams have been preponed. Will make a PR probably within a week.

**Comment by rt4914** [comment]
Okay, in that case I will un-assign you for now and feel free to take any new issue when you are available again. Thanks and all the best.

**Comment by Rohit1173** [comment]
May I work on this

**Comment by Rohit1173** [comment]
@anandwana001 I am not able to find this screen on my mobile app, Could you pls guide me through

**Comment by anandwana001** [comment]
Steps:
1. Open Fractions card on the home screen
2. Lesson Tab
3. Expand the card
4. Start playing chapter 1 "What is Fraction?"
5. While playing this fraction chapter you will get questions where they have multiple options to select. 

This issue is not just about the 1 question but it's about all the questions which have multiple answers to select.

Let me know if this helps you or not.

**Comment by Rohit1173** [comment]
Yeah, Thanks @anandwana001

**Comment by rt4914** [comment]
This issue will get assigned to Avinash.

**Comment by darkmat13r** [comment]
@rt4914 This is Avinash. Please assign this issue to me.

**Comment by seanlip** [comment]
We changed how we display this in https://github.com/oppia/oppia-android/issues/4491 per learner/partner feedback. So, let's leave the text as-is until we get more feedback that the new version isn't suitable. /cc @BenHenning 

However I have a question. When the user selects the max number of choices, can we disable the rest? I think that's probably the only thing we need to do here.

**Comment by seanlip** [comment]
Also, @Akshatkamboj14, with this clarification, would you be comfortable working on this?

**Comment by BenHenning** [comment]
> We changed how we display this in #4491 per learner/partner feedback. So, let's leave the text as-is until we get more feedback that the new version isn't suitable. /cc @BenHenning
> 
> However I have a question. When the user selects the max number of choices, can we disable the rest? I think that's probably the only thing we need to do here.

Disabling checkboxes should indeed be possible, though we'll need to test how Talkback behaves for those checkboxes to make sure the experience is equally seamless (or we may need to refine the instructional language to accommodate both screenreader & non-screenreader users).

**Comment by Akshatkamboj14** [comment]
@seanlip yes, I am comfortable working on this.

**Comment by seanlip** [comment]
OK, thanks! Feel free to ask if any questions come up.

**Comment by Akshatkamboj14** [comment]
Hey, @seanlip I want to confirm that we need to change the default text to `"Please select all correct choices"` instead of `"Please select one or more choices."` and we need to disable the other options after selecting the max number of choices, is that all? or there are other things as well?

**Comment by seanlip** [comment]
This is correct, but the first one is done already right? See https://github.com/oppia/oppia-android/pull/4493.

**Comment by Akshatkamboj14** [comment]
Okay, @seanlip is there anything else except this?

**Comment by seanlip** [comment]
No, that's all (assuming that by "this" you mean the second thing you mentioned, i.e. disabling the other options).

**Comment by Akshatkamboj14** [comment]
Okay thanks @seanlip
