### ISSUE TITLE
Optimise reading_text_size_fragment.xml implementation

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3179]
We should shift the `reading_list_app_bar_layout` from `mobile` xml files to the `reading_text_size_activity` so that we can remove the `layout-sw600dp/reading_text_size_fragment`.

**Comment by sanchi0204** [comment]
Can I work on  this issue?

**Comment by rt4914** [comment]
@sanchi0204 Assigned. Thanks.

**Comment by rt4914** [comment]
@sanchi0204 Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by kritigupta45** [comment]
I would like to work on this issue, kindly assign it to me. @rt4914

**Comment by mukulasija** [comment]
during working on issue #3570 I also shifted the app bar layout to the reading_text_size_activity file, so can u please assign me this issue #3179 so that I can create a PR...

**Comment by bhaktideshmukh** [comment]
@rt4914 
Since there is no active PR for this issue. Can I take this up?
