### ISSUE TITLE
Use caption-with-value from <oppia-interactive-image> in RichText

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3188]
Currently `oppia-interactive-image` is used to render images in RichText.
We should use `caption-with-value` from `oppia-interactive-image` to show a caption below the image in application.

**Comment by Victor-Titan** [comment]
@rt4914 I'd like to work on this. How should I go about it?

**Comment by rt4914** [comment]
> @rt4914 I'd like to work on this. How should I go about it?

@Victor-Titan You can start with `ImageTagHandler` in utility module. It might be too hard at first but if you get stuck feel free to unassign.

**Comment by Victor-Titan** [comment]
@rt4914 I can not find `ImageTagHandler` in any kotlin files in the project. Can you please help.

**Comment by manas-yu** [comment]
Hi @adhiamboperes can i work on this, i can add the `caption-with-value` tag in the `ImageTagHandler` and its related tests.
The handler will retrieve the caption from the `caption-with-value` tag and append the caption as a new line below the image using `SpannableStringBuilder`
