### ISSUE TITLE
Create a BUILD.bazel file in each of the subdirectories of util/parser

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#3189]
**Describe the solution you'd like**
We want to make each package in util/parser a buildable unit in Bazel.

**Additional context**
There will be references between the packages, so we will have to migrate all the packages together.

**Comment by jonathanalvares9009** [comment]
![Screenshot 2021-05-13 at 2 25 32 PM](https://user-images.githubusercontent.com/74007627/118103184-402e4400-b3f7-11eb-8a17-527583d45541.png)

Hi @fsharpasharp , could you help me resolve this can't understand the error

**Comment by fsharpasharp** [comment]
Can you show me the pull request for more context?

**Comment by jonathanalvares9009** [comment]
@fsharpasharp should I make a PR with my existing code as it doesn't build?

**Comment by fsharpasharp** [comment]
> @fsharpasharp should I make a PR with my existing code as it doesn't build?

Yes, that's okay!

**Comment by jonathanalvares9009** [comment]
I'll create a new PR by Monday to solve this issue

**Comment by yash10019coder** [comment]
@fsharpasharp made a PR PTAL

**Comment by rt4914** [comment]
@yash10019coder Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.
