### ISSUE TITLE
Full UI: ItemSelectionInteractionView [Blocked: #15, #154]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#32]
This is tracking implementing the fully polished UI version of the item selection interaction.

See the web frontend for details on how the item selection interaction works. Note that when explorations are downloaded, their item selection assets also need to be downloaded (e.g. images) to ensure that these work properly offline.

Mock: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/97bc8e75-0232-4079-be1f-3e935fe73e33/TM-Q4-Checkboxes-No-Answer-
(NOTE: This mock reference is from TrainMode and not exploration but both of them will have same mocks for ItemSelection)

## Checklist
- [ ] ItemSelection
<img width="295" alt="Screenshot 2019-11-08 at 4 04 20 PM" src="https://user-images.githubusercontent.com/9396084/68470149-7eb2d380-0241-11ea-9829-ad2dd9b42b29.png">

- [ ] Final touch up with padding, margin, animations and Accessibility Scanner test

**Comment by BenHenning** [comment]
This is blocked on #28 to introduce the general interaction architecture.

**Comment by BenHenning** [comment]
This is blocked on #15 for a full domain controller implementation and #154 for the initial structure introduction for this interaction.

**Comment by veena14cs** [comment]
This is been fixed in PR #337 .
