### ISSUE TITLE
Alpha Content Error

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3202]
**Describe the bug**
One of the questions from the alpha content not accepting the correct answers. 

**To Reproduce**
1. Use Alpha Content
2. Fractions Chapter

**Expected behavior**
It should accept the correct answer. Currently, on the latest develop branch, it is accepting answer. 

**Screenshots**
<img src="https://user-images.githubusercontent.com/25057618/118759568-e57d6800-b88e-11eb-8a4d-1e01f6199132.png" width=250 height=450 />

**Device**
Pixel XL - 28

**Comment by rt4914** [comment]
Ack @anandwana001

**Comment by MohitGupta121** [comment]
Now this issue is fixed:
<img src="https://github.com/oppia/oppia-android/assets/76530270/51c964a4-ad04-4448-98a3-10eacd655479" width=250 height=450 />

Device:
Emulator: Pixel 4 - API 29
