### ISSUE TITLE
Paused activity does not get LiveData update onResume

### ISSUE THREAD

**Issue by jamesxu0** [oppia/oppia-android#322]
In ProfileActivity, ProfileChooserFragment's list of profiles does not get updated when returning to the activity when another activity updates ProfileDatabase.

**Comment by BenHenning** [comment]
FYI I'm pretty sure this issue shouldn't happen with the new CoroutineLiveData that we're using, but this needs verification from someone.

**Comment by viktoriias** [comment]
I tried reproducing this issue as described in https://github.com/oppia/oppia-android/pull/544:
> To reproduce, click the "Add Profile" button and enter the admin PIN. Enter a name and click create. The profile will not be shown in the ProfileChooserFragment. If the app is restarted the new profile will be displayed.

Newly added profile **is shown** in the ProfileChooserFragment without needing to restart the app. It is also shown after the restart.

**Comment by BenHenning** [comment]
Cool, I think that means that the replacement NotifiabelAsyncLiveData fixed this (or some other change).
