### ISSUE TITLE
Hi-Fi Pin Verification Tablet 

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3234]
Mobile Portrait : https://xd.adobe.com/view/3dca36c2-5115-419c-b25e-0f10526b077c-6899/screen/4d274b3e-c27b-438a-8c74-c0ff16134080/
Mobile Landscape : https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/327723da-a1e8-40e4-aace-9c30d663b20b/
Tablet Portrait : https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/8de829a5-fc1c-4083-b510-44c1387ed9c2/
Tablet Landscape : https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/0648610b-7d70-403c-a42e-a206be75e85f/

**Follow this guide**: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by rishidyno** [comment]
@anandwana001 can you please explain to me this issue.

**Comment by rt4914** [comment]
@rishidyno Reference: https://github.com/oppia/oppia-android/pull/3684

**Comment by rishidyno** [comment]
Do these for mobile portrait and tablet both
Change the color code of `Please enter you administration pin`
use `medium` font for `admin name`.

**Comment by rt4914** [comment]
Currently all the four UIs are focused on `fixed width` and `variable margin` concept, instead this needs to be changed for mobile -portrait to `variable width` and `fixed-margin`.

*Mobile-Portrait*
- Current: `fixed width` and `variable margin` 
- New: `variable width` and `fixed-margin`.
- Needs change

*Mobile-Landscape*
- Current: `fixed width` and `variable margin` 
- New: `fixed width` and `variable margin` 
- No change

*Tablet-Portrait*
- Current: `fixed width` and `variable margin` 
- New: `fixed width` and `variable margin` 
- No change

*Tablet-Landscape*
- Current: `fixed width` and `variable margin` 
- New: `fixed width` and `variable margin` 
- No change

**Comment by rishidyno** [comment]
As discussed assigning this to @deepanshu731.

**Comment by rt4914** [comment]
Closing this as it has been solved in https://github.com/oppia/oppia-android/pull/4355
