### ISSUE TITLE
Hi-Fi Add Profile Tablet

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3236]
Mobile - https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/62215bbd-1f4e-448e-b370-19c4a06fa814/

Tablet - https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/271b428d-7d98-40b4-b74e-f2a5266b0587/

**Follow this guide**: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by viktoriias** [comment]
@anandwana001 What needs to be done in this task? "Add profile" looks exactly like it's shown in the spec:

<img width="365" alt="Screen Shot 2021-01-06 at 12 44 00 PM" src="https://user-images.githubusercontent.com/10843277/120246629-a1427e00-c225-11eb-8d79-f6c84e39ba99.png">

**Comment by FareesHussain** [comment]
> @anandwana001 What needs to be done in this task? "Add profile" looks exactly like it's shown in the spec:
> 
> <img alt="Screen Shot 2021-01-06 at 12 44 00 PM" width="365" src="https://user-images.githubusercontent.com/10843277/120246629-a1427e00-c225-11eb-8d79-f6c84e39ba99.png">

This is fixed in https://github.com/oppia/oppia-android/pull/2124

**Comment by anandwana001** [comment]
This issue is about reducing the usage of tablet UI files.
@viktoriias Please check if we can remove the files like `sw600dp-port` or `sw600dp-land` or maybe both and achieve a similar UI or by introducing the dimension resources. 

Example PRs - https://github.com/oppia/oppia-android/pull/3209/files
https://github.com/oppia/oppia-android/pull/3207/files
