### ISSUE TITLE
Hi-Fi Admin Pin Tablet

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3238]
Mobile - https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/c3809dea-7afa-4905-9a93-ea4273459a68/

Tablet - https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/6876c089-6ee6-48d4-85bb-880be3b5ac35/

**Comment by theMr17** [comment]
Hi @adhiamboperes, I would like to work on this issue. My approach would be to add `admin_pin_activity.xml` layouts for `sw600dp-port` and `sw600dp-land`  qualifiers and create the screen according to the UI attached with the issue.

**Comment by adhiamboperes** [comment]
@seanlip I think we can close this since it's getting redesigned in the onboarding project, so the priority is really low.

**Comment by seanlip** [comment]
I agree that we can close this since the onboarding experience is being redesigned.
