### ISSUE TITLE
Hi-Fi Admin Auth Tablet

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3239]
Mobile - https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/785546bd-b160-4d9b-b5d6-53ddc1b4a80a/

Tablet - https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/f2b8acef-b71a-40c3-a4f4-e426e6be563f/

**Follow this guide**: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by ayush0402** [comment]
@rt4914 I would like to try working on this issue.

**Comment by rt4914** [comment]
@anandwana001 Can you verify what exactly is pending in this? Looks like it has been solved in develop.

**Comment by rt4914** [comment]
@ayush0402 Hi, I have assigned this to @Pranav-Bobde as he is currently working on this project along with @yash10019coder . Thanks.

**Comment by rt4914** [comment]
Closing this as it has already been solved in develop.
