### ISSUE TITLE
Hi-Fi App Version Tablet

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3240]
Mobile - https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/79e0846d-de5c-42b7-93aa-f93d4995616d/

Tablet - https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/80d1f4d6-be84-42db-ab23-9b5e1eb6e596/

**Follow this guide**: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by Pranav-Bobde** [comment]
Please assign me this issue.

**Comment by Pranav-Bobde** [comment]
Just wanted to bring to notice that while while working on this issue #3240, I came across this bug. Seems like the view from the 'Edit Profile' is still there (JUST INVISIBLE) even after selecting something else.

Here is a clip of the same bug.

https://user-images.githubusercontent.com/66965591/129770697-08919adc-ccbb-49e2-9575-99516ecdba71.mp4

**Comment by anandwana001** [comment]
@Pranav-Bobde Could you please file an issue for this bug with all the necessary details, also is this happening in the latest develop branch?

**Comment by Pranav-Bobde** [comment]
@anandwana001 Ok, can you help me in finding which fragment is that (containing list of profiles in Edit Profiles). 
Yes, in the latest develop only i tried, the mobile one is fine, this only seems to be a problem in Tablets(MULTIPANE).
