### ISSUE TITLE
Language change is not working

### ISSUE THREAD

**Issue by pravesh00** [oppia/oppia-android#3247]
**Describe the bug**
In the app, we have given language change support but it is not applying to the app.

**To Reproduce**
1. Open the app
2. Click on menu hamburger
3. Click on options and then app language
4. Select another language

**Expected behavior**
On selecting other language radio button it should apply language changes to the whole app

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

https://user-images.githubusercontent.com/64903405/119498309-1d027d80-bd83-11eb-9dbc-1d204a972bab.mp4

**Device**
- Device/emulator being used
-Realme RMX1851
- SDK version
-API level 29(Android 10)

**Comment by rt4914** [comment]
@pravesh00 This is actually not an issue as this is an entire feature which is pending. Therefore closing this issue. This also getting tracked in #52
