### ISSUE TITLE
Find a maintained replacement for CircularImageView

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3258]
The codebase currently depends on 2 different CircularImageView dependencies. One of them, https://github.com/sparrow007/CircularImageview, is no longer maintained and should be replaced with a dependency that's kept up-to-date. This will allow us to remove our custom fork of the library (which was needed per #2923 to remove the codebase's dependency on jcenter).

**Comment by anandwana001** [comment]
Rajat and I discussed about using ShapeableImageView from material design library. 
https://developer.android.com/reference/com/google/android/material/imageview/ShapeableImageView
Need to test if it goes similar with our mocks.

**Comment by BenHenning** [comment]
SGTM if that works.

**Comment by AkinchanKushwaha** [comment]
Hi, Please check out https://github.com/hdodenhof/CircleImageView. It has 13.9k stars on GitHub.

**Comment by anandwana001** [comment]
@AkinchanKushwaha Currently, we are using this library only, but we are looking forward to move to `ShapeableImageView `.

**Comment by aadityaguptaa** [comment]
Can I work on this issue?

**Comment by anandwana001** [comment]
Hi @aadityaguptaa I had assigned you this issue. 
In order to complete this issue please check the above comments and we can go for the best suitable solution.

**Comment by aadityaguptaa** [comment]
@anandwana001 thank you, I am working on this, will give you updates in a couple of days

**Comment by aadityaguptaa** [comment]
> @anandwana001 I am trying to change CircularImageView to ShapableImageView, but I am getting the error "This Feature requires ASM7" Any idea what's causing this error??
> 
> [![Screenshot-from-2021-10-20-19-28-15](https://camo.githubusercontent.com/6b59705f5ab688d36ba311a60e7c32f710be0ae889dfa4cdd8cffc10cc80fc2e/68747470733a2f2f692e6962622e636f2f594e42744d77622f53637265656e73686f742d66726f6d2d323032312d31302d32302d31392d32382d31352e706e67)](https://ibb.co/TwMHSdr)

okay nvm, I just had to rebuild the project

**Comment by rt4914** [comment]
@aadityaguptaa Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by bhaktideshmukh** [comment]
Hey @rt4914 I would like to work upon this issue.Can you please assign it to me?

**Comment by bkaur-bkj** [comment]
@bhaktideshmukh done

**Comment by dmdbilal** [comment]
Can I work on this issue ?

**Comment by Rd4dev** [comment]
Hi @BenHenning @adhiamboperes, I was wondering if there are any remaining tasks related to this issue (as it is still open) that I could assist with. The [PR #4155](https://github.com/oppia/oppia-android/pull/4155) replaced CircularImageView with ShapeableImageView, and [the review](https://github.com/oppia/oppia-android/pull/4139#pullrequestreview-870382366) suggests renaming the title to tackle a segment of #3258, considering potential future tasks associated with `ProfileProgress`, `ProfileList`, and `ProfileEdit`, but it seems like potential fixes for those are already being included.

I am reaching out to seek clarification on whether there are additional tasks or if removing the CircularImageView dependency is the only remaining aspect to address for this issue. 

Thanks

**Comment by adhiamboperes** [comment]
@Rd4dev, could you please search the codebase for usages of [CircularImageview](https://github.com/sparrow007/CircularImageview), and make note of those? If none is found, please test removing the dependency by removing from gradle and building the app(although complete removal means removing from bazel as well).

**Comment by Rd4dev** [comment]
@adhiamboperes , Sure! While a majority of occurrences were updated, a few lingering attributes tied to CircularImageView were identified and addressed in the PR #5350. I'll handle the dependency removal from Bazel in the subsequent commits.
