### ISSUE TITLE
Create a BUILD.bazel file for domain/onboarding

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#3276]
This task is part of the build system migration from Gradle to Bazel. 

## Prerequesites

- Make sure you are able to build Oppia using Bazel
- Follow the [Oppia Bazel Setup instructions](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions) to setup Bazel and learn the terminology.
- Read the [Gradle Bazel Migration Best Practies and FAQ](https://github.com/oppia/oppia-android/wiki/Gradle--Bazel-Migration-Best-Practices-and-FAQ) for more context and see if there's an answer there to any question you have.

## Task

1. Create a BUILD.bazel file in

`domain/src/main/java/org/oppia/android/domain/onboarding/`

and

`domain/src/main/java/org/oppia/android/domain/onboarding/testing`

2. Define the kt_android_library library/libraries

Based on the imports in the Kotlin files, add the required third_party dependencies to make the libraries build. Check the Useful links section for a list of third_party dependencies.  You may also need to add the non third_party dependencies.

Create libraries to separate interfaces, annotations and implementations. Often we can split a package into the libraries: api, module and interface.

3. Add the directory to the MIGRATED_PROD_FILES of the module's root BUILD.bazel file

4. Add the libraries to the list of deps dependencies in the targets that require the library

You will have to set the apropriate visbility. See the list of visibilities in the link below.

5. Clean up any unused deps dependencies

6. Verify that the app builds

## Useful links

- [BUILD.bazel files](https://github.com/oppia/oppia-android/search?q=filename%3ABUILD.bazel&type=code)
- [Visibilities](https://github.com/oppia/oppia-android/blob/76dc13dba3ad77aecd2218a5372949d6551f12fe/BUILD.bazel)
- [third_party dependencies](https://github.com/oppia/oppia-android/blob/a70d9b016f0d77dd30c4939041f82ea02ee28d1d/third_party/versions.bzl)

**Comment by rishidyno** [comment]
@JonathanAlvares if you are not working on this issue, @fsharpasharp can you assign me this issue.

**Comment by rishidyno** [comment]
I have been trying to install bazel from past many days but every time i find new issues this time the issue is 

`error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexBuilder`
`strictly requires --min-sdk-version >= 24 (blocked at current API level 13)`


![Screenshot from 2021-09-06 21-18-03](https://user-images.githubusercontent.com/78549195/132241177-10b7afaf-880c-48c1-bd41-ca0abdd76ae9.png)
@fsharpasharp please help me with the installation

**Comment by rt4914** [comment]
@rishidyno Un-assigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.
