### ISSUE TITLE
Story card does not collapse when the topic is opened from promoted topics lists

### ISSUE THREAD

**Issue by MaskedCarrot** [oppia/oppia-android#3283]
**Describe the bug**

The Story card in Topic Lessons fragment does not collapse when the topic is opened from promoted stories.

**To Reproduce**
1. Go to the "What is Fractions?" topic from the promoted stories.
2. Click on the upward-facing arrow in the Story card
3. See error

**Expected behavior**
The story card should close 

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

https://user-images.githubusercontent.com/53645584/121533646-1aa85080-ca1e-11eb-83c4-1c2ecab2a928.mp4

**Device**
- Real device Oneplus 7 
- SDK version 30

**Additional context**

**Comment by deepanshu731** [comment]
@MaskedCarrot Can I work on this issue?

**Comment by MaskedCarrot** [comment]
@rt4914 Can you please confirm this issue?

**Comment by MaskedCarrot** [comment]
@deepanshu731 in the meantime you can take a look at the onboarding instructions mentioned [here](https://github.com/oppia/oppia-android/wiki#onboarding-instructions) and make sure you sign the CLA.

**Comment by rt4914** [comment]
@MaskedCarrot Yes this is an error.

**Comment by rt4914** [comment]
@deepanshu731 Are you picking any other issue?

**Comment by deepanshu731** [comment]
@rt4914 I am new to open source, this bug may be slightly hard for me for now, so I am looking for an easy one

**Comment by rt4914** [comment]
@deepanshu731 Thanks. Can you pick one of these issues: https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee

**Comment by ayush0402** [comment]
@rt4914 Assign this please.

**Comment by rt4914** [comment]
@ayush0402 Unassiging you this as you are working on Dark Mode project.

**Comment by rt4914** [comment]
Tested this on latest `0.8-alpha` and works correctly. Closing this now.

**Comment by KolliAnitha** [comment]
Working fine in beta build 0.10-beta-5e64fae55e.
