### ISSUE TITLE
Update Wiki to include instructions for updating Maven dependencies in the repository

### ISSUE THREAD

**Issue by prayutsu** [oppia/oppia-android#3284]
The process of updating Maven dependencies will slightly be changed after #3270 is merged. Add the instructions for the same in the wiki.

**Target PR date**: 2021-06-10
**Target completion date**: 2021-06-13

**Comment by prayutsu** [comment]
@BenHenning @rt4914 I have updated the wiki page - https://github.com/oppia/oppia-android/wiki/Updating-Maven-Dependencies
PTAL.

**Comment by rt4914** [comment]
@prayutsu Suggest providing the direct link for `versions.bzl` file.

**Comment by prayutsu** [comment]
> @prayutsu Suggest providing the direct link for `versions.bzl` file.

Done.

**Comment by prayutsu** [comment]
@BenHenning Can you please also take a look and approve the changes so that I can close the issue?
