### ISSUE TITLE
Create a Kotlin script to validate the Xml files for syntax correctness

### ISSUE THREAD

**Issue by Sparsh1212** [oppia/oppia-android#3291]
We want to make sure that, all the Xml files are syntactically correct as per the Xml syntax. Introduce a script that checks all the Xml files for syntax correctness.

**Target PR date:** 2021-06-23
**Target completion date:** 2021-06-27

**Comment by anandwana001** [comment]
Keep track of https://github.com/oppia/oppia-android/issues/970#issuecomment-842465122
