### ISSUE TITLE
Create a Kotlin script to ensure the presence of KDoc for every non-private declaration.

### ISSUE THREAD

**Issue by Sparsh1212** [oppia/oppia-android#3304]
KDoc must be present for every:

- Classes
- Values/fields
- Explicit constructors
- Companion objects
- Nested classes
- Enums
- Annotations
- Interfaces
- Extension functions

Create a script which ensures the same.

**Target PR date:** 2021-07-30
**Target completion date:** 2021-08-04

**Comment by anandwana001** [comment]
Duplicate - https://github.com/oppia/oppia-android/issues/3195
