### ISSUE TITLE
Cannot change app language

### ISSUE THREAD

**Issue by isalooo** [oppia/oppia-android#3346]
**Describe the bug**
A user reports that they cannot change the app language

**To Reproduce**
Go to app language menu and select a language other than English. The options listed are English, French, Chinese and Hindi. 

**Expected behavior**
In the app language menu, the user should be able to change the language by selecting a language from the list such as Hindi. 
**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![Screenshot_20210616-203352__01](https://user-images.githubusercontent.com/82181327/122643735-6b4c3780-d109-11eb-8f1c-7b2adb761651.jpg)
![Screenshot_20210616-203347__01](https://user-images.githubusercontent.com/82181327/122643736-6c7d6480-d109-11eb-98da-dfb83cbfc6e6.jpg)

**Device**
OnePlus 6 (ONEPLUS A6000)
Android version: 10

**Additional context**
I wonder if this is because the app strings have not been translated yet. If that's the case, we should not display languages that are not yet available.

**Comment by TheSwarnim** [comment]
Hello, @isalooo I want to work on this issue, I've filled the individual form and survey form.
Please assign me, I know how to resolve this issue.

**Comment by TheSwarnim** [comment]
Hello, @isalooo I want to work on this issue. I've filled the individual form and survey form.
Please assign me. I know how to resolve it...

**Comment by isalooo** [comment]
I don't think I have permission to assign issues. 

@BenHenning, can you help?

**Comment by TheSwarnim** [comment]
Thanks, @isalooo for help,
How can I reach @BenHenning for help,
I've read the code and only need some help in code to implement it...

**Comment by rt4914** [comment]
Closing this as is not an issue instead the entire functionality is pending.

**Comment by rt4914** [comment]
> Thanks, @isalooo for help,
> How can I reach @BenHenning for help,
> I've read the code and only need some help in code to implement it...

@TheSwarnim Thanks for showing interest. Please, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.5-alpha (MR2).
