### ISSUE TITLE
Merge OppiaTestRule and AccessibilityTestRule

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3351]
Merge `OppiaTestRule` and `AccessibilityTestRule` in `OppiaTestRule`

Once done, run all test cases on Espresso and post screenshot displaying all tests are passing on Pixel 3 XL.

**Comment by vrajdesai78** [comment]
@rt4914 Can you guide me on how can I get started with this issue. Actually, I am new to testing.

**Comment by vrajdesai78** [comment]
I am getting this error while running OppiaTestRule without merging it with AccessbilityTestRule. I am using windows 11 and arctic Fox android studio
<img width="926" alt="image" src="https://user-images.githubusercontent.com/43074241/144241602-063edfd9-0b0d-47a0-8154-f71606e0b80b.png">

**Comment by rt4914** [comment]
@vrajdesai78 `OppiaTestRule` is actually not a test. Instead its a rule which we use in different test files. You cannot run it as a test.

**Comment by vrajdesai78** [comment]
Okay so how can I check that my merged test cases are passing

**Comment by yash10019coder** [comment]
@vrajdesai78 please run your test case file rather then running the test case rule

**Comment by vrajdesai78** [comment]
@yash10019coder sorry I am not getting how to run the test case file. Can you please help me out

**Comment by yash10019coder** [comment]
Hi @vrajdesai78 please make a PR for this issue.

**Comment by vrajdesai78** [comment]
<img width="926" alt="image" src="https://user-images.githubusercontent.com/43074241/148027336-c88c5d46-c409-470a-95dd-ff1d589780dd.png">
I am getting this error while building gradle.
