### ISSUE TITLE
Convert welcome.xml into single layout file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3359]
Currently `welcome.xml` has 4 different qualifier files but instead we can convert this into one single file.

Make sure that it does not affect the UI for any screen. To check this correct take before and after screenshots of home screen for `mobile-portrait`, `mobile-landscape`, `tablet-portrait`, `tablet-landscape` and they should look exactly same as before.

**Comment by rt4914** [comment]
@TheSwarnim PTAL

**Comment by TheSwarnim** [comment]
Hello @rt4914, please assign this issue to me, sir. I'm working on it...

**Comment by TheSwarnim** [comment]
Hello @prayutsu  and @rt4914 I've added a pull request, please review it.
Thanks
