### ISSUE TITLE
Arrange the list of activities in alphabetical order in ActivityComponent

### ISSUE THREAD

**Issue by yashraj-01** [oppia/oppia-android#3378]
**Describe the bug**
The list of activities are not arranged in alphabetical order.

**To Reproduce**
1. Go to `ActivityComponent.kt`
2. See that at several instances the list is not in alphabetical order.

**Expected behavior**
The list of activities should be arranged in alphabetical order.

**Additional context**
File Reference:
https://github.com/oppia/oppia-android/blob/45e0bcb34678954ff85892c0ce50c942ff69c8aa/app/src/main/java/org/oppia/android/app/activity/ActivityComponent.kt#L73-L122

**Comment by yashraj-01** [comment]
cc: @rt4914

**Comment by ayush0402** [comment]
Can I work on this? @yashraj-01

**Comment by rt4914** [comment]
@ayush0402 Assigned.
