### ISSUE TITLE
Arrange the list of fragments in alphabetical order in FragmentComponent 

### ISSUE THREAD

**Issue by yashraj-01** [oppia/oppia-android#3379]
**Describe the bug**
The list of fragments are not arranged in alphabetical order.

**To Reproduce**
1. Go to `FragmentComponent.kt`
2. See that at several instances the list is not in alphabetical order.

**Expected behavior**
The list of fragments should be arranged in alphabetical order.

**Additional context**
File Reference:
https://github.com/oppia/oppia-android/blob/090f7b192cfd71d6dd51572767eb5f28dba3d811/app/src/main/java/org/oppia/android/app/fragment/FragmentComponent.kt#L75-L118

**Comment by yashraj-01** [comment]
cc: @rt4914

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by rt4914** [comment]
Hello @RhnSharma Thanks for showing interest. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first and make sure you sign the CLA and fill the survey form after which we can assign you issues to work on.

**Comment by ayush0402** [comment]
Is this issue available to work on? @rt4914

**Comment by The-Anton** [comment]
@rt4914 Can you confirm that PR for this issue is merged or I can work on this?

**Comment by rt4914** [comment]
@The-Anton Assigned. Thanks.

**Comment by yashraj-01** [comment]
Unassigning @The-Anton due to inactivity. @rt4914 I'm assigning this to myself as I'll be fixing this in my latest PR. Thanks.
