### ISSUE TITLE
Find a way to use Optional below Build Version N

### ISSUE THREAD

**Issue by yashraj-01** [oppia/oppia-android#3383]
**Describe the bug**
Currently, the `Optional` used in the `NavigationDrawerFragmentPresenter` for checking `DeveloperOptionsStarter` works only for Build Versions greater than **N**.

**To Reproduce**
1. Go to `NavigationDrawerFragmentPresenter`
2. See TODO in `setIfDeveloperOptionsMenuItemListener` method.

**Expected behavior**
This feature should work for all Build Versions.

**Comment by yashraj-01** [comment]
cc: @rt4914 @Sarthak2601

**Comment by rt4914** [comment]
@yashraj-01 This should be on priority as it might lead to crash on lower versions for developers.

**Comment by yashraj-01** [comment]
> @yashraj-01 This should be on priority as it might lead to crash on lower versions for developers.

Okay. I can work on it as soon as I finish M2. Also, it is not crashing the app on lower versions. It's just that the Developer Options is not accessible in lower versions.

**Comment by yashraj-01** [comment]
Found a fix for this. We should use Guava's Optional instead of Java8.
