### ISSUE TITLE
Full UI: ContinueInteractionView [Blocked: #15, #156]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#34]
This is tracking implementing the fully polished UI version of the continue interaction.

See the web frontend for details on how the continue button interaction works.

Mock: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/40d6cf5f-f673-42c8-af15-035f711ef6b9/PM-IN-Introduction-

## Checklist
- [ ] Continue Button
<img width="323" alt="Screenshot 2019-11-08 at 3 49 33 PM" src="https://user-images.githubusercontent.com/9396084/68469412-20392580-0240-11ea-92ba-6f22a4cfe229.png">

- [ ] Next Button and Previous Button
<img width="328" alt="Screenshot 2019-11-08 at 3 50 42 PM" src="https://user-images.githubusercontent.com/9396084/68469418-23341600-0240-11ea-9db5-99942d2ea6da.png">

- [ ] Submit inactive/active Button
<img width="323" alt="Screenshot 2019-11-08 at 3 49 56 PM" src="https://user-images.githubusercontent.com/9396084/68469448-321ac880-0240-11ea-8a76-50c0e057e3a2.png">
<img width="328" alt="Screenshot 2019-11-08 at 3 50 10 PM" src="https://user-images.githubusercontent.com/9396084/68469449-33e48c00-0240-11ea-9ef1-86482879336c.png">

- [ ] Learn again Button
<img width="327" alt="Screenshot 2019-11-08 at 3 51 10 PM" src="https://user-images.githubusercontent.com/9396084/68469461-37781300-0240-11ea-8e79-6e79e8533483.png">

- [ ] Final touch up with padding, margin, animations and Accessibility Scanner test

**Comment by BenHenning** [comment]
This is blocked on #28 to introduce the general interaction architecture.

**Comment by BenHenning** [comment]
This is blocked on #15 for a full domain controller implementation and #156 for the initial structure introduction for this interaction.

**Comment by BenHenning** [comment]
NB: we also need to update the continue button to display the ~placeholder~ button text specified by the exploration state.

**Comment by BenHenning** [comment]
@rt4914 can you clarify what remaining work needs to be done here?

**Comment by rt4914** [comment]
The UI is ready but the final implementation depends on #377

**Comment by rt4914** [comment]
Closed via #1653
