### ISSUE TITLE
Merge administrator_controls_download_permissions_view into single xml file.

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3411]
Currently there are three versions of `administrator_controls_download_permissions_view.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by The-Anton** [comment]
@rt4914  I want to work on this issue.

**Comment by rt4914** [comment]
@The-Anton Assigned. Thanks.

**Comment by Akshatkamboj14** [comment]
@rt4914 hey I want to work on this issue but I want to know if there are any files of screen sizes in colour.xml because when I compared it's showing it has a difference between (android:background="@color/mid_grey_30") and (android:background="@color/oppia_grey_background") other than dimension

**Comment by rt4914** [comment]
@Akshatkamboj14 you can use the color which is mentioned in in portrait file.

**Comment by Akshatkamboj14** [comment]
hey @rt4914 can you assign me this?
