### ISSUE TITLE
Espresso Test failing in TopicPracticeFragmentTest

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3413]
`testTopicPracticeFragment_loadFragment_selectSubtopics_clickStartButton_skillListTransferSuccessfully` is failing

<img width="1510" alt="Screenshot 2021-07-06 at 1 08 25 AM" src="https://user-images.githubusercontent.com/9396084/124512747-c151f800-ddf6-11eb-812e-2cebd0f17dc5.png">

**Comment by yash10019coder** [comment]
@rt4914 when I try to run the above test nothing happens it neither shows test passed nor shows test failed please help 
![Screenshot from 2021-08-13 15-30-11](https://user-images.githubusercontent.com/76404817/129340717-1638e6f9-b9af-49fb-86cb-61ff36e2abd0.png)

**Comment by rt4914** [comment]
@yash10019coder Can you share an screenshot showing if other tests are passing for you?

**Comment by yash10019coder** [comment]
@rt4914 that issue is fixed now the tests are running now

**Comment by yash10019coder** [comment]
```
@Test fun abc(){
    launchTopicActivityIntent(internalProfileId, FRACTIONS_TOPIC_ID)
    clickPracticeTab()
    onView(atPositionOnView(
      recyclerViewId =R.id.topic_practice_skill_list,
      position=1,
      targetViewId=R.id.subtopic_check_box
    )).perform(click())
    scrollToPosition(5)
    onView(atPositionOnView(
      recyclerViewId =R.id.topic_practice_skill_list,
      position=5,
      targetViewId=R.id.topic_practice_start_button
    )).perform(click())
}
```
@rt4914 I have added this code and all the clicks are happening in the test it reaches to the Next Activity and then the error comes
I have also referred to [https://stackoverflow.com/questions/29786413/performexception-error-performing-single-click](url) but it didn't helped much as no soft keyboard is opening 
Still getting the same error as mentioned above in the issue
please help

**Comment by rt4914** [comment]
@anandwana001 @BenHenning Can you please look into this?

**Comment by anandwana001** [comment]
The actual error here is:

```
Caused by: androidx.test.espresso.IdlingResourceTimeoutException: Wait for [TestCoroutineDispatcherIdlingResource] to become idle timed out
at androidx.test.espresso.IdlingPolicy.handleTimeout(IdlingPolicy.java:61)
```

If you see in the emulator when running the test, it did all the steps, the `QuestionPlayerActivity` is also opening, but for idling resource, before the execution comes to intended and check the activity, the time out thing occurs and it throws `THROW_IDLE_TIMEOUT`.
