### ISSUE TITLE
Merge concept_card_fragment into single xml file.

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3424]
Currently there are three versions of `concept_card_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

For this specific issue, you might need to change the launcher activity from `SplashActivity` to `ConceptCardTestActivity` in `AndroidManifest` file.

**Comment by vrajdesai78** [comment]
I want to work on this issue
