### ISSUE TITLE
[A11y] Use alt-with-value from <oppia-noninteractive-image> in RichText

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3432]
Currently `oppia-noninteractive-image` is used to render images in RichText.
We should use its attribute `alt-with-value` as content description which will be readable by screen readers as an alternative to images.

**Comment by rt4914** [comment]
More information about this issue:
It was solved on in this PR https://github.com/oppia/oppia-android/pull/3433
but later on we identified one issue because of this PR https://github.com/oppia/oppia-android/issues/3765

In short, the code mentioned in #3433 does work well but raises the issue mentioned in #3765 .While solving this issue you can check code from #3433 for reference and make sure that it does work for #3765 also.

**Comment by TheSwarnim** [comment]
Hi @BenHenning and @rt4914, I would like to work on this issue. Please assign it to me
