### ISSUE TITLE
Investigate & document steps to perform complete Oppia Android development in a VM

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3437]
Per #3371 Bazel development support is very limited on Windows. While we know a subsystem is a viable path forward for Bazel, it introduces an awkward bifurcation where the repository lives in Windows & the user does development via Windows Android Studio, but uses Bazel within an Ubuntu subsystem.

A better alternative might be to instead set up a VM and run both Android Studio and Bazel from the same Unix-based environment. We need to investigate & document the steps to ensure this approach is viable for all aspects of Oppia Android development:
- Using git to clone & modify Oppia Android
- Running Android Studio
- Building & running tests via Gradle (in Android Studio)
- Building & running tests via Bazel (CLI)
- Deploying the app binary & tests to a real device
- Starting an emulator
- Deploying the app binary & tests to an emulator

**Comment by MohitGupta121** [comment]
@BenHenning we can say this particular issue is also part of this issue https://github.com/oppia/oppia-android/issues/2746 becuase we are now giving proper doc of Bazel for all OS ?

**Comment by seanlip** [comment]
I think that's fine and I've modified #2746 accordingly. Closing this one.
