### ISSUE TITLE
Merge admin_auth_activity.xml into single xml

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3453]
Currently there are 4 versions of `admin_auth_activity.xml` file, merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by The-Anton** [comment]
@rt4914 I can work on this!

**Comment by pravesh00** [comment]
Can I work on this?

**Comment by MaskedCarrot** [comment]
Since The-Anton has been assigned a different issue so assigning this issue @pravesh00

**Comment by rt4914** [comment]
@pravesh00 Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by addy-zero** [comment]
I'd like to work on this
