### ISSUE TITLE
Merge admin_pin_activity into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3454]
Currently there are 4 versions of `admin_pin_activity.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by The-Anton** [comment]
@rt4914 I want to work on this

**Comment by pravesh00** [comment]
@rt4914 can I work on this?

**Comment by MaskedCarrot** [comment]
Assigning this issue to @The-Anton.

**Comment by MaskedCarrot** [comment]
@pravesh00 assigning you the other issue where you commented.

**Comment by rt4914** [comment]
@The-Anton Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by ishant904** [comment]
@rt4914 I would like to work on this. Please assign it to me
