### ISSUE TITLE
Merge admin_settings_dialog.xml into and reset_pin_dialog into single file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3455]
Currently there are 2 versions of `admin_settings_dialog.xml` and `reset_pin_dialog.xml` file merge it into individual xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by iprasandeep** [comment]
Hi, @rt4914 I want to fix this issue please assign me.

**Comment by rt4914** [comment]
@prsndp Thanks for showing interest. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by iprasandeep** [comment]
@rt4914 Hi, You can assign me this issue I have filled out both forms and also I'm done with the project setup.

**Comment by rt4914** [comment]
@prsndp Assigned you #3456  once that is finished you can work on this PR.

**Comment by yash10019coder** [comment]
hi @rt4914  please assign this issue to me

**Comment by yash10019coder** [comment]
Hi , Sir I am having issues with my bazel I'm unable to build the app with
it
I have attached the screenshots of my terminal and I use ubuntu 20.04LTS

[image: image.png]

**Comment by yash10019coder** [comment]
@rt4914 @prayutsu PTAL
