### ISSUE TITLE
Merge all `adminstrator_controls_*` file into individual xml files.

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3456]
Currently there are 3 versions of each of these files:
- `administrator_controls_account_action_view`
- `administrator_controls_activity`
- `administrator_controls_app_information_view`
- `administrator_controls_fragment`
- `administrator_controls_general_view`
- `administrator_controls_profile_view`

We need to merge this different versions into individual single files. The PR should reduce 3*6 = `18 files` to `6 files`.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by iprasandeep** [comment]
Hi @rt4914 Could you assign me this issue, please? I want to fix this issue.

**Comment by The-Anton** [comment]
@rt4914 I want to work on this if you allow me! I have pushed the PR of a similar issue (#3411).

**Comment by rt4914** [comment]
> Hi @rt4914 Could you assign me this issue, please? I want to fix this issue.

@prsndp Thanks for showing interest. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by iprasandeep** [comment]
> > Hi @rt4914 Could you assign me this issue, please? I want to fix this issue.
> 
> @prsndp Thanks for showing interest. Please check out our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.
@rt4914 Hi, I have filled out both forms. Now You can assign me :)

**Comment by rt4914** [comment]
@prsndp Assigned you PR.

**Comment by anandwana001** [comment]
@prsndp 

Look for the mentioned XML files and see how could you reduce the file.
For example, if the difference between the same layout files (XML files) are only the dimension (padding/margin/etc), use the resource from the dimens.xml file of that respective res folder(layout/layout-land/sw600-port/lsw600dp-land/sw600dp). And this way, we can reduce the file. 
Look here for reference - https://developer.android.com/guide/topics/resources/providing-resources

**Comment by anandwana001** [comment]
@prsndp Check this PR for reference - https://github.com/oppia/oppia-android/pull/3273/files

In brief, if any two or more XML files have the same layout, but the only difference in dimension values like margin/padding/etc due to different types of files like layout/layout-land/sw600-port/lsw600dp-land/sw600dp, then we try to reduce on how can we get the dimension values from the resources and decrease the layout files. 

Official documentation on how to support a layout at different screen sizes - https://developer.android.com/training/multiscreen/screensizes

**Comment by rt4914** [comment]
@prsndp Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by aayushimathur6** [comment]
can you please assign me this

**Comment by rt4914** [comment]
@aayushimathur6 Assigned. Thanks.
