### ISSUE TITLE
Merge all_topics.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3459]
Currently there are 4 versions of `all_topics.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by deepanshu731** [comment]
I want to work on this issue

**Comment by anandwana001** [comment]
Hi @deepanshu731 
Any update on this issue? Are you finding any difficulty in making the Pull Request?

**Comment by deepanshu731** [comment]
@anandwana001 I have created a PR. plz review the PR
