### ISSUE TITLE
Merge app_language_fragment into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3460]
Currently there are 3 versions of `app_language_fragment.xml` file merge it into single xml file.
For merging this better shift the `toolbar` from mobile qualifier files to `app_language_activity.xml` so that the `app_language_fragment` will contain only the `RecyclerView` which can we easily used in mobile as well as tablet.

This will need changes in respective kotlin files and test files too.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by bkaur-bkj** [comment]
@rt4914 I would like to work on this issue, pls assign this to me.

**Comment by rt4914** [comment]
@bkaur-bkj Assigned. Thanks.

**Comment by bkaur-bkj** [comment]
Tried working on it but facing issues of injection and binding  in kt file, learning these concepts but unassigning it to avoid any delay in issue solving.

**Comment by aadityaguptaa** [comment]
@rt4914 can I work on this?

**Comment by rt4914** [comment]
@aadityaguptaa Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by bhaktideshmukh** [comment]
Hey @rt4914 I would like to work on this issue. Can you please assign it to me?

**Comment by yash10019coder** [comment]
Assigned to you @bhaktideshmukh thanks
