### ISSUE TITLE
Merge app_version_activity and app_version_fragment into individual xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3461]
Currently there are 2 versions of `app_version_activity.xml` file merge it into single xml file.
Currently there are 3 versions of `app_version_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by Rohit1173** [comment]
I want to work on this issue
