### ISSUE TITLE
Merge audio_language_fragment into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3462]
Currently there are 3 versions of `audio_language_fragment.xml` file merge it into single xml file.
For merging this better shift the `toolbar` from mobile qualifier files to `audio_language_activity.xml` so that the `audio_language_fragment` will contain only the `RecyclerView` which can we easily used in mobile as well as tablet.

This will need changes in respective kotlin files and test files too.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by jashasweejena** [comment]
Can I pick this up? @rt4914

**Comment by rt4914** [comment]
@jashasweejena Assigned. 
Also, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by jashasweejena** [comment]
Thanks, @rt4914 :) I have signed the CLA before as I had contributed to one issue in the past. Do I have to re-sign it?

**Comment by rt4914** [comment]
@jashasweejena Thanks. You don't need to sign it again.

**Comment by jashasweejena** [comment]
Awesome @rt4914

**Comment by jashasweejena** [comment]
Hey @rt4914,

As you have mentioned in the issue description, the toolbar has to be moved into `audio_language_activity.xml`. But I am facing an issue while moving the toolbar into the Activity. In the `AudioLanguageFragmentPresenter.kt` file, there is a click listener on the toolbar which gets a value from `LanguageSelectionViewModel`. I am pasting the piece of code below for your reference.

```
 binding.audioLanguageToolbar?.setNavigationOnClickListener {
      val message = languageSelectionViewModel.selectedLanguage.value
      val intent = Intent()
      intent.putExtra(MESSAGE_AUDIO_LANGUAGE_ARGUMENT_KEY, message)
      (fragment.activity as AudioLanguageActivity).setResult(REQUEST_CODE_AUDIO_LANGUAGE, intent)
      (fragment.activity as AudioLanguageActivity).finish()
    }
```
Now, if I move this piece of code into `AudioLanguageActivityPresenter`, it requires me to execute this line       
`val message = languageSelectionViewModel.selectedLanguage.value` which has a reference to the `LanguageSelectionViewModel`.
 I tried injecting the `LanguageSelectionViewModel` into `AudioLanguageActivityPresenter` but that causes an issue as `LanguageSelectionViewModel` is `@FragmentScope` while  `AudioLanguageActivityPresenter` is `@ActivityScope` which results in a compilation error. 

I was wondering if there was any way we can inject `LanguageSelectionViewModel` into `AudioLanguageActivityPresenter.kt`.

Thank You.

**Comment by rt4914** [comment]
@jashasweejena You can create a interface which will be listening for value in activity but will get used in the fragment. Whenever the value changes using that interface send that information back to activity and that way you will always have a value in the activity.

**Comment by jashasweejena** [comment]
Hey @rt4914, do you want me to pass an interface's instance (callback function) to the fragment from the activity, and when the value of `languageSelectionViewModel.selectedLanguage` changes, we call the callback method on the passed instance from the fragment so that it notifies the activity of the change?

**Comment by jashasweejena** [comment]
@rt4914, I think I found another solution to the problem. I was just going through the code and I found this piece of code being called in **AudioLanguageFragmentPresenter**

 ```
 private fun updateAudioLanguage(audioLanguage: String) {
    // The first branch of (when) will be used in the case of multipane
    when (val parentActivity = fragment.activity) {
      is OptionsActivity ->
        parentActivity.optionActivityPresenter.updateAudioLanguage(audioLanguage)
      is AudioLanguageActivity ->
        parentActivity.audioLanguageActivityPresenter.setLanguageSelected(audioLanguage)
    }
  }
```
Clearly, in the second condition in the above _when_ block, the language is getting set in the **AudioLanguageActivityPresenter**. 

Hence, I don't think there is any need for callback interfaces/getting references to the **LanguageSelectionViewModel** as we have the data we need, readily available in **AudioLanguageActivityPresenter**. 
I tried using that data and the app seems to work fine as of now. I will test some more use-cases and push the code if everything seems fine.

Thanks a lot for the help on the issue :)

**Comment by rt4914** [comment]
@jashasweejena That's really great. I think you can create a PR for this. Thanks.

**Comment by jashasweejena** [comment]
@rt4914 Thanks a lot. I will release a PR shortly.

**Comment by jashasweejena** [comment]
Hey @rt4914, I just created a PR for this issue. https://github.com/oppia/oppia-android/pull/3997. Please review the same :)
