### ISSUE TITLE
Merge coming_soon_topic_list into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3463]
Currently there are 4 versions of `coming_soon_topic_list.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by deepanshu731** [comment]
I want to work in this issue

**Comment by deepanshu731** [comment]
@rt4914 I cant find the use of coming_soon_topic_list.xml in oppia app ,so how will I take screenshots .Can you help me to find its usage

**Comment by rt4914** [comment]
@deepanshu731 Okay no issues. Just create a PR and I will review it directly via code.
