### ISSUE TITLE
Merge coming_soon_topic_view into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3464]
Currently there are 4 versions of `coming_soon_topic_view.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by jashasweejena** [comment]
I would like to work on this

**Comment by jashasweejena** [comment]
As mentioned in the issue description, I need to attach before and after screenshots of the concerned page. But, I am unable to find any activity/fragment where the layout `coming_soon_topic_view.xml` is used. Can someone kindly help me out with what should be done in this situation? Thank you.

**Comment by rt4914** [comment]
> As mentioned in the issue description, I need to attach before and after screenshots of the concerned page. But, I am unable to find any activity/fragment where the layout `coming_soon_topic_view.xml` is used. Can someone kindly help me out with what should be done in this situation? Thank you.

@jashasweejena For this particular issue it won't be possible. You can just create a PR without screenshots and I will check it manually. Thanks.

**Comment by jashasweejena** [comment]
@rt4914  Thanks for the headsup! Will raise an MR

**Comment by jashasweejena** [comment]
@rt4914, I have raised a PR for the issue.
