### ISSUE TITLE
Merge completed_story_* files into individual xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3465]
Currently there are 4 versions of `completed_story_item.xml` file merge it into single xml file.
Currently there are 4 versions of `completed_story_list_activity.xml` file merge it into single xml file.
Currently there are 4 versions of `completed_story_list_fragmentxml` file merge it into single xml file.

**How to find CompletedStoryList Screen**.
1. Open `Test Topic 1` -> `Lessons`
2. Finish `Prototype Exploration` and `ImageRegionSelection Exploration`.
3. Open Home Screen -> Navigation Drawer
4. Click Profile 
5. Click `1 Story Completed`
6. You will see `CompletedStoryList` screen.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by vrajdesai78** [comment]
I want to work on this issue

**Comment by vrajdesai78** [comment]
Hey @rt4914, in completed_story_item.xml file how to manage below code to merge it into single file. I have already write dimensions in dimens.xml file but don't know how to work on below code.  

![image](https://user-images.githubusercontent.com/43074241/127759990-f1bdcaa5-3786-405a-a1bc-cd476b46a42f.png)
<br>
Also I am getting below error while running completed_story in tablet portrait mode.

![image](https://user-images.githubusercontent.com/43074241/127760232-1da91e5d-0d2a-4926-859d-494df5597c29.png)

**Comment by rt4914** [comment]
@vrajdesai78 You might need to remove `topRoundedRectDrawableWithColor` if its not affecting the before/after images.

If it is affecting the UI then in this case we might need to keep atleast 2 files for this xml. One file without `topRoundedRectDrawableWithColor` and one file with `topRoundedRectDrawableWithColor`

**Comment by rt4914** [comment]
@vrajdesai78 Any updates on this?

**Comment by vrajdesai78** [comment]
@rt4914 Hey, can you help me out I am getting error which I have mentioned above even after keeping at least 2 files one for smartphone and another for tablet. Can you help me out.

**Comment by rt4914** [comment]
> @rt4914 Hey, can you help me out I am getting error which I have mentioned above even after keeping at least 2 files one for smartphone and another for tablet. Can you help me out.

@vrajdesai78 Whenever you delete any tablet xml file make sure you install the app from the device, rebuild the app and then install it. This should solve your error.
