### ISSUE TITLE
Merge faq_list_activity into single xml layout file

### ISSUE THREAD

**Issue by TheSwarnim** [oppia/oppia-android#3472]
Currently `faq_list_activity.xml` has 2 different quantifiers but we can convert this into one single file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in the `dimens.xml` file and use it accordingly.

Note: In PR, make sure you add before and after screenshots of `mobile-portrait`, `mobile-landscape`, `tablet-portrait`, and `tablet-landscape` for comparison and make sure that there is no difference between before and after UI.

**Comment by yash10019coder** [comment]
Hi @prayutsu  please assing this issue to me
