### ISSUE TITLE
Convert faq_list_fragment.xml into single xml file

### ISSUE THREAD

**Issue by TheSwarnim** [oppia/oppia-android#3473]
Currently `faq_list_fragment.xml` has 2 different quantifiers but we can convert this into one single file.

https://text-compare.com/ can be used to compare two versions of this file and for all the differences we can create variables in the `dimens.xml` file and use it accordingly.

Note: In PR, make sure you add before and after screenshots of `mobile-portrait`, `mobile-landscape`, `tablet-portrait`, and `tablet-landscape` for comparison and make sure that there is no difference between before and after UI.

**Comment by UttaranDas** [comment]
I would like to work on this.

**Comment by anandwana001** [comment]
Hi @Noobmaster-UD 
Any update on this issue? Any difficulties you are facing while working on this issue?

**Comment by rt4914** [comment]
@UttaranDas Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by shankarpriyank** [comment]
I would like to work on this issue can you please assign this to me @bkaur-bkj

**Comment by bkaur-bkj** [comment]
> I would like to work on this issue can you please assign this to me @bkaur-bkj

done

**Comment by shankarpriyank** [comment]
Hey @bkaur-bkj this issue seems a bit complex , I am  not sure if we can merge these files , there are a lot of differences , I would like to work on issue no  #3581 first

**Comment by rt4914** [comment]
This issue is already optimised. Further optimisation will only make the code less readable.
