### ISSUE TITLE
Convert faq_single_activity into single layout file

### ISSUE THREAD

**Issue by TheSwarnim** [oppia/oppia-android#3474]
Currently there are 3 versions of `faq_single_activity .xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in the `dimens.xml` file and use it accordingly.

Note: In PR, make sure you add before and after screenshots of `mobile-portrait`, `mobile-landscape`, `tablet-portrait`, and `tablet-landscape` for comparison and make sure that there is no difference between before and after UI.

**Comment by rishidyno** [comment]
Sir, i would like to work on this issue.

**Comment by anandwana001** [comment]
Hi @rishidyno 
Any update on this issue? Any difficulties you are facing while working on this issue?

**Comment by rishidyno** [comment]
@anandwana001 I have added a pull request for the same with some details.

https://github.com/oppia/oppia-android/pull/3518
