### ISSUE TITLE
Enable checkpointing once mechanism to resume exploration with checkpoints is implemented.

### ISSUE THREAD

**Issue by MaskedCarrot** [oppia/oppia-android#3479]
Checkpointing is disabled until the mechanism to resume explorations with checkpoints is implemented. 
Once resuming mechanism is complete checkpointing will have to be enabled by changing the value of the boolean shouldSavePartialProgress in the following classes:
1. TopicLessonsFragment.kt
2. RecentlyPlayedFragmentPresenter.kt
3. StoryChapterSummaryViewModel.kt

**Comment by BenHenning** [comment]
@MaskedCarrot shouldn't this be part of M2 & in your project board?

**Comment by MaskedCarrot** [comment]
added to M2 of the project.
