### ISSUE TITLE
Update GenerateMavenDependenciesList.kt to call out first co-ordinate name that should be updated to update all occurences of the license

### ISSUE THREAD

**Issue by prayutsu** [oppia/oppia-android#3486]
Currently, the `GenerateMavenDependenciesList.kt` only prints the licenses whose links have not been verified manually. It should also point to a particular coordinate that should be updated in order to update all occurrences of those licenses.

Reference Comment - https://github.com/oppia/oppia-android/pull/3434#discussion_r670979579

**Comment by BenHenning** [comment]
Also: we should output that only that one needs to be updated & then the script re-run to update the whole text proto file (we should try to be as clear as possible on instructions to avoid potential mistakes).
