### ISSUE TITLE
Required Bazel build CI check now failing for everyone

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3510]
See #3509 for initial context.

**Comment by BenHenning** [comment]
Continuing the discussion from https://github.com/oppia/oppia-android/pull/3509#issuecomment-883953562.

Given that we don't have an explicit workflow to set up the Android SDK in CI, we're probably relying on the SDK provided by GitHub. If GitHub updated to use a newer platform tools, it's likely causing this failure. We may need to set up a CI action to force a specific version (which is probably better, anyway; this change is breaking CI environment hermeticity).

**Comment by FareesHussain** [comment]
This is only reproduced when we try to build android_binary

**Comment by BenHenning** [comment]
@FareesHussain I think that's expected because only android_binary runs the dexer portion of the build pipeline.

**Comment by BenHenning** [comment]
So trying to find a way locally to determine what actually updated in GitHub's environment to break us. It seems this is caused by build tools being updated from 29.0.2 (or, at least, that's my local version) to 31.0.0. I'm guessing this means the prerelease build tools are now officially supported that include the breaking dexer changes. #3024 has more context on the reason why the build tools upgrade breaks us.

**Comment by BenHenning** [comment]
So per #3024 we have a workaround: https://github.com/oppia/oppia-android/wiki/Bazel-Setup-Instructions-for-Windows#3-installing-the-android-sdk explains how to install specific build tools versions. I'm looking for a CI-compatible way to do this since we need to be able to accept the licenses which I don't think can happen automatically.

**Comment by BenHenning** [comment]
https://stackoverflow.com/a/45782695 & https://github.com/android-actions/setup-android/blob/main/src/main.ts#L14 as references seem to demonstrate that this is possible. Sending out a PR momentarily to update all Bazel workflows to set up a hermetic SDK environment to both mitigate this issue & avoid it in the future.
