### ISSUE TITLE
Update Wiki describing End to End tests

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#3522]
Overview of End to end tests
and how to run the end to end tests

- [WIKI doc](https://docs.google.com/document/d/1Evcx_QaOT8rO4BKqrj7dcqQc_qN5Wfb8qfAPgQoTTjA/edit#heading=h.vdwdbdx2papz)
- [preview](https://github.com/FareesHussain/oppia-android/wiki/End-to-End-testing)

**Comment by FareesHussain** [comment]
[WIKI doc](https://docs.google.com/document/d/1Evcx_QaOT8rO4BKqrj7dcqQc_qN5Wfb8qfAPgQoTTjA/edit#heading=h.vdwdbdx2papz)

[preview](https://github.com/FareesHussain/oppia-android/wiki/End-to-End-testing)

**Comment by anandwana001** [comment]
Closing this issue as we had added the wiki now.
