### ISSUE TITLE
Rename concept_card dimens properly

### ISSUE THREAD

**Issue by deepanshu731** [oppia/oppia-android#3530]
In dimens.xml file, Rename all the dimens of concept card fragment, according to proper convention like
concept_card_explanation_text_marginEnd(wrong convention) -> concept_card_explanation_text_margin_end(right convention)

Note: As you change the dimens.xml file, accordingly also change the concept_card XML file

**Comment by rishidyno** [comment]
@prayutsu Please assign me this issue

**Comment by rishidyno** [comment]
@deepanshu731 assign me this issue
