### ISSUE TITLE
Merge home_activity.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3536]
Currently there are 3 versions of `home_activity.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by mukulasija** [comment]
i would like to work on this issue

**Comment by yash10019coder** [comment]
Hi @mukulasija I am assigning you this issue thanks
