### ISSUE TITLE
Merge hints_summary.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3537]
Currently there are 4 versions of `hints_summary.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

It can happen that it becomes really hard to merge all 4 files into single file, in such cases prefer code-readability over single file. Therefore it can be fine if in the end the code still contains 2 or 3 files.

**Note**: **In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.**

**Comment by arinarora18** [comment]
Can I work on this?

**Comment by arinarora18** [comment]
Also can you please elaborate merging them all in one file because as far as I know we need different layout files for different orientations.

**Comment by MaskedCarrot** [comment]
Hi @arinarora18, assigning this to you!

We have 4 XML files for hints_summary.xml. Instead of having 4 layout files, we want to have a single layout file. But these layout files may use different dimensions, so for each dimension that is different create a variable in the corresponding dimens.xml for that layout and use that variable instead.

**Comment by arinarora18** [comment]
There are some constraints like vertical and horizontal bias which effect the layout and cannot be stored in dimens.xml.
I have merged the mobile orientations in one but the tablet layouts are causing this problem.

**Comment by MaskedCarrot** [comment]
I am not sure if we should be using bias here. We have to defer to @rt4914 on this.

**Comment by rt4914** [comment]
@MaskedCarrot @arinarora18 Agreed. We should get rid of horizontal/vertical bias and try to convert everything correctly using padding/margin values only.

Also in case the bias is still needed, we can actually define bias in `dimens.xml` files. [Reference](https://stackoverflow.com/a/20120240/5860956)

**Comment by rt4914** [comment]
@arinarora18 Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by addy-zero** [comment]
Could I work on this?

**Comment by addy-zero** [comment]
@ArchitJain1201 I was already assigned to this.

**Comment by ArchitJain1201** [comment]
I am really sorry @adizcode, this issue was aligned with my issue. Can you please pick a new one?
PTAL @rt4914

**Comment by Ryggs** [comment]
Hello, id like to work on this issue

**Comment by ma-za-kpe** [comment]
Hello, id like to work on this
