### ISSUE TITLE
Merge home_fragment.xml into single xml file 

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3538]
Currently there are 4 versions of `home_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by bkaur-bkj** [comment]
@rt4914  Hello sir, please assign this issue to me I am interested to work on it

**Comment by bkaur-bkj** [comment]
This issue was solved by me in PR-https://github.com/oppia/oppia-android/pull/3737 But due to mentioning of wrong issue number this issue didn't got closed automatically. So please close this issue.

**Comment by Arjupta** [comment]
Okay no worries, keep a check on this in future. Closing this issue now.
