### ISSUE TITLE
Merge onboarding_fragment.xml into single xml file 

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3541]
Currently there are 4 versions of `onboarding_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by kemicky** [comment]
Hello Sir,
I have taken look at this , Looking at the layout, I noticed the onboarding_fragment. xml & onboarding_fragment.xml(sw600dp-port) are the same orientation and may be merge .
May you please sir assign this issue to me and let me try and see if I may succeed in merging them using text-compare.com are recommended, sir

**Comment by kemicky** [comment]
And Sir, After comparing the code with text-compare , there are a few difference in constraints, background color and onboarding_fragment.xml horizontal constraint is missing.

**Comment by rt4914** [comment]
@kemicky Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by kemicky** [comment]
Hi Rajat,
Yes sir I already filed the CLA , and I am using the wiki site  as well as
I already fixed the port , on the land.

**Comment by rt4914** [comment]
Closing this as merging files for this layout can make the code less readable.
