### ISSUE TITLE
Merge onboarding_slide_final.xml into single xml file 

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3543]
Currently there are 4 versions of `onboarding_slide_final.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by cdhiraj40** [comment]
hey @rt4914 @BenHenning, I would like to give it a try on this :)

**Comment by rt4914** [comment]
@cdhiraj40 
Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by rt4914** [comment]
Files for this layout cannot (rather should not be) be merged as the designs for all screen is different.
