### ISSUE TITLE
Merge ongoing_story_card.xml into single xml file 

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3544]
Currently there are 4 versions of `ongoing_story_card.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by Aakash1121** [comment]
@rt4914 , @yash10019coder I would like to work on this issue. Can you assign it to me?
Also, I am assigned to issue #3561 ...which needs review until that can I start this one?

**Comment by pandayed** [comment]
Can you please assign this issue to me?
I have started working on this.

**Comment by rishidyno** [comment]
Assigned this to @xpandeyed.
