### ISSUE TITLE
Merge ongoing_topic_item.xml into single xml file 

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3545]
Currently there are 4 versions of `ongoing_topic_item.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by shankarpriyank** [comment]
I would like to work on this issue, could you please assign this to me

**Comment by shankarpriyank** [comment]
Hi @rt4914, @bkaur-bkj

**Comment by bkaur-bkj** [comment]
@shankarpriyank done
