### ISSUE TITLE
Merge ongoing_topic_list_activity.xml into single xml file 

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3546]
Currently there are 2 versions of `ongoing_topic_list_activity.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by bhaktideshmukh** [comment]
Hey! @rt4914 

Please assign this xml file to me.

**Comment by bhaktideshmukh** [comment]
Here contents of layout-land/ongoing_topic_list_activity.xml and layout/ongoing_topic_list_activity.xml are identical. Hence merging layout-land/ongoing_topic_list_activity.xml with layout/ongoing_topic_list_activity.xml.

![Screenshot from 2022-01-10 16-24-06](https://user-images.githubusercontent.com/78796264/148754886-c238979b-e2c7-45cd-91a7-5dc4b8519714.png)
