### ISSUE TITLE
Merge ongoing_topic_list_fragment.xml into single xml file 

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3547]
Currently there are 4 versions of `ongoing_topic_list_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by shankarpriyank** [comment]
I would love to work on this , could you please assign this to me

**Comment by priyatanu** [comment]
@rt4914 I would like to work on this issue. Is it possible to work on this task

**Comment by rt4914** [comment]
@priyatanu Assigning you this issue.

**Comment by rt4914** [comment]
Closing this as it has already been solved.
