### ISSUE TITLE
Merge option_activity.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3549]
Currently there are 3 versions of `option_activity.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by bhaktideshmukh** [comment]
Hi @rt4914 Please assign this one as well! Thanks.

Here in option_activity.xml out of 3 versions, 2 of them are identical and third one has different layout.

**Comment by bhaktideshmukh** [comment]
This is the layout of layout-sw600dp/option_activity.xml

![Screenshot from 2022-01-09 22-39-47](https://user-images.githubusercontent.com/78796264/148692833-12152f49-28e5-4443-9706-e51e0094479c.png)

**Comment by bhaktideshmukh** [comment]
This is the layout of layout-land/option_activity.xml which is same as that of layout/option_activity.xml

![Screenshot from 2022-01-09 22-40-11](https://user-images.githubusercontent.com/78796264/148692884-c90560ca-96fc-4194-a1af-01f3e79c67d5.png)

**Comment by bhaktideshmukh** [comment]
There are 3 files with the same name, 2 of them are identical
(now merged to a single file) and the third one has a different
layout.

![Screenshot from 2022-01-09 22-43-41](https://user-images.githubusercontent.com/78796264/148693464-0582361f-4266-4dd7-b09b-9816a448c267.png)
