### ISSUE TITLE
Merge option_app_language.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3550]
Currently there are 3 versions of `option_app_language.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by bhaktideshmukh** [comment]
Hi @rt4914 Please assign this one as well! Thanks.

**Comment by rt4914** [comment]
@bhaktideshmukh Assigned.
