### ISSUE TITLE
Merge option_audio_language.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3551]
Currently there are 3 versions of `option_audio_language.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by shankarpriyank** [comment]
Hi , I would like to work on this , could you please assign this to me

**Comment by shankarpriyank** [comment]
I found out the sw600dp version of the xml fine contains this
 <variable
      name="commonViewModel"
      type="org.oppia.android.app.options.OptionControlsViewModel" />
      
      I am not much familiar with databinding but I am sure this thing can go into dimens

**Comment by shankarpriyank** [comment]
I found out that the sw600dp version of the xml contains this which is an extra variable when compared to the other 2 files 
I don't know know much about databinding but I am not sure this thing can go into dimen
`<variable
      name="commonViewModel"
      type="org.oppia.android.app.options.OptionControlsViewModel" />`

**Comment by shankarpriyank** [comment]
Hi @rt4914 , @bkaur-bkj

**Comment by bkaur-bkj** [comment]
@shankarpriyank as explained to get the PR reviewed you need to keep the assignee section updated by assigning the PR back to reviewers after your work or changes is done. You can do that by writing PTAL @name

**Comment by bkaur-bkj** [comment]
> Hi , I would like to work on this , could you please assign this to me

also to get it assigned you can tag us

**Comment by bkaur-bkj** [comment]
> 

also I think you don't need to use data binding here, you try to merge as many files as possible and create a PR then we will let you know what changes can be done
