### ISSUE TITLE
Merge option_story_text_size.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3552]
Currently there are 3 versions of `option_story_text_size.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by shubhanshu-coder** [comment]
can u pl assign this to me and pl guide how to setup

**Comment by rt4914** [comment]
> can u pl assign this to me and pl guide how to setup

@shubhanshu-coder Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by shankarpriyank** [comment]
I would like to work on this issue please assign this to me @bkaur-bkj

**Comment by bkaur-bkj** [comment]
> I would like to work on this issue please assign this to me @bkaur-bkj

done
