### ISSUE TITLE
Merge options_without_drawer_activity.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3554]
Currently there are 3 versions of `options_without_drawer_activity.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by bhaktideshmukh** [comment]
Hi @rt4914!

I want to work on this issue. Please assign it to me. 

Out of the 3 versions of options_without_drawer_activity.xml, 2 of them are identical and the third one has a very different layout.

**Comment by bhaktideshmukh** [comment]
This is layout-sw600dp/options_without_drawer_activity.xml
![Screenshot from 2022-01-09 20-35-42](https://user-images.githubusercontent.com/78796264/148688163-58d6da32-b653-487d-887b-7787f8b1c999.png)

This is the layout of layout/options_without_drawer_activity.xml which is same as layout-land/options_without_drawer_activity.xml

![Screenshot from 2022-01-09 20-34-50](https://user-images.githubusercontent.com/78796264/148688198-1bd5011a-9bdd-4294-9a26-3660790346cf.png)
