### ISSUE TITLE
Merge profile_chooser_add_view.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3556]
Currently there are 4 versions of `profile_chooser_add_view.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by shubhanshu-coder** [comment]
can u pl assign this to me and pl guide how to setup .

**Comment by ArchitJain1201** [comment]
@rt4914  Can you please assign me this issue?

**Comment by rt4914** [comment]
@ArchitJain1201 Assigning you this issue

**Comment by ArchitJain1201** [comment]
@bkaur-bkj  @rt4914 Can you please suggest how can I proceed further on this issue as 
1. layout\profile_chooser_add_view.xml has a different UI layout than the other three
2. layout-sw600dp-port/profile_chooser_add_view.xml and layout-sw600dp-land/profile_chooser_add_view.xml uses a different variable for paddingEnd and paddingStart, and can't merge the variable into one as they have different functionality and are used in other places also. ( as shown in the screenshot ) 
<img width="911" alt="image" src="https://user-images.githubusercontent.com/80871543/151587012-988606fd-1eae-447b-8092-5e61a9444444.png">
**for profile_chooser_description_margin_end_profile_not_added**
<img width="917" alt="image" src="https://user-images.githubusercontent.com/80871543/151587649-7035a572-7441-4770-9ce7-8017864eb421.png">
**for profile_chooser_add_view_parent_margin_start_profile_not_added**
<img width="938" alt="image" src="https://user-images.githubusercontent.com/80871543/151587845-bcefa9aa-2142-47b5-be2c-7fd3c06a258a.png">

**Comment by bkaur-bkj** [comment]
@rt4914 I checked out this issue but it has a lot of differences in mobile/layout as well as mobile/landscape too, even the orientation and layout components differ. PTAL

**Comment by rt4914** [comment]
yeah, that's correct. Closing this as this cannot be merged.
