### ISSUE TITLE
Merge profile_chooser_fragment.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3557]
Currently there are 4 versions of `profile_chooser_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

It can happen that it becomes really hard to merge all 4 files into single file, in such cases prefer code-readability over single file. Therefore it can be fine if in the end the code still contains 2 or 3 files.

**Note**: **In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.**

**Comment by priyatanu** [comment]
@rt4914 , I would like to work on this issue ?

**Comment by priyatanu** [comment]
@ARJUPTA , I would like to work on this issue ?

**Comment by Arjupta** [comment]
@priyatanu assigned it to you

**Comment by priyatanu** [comment]
Thank you :D

**Comment by addy-zero** [comment]
I'm interested! Is this available?

**Comment by priyatanu** [comment]
> I'm interested! Is this available?

Hi @adizcode , I am working on it.

**Comment by addy-zero** [comment]
Okay

**Comment by ShivamMadlani** [comment]
I would like to work on this issue. Plz assign it to me

**Comment by ritece** [comment]
I'm working on this! Please assign.

**Comment by rt4914** [comment]
Unassigned because of inactivity.

**Comment by mukulasija** [comment]
i would like to work on this issue

**Comment by sorinmircea** [comment]
I do want to take this task.

**Comment by seanlip** [comment]
@msorins Go for it! I've assigned you :)

**Comment by dmdbilal** [comment]
Can i work on this issue ?

**Comment by sorinmircea** [comment]
I did open: https://github.com/oppia/oppia-android/pull/4729

I do have a question regarding sw600dp-land and port files. The only difference that puzzles me is:

- ` app:layoutMarginTop="@{hasProfileEverBeenAddedValue ? @dimen/space_0dp: @dimen/profile_chooser_margin_top_profile_not_added}"`
- ` app:layoutMarginTop="@{hasProfileEverBeenAddedValue ? @dimen/profile_chooser_fragment_margin_top_profile_already_added : @dimen/profile_chooser_fragment_margin_top_profile_not_added}"`

Is there any way to merge this (@dimen/space_0dp and @dimen/profile_chooser_fragment_margin_top_profile_already_added 
 being different)  into one XML without relying on any code changes?

**Comment by BenHenning** [comment]
@dmdbilal it looks like this issue is being actively worked on, so you’ll need to find another one to work on.

**Comment by BenHenning** [comment]
> I did open: #4729
> 
> I do have a question regarding sw600dp-land and port files. The only difference that puzzles me is:
> 
> * ` app:layoutMarginTop="@{hasProfileEverBeenAddedValue ? @dimen/space_0dp: @dimen/profile_chooser_margin_top_profile_not_added}"`
> * ` app:layoutMarginTop="@{hasProfileEverBeenAddedValue ? @dimen/profile_chooser_fragment_margin_top_profile_already_added : @dimen/profile_chooser_fragment_margin_top_profile_not_added}"`
> 
> Is there any way to merge this (@dimen/space_0dp and @dimen/profile_chooser_fragment_margin_top_profile_already_added being different) into one XML without relying on any code changes?

@msorins is the difference between those two based on a qualifier (like sw600dp or land)? If so, you could make sure that profile_chooser_fragment_margin_top_profile_already_added is defined as 0 in its dimens.xml file corresponding to whichever qualifier is used the 0dp code today. Could that work?

I’m also not sure what is meant by “no code changes”—could you clarify?

**Comment by sorinmircea** [comment]
Thank you for the tip, I was able to solve this and amended the PR with another commit.

**Comment by seanlip** [comment]
Deassigning @msorins since he is no longer working on this.

**Comment by ArchitJain1201** [comment]
@seanlip I would like to work on this issue. Can you please assign it to me?

**Comment by seanlip** [comment]
@ArchitJain1201 Feel free to go ahead and raise a PR. If it looks reasonable we can assign you to this. Thanks!

**Comment by kunsistent** [comment]
Can I work on this issue? @seanlip

**Comment by seanlip** [comment]
@kunsistent My response to @ArchitJain1201 above applies here, too.

**Comment by masclot** [comment]
I created a PR, #4849, but I cannot assign it. Will it be automatically assigned or do i need to ping somebody?

**Comment by seanlip** [comment]
Ah, I assigned @rt4914 for you @masclot. In the future I think you can just say "@XXX PTAL" and Oppiabot will assign them for you. Thanks!

**Comment by chrislee115** [comment]
I'm working on this issue and making a PR

**Comment by seanlip** [comment]
Hi @masclot @chrislee115 Just a question about this -- reading the conversation above, there's a PR #4849 that's already been merged. Are there remaining tasks for this issue?

/cc @BenHenning @adhiamboperes

**Comment by seanlip** [comment]
(Also, PR #4849 says that it fixes part of the issue but doesn't really specify which part it fixes or which parts are left ... @masclot would you mind clarifying please? Thanks!)

**Comment by masclot** [comment]
I merged the two layouts for big screens. There remained two layouts for small screens which I think can be merged. I don't think it makes sense to merge the layout for big screen with the ones for small screens.

**Comment by chrislee115** [comment]
Are you referring to merging layout-sw600dp-land and layout-sw600dp-port?

**Comment by seanlip** [comment]
Per discussion with @BenHenning, closing this issue because it looks like merging these files is a bit complicated and probably not worth it.
