### ISSUE TITLE
Merge profile_edit_fragment.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3559]
Currently there are 2 versions of `profile_edit_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by mahmood199** [comment]
Can you assign this to me?

**Comment by rt4914** [comment]
@mahmood199 Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by vivaansahai** [comment]
Hello, can I work on this issue?

**Comment by rt4914** [comment]
@vivaansahai If you are still interested in this issue you can start working on it.

**Comment by vivaansahai** [comment]
@rt4914 Yes, I am still interested. Can you please assign this to me?

**Comment by ShivamMadlani** [comment]
Please assign me this issue.

**Comment by ShivamMadlani** [comment]
I would like to work on this. Please assign this to me.

**Comment by ShivamMadlani** [comment]
@yash10019coder Hello, I am getting issues in pushing my commit. The error is given in the screenshot below.
![image](https://user-images.githubusercontent.com/94903454/161028298-03b790a0-15c5-4ef0-b48a-932fc94b8ada.png)

**Comment by ShivamMadlani** [comment]
> @yash10019coder Hello, I am getting issues in pushing my commit. The error is given in the screenshot below. ![image](https://user-images.githubusercontent.com/94903454/161028298-03b790a0-15c5-4ef0-b48a-932fc94b8ada.png)

------------------I resolved the above issue.----------------------

**Comment by rt4914** [comment]
Closing this issue as over-optimisation can make code less readable here. There are currently 2 files and they are fine to keep because of strategy difference in how the layout has been created.
