### ISSUE TITLE
Merge profile_list_fragment.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3560]
Currently there are 3 versions of `profile_list_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by Rishavgupta12345** [comment]
I want to work on this issue please assign me this

**Comment by bkaur-bkj** [comment]
@Rishavgupta12345 done

**Comment by anamansari062** [comment]
@rt4914 I would like to work on this issue!

**Comment by rt4914** [comment]
@anamansari062 @anamansari062 
Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by ShivamMadlani** [comment]
Please assign me this issue.
