### ISSUE TITLE
Merge profile_picture_activity.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3562]
Currently there are 2 versions of `profile_picture_activity.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by shubhamji88** [comment]
actually, both the files are exactly the same. the portrait and the landscape one and deleting one of them to make it a single file should work fine. should I move ahead with this?
please assign this to me

**Comment by rt4914** [comment]
@shubhamji88 Yes you can remove the other file. 

Also, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by shubhamji88** [comment]
okay
