### ISSUE TITLE
Merge profile_progress_fragment.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3563]
Currently there are 4 versions of `profile_progress_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by shakivhussain** [comment]
I would like to work on this, please assign me.

**Comment by FareesHussain** [comment]
@shakivhussain are you available to pick this up?

**Comment by shubhanshu-coder** [comment]
can u assign this to me i am intersted in this .  Also pl guide me how to setup

**Comment by bhaktideshmukh** [comment]
@yash10019coder Hey! assign this to me.
