### ISSUE TITLE
Merge profile_progress_recently_played_story_card.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3565]
Currently there are 4 versions of `profile_progress_recently_played_story_card.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by shakivhussain** [comment]
I would like to work on this , please assign me.

**Comment by Arjupta** [comment]
@shakivhussain assigned it to you

**Comment by Arjupta** [comment]
@shakivhussain there were no updates from your side. If you are stuck over anything you can ask here in the comments.

**Comment by rt4914** [comment]
@shakivhussain Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by yashbansal130** [comment]
@yash10019coder can i work on this? I know how to do this now

**Comment by yashbansal130** [comment]
I cannot find the activity this xml file is inflating to verify the changes since its UI

**Comment by rt4914** [comment]
@yashbansal130 Just play through couple of explorations like `Prototype Exploration`, `What is a fraction`, etc. and after that open `Navigation Drawer`, click on profile-header, you will see a new activity and in that you will see cards at bottom which are inflating the xml mentioned in this issue.

**Comment by yashbansal130** [comment]
@rt4914 thanks for the help

**Comment by yashbansal130** [comment]
@yash10019coder after deleting rest of the layout files and adding dimens for port, land, sw600dp-land and sw600dp-port I am getting this error for tablets and the app crashes
![Screenshot from 2022-01-20 14-15-05](https://user-images.githubusercontent.com/66557534/150464608-ee956a42-f762-4fe4-a421-fa8d46b2c48f.png)

**Comment by rt4914** [comment]
@yashbansal130 Please take a look at here: https://github.com/oppia/oppia-android/wiki/Frequent-Errors-and-Solutions#crashing-layout-tags-in-tablet
