### ISSUE TITLE
Merge profile_reset_pin_activity.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3567]
Currently there are 2 versions of `profile_reset_pin_activity.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by MohitGupta121** [comment]
@rt4914 I want to work on that issue can u please assign me that also.

**Comment by MohitGupta121** [comment]
@rt4914  can you please review my PR for this issue #3942

**Comment by MohitGupta121** [comment]
@rt4914 can you please review my PR for this issue #3942

**Comment by rt4914** [comment]
@MohitGupta121 Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by MohitGupta121** [comment]
@rt4914 I resolved this issue and my PR also merged

**Comment by rt4914** [comment]
Thanks @MohitGupta121 . The issue should have been closed automatically. Nevermind, I will close it manually now.

Closing at it has been fixed in #3942
