### ISSUE TITLE
Merge recently_played_fragment.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3571]
Currently there are 4 versions of `recently_played_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by arinarora18** [comment]
I want to work on this

**Comment by rt4914** [comment]
@arinarora18 Considering you have been assigned other issues. I am assigning this to myself to unblock on other issues that I am working on. Thanks.
