### ISSUE TITLE
Merge revision_card_fragment.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3572]
Currently there are 4 versions of `revision_card_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by sanchi0204** [comment]
Can I work on this?

**Comment by sanchi0204** [comment]
@rt4914 there are 4 versions - 
revision_fragment and revision_fragment(land) vary only in case of dimensions
revision_fragment(sw600) and revision_fragment(sw00 land) have an extra linear layout against revision_fragment and revision_fragment(land)

So shall I make 2 versions ?

**Comment by rt4914** [comment]
> revision_fragment

@sanchi0204 I checked the `sw600dp-land` file and I think the two linearlayouts can be merged into a single linear layout.
The final linear layout will look like this
```
<LinearLayout
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:layout_gravity="center_horizontal"
      android:gravity="center"
      android:minWidth="640dp"
      android:orientation="vertical"
      android:paddingBottom="148dp">
```

So I think it its possible to combine all xml files into a single file. Also, if this solution does not work then also create a PR which makes sense to you so that we can suggest changes in that PR directly.

**Comment by rt4914** [comment]
@sanchi0204 Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by ArchitJain1201** [comment]
@bkaur-bkj Can you please assign me this issue?

**Comment by bkaur-bkj** [comment]
@ArchitJain1201 done

**Comment by ArchitJain1201** [comment]
@bkaur-bkj Sir, the solution I can figure out is to use two files, one that handles the large size ( such as tables ) and the other that handles medium or a small size ( phones ). Reason: the code uses two methods for UI 1. Takes margin in the text field from start and end ( for small size screen ) whereas 2. Take minimum width ( Using method minWidth ) from the center ( for large size screen ).
Sir, please guide me if there is another alternative.

**Comment by ArchitJain1201** [comment]
**### Screenshots** 
**Before**
![Screenshot_20220114_001544](https://user-images.githubusercontent.com/80871543/149484079-6c230d71-d11d-4c4f-8336-87b0762ec776.png)
**After** 
![Screenshot_20220114_130407](https://user-images.githubusercontent.com/80871543/149484177-f0e042e7-f98e-4bdb-ba6c-3497f9db4ab9.png)
**Before** 
![Screenshot_20220114_001601](https://user-images.githubusercontent.com/80871543/149484697-7c3f87f5-6caa-4341-8963-a33003e6517b.png)
**After** 
![Screenshot_20220114_130450](https://user-images.githubusercontent.com/80871543/149484792-833db0b6-bfd0-4f1a-bf46-cf71b029549c.png)
**Before** 
![Screenshot_20220114_003102](https://user-images.githubusercontent.com/80871543/149485876-548bdf1d-8007-400a-8b85-d9d3f861b043.png)
**After**  
![Screenshot_20220114_141737](https://user-images.githubusercontent.com/80871543/149485995-c856644e-a2a1-4d12-9895-f5bd424312e5.png)
**Before** 
![Screenshot_20220114_003119](https://user-images.githubusercontent.com/80871543/149486048-4b9e1525-9213-4dff-8086-e2f966d2610d.png)
**After** 
![Screenshot_20220114_141743](https://user-images.githubusercontent.com/80871543/149486181-6fbff088-3bc6-4973-b498-b41b5cf27789.png)

**Comment by ArchitJain1201** [comment]
@PTAL bkaur-bkj

**Comment by bkaur-bkj** [comment]
@ArchitJain1201 as I explained in the meet, make a PR addressing this issue and that will be reviewed
