### ISSUE TITLE
Merge section_title.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3573]
Currently there are 4 versions of `section_title.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by JishnuGoyal** [comment]
May I work on this?

**Comment by JishnuGoyal** [comment]
Kindly assign this to me if no one is working on it

**Comment by JishnuGoyal** [comment]
![image](https://user-images.githubusercontent.com/64526117/137796601-e125c68f-e68e-4c55-b88a-3653aa4b5775.png)

Just to confirm, is this the view we are talking about?

**Comment by JishnuGoyal** [comment]
I have tried to search a lot, I'm not able to find which view is section_title.xml. Please provide a screenshot @rt4914

**Comment by rt4914** [comment]
@JishnuGoyal This corresponds to following file:
https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/layout/section_title.xml


**Steps to navigate**
1. Play a couple of explorations like `What is a Fraction?`, `Test Exploration`, etc.
2. Now go to home screen you will see `View All` button below `Good after/evening, etc ` text.
3. This will open `RecentlyPlayedActivity`
4. In this you will see text like `Played Within the Last Week`, or ``Played Within the Last Month`, etc. 

This is `section_title.xml`

**Comment by JishnuGoyal** [comment]
Thank you so much
