### ISSUE TITLE
Merge solution_summary.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3574]
Currently there are 4 versions of `solution_summary.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by MohitGupta121** [comment]
@rt4914  Can I'll work on this Issue?

**Comment by MohitGupta121** [comment]
Can you please assign this issue to me I do all the necessary stuff on my local and also mentor is assign to me.

**Comment by MohitGupta121** [comment]
@rt4914 can you please tell me how I can generate all the screenshot as I not have Tablet, is there any way to get screenshot like other PR have.

**Comment by rt4914** [comment]
@MohitGupta121 You will need to create a Tablet emulator to generate screenshots for that.
`Tools -> AVD Manager` from here you can create a tablet emulator and run the app on that device.

**Comment by MohitGupta121** [comment]
@rt4914 Can I run on online emulator I test on that its work. Because my PC is not so good to handle emulator and android studio.

**Comment by rt4914** [comment]
@MohitGupta121 I do not have experience with online emulator but if it works correctly feel free to do so and also mention how you did it in your PR so that I can also check that process.

**Comment by MohitGupta121** [comment]
Ok Thanks but I'll first try the Android virtual emulator for testing on my 1st Priority.

**Comment by MohitGupta121** [comment]
@rt4914 which Tablet emulator we need for oppia Nexus 9 or 7?

**Comment by rt4914** [comment]
> @rt4914 which Tablet emulator we need for oppia Nexus 9 or 7?

@MohitGupta121 Might need both for best results.

**Comment by MohitGupta121** [comment]
Okayy thanks you

**Comment by MohitGupta121** [comment]
@rt4914 bro I have make PR for that issue can you please review it.
As I told due to Laptop limitation I try android emulator but its too hang on my PC that's why I have use the online emulator for tablet and my Physical device for mobile.

And bro I not understand why in my commit the .idea file also added I'll unstagged it but on commit it automatically add to commit.
