### ISSUE TITLE
Merge story_chapter_view.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3575]
Currently there are 3 versions of `story_chapter_view.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by shubhanshu-coder** [comment]
can u pl assign this to me and pl guide how to setup

**Comment by vaibhavjain30699** [comment]
Can I work on this issue?

**Comment by ArchitJain1201** [comment]
@bkaur-bkj Can you please assign me this issue?

**Comment by ArchitJain1201** [comment]
@bkaur-bkj @rt4914 Can you suggest how to proceed further as all three have different UI layout 
**layout/story_chapter_view.xml**
<img width="212" alt="image" src="https://user-images.githubusercontent.com/80871543/151588997-4baa8d03-96c4-41f6-8bd2-eccc46184e96.png">
**layout-sw600dp/story_chapter_view.xml**
<img width="200" alt="image" src="https://user-images.githubusercontent.com/80871543/151589088-a39a88f5-a3ea-477c-92d7-b046bf540815.png">
**layout-land/story_chapter_view.xml**
<img width="200" alt="image" src="https://user-images.githubusercontent.com/80871543/151589162-546246bb-60c4-43ae-8735-32ae15ecc012.png">

**Comment by bkaur-bkj** [comment]
@ArchitJain1201 try merging layout and layout-land I guess they can be merged, leave sw600/ as it has different component

**Comment by ArchitJain1201** [comment]
@bkaur-bkj  but ma'am constraintlayout of layout contains chapter_thumbnail, view and imageView which is not available in layout-land

**Comment by rt4914** [comment]
The files for this layout cannot be merged further as all three designs are different.
