### ISSUE TITLE
Merge toolbar.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3578]
Currently there are 2 versions of `toolbar.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by UttaranDas** [comment]
I would like to work on this.

**Comment by MaskedCarrot** [comment]
@Noobmaster-UD assigning this to you
