### ISSUE TITLE
Merge topic_info_fragment.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3579]
Currently there are 4 versions of `topic_info_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by mukulasija** [comment]
I would like to work on this.

**Comment by vivaansahai** [comment]
Hello, can I work on this issue?

**Comment by rishidyno** [comment]
@vivaansahai Assigned this to you if you have any doubt ask here.

**Comment by rt4914** [comment]
Unassigned because of inactivity.

**Comment by vivaansahai** [comment]
Hello @rt4914, I am still working on this. Sorry for the delay.

**Comment by rt4914** [comment]
@vivaansahai No worries. I will assign you back.

**Comment by rt4914** [comment]
Closing this PR as this issue cannot be solved. All four combinations of the UI are quite different and therefore we cannot merge them.
