### ISSUE TITLE
Merge topic_lessons_title.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3582]
Currently there are 4 versions of `topic_lessons_title.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is no difference between before and after UI.

**Comment by ayaazansari** [comment]
can I work on this?

**Comment by rt4914** [comment]
@ayaazansari Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by shivambh12** [comment]
@FareesHussain  can,i work on this?

**Comment by shivambh12** [comment]
@rt4914  In topic_lessons_title.xml textview width is wrap content but in  sw600dp/topic_lessons_title.xml textview width is 528dp.How should I merge them.Also,in  sw600dp/topic_lessons_title.xml textviiew gravity is centre.

**Comment by rt4914** [comment]
@shivambh12 The differences that you suggested are correctly but even after merging of files these differences should exists. That's why the issue mentions : `**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is no difference between before and after UI.`

So in the end you might merge all files into a single file or 2 files based on the code that has been written.
