### ISSUE TITLE
Merge topic_practice_fragment.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3584]
Currently there are 4 versions of `topic_practice_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by kritigupta45** [comment]
I would like to work on this issue, kindly assign it to me.

**Comment by rt4914** [comment]
@kritigupta45 Any updates in this issue? If you facing any issues, please reach out to your mentor. Thanks.

**Comment by kritigupta45** [comment]
> @kritigupta45 Any updates in this issue? If you facing any issues, please reach out to your mentor. Thanks.

@rt4914 Apologies for the delay, I am working on this issue right now.

**Comment by rt4914** [comment]
@kritigupta45 Thanks.
