### ISSUE TITLE
Merge topic_practice_subtopic.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3586]
Currently there are 4 versions of `topic_practice_subtopic.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by kritigupta45** [comment]
@rt4914 I would like to work on this issue, kindly assign it to me.

**Comment by rt4914** [comment]
@kritigupta45 
Thank you for showing interested. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by rt4914** [comment]
cc: @ARJUPTA
