### ISSUE TITLE
Merge topic_summary_view.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3589]
Currently there are 3 versions of `topic_summary_view.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by rt4914** [comment]
@yash10019coder Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by ishant904** [comment]
@rt4914 I am new to open source and i filled up the CLA and contribution survey. I am currently understanding the app architecture and code base and would be happy to work on this issue.

**Comment by yash10019coder** [comment]
Hi @ishant904 welcome to oppia I'm assigning this to you.

**Comment by ishant904** [comment]
thanks @yash10019coder , let me know if you can provide any additional inputs on this so I can get started.

**Comment by yash10019coder** [comment]
@ishant904 just try to read the instructions in the issue and the basic idea is to remove the tablet file so that we can decrease the diversity of our layout files and it also makes it more easier to work on ui as we have to then make the changes on one xml file instead of two or three files.

**Comment by ishant904** [comment]
@yash10019coder thanks for the inputs. I created variables for the all the different dimensions in dimens.xml . But one of the version of topic_summary_view.xml (sw600dp-land) has a unique attribute android:scaleType="centerInside" . Should I create a new style sw600dp-land and place the scaleType in it and use accordingly?

**Comment by yash10019coder** [comment]
@ishant904  please create a PR for the work you have done thanks.

**Comment by yash10019coder** [comment]
then we can discuss the problems in code

**Comment by ishant904** [comment]
@yash10019coder I am trying to push commit in my forked repo but getting this error.

![image](https://user-images.githubusercontent.com/52167192/146382560-d70eb00c-5eb4-487b-a696-1075ffca13ed.png)

**Comment by yash10019coder** [comment]
Hi @ishant904 is python2 installed in your system?

**Comment by ishant904** [comment]
nope.

**Comment by yash10019coder** [comment]
please install python2 then

**Comment by ishant904** [comment]
installed python2 but still no luck

**Comment by yash10019coder** [comment]
try to run this command 
`java -jar ../oppia-android-tools/ktlint -F --android domain/src/**/*.kt utility/src/**/*.kt data/src/**/*.kt app/src/**/*.kt testing/src/**/*.kt scripts/src/**/*.kt  instrumentation/src/**/*.kt`

**Comment by ishant904** [comment]
@yash10019coder thanks!! . There was some issue with the google_check.xml and I was able to solve it by copying the content from checkstyle repo. I have created a PR, please do let me know on the changes req to elimnate all the xml files.

**Comment by yash10019coder** [comment]
@ishant904 you have to also link the PR to the issue by writing Fixes #<issue number>. so that it is shown up in the the linked PR's.

**Comment by yash10019coder** [comment]
and also whenever createing a pr you ask a review also assingn the PR to the person thanks

**Comment by ishant904** [comment]
Done. @rt4914 I made PR #4070 , let me know on the additional changes required.
