### ISSUE TITLE
Merge walkthrough_final_fragment.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3590]
Currently there are 2 versions of `walkthrough_final_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by mahendra1290** [comment]
@rt4914 I can see one file for portrait and one for landscape no other XML files name ```walkthrough_final_fragment.xml```. What files need to be merged can you give some examples?

**Comment by rt4914** [comment]
@mahendra1290 The main purpose is to merge the two files that you have mentioned such that the output/UI remains the same but there is only one file in the end. This can be done by finding about the differences first and then using `dimens.xml` files create variables to fix those differences.

**Comment by mahendra1290** [comment]
> @mahendra1290 The main purpose is to merge the two files that you have mentioned such that the output/UI remains the same but there is only one file in the end. This can be done by finding about the differences first and then using `dimens.xml` files create variables to fix those differences.

But the layout for landscape and portrait is different how to handle it.

**Comment by rt4914** [comment]
@mahendra1290 Can you mention the reasons why it is different? So that once those reasons are mentioned here we can close this issue directly.

**Comment by mahendra1290** [comment]
![Screenshot from 2021-09-11 00-02-09](https://user-images.githubusercontent.com/42772952/132900973-9c1b55aa-154c-4bcd-a7f8-f6cf8f9fdb27.png)
Landscape layout [layout-land/walkthrough_final_fragment.xml](https://github.com/oppia/oppia-android/blob/92ce46b81b2183283e04c4d592fc8682338e1404/app/src/main/res/layout-land/walkthrough_final_fragment.xml)

![Screenshot from 2021-09-11 00-01-58](https://user-images.githubusercontent.com/42772952/132900982-ffa12ca8-6ab8-4dc3-97bf-39388ebbc9bc.png)
portrait layout [/layout/walkthrough_final_fragment.xml](https://github.com/oppia/oppia-android/blob/92ce46b81b2183283e04c4d592fc8682338e1404/app/src/main/res/layout/walkthrough_final_fragment.xml)

As you can see the layout for portrait and landscape is not the same so we have to keep two files for both. We can't merge these files without affecting UI.

**Comment by rt4914** [comment]
Thanks @mahendra1290 

Closing this as per above comment as the two files cannot be merged.
