### ISSUE TITLE
Merge walkthrough_welcome_fragment.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3591]
Currently there are 2 versions of `walkthrough_welcome_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by bkaur-bkj** [comment]
@rt4914 sir I would like to work on this

**Comment by bkaur-bkj** [comment]
@rt4914  Sir I went through the issue  but it not only has variable differences but also several other constraints are present in one file and absent in other, so these files differ in terms of them too, so how should we merge them, as same entity of different files are constrained to different entities.
I think they cannot be just merged by dimens.xml changes

**Comment by mahendra1290** [comment]
![Screenshot from 2021-09-11 00-02-09](https://user-images.githubusercontent.com/42772952/132900973-9c1b55aa-154c-4bcd-a7f8-f6cf8f9fdb27.png)
Landscape layout [layout-land/walkthrough_final_fragment.xml](https://github.com/oppia/oppia-android/blob/92ce46b81b2183283e04c4d592fc8682338e1404/app/src/main/res/layout-land/walkthrough_final_fragment.xml)

![Screenshot from 2021-09-11 00-01-58](https://user-images.githubusercontent.com/42772952/132900982-ffa12ca8-6ab8-4dc3-97bf-39388ebbc9bc.png)
portrait layout [/layout/walkthrough_final_fragment.xml](https://github.com/oppia/oppia-android/blob/92ce46b81b2183283e04c4d592fc8682338e1404/app/src/main/res/layout/walkthrough_final_fragment.xml)

As you can see the layout for portrait and landscape is not the same so we have to keep two files for both. We can't merge these files without affecting UI.

**Comment by HIM7707** [comment]
@rt4914 I would like to work on this issue.

**Comment by rt4914** [comment]
@HIM7707 Assigned you this PR.  Also, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by HIM7707** [comment]
Thank you @rt4914 for the opportunity.

**Comment by pandayed** [comment]
Can you please assign me this issue?

**Comment by rishidyno** [comment]
Assigned this to @xpandeyed due to @HIM7707 inactive.

**Comment by ShivamMadlani** [comment]
Hello there, I would like to work on this issue.Also I am a beginner at this stuff. I would be great if you brief me on how to approach the above mentioned issue... Thanks!!

**Comment by rishidyno** [comment]
Thanks @ShivamMadlani assigned this to you. Take reference from [here](https://github.com/oppia/oppia-android/pull/4181)

**Comment by ShivamMadlani** [comment]
I am facing layout issues...
This image does not have the same layout as what is supposed to be there is landscape mode.
![image](https://user-images.githubusercontent.com/94903454/157253131-43dead84-9185-4c5c-b5f3-ce37b8603855.png)

The below image is how its supposed to look
![image](https://user-images.githubusercontent.com/94903454/157253181-4438ee94-746b-4394-a027-ee5e9c8b5d01.png)

How do I make different layouts in the same xml file?
Any help is appericiated...

**Comment by ShivamMadlani** [comment]
@rishidyno There are layout issues. How do I solve this...

**Comment by rishidyno** [comment]
@ShivamMadlani I think this might be merged into single file as we have different layouts for port and land. 

@rt4914 PTAL at this issue, I think we might not be able to merge `walkthrough_welcome_fragment`. Left some suggestions, not so sure but just in case if that possible please let us know, thanks.

Not so sure if this is possible, but there might be one way to do it by making ids.xml for different configs, and we can add different constraints values accordingly to be used in differ configurations.

**Comment by rishidyno** [comment]
@ShivamMadlani Suggest looking at some other good first issues for the time being once we get clarification from @rt4914

**Comment by ShivamMadlani** [comment]
@rishidyno Sure!! Thanks!!

**Comment by anamansari062** [comment]
i would like to be assigned to this issue! @rt4914

**Comment by ShivamMadlani** [comment]
Can you assign me this issue?

**Comment by rt4914** [comment]
> Can you assign me this issue?

@ShivamMadlani Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by ShivamMadlani** [comment]
@rt4914 I already checked out the wiki page and have signed the CLA.

**Comment by ShivamMadlani** [comment]
@rt4914 As I mentioned earlier, there are different layouts for portrait and landscape files. These cannot be merged in a single file, so we will have to keep both the files.
Attaching the screenshots for your refernce.
![image](https://user-images.githubusercontent.com/94903454/160677758-373482d9-4396-4058-8de0-0bb081362968.png)
![image](https://user-images.githubusercontent.com/94903454/160677764-d2a7c8bf-58b4-43b9-94db-7fa31fcce792.png)

**Comment by kemicky** [comment]
**Hello,
I have Finished the getting started, please may you kindly assign me this issue or any UI merge issue. thank you**

**Comment by rt4914** [comment]
Closing this as we cannot merge files for this layout considering both the layouts are designed differently.

**Comment by kemicky** [comment]
I left it when I heard no response from you.
Nobody reached out to me or communicate to me on how to proceed.
So I left it. I did it already but when I wasn't get any form of response I
thought maybe it's not needed anymore.
