### ISSUE TITLE
Display loading progress while downloading audio for the card

### ISSUE THREAD

**Issue by om-khandade** [oppia/oppia-android#3596]
**Describe the bug**
When a user tries to play audio that is not downloaded, the downloading starts in the background but no loading message is shown to user. 

**To Reproduce**
1. Go to a lesson for which audio is not downloaded
2. enable the audio and press the play button
3. Now there is no message that indicates that the audio is loading

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![Screenshot_20210727-190616](https://user-images.githubusercontent.com/63059690/127164178-adc73c8d-777f-455d-8cee-ab06f22e6dcd.jpg)
![Screenshot_20210727-190637](https://user-images.githubusercontent.com/63059690/127164217-86225c47-03a0-4506-b4a2-d16f558f3a1b.jpg)

**Expected behavior**
When a user tries to play audio that is not downloaded, a message should be shown to user that the audio is downloading with percentage. 

**Device**
OnePlus 6 (ONEPLUS A6000)
Android version: 10

**Comment by anandwana001** [comment]
Hi @om-khandade 
Thanks for filing an issue.

**Comment by BenHenning** [comment]
I think the best that we can do here is introduce a non-determinate progress bar while the audio is buffering since we don't actually download the full audio stream ahead of time.

**Comment by om-khandade** [comment]
I think that the full audio stream is being loaded before the playback starts, as there is no data usage once the audio starts playing.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.5-alpha (MR2).
