### ISSUE TITLE
ItemSelectionInput submit button is enabled after config change

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#3598]
**Describe the bug**

**To Reproduce**
1. Go to 'First Test Topic'
2. Go to 'Prototype Exploration'
3. Navigate to Item Selection Input
4. check a option
5. rotate to landscape
6. submit button is enabled even when the options are not selected

**Expected behavior**
Submit button should be disabled when no option is selected

**Comment by Rohit1173** [comment]
@FareesHussain I have found this issue in the app. But I am not able to find the exact file in the project. So could you please guide me through

**Comment by FareesHussain** [comment]
@Rohit1173 you can find everything related to it under [this](https://github.com/oppia/oppia-android/tree/develop/app/src/main/java/org/oppia/android/app/player/state) directory

**Comment by Rohit1173** [comment]
ok, thanks! I will check it

**Comment by rt4914** [comment]
This issue is no more reproducible. The submit button remains `DISABLED` if there is not option selected.
