### ISSUE TITLE
Fix HTML formatting throughout app

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#361]
There are a few issues we've noticed with HTML formatting:
1. Images that are too large get cut off--we should resize these to take up the maximum space they have available without requiring scrolling, but maintain aspect ratio.
2. Bullet list items need to have proper spacing.
3. Newlines shouldn't be rendered as <br>s.
4. Generally, we need the HTML result to look really clean.

**Comment by rt4914** [comment]
@BenHenning I think this has been finished in various different parts?

**Comment by BenHenning** [comment]
Please make sure this is resolved by verifying large and small images with display and font zoom to simulate small screens. 

Also, I think the bullet list spacing might be a bit off. We should look into fixing that. 

Otherwise, I agree that other aspects of this issue are probably resolved now.

**Comment by veena14cs** [comment]
This is been fixed in PR #404 and #454 .
