### ISSUE TITLE
Move DEVELOPER_URL to DI Graph

### ISSUE THREAD

**Issue by Sparsh1212** [oppia/oppia-android#3623]
We need to move the DEVELOPER_URL: "https://oppia.org" to the DI graph.

**Comment by Sparsh1212** [comment]
@BenHenning Can you please confirm this once. This is in replacement for #74 TODO.

**Comment by BenHenning** [comment]
This seems reasonable.

Out of curiosity @FareesHussain will this be addressed with your project since we need to be able to set a different endpoint URL for Oppia's backend? For context, see: https://github.com/oppia/oppia-android/blob/develop/data/src/main/java/org/oppia/android/data/backends/gae/NetworkSettings.kt#L9.

**Comment by FareesHussain** [comment]
> This seems reasonable.
> 
> Out of curiosity @FareesHussain will this be addressed with your project since we need to be able to set a different endpoint URL for Oppia's backend? For context, see: https://github.com/oppia/oppia-android/blob/develop/data/src/main/java/org/oppia/android/data/backends/gae/NetworkSettings.kt#L9.

@BenHenning I was wondering if the developer url in the NetworkSettings is the oppia-test-server.
If it is the localhost we can remove the NetworkSettings and directly use the prod_url in the app module and just use the oppia_test from the instrumentation module for the developer URL

Is this what you were expecting here?

**Comment by FareesHussain** [comment]
I'm expecting we need to remove the NetworkSettings and use the dev URL directly.

https://github.com/oppia/oppia-android/pull/3529/files#diff-540a835172c1421fa8a63c29d1522969d8ef198f83891f2698f1a197d6aa9762

**Comment by FareesHussain** [comment]
Closing this since this was fixed in https://github.com/oppia/oppia-android/pull/3529

**Comment by seanlip** [comment]
Looks like this wasn't actually closed at the time of @FareesHussain's comment. Closing now.
