### ISSUE TITLE
Link backend domain model

### ISSUE THREAD

**Issue by Sparsh1212** [oppia/oppia-android#3636]
We want to update all the GAE data classes related to feedback reporting (e.g. GaeFeedbackReport, GaeEntryPoint, etc.) to link back to their corresponding backend controllers that pass these data objects, similar to other GAE data classes (for example, [GaeStory](https://github.com/oppia/oppia/blob/b56a20/core/controllers/story_viewer.py#L47)).

**Comment by BenHenning** [comment]
Closing this in favor of #3016.
