### ISSUE TITLE
Investigate using finish instead of intent

### ISSUE THREAD

**Issue by Sparsh1212** [oppia/oppia-android#3641]
Currently, we need to start intent for ProfileChooserActivity to get an update. We need to investigate on using finish instead as the live data bug is fixed.

- [ ] https://github.com/oppia/oppia-android/blob/ef7ffb8/app/src/main/java/org/oppia/android/app/profile/AddProfileActivity.kt#L32
- [ ] https://github.com/oppia/oppia-android/blob/ef7ffb8/app/src/main/java/org/oppia/android/app/drawer/ExitProfileDialogFragment.kt#L67

**Comment by rishav2404** [comment]
I want to work on this issue. Please assign this to me.

**Comment by adhiamboperes** [comment]
> I want to work on this issue. Please assign this to me.

Hi @rishav2404, please give an overview of your proposed solution

**Comment by theayushyadav11** [comment]
I want to work on this issue,plz assign it to me.

**Comment by adhiamboperes** [comment]
@theayushyadav11, please feel free to create a PR.
