### ISSUE TITLE
Bazel Build Fail for MacOS

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3653]
Original issue - https://github.com/protocolbuffers/protobuf/issues/8863

**Comment by BenHenning** [comment]
I don't think that this is a problem anymore. There have been a lot of OSX fixes in Bazel that we now have after migrating to 6.x in #4886. Closing this as completed.

@adhiamboperes or anyone else with a Mac, please reopen if you're facing any Mac-specific build issues when using Bazel.
