### ISSUE TITLE
RTL Onboarding Images in Landscape mode

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3655]
PR Reference: https://github.com/oppia/oppia-android/pull/3635

## Screenshot LTR and RTL
**Mobile Portrait:** 

<img width="144" alt="Screenshot_1627853193" src="https://user-images.githubusercontent.com/16301028/127840982-4546daac-aacc-4203-9210-1351629e934a.png">..... <img width="144" alt="Screenshot_1627853346" src="https://user-images.githubusercontent.com/16301028/127841214-64d711ad-486f-46b7-ae73-457d0091d899.png">
<img width="144" alt="Screenshot_1627853198" src="https://user-images.githubusercontent.com/16301028/127841043-821f2bc8-5907-464a-8881-59eeb972ed92.png">.....<img width="144" alt="Screenshot_1627853351" src="https://user-images.githubusercontent.com/16301028/127841302-a0d3bbfd-7dac-45b6-b653-60e5b6b9c42b.png">

<img width="144" alt="Screenshot_1627853201" src="https://user-images.githubusercontent.com/16301028/127841072-ff164c72-eee7-4238-b2eb-351cacbd42cd.png">.....<img width="144" alt="Screenshot_1627853355" src="https://user-images.githubusercontent.com/16301028/127841382-3cd183a5-32a5-4b56-9bb8-80e70898568b.png">

<img width="144" alt="Screenshot_1627853205" src="https://user-images.githubusercontent.com/16301028/127841117-fadaf473-e534-49ce-b7b6-7b35a52abf49.png">.......<img width="144" alt="Screenshot_1627853359" src="https://user-images.githubusercontent.com/16301028/127841435-db428cb7-23ec-4757-8c61-9b7990862112.png">

**Mobile Landscape:** 

<img width="256" alt="Screenshot_1627853246" src="https://user-images.githubusercontent.com/16301028/127841688-bd83079e-4261-42e6-8283-48903527a2a8.png">......<img width="256" alt="Screenshot_1627853385" src="https://user-images.githubusercontent.com/16301028/127841930-41526013-92c9-4fbb-9dcd-f18d5a08f2ac.png">

<img width="256" alt="Screenshot_1627853243" src="https://user-images.githubusercontent.com/16301028/127841749-922e3864-dbe8-41cc-96bf-b8643f0a12f0.png">........<img width="256" alt="Screenshot_1627853381" src="https://user-images.githubusercontent.com/16301028/127841990-2111ce07-2439-44e9-896f-6ef439ccd07b.png">
<img width="256" alt="Screenshot_1627853239" src="https://user-images.githubusercontent.com/16301028/127841792-ab7e446e-fcee-4181-bb6f-5a021b32fcc0.png">.......<img width="256" alt="Screenshot_1627853376" src="https://user-images.githubusercontent.com/16301028/127842105-53c045cf-74b8-4f97-a4f8-9588aedb8ae7.png">

<img width="256" alt="Screenshot_1627853228" src="https://user-images.githubusercontent.com/16301028/127841864-0eb50269-2517-4bd9-97f9-e460c2bf19ca.png">....<img width="256" alt="Screenshot_1627853368" src="https://user-images.githubusercontent.com/16301028/127842170-7dc53405-7c71-494b-be59-46f76f015dac.png">

**Tablet Portrait:** 
<img width="160" alt="Screenshot_1627853506" src="https://user-images.githubusercontent.com/16301028/127842328-fb222353-4c5f-4b4c-a1ff-430cbbfe8fac.png">......<img width="160" alt="Screenshot_1627853600" src="https://user-images.githubusercontent.com/16301028/127843072-f21e581d-656d-423c-9439-c7a01fd105f9.png">
<img width="160" alt="Screenshot_1627853510" src="https://user-images.githubusercontent.com/16301028/127842383-c4d6efa5-7677-49c0-8c72-19daf8778fc5.png">....<img width="160" alt="Screenshot_1627853598" src="https://user-images.githubusercontent.com/16301028/127843037-345f6f06-c474-432b-adec-cb6b542eefa1.png">
<img width="160" alt="Screenshot_1627853513" src="https://user-images.githubusercontent.com/16301028/127842431-7eac3ee2-75ce-45b5-977b-21585fda41ea.png">....<img width="160" alt="Screenshot_1627853595" src="https://user-images.githubusercontent.com/16301028/127842992-57396fc6-aff4-4e57-bb89-96cb3e4544b8.png">
<img width="160" alt="Screenshot_1627853519" src="https://user-images.githubusercontent.com/16301028/127842470-6c8065a5-3445-438d-988e-826f5aaf9694.png">.....<img width="160" alt="Screenshot_1627853590" src="https://user-images.githubusercontent.com/16301028/127842933-e06a8db6-2629-4b87-bd2e-bb40cc8d7955.png">

**Tablet Landscape:** 
<img width="256" alt="Screenshot_1627853539" src="https://user-images.githubusercontent.com/16301028/127842533-0d3febe0-8de6-4403-bd99-a8e83ab2ea5e.png">....<img width="256" alt="Screenshot_1627853572" src="https://user-images.githubusercontent.com/16301028/127842746-d80ccb20-1e06-42d0-be4e-e6fbb82cb842.png">
<img width="256" alt="Screenshot_1627853535" src="https://user-images.githubusercontent.com/16301028/127842573-e526b2e1-6336-4b37-bd2c-94b08536ed16.png">....<img width="256" alt="Screenshot_1627853575" src="https://user-images.githubusercontent.com/16301028/127842802-8eb59599-5d15-4fa4-97b7-a45245715671.png">
<img width="256" alt="Screenshot_1627853531" src="https://user-images.githubusercontent.com/16301028/127842636-dce02a95-b77f-4111-8e5b-4c842c82ecba.png">.....<img width="256" alt="Screenshot_1627853579" src="https://user-images.githubusercontent.com/16301028/127842837-987c5a8c-72b4-4db5-8a44-6824095c5670.png">
<img width="256" alt="Screenshot_1627853526" src="https://user-images.githubusercontent.com/16301028/127842684-9232bc2b-a3d9-4a8b-8584-8f1cfd64fcce.png">.....<img width="256" alt="Screenshot_1627853582" src="https://user-images.githubusercontent.com/16301028/127842875-8ab48c2c-26e5-447d-ab35-e02d05571939.png">

In all of above images notice how in RTL portrait the foreground is flipped. It found nice if only the background is flipped and not the foreground. Currently this is not possible because the `foreground + background` is part of a single image. Also if we create new images with flipped background for RTL then the apk size would increase because of these new images which is not great.

So we need to find a solution such that:
1. background is flipped for RTL
2. foreground remains the same in LTR and RTL
3. apk size does not increase at all.

**Possible Theoretical Solution**
(Note: This is just a theory and haven't been tested at all.)
1. Let's take one of these images and assume that its size is 4KB. This 4KB image comprise of foreground as well as background. 
2. Now if we can create separate image for foreground and separate image for background such that each of these takes approx 2 KB each and combined it takes 4 KB. In this case we can again achieve our original image by overall these images on top of each other in UI and still the apk size will remain same. (This theory that on creating separating images and total of those two images will be equal to that of the original has not been tested.)
3. If above step us possible then now in RTL we can just flip the background and keep the foreground as it is and our apk size will also remain the same.

This issue does require some design expertise and also if the apk size changes even slightly then this issue will get closed.

**Comment by adhiamboperes** [comment]
Closing since the onboarding layout design has changed.
