### ISSUE TITLE
Bottom text cutting for ConceptCard

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3673]
Just add `android:clipToPadding="false"` to scroll view

![Screenshot_1628786031](https://user-images.githubusercontent.com/9396084/129234980-15a4242e-5089-42de-a995-cdca7756aa48.png)

**Comment by yash10019coder** [comment]
@rt4914 are u working on this?

**Comment by sanchi0204** [comment]
Can I work on this?

**Comment by rt4914** [comment]
@sanchi0204 Its assigned to me. Can you work on some other issue from [here](https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee)
