### ISSUE TITLE
Add thumbnails to story tiles

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#368]
Stories do not currently have thumbnails:

![image](https://user-images.githubusercontent.com/12983742/68998367-365d6c00-0866-11ea-98da-7f4c025007b4.png)

We should leverage our existing vector assets for these, and get recommended colors from @mschanteltc.

**Comment by BenHenning** [comment]
I inadvertently fixed this in #392.

**Comment by mschanteltc** [comment]
The thumbnails I used here are thumbnails that I used for the Topics, although ideally they would be different. I added a folder of pngs and svgs (in a zip file) of several of the images to the Google Drive under the folder "Topic Thumbnails"
