### ISSUE TITLE
Hi-fi Resume Lesson Tablet

### ISSUE THREAD

**Issue by MaskedCarrot** [oppia/oppia-android#3691]
Update the tablet UI for resume lesson.

Mock for mobile portrait: https://xd.adobe.com/view/3dca36c2-5115-419c-b25e-0f10526b077c-6899/screen/1c7d4ec6-a5f1-4462-886d-e47c1457b69e/

**Comment by theMr17** [comment]
Hi @adhiamboperes, I would like to work on this issue. My approach would be to add a layout `resume_lesson_fragment.xml` for `sw600dp-port` qualifiers and create the screen according to the UI attached with the issue.

**Comment by adhiamboperes** [comment]
> Hi @adhiamboperes, I would like to work on this issue. My approach would be to add a layout `resume_lesson_fragment.xml` for `sw600dp-port` qualifiers and create the screen according to the UI attached with the issue.


Can you please confirm that this file doesn't exist?

**Comment by theMr17** [comment]
No, the file does not exist at present.

![image](https://github.com/oppia/oppia-android/assets/84731134/c43216d3-3b8c-4eb1-af96-575c5dcb545b)

**Comment by MohitGupta121** [comment]
@adhiamboperes But I think we need design for Resume Lesson specifically for tablet. Is that exist?

**Comment by adhiamboperes** [comment]
> @adhiamboperes But I think we need design for Resume Lesson specifically for tablet. Is that exist?

@MohitGupta121, for this screen I think it's fine if it looks like the mobile portrait, as in the linked mock. Cc @seanlip

**Comment by seanlip** [comment]
Here are the tablet mocks I'm aware of. Maybe see if this one is included there? https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid

**Comment by theMr17** [comment]
@seanlip I had a look through all the tablet mocks, but this one is not available there.

**Comment by seanlip** [comment]
@the-mr17 Thanks for checking. Are there any mocks that are similar or that cover the same screen (but perhaps in a different context)? The link I sent you is all the mocks we have, so we might need to reason by analogy if the exact mock isn't provided there.

**Comment by adhiamboperes** [comment]
https://github.com/oppia/oppia-android/pull/5116 shows how this screen looks on different devices. I don't forsee any issues with making the tablet portrait look like mobile portrait(mocks linked in issue description)

**Comment by MohitGupta121** [comment]
@adhiamboperes hope this will help https://xd.adobe.com/view/3dca36c2-5115-419c-b25e-0f10526b077c-6899/screen/1c7d4ec6-a5f1-4462-886d-e47c1457b69e/
Dark mode : https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/826c5108-769e-4138-aa3c-74da1113ca5a/

**Comment by theMr17** [comment]
Thanks! I am submitting a PR after implementing the screen based on the available mocks.

**Comment by theMr17** [comment]
I have added some extra horizontal margin to the texts. I don't think anything else needs to changed. Please let me know your thoughts on this.

|Before|After|
|--|--|
|<img src="https://github.com/oppia/oppia-android/assets/84731134/99eace0a-94ff-40a5-97c2-8bc69965dc0e" width="400"/>|<img src="https://github.com/oppia/oppia-android/assets/84731134/170808c4-0a5b-45df-b2a4-7bd312216010" width="400"/>|

**Comment by seanlip** [comment]
Thanks, I don't have any concerns here.
