### ISSUE TITLE
Hi-fi Resume Lesson for mobile landscape [Blocked on #3490]

### ISSUE THREAD

**Issue by MaskedCarrot** [oppia/oppia-android#3692]
Update the mobile landscape UI for resume lesson.

mock for mobile portrait: https://xd.adobe.com/view/3dca36c2-5115-419c-b25e-0f10526b077c-6899/screen/1c7d4ec6-a5f1-4462-886d-e47c1457b69e/

**Comment by rt4914** [comment]
This has been finished now.
In landscape mode we change a design a bit and mainly hide the image. The reference for hiding the image was taken from UI of `ChapterList` in `StoryActivity`.

![Screenshot_20230619-130845](https://github.com/oppia/oppia-android/assets/9396084/8d15df86-6a02-410c-8315-0c1b3d5698fb)
