### ISSUE TITLE
Clear application data for each test case in e2e tests

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#3693]
Reset Application for each test case between tests in the instrumentation module.

**Comment by BenHenning** [comment]
@FareesHussain why was this closed? It should be closed by the PR that's fixing it.

**Comment by FareesHussain** [comment]
> @FareesHussain why was this closed? It should be closed by the PR that's fixing it.

This was accidentally closed when I created the 2.4 pr.
Closing now as this was addressed in the 2.2 pr
