### ISSUE TITLE
Remove non-JSON test data

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#370]
The Oppia app currently uses a bunch of hardcoded test data rather than relying on real lesson data loaded from JSON. We should remove all test data in favor of the loaded JSON files.

**Comment by BenHenning** [comment]
As mentioned in #350 we probably want to remove all JSON data from the app for production classes which means this issue is blocked on download support.

/cc @rt4914 as FYI.

**Comment by rt4914** [comment]
> As mentioned in #350 we probably want to remove all JSON data from the app for production classes which means this issue is blocked on download support.
> 
> /cc @rt4914 as FYI.

Got it. Thanks.

**Comment by BenHenning** [comment]
I actually think this issue changed meanings over time. We'll organically move to a hybrid model of embedded & downloadable lessons, even for developers. Per the original intention of this issue, we don't hardcode anything in the app anymore (as demonstrated by multiple user-facing releases that rely on different lesson data than what's available locally for developers).
