### ISSUE TITLE
Full app audit on KitKat/SDK 19 [Blocked: #3504]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3725]
Blocked on #3504

This issue tracks performing another full audit of the app on KitKat & filing all issues under the KitKat project board (https://github.com/oppia/oppia-android/projects/14) as they're found.

**Comment by seanlip** [comment]
Per https://github.com/oppia/oppia-android/issues/5012, we are deprecating support for Android KitKat, so this issue is no longer valid.
