### ISSUE TITLE
Import Arabic translations into the app

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3731]

**Comment by vishalsharma0657** [comment]
Can I work on it?

**Comment by MaskedCarrot** [comment]
Hi @vishalsharma0657, I don't think this issue is available. I suggest you pick one of the good first issues from [here](https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

**Comment by BenHenning** [comment]
This is effectively done with #3687 merged. Other changes are coming to properly support the translations.
