### ISSUE TITLE
The App crashes on the main screen when trying to run on Pixel 3a API 19.

### ISSUE THREAD

**Issue by aadityaguptaa** [oppia/oppia-android#3745]
**Describe the bug**
When trying to run the app on Google Pixel 3a Emulator with API 19, the App crashes on the main screen.

**To Reproduce**
1. Just run the app and wait for a couple of seconds

**Screenshots**
![crash image](https://i.ibb.co/8gYwwKv/Screenshot-1630346091.png)

**Device**
- Emulator - Pixel 3a
- API 19

**Logcat Images**
![image1](https://i.ibb.co/jT9bTGV/part1.png)
![image2](https://i.ibb.co/09y2L28/part2.png)

**Comment by BenHenning** [comment]
/cc @anandwana001 who's looking into this.

Thanks for the report @aadityaguptaa!

**Comment by anandwana001** [comment]
This is a duplicate issue. 
@rt4914 is handling this crash over here - https://github.com/oppia/oppia-android/issues/3504

**Comment by rt4914** [comment]
Closing this now.
