### ISSUE TITLE
Text-based interactions need real-time answer validation

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#376]
Although we limit the characters we can freely input to text-based interactions, it's still possible to fill in impossible answers that will likely fail or crash the app, e.g. '2/3/4/3' in a fractions lesson.

We should have an error label appear when an incorrect answer is typed in a text-based interaction and prevent answer submission.

**Comment by seanlip** [comment]
Note that the interactions in the web version have custom logic for this.
Probably worth following it exactly.

>

**Comment by nikitamarysolomanpvt** [comment]
@BenHenning I had gone through https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/app/parser/StringToFractionParser.kt updates from your end. Seems even some valid fraction inputs are failing with the regx used. I had updated the test cases as per the new changes.
Please suggest the expected changes as per #376 issue.

> Note that the interactions in the web version have custom logic for this. Probably worth following it exactly.
> […](#)

@seanlip you mean https://github.com/oppia/oppia/blob/develop/extensions/interactions/FractionInput/directives/oppia-interactive-fraction-input.directive.ts as 

> custom logic for this

Or
Do you want me to use 
https://github.com/oppia/oppia/blob/develop/core/templates/dev/head/domain/objects/FractionObjectFactory.ts
or other validations in files of 
https://github.com/oppia/oppia/tree/develop/extensions/interactions/FractionInput/directives folder
Adding Banglore team in loop @veena14cs @rt4914

**Comment by seanlip** [comment]
For this one in particular I think https://github.com/oppia/oppia/blob/develop/core/templates/dev/head/domain/objects/FractionObjectFactory.ts is the most relevant.

**Comment by BenHenning** [comment]
That's interesting. @nikitamarysolomanpvt which inputs fail?

I'm not against using the web code, but mine was meant to be a simplification, actually. I intended for it to be correct, so I'm curious which inputs make it fail.

**Comment by BenHenning** [comment]
Aha, @nikitamarysolomanpvt you spotted a bug with the denominator patterns. I accidentally kept the ``+`` out of the parentheses. The following should be the correct patterns:

```kotlin
  private val wholeNumberOnlyRegex = """^-? ?(\d+)$""".toRegex()
  private val fractionOnlyRegex = """^-? ?(\d+) ?/ ?(\d+)$""".toRegex()
  private val mixedNumberRegex = """^-? ?(\d+) ?(\d+) ?/ ?(\d+)$""".toRegex()
```

The following bugs existed:
- Fraction-only inputs would not retrieve denominators with more than one digit
- Mixed number inputs would not retrieve whole numbers with more than one digit
- Mixed-number inputs would not retrieve denominators with more than one digit

I'm pretty sure these inputs are now right, but we really ought to add tests for them to be sure.

**Comment by nikitamarysolomanpvt** [comment]
> Aha, @nikitamarysolomanpvt you spotted a bug with the denominator patterns. I accidentally kept the `+` out of the parentheses. The following should be the correct patterns:
> 
> ```kotlin
>   private val wholeNumberOnlyRegex = """^-? ?(\d+)$""".toRegex()
>   private val fractionOnlyRegex = """^-? ?(\d+) ?/ ?(\d+)$""".toRegex()
>   private val mixedNumberRegex = """^-? ?(\d+) ?(\d+) ?/ ?(\d+)$""".toRegex()
> ```
> 
> The following bugs existed:
> 
> * Fraction-only inputs would not retrieve denominators with more than one digit
> * Mixed number inputs would not retrieve whole numbers with more than one digit
> * Mixed-number inputs would not retrieve denominators with more than one digit
> 
> I'm pretty sure these inputs are now right, but we really ought to add tests for them to be sure.

@BenHenning 
Ya and also normalizeWhitespace(),  bug with the wholenumber patterns(fails when its more than one digit).

**Comment by rt4914** [comment]
@nikitamarysolomanpvt This issue is somewhat connected to https://github.com/oppia/oppia-android/pull/419, please have a look.

**Comment by rt4914** [comment]
My interpretation of this issue:
While learner is typing an answer, if they enter invalid answer like `3/4/5/6` we should provide label for invalid answer even when learner has not even clicked on the submit button.

@BenHenning Is this what you mean or something else?

@nikitamarysolomanpvt @seanlip

**Comment by seanlip** [comment]
Yes, that's correct. You can see an example of the expected behaviour in Q2 of this exploration: https://www.oppia.org/explore/rfX8jNkPnA-1?collection_id=4UgTQUc1tala

**Comment by rt4914** [comment]
> Yes, that's correct. You can see an example of the expected behaviour in Q2 of this exploration: https://www.oppia.org/explore/rfX8jNkPnA-1?collection_id=4UgTQUc1tala

Okay. @nikitamarysolomanpvt check this, maybe this can clarify things.

**Comment by BenHenning** [comment]
I suspect that this issue only affects fractions since text & numeric input shouldn't be able to have incorrect values passed in (though maybe numeric does if you paste in something without numbers?)

**Comment by seanlip** [comment]
Yep -- there's no issue with text. For numeric, assuming only numbers, negative signs and dots can be entered in the field, you could have things like: (a) blank input, (b) multiple dots, (c) multiple negative signs, (d) negative signs in the middle of the number, (e) dot before the negative sign.

**Comment by BenHenning** [comment]
@nikitamarysolomanpvt what work remains for this issue?

**Comment by BenHenning** [comment]
Looks like this has been done #419 and #640.
