### ISSUE TITLE
StoryActivity chapter summary uses incorrect description

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3762]
In `StoryActivity` we show chapters with title and some other details.

Currently the `chapter_summary` textview inside `story_chapter_view` is using `outline` from json content [Reference](https://github.com/oppia/oppia-android/blob/develop/domain/src/main/assets/wAMdg4oOClga.json) instead we should be using `description` as part of summary.

Add/Update tests accordingly.

This issue will need changes in `domain` and `app` layer of code.

**Comment by rt4914** [comment]
This will be assigned to Avinash.

**Comment by darkmat13r** [comment]
@rt4914  This is Avinash. Please assign this issue to me.
