### ISSUE TITLE
roboelectric and Junit tests not working in latest android studio arctic fox

### ISSUE THREAD

**Issue by yash10019coder** [oppia/oppia-android#3773]
**Describe the bug**
As you go to run any specific test by adding configuration a weird error comes saying that the memory is Filled fully 
this is the SS of the error
![image](https://user-images.githubusercontent.com/76404817/132731124-d61e1d21-b8a9-4ab1-801f-d3b54f73153d.png)
![image (1)](https://user-images.githubusercontent.com/76404817/132731278-bd1df974-87bd-467b-add4-a21428b8ef6e.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/76404817/132731422-2fb594bc-1485-4ac6-bb16-ae1f23c31ba6.png)
click on it then on edit configuration

After that a window pops up like this click on + symbol at the top left corner and then click on junit
![image](https://user-images.githubusercontent.com/76404817/132731529-24880bc9-8f58-4066-966e-4d8f8e1c7511.png)

then this window appears
![image](https://user-images.githubusercontent.com/76404817/132731831-a96d55a5-5d55-484a-a28a-a2449ce0d065.png)

then click on the blue part and select a app module and search a class  to retrace what I did select the app module and then search the class StoryFragmentTest select it and click on apply and Ok then run the test by clicking on the run button or by shortcut Shift + F10 and you're done wait for it then the error appears as the gradle compiles and the app runs
NOTE that in android studio 4.2.1 this successfully runs this error happens only in artic fox

**Expected behavior**

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Device**
- Device/emulator being used
- SDK version

**Additional context**

**Comment by darkmat13r** [comment]
@yash10019coder 
Configuration : 

![image](https://user-images.githubusercontent.com/35571567/134760866-4864762b-f489-46b6-9889-1b8a415ef29b.png)

Error
![image](https://user-images.githubusercontent.com/35571567/134760848-446d11d2-6545-4207-8514-59b8578ffcc8.png)

**Comment by darkmat13r** [comment]
@yash10019coder  @rt4914 I think its a bug in javaagent of the android studio. I was able to run the test cases in Intellij IDEA community IDE with following configuration.

![image](https://user-images.githubusercontent.com/35571567/134763990-e8743dc4-6e7d-492b-9d70-cba3dbf91c1e.png)
Result
![image](https://user-images.githubusercontent.com/35571567/134764016-33a50827-9815-4af0-8c1c-e9aa3460c65f.png)

**Comment by rt4914** [comment]
Thanks @darkmat13r

**Comment by BenHenning** [comment]
@yash10019coder assigning this to you since you have a PR out to address this.

**Comment by BenHenning** [comment]
This is an open issue to work on (#3783 is a good place to start--please also look at the comments).

This is actually a rather important issue since it will affect new contributors, so we'd really appreciate help on this one. :)
