### ISSUE TITLE
New hints/solution after the first don't enable the highlight bulb

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3778]
**Describe the bug**
When subsequent hints or the solution are ready to be viewed, the yellow lightbulb to indicate it's available does not get shown after the first hint.

**To Reproduce**
1. Navigate to an exploration state with hints
2. Trigger the first hint by entering 2 wrong answers
3. View the hint
4. Enter another wrong answer & wait 10 seconds
5. Notice that the bulb doesn't appear despite the next hint/solution being available

**Expected behavior**
The bulb should always appear when a new hint/solution is available. This is a regression.

**Additional context**
I suspect this was caused by #3659 but it might have been caused after.

**Comment by BenHenning** [comment]
@anandwana001 this is likely an alpha MR3 blocker; could you PTAL?

**Comment by anandwana001** [comment]
I checked this on the latest develop branch and it is working for me correctly.

**Comment by BenHenning** [comment]
Given we haven't hit this again, closing as not reproducible.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).
