### ISSUE TITLE
Text-based interactions need correct hint text

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#378]
We should use the same hint text as Oppia web for text-based interactions (e.g. 'Enter a fraction in the form x/x').

**Comment by seanlip** [comment]
Note that, in the web version, this is typically determined based on
customization args specified for the interaction. Probably worth mimicking
that logic exactly.

**Comment by BenHenning** [comment]
Thanks. What is the value used in cases when the customization arg isn't specified, or is it always blank in that case?

**Comment by seanlip** [comment]
It depends on the type of interaction.

For FractionInput it's based on the logic here: https://github.com/oppia/oppia/blob/develop/extensions/interactions/FractionInput/directives/fraction-input-interaction.directive.html#L5

For Textinput the placeholder is specified directly as a customization arg: https://github.com/oppia/oppia/blob/develop/extensions/interactions/TextInput/directives/oppia-interactive-text-input.directive.ts#L49

**Comment by BenHenning** [comment]
Thanks. If I'm reading this right, numeric input doesn't have placeholder text and fractions supports a custom one, otherwise specifies its own. TextInput seems to only use a custom placeholder if one is present.

**Comment by seanlip** [comment]
Yep, that's my understanding.
