### ISSUE TITLE
Break AddProfileActivity string "*Required" into two parts.

### ISSUE THREAD

**Issue by rishidyno** [oppia/oppia-android#3788]
`“*Required”` string in `Add Profile` should be broken down into two parts because “*” does not need a translation.

**Comment by jashasweejena** [comment]
Hey @rishidyno, if no one is currently working on this, can I pick this up?

**Comment by rishidyno** [comment]
@jashasweejena I am working on this issue.

**Comment by jashasweejena** [comment]
> @jashasweejena I am working on this issue.

Oh great :) I'll maybe try picking some other issue.
