### ISSUE TITLE
Entering an exploration state sometimes scrolls past the content

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#380]
If a state card has a text-based interaction, sometimes Android will scroll the user partly down past the content card (likely because the text input is focused). We shouldn't focus the interaction by default.

@rt4914 and I also noticed when playing through state cards that sometimes when selecting a text input to open the keyboard, the keyboard won't open on the first tap and the interaction will be scrolled off screen.

We need to generally fix jank in this area to ensure the experience is solid.

## Issue Work Items

- [ ] Whenever state is changed the scroll view should start from the top everytime.
- [ ] On click of input type interaction item, it requires two clicks to display keyboard, which should actually be just a single click.

**Comment by rt4914** [comment]
This issue can be divided into 2 parts:

- [ ] Whenever state is changed the scroll view should start from the top everytime.
- [ ] On click of input type interaction item, it requires two clicks to display keyboard, which should actually be just a single click.
