### ISSUE TITLE
Handle low memory death crashes due to localization

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3800]
#3795 will introduce a crash that occurs when the app is reconstituted after low-memory death due to the locale not being properly retained. This issue is tracking fixing that crash scenario.

Related: #2571.

**Comment by BenHenning** [comment]
Suggesting that this be an MR4 blocker.

**Comment by srushtirk** [comment]
Caroline came across the same issue when she tried accessing the app for MR3 testing for Portuguese language. 

Screenshot attached:
![image](https://user-images.githubusercontent.com/27875087/134092687-4d38b302-d76c-4a36-ab05-f90915a3bcbe.png)

**Comment by BenHenning** [comment]
Idea for solving after #3795 is merged: we could use the mixin to detect the application death scenario & save the locale context in saved instance state (since it should have access to it, maybe) & restore the singleton upon recreation. This needs some investigation work.

**Comment by BenHenning** [comment]
This case also affects restarting the app after a crash (probably for the same reason).

**Comment by BenHenning** [comment]
Closing now that #3866 is closed (which removed the TODO lines).

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).
