### ISSUE TITLE
Bazel/Gradle Support on Kitkat

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3803]
**Describe the bug**
Currently, the Bazel build apk does not work on kitkat (API 19)

**To Reproduce**
1. Build apk using Bazel and install on API level 19.
2. App crash

**Expected behavior**
The app should run correctly without any crashes.

**Additional Context**
As per AlphaMR3, if it takes longer to bring Bazel support, use Gradle as a build system to run APK on KitKat version.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).
