### ISSUE TITLE
[RTL Exempted file] Fix add_profile_activity.xml

### ISSUE THREAD

**Issue by viktoriias** [oppia/oppia-android#3807]
`file_content_validation_checks.textproto` contains regex pattern checks to spot prohibited content. Some files are listed as `exempted_file_name` because they contain prohibited elements . This is a tracking issue to fix `add_profile_activity.xml` exempted file and make it RTL compatible.

This [Sample PR](https://github.com/oppia/oppia-android/pull/3776) can be used as an example.

RTL guidelines: https://github.com/oppia/oppia-android/wiki/RTL-Guidelines

Please add screenshots when creating a PR with both LTR and RTL views on mobile + tablet.

**Comment by bkaur-bkj** [comment]
@rt4914 sir Please assign this issue to me.
