### ISSUE TITLE
[RTL Exempted file] Fix styles.xml

### ISSUE THREAD

**Issue by viktoriias** [oppia/oppia-android#3809]
`file_content_validation_checks.textproto` contains regex pattern checks to spot prohibited content. Some files are listed as `exempted_file_name` because they contain prohibited elements . This is a tracking issue to fix `styles.xml` exempted file and make it RTL compatible.

This [Sample PR](https://github.com/oppia/oppia-android/pull/3776) can be used as an example.

RTL guidelines: https://github.com/oppia/oppia-android/wiki/RTL-Guidelines

Please add screenshots when creating a PR with both LTR and RTL views on mobile + tablet.

**Comment by rawlin** [comment]
Could you assign me this issue please

**Comment by viktoriias** [comment]
@rawlin Any updates in this?
