### ISSUE TITLE
Audio bar occludes content card

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#381]
The audio bar currently occludes the content, making it difficult to read:

![image](https://user-images.githubusercontent.com/12983742/68998574-21360c80-0869-11ea-87c5-ecd97f6cf285.png)

**Comment by rt4914** [comment]
@BenHenning This has been solved earlier and is in develop right now.

It works as following:
1. If the learner is a top of screen without any scroll and then click on volume icon -> The audio bar will be visible and scroll the top content card to approx 72dp.
2. If the learner is not on top and has scrolled a bit, then click on volume icon -> The audio bar will be visible without any scroll.

Please check this functionality on develop and confirm that this is what finally we want. @BenHenning

**Comment by BenHenning** [comment]
Yep, this works really well after checking it again. Thanks!
