### ISSUE TITLE
App frozen on the Oppia logo screen

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#3812]
The app when opened using pixel phones gets stuck at the first screen with Oppia logo. Please see the screenshot attached. 
(No error is shown when this behavior occurs)

1. Go to Oppia app on Pixel phone
2. Click on the app icon
3. The screen with Oppia logo comes up, and will stay without moving to the profiles  tab.

Additional info:  Uninstalling and  reinstalling displayed the same issue.

Device issues observed on:
- Pixel 3, 4XL

**Comment by anandwana001** [comment]
Thank you @srushtirk for filing this issue. 
1. What API level does this Pixel 3, 4XL have? 
2. The screenshot is missing in the issue as given `Please see the screenshot attached.`
3. Does the Oppia app installed using Gradle or Bazel built?

**Comment by srushtirk** [comment]
Hi Akshay - 

1. The API level for Pixel 3 is 30 (Android version 11)
2. Added screenshot
3. NA

![a1177d9f-5e32-4d24-9ecb-7136edb4d90f](https://user-images.githubusercontent.com/27875087/134045191-3b0ee4c7-cf81-4cf8-a085-d615df743e3f.png)

**Comment by srushtirk** [comment]
App seems to work fine with Pixel 3/5 now.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).
