### ISSUE TITLE
Chapter Expand/Collapse not working when launched from Recently-Played

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3818]
**Describe the bug**
The expand and collapse feature doesn't work correctly when the topic's lesson tab opened from recently played cards from the Home Screen. 

**To Reproduce**
1. Go to the home screen 
2. Play some exploration
3. Go back to the home screen, the recently played exploration will appear
4. Click on any card and lesson tabs open
5. Click on expand collapse icon - it will not work

**Expected behavior**
It should expand and collapse correctly. 

**Device**
- Device being used
- SDK version - Android 11

**Comment by app-phyrem** [comment]
I will work on this issue. Please assign this to me

**Comment by darkmat13r** [comment]
I will work on this issue. Please assign this to me.

**Comment by anandwana001** [comment]
@darkmat13r I had assigned it to you, you can reach out to your onboarding mention in case you find any difficulty with the codebase. Though, it looks like this will be your first issue so I suggest looking for a good first issue as they help you in building a good understanding of the codebase.

**Comment by darkmat13r** [comment]
@anandwana001 Thank you.

**Comment by BenHenning** [comment]
@anandwana001 was this reproed on develop or was this part of MR3 testing?

**Comment by anandwana001** [comment]
This is for develop branch.
