### ISSUE TITLE
English text present in Arabic language 

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#3820]
**Describe the bug**
Some of the cards and text is being displayed in English on selecting Arabic language for the app.
(Text wrapping and translations issue)

**To Reproduce**
1. Install Oppia app on android phone
2. Change the phone language to "Arabic"
3. Open the app and navigate through lessons

**Expected behavior**
All text should be displayed in Arabic language

**Screenshots**
1. Lesson Title
![image](https://user-images.githubusercontent.com/27875087/134048785-36bbe93d-29e1-4a2d-82dc-56a263788ea5.png)

2. "Lessons" (the word 'lessons' followed by # of lessons contained in each topic)
![image](https://user-images.githubusercontent.com/27875087/134048830-a5bcc557-5f43-4603-b07e-b44cab99a2b4.png)

3. "Admin", Lesson titles and description
![image](https://user-images.githubusercontent.com/27875087/134048900-3e119491-7b56-4e75-b94f-028c26b38968.png)
![image](https://user-images.githubusercontent.com/27875087/134049544-ce25e878-d28f-43e8-b2df-88df629f1d9a.png)

4. First page and descriptions for the lessons, with some inconsistent Arabic words and numbers
![image](https://user-images.githubusercontent.com/27875087/134049233-978e1ac4-8f36-4be4-b54a-54ead8d5ef10.png)
![image](https://user-images.githubusercontent.com/27875087/134049373-8c3d4e78-b5e3-4dea-98ab-7a60e1e28ddd.png)

5. Revision cards
![image](https://user-images.githubusercontent.com/27875087/134049466-c1cf1cfc-8e0d-49f4-b871-44154e051d4c.png)

**Device**
- Device used: Pixel 4XL
- Android 11 
- App version: 0.6-alpha-908d57b2b1

**Additional context**

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).

**Comment by seanlip** [comment]
Closing this issue since these have all been fixed apart from the revision card translations, which are currently unavailable in Web (once they are, we can start a separate effort to bring these to the Android app).
