### ISSUE TITLE
[Portuguese] Text cut off in the title for onboarding slide 1

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#3822]
**Describe the bug**
Title text appears to be cut off on the onboarding slide 1 title "Adicione usuários à sua " screen in the app.

**To Reproduce**
1. Set device language to Portuguese
2. Go to Oppia App
3. After the green Oppia Screen , the onboarding screen to add profiles appears
4. See the error on the title for this screen as "Adicione usuários à sua" 

**Expected behavior**
The title should appear as "Adicione usuários à sua conta."

**Demonstration**
Per https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/values-pt-rBR/strings.xml: 
Line 212: <string name="onboarding_slide_1_title">Adicione usuários à sua conta.</string>

![image](https://user-images.githubusercontent.com/27875087/134089215-dc18660b-76e9-43d9-b73b-a43971c99d82.png)

**Environment**
- Device/emulator being used: TBD
- Android or SDK version (e.g. Android 5 or SDK 21): TBD
- App version: TBD

**Additional context**
Per chat with @BenHenning , some strings need to have max lengths defined. This is not specified in the app currently, and needs to be added.

**Comment by BenHenning** [comment]
I believe this isn't a blocker for MR3 (& am thus removing it from our blocker list). If I got that wrong, please re-add it @srushtirk.

**Comment by rt4914** [comment]
@coder2699 Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).

**Comment by KolliAnitha** [comment]
Working fine in beta build 0.10-beta-5e64fae55e. 
![Screenshot_20221114-130642](https://user-images.githubusercontent.com/101634267/201603037-911df09e-0927-4a3a-831d-bcc752f101a2.jpg)
