### ISSUE TITLE
Black square around the profile picture 

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#3826]
**Describe the bug**
On editing the profile picture, a black square appears around the profile pic.

**To Reproduce**
1. Go to Oppia app
2. Click on user profile
3. Click on edit - pencil icon over the profile picture 
4. Change the profile picture
5. Save
6. See error 

**Expected behavior**
Profile picture should not have anything surrounding it - it should be displayed in a circle.

**Screenshots**
![image](https://user-images.githubusercontent.com/27875087/134093749-cbf9593d-ebde-467f-a6a9-5787f958157c.png)

**Device**
- Device - TBD
- SDK version - TBD
- App version - 0.6-alpha-908d57b2b1

**Additional context**
Device language was selected as Portuguese for testing.

**Comment by coder2699** [comment]
@srushtirk , @anandwana001 I want to fix this. Can I start working on this issue?

**Comment by srushtirk** [comment]
Hi @coder2699 , thanks for your interest in helping out! Just to check, have you followed the instructions on https://github.com/oppia/oppia-android/wiki yet? If so, your onboarding mentor can assign you to the appropriate issues - could you please ask them? Thanks!

**Comment by coder2699** [comment]
@srushtirk all my steps are completed.

**Comment by BenHenning** [comment]
I believe this isn't a blocker for MR3 (& am thus removing it from our blocker list). If I got that wrong, please re-add it @srushtirk.

**Comment by coder2699** [comment]
@srushtirk I am able to reproduce this bug. But I'm unable to locate this exact layout file, if possible can you help regrading this?

**Comment by srushtirk** [comment]
@coder2699 What layout file are you referring to? Is it this one - https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/values-pt-rBR/strings.xml

**Comment by anandwana001** [comment]
@coder2699 Look at the XML file here - https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/layout/profile_picture_activity.xml

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).
