### ISSUE TITLE
[Portuguese] Translated text overlap

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#3827]
**Describe the bug**
Text overlap has been observed with the translated text in Portuguese.

**To Reproduce**
1. Go to Oppia app
2. Click on admin profile
3. See error 

**Expected behavior**
Text should be separated and should not overlap over one another. 

**Demonstration**
![image](https://user-images.githubusercontent.com/27875087/134094703-4bf2ce9d-ad28-4f5e-8c55-e4d3d9a4d80f.png)

**Environment**
- Device: TBD
- Android: TBD
- App version: 0.6-alpha-908d57b2b1

**Additional context**
Device language was selected as Portuguese for testing.
Per discussion with @BenHenning this could be a size length or a text wrapping issue.

**Comment by BenHenning** [comment]
I believe this isn't a blocker for MR3 (& am thus removing it from our blocker list). If I got that wrong, please re-add it @srushtirk.

This is a good issue to track looking into adding max character lengths for strings.

**Comment by coder2699** [comment]
@srushtirk I'm willing to work on this. So I'm self-assigning this.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).
