### ISSUE TITLE
Incorrect Audio Language displayed

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#3828]
**Describe the bug**
The audio language is being displayed as 'Hindi' for device language of Portuguese in the app.

**To Reproduce**
1. Go to Oppia app and user profile
2. In user profile menu, select options
3. See error: Audio Languge appears as Hindi 

**Expected behavior**
Audio language should be displayed as 'Portuguese'

**Demonstration**
![image](https://user-images.githubusercontent.com/27875087/134094938-cd99e7df-5dfe-4159-b667-725a459e9bad.png)

**Environment**
Device: TBD
Android: TBD
App version: 0.6-alpha-908d57b2b1

**Additional context**
Device language was selected as Portuguese for testing.

**Comment by BenHenning** [comment]
I believe this isn't a blocker for MR3 (& am thus removing it from our blocker list). If I got that wrong, please re-add it @srushtirk.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).

**Comment by BenHenning** [comment]
So looking at this again, I don't actually think this is a bug. The audio language is selected independently of the device language, and we don't currently have support for automatically populating the audio language based on the device language.

**Comment by KolliAnitha** [comment]
As the audio language is independent of device language, after changing device language to Protugese any audio language can be d
![Screenshot_20221114-123150](https://user-images.githubusercontent.com/101634267/201596699-b5ca82ab-e90b-41b8-88d3-934d7f13196b.jpg)
isplayed and now english is displayed
