### ISSUE TITLE
"Start over" button missing left border in the UI

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#3833]
**Describe the bug**
The button "Start Over" after returning to an incomplete lesson in the app is missing left border around it or the left side of the button is possibly being cut off.

**To Reproduce**
1. Go to a lesson in the app
2. Play at least 2 cards and leave the lesson
3. Click on the incomplete lesson and see a screen that prompts to start over vs. continue from where you left off
4. See error in the 'Start Over' button

**Expected behavior**
'Start Over" button should have all borders consistent around it.

**Demonstration**
![image](https://user-images.githubusercontent.com/27875087/134443760-b1f61352-c91e-4db7-afc4-7864711e820f.png)

**Environment**
- Device/emulator being used: Honor-6X
- Android or SDK version (e.g. Android 5 or SDK 21): Android 7
- App version: 0.6-alpha-908d57b2b1

**Additional context**

**Comment by BenHenning** [comment]
I believe this isn't a blocker for MR3 (& am thus removing it from our blocker list). If I got that wrong, please re-add it @srushtirk.

**Comment by srushtirk** [comment]
Note that this issue is not seen on Pixel (3, 4XL, 5) devices (Android 11+).

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).

**Comment by KevinGitonga** [comment]
Closing this since it is possibly the same issue as #4710 whereby resume lesson screen buttons are not scaling as expected when font size and display are set to max on device settings.
