### ISSUE TITLE
Make sure all tests end in "Test"

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3837]
Currently, at least two tests aren't ending with "Test": ProfileProgressSpanCount & PlayerSplitScreenTesting. Both should be renamed such that they end in "Test", and all other files in test folders should be double checked to make sure that they end with "Test".

**Comment by justdvnsh** [comment]
@BenHenning I'd like to work on this issue

**Comment by ayaazansari** [comment]
I'd like to work on this
