### ISSUE TITLE
'time_ago' & quantity plurals should be combined

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3841]
After #3795, TextViewBindingAdapters combines two strings (time_ago & plurals) into a single one. This ought to just be different plural options so that translators have better context when translating the full conceptual string.

**Comment by maityamit** [comment]
Hi, can I work on this issue, I go through the whole codebase and for this issue, I got an idea to solve it. Please verify this idea. If it is valid you can assign me, I want to contribute and fix that issue.  @adhiamboperes 

**Code:** 
```
  private static String getPluralString(
      AppLanguageResourceHandler resourceHandler,
      @PluralsRes int pluralsResId,
      int count
  ) {
    // TODO(#3841): Combine these strings together.
    return resourceHandler.getStringInLocaleWithWrapping(
        R.string.time_ago,
        resourceHandler.getQuantityStringInLocaleWithWrapping(
            pluralsResId, count, String.valueOf(count)
        )
    );
  }
```

**Idea to Solve:**  
I can retrieve the "time_ago" string and the plural string separately, and then concatenate them together. The combined string is then returned as the final result. This way is right ?

**Comment by adhiamboperes** [comment]
Hi @maityamit, that's a good start. Do you know which screen/screens are affected by this, and to do you know which plurals will be affected? Could you please share those with me?

**Comment by adhiamboperes** [comment]
Hi @BenHenning , Could you clarify a bit on what is required for this issue:

Given the lines of code being referred to is:
```
// TODO(#3841): Combine these strings together.
    return resourceHandler.getStringInLocaleWithWrapping(
        R.string.time_ago,
        resourceHandler.getQuantityStringInLocaleWithWrapping(
            pluralsResId, count, String.valueOf(count)
        )
```

I can see in the strings file we already have 

 ` <string name="time_ago">%s ago</string>`
 
 and 
 
  ```
 <plurals name="minutes">
    <item quantity="one">a minute</item>
    <item quantity="other">%s minutes</item>
  </plurals>
  <plurals name="hours">
    <item quantity="one">an hour</item>
    <item quantity="other">%s hours</item>
  </plurals>
  <plurals name="days">
    <item quantity="one">a day</item>
    <item quantity="other">%s days</item>
  </plurals>
```

I'm guessing what we want is something like: 

```
 <plurals name="minutes_ago">
    <item quantity="one">a minute ago</item>
    <item quantity="other">%s minutes ago</item>
  </plurals>
```

**Comment by BenHenning** [comment]
@adhiamboperes I think the last example for plurals sounds good (having one per category of time). Beyond that, we should also add 'zero' as a case per https://developer.android.com/guide/topics/resources/string-resource#Plurals since that's specially handled in different languages.
