### ISSUE TITLE
Completed/ongoing story strings should be separate text views rather than a combined string

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3843]
After #3795, NavigationDrawerHeaderViewModel combines two strings (for ongoing & completed stories) into a single one. String concatenation should never be used for display purposes since it can be wrong in LTR/RTL situations. Instead, there should be separate text views or a single string to represent the text.

**Comment by jkugsiya** [comment]
Hi, can I work on this issue, I have worked in this repo before, but its been long time, so I want to start again to contribute, so this will be a good re-starting point for me.

**Comment by MohitGupta121** [comment]
Hi @jkugsiya , can you give a brief description of how you are tackling this? What files have you changed, what is the actual cause of the issue?

Feel free to post your approach here and if it looks like it is in the right direction, we can assign this to you. Thanks!

**Comment by jkugsiya** [comment]
> Hi @jkugsiya , can you give a brief description of how you are tackling this? What files have you changed, what is the actual cause of the issue?
> 
> Feel free to post your approach here and if it looks like it is in the right direction, we can assign this to you. Thanks!

Hi @MohitGupta121, the way I want to tackle this is to create two separate views to display the text, I would like to have assistance in approaching the same.

**Comment by MohitGupta121** [comment]
Okay Thanks @jkugsiya Please go ahead.
Feel free to ask any things. Thanks!

**Comment by jkugsiya** [comment]
Hi @MohitGupta121, where can I ask questions regarding this as I am starting again and want to re-gain the concepts. Or can you please brief me through this as what to be implemented. 

Thanks and apologies for this much delay.

**Comment by MohitGupta121** [comment]
@jkugsiya Totally fine, You can ask your queries in the [Github-discussion](https://github.com/oppia/oppia-android/discussions)  Tab of oppia-android.

**Comment by adhiamboperes** [comment]
Unassigning @jkugsiya due to inactivity

**Comment by dev-divyansh** [comment]
@adhiamboperes I would like to work on this issue

**Comment by adhiamboperes** [comment]
@dev-divyansh Feel free to post your approach here and if it looks good, we will assign this to you. Thanks!

**Comment by dev-divyansh** [comment]
@adhiamboperes Sorry  , for the late reply was  busy with other stuff.
I would  separate the two strings and use separate views to display them.

**Comment by ayush290104** [comment]
@adhiamboperes on checking the code for welcome viewmodel and its layout what i saw is that there are already two seperate textviews for both the texts welcome and name.
Can you guide.
![Screenshot (34)](https://github.com/oppia/oppia-android/assets/116818222/f34b0480-8ef6-4904-9da9-95fb2fe1536f)

**Comment by dev-divyansh** [comment]
@adhiamboperes what u say ??

**Comment by adhiamboperes** [comment]
> @adhiamboperes what u say ??

Feel free to put up a PR showing your proposed solution.

**Comment by adhiamboperes** [comment]
> @adhiamboperes on checking the code for welcome viewmodel and its layout what i saw is that there are already two seperate textviews for both the texts welcome and name. Can you guide. ![Screenshot (34)](https://user-images.githubusercontent.com/116818222/257066263-f34b0480-8ef6-4904-9da9-95fb2fe1536f.png)


This issue requests changes in `NavigationDrawerHeaderViewModel`
