### ISSUE TITLE
Add tests for TextViewBindingAdapters

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3846]
TextViewBindingAdapters today doesn't have any tests for it, and ought to since it may not be obvious to track down future regressions that may occur in this file. These tests also ought to specifically test the binding adapters in their normal context (i.e. used through databinding with a test layout).

This also tracks adding new testing coverage after #3795 is merged since https://github.com/oppia/oppia-android/blob/baf7fd23affbf7dc27192a24fbb881e10519d2e7/utility/src/test/java/org/oppia/android/util/system/OppiaDateTimeFormatterTest.kt is being removed & its behaviors are now part of TextVIewBindingAdapters directly (so the same behaviors from that test suite should be added to the test suite for TextViewBindingAdapters).

**Comment by justdvnsh** [comment]
@BenHenning I'd Like to work upon it.

**Comment by rt4914** [comment]
@rishidyno Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by rishidyno** [comment]
@rt4914 @BenHenning @anandwana001 do I need to create a layout file for `TextViewBindingAdaptersTestActivity`
like (eg: 
 `test_image_view_bindable_adapter_activity` was made for `ImageViewBindingAdaptersTestActivity`)

as for now, I have created a layout file for the same with a textview.

Also as I don't have much experience in writing tests. Could you please give me a few examples for writing tests for binding adpters and explain them to me. Also, are there any prerequisites like learning something new in particular for this PR, please let me know and suggest some resources for the same? Thanks.

**Comment by BenHenning** [comment]
@rishidyno you will need to create a test activity & layout (so that you have an easy-to-access TextView to test the adapters). In terms of how they work, I suggest looking at https://github.com/oppia/oppia-android/blob/develop/app/src/sharedTest/java/org/oppia/android/app/databinding/MarginBindingAdaptersTest.kt or other tests from that databinding package. Generally, the way we test binding adapters is by calling them directly to ensure that whatever they're supposed do/change actually happens.

In terms of actually writing tests, I suggest reading over https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#learning-how-to-write-good-tests including the corresponding presentation, if you haven't already.
