### ISSUE TITLE
Remove Pinview thirdparty library.

### ISSUE THREAD

**Issue by veena14cs** [oppia/oppia-android#3855]
Older implementation of Pin Verification UI was using PinView library `io_github_chaosleung_pinview`  which was not supporting RTL. To fix this we removed this library and created new UI as per the new mocks implemented in the PR #3684.

This library has to be removed from
```
BUILD.bazel
build.gradle
versions.bzl
```

Then update `maven_intall.json` file.

**Comment by justdvnsh** [comment]
@veena14cs I'd like to work on this issue.

**Comment by veena14cs** [comment]
Thanks @justdvnsh I will assign it to you.

**Comment by BenHenning** [comment]
De-assigning since #3884 was auto-closed from being stale. @justdvnsh if you're still working on this, please let us know and we can reassign this & reopen the PR.
