### ISSUE TITLE
Submit-time errors permanently break the answer submission flow

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3861]
**Describe the bug**
When a submit-time error is encountered, attempting to submit another answer (regardless of correctness) causes an error to be logged in logcat and the submit button stops working (the entire exploration experience goes into a bad state).

**To Reproduce**
1. Open the prototype exploration
2. Navigate to the fraction input state (second state)
3. Input "1/" and click submit
4. Observe the submit-time error
5. Now, try to input "1/2"
6. Observe that the submit button goes gray, no feedback is given, and the exploration is now broken (including back navigation)

Note that navigating away & back to the lesson (e.g. via checkpointing) fixes the issue & is probably a reasonable mitigation in the meantime.

**Expected behavior**
Submit-time errors should not break the lesson experience.

**Demonstration**
None--this is fairly easy to repro so no demo was added.

**Environment**
- Device/emulator being used: Nexus 5X
- Android or SDK version (e.g. Android 5 or SDK 21): SDK 27
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.6-dev-7ff1b2bbd2

**Additional context**
This was found during alpha MR3 development, but it's not specifically tied to the MR3 release.

**Comment by anandwana001** [comment]
The steps to reproduce has a nit change for me

1. Open the prototype exploration
2. Navigate to the fraction input state (second state)
3. Input "1/" and click submit
4. Observe the submit-time error (Error log in logcat)
5. Now, try to input "1/2"
**6. The submission button goes green**
**7. Click on submit and nothing happen and then it goes to gray.**
8. Observe that the submit button goes gray, no feedback is given, and the exploration is now broken (including back navigation)

Working on it.

Error Log 
```
org.oppia.android E/StateFragment: Failed to retrieve answer outcome
    kotlin.UninitializedPropertyAccessException: lateinit property answerOutcome has not been initialized
        at org.oppia.android.domain.exploration.ExplorationProgressController.submitAnswer(ExplorationProgressController.kt:202)
        at org.oppia.android.app.player.state.StateFragmentPresenter.handleSubmitAnswer(StateFragmentPresenter.kt:403)
        at org.oppia.android.app.player.state.StateFragmentPresenter.onSubmitButtonClicked(StateFragmentPresenter.kt:193)
        at org.oppia.android.app.player.state.StateFragment.onSubmitButtonClicked(StateFragment.kt:105)
        at org.oppia.android.databinding.SubmitButtonItemBindingImpl._internalCallbackOnClick(SubmitButtonItemBindingImpl.java:322)
        at org.oppia.android.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
```

**Comment by KolliAnitha** [comment]
Verified in 0.7-alpha-6c08d882d3. Feedback is seen after entering a fraction in the edit box.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).
