### ISSUE TITLE
Due to wrong Input Submit / Back button not working

### ISSUE THREAD

**Issue by puranjayK** [oppia/oppia-android#3875]
**Describe the bug**
On filling wrong type of input in Chapter 1: Prototype Exploration, the 'Submit' and back arrow button do not work. Unable to submit the correct answer after that or move to the previous activity.

**To Reproduce**
1. Scroll to 'All Topics'
2. Click on 'First Test Topic'
3. Click on 'Lessons'
4. Click on 'First Story'
4. Click on 'Prototype Exploration'
5. Fill in the answers till before the question ' Two numbers are respectively 20% and 50% more than a third number. The ratio of the two numbers is '.
6. Now fill in a fraction (for eg 2/5) and click 'SUBMIT'
7. Now fill in a ratio ( for eg 2:5) and click 'SUBMIT' or click the back arrow button
7. See the error

**Expected behavior**
The answer submitted should be checked whether it was correct or not and a output should have been shown. 
If the back button was pressed then it should have moved to the previous question

**Demonstration**

https://user-images.githubusercontent.com/85157266/135828941-3d4b8deb-de54-46a8-b078-7a91b6caa3f6.mp4

**Environment**
- Device/emulator being used: Pixel 5 API 30
- Android or SDK version (e.g. Android 5 or SDK 21): Android 11
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0

**Comment by binaryshrey** [comment]
Hi, I would like to take up this task.

**Comment by bkaur-bkj** [comment]
@binaryshrey are you still interested should I assign you this issue?

**Comment by bkaur-bkj** [comment]
Closing this issue as similar issue is listed under the issue [#4013](https://github.com/oppia/oppia-android/issues/4013)
