### ISSUE TITLE
Add Proguard support to oppia_alpha_kitkat

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3886]
A forthcoming PR is introducing basic KitKat support in the app, and one limitation is that we must manually define the main dex class list in order for the main dex file to be set up correctly for multidex to kick-in. While Bazel supports both this & Proguard individually, it has a bug today in supporting these together (there's a sandbox issue when trying to call into dex_list_obfuscator.sh). I'm working on a change to patch the issue, but we'll need to wait for an Android tools update & Bazel re-deploy so it may be weeks before the build works.

From there, I suspect additional work might be needed since dex_list_obfuscator.sh appears to no-op actually updating the dex list, so we might need to manually add keep rules for each of the files in that list (we just need to run the Proguard-optimized version of the KitKat app on a KitKat device to test).

**Comment by seanlip** [comment]
Per https://github.com/oppia/oppia-android/issues/5012, we are deprecating support for Android KitKat, so this issue is no longer valid.
