### ISSUE TITLE
Investigate Glide drawable native crash on KitKat

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3887]
After a forthcoming PR is merged to introduce basic KitKat support, there'a fairly common crash that occurs (especially on fresh install) on KitKat devices after opening the home screen. This seems to correlate to vector drawables that are loaded & transformed directly by Glide. It's not exactly clear what might be causing this crash, but it's expected to necessary to fix to unblock KitKat launch.

Further, this may not actually be a true problem in practice since we don't rely on the drawable mechanism for production since all thumbnails are loaded. This issue should investigate whether removing the drawable pipeline for thumbnails fixes the issue, and whether the other Glide transformation pipelines have the same crash potential.

**Comment by BenHenning** [comment]
https://github.com/bumptech/glide/issues/372#issuecomment-86835027 is a similar crash to what I saw.

**Comment by BenHenning** [comment]
Note: per #3939 this is also observed as happening on occasional reopens (sometimes consistently back-to-back).

That issue also includes a native trace that might be helpful in debugging or at least providing a bit more context.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).

**Comment by seanlip** [comment]
Per https://github.com/oppia/oppia-android/issues/5012, we are deprecating support for Android KitKat, so this issue is no longer valid.
