### ISSUE TITLE
Second layer of authentication to user profile PIN

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#3888]
**Is your feature request related to a problem? Please describe.**
When user forget their profile PIN, sometimes the app auto backs up and restores the profile and hence the PIN doesn't reset even after uninstalling and re-installing the app.

**Describe the solution you'd like**
Add a user chosen security question (from the list of 2-3 questions) as a second layer authentication (and back up) when the user forget their profile PIN. 

**Describe alternatives you've considered**
1. Clearing the storage in the app settings should reset all of the profiles so that the user can access the app. However, our users are not so familiar with tech and how to perform these steps.
2. TBD

**Additional context**

**Comment by BenHenning** [comment]
As discussed, assigning this to you @yash10019coder.

**Comment by srushtirk** [comment]
Here is the PRD for your reference: https://docs.google.com/document/d/1X3afsvo3XmzuJziWvzylFWbb4AEjwhtoSp1MyPNEXpA/edit#

**Comment by yash10019coder** [comment]
thanks @srushtirk I'll take a look at it

**Comment by yash10019coder** [comment]
@srushtirk I just check the access is denied for the doc can you make it public or provide access?

**Comment by BenHenning** [comment]
Just shared it with you @yash10019coder. Please follow up with me if you still can't access it.

**Comment by theMr17** [comment]
@adhiamboperes Is this feature still required?

**Comment by seanlip** [comment]
Thanks for checking @theMr17. From a product perspective, we won't do this until we see stronger need for it. Closing.
