### ISSUE TITLE
[A11Y] Locked chapter item selection change is incorrect

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3892]
Currently in `StoryActivity`, when we click on link in locked chapter, the previous unlocked-chapter should get selected automatically which is not happening currently.

https://user-images.githubusercontent.com/9396084/136243294-1ce2854c-878a-4921-b40d-7ac33315bc31.mp4

## IMPORTANT

This issue needs to be tested on Talkback app + Samsung screen readers too.

**Comment by rt4914** [comment]
@viktoriias Considering you have not yet created any PR for this issue, I am assigning this to @vrajdesai78

**Comment by viktoriias** [comment]
> @viktoriias Considering you have not yet created any PR for this issue, I am assigning this to @vrajdesai78

No problem, I'm having trouble with Android Studio permissions on my work laptop.

**Comment by vrajdesai78** [comment]
I am un-assigning it for now. In the future, if someone takes this issue, they can look at my closed PR #4201 in which I am sending focus to the toolbar instead of the first chapter story using sendAccessibilityEvent

**Comment by vrajdesai78** [comment]
I have tried various combinations of stories to check what is the exact problem. While debugging I have found that this issue is happening due to rendering content on screen. If I increase the size of fonts then the talkback reader is working completely fine as shown below. 

https://user-images.githubusercontent.com/43074241/180804703-84a6c115-4360-469a-a840-4d5075a8a495.mp4

**Comment by rt4914** [comment]
To add more details: if there are more items or if each item has more content in that case also the screen-reader does work correctly.

**Comment by rt4914** [comment]
## Expected Behaviour
When screen-reader is on, and there is no progress in the topic, in such scenario if user navigates to chapter-2 (locked) and click on `Complete Chapter 1 :..... to unlock this chapter` then the screen-reader should get shifted to chapter 1. Similarly if user clicks on same text in `Chapter 3 card` which shows `Complete Chapter 2: ... to unlock ...` then screen-reader should get shifted to chapter 2. See ideal flow in this video:

https://user-images.githubusercontent.com/9396084/186942121-1cf5f693-6913-4a23-87af-c94f243a3226.mp4

## Problem

For a very specific case in `develop` `First Topic`, if there is no progress and screen-reader user clicks on `Complete Chapter 1 :..... to unlock this chapter` the `Chapter-1 Card` does not get selected. See below video for problem:

https://user-images.githubusercontent.com/9396084/186942576-abaf09f6-6613-476d-8c08-20c837fc0601.mp4

## Solution

Actually changing anything in code did not work at all. Mainly I explored around `LinkMovement` and also correct index shifting in onClick function on clickable spans but after some more trial and tests these are the results that I found.

## Attempted Solution 1
If I change the screen-width of my device to small and increase the font-size to largest, basically making sure that the overall view is zoomed-out as much possible, in this case the same situation does work correctly. See below video:

https://user-images.githubusercontent.com/9396084/186943328-561eb6a8-0003-42a8-8005-a5faaf41ba88.mp4

## Attempted Solution 2
In this I simply changed the `description` of chapter such that it covers more and more screen and as a result this also worked correctly. See below video:

https://user-images.githubusercontent.com/9396084/186943601-c6c053aa-7a8a-488f-9ef8-a9c21a4254c1.mp4

## Conclusion

Combining solution 1, solution 2 and the results of `Place Values`, the common factor that I was able to think was following: if the chapter-1 card is big enough such that chapter-2 card is out-of-screen at start then the screen-reader will work correctly.
Based on this theory, it does make sense why its failing for only chapter 2 to shifting chapter 1 only and not for chapter3, 4, 5, etc because they are already out-of-screen when UI is laid out.

In all this no code was changed and therefore it looks like the screen-reader (Talkback) is itself working unexpectedly here and this is something which cannot be solved with code.

**Comment by BenHenning** [comment]
@rt4914 what mechanism are we using to try and focus on the specific card when the link is clicked?

**Comment by rt4914** [comment]
@BenHenning There are only three things for this functionality:

1. The [clickableSpan](https://github.com/oppia/oppia-android/blob/1ca0a4ae238a8075fb552ef4ccb66ef60a8459f0/app/src/main/java/org/oppia/android/app/story/StoryFragmentPresenter.kt#L186) - This makes sure that the text is clickable.
2. [LinkMovement](https://github.com/oppia/oppia-android/blob/1ca0a4ae238a8075fb552ef4ccb66ef60a8459f0/app/src/main/java/org/oppia/android/app/story/StoryFragmentPresenter.kt#L208) - This makes sure that there is movement of **focus** between different hyperlinks.
3. Finally [scroll](https://github.com/oppia/oppia-android/blob/1ca0a4ae238a8075fb552ef4ccb66ef60a8459f0/app/src/main/java/org/oppia/android/app/story/StoryFragmentPresenter.kt#L187) - This function basically accepts the position to which the scroll should work. 


Similar to `[LinkMovement](https://developer.android.com/reference/android/text/method/MovementMethod)` there are other movementMethods too but I think for our case `LinkMovement` is the correct one. 
Although there is one edge case:
If Chapter -1 is unlocked and chapter -2 is locked, when user is inside chapter-2 card and clicks on `Complete Chapter 1... to unlock...` in that case the `LinkMovement` will try to find another `hyperlink` but won't be able to. In theory it looks like for chapter-2 card the movement of link should never work but it does shift to Chapter-1 card in almost every case (**except the failure case mentioned above.**). 

If we remove `LinkMovement` then the alternative can be to bring focus on item programmatically but I am afraid it might fail on other screen-readers. Also even if this focus solution works it might fail fore regular users. (Haven't tried this, just mentioning what I remember about these concepts).

**Comment by BenHenning** [comment]
@rt4914 this might be a case where we need to specialize the behavior for a11y users. Just thinking about this from a UX perspective, it's generally not a good pattern to move a screenreader's focus since it can be really disorienting. Simply telling them that another chapter needs to be completed first should be sufficient since they can navigate to the other one themselves.

There's also the principle that there should be parity between screenreader & non-screenreader UX (since often things that benefit screenreader users also benefit non-screenreader users), but I think we do want to intentionally err away from that here since we know that some of our users need extra direction given lack of familiarity with devices (which is less likely to occur with a11y users). Until we have more data to suggest otherwise, I think it's fair to assume that just the verbal direction would be enough here for screenreader users (as long as that description is really clear).

What do you think about this UX shift?

**Comment by rt4914** [comment]
@BenHenning Makes complete sense. I will try to see what best solution can be implemented for non-sighted users.
