### ISSUE TITLE
[A11Y Advanced] Lessons tab flow needs to be improved

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3896]
Lessons tab flow needs to be improved. Current experience is shown below:

https://user-images.githubusercontent.com/9396084/136244615-eb6b4f3f-e676-485d-9477-579822845039.mp4

**Comment by BenHenning** [comment]
To clarify, is this an advanced test failure?

**Comment by rt4914** [comment]
Yes. This is an advanced test.

**Comment by bkaur-bkj** [comment]
@rt4914 sir I would like to discuss on this issue, what is meant by advanced test failure? and do we have any expected flow which would be better than this or we need to figure it out

**Comment by rt4914** [comment]
@bkaur-bkj Actually this issue is part of [A11Y] Advanced and currently we are focused on [A11Y] Basic and based on that I suggest you pick up something from that. 
For clarification part, the video shows that each and every UI item is browsable(can be visited) but the flow is incorrect and experience is bad. The aim of this issue is to somehow make the experience better. The best experience would be to simulate the behaviour of any regular user.
