### ISSUE TITLE
[A11Y] Remove blank space from QuestionPlayer

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3901]
[A11Y] Remove blank space from QuestionPlayer as it is readable by screen-reader.

<img src="https://user-images.githubusercontent.com/9396084/136251065-b26154c6-8a13-4bc7-aa29-b170076115f3.png" width="250" />

**Comment by adarrssh** [comment]
Hey I am a beginner ,I would like to work on this issue .
what i have to do in this issue and what can i do to get started?

**Comment by rt4914** [comment]
@adarrssh Thanks for showing interest. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

Once this is done please pick issues from [here](https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22good+first+issue%22).

**Comment by adarrssh** [comment]
Hey, I am facing an issue while installing the project, where can I discuss my issue?

**Comment by rt4914** [comment]
@adarrssh You can post it on https://gitter.im/oppia/oppia-android

**Comment by adarrssh** [comment]
Hey, I have installed oppia-android on my PC and it is running fine, but I am getting error in 4th step of installation process (https://github.com/oppia/oppia-android/wiki) and I am not getting any response on gitter about my issue .what can I do to solve this issue?


![image](https://user-images.githubusercontent.com/85433137/136685856-646031a3-4dd8-4b3c-ad08-2d151cfc9798.png)

**Comment by adarrssh** [comment]
Is this issue still open?

**Comment by rt4914** [comment]
@adarrssh As mention above please pick issues from [here](https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22good+first+issue%22).

Also I am currently working on this.

**Comment by bkaur-bkj** [comment]
@rt4914 sir the PR above #3928 seems to actually have solved this issue of removing blank space, but the PR is closed now So are you working on this issue?
