### ISSUE TITLE
[A11Y] Incorrect a11y output for welcome text

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3902]
Incorrect a11y output for welcome text. There is an extra `,` in the output.

<img src="https://user-images.githubusercontent.com/9396084/136251218-5e6b5487-aa5b-4f95-ab89-1d857de45b9c.png" width="250" />

Update:
The extra `,` is because there are two separate textview and screenreader is combining both the textviews at once and as a result we see one extra `,`  which is added by screenreader. To fix this we can mark both the textviews as `importantForAccessibility=no` and use `contentDescription` for `FlexboxLayout` `android:contentDescription="@{viewModel.greeting + viewModel.computeProfileNameText()}"`

**Comment by JishnuGoyal** [comment]
May I work on this?

**Comment by rt4914** [comment]
> May I work on this?

@JishnuGoyal Thanks for showing interest. Please, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on. Also pick issues from [here](https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22good+first+issue%22).

**Comment by rt4914** [comment]
Closing this for #3930
