### ISSUE TITLE
[A11Y] Add hint for question

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3903]
Add hint for question mentioned below:

<img src="https://user-images.githubusercontent.com/9396084/136251414-eb008efc-c6a3-4942-b8a7-418dc7f5e7cc.png" width="250" />

**Comment by bkaur-bkj** [comment]
@rt4914 I would like to work on this issue.

**Comment by bkaur-bkj** [comment]
@rt4914 I am a bit confused about this issue as I opened the app screen and found that the EditText already has a hint so what needs to be done?

![WhatsApp Image 2021-10-20 at 7 37 54 PM](https://user-images.githubusercontent.com/64087572/138109229-8c591d69-0af4-47ce-b9e4-a788ea9be87a.jpeg)

**Comment by rt4914** [comment]
@bkaur-bkj Thanks. Quite weird. But you are actually correct. The hint is available in json file. https://github.com/oppia/oppia-android/blob/63adb8b66242626083cbc3db65ac09915fd579b3/domain/src/main/assets/questions.json#L171

Closing this issue.
