### ISSUE TITLE
[A11Y] Incorrect output for rich-text in Hints and Solution

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3906]
Incorrect output for rich-text in Hints and Solution.
<img src="https://user-images.githubusercontent.com/9396084/136251962-5cb5b12d-434e-4d22-b3cc-f2b784e3cc49.png" width="250" />

**Comment by BenHenning** [comment]
@rt4914 does this block on #1050?

**Comment by deepanshu731** [comment]
@rt4914 how to reproduce this issue ? can you help me out with this

**Comment by rt4914** [comment]
@deepanshu731 Unassigning this issue because of inactivity let me know if you  are still working on this.

**Comment by vrajdesai78** [comment]
I am un-assigning this issue for now as it is blocked on #3852. Will continue work on this once #3852 will merge
