### ISSUE TITLE
Introduce end-to-end test to ensure KitKat startup support

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3911]
With the introduction of #3910 we need an end-to-end test that opens up the app on a KitKat emulator to verify that it starts successfully since it's quite likely future changes to the OppiaApplication class will break app startup on KitKat devices.

**Comment by seanlip** [comment]
Per https://github.com/oppia/oppia-android/issues/5012, we are deprecating support for Android KitKat, so this issue is no longer valid.
