### ISSUE TITLE
Build gets failed with an errror at develop branch on windows PC

### ISSUE THREAD

**Issue by bkaur-bkj** [oppia/oppia-android#3916]
Build is failing, I tried to build the project to work on my new issue and faced this error, tried updating multiples times but no help.

Operating system - Windows
![image](https://user-images.githubusercontent.com/64087572/136619134-b87c3c66-1631-4c07-9ce8-d6727a7916a8.png)

**Comment by BenHenning** [comment]
@bkaur-bkj did you try a clean + rebuild? I'm wondering if this is a syncing issue from recent changes.

**Comment by BenHenning** [comment]
Also, is this on the latest develop? A commit hash of your base would be helpful to make sure that we understand what state your local repository is in.

Edit: and, is this a clean repository or are there changes? If there are changes, does the project build with in a clean/unchanged state?

**Comment by BenHenning** [comment]
Finally per https://github.com/oppia/oppia-android/pull/3910/files the most recent changes to these files should be innocuous, and not related to the dimensions.

**Comment by bkaur-bkj** [comment]
> @bkaur-bkj did you try a clean + rebuild? I'm wondering if this is a syncing issue from recent changes.

Yesterday I tried to rebuild it gave the same results, I tried closing studio updating and then building again it worked fine now so I think we can close the issue now.

**Comment by BenHenning** [comment]
Got it. I suspect this was some sort of caching issue with Gradle @bkaur-bkj. Glad that it's working now--thanks for checking again!
