### ISSUE TITLE
Greeting text on home screen should be a single TextView

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3930]
For localization, it's hard to make sure that the reversed text for each of the two TextViews that comprise the home screen greeting correctly match the flipped layout that Android forms. This is *mostly* correct today, but it would be more correct if we could combine the strings together. The main challenge has been making sure that:
1. That the line properly extends the whole length of the TextView
2. That when the profile name is really long or display text is large, that the name properly wraps to the next line & the underline is properly resized to not extend past the last character

Another issue with current code is that the screen-reader reads it as `Good Morning,, Rajat!`. Basically there is one extra `,`. This is because the screen-reader adds `,` between two textviews and we already have one `,` in text itself.

<img src="https://user-images.githubusercontent.com/9396084/136251218-5e6b5487-aa5b-4f95-ab89-1d857de45b9c.png" width="250" />

**Comment by ihrishix** [comment]
Can I work on this ?

**Comment by rishidyno** [comment]
Thanks @rushikeshsuryawanshi.

**Comment by rt4914** [comment]
@rishidyno I am removing the `good-first-issue` tag as this is actually a complicated issue. 
@rushikeshsuryawanshi Feel free to work on it but if it becomes complicated then please pick a different good-first-issue.

**Comment by ihrishix** [comment]
@rt4914 
Yeah Sure ! 
Working on this.

**Comment by yashbansal130** [comment]
@rt4914 can i work on this?

**Comment by yashbansal130** [comment]
@yash10019coder can i work on this

**Comment by yashbansal130** [comment]
@rishidyno can you guide like what exactly i have to do in this one

**Comment by rishidyno** [comment]
@yashbansal130 did you read the description of the issue? [Description](https://github.com/oppia/oppia-android/issues/3930#issue-1026630209)

**Comment by yashbansal130** [comment]
like in #3902 it appears in the toast message that there are two "," but in the layout its showing only one, why is that happening, why is the extra "," not appearing in textview but in Toast messsage it is appearing?

**Comment by yashbansal130** [comment]
@rishidyno 
I found out that there are two separate textview for greeting message and the message of the user.

![Screenshot from 2022-02-09 14-48-08](https://user-images.githubusercontent.com/66557534/153164344-eeaf23c1-531c-42ed-a048-f05e09bdc1b1.png)

since both of the texts are databinded i can use a single textview, so either i have to remove first textview of the greetings message or the second, the ids of both the textviews have a lot of usage so i have to refactor those usages i wanted to know which textview should i remove, i am attaching the usages of both the textview
![Screenshot from 2022-02-09 14-53-24](https://user-images.githubusercontent.com/66557534/153164982-439eebcf-9af9-4c1f-aaaa-536f50c7580b.png)
![Screenshot from 2022-02-09 14-48-46](https://user-images.githubusercontent.com/66557534/153165140-7825f5b3-fb9b-463e-a265-0e9acf5eccb7.png)

according to me i think i should remove the first one, what is your opinion?

**Comment by rishidyno** [comment]
It does not matter which one you remove, basically you have to find out a solution such that the functionality remains same as earlier. If we merge these two text view it will work better in RTL and we can also get rid of double commas when screen reader is on. Just manage the string resource which we are getting from view model in a singel textview. I hope this makes sense.

**Comment by yashbansal130** [comment]
@rishidyno functionality will remain same after removing the first textview and it does not have much of usages, but it has usages in androidTests so those tests would no longer pass.
what to do with them?

**Comment by rishidyno** [comment]
I think the test will have to modify accordingly. Can you please link the test file here.

**Comment by yashbansal130** [comment]
ya sure 
https://github.com/oppia/oppia-android/blob/develop/app/src/sharedTest/java/org/oppia/android/app/home/HomeActivityTest.kt

**Comment by rishidyno** [comment]
So looking at it you will have to combine the test which says the user name which is Admin in our case and the greetings text. I can see that there are 3 different timestamps for which we are checking. So you will have to modify all the tests related to it accordingly.

**Comment by yashbansal130** [comment]
also the string resource of greeting message is in 3 languages i guess and they contain "," from the string resource itself
![Screenshot from 2022-02-10 10-45-55](https://user-images.githubusercontent.com/66557534/153342282-48b9b75a-adac-4515-b13c-234e5251f1bd.png)
![Screenshot from 2022-02-10 10-47-33](https://user-images.githubusercontent.com/66557534/153342323-712c310e-1399-4ebe-a486-89d5483d7365.png)
![Screenshot from 2022-02-10 10-47-53](https://user-images.githubusercontent.com/66557534/153342368-2ed6e03e-cbd0-4e8d-9ab7-62a864225ccd.png)

**Comment by yashbansal130** [comment]
> So looking at it you will have to combine the test which says the user name which is Admin in our case and the greetings text. I can see that there are 3 different timestamps for which we are checking. So you will have to modify all the tests related to it accordingly.

 u mean to say i have to edit the test  such that the textview is tested with both the greeting message + username in a single test

**Comment by rishidyno** [comment]
Yes @yashbansal130 I mean ones the textviews are merged we will also have to merge the tests which were initially written seperately.

**Comment by yashbansal130** [comment]
@rishidyno the textview for header of profile progres fragment and home fragment have same id, should i change that?

**Comment by rishidyno** [comment]
@yashbansal130 can you please share SS or link these files here. Thanks!

**Comment by rishidyno** [comment]
> also the string resource of greeting message is in 3 languages i guess and they contain "," from the string resource itself ![Screenshot from 2022-02-10 10-45-55](https://user-images.githubusercontent.com/66557534/153342282-48b9b75a-adac-4515-b13c-234e5251f1bd.png) ![Screenshot from 2022-02-10 10-47-33](https://user-images.githubusercontent.com/66557534/153342323-712c310e-1399-4ebe-a486-89d5483d7365.png) ![Screenshot from 2022-02-10 10-47-53](https://user-images.githubusercontent.com/66557534/153342368-2ed6e03e-cbd0-4e8d-9ab7-62a864225ccd.png)

I think we can just keep the commas here.

**Comment by yashbansal130** [comment]
https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/layout/welcome.xml
https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/layout/profile_progress_header.xml

**Comment by yashbansal130** [comment]
> > also the string resource of greeting message is in 3 languages i guess and they contain "," from the string resource itself ![Screenshot from 2022-02-10 10-45-55](https://user-images.githubusercontent.com/66557534/153342282-48b9b75a-adac-4515-b13c-234e5251f1bd.png) ![Screenshot from 2022-02-10 10-47-33](https://user-images.githubusercontent.com/66557534/153342323-712c310e-1399-4ebe-a486-89d5483d7365.png) ![Screenshot from 2022-02-10 10-47-53](https://user-images.githubusercontent.com/66557534/153342368-2ed6e03e-cbd0-4e8d-9ab7-62a864225ccd.png)
> 
> I think we can just keep the commas here.

ok

**Comment by rishidyno** [comment]
> @rishidyno the textview for header of profile progres fragment and home fragment have same id, should i change that?

@rt4914 Will have to take a look at this as I am not quite sure how to approach this. @rt4914 PTAL.

**Comment by BenHenning** [comment]
> > @rishidyno the textview for header of profile progres fragment and home fragment have same id, should i change that?
> 
> @rt4914 Will have to take a look at this as I am not quite sure how to approach this. @rt4914 PTAL.

It'd probably be nice to change the ID to keep them separate (practically it shouldn't ever cause issues, but it's better to keep IDs generally unique).

**Comment by rishidyno** [comment]
> > > @rishidyno the textview for header of profile progres fragment and home fragment have same id, should i change that?
> > 
> > 
> > @rt4914 Will have to take a look at this as I am not quite sure how to approach this. @rt4914 PTAL.
> 
> It'd probably be nice to change the ID to keep them separate (practically it shouldn't ever cause issues, but it's better to keep IDs generally unique).

Agreed!

**Comment by yashbansal130** [comment]
> Agreed!

should i make a different issue for this?

**Comment by yashbansal130** [comment]
@rishidyno can i change the name of the test functions since they wont follow the naming convention after i make the changes

**Comment by rishidyno** [comment]
Ya sure take reference from https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing

**Comment by yashbansal130** [comment]
@rishidyno i made changes to the tests and they are working fine for english but skipping for brazilian and arabic languages.

**Comment by rishidyno** [comment]
@yashbansal130 please create a PR so that we can see your changes.

**Comment by yashbansal130** [comment]
> @yashbansal130 please create a PR so that we can see your changes.

sure

**Comment by yashbansal130** [comment]
@rishidyno  getting this error while pushing changes 
![Screenshot from 2022-02-18 19-15-22](https://user-images.githubusercontent.com/66557534/154694222-0d1a6a42-ff47-4220-801a-4709152d8866.png)

**Comment by rishidyno** [comment]
@yashbansal130 In Oppia we follow particular style guide for code formatting and one of the rules in style guide is to not exceed more that 100 char in a line so you will just neet to format the code. Well most of the time all these issues can be fixed automatically while pushing the code but sometimes we have to do it manually. Take refrence from `code style guide` in wiki.

**Comment by ShubhadeepKarmakar** [comment]
Hey, @adhiamboperes may I work on this?

**Comment by adhiamboperes** [comment]
> Hey, @adhiamboperes may I work on this?

Yes, assigning you

**Comment by Abinash6000** [comment]
Changing this line `android:text="@{viewModel.greeting}"` to `android:text="@{viewModel.greeting + viewModel.computeProfileNameText()}"` in `welcome.xml` solves this issue, except the issue of screen reader reading two commas , is there anything else to this ? @adhiamboperes

**Comment by ShubhadeepKarmakar** [comment]
Is the label "good first issue" correct for this issue?
@adhiamboperes  Just a query, nothing more than that.
Thanks.
