### ISSUE TITLE
Add networking support for KitKat devices

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3954]
**Is your feature request related to a problem? Please describe.**
Per https://medium.com/square-corner-blog/okhttp-3-13-requires-android-5-818bb78d07ce, OkHttp dropped support for KitKat devices due to the need to upgrade to TLS 1.2 and compatibility problems with KitKat & TLS 1.2. #3910 disabled OkHttp in KitKat builds to work around this issue.

**Describe the solution you'd like**
We should look into the difficulty of supporting networking in KitKat devices. This is part of a broader strategy discussion of whether & how we want to support KitKat devices.

**Describe alternatives you've considered**
We're also considering dropping networking support altogether & relying on embedded lessons, or dropping KitKat support altogether.

**Additional context**
None

**Comment by BenHenning** [comment]
From a technical perspective, we have a few choices:
- Try to make OkHttp work (https://medium.com/tech-quizlet/working-with-tls-1-2-on-android-4-4-and-lower-f4f5205629a & https://github.com/square/okhttp/issues/2372) provide a lot of context on how to do this, but it's basically one or more of the following (per https://github.com/square/okhttp/issues/2372#issuecomment-624927904):
  - Use Google Play Services to bring in TLS 1.2 support (requiring Google Play Services to be installed on the device, and us to potentially prompt for an upgrade)
  - Ship the native code for Conscrypt (requiring maintaining native code)
  - Enable TLS 1.1 support for Oppia web backend (which might not be possible, and has unforeseeable security implications)
- Pick an alternative library to OkHttp that supports TLS 1.2 (however, none were obvious including the internal Android library since TLS 1.2 support is uncertain)

We could potentially go with a hybrid option where we make a best-effort basis to support download functionality, but fallback to embedded lessons specifically for KitKat devices. Since we now have dedicated KitKat builds, it's certainly possible for us to only embed lessons for KitKat devices.

**Comment by BenHenning** [comment]
Also: we will need to use OkHttp 3.12.12+ (https://github.com/square/okhttp/issues/4481#issuecomment-637032983 -- see https://github.com/square/okhttp/tree/okhttp_3.12.x). The blog indicates this branch will only be maintained until EOY 2020, but it seems like there are still changes. This presents some risk since it's not clear how long the branch will stick around.

**Comment by seanlip** [comment]
Per https://github.com/oppia/oppia-android/issues/5012, we are deprecating support for Android KitKat, so this issue is no longer valid.
