### ISSUE TITLE
Required field label has to be right aligned in RTL.

### ISSUE THREAD

**Issue by veena14cs** [oppia/oppia-android#3958]
In Add profile screen required field has to be right aligned in RTL.

<img width="144" alt="Screenshot_1634864192" src="https://user-images.githubusercontent.com/16301028/138276849-ab6f46b3-4055-403b-8ac4-e601d2f2446e.png">

**Comment by BenHenning** [comment]
Nice catch @veena14cs. Thanks for filing this & following up with a fix.
