### ISSUE TITLE
Update target API to SDK 30

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3981]
Play now requires us to upgrade to SDK 30 before we can complete any more releases.

**Comment by JishnuGoyal** [comment]
May i work on this? @BenHenning

**Comment by BenHenning** [comment]
@JishnuGoyal I'm happy to hand it off, but this is actually a harder issue than it sounds (since it requires playing through the app in detail after updating the target SDK version to ensure there aren't any regressions, and it's likely *something* will break with this change; we also need to look at the deltas in behavior for SDKs 29 & 30 to determine if there are any specific API incompatibilities that we need to check). Given that, I suggest working on a few more starter issues to gain further familiarity with the codebase before taking on an issue like this.

**Comment by JishnuGoyal** [comment]
Sure @BenHenning

**Comment by BenHenning** [comment]
FYI @anandwana001 this will require updating the target SDK everywhere for Gradle & Bazel, and playing through the app to make sure that nothing breaks on an API 30 device (since it changes Android SDK behavior). We should also look at all the SDK changes between our current target and 30 via Android docs to see what the difference is.
