### ISSUE TITLE
Move some of the packages in the app module into app/utility

### ISSUE THREAD

**Issue by vinitamurthi** [oppia/oppia-android#3990]
The following packages need to be moved into app/utility in order to make code ownership a little easier:

- [ ] app/activity
- [ ] app/customview
- [ ] app/databinding
- [ ] app/fragment
- [ ] app/shim
- [ ] app/viewmodel
- [ ] app/parser

**Comment by coder2699** [comment]
@vinitamurthi I want to work on this, shall I assign it to myself?

**Comment by vinitamurthi** [comment]
Hi, actually we are pausing this effort until we have a better idea on how to restructure the codebase. Closing this bug till then!
