### ISSUE TITLE
"View All" button not visible on Tablet in Landscape Mode

### ISSUE THREAD

**Issue by JishnuGoyal** [oppia/oppia-android#3993]
**Describe the bug**
The `View All` button which navigates user to "RecentPlayedActivity" is not visible on Tablet in landscape mode

**To Reproduce**
1. After 'Login screen -> navigate to home page where different stories are displayed will be visible'
2. You can see "View All" button below greeting message.
3. When you use a tablet, this button won't be visible in landscape mode.

**Expected Behaviour**
This image corresponds to the portrait view on tablet, where `View All` button is clearly visible.
![image](https://user-images.githubusercontent.com/64526117/141359729-af282886-0b9f-450f-bb52-df3328925d39.png)

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.

Tablet in landscape mode:

![image](https://user-images.githubusercontent.com/64526117/141358868-ea669abc-77d6-427f-87ff-99bffbedd457.png)

**Environment**
- Device/emulator being used: Tablet Pixel C API 30
- Android or SDK version (e.g. Android 5 or SDK 21): Android 11

**Comment by JishnuGoyal** [comment]
May I work on this?

**Comment by BenHenning** [comment]
Nice find @JishnuGoyal. Can you confirm whether the 'View All' button in this context shows up for a handset (i.e. non-tablet) in landscape mode? It'd be helpful to know whether this issue is isolated to tablet landscape or if it's generally landscape.

@rt4914 is there anything special about tablet landscape that would explain why 'view all' is hidden, or is this a bug?

@JishnuGoyal once the above two points are addressed, and if this is a bug, then you're free to work on it. :)

**Comment by JishnuGoyal** [comment]
> Nice find @JishnuGoyal. Can you confirm whether the 'View All' button in this context shows up for a handset (i.e. non-tablet) in landscape mode? It'd be helpful to know whether this issue is isolated to tablet landscape or if it's generally landscape.
> 

Yes, the `View All` button is visible on a mobile device in portrait as well as landscape mode. Only on a tablet, particularly in landscape mode, it is not visible. Thanks. @BenHenning

**Comment by MaskedCarrot** [comment]
@BenHenning @JishnuGoyal The "view all" button is visible once scrolling is enabled (i.e. it is visible for three cards in tablet portrait mode and four cards in tablet landscape mode)

**Comment by JishnuGoyal** [comment]
> @BenHenning @JishnuGoyal The "view all" button is visible once scrolling is enabled (i.e. it is visible for three cards in tablet portrait mode and four cards in tablet landscape mode)

When in landscape mode, I am not able to see the `View all` button at all. How exactly can I navigate to `RecentlyPlayedActivity` from here? 

When you say "scrolling enabled", what exactly does it mean? It would be great if you could help to reproduce the behaviour you mentioned or provide a screenshot. Thanks.
@MaskedCarrot

**Comment by MaskedCarrot** [comment]
@JishnuGoyal Here are the steps to reproduce this 
1. Create and open a new profile
2. play one lesson from the "first test topic"
3. see view all button appears for tablet in portrait mode
4. play one lesson from the "second test topic"
5. see view all button appears for tablet landscape mode

**Comment by JishnuGoyal** [comment]
> @JishnuGoyal Here are the steps to reproduce this
> 
> 1. Create and open a new profile
> 2. play one lesson from the "first test topic"
> 3. see view all button appears for tablet in portrait mode
> 4. play one lesson from the "second test topic"
> 5. see view all button appears for tablet landscape mode

@MaskedCarrot I  got it 👍. Thanks for elaborating. I'll close this issue :)

**Comment by BenHenning** [comment]
Thanks @MaskedCarrot for the additional context & @JishnuGoyal for filing this.
