### ISSUE TITLE
Full UI: Question training interface [Blocked: #110, #27, #159]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#40]
Learners should be able to assemble a random assortment of questions based on preselected skills to train and review those skills.

Specific things to complete (from #500):
- [ ] End of question player has weird scrolling
- [ ] Not following mocks (initial implementation is closer to the exploration player and doesn't follow the non-conversational flow of the mocks)
- [ ] Add hints & solutions support (partially supported in the shared state recycler view assembler from #500)
- [ ] Add audio voiceover playback support (partially supported in the shared state recycler view assembler from #500)

**Comment by BenHenning** [comment]
This is blocked on #27 and #15.

**Comment by BenHenning** [comment]
This actually also blocks on #159 and #110.

**Comment by rt4914** [comment]
@BenHenning What is the difference between this issue and #27 ?

**Comment by BenHenning** [comment]
Closing #27 in favor of this one. That was based on assumptions of how the code would be laid out that didn't end up being true. Thanks for asking.

**Comment by rt4914** [comment]
> Closing #27 in favor of this one. That was based on assumptions of how the code would be laid out that didn't end up being true. Thanks for asking.

Thanks for the update.

**Comment by rt4914** [comment]
This issues was finished in parts and the final PR was #1653

**Comment by BenHenning** [comment]
Reopened due to #1768.

**Comment by BenHenning** [comment]
Per https://github.com/oppia/oppia-android/pull/1768#issuecomment-685593869 moving to beta.
