### ISSUE TITLE
ProfileEditFragment Backstack loop error

### ISSUE THREAD

**Issue by yash10019coder** [oppia/oppia-android#4007]
**Describe the bug**
In tablet When we reset or rename the Profile by Administrator controls in ProfileEditFragment and then on Pressing the back button we get stuck in a loop
**To Reproduce**
1. Go to Administrator Controls and click on any profile and then reset the pin or rename the name 
2. Click on the BackButton
3. Again Click on the back button
4. You get stuck in a loop of ProfileEditFragment and ProfileListFragment

**Expected behavior**
You should go back to administrator controls activity after pressing back button

**Demonstration**
|   |    |   |
| - | - | - |
| ![Screenshot_20211122_210529](https://user-images.githubusercontent.com/76404817/142893265-b45c50ad-3dfe-405d-9b35-1d73a7298fd2.png) | ![Screenshot_20211122_210618](https://user-images.githubusercontent.com/76404817/142893275-c7118e6b-7a26-4464-ac25-f8f6502b9438.png) | ![Screenshot_20211122_210644](https://user-images.githubusercontent.com/76404817/142893282-d090ca4a-096c-45d4-a458-6704ec14e81b.png) |
| ![Screenshot_20211122_210701](https://user-images.githubusercontent.com/76404817/142893287-78932150-2f28-4fd0-bbab-9edd6c3eb546.png) | ![Screenshot_20211122_210706](https://user-images.githubusercontent.com/76404817/142893292-7afc59fb-9612-434e-9e57-c6760a067bc0.png) |

https://user-images.githubusercontent.com/76404817/142893869-2f33edc5-0c89-4267-a5ff-af8bfe17f3e4.mp4

**Environment**
- Device/emulator being used: <device version/emulator>
- Android or SDK version : Android 9 Oreo/ api 28
- App version : latest dev

**Comment by chrk2205** [comment]
can i work on this @yash10019coder ?

**Comment by yash10019coder** [comment]
yeah sure @chrk2205 I am assigning it to you.

**Comment by chrk2205** [comment]
this is specific to tablet view.
It is not happening in android.
do I need to add test case?

**Comment by chrk2205** [comment]
@yash10019coder 
I found the cause of this, after renaming and submitting instead of finishing the current activity ( which will lead to profile edit activity in the stack ),  we are creating a new profile edit activity.
[link to code](https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/settings/profile/ProfileRenameActivityPresenter.kt#L107)

With creating a new activity this effect is showing in mobile also ( link a screen blink ).

**Comment by yash10019coder** [comment]
> this is specific to tablet view. It is not happening in android. do I need to add test case?

I think this is not happening in mobile ig
