### ISSUE TITLE
Radio Button Implementation

### ISSUE THREAD

**Issue by dika1osune** [oppia/oppia-android#4017]
**Is your feature request related to a problem? Please describe.**
Watching the young learners at close quarters helped with these observation. Sometimes, the child is reading slowly and needs some time to process the question they are being asked. As a result, the screen sometimes blanks out. I have noticed that tapping the screen to wake it up sometimes results in selecting the wrong option and this automatically results in the child having to learn the same material. Some kids found it frustrating, especially when you consider that the learning material already can be worthy

**Describe the solution you'd like**
Consider changing the radio buttons to allow child to select answer and then tap on the Submit button

**Describe alternatives you've considered**
The other alternative is to encourage user to change their background light settings to never dim. Considering also that many of the target users live in less than ideal conditions, charging their phones regularly too can be a luxury.

**Additional context**

**Comment by PushkarAdhyapak** [comment]
Hi, can I work on this.

**Comment by BenHenning** [comment]
Thanks @dika1osune.

It would be fairly easy for us to change the radio button implementation to display a submit button like item selection. @seanlip & @srushtirk can you please provide product guidance on how you think we should proceed here?

@PushkarAdhyapak I'm glad to see you're interested in working on this. :) I think we need to get clarity on what the solution should be before attempting any changes.

**Comment by seanlip** [comment]
Given the issues mentioned, I have no objections to the flow suggested by @dika1osune.

I ultimately defer to @srushtirk, though.

**Comment by seanlip** [comment]
Also /cc @dchen97 in case we want to mimic this on the Web (though I think it's fine if Web/Android have different implementations here, and there's something nice about 1 click vs 2 if the screen isn't blacking out on Web).

**Comment by srushtirk** [comment]
+1, Agree with @dika1osune and @seanlip regarding having user submit their answer choices using a 'Submit' button. I can write up a one-pager on the specs and lightweight mocks if that helps.

**Comment by BenHenning** [comment]
Thanks @seanlip and @srushtirk.

@srushtirk a one-pager isn't necessary here since it's a trivial change, and we're essentially making the radio button interaction behave like its item selection counterpart (which is fulled spec'd).

**Comment by BenHenning** [comment]
This is important for alpha MR4, and I think can be worked one by anyone who's comfortable with interpreting requirements and digging into the code. For reference, https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/SelectionInteractionViewModel.kt is the main file for the logic for both radio buttons & item selection.

**Comment by bhaktideshmukh** [comment]
Hey @rt4914 @BenHenning I would like to give this issue a try but do not have an experience in UI design.
So it will be great help if someone would guide a little.

**Comment by BenHenning** [comment]
@bhaktideshmukh since this is fairly urgent time wise, I've assigned it to @anandwana001 to work on. However, if you get to this before him, feel free to send a PR for it.

A good place to start is https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/SelectionInteractionViewModel.kt. You should read through that view model to see how it's used to display radio buttons for multiple choice vs. checkboxes for item selection (the goal here is to always use checkboxes, but restrict to a single selection for better usability).

**Comment by anandwana001** [comment]
Deferring to @rt4914 as he is already working on this.

**Comment by rt4914** [comment]
I will push my local code which is some missing pieces but does work upto an extent. As per discussion @anandwana001 will continue on that branch.

**Comment by KolliAnitha** [comment]
Verified in 0.7-alpha-6c08d882d3. Submit button is enabled after selecting a radio button.
