### ISSUE TITLE
Unable to move past a card in Chapter 6 (Fractions)

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#4026]
**Describe the bug**
Cannot go beyond a card in chapter 6 because there is no input method available for the user to enter their answer. The text is also illegible on this card.

**To Reproduce**
1. Go to Chapter 6 - Mixed Numbers and the Number line
2. Reach the card with the following question:
"What are fruit tarts?
1 ⅚
How many sixths of a cake are there in 2 ⅙
Which point on this number line represents 2 ¼ ?" 
3. Scroll down to input or continue button. Input box does not let the user type anything.

**Expected behavior**
There should some form of input method for the user to enter their answer and move to the next card.

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.
![Screenshot_20211205-214452](https://user-images.githubusercontent.com/27875087/144890475-bbc061b8-eb25-4477-8f17-0559d81736ad.png)

**Environment**
- Device/emulator being used: Pixel 5
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.6-alpha-7ff1b2bbd2

**Additional context**
Video: https://drive.google.com/file/d/13bwKEotN7DXiw6HMX55C2r8_3xNFGDvh/view?usp=sharing

**Comment by BenHenning** [comment]
@srushtirk were you connected to the internet when you reached this card? I have a feeling that we might not properly handle offline cases for image region selection (which I think is the interaction type being used here given the question).

Also, to clarify: you mentioned that the text is illegible. Could you be more specific as to which specific text was illegible?

**Comment by srushtirk** [comment]
![Screenshot_20211207-121413.png](https://user-images.githubusercontent.com/27875087/145099608-2ca848e1-86c4-46cc-b144-e9636b845082.png)

The text (fractions) on the number line in this screenshot is illegible, unable to read properly.

**Comment by srushtirk** [comment]
I was connected to the internet while playing this card and lesson.

**Comment by BenHenning** [comment]
Initial thoughts (more investigation needed): remote image loading as a fallback might be failing here for image region selection.

**Comment by anandwana001** [comment]
@BenHenning @rt4914 Could you help me by giving me access to this alpha data?

**Comment by rt4914** [comment]
@BenHenning Will be able to help in that.

**Comment by anandwana001** [comment]
<img src="https://user-images.githubusercontent.com/25057618/154471532-03b9a25b-09b0-46a3-830e-efabc181079c.png" width=230 height=450/>

@BenHenning  This is working for me correctly. 
@srushtirk  I guess due to an internet issue, I image didn't load for you.

**Comment by srushtirk** [comment]
Hi @anandwana001, This issue was experienced by other user(s) in Nigeria as well. 
Device/emulator being used: Samsung Galaxy 8
Android or SDK version (e.g. Android 5 or SDK 21): Android 9
App version: 0.6-alpha-908d57b2b1

Understand the internet issue, but can we ensure that this doesn't happen with other users while using the app?

**Comment by BenHenning** [comment]
We've seen cases where Glide sometimes just doesn't load images.

@srushtirk are you able to consistently hit this? I'm curious what the app logs might be if there's a Glide issue.

@anandwana001 have you tried reproing the issue in difficult network conditions (which I think might be possible to simulate, but I'm not sure).

**Comment by srushtirk** [comment]
Video for demonstration here: https://drive.google.com/file/d/12GOIRzxMeajCZ6q886MqzEO3X4t3IeMd/view

**Comment by anandwana001** [comment]
> We've seen cases where Glide sometimes just doesn't load images.
> 
> @srushtirk are you able to consistently hit this? I'm curious what the app logs might be if there's a Glide issue.
> 
> @anandwana001 have you tried reproing the issue in difficult network conditions (which I think might be possible to simulate, but I'm not sure).

Yes, I tried with multiple options like GSM(poor strength) and others and Yes, the image doesn't load.
and increasing the network quality to LTE and soo the image displayed.

**Comment by KolliAnitha** [comment]
Verified in 0.7-alpha-6c08d882d3. Number line is now seen with 2g data

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).
