### ISSUE TITLE
Implementing dark mode to various screens.

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#4030]
Creating PRs updating layout files with dark mode support using `component_colors` and `color_palette`.

Link to the original PR having discussions over the decided approach : [link](https://github.com/oppia/oppia-android/pull/3951)
Suggested to carefully go through this comment under above mentioned PR : [comment](https://github.com/oppia/oppia-android/pull/3951#discussion_r736145085)

Go through this PR for implementation + discussion over some files : [link](https://github.com/oppia/oppia-android/pull/4032)

#### Summary for decided approach for introducing new colors to the project and their usage :
- Introduced new colors in `color_defs.xml` following decided snake_case naming convention. `colors_def.xml` should strictly contain actual color name irrespective of their intended use with their hex color code declaration.
```xml
<color name="lime_green">#90EE90</color>
```
- Then `color_palette.xml` (day/night) splits the colors (to be used by `component_colors.xml`) according to chosen theme. `color_palette.xml` should not contain any name tied to the intended component to be used on, rather should have generic naming of the colors.
> Don't :
```xml
 <color name="add_profile_background_color">@color/oppia_background_black</color>
 <color name="text_input_layout_error_color">@color/error_red</color>
```
> Do : 
```xml
 <color name="background_color">@color/oppia_background_black</color>
 <color name="error_color">@color/error_red</color>
```
- `component_colors.xml` then only references `color_palette.xml`. It uses UI component specific names. Component colors should be shared very little outside of their respective views/fragments/activities.
```xml
  <color name="shared_text_input_edit_text_cursor_color">@color/primary_text_color</color>
  <color name="shared_activity_toolbar_color">@color/toolbar_color</color>
  <!--Styles.xml-->
  <color name="shared_text_input_layout_text_color">@color/primary_text_color</color>
  <color name="shared_input_interaction_edit_text_text_color">@color/primary_text_color</color>
  <color name="shared_text_input_layout_background_color">@color/text_input_background_color</color>
  <!--Admin Auth Activity-->
  <color name="admin_auth_secondary_text_color">@color/description_text_color</color>
  <color name="admin_auth_layout_background_color">@color/background_color</color>
  <!--Add Profile Activity-->
  <color name="add_profile_activity_label_text_color">@color/primary_text_color</color>
  <color name="add_profile_activity_switch_text_color">@color/dark_text_color</color>
```
- `colors_migrating.xml` contains color declarations which are supposed to be in `color_defs.xml` but has not been renamed yet to have actual color name instead of names linked to their use and components. This is a temporary measure to make sure other 4 color files follows the convention decided for them.

Note: colors declared in `component_colors.xml` and `color_palette.xml` should not use "oppia_" prefix to avoid redundancy and must have `_color` suffix. And just opposite applies to `color_defs.xml`

**Comment by rt4914** [comment]
All these instructions with more details have been mentioned on wiki https://github.com/oppia/oppia-android/wiki/Dark-Mode
