### ISSUE TITLE
Unable to access Admin profile and Admin Controls

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#4040]
**Describe the bug**
After entering the PIN to access the admin profile or admin controls, the app goes back to the profiles screen instead of the admin profile or admin controls screen. The PIN doesn't reset even after uninstalling and reinstalling the app. 

**To Reproduce**
1. Go to Admin profile
2. Enter the admin PIN and hit Submit
3. See error

**Expected behavior**
After entering the PIN the admin profile page or the admin controls page should be visible. 

**Demonstration**
https://drive.google.com/file/d/1cjjD9ub8P6UGPcDf2dxi55X2KEwWDW5n/view

**Environment**
- Device/emulator being used: Pixel 5
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.6-alpha-7ff1b2bbd2

**Additional context**

**Comment by BenHenning** [comment]
Interesting, it looks like the app is actually crashing.

@srushtirk would you be able to send me directly a full bug report from your device after reproing this? I can attach the crash that's occurring to provide more context to the issue.

**Comment by srushtirk** [comment]
@BenHenning Shared the bug report with you via email.

**Comment by anandwana001** [comment]
This is working fine for me on the latest develop branch, tested on pixel 3a.

**Comment by srushtirk** [comment]
Video for demonstration here: https://drive.google.com/file/d/1cjjD9ub8P6UGPcDf2dxi55X2KEwWDW5n/view

**Comment by BenHenning** [comment]
The video definitely looks like a crash; looking at the report logs.

**Comment by BenHenning** [comment]
Stack traces from the bug report:
```
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: Failed to prime cache ahead of LiveData conversion for StoryProgressController.
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: java.lang.IllegalStateException: Asset doesn't exist: vfJDB3JAdwIx
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at gg.d.a(SourceFile:58)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at ga.R.d(SourceFile:633)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at ga.R.a(SourceFile:429)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at ga.R.a(SourceFile:6322)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at ga.T.a_(SourceFile:243)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at ga.T.a(Unknown Source:10)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at gh.m.a_(SourceFile:90)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at gh.m.a(Unknown Source:10)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at gh.e.b(SourceFile:147)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at gh.e.a(SourceFile:89)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at gh.v.a(SourceFile:73)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at gh.w.a_(Unknown Source:11)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at cL.a.b(SourceFile:33)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at el.ac.run(SourceFile:56)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-23 17:52:20.916 10343  6059  6096 E StoryProgressController: 	at java.lang.Thread.run(Thread.java:920)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: FATAL EXCEPTION: pool-10-thread-1
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: Process: org.oppia.android, PID: 6059
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: java.lang.IllegalStateException: Asset doesn't exist: vfJDB3JAdwIx
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at gg.d.a(SourceFile:58)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at ga.R.d(SourceFile:633)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at ga.R.a(SourceFile:429)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at ga.R.a(SourceFile:6322)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at ga.T.a_(SourceFile:243)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at ga.T.a(Unknown Source:10)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at gh.m.a_(SourceFile:90)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at gh.m.a(Unknown Source:10)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at gh.e.b(SourceFile:147)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at gh.e.a(SourceFile:89)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at gh.v.a(SourceFile:73)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at gh.w.a_(Unknown Source:11)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at cL.a.b(SourceFile:33)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at el.ac.run(SourceFile:56)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-23 17:52:21.030 10343  6059  6098 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
```

The second bit also showed up in Play Console (deobfuscated):

```
java.lang.IllegalStateException: 
  at org.oppia.android.util.caching.AssetRepositoryImpl.loadProtoFromLocalAssets (AssetRepositoryImpl.java:58)
  at org.oppia.android.domain.topic.TopicController.loadStorySummary (TopicController.java:633)
  at org.oppia.android.domain.topic.TopicController.combineTopicAndTopicProgress$domain_domain_kt (TopicController.java:429)
  at org.oppia.android.domain.topic.TopicController.createCompletedStoryListFromProgress (TopicController.java:322)
  at org.oppia.android.domain.topic.TopicController.access$createCompletedStoryListFromProgress (TopicController.java:90)
  at org.oppia.android.domain.topic.TopicController$getCompletedStoryList$1.invokeSuspend (TopicController.java:243)
  at org.oppia.android.domain.topic.TopicController$getCompletedStoryList$1.create (TopicController.java:10)
  or                     .invoke (TopicController.java:10)
  at org.oppia.android.util.data.AsyncResult$transformAsync$2.invokeSuspend (AsyncResult.java:90)
  at org.oppia.android.util.data.AsyncResult$transformAsync$2.create (AsyncResult.java:10)
  or                     .invoke (AsyncResult.java:10)
  at org.oppia.android.util.data.AsyncResult.transformWithResultAsync (AsyncResult.java:147)
  at org.oppia.android.util.data.AsyncResult.transformAsync (AsyncResult.java:89)
  at org.oppia.android.util.data.DataProviders$Companion$transformAsync$1.retrieveData (DataProviders.java:73)
  at org.oppia.android.util.data.DataProviders$Companion$transformAsync$1$retrieveData$1.invokeSuspend (DataProviders.java:11)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java:56)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:920)
```

So it looks like we're running into a problem where the progress controller is causing the app to crash when it encounters progress for a lesson that is no longer on the device. I'm not actually sure which topic vfJDB3JAdwIx corresponds to or how Srushti managed to get progress for it. I think we need to both figure that out, confirm this theory, and fix the underlying problem.

**Comment by anandwana001** [comment]
@BenHenning  Here is the file https://github.com/oppia/oppia-android-assets/blob/master/vfJDB3JAdwIx.json

The file `C4fqwrvqWpRm.json` consists of the id `vfJDB3JAdwIx`.
The PR - https://github.com/oppia/oppia-android-assets/pull/7 consists of both the files.

I am currently, looking at why uninstalling and again installing the APK doesn't setUp the local assets.

**Comment by anandwana001** [comment]
@BenHenning My initial thoughts to fix this error is what if we never throw the error that says assets don't exist and in place of that we return the default instance.

```kt
override fun <T : MessageLite> loadProtoFromLocalAssets(assetName: String, baseMessage: T): T {
    return maybeProtoFromLocalAssetsOrFail(assetName, baseMessage)
      ?: defaultProto(baseMessage)
  }

  private fun <T : MessageLite> defaultProto(
    baseMessage: T
  ): T {
    @Suppress("UNCHECKED_CAST") // Safe type-cast per newBuilderForType's contract.
    return baseMessage.newBuilderForType()
      .build() as T
  }
```

I didn't check if it work on not, just an initial thought.

**Comment by BenHenning** [comment]
> @BenHenning Here is the file https://github.com/oppia/oppia-android-assets/blob/master/vfJDB3JAdwIx.json
> 
> The file `C4fqwrvqWpRm.json` consists of the id `vfJDB3JAdwIx`. The PR - [oppia/oppia-android-assets#7](https://github.com/oppia/oppia-android-assets/pull/7) consists of both the files.
> 
> I am currently, looking at why uninstalling and again installing the APK doesn't setUp the local assets.

Ah, I'm wondering if this actually happened since we dropped lessons in MR3--is the ``vfJDB3JAdwIx`` ID available in the latest downloaded assets?

Regarding the fix, I'm not keen on that since the app doesn't do well with the default exploration instance. It would avoid the crash, but at the expense of a significantly degraded experience.

**Comment by BenHenning** [comment]
I found a way to easily repro this:
1. Load the app with test assets
2. Play some or all of the assets (e.g. using the developer options menu)
3. Replace the assets in the binary with production assets & reload the app
4. Try to access admin controls or login

It crashes at this point with a similar stack to the above since it seems to be trying to load the topic corresponding to past progress. We should be ignoring progress in these cases since it's valid to have progress for topics that are no longer on the device.

**Comment by BenHenning** [comment]
(Taking this since I need to fix it, anyway, to make progress on some of the other issues).

**Comment by KolliAnitha** [comment]
Verified in 0.7-alpha-6c08d882d3. Admin profile and controls are accessible now.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).
