### ISSUE TITLE
Continue button changes to a conversation message when going backwards in a chapter

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#4076]
**Describe the bug**
Continue button changes to a conversation message (color changes from green to white) that says 'Please continue' once the user goes backwards in a chapter. Please continue looks like a button but is not clickable. Right and left arrows also appear once gone backwards in a chapter for navigation in the lesson. It is confusing to the user whether to click the arrows or the please continue button-like message. 

**To Reproduce**
1. Go to any topic and a chapter in that topic
2. Go over 3 cards
3. Go to previous card
4. See 'Please continue' unclickable button-like message and 2 right and left arrows on the screen

**Expected behavior**
'Please Continue' button should not appear on the screen. Only the front and back arrows for navigation between the lessons are sufficient. 

**Demonstration**
![image](https://user-images.githubusercontent.com/27875087/147781016-5d76a41f-0574-4293-867f-99791cca46c3.png)

**Environment**
- Device/emulator being used: Samsung Galaxy 8
- Android or SDK version (e.g. Android 5 or SDK 21): Android 9
- App version: 0.6-alpha-908d57b2b1

**Additional context**

**Comment by yashbansal130** [comment]
can i work on this issue?

**Comment by yashbansal130** [comment]
@yash10019coder can i try this one?

**Comment by yash10019coder** [comment]
You can try it but it not seems easy for a starter issue.

**Comment by chrk2205** [comment]
if this is open can i work on it?? @srushtirk @yash10019coder

**Comment by yash10019coder** [comment]
Assigned @chrk2205

**Comment by chrk2205** [comment]
I have found the bug. Technically I feel that it is not a bug. 
Explanation :
In the application to go to the next state ( next page ), we are using a single method which is [submit answer](https://github.com/oppia/oppia-android/blob/develop/domain/src/main/java/org/oppia/android/domain/exploration/ExplorationProgressController.kt#L148).
In case the page does not have any questions then we are using the phrase "Please continue." to go to the next state or page.
This phrase is being shown when the previous state or page is opened.

To solve this bug one thing we can do is use the if statement while showing the page or state which I won't recommend.
@yash10019coder

**Comment by chrk2205** [comment]
@rt4914 can you confirm if this is a bug or not??

**Comment by BenHenning** [comment]
I think this requires input from our UX team before we can move forward with a technical solution since it's not actually clear what we should be changing.

@srushtirk can you follow up with UX to determine what needs to be changed here?

**Comment by BenHenning** [comment]
Thanks @chrk2205. I think we'll need to wait on input from Srushti & UX before we can move forward with a fix.

**Comment by srushtirk** [comment]
@om-khandade Can you provide UX inputs?

**Comment by srushtirk** [comment]
Per chat with Chantel (UXD), we agree on removing the 'Please continue' message altogether and have the user rely on forward and backward arrows.

**Comment by BenHenning** [comment]
Taking this since it's time sensitive and it seems like any progress that's been completed for it hasn't been pushed.

**Comment by KolliAnitha** [comment]
Verified in 0.7-alpha-6c08d882d3. No conversation message is seen on navigating back in a chapter.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).
