### ISSUE TITLE
Change Revision Tab Icon 

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#4086]
**Is your feature request related to a problem? Please describe.**
The icon, when seen without the labels, do not match to real world representation of ‘revision’ and is misleading as found during user studies. Students often opened the revision tab when asked to start learning.

Current revision tab icon:
![Screen Shot 2022-01-07 at 3 47 16 PM](https://user-images.githubusercontent.com/27875087/148621089-bec1349a-32b6-47ae-b28a-8a1c7db6a202.png)

**Describe the solution you'd like**
Update revision icon to below:
![Screen Shot 2022-01-07 at 3 47 51 PM](https://user-images.githubusercontent.com/27875087/148621124-01fb766f-8796-4edd-b941-d9282cc610f0.png)

**Describe alternatives you've considered**
Alternatives considered in this doc:  @https://docs.google.com/a/google.com/document/d/1oD8LTH71BBsXxn5R1F8To3EsV786w0q-EQFcb4hRiik/edit

**Additional context**

cc: @mschanteltc

**Comment by BenHenning** [comment]
Is the proposed icon a material icon @srushtirk? Or, is there a material icon alternative that we can use?

**Comment by om-khandade** [comment]
No it is not a material icon. An alternative could be "Format List Bulleted".

**Comment by srushtirk** [comment]
@om-khandade Won't the users will get confused between lessons and revision tab is we use 'format list bulleted' icon for revision? I believe this won't solve the current user pain point of not being able to distinguish between lessons and revision tab intuitively.

**Comment by srushtirk** [comment]
![Revision_icon](https://user-images.githubusercontent.com/27875087/156463578-fec7c3b1-880c-4a20-b12c-c13275c92def.svg)

@BenHenning here is the material icon.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).

**Comment by pratyaksh1610** [comment]
@BenHenning I would like to work on this issue .
Since it is inactive.
Can I be assigned ?
Thanks.

**Comment by BenHenning** [comment]
@pratyaksh1610 this is available to work on--happy to assign it to you.

**Comment by BenHenning** [comment]
Actually scratch that, we need to verify that the new icon will solve the original concern for the issue. @seanlip it would be nice to have product feedback on this.

**Comment by seanlip** [comment]
I just chatted with @om-khandade, and here are some updates to what is currently in this thread:

- The revision icon proposed in the original comment was created by @om-khandade and is a non-material icon.
- "Format List Bulleted" seems like the closest alternative in the Material Icon list (when Om last checked it), but it's not clear that it would be intuitive. https://fonts.google.com/icons?icon.query=format+list+bulleted
- The icon Srushti subsequently gave in https://github.com/oppia/oppia-android/issues/4086#issuecomment-1057475074 is not a Material icon.

I'll post a follow-up to "what we should do" in the next comment.

**Comment by seanlip** [comment]
Based on a discussion between @om-khandade and I, here is what we propose:

- If the icon needs to be a material icon (or if that is strongly preferred), we can go with list-alt: https://fonts.google.com/icons?icon.query=list+alt&icon.style=Outlined
- If it doesn't need to be a material icon, then @om-khandade can make a version of list-alt with an arrow in the bottom right, and we can use that.

@BenHenning Could you please advise on the desirability of using icons from the standard Material set? If other icons are also OK, could you please let us know what constraints they will need to satisfy (e.g. file format, size, etc.)? Thanks.

**Comment by BenHenning** [comment]
@seanlip a Material icon isn't strictly needed (though it *can* simplify things slightly since we can pull it in through third-party dependencies rather than including our own icon). I'm happy to go with our own icon so long as it's a vector graphic and matches the aesthetic of other Material icons used in the app. Besides that, we should go with whatever icon works best with learners.

**Comment by seanlip** [comment]
Thanks @BenHenning! Sounds good -- assigning to @om-khandade to supply the icon so that it can be replaced.

**Comment by om-khandade** [comment]
![Group 1(5)](https://user-images.githubusercontent.com/63059690/188097377-51b4ca25-6ed7-45f0-b2a1-6a29fac6beaa.svg)
Here is the icon to be used.

**Comment by seanlip** [comment]
Thanks, @om-khandade!

@pratyaksh1610 -- I think you can now go ahead with this, if you'd like to. Thanks!

**Comment by pratyaksh1610** [comment]
@seanlip  Thankyou for assigning me, I am working on it.
