### ISSUE TITLE
Full UI: StoryFragment/Activity

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#41]
The story page should show the user their current progress through the story, and provide links to the corresponding explorations that they can play.

Mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/5abb0ace-19ee-48b8-8154-919154f924d2/TP-CL-Chapter-List-/

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/cce938d6-e079-4761-bac0-8bde22ac6348/TP-CL-Auto-Scroll-Button-

**Comment by BenHenning** [comment]
This is blocked on #15.

**Comment by BenHenning** [comment]
This is also blocked on #42.

**Comment by BenHenning** [comment]
This is also blocked on #166.

**Comment by BenHenning** [comment]
@hareshkh are you making any progress on this? If not, I'd like to deassign it for now. If you are making progress, let's sync on where you're at since much of the work I originally asked you to do is actually part of #166 and not part this issue (now that we have better granularity on tasks being done).

**Comment by BenHenning** [comment]
This is also blocked on #21 to show the current progress of completed explorations.

**Comment by BenHenning** [comment]
@hareshkh I'm assigning #166 to you first since it needs to precede this work.

**Comment by rt4914** [comment]
@Luffy18346 In this issue, most of the items are correct in develop but still needs rechecking.

**Comment by rt4914** [comment]
Closed via https://github.com/oppia/oppia-android/pull/926
