### ISSUE TITLE
Pin Text View is not visible in MDPI small

### ISSUE THREAD

**Issue by deepanshu731** [oppia/oppia-android#4105]
Pin Text View is not visible 
![Screenshot_1642243720](https://user-images.githubusercontent.com/78534813/149619040-2b7f35bd-7809-4094-864a-1d31ffc80659.png)
MDPI_SMALL
Size: 3.2 inch
Android API: 28

**Comment by BenHenning** [comment]
The fix here ought to be to disable LDPI altogether. If I recall correctly, that mode is generally used for watches, so it's never going to be needed for the Oppia platform.

@rt4914 do you have any thoughts on this?

**Comment by rt4914** [comment]
@deepanshu731 @BenHenning Yes we can disable LDPI. We will need to fix it for MDPI. I have created this issue https://github.com/oppia/oppia-android/issues/4109

@BenHenning can you add labels/projects/milestone correctly for this?

**Comment by rt4914** [comment]
This issue has been solved by me in #4355 

For reference I have taken this screenshot in `2.7 QVGA Device`

![Screenshot_20220803_014425](https://user-images.githubusercontent.com/9396084/182465099-635e1b48-4d35-43fa-a31a-2b8154b7fa7b.png)
