### ISSUE TITLE
Add tests for whitespace & fractions patterns

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#414]
See #413 for details.

**Comment by BenHenning** [comment]
Examples of interesting tests @nikitamarysolomanpvt has been doing that we should replicate later with automated tests:
- Single & multi digit terms
- Negatives
- Variable spaces between terms
- Verifying that numerator & denominator are correct for fraction-only, whole number-only, and mixed number fractions

**Comment by BenHenning** [comment]
To be more clear: this is proposing that we introduce a well-tested StringToFractionParserTest class for StringToFractionParser (there are no tests for this currently).

**Comment by rt4914** [comment]
Reverted PR in #3196

**Comment by rt4914** [comment]
cc : @viktoriias
