### ISSUE TITLE
Enhancing onboarding experience

### ISSUE THREAD

**Issue by Manikant25** [oppia/oppia-android#4154]
**Is your feature request related to a problem? Please describe.**
Its not related to problem but enhancement.  In onborarding fragment we can add feature like clicking on left and right its view changes like an instagram or whatapp story.

**Describe the solution you'd like**
We can add touch listeners which will detect and do the action

**Describe alternatives you've considered**
No other

**Additional context**
N/A

**Comment by Manikant25** [comment]
Please assign me, if you feel its  good to add. @rt4914

**Comment by BenHenning** [comment]
Thanks for submitting this @Manikant25. Note that we're currently in the process of determining what changes we should be making to the onboarding flow, so I'm sending this over to @srushtirk who's spearheading that design work.

**Comment by seanlip** [comment]
We won't do this -- we have other plans for a revised onboarding flow, so this is a bit obsolete. Thanks for the suggestion though.
