### ISSUE TITLE
Topic name text is cut off in topic_info_fragment for ratios and proportional reasoning

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#4169]
**Describe the bug**
Text in `topic_name_text_view` under topic_info_fragment for `Ratios and Proportional Reasoning` is extending outside screen borders.

**To Reproduce**
1. Go to All Topics.
2. Click on Ratios and Proportional Reasoning.
3. See error

**Expected behavior**
Topic name should be completely visible.

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.
<img src="https://user-images.githubusercontent.com/76056229/153182583-09bd069a-1308-4fc6-892d-fb4ff9dddcec.png" width="250px">

**Environment**
- Device/emulator being used: Pixel 3A
- Android or SDK version (e.g. Android 5 or SDK 21): API 28

**Comment by rt4914** [comment]
In this while creating PR please create screenshots for all the below mentioned cases:
1. LTR(English) Mobile Portrait
2. LTR(English) Mobile Landscape
3. LTR(English) Tablet Portrait
4. LTR(English) Tablet Landscape
5. RTL(Arabic) Mobile Portrait
6. RTL(Arabic) Mobile Landscape
7. RTL(Arabic) Tablet Portrait
8. RTL(Arabic) Tablet Landscape

https://github.com/oppia/oppia-android/wiki/RTL-Guidelines

**Comment by MohitGupta121** [comment]
I want to work on this issue can you please assign me

**Comment by KolliAnitha** [comment]
Unable to test this because of issue #4713 as Info tab is no longer seen

**Comment by BenHenning** [comment]
Ah, we may need to wait on being able to verify this until we can conditionally enable features in-app (which will happen on the order of months, so I think we can skip requiring verification for this issue as part of the next beta release).

**Comment by MohitGupta121** [comment]
> 

Yes sure no problem for now. Please consider release on the priority.
