### ISSUE TITLE
State Navigation Button Duplicate

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#417]
The state navigation buttons are getting duplicate in some cases. Mostly, the `state_button_item` is getting created twice mostly from `StateFragmentPresenter` not sure yet.

## With visibility control
![Screenshot_1574167027](https://user-images.githubusercontent.com/9396084/69147700-a2ef9980-0af8-11ea-8cfa-cbe51cf1939a.png)

## Without visibility control
![Screenshot_1574167105](https://user-images.githubusercontent.com/9396084/69147702-a420c680-0af8-11ea-9fa5-cb5e78f5b5f2.png)

**Comment by BenHenning** [comment]
Discussed during the team meeting today. Per @mschanteltc we need to make sure navigation-esque buttons are aligned. Note that this happens because one continue button is actually an interaction, and the other is a nav button.
