### ISSUE TITLE
Add dark mode support to TopicActivity

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#4177]
Add dark mode support to TopicActivity and contained views/fragment.

Go through this [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode) to get started.

#### Location in the app
1. Open the app
2. Go to All Topics
3. Open any topic

For on tasks in following order:
- Toolbar + Tabs in first PR
- Info tab in second PR
- Revision Card tab in third PR
- Practice tab in fourth PR
- Finally Lesson tab

**Comment by ShivanshGoel221B** [comment]
I am currently working on it. Can you assign it to me?

**Comment by ayush0402** [comment]
@ShivanshGoel221B Assigned.

**Comment by ShivanshGoel221B** [comment]
@ayush0402 
There is a color `<color name="oppia_secondary_text">#666666</color>` in color_migrating.xml that is being used in fragments.
Though this can be used as secondary_text_color in colors_def.xml. What color should I use for its night mode counterpart?
Can you tell me the HEX code for that or should I create it according to what looks fine?

**Comment by ayush0402** [comment]
@ShivanshGoel221B You can look at the mocks for its dark mode counterpart at https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/33f22169-7db1-4a28-84e3-8a6cb3be2f4d/specs/ , its the white color already defined in color_defs.xml. Go through each views individually in the dark mode mocks. You can create a new color for #666666 in color_defs.xml with an actual color name.

**Comment by MohitGupta121** [comment]
@rt4914 is this issue is still open?

**Comment by MohitGupta121** [comment]
@rt4914 In **Revision Card tab in third PR** also add dark_mode in Revision Card Fragment (after clicking on card Fragment) ? Or only Revision Card Tab Activity ?

**Comment by MohitGupta121** [comment]
As all the parts mentioned in this issue I have completed now. Only Part 5 Lesson Tab is left for that we have to make a new dark mode mockup which is not ready yet. So for the particular Lesson Tab, I am opening a new Issue.
