### ISSUE TITLE
Add dark mode support to OnboardingActivity and PinPasswordActivity

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#4178]
Add dark mode support to OnboardingActivity and PinPasswordActivity.

Go through this [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode) to get started.

**Comment by pandayed** [comment]
Please assign this to me.

**Comment by ayush0402** [comment]
@xpandeyed Assigned.

**Comment by rt4914** [comment]
This has been finished. The related PRs are https://github.com/oppia/oppia-android/pull/4379 & https://github.com/oppia/oppia-android/pull/4380
