### ISSUE TITLE
Add dark mode support to OptionActivity and OptionWithoutDrawerActivity

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#4182]
Add dark mode support to OptionActivity and OptionWithoutDrawerActivity as well as the contained views.

Go through this [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode) to get started.

**Comment by Akshatkamboj14** [comment]
can you assign me this?

**Comment by Akshatkamboj14** [comment]
hey @ayush0402 can you suggest me some PRs that I cant take reference from

**Comment by Akshatkamboj14** [comment]
@ayush0402 can*

**Comment by ayush0402** [comment]
@Akshatkamboj14 You can take a look at some parts of this PR #4032.

**Comment by Akshatkamboj14** [comment]
@ayush0402 hey Ayush, in my PR there is no use of color in my PR's Activities.....so what I am supposed to do?

**Comment by ayush0402** [comment]
@Akshatkamboj14 You might have to look into the contained fragments and other contained view's layout. Check `options_fragment.xml`, `options_story_text_size.xml` and other contained layouts.

**Comment by Akshatkamboj14** [comment]
hey @ayush0402, I am a bit confused I have to add dark mode support to **option_activity.xml** and **option
_without_drawer_activity.xml**, right?

**Comment by ayush0402** [comment]
@Akshatkamboj14 It applies to everything you see when you open OptionsActivity in the app. Including the contained layouts and views.
