### ISSUE TITLE
Unselect All option in Developer Options not working

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#4186]
**Describe the bug**
The Developer options have three items, Mark Chapters, Mart Stories, and Mark Topic. Inside each item, there is an option to select all at once.
But, unselecting the all option didn't work correctly. 

**To Reproduce**
1. Go to admin profile
2. Swipe left from the Home screen and click on Developer options
3. Open any item of the three-item (Mark Chapters, Mart Stories, and Mark Topic) and select all
4. Click all again and it will not unselect

**Expected behavior**
It should unselect all items correctly.

**Demonstration**
![Screenshot_20220214_163035](https://user-images.githubusercontent.com/25057618/153852535-513d588e-12c4-4653-bad6-ef81637372ed.png)

**Environment**
- Device/emulator being used: emulator
- Android or SDK version (e.g. Android 5 or SDK 21):  SDK 30
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0

**Additional context**
In PR please add test case showing that this has been fixed now.

**Comment by anandwana001** [comment]
@rt4914 If you have any thoughts on this or any context I am missing.

**Comment by rt4914** [comment]
@anandwana001 No. This is a bug as per explanation. Shifting it to good-first-issue.

**Comment by Akshatkamboj14** [comment]
can you assign me this?

**Comment by rishidyno** [comment]
@Akshatkamboj14 Unassigning you due to inactivity. If you are working on this, please reassign yourself.

**Comment by shankarpriyank** [comment]
I would like to work on this @bkaur-bkj

**Comment by visheshkadian** [comment]
@anandwana001 @rt4914 I would like to work on this bug can you assign me this

**Comment by visheshkadian** [comment]
@anandwana001 @rt4914 Hey! I have fixed the issue, can you review my PR??

**Comment by visheshkadian** [comment]
@anandwana001 sir, I wanted to ask you that since I made a PR for this issue which only solves the issue for Mark Topic Completed but the same issue is there for Mark Chapters and Mark Stories so should I make a new PR for both of them or push it in the same PR?

**Comment by BenHenning** [comment]
This shouldn't have been closed earlier.
