### ISSUE TITLE
Add dark mode support to MarkChaptersCompletedActivity, MarkStoriesCompletedActivity, MarkTopicsCompletedActivity and ProfilePictureActivity

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#4192]
Add dark mode support to MarkChaptersCompletedActivity, MarkStoriesCompletedActivity, MarkTopicsCompletedActivity and ProfilePictureActivity

Go through this [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode) to get started.

**Comment by UvrajSB** [comment]
Can you assign this issue to me, please

**Comment by ayush0402** [comment]
@UvrajSB Assigned.

**Comment by UvrajSB** [comment]
For the text color of checkboxes in different states ( selected, enabled but not selected, disabled), I cant find any fit from palette.
Should I create references in palette like "color_palette_selected_check_box_text_color"
Is this approach fine?

**Comment by UvrajSB** [comment]
For the disabled checkbox, the text has been assigned black color with alpha = 0.38
but it is better if we assign it some color code according to the designs it should be "color_def_oppia_grayish_black" but that is hardly visible on the background.
There is no color code in color_defs that matches the requirement.

I suggest to use some lighter shade of gray like #5CB8B8B8

**Comment by ritece** [comment]
is this issue available? I'd like to start working on this.

**Comment by UvrajSB** [comment]
> is this issue available? I'd like to start working on this.

Yeah you can go ahead

**Comment by bhaktideshmukh** [comment]
> is this issue available? I'd like to start working on this.

Are you still working on it?
