### ISSUE TITLE
Add dark mode support to ProfileProgressActivity, RecentlyPlayedActivity, CompletedStoryListActivity and OngoingTopicListActivity

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#4193]
Add dark mode support to ProfileProgressActivity, RecentlyPlayedActivity, CompletedStoryListActivity and OngoingTopicListActivity.

Go through this [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode) to get started.

**Comment by TheSwarnim** [comment]
Hi, @rt4914 @ayush0402 will every component have to be added for the color in activity. For eg: if textview color is the same in all activities then will it be convenient if we just take color from shared text view text color style?

**Comment by ayush0402** [comment]
@TheSwarnim Every component should be added separately for that activity. `shared_` prefix is used for colors which affect globally or to many layouts for example through a style defined in `styles.xml`.
