### ISSUE TITLE
Add dark mode support to QuestionPlayerActivity and ExplorationActivity

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#4195]
Add dark mode support to QuestionPlayerActivity and ExplorationActivity (includes state fragment).

Go through this [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode) to get started.

**Comment by MohitGupta121** [comment]
@rt4914 I checked and run this issue on my emulator and found almost all the things related to dark mode in this issue are fixed by @bhaktideshmukh 

Only one thing left which is already been raised in issue #4671

So @rt4914 can you please tell me if any part of this issue is missing from me? As this issue is fixed in differnet parts.
Is any part left by @bhaktideshmukh?

**Comment by rt4914** [comment]
@MohitGupta121 In this my only suggestion is to check solution UI too in dark-mode. 
I would suggest that you assign this and https://github.com/oppia/oppia-android/issues/4671 to yourself and solve both the issues in one single PR. 
In PR make sure that you generate dark-mode screenshots of solution summary too.

**Comment by MohitGupta121** [comment]
@rt4914 okay thanks you, got it. 
I'll fix this issue.

**Comment by MohitGupta121** [comment]
@rt4914 @BenHenning 
The hint_summary exapnd icon in different in Production app and in mockup so I have to go with which one?

In Production: https://user-images.githubusercontent.com/76530270/205110455-a7fb11e2-0a7a-4a76-b40a-cc94ed266dee.png

In Desgins Mockup: https://xd.adobe.com/view/3dca36c2-5115-419c-b25e-0f10526b077c-6899/screen/99e9e4c3-6c5e-4c13-a9f2-6b92aee17392/specs/

I think keep the Production one as in the dark mode, but the color of arrow should be white in dark mode.
As the Mockup one is too small so user get confused. 

What you should suggest?

**Comment by BenHenning** [comment]
I'm assuming the current arrow was just a reuse of the one used in the topic fragment. I actually don't see much issue with keeping it as-is (at least until we actually see user confusion arise that needs to be addressed). Do you have any concerns @rt4914?

**Comment by MohitGupta121** [comment]
> @rt4914 I checked and run this issue on my emulator and found almost all the things related to dark mode in this issue are fixed by @bhaktideshmukh
> 
> Only one thing left which is already been raised in issue #4671
> 
> So @rt4914 can you please tell me if any part of this issue is missing from me? As this issue is fixed in differnet parts. Is any part left by @bhaktideshmukh?

@rt4914 can I do #4561 and #4513 issue also in that one single PR? What you say?

**Comment by rt4914** [comment]
@MohitGupta121 
Use the mocks design for icon color. That is, for light mode use black drop down icon and for dark mode you white drop down icon. Transparent background in both cases.

**Comment by MohitGupta121** [comment]
> @MohitGupta121 Use the mocks design for icon color. That is, for light mode use black drop down icon and for dark mode you white drop down icon. Transparent background in both cases.

Okay sure, I use same as in mocks.

**Comment by MohitGupta121** [comment]
Now we can close this issue as according to me and @rt4914 everything is again revist and fixed for Question and Exploration Player.
