### ISSUE TITLE
Add dark mode support for StoryActivity, ResumeLessonActivity and HintsAndSolutionFragment

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#4196]
Add dark mode support for StoryActivity, ResumeLessonActivity and HintsAndSolutionFragment including the contained views.

Go through this [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode) to get started.

**Comment by pravesh00** [comment]
Can I work on this @ayush0402
