### ISSUE TITLE
Full UI: ExplorationPlayerFragment/Activity

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#42]
The exploration player should be functionally close to the reactive exploration player in the web frontend, though with mobile-specific considerations. At a high level, this player should:

- Displaying cards (see #26)
- Playing audio tracks (see #17)
- Support back-and-forth navigation
- Submitting answers (see #27)
- Tying into skills when questions are answered
- Linking to concept cards
- Recording story progress when completed (time permitting)
- Full answer classification minus ML since that is a WIP
- Misconceptions & hints triggers
- Redirection to other cards
- Correct/wrong answers
- Missing prerequisites as feedback for showing concept card

**Comment by BenHenning** [comment]
This is blocked on #15, #17, #26, and #27. Design should start before that work is done since this is encapsulating a large portion of the prototype. This issue should be split into constituent pieces and parallelized across multiple individuals. This can also be built before being hooked up to #41.

**Comment by BenHenning** [comment]
This is blocked on #15, #17, #26, and #27. Design should start before that work is done since this is encapsulating a large portion of the prototype. This issue should be split into constituent pieces and parallelized across multiple individuals. This can also be built before being hooked up to #41.

**Comment by BenHenning** [comment]
This is also blocked on #19 for lesson language selection.

**Comment by BenHenning** [comment]
Consider skipping hints & solutions.

**Comment by BenHenning** [comment]
This actually blocks on #113, #164, and #165. Language selection is now scoped out of the prototype, and much of the exploration complexity has been pushed down into state fragment.

**Comment by BenHenning** [comment]
Note that this is tracking the high-fidelity work for the entire exploration learning experience, so it may be worth breaking this into pieces later once larger portions of the high fidelity work are identified.

**Comment by BenHenning** [comment]
@rt4914 can you clarify what remaining work needs to be done here?

**Comment by rt4914** [comment]
@BenHenning This one is blocked on #377

**Comment by rt4914** [comment]
This issues was finished in parts and the final PR was #1653

**Comment by BenHenning** [comment]
Reopened due to #1768.

**Comment by BenHenning** [comment]
Per https://github.com/oppia/oppia-android/pull/1768#issuecomment-685593869 moving to beta.

**Comment by anandwana001** [comment]
updating PR title as it is no more blocked on #113 #164 #165
