### ISSUE TITLE
Add dark mode support to AudioLanguageActivity, ReadingTextSizeActivity, AppLanguageActivity and dialog views.

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#4200]
Add dark mode support to AudioLanguageActivity, ReadingTextSizeActivity, AppLanguageActivity and dialog views.
Dialog views include:
- profile_picture_edit_dialog
- cellular_data_dialog 
- etc.
and the system AlertDialog. (look at OppiaAlertDialogTheme)

Go through this [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode) to get started.

**Comment by indresh149** [comment]
Do I work on this?

**Comment by ayush0402** [comment]
@indresh149 Assigned.

**Comment by MohitGupta121** [comment]
I want to work on this issue can you please assign me

**Comment by MohitGupta121** [comment]
I unable to navigate to App Language Activity.
As I not find it on options menu, where is that activity?

**Comment by BenHenning** [comment]
@MohitGupta121 the app language feature is currently disabled, but you can enable it in a local build by setting [this parameter](https://github.com/oppia/oppia-android/blob/develop/utility/src/main/java/org/oppia/android/util/platformparameter/PlatformParameterConstants.kt#L63) to true.

**Comment by MohitGupta121** [comment]
> @MohitGupta121 the app language feature is currently disabled, but you can enable it in a local build by setting [this parameter](https://github.com/oppia/oppia-android/blob/develop/utility/src/main/java/org/oppia/android/util/platformparameter/PlatformParameterConstants.kt#L63) to true.

Okay thanks you

**Comment by MohitGupta121** [comment]
How I'll find my dark mode mocks as in Abode xd there are 500+ mocks.
Is there any searching in that?

**Comment by BenHenning** [comment]
@MohitGupta121 I think there's a magnifying glass on the upper right of the Adobe XD view (at least on a laptop) that provides access to a search bar.

**Comment by MohitGupta121** [comment]
> @MohitGupta121 I think there's a magnifying glass on the upper right of the Adobe XD view (at least on a laptop) that provides access to a search bar.

Okay thanks you

**Comment by rt4914** [comment]
@MohitGupta121 What all is pending in this issue?

**Comment by MohitGupta121** [comment]
> @MohitGupta121 What all is pending in this issue?

@rt4914 All completed in this issue. No issue left now according to me.

**Comment by rt4914** [comment]
Great. Closing this now.
