### ISSUE TITLE
Add all pt-br translations

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#4224]
**Is your feature request related to a problem? Please describe.**
The classroom web page at oppia.org/learn/math is fully translated to Brazilian Portuguese. Please add these translations including title and description into the Android app. 

Current issues:
"Currently, the current solution is a fragile, temporary one. It will break for a bit if we change the titles of anything"

Context: Email thread with subject - Re: Oppia classroom page fully translated to pt-br

**Comment by srushtirk** [comment]
@isalooo Filing issue in github for tracking purposes

**Comment by BenHenning** [comment]
Per a discussion with @isalooo for the beta release, this will include restricting the app to only lessons with 100% pt-BR written translations.
