### ISSUE TITLE
Add support for svgz images

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4231]
**Is your feature request related to a problem? Please describe.**
Oppia web is planning to add support for svgz images (which are just svg images with gzip compression) in order to reduce bandwidth and storage requirements for images.

**Describe the solution you'd like**
The Android app should be updated to support images ending with svgz by first decompressing them using built-in Android gzip utilities, and then passing them to the existing gzip pipeline (this may benefit from making use of a Glide transcoder).

**Describe alternatives you've considered**
The alternative would be to not support svgz at all, but that doesn't seem ideal since there are very clear benefits for both download and storage size (APK size for embedded lessons will barely change since APKs are already zip-compressed).

**Additional context**
None

**Comment by MnCSSJ4x** [comment]
can i contribute to this ?

**Comment by BenHenning** [comment]
Hi @MnCSSJ4x. Welcome to Oppia! Apologies for missing this. It looks like you haven't contributed to the project before. Please follow [these steps] to begin onboarding where we'll match you to an onboarding mentor and help find an issue for you to get started (which could be this one since it's marked as a starter issue).

**Comment by BenHenning** [comment]
So it looks like AndroidSVG (the library we use for parsing SVG files) already supports GZIP-compressed SVGs: https://github.com/oppia/androidsvg/blob/4bc1d26412f0fb9fd4ef263fa93f6a64f4d4dbcf/androidsvg/src/main/java/com/caverock/androidsvg/utils/SVGParserImpl.java#L601. Based on that, we probably only need to add support on the Oppia side to properly route images ending in svgz (vs. just svg).

**Comment by pratik9315** [comment]
> So it looks like AndroidSVG (the library we use for parsing SVG files) already supports GZIP-compressed SVGs: https://github.com/oppia/androidsvg/blob/4bc1d26412f0fb9fd4ef263fa93f6a64f4d4dbcf/androidsvg/src/main/java/com/caverock/androidsvg/utils/SVGParserImpl.java#L601. Based on that, we probably only need to add support on the Oppia side to properly route images ending in svgz (vs. just svg).

So..we can directly use the image files with .svgz extension🤔?

**Comment by BenHenning** [comment]
Yes I think so, though the app today won’t load them through the pipeline correctly. Changes are needed in UrlImageParser to fix that, I think.

**Comment by pratik9315** [comment]
> Yes I think so, though the app today won’t load them through the pipeline correctly. Changes are needed in UrlImageParser to fix that, I think.

If its okay, can I try my hand at this issue?

**Comment by BenHenning** [comment]
Sure @pratik2315. Assigning to you.

**Comment by ihharsh** [comment]
We can use Glide Library as it provide support for a wide variety of image file formats, including SVGZ.
Alternatively, we can use
 com.caverock:androidsvg
this library this library is a SVG parser and renderer for Android. It can parse SVG files and render them to Canvas or OpenGL.

**Comment by BenHenning** [comment]
@ihharsh unless I'm mistaken, I don't think Glide does support SVG or SVGZ. See: https://github.com/bumptech/glide/blob/5e7c91a24a4439ddf6da9521f99bfa2f72284c91/library/src/main/java/com/bumptech/glide/load/ImageHeaderParser.java#L21.

We actually already use AndroidSVG today and, as discussed above, it seems to support SVGZ out-of-the-box. There's just a small UrlImageParser change needed here, plus tests, in order to enable the SVGZ functionality.

@pratik2315 are you still working on this?

**Comment by supreme96** [comment]
> @ihharsh unless I'm mistaken, I don't think Glide does support SVG or SVGZ. See: https://github.com/bumptech/glide/blob/5e7c91a24a4439ddf6da9521f99bfa2f72284c91/library/src/main/java/com/bumptech/glide/load/ImageHeaderParser.java#L21.
> 
> We actually already use AndroidSVG today and, as discussed above, it seems to support SVGZ out-of-the-box. There's just a small UrlImageParser change needed here, plus tests, in order to enable the SVGZ functionality.
> 
> @pratik2315 are you still working on this?

@BenHenning if @pratik2315 is no longer working on this, can you please assign me this issue? Thanks

**Comment by seanlip** [comment]
Deassigning @pratik2315 due to inactivity and lack of response.

@supreme96 If you're interested in working on this, could you please provide a description of what you plan to do and what files you plan to change etc.?

**Comment by supreme96** [comment]
Hi @seanlip, I am looking through the UrlImageParser code. I'll update this issue with the details of my proposed change or my queries/clarifications shortly. Thanks :)

**Comment by supreme96** [comment]
> Yes I think so, though the app today won’t load them through the pipeline correctly. Changes are needed in UrlImageParser to fix that, I think.

@BenHenning @seanlip can you elaborate a bit on what you meant by 'the app today won’t load them through the pipeline correctly' ?
