### ISSUE TITLE
To review: PRs requiring Rajat approval

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4266]
The following PRs require post-merging PR approval from @rt4914:
- [x] #2173
- [x] #4267
- [x] #4269
- [x] #4274
- [x] #4307
- [x] #4271
- [x] #4259

Note that these were force-merged due to the sensitive timeline they're part of.

Reviewer: please review the above PRs & check them off once complete. Assign back to me once all have been addressed. Comments can be left directly on the original PRs, and I'll follow up with one PR to address all of them (if code changes are needed, otherwise I'll follow up on the corresponding PRs). This issue should only be closed once you're satisfied with all of the changes, including needed follow-up changes.

**Comment by BenHenning** [comment]
@rt4914 could you please review the above merged PRs per the instructions in the opening comment?

**Comment by BenHenning** [comment]
Findings (so far that I've noticed): https://github.com/oppia/oppia-android/pull/4274#pullrequestreview-1012710889

**Comment by rt4914** [comment]
@BenHenning I have reviewed all PRs. Thanks.

**Comment by BenHenning** [comment]
Thanks much @rt4914! I really appreciate it.

It looks like there's just one comment to address. I'll follow up with addressing that comment to finish up this issue.
