### ISSUE TITLE
Disable copying for empty Profile IDs

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#4276]
**Describe the bug**
Multiple profile IDs are being copied on copying just a single Profile ID. 

**To Reproduce**
1. Go to Admin controls
2. Click on Profile Learner IDs & Sync Status
3. Copy profile IDs for the profiles with no ID available

**Expected behavior**
Disable copy button for empty profile IDs

**Demonstration**
<img width="368" alt="image" src="https://user-images.githubusercontent.com/27875087/160757243-fff27c1a-45d8-4544-85d0-452cc1a602d5.png">

**Environment**
- Device/emulator being used: Pixel 5
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.7-alpha-d1b2827517

**Comment by Umesh-01** [comment]
@srushtirk I want to work on this issue, if you can guide me a little bit.

**Comment by BenHenning** [comment]
Notes on reproing this: you need to create the profile with a version of the app where the feature is disabled, and not log into it (otherwise a learner ID will be generated).

**Comment by BenHenning** [comment]
This was fixed in #4064.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).
