### ISSUE TITLE
Previous Profile IDs show "Copied" checkmark after leaving and returning to Profile IDs screen 

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#4278]
**Describe the bug**
Previous Profile IDs show "Copied" checkmark after leaving and returning to Profile IDs screen.

**To Reproduce**
1. Go to Profile Learner IDs & Sync Status 
2. Click "Copy" for one of the Profile IDs
3. Leave the screen and come back to it

**Expected behavior**
"Copied" checkmark should disappear in 3 sec.

**Demonstration**
[If applicable, add screenshots or videos to help explain your problem.](https://drive.google.com/file/d/1AjRKuBacSnRsIyepPypwyin9yyCihID0/view)

**Environment**
- Device/emulator being used: Pixel 5
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.7-alpha-d1b2827517

**Additional context**

**Comment by pravesh00** [comment]
Can I work on this @srushtirk @rt4914 @anandwana001

**Comment by BenHenning** [comment]
The screen that this is corresponding to isn't actually checked into the develop branch yet @pravesh00, so it isn't available to work on. Sorry for the confusion.

Assigning to myself to avoid further confusion.

**Comment by BenHenning** [comment]
Given that no confusion has come up during the dry-run, going to close this as an issue we're not going to fix. I think the current UX is probably fine, and we can revisit changing this if there's observed confusion.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).
