### ISSUE TITLE
Numerator/denominator concept card should have images at the bottom

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#428]

**Comment by BenHenning** [comment]
Hey James. Sean mentioned that you might have an idea on how to fix this?

**Comment by seanlip** [comment]
More specifically -- @jamesxu0, I seem to remember you showed me once a concept card with two images at the bottom. Similar to this one? https://www.oppia.org/explore/xHwiGtvK2N4L

**Comment by BenHenning** [comment]
@vinitamurthi James has a bunch of questions & audio work to complete early next week. Might you be able to look at this?

**Comment by vinitamurthi** [comment]
Not 100% sure I understood this one..Do we want to have a concept card where the HTML content has image tags? Is that what we are going for?

**Comment by BenHenning** [comment]
I suspect this issue will go/has gone away with the full implementation of subtopic cards & proper data being imported into the app.
