### ISSUE TITLE
Text size does not change in-exploration

### ISSUE THREAD

**Issue by rajattrehan-oppia** [oppia/oppia-android#4285]
If you change the text size from the 3 dot menu during an exploration the text size does not change for the current exploration.  The text size change happens when the next exploration is played.

**To Reproduce**
1. Go to the three dot menu in any exploration card.
2. Set 'Reading Text Size' to a different size than currently selected (e.g. change from Small to Extra Large)
3. Go back from Options to Exploration card 
4. Text size does not change in the exploration (remains Small)
5. The next exploration plays in the new font setting (Extra Large)

**Expected behavior**
If 'reading size' and 'default audio' options are accessible from any exploration card, then the expectation is for these settings to be effective immediately.

**Demonstration**
Find screenshots [here](https://docs.google.com/presentation/d/1WHNtVE1ADRZmtocLNtkR9n7vmWmVmEGFFRQWox_0X9Q/edit?usp=sharing) replicating the steps

**Environment**
- Device/emulator being used: Galaxy Tab S6 Lite / SM-P610
- Android or SDK version (e.g. Android 5 or SDK 21): Android 11
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.7-alpha-d1b2827517

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).

**Comment by BenHenning** [comment]
This is causing issues with the Kenya research project, so bumping it up to investigate.

**Comment by BenHenning** [comment]
(Note that I'm distinguishing this from #4372 where sometimes the text doesn't change at all which is what this issue is tracking).

**Comment by BenHenning** [comment]
Actually, I misread the original description. This actually is the same as #4372. I'm going to investigate trying to fix the problem fully, anyway.

**Comment by BenHenning** [comment]
So it turns out that this feature does fully break sometimes, but it's tied to internationalization. I filed #4394 to track.

**Comment by BenHenning** [comment]
FYI @KevinGitonga I actually do have a fix for this issue that I plan to submit as part of beta (see #4411).

**Comment by KolliAnitha** [comment]
Reading text size and audio are applied in the exploration in beta version
