### ISSUE TITLE
Profile Learner IDs & Sync Status overlaid on Edit Profile tab

### ISSUE THREAD

**Issue by rajattrehan-oppia** [oppia/oppia-android#4286]
**Describe the bug**
In administrator controls, when going from 'Edit profiles' to 'Profile Learner IDs & Sync Status' the IDs the latter tab's content is overlaid on the former. The copy button nevertheless works.

**To Reproduce**
1. Go to Administrator Controls
2. Click on Profile Learner IDs & Sync Status
3. The Profile Learner IDs & Sync Status context is overlaid on the Profile Learner screen

**Expected behavior**
The overlay gives the impression that the panel/tab is broken and is confusing to the user. The Copy function works nevertheless

**Demonstration**
Find screenshots [here](https://docs.google.com/presentation/d/1MDDNbIEL6TvU9kdbqJy_nQJQmDZ1bvfoACqjGhcOHW8/edit#slide=id.g12148215a07_0_3) 

**Environment**
Device/emulator being used: Galaxy Tab S6 Lite / SM-P610
Android or SDK version (e.g. Android 5 or SDK 21): Android 11
App version: 0.7-alpha-d1b2827517

**Comment by BenHenning** [comment]
This was fixed in #4064.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).
