### ISSUE TITLE
Additional white box added to cards when navigating backwards

### ISSUE THREAD

**Issue by rajattrehan-oppia** [oppia/oppia-android#4287]
**Describe the bug**
When navigating backwards from the card where a question in answered by manual input, an extra white box appears on all cards above the forward arrow button

**To Reproduce**
1. Start an exploration and move forward through all cards till a question comes up which requires manual entry
2. Provide input to text field and press submit 
3. Navigate backwards using back arrow button
4. A white box appears on all cards above forward button. Clicking on the button produces no action.

**Expected behavior**
Such unnecessary elements may confuse the user, who would be confused if an input is required or it has some navigational function.

**Demonstration**
Find screenshots [here](https://docs.google.com/presentation/d/1BiKgarCERYHnbXF6LcU_gJkcFuFBQbnz7_v1UYm5zQg/edit?usp=sharing)

**Environment**
Device/emulator being used: Galaxy Tab S6 Lite / SM-P610
Android or SDK version (e.g. Android 5 or SDK 21): Android 11
App version: 0.7-alpha-d1b2827517

**Comment by BenHenning** [comment]
Interestingly, this only seems to happen after state changes. If you navigate back from the next card immediately after pressing 'continue', the box isn't there. However, once whatever triggers it occurs it stays broken from that point onward.

**Comment by BenHenning** [comment]
Ah I see. This is being caused by the view model being recycled from a previous card and not correctly reset (since there's nothing to bind). I more or less did the original implementation incorrectly. It's better to avoid creating a model to bind in the first place rather than trying to condition what is bound to the specific view.

**Comment by KolliAnitha** [comment]
No whitebox is seen while navigating to previous pages in alpha build 0.7-alpha-6c08d882d3.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).
