### ISSUE TITLE
After deleting a profile, Deleted successfully message should be displayed

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4294]
**Describe the bug**
After deleting a profile, Deleted successfully notification should be displayed 

**To Reproduce**
1. Login to Oppia as Administrator
2. Click on Administrator Controls- Enter PIN
3. Click on Edit Profiles
4. Select a profile to delete - Click on Profile Deletion
5. A confirmation dialog appears- Click on Delete 

**Expected behavior**
After clicking on Delete a message 'Deleted successfully' should be seen and read by talk back. This helps the talk back users to confirm that the profile has been deleted

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).

**Comment by theayushyadav11** [comment]
Hi @BenHenning , I would like to work on it,plz assign it to me.

**Comment by adhiamboperes** [comment]
Hi @theayushyadav11, please feel free to create a PR
