### ISSUE TITLE
Hyperlink for 'concept card' in the revision card 'Naming Numbers' is shown as 'this concept card' instead of 'concept card'

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4298]
**Describe the bug**
Hyperlink for 'concept card' in the revision card 'Naming Numbers' is shown as 'this concept card' instead of 'concept card'

**To Reproduce**
1. Go to 'Topic: Place Values'
2. Click on 'Revision' tab- Select 'Naming Numbers'
3. Check for the Concept Card link

**Expected behavior**
hyperlink should be seen for text concept card only

Actual Result:
this concept card is displayed as hyperlink instead of hyperlink

**Demonstration**
![Screenshot 2022-04-14 1 36 15 PM](https://user-images.githubusercontent.com/101634267/163341923-b49294f0-1877-462c-adc6-b08a52fde0dd.png)

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

**Comment by seanlip** [comment]
This is now fixed in the original content, and will be updated in the Android app during the next content pull. Thanks @KolliAnitha!

**Comment by BenHenning** [comment]
Reopening to track pulling in the fix in data so that @KolliAnitha can verify it.

**Comment by BenHenning** [comment]
This wasn't completed in time, so deferring it.

**Comment by BenHenning** [comment]
Confirming this has been fixed in the latest alpha data, so marking this as closed so that Anitha can verify as part of the Alpha MR5 test pass.

**Comment by KolliAnitha** [comment]
Verified in 0.8-alpha-091b45a188 and its working fine.
![Screenshot_2022-08-21-15-37-24-83_943a62cb4c6fb83e010e1c2e82766a17](https://user-images.githubusercontent.com/101634267/185786071-a91d1cb4-4854-4181-be0c-8d4da73eebd3.jpg)
