### ISSUE TITLE
Reduce white space between feedback & answer & content boxes

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#430]
There's too much vertical whitespace which makes it harder to consume all the content on the screen. We should reduce this (see Oppia Web for context).

**Comment by veena14cs** [comment]
![2019-11-19](https://user-images.githubusercontent.com/16301028/69216208-a2efa800-0b91-11ea-9b55-bd03be82d7f9.png)
![2019-11-19 (1)](https://user-images.githubusercontent.com/16301028/69216214-a5520200-0b91-11ea-9552-15bc986e9dab.png)

@seanlip PTAL at these screenshot if this spacing looks good.

**Comment by seanlip** [comment]
Spacing is better. I have a couple other requests though:

- See https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/5954b83a-4bcf-4fa6-8382-f814137fa8ab/PM-Q4-Fill-In-Learn-Again- . Could you please do the following:
    - Reduce the width of the "learner response" box based on the content within it, and right-align it accordingly.
    - Add a bit of breathing room above the "back button + continue button" row.

**Comment by veena14cs** [comment]
> Spacing is better. I have a couple other requests though:
> 
> * See https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/5954b83a-4bcf-4fa6-8382-f814137fa8ab/PM-Q4-Fill-In-Learn-Again- . Could you please do the following:
>   
>   * Reduce the width of the "learner response" box based on the content within it, and right-align it accordingly.

This is getting fixed in PR #412 .

**Comment by veena14cs** [comment]
>   * Add a bit of breathing room above the "back button + continue button" row.

I will add spacing at the top of "back button + continue button" row.
