### ISSUE TITLE
Introduce beta notice

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4300]
**Is your feature request related to a problem? Please describe.**
Users need to be aware of when they're changing to a beta version of the app.

**Describe the solution you'd like**
See [PRD](https://docs.google.com/document/d/1vnD20MuZ8JVr6ZuA40p5c2GRiJrCpbodMghqHJSeMHg/edit?usp=sharing) and [mocks](https://xd.adobe.com/view/3dca36c2-5115-419c-b25e-0f10526b077c-6899/screen/d92286cb-e0d8-4687-b6a3-6448c44dbe00/) (see the 'Splash Page w/ Beta notice'). Users should see a notice when changing to the beta channel (from either alpha or GA), and only during app startup. If they select "Don't show again" then the notice should not be shown again _unless_ they change from & back to the beta channel (then the app should reset the earlier preference).

The preference is per-app, not per-user.

**Describe alternatives you've considered**
Lots of alternatives, including using an icon, title change, splash text + waiting until the user clicks on it, extra bar added to the profile page & home screen, and others. The solution the team landed on was the simplest approach (technically) that should minimize user confusion and avoid accessibility problems.

**Additional context**
None.

**Comment by KolliAnitha** [comment]
beta notice is seen on upgrading from alpha to beta.
![4f00931b-df7e-409d-88ca-775964cfe81c](https://user-images.githubusercontent.com/101634267/189514214-4c937f00-c2ce-446d-be4f-00d266ce2d59.jpg)
