### ISSUE TITLE
Update Play Store description for beta

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4301]
As part of introducing explicit beta notices (e.g. #4300), the Play Store description also needs to be updated to have beta-specific messaging. The messaging provided by the UX team is:

```
The Oppia app is currently in beta. Although the app works and you'll be able to play the lessons, some users may experience bugs and technical issues. The team at Oppia would love your help – if you experience problems while using the app, or have questions, please contact us at [android-feedback@oppia.org](mailto:android-feedback@oppia.org).
```

However, we should make sure this change is done in an easy-to-maintain way. In particular, we should find a way to:
- Ensure Play Store descriptions can exist inside the local repository
- Play Store descriptions can be localized (e.g. via Translatewiki, though Play Store also automatically translates these)
- Specialize the description for different release tracks (so that we can have a specific message for beta, as indicated above)

**Comment by BenHenning** [comment]
Confirming that the Play Store description is not yet updated. Specifically, the feature graphic and screenshots need updating before I think we can release.

I don't plan to do any of the generic work listed above during this release, but it's being considered as part of the broader release automation work.

**Comment by BenHenning** [comment]
It seems the description is now fully updated on Play Console and is just waiting for Google approval. Marking this as fixed.

**Comment by KolliAnitha** [comment]
Unable to verify the message as the app is not yet moved to LIVE.
![Screenshot_2022-09-10-09-14-18-90_b5a5c5cb02ca09c784c5d88160e2ec24](https://user-images.githubusercontent.com/101634267/189468801-12286b0a-92f2-4f9f-af46-dd7e902ff65a.jpg)
