### ISSUE TITLE
Profile page is cut off with small display size

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#431]

**Comment by BenHenning** [comment]
@jamesxu0 is this going to be fixed with the remaining profile work?

**Comment by anandwana001** [comment]
I checked on 480*800 hdpi. Could you please post a specific screenshot or configuration?

![Screenshot_1594185195](https://user-images.githubusercontent.com/25057618/86879128-1554ce80-c108-11ea-88ac-37bd7a49185e.png)

**Comment by BenHenning** [comment]
@anandwana001 how does the profile list look (both in newcomer and existing user mode) under the same display settings? Also, what about all other profile pages? I don't remember which one had issues, but we should check all of them.

**Comment by anandwana001** [comment]
Adding screenshot for reference. 

What we need actually? -> In this particular case when a user has not added any profile once, both the items should be completely visible on the screen. 

### Screenshot
Nexus S
![Screenshot_1595586090](https://user-images.githubusercontent.com/25057618/88393568-7b657500-cddb-11ea-9189-528d86fcdb57.png)

**Comment by anandwana001** [comment]
For reference, 
We are in discussion with Chantel regarding supporting the lower devices for mock

**Comment by rt4914** [comment]
@Pranav-Bobde Can you leave a comment on this issue mentioning you are working on it.

**Comment by Pranav-Bobde** [comment]
working on it
