### ISSUE TITLE
Replace numbers with digits in the "Place Values" chapter one lesson

### ISSUE THREAD

**Issue by gtfrans2re** [oppia/oppia-android#4314]
**Describe the bug**
In the "Place Values" chapter one lesson, there is a need to replace numbers by digits indicating Jaime's score at the arcade game. In fact, the score is a number made up of digits. As a result, instead of stating "Jaime's score has a lot of numbers in it," it should rather be "Jaime's score has a lot of digits in it."

**To Reproduce**
1. Go to 'Oppia Android App'
2. Click on 'Place Values' beneath All Topics
3. Click on 'Lessons'
4. Click on '1. What are the Place Values?' lesson
5. Click on 'CONTINUE'

**Expected behavior**
Digits should be used to indicate Jaime's score at the arcade game.

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.

Observation
![numbersIssueAndroid](https://user-images.githubusercontent.com/67015080/164970136-12443e62-19b7-415a-8f95-ddc64f195e11.png)

Reference
![numbersReference](https://user-images.githubusercontent.com/67015080/164969722-a897f3e5-811c-4bf7-ae7f-1a73e8cf9ba2.png)

**Environment**
- Device being used: Samsung Galaxy s6 edge +
- Android version: Android 7.0
- App version: 0.6-alpha-de345f92ee

**Additional context**
Please let me know if you need any further clarifications. Thanks in advance !

**Comment by BenHenning** [comment]
@seanlip since this is a content issue, could you follow-up or delegate to someone on the content team? If there's an actual action item here, I'm happy to keep this issue open to track the content being changed (since I know content issues are tracked separately).

**Comment by BenHenning** [comment]
Hi @gtfrans2re. Thanks for filing the issue! We'll be following up on the specific content change request once we have someone from the lesson content team take a look at the details you've provided.

**Comment by gtfrans2re** [comment]
Hello, @BenHenning. Thank you for your comment. 
I hope to see the change soon. Thanks again !

**Comment by seanlip** [comment]
Sorry for the late reply -- I just realized I had a bunch of issues assigned to me on the Android repo.

As discussed on https://github.com/oppia/oppia/issues/15392, we are not going to fix this. Please see that issue for the rationale.

**Comment by gtfrans2re** [comment]
> Sorry for the late reply -- I just realized I had a bunch of issues assigned to me on the Android repo.
> 
> As discussed on [oppia/oppia#15392](https://github.com/oppia/oppia/issues/15392), we are not going to fix this. Please see that issue for the rationale.

Thank you so much, Sean.
