### ISSUE TITLE
Talkback is reading astreisk for required fields 

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4322]
**Describe the bug**
Talkback is reading astreisk for required fields 

**To Reproduce**
1. Click on Add Profile
2. Enable Talk back
3. Navigate across page

**Expected behavior**
Talk back should read required or mandatory as a label for mandatory fields instead of astreisk

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

https://user-images.githubusercontent.com/101634267/165506491-9ed35fef-952f-48f8-a954-0608649d2905.mp4

**Comment by BenHenning** [comment]
I suspect this is probably a good second issue and will likely involve splitting up the strings coming from strings.xml such that the asterisk isn't part of the string, and is instead concatenated onto it.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).
