### ISSUE TITLE
Derive a ratio concept card picture & content is wrong

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#433]

**Comment by vinitamurthi** [comment]
This was what was present in the skill, what should the content and picture be? @seanlip @BenHenning

**Comment by seanlip** [comment]
The content wasn't in the spreadsheet originally, sorry about that. I've just written it, here it is:

-----

A ratio represents a **relative** relationship between two or more amounts. To write a ratio, start by writing these amounts, separating them by a colon. Remember that the order matters!

For example, let's say you have 9 apples and 6 pears. You can write the ratio of apples to pears as **9 : 6**.

If, instead, you have 3 pears, 5 apples and 9 bananas, you can write the ratio of apples to bananas to pears as **5 : 9 : 3**. Notice that the order of items in the ratio follows the order that was asked for.

---

For the thumbnail, I think you can use something like this (feel free to crop/modify to an appropriate size):

![ratio_thumbnail](https://user-images.githubusercontent.com/10575562/69764673-0e9fbb00-1126-11ea-86fb-96f42f13c36d.png)
