### ISSUE TITLE
Mismatch with the option selected and the description shown after submitting it in chapter The Importance of Order

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4341]
**Describe the bug**
Mismatch with the option selected and the description after submitting it in chapter The Importance of Order

**To Reproduce**
1. Go to Topic "Ratios and Proportions"
2. Open Chapter "Importance of Order"
3. Get to the question "What is a shorter way to correctly state the ratio of ingredients needed for the mango smoothie"
4. Submit the answer "The ratio of milk to mango puree is 1:2"
5. Verify the description displayed saying No, that's not correct.

**Expected behavior**
The option should be modified as per the description as the description shows The ratio of mango puree to milk is 1:2

![Screenshot_2022-04-29-17-11-26-73_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/166481611-f4468586-72ad-418f-9d1b-2f94f3f1a07f.jpg)

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

**Comment by BenHenning** [comment]
@seanlip this appears to be a content error. Are you aware of it?

**Comment by seanlip** [comment]
Sorry for the late reply. I wasn't aware of this before, but it is now fixed on the server. (It seems to have been introduced during an edit to the lessons based on learner feedback, but the edit was done incorrectly.)

Thanks @KolliAnitha for finding this!

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).

**Comment by BenHenning** [comment]
This should be fixed given Sean's earlier comment. @KolliAnitha could you please verify in the latest beta version?

**Comment by KolliAnitha** [comment]
Verified in latest beta build 0.10-beta-5e64fae55e. Working fine, please refer to the below screenshot.

![Screenshot (Nov 14, 2022 12_23_40 PM)](https://user-images.githubusercontent.com/101634267/201594489-395ebc30-4eed-4c34-be0f-1bb2ecd3e1b7.jpg)
