### ISSUE TITLE
To review: PRs requiring Akshay approval

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4344]
The following PRs require post-merging PR approval from @anandwana001 :
- [x] #4307
- [x] #4271

Note that these were force-merged due to the sensitive timeline they're part of.

Reviewer: please review the above PRs & check them off once complete. Assign back to me once all have been addressed. Comments can be left directly on the original PRs, and I'll follow up with one PR to address all of them (if code changes are needed, otherwise I'll follow up on the corresponding PRs). This issue should only be closed once you're satisfied with all of the changes, including needed follow-up changes.

**Comment by BenHenning** [comment]
@anandwana001 could you please review the above merged PRs per the instructions in the opening comment?

**Comment by anandwana001** [comment]
Done

**Comment by anandwana001** [comment]
Closing this issue as both the PRs I had reviewed and extra follow-up is needed.

**Comment by BenHenning** [comment]
> Closing this issue as both the PRs I had reviewed and extra follow-up is needed.

Sorry, to double check @anandwana001, did you mean to say that no extra follow-up is needed? Otherwise, I'd expect this issue to remain open until such items are addressed. Could you please clarify?

**Comment by anandwana001** [comment]
> > Closing this issue as both the PRs I had reviewed and extra follow-up is needed.
> 
> Sorry, to double check @anandwana001, did you mean to say that no extra follow-up is needed? Otherwise, I'd expect this issue to remain open until such items are addressed. Could you please clarify?

I didn't saw any extra follow-up is required.

**Comment by BenHenning** [comment]
> > > Closing this issue as both the PRs I had reviewed and extra follow-up is needed.
> > 
> > 
> > Sorry, to double check @anandwana001, did you mean to say that no extra follow-up is needed? Otherwise, I'd expect this issue to remain open until such items are addressed. Could you please clarify?
> 
> I didn't saw any extra follow-up is required.

Thanks for confirming @anandwana001!
