### ISSUE TITLE
Spelling mistake is seen while setting up pin in 'Enter a New Pin' dialog box

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4352]
**Describe the bug**
Spelling mistake is seen while setting up pin in 'Enter a New Pin' dialog box

**To Reproduce**
1. Select a learner to login
2. Click on 'I forgot my PIN'
3. Enter admin pin 
4. Enter a new pin dialog box will be seen
5. Verify the dialog box

**Expected behavior**
This PIN will be <users> new PIN and will be required when signing in. should be seen

Actual Result:
This PIN _wil_ be <users> new PIN and will be required when signing in. is seen

![Screenshot_2022-04-29-12-28-21-34_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/167570073-d79be91d-8970-49f1-ac36-2c269eb3cbe8.jpg)

Environment
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

**Comment by saudAnwar786** [comment]
hey ! I can solve this issue very quickly

**Comment by rishidyno** [comment]
Hey, @saudAnwar786 I have assigned this to you.

**Comment by saudAnwar786** [comment]
I will resolve it by tomorrow .
Thanks for assigning the task

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).

**Comment by pratyaksh1610** [comment]
@BenHenning Pls assign this issue to me , if it is not assigned yet, I would love to contribute.

**Comment by pratyaksh1610** [comment]
@rishidyno I have resolved this issue. Pls assign this issue to me.

**Comment by vrajdesai78** [comment]
@saudAnwar786 unassiging you from this issue due to inactivity from last 2 months.

**Comment by pratyaksh1610** [comment]
@vrajdesai78 I have made a PR.
