### ISSUE TITLE
In Profile selection page, accessibility scanner shows an error for a profile status

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4356]
**Describe the bug**
In Profile selection page, accessibility scanner shows an error for a profile status

**To Reproduce**
1. Open Oppia
2. Have multiple profiles with last seen status
3. Enable Accessibility scanner

**Expected behavior**
No errors must be seen in the page

Actual behabior:
 An error for text contrast is seen for Last seen recently status

![Screenshot_2022-04-13-15-16-48-89_80a9469f53bfe75dbc6e8989be28e2f0.jpg](https://user-images.githubusercontent.com/101634267/168259113-d8338bab-b77a-499f-9afa-72c29a500afc.jpg)![Screenshot_2022-04-13-15-16-45-73_80a9469f53bfe75dbc6e8989be28e2f0.jpg](https://user-images.githubusercontent.com/101634267/168259309-9f79b89b-a820-470a-aaac-6eddbd3de53e.jpg)

Environment
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

**Comment by duttabhishek0** [comment]
Hey, I tested it, but there was no suggestion. Any other way to reproduce the error?
Environment
Device name: Samsung A50
Android version : Android 11
App version : 0.7-alpha-d1b2827517

**Comment by KolliAnitha** [comment]
Hi Abhishek, Create around 9 profiles and login with all the users so that we can see the last seen status for each user and then take a screenshot in the accessibility scanner.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).

**Comment by rt4914** [comment]
@seanlip @BenHenning 
I thinks this error can be ignored (not fully sure). This error is because of the gradient of `Administrator Controls`. 
So basically the UI of all profiles (images + names) is below and above that we have a UI with a slightly gradient (black to white sort of) background with `Administrator Controls` text written. Because the gradient is above profile image+name+last-used the accessibility scanner is giving this error.

**Comment by seanlip** [comment]
Per offline discussion with @rt4914, I agree this is fine to close. Talkback users can still hear the text, and sighted users can just scroll the page. So I don't think this is an issue.

@BenHenning Please feel free to reopen if you disagree. Thanks!
