### ISSUE TITLE
With talkback enabled, on navigating to next pages in an exploration the focus is going to Continue/submit buttons

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4359]
**Describe the bug**
With talkback enabled, on navigating to next pages in an exploration the focus is going to Continue/submit buttons

**To Reproduce**
1. Go to Place Values
2. Open 'Comparing numbers'
3. Click on the Continue button
4. Go to Question page submit answer 
5. In the next page check where the focus is on

**Expected behavior**
On moving to the next pages, focus should be on the content, questions not on the buttons

https://user-images.githubusercontent.com/101634267/168569832-bfcf6f24-ee8e-4e87-8211-907a2877b6f2.mp4

Environment
Device name: One plus Nord2 5G
Android version : Android 11
App Version: 0.7-alpha-6c08d882d3

**Comment by BenHenning** [comment]
This isn't a new issue in MR4, and seems to be part of the broader accessibility focus/ordering problems in the exploration player. Moving it to the CLAM team for triaging.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).

**Comment by rt4914** [comment]
Duplicate https://github.com/oppia/oppia-android/issues/3893
