### ISSUE TITLE
When reading text size is extra large, resume lesson page and revision tabs content is seen in normal size

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4362]
**Describe the bug**
When reading text size is extra large, resume lesson page and revision tabs content is seen in normal size

**To Reproduce**
1. Go to 'Navigation menu'
2. Click on 'Options'- Change Reading text size to Extra large
3. Open any exploration which is in progress
4. The Resume page will be seen in normal text size

**Expected behavior**
Resume lesson page should also be in Extra large size
In the Revision tab, click on any tile the content is displayed in normal text size

![Screenshot_2022-05-16-16-35-00-35_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/168581188-f38f3c3b-6981-4f52-a3ea-47fd7ac0eebe.jpg)

Environment:
Device name: One plus Nord2 5G
Android version : Android 11
App version: 0.7-alpha-6c08d882d3

**Comment by BenHenning** [comment]
This is a known issue, though I don't think there's anything tracking it currently. Adding to the CLAM team's board for triaging.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).

**Comment by KevinGitonga** [comment]
Closed this since it is possibly the same issue as #4710 whereby resume lesson screen buttons are not scaling as expected when font size and display are set to max on device settings.

**Comment by adhiamboperes** [comment]
Re-opening this since it is not actually tied to  https://github.com/oppia/oppia-android/issues/4710 even though the screenshots here have the same bug as  https://github.com/oppia/oppia-android/issues/4710.

**Comment by adhiamboperes** [comment]
As per [issuecomment](https://github.com/oppia/oppia-android/issues/4710#issuecomment-1433999958), the app controlled reading text size is limited to in-lesson. Do we have plans to resolve this? (Adding this to the backlog).
