### ISSUE TITLE
Able to access the app after expiry date if app is accessed through recent apps

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4364]
**Describe the bug**
Able to access the app after expiry date if app isnt closed before changing date

**To Reproduce**
1. Open Oppia
2. Login as admin and open any exploration
3. Donot close the app. Go to home page 
4. Open settings- Change date time to Jan 1st 2023
5. Open app from recent apps

**Expected behavior**
User should not be able to access the app after expiry date

https://user-images.githubusercontent.com/101634267/168597484-2b224a28-7ae1-425c-82f0-7707e16b977c.mp4

Environment:
Device name: One plus Nord2 5G
Android version : Android 11
App version: 0.7-alpha-6c08d882d3

**Comment by BenHenning** [comment]
This is an expected limitation in the current expiration mechanism. The app will eventually close and then the mechanism will kick-in. I think this edge case is fine to keep in.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).
