### ISSUE TITLE
Audio language is auto changed to English after selecting Default audio language 

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4373]
**Describe the bug**
Audio language is auto changed to English after selecting Default audio language 

**To Reproduce**
1. Go to 'What is a Ratio?' Chapter
2. Click on audio symbol- Change the language to Hindi
3. Now click on Options- Default Audio Language- Set to No Audio
4. Now open the Audio language options
5. English is selected as the Audio language instead if Hindi

Expected behavior:
Audio language should be Hindi as it is selected by user

https://user-images.githubusercontent.com/101634267/169824430-48685b88-2c23-4755-978d-45ee93c189c7.mp4

Environment:
Device name: One plus Nord2 5G
Android version : Android 11
App version: 0.7-alpha-6c08d882d3

**Comment by debz-g** [comment]
I tried replicating the issue with the above steps on the latest branch as of today. It seems the issue has been solved. 

Tested on: Pixel 6 Android 13

**Comment by seanlip** [comment]
Thanks @debz-g for checking. @KolliAnitha could you please double-confirm with the latest build so we can close this issue? Thanks!

**Comment by KolliAnitha** [comment]
@seanlip, now there is no option for 'No audio' in the Options layout. If I change to any other language and open the audio language it is working fine. 

![Screenshot_2023-01-24-08-36-05-44_943a62cb4c6fb83e010e1c2e82766a17](https://user-images.githubusercontent.com/101634267/214204428-f4a42d76-028d-4b8f-ac56-921306219f88.jpg)

**Comment by seanlip** [comment]
Yup, the "No audio" was removed in this PR: https://github.com/oppia/oppia-android/pull/4575 (the reasoning is there as well). So I think this issue can be closed. Thanks @debz-g for checking on this, and @KolliAnitha for re-verifying!
