### ISSUE TITLE
Different shades of fillColor used in portrait and landscape of ic_onboarding_2.xml

### ISSUE THREAD

**Issue by bhaktideshmukh** [oppia/oppia-android#4381]
**Describe the bug**
In Onboarding Screens the color codes / slide images are not consistent. The images use different color codes for different screen/mode/orientation. This is not just limited to one single slide but infact extends to all slides. Check slide-3 for reference:

### Example: Download icon color
[Mobile Portrait](https://xd.adobe.com/view/3dca36c2-5115-419c-b25e-0f10526b077c-6899/screen/9caedbc6-7055-4cff-88e6-caf0052bcf0b/) -> `#00645c`
[Mobile Landscape](https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/638f81ac-1f59-4b8b-b708-437014a309f7/) -> `#0d645c`
[Tablet](https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/0102051d-8e8c-40e5-a7e1-38f9275eda9a/) -> `#02655c`

[Dark Mode](https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/9caedbc6-7055-4cff-88e6-caf0052bcf0b/) -> `#3BD1C4`

**Expected behavior**
The images should have a consistent behaviour atleast in terms of color-codes for light mode.
For now use `#00645c` for all types of images for dark-mode as well as night mode. If in PR the screenshots of dark-mode does not look good then in that case we might consider changing colors for dark-mode too. 

**In your PR please create following screenshots**
1. Mobile Portrait - Dark mode and Light mode for all 4 slides
2. Mobile Landscape - Dark mode and Light mode for all 4 slides
3. Tablet Portrait - Dark mode and Light mode for all 4 slides
4. Tablet Landscape - Dark mode and Light mode for all 4 slides

**Comment by MihirShirgaonkar** [comment]
hello @bhaktideshmukh 
I'm intrested to contribute in this project and also im beginner to open source 
can u please help me to start with?

**Comment by bhaktideshmukh** [comment]
> hello @bhaktideshmukh I'm intrested to contribute in this project and also im beginner to open source can u please help me to start with?

Welcome to Oppia @MihirShirgaonkar, you firstly need to sign the CLA to proceed with the contributions.
You can follow the instructions mentioned [here](https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android#onboarding-instructions) to sign the CLA and fill out the contributor survey.

**Comment by Joaquin144** [comment]
Hi. I am interested to work on this issue.

**Comment by bhaktideshmukh** [comment]
> Hi. I am interested to work on this issue.

Sure go ahead, but you need to sign the CLA to proceed further if you haven't filled it yet then you can follow [these](https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android#onboarding-instructions) instructions and if you have already filled you are good to go, I see you are already assigned.

**Comment by Joaquin144** [comment]
Yes I have signed the CLA few days before.

**Comment by MohitGupta121** [comment]
@BenHenning I think this issue is fixed by @rt4914 in PR #4774 
So can we close this issue @rt4914 ?
