### ISSUE TITLE
Text doesn't change when using non-English languages

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4394]
**Describe the bug**
In-lesson reading text size doesn't change when selecting different sizes when using a language other than English.

**To Reproduce**
1. Select a non-English language at the system level (e.g. Swahili)
2. Open a lesson and navigate to a chapter
3. Open the options overflow and navigate to reading text size
4. Select a text size & navigate back to the options screen
5. Observe that the reading size (subtext) hasn't changed
6. Navigate back to the exploration (you may need to leave and re-enter it per #4285)
7. Observe that the text size hasn't changed

**Expected behavior**
The reading text size should change when a new size is picked regardless of language, and should be reflected in the options screen.

**Demonstration**
Not including this initially, but I can if it's needed.

**Environment**
- Device/emulator being used: Nexus 5X
- Android or SDK version (e.g. Android 5 or SDK 21): 8.1.0
- App version (you can get this through system app settings or via the admin controls menu in-app): tip-of-tree (0.8), but it probably affects all releases since internationalization was introduced (0.6 and 0.7).

**Additional context**
This was brought up in a discussion regarding the Kenya research project. It was assumed to be the same issue as #4285 until I accidentally stumbled upon it and realized that the feature completely breaks (vs. being awkward and needing a UI restart).

**Comment by BenHenning** [comment]
(Adding this to the Alpha MR5 milestone since this is actually a bit important to try and fix, especially since it's hopefully relatively straightforward).

**Comment by BenHenning** [comment]
@KolliAnitha this might indicate that we aren't testing internationalization cases in our test matrix. Are we ensuring that different features are tested (at least occasionally) with non-English?

/cc @seanlip as FYI

**Comment by KolliAnitha** [comment]
Hi Ben, I will add localization cases in the test matrix and ensure to cover them going forward.

**Comment by KolliAnitha** [comment]
User is able to change the reading text size in non-english language(Portugese) in beta version.
