### ISSUE TITLE
Add CI checks to ensure layout xml files are only referencing colors from component_colors.xml

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#4396]
According to newer color conventions, all layout files should only access colors from `component_colors.xml`. 
Add a CI check ensuring the same.

Reference: #4203, #4205

**Comment by MohitGupta121** [comment]
@BenHenning We need to add these CI checks only for xml files or also for .kt files?

**Comment by BenHenning** [comment]
> @BenHenning We need to add these CI checks only for xml files or also for .kt files?

We should add the checks for both, but for Kotlin files we should focus on user-facing components: activities, activity presenters, fragments, fragment presenters, views, and view presenters.
