### ISSUE TITLE
Full UI: ProfileSelectionFragment/Activity [Blocked: #11, #16, #168]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#44]
The profile selection page may require a lot of custom UI that's not broadly available in the Google material design component libraries. See the PRD for specifics.

## Auth Screen
- [ ] Auth Screen: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/a841330e-efe5-4bdb-acdd-4d6e52a59571/PC-MP-Admin-Authorization-Empty-
 (@rt4914 )
- [ ] Submit Button active/inactive
- [ ] Submit button should be visible above keyboard
- [ ] Submit button in keyboard should submit the pin directly.
- [ ] Accessibility test

## Add Profile Screen
- [ ] Add Profile Screen: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/bdbfc057-f662-4ce1-b142-7e842ed65afb/PC-MP-Add-Profile-Empty- (@nikitamarysolomanpvt waiting for design) 
- [ ] Create Button active/inactive
- [ ] Create button should be visible above keyboard
- [ ] Create button in keyboard should submit the pin directly.
- [ ] Accessibility test

## Profile Chooser
- [ ] Profile Chooser Screen: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/ad1de6e2-1d5d-4ac3-888c-58d036c7ede4/PC-MP-Profile-Chooser- (@veena14cs )
 - [ ] Accessibility test

**Comment by BenHenning** [comment]
This is blocked on #4, #11, and #16.

**Comment by BenHenning** [comment]
This is also blocked on #168.

**Comment by rt4914** [comment]
@jamesxu0 Can you please mention all the links in here, which will be part of profile-selection, so that I can divide the High-fi work in that.

**Comment by jamesxu0** [comment]
@rt4914 What links are you referring to?

**Comment by rt4914** [comment]
> @rt4914 What links are you referring to?

@jamesxu0 from [mocks](https://xd.adobe.com/view/bee1fced-33bd-4f69-6a89-2c30fe1c4f65-c8d0/grid), what all links you have used to create ProfileSelection, I want all those links so that I can divide the High-fi issues accordingly.

**Comment by jamesxu0** [comment]
> @jamesxu0 from mocks, what all links you have used to create ProfileSelection, I want all those links so that I can divide the High-fi issues accordingly.

@rt4914 
- https://xd.adobe.com/view/bee1fced-33bd-4f69-6a89-2c30fe1c4f65-c8d0/screen/ad1de6e2-1d5d-4ac3-888c-58d036c7ede4/PC-MP-Profile-Chooser-
- https://xd.adobe.com/view/bee1fced-33bd-4f69-6a89-2c30fe1c4f65-c8d0/screen/a82ac74b-b0fa-4b4e-93d3-da83bee54900/PC-MP-Profile-Created-Visible-

**Comment by rt4914** [comment]
@jamesxu0 Thanks.

**Comment by nikitamarysolomanpvt** [comment]
@mschanteltc Please do update on this when Add Profiles screen updated design is ready.

**Comment by mschanteltc** [comment]
> @mschanteltc Please do update on this when Add Profiles screen updated design is ready.

I updated the mocks but on the [v7 prototype](https://xd.adobe.com/view/54bd2eee-0536-4504-4976-8e2211bd169a-228c/screen/a841330e-efe5-4bdb-acdd-4d6e52a59571/PC-MP-Admin-Authorization-Empty-/). The features are also described in the [PRD](https://docs.google.com/document/u/1/d/1Ae587Q1ggfoca0j5j44LO3VFx_Z35oklyTcPZbz2w3I/edit?ts=5d02d804&urp=gmail_link#heading=h.q8u8btmzdymw).

**Comment by BenHenning** [comment]
What work is left here @rt4914?

**Comment by rt4914** [comment]
Just checked again, this issue has been finished way back via different sub issues. So closing this now.
