### ISSUE TITLE
Dark Mode support for Confetti

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#4409]
As per [this](https://github.com/oppia/oppia-android/pull/4404#issuecomment-1168046385) comment we should see if confetti requires dark-mode support or not.

This issue still need discussion to finalise the decision.

**Where is this confetti shown?**
Whenever user answers correctly in Question/Exploration player the confetti is show as below images.
And whenever the exploration / question player is finished completely by answering correctly the confetti is again shown but in a different way.

<img src="https://user-images.githubusercontent.com/78796264/175898797-2fb06705-7249-4a57-8e1b-2ea127c0fa9c.jpg" width="250" /> <img src="https://user-images.githubusercontent.com/78796264/175898808-f6ac3f40-9839-4943-8799-1b3b278a1f3c.jpg" width="250" />

**Comment by findimue** [comment]
Yes, I think the colors of the confetti in dark mode need to be changed/lightened up.

**Comment by findimue** [comment]
I suggest changing the colors in dark mode to these accent colors from our Oppia Design Guide. 
The yellow would be changed to #EFCF24.
The red would be changed to #EA6390.
The blue would be changed to #49A9E5. 
![Swatches for Confetti in Dark Mode](https://user-images.githubusercontent.com/34294292/187840440-83f09110-8be8-4741-8892-1cb3cdffd245.svg)

**Comment by seanlip** [comment]
Thanks @findimue!

@MohitGupta121 -- would you like to take this up, per our discussion in the meeting?

**Comment by MohitGupta121** [comment]
Okay sure @seanlip I start working on this also.
