### ISSUE TITLE
Update Oppia logo (app icon) for beta

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4413]
The current logo is a placeholder and should be updated for beta.

**Comment by isalooo** [comment]
I updated the app icon already. Do we have a separate issue for the adaptive icon or should that be tracked here as well?

**Comment by BenHenning** [comment]
Ah, I forgot I filed this issue. Let's track the adaptive icon here, too @isalooo.

Please upload resources here once they're ready.

**Comment by KolliAnitha** [comment]
Oppia logo is now changed below.
![Screenshot_2022-09-10-09-58-58-80_3f76808b89d2117205aad87459958156](https://user-images.githubusercontent.com/101634267/189468767-3b4ed788-c921-4f46-a00a-0bd49a8c0c2e.jpg)
