### ISSUE TITLE
Update topics for beta

### ISSUE THREAD

**Issue by isalooo** [oppia/oppia-android#4435]
Topics for beta include: 

1. Places Values
2. Addition and Subtraction
3. Multiplication
4. Division
5. Fractions
6. Ratios

***Not included***

1. Expressions and Equations
2. Percentages

**Comment by BenHenning** [comment]
It seems multiplication will also be excluded due to missing pt-BR translations (as of now), but the other 5 topics should be good to go. I've pulled them and have them standing by for when the beta release can be cut.

**Comment by BenHenning** [comment]
Confirming that the assets script has been updated successfully to pull in the following (expected) topics for Beta MR1:
- Place Values
- Addition and Subtraction
- Division
- Fractions
- Ratios and Proportional Reasoning

Verification screenshot:

![image](https://user-images.githubusercontent.com/12983742/189315547-efc383e8-9188-418e-97dd-9cecd5f83a33.png)

**Comment by KolliAnitha** [comment]
Beta version has only the below chapters. Working as expected.
Place Values
Addition and Subtraction
Division
Fractions
Ratios and Proportional Reasoning
