### ISSUE TITLE
[Cleanup] Migrate all fragment arguments & activity parameters to proto values

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4437]

**Comment by seanlip** [comment]
@BenHenning Could you please add a description for this issue?

**Comment by Vishwajith-Shettigar** [comment]
Hi @seanlip, this issue has already been addressed in #4986.

**Comment by BenHenning** [comment]
Thanks @Vishwajith-Shettigar. You're correct that #4986 addresses this issue plus more, so closing this in favor of that one.
