### ISSUE TITLE
Change speaker icon to headphones icon

### ISSUE THREAD

**Issue by JishnuGoyal** [oppia/oppia-android#4439]
**Is your feature request related to a problem? Please describe.**

According to the user reports, some users do not understand what the speaker button on the exploration screen does. Change it to a headphones button instead. Make sure that the button has both on and off states displayed correctly. This issue is a part of the GSoC Interactive Onboarding Flow project.

**Comment by JishnuGoyal** [comment]
Please assign this to me @BenHenning

**Comment by BenHenning** [comment]
Done @JishnuGoyal. FYI that you'll be able to self-assign once your onboarding is complete.
