### ISSUE TITLE
Hide Info tab

### ISSUE THREAD

**Issue by JishnuGoyal** [oppia/oppia-android#4447]
**Is your feature request related to a problem? Please describe.**
According to the recent user studies, the info tab does not provide much information to the user. Some users do not understand what to do on this screen and keep on clicking on the 'topic downloaded' button hoping to start a lesson.

**Describe the solution you'd like**
Remove the info tab and make the lessons tab as the default landing page for topics screen.

**Comment by MihirShirgaonkar** [comment]
@JishnuGoyal  can u assign me this task? i have solution for this task.

**Comment by BenHenning** [comment]
@MihirShirgaonkar sorry this is actually being worked on by @JishnuGoyal as part of a broader project (he just wasn't able to self-assign before).
