### ISSUE TITLE
Hide promoted story section for the first time user

### ISSUE THREAD

**Issue by JishnuGoyal** [oppia/oppia-android#4448]
**Is your feature request related to a problem? Please describe.**
The recent user reports suggest that there isn't a clear CTA on the home screen. The users cannot decide what to do next.

**Describe the solution you'd like**
We need to minimize the amount of information presented to a user at a particular time. This can be achieved by hiding the promoted story section when the user logs in for the first time. This way, the focus would be to help them start their first lesson from the topics list. A clear CTA also needs to be added as the topics list header. Note that when the user enters the app for the second time (and every time after that), we should make sure that the promoted stories section is displayed as usual.

**Comment by MihirShirgaonkar** [comment]
I have a doubts.
does promoted story mean recommended story provision and i have to hide it and show only All Topics provision at 1st launch?

**Comment by BenHenning** [comment]
> I have a doubts. does promoted story mean recommended story provision and i have to hide it and show only All Topics provision at 1st launch?

Yep @MihirShirgaonkar that is the intention for this task. This is meant to address a point of user onboarding confusion that we observed in past user studies.

**Comment by JishnuGoyal** [comment]
#4430
