### ISSUE TITLE
Modify the design of the chapter list in lessons tab

### ISSUE THREAD

**Issue by JishnuGoyal** [oppia/oppia-android#4449]
**Is your feature request related to a problem? Please describe.**
The chapters (recycler items) on the lessons tab do not look clickable. Users do not get an idea of how to start a chapter from that screen.

**Describe the solution you'd like**
Modify the design of the chapter list so that it clearly shows chapters that are completed, ready to start and locked. Also, make sure that the chapter list  drop down is open by default.

**Comment by BenHenning** [comment]
Reopening since #4535 was reverted in #4603.

**Comment by BenHenning** [comment]
#4604 may be helpful when looking into fixing the issues.

**Comment by JishnuGoyal** [comment]
Thanks, I'll be following up on this.
