### ISSUE TITLE
Add Wiki documentation for adding the spotlight experience to any element 

### ISSUE THREAD

**Issue by JishnuGoyal** [oppia/oppia-android#4460]

**Comment by BenHenning** [comment]
@JishnuGoyal has this been completed?

**Comment by JishnuGoyal** [comment]
Yes, this has been updated. PTAL. @BenHenning

**Comment by seanlip** [comment]
@JishnuGoyal Could you please add a link in this thread to the wiki documentation in question?

**Comment by JishnuGoyal** [comment]
Here is this link to the Spotlight Wiki doc: https://docs.google.com/document/d/1houcOoZLbTgdwnL1HnmocolEjP6exfY-R_qsNbYPY7Y/edit#

I believe this is fully complete now. @BenHenning PTAL, thanks!

**Comment by seanlip** [comment]
@JishnuGoyal As discussed in chat, please make a PR to the oppia-android repo the usual way, and @BenHenning can review that directly. Note that the wiki pages are now stored within the repo, see https://github.com/oppia/oppia-android/tree/develop/wiki. Thanks!
