### ISSUE TITLE
Add analytics for answers

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#4467]
Per discussion with @BenHenning, the aim of this feature request is to log incorrect answers so that weak points in the lessons can be identified and fixes made for them.

**Describe the solution you'd like**

Exploration ID and state name should be collected, but no user-identifying information.

Proposed (temporary) format:
- Multiple choice: the index or content ID
- Numeric: the text representation of the number entered
- Text input: the raw text
- Item-selection/Drag-and-drop: something like "[1, 2]" if we have access to the indexes, otherwise just skip.
- Math expressions and their variants: any text representation will do, we can decode it at analysis time
- Image region selection: "(0.35, 0.25)" where these are the normalized x/y coords
- FractionInput: "3/5"
- Ratios: just the string representation
- Anything else that's not obvious: just skip (this applies to any of the above items that are hard to obtain)

**Additional context**
Known constraints: event parameter values can only be up to 100 chars long. This could be exceeded with e.g. TextInput so some truncation may be necessary (if it's not automatically done).

**Comment by BenHenning** [comment]
Thanks for filing this @seanlip!
