### ISSUE TITLE
Improve accessibility for custom text-based interactions 

### ISSUE THREAD

**Issue by vrajdesai78** [oppia/oppia-android#4475]
**Describe the bug**
For InputInteractions like FractionInputInteraction, NumericInputInteraction, TextInputInteraction, MathExpressionInteraction, and
RatioExpressionInteraction content description is not set. So, when talkback is turned on it will read hint, but when we click on editbox and press back hint will disappeared and after that there is no content description for these interactions. 

**To Reproduce**
1. Open any story from Exploration or Question player which has text-based interaction as mentioned above. 
2. Turn on talkback reader. 
3. Click on editbox and press back
4. Now navigate to editbox using talkback reader

**Expected behavior**
Every text-based input interactions should have content description apart from hint. 

**Demonstration**
GIF Drive Link: https://drive.google.com/file/d/1xRry56PNeOhcxPIOYaaewf6xGYaBUYCB/view?usp=sharing 

**Environment**
- Device being used: Realme GT Master Edition
- Android or SDK version: Android 12
- App version : 1.0

**Comment by vrajdesai78** [comment]
@rt4914 I think this issue is solved now, as with current develop branch the input interaction is holding the hint text even when we press back. You can watch attached video for reference.

### Video (Current Develop)


https://user-images.githubusercontent.com/43074241/196364804-1abdfc81-499f-4e52-bc42-cfc985d4f1d9.mp4


 So, if you agree we can close this issue.

**Comment by BenHenning** [comment]
Ah, this was probably fixed with #4556 by @JishnuGoyal. That's actually quite nice to see--one less PR is needed here. I agree that we can close this. Per your video, the latest behavior looks correct.
