### ISSUE TITLE
Create documentation for Accessibility audit

### ISSUE THREAD

**Issue by vrajdesai78** [oppia/oppia-android#4476]
Make detailed documentation for Accessibility audit

**Comment by vrajdesai78** [comment]
Created document for accessibility audit. [Doc Link](https://docs.google.com/document/d/1ahw1-isEJe96Ni3Yx6l9QOHrtHFi72buBElsJAoq9pY/edit?usp=sharing)

**Comment by seanlip** [comment]
Closing this since the doc has been completed (see Vraj's comment above). Note that that audit was done around Nov 2022.
