### ISSUE TITLE
Fix ItemSelectionInput instruction to be clearer to students.

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#4491]
**Describe the bug**
The text for ItemSelectionInput is not clear to students.

**To Reproduce**
1. Go to an item selection interaction (see e.g. Multiplication 1). See screenshot below.

**Observed behavior**
The wording "Please select at least one choice." is confusing to students. They keep on choosing just one right answer and leaving the other right answers on the table, which results in them getting feedback that their answer is not correct. This leads to frustration.

**Expected behavior**
Change the prompt to "Please select all correct choices”.

**Demonstration**
![image5](https://user-images.githubusercontent.com/10575562/182777670-962d90d9-68f6-4597-ae8e-1bbb04a0c901.jpg)

**Comment by KolliAnitha** [comment]
Verified the issue in 0.8-alpha-091b45a188. 'Please select all correct choices' is displayed for multi selection inputs.
![Screenshot_2022-08-21-15-41-38-73_943a62cb4c6fb83e010e1c2e82766a17](https://user-images.githubusercontent.com/101634267/185786233-173c9a3f-12f9-4e14-a010-83ce34faa6a7.jpg)
