### ISSUE TITLE
Make the hint button animate.

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#4494]
**Is your feature request related to a problem? Please describe.**
From researcher feedback, students do not realize when a hint is available (or when a new hint is available that's different from one that they've already seen). They've also seemed fairly reticent to click on the hint button.

**Describe the solution you'd like**
Make the light bulb on the Hints button bounce up and down (possibly with some pause in between) when a hint is available. It doesn't have to be too overt; it just needs to 'softly' get the user's attention.

**Comment by seanlip** [comment]
@JishnuGoyal Do you think it would be possible to prioritize this for Alpha MR5, please? This would solve an issue that's currently being faced in the Kenya study.

/cc @BenHenning

**Comment by seanlip** [comment]
Ah sorry, I think I missed that this wasn't in your project Jishnu. I took you off the assignee list!

**Comment by JishnuGoyal** [comment]
Thanks @seanlip, let me know if any other input is needed from my side.

**Comment by KolliAnitha** [comment]
Hint button is animated. Verified and working fine in 0.8-alpha-091b45a188. 
![Screenshot_2022-08-21-15-34-39-29_943a62cb4c6fb83e010e1c2e82766a17](https://user-images.githubusercontent.com/101634267/185786009-54dce5e4-5ded-4089-ba11-990f81f3173e.jpg)
