### ISSUE TITLE
Wrong voiceover language is being played when the student selects English.

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#4495]
**Describe the bug**
When students select English as the voiceover language, the wrong voiceover plays.

From the Kenya research team: "Most of the students had chosen English but the application was speaking a language that they were not understanding."

**To Reproduce**
1. Open lesson 1 of Multiplication. 
2. Switch voiceover language to English.
3. Play the lesson to almost the end (see screenshot at bottom).
4. Observe that the voiceover plays in a non-English language.

**Expected behavior**

When a voiceover is not available in the student's preferred language, no voiceover should play by default. (Ideally there is some icon to indicate that, perhaps a slash over the voiceover icon that, when clicked, shows a "Voiceover not available" tooltip.)

**Demonstration**

From Multiplication 1, third card from the end ("TEST 3"):

![image6](https://user-images.githubusercontent.com/10575562/182964025-c4b9b676-638e-4187-a186-7b130894e57f.jpg)

**Environment**
- Device/emulator being used: <device version/emulator>
- Android or SDK version (e.g. Android 5 or SDK 21): <os/sdk version>
- App version (you can get this through system app settings or via the admin controls menu in-app): Alpha MR4

**Comment by seanlip** [comment]
Note: Assigning this to Alpha MR5, but note that it's lower priority than [the other MR5 issues](https://github.com/oppia/oppia-android/milestone/43).

**Comment by seanlip** [comment]
This might also be related to #3088 (not sure if it's close enough to be a duplicate, though). To be clear, the aim of this issue (as far as Alpha MR5 is concerned) is to fix just this specific bug and not necessarily any other issues with voiceovers.

**Comment by BenHenning** [comment]
I did repro this issue once when try to get toward the end, but didn't encounter it on the state in the opening comment. This does seem different from #3088 as that one is covering the case when English isn't available at all, whereas the issue here seems tied to the voiceover unexpectedly switching to non-English when English is both selected and available.

**Comment by KolliAnitha** [comment]
Voiceover is playing in english language till the end of the lesson except for those cards where there is no audio language in it.
Verified in 0.8-alpha-091b45a188
