### ISSUE TITLE
No enough padding on Continue button style

### ISSUE THREAD

**Issue by Chandra-Sekhar-Bala** [oppia/oppia-android#4504]
**Describe the bug**
Continue has not enough padding when reading size changed to ``` Extra Large```

**To Reproduce**
1. Go to 'Navigation menu' -> Select Option
2. Click on 'Reading text size' -> Select Extra Large
3. Open any lesson
4.  Scroll down to click on Continue

**Expected behavior**
Continue button should have good padding from both ends.

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.
<img width="177" alt="oppia_issue" src="https://user-images.githubusercontent.com/57448981/184975046-9d07d219-4fda-4de0-b98d-424cf05f3fca.png">

**Environment**
- Device/emulator being used: Pixel  4 XL
- Android or SDK version: API Level 27
- App version: 1.0

**Comment by BenHenning** [comment]
@Chandra-Sekhar-Bala have you checked whether this issue repros on the latest develop? Given the recent work on this exact issue, I'd expect this to not be an issue anymore.

**Comment by Chandra-Sekhar-Bala** [comment]
Yes, I have checked it is on the latest version. Steps are mentioned to reproduce the bug, you can verify.

**Comment by Chandra-Sekhar-Bala** [comment]
Hey @BenHenning Yes, I have checked it is on the latest version. Steps are mentioned to reproduce the bug, you can verify.

**Comment by BenHenning** [comment]
@Ryggs can you look into this since #4385 was supposed to fix this issue?

**Comment by Ryggs** [comment]
Hey @BenHenning taking a look

**Comment by Chandra-Sekhar-Bala** [comment]
@BenHenning @Ryggs  let me give my view on this,
Yes #4385 solved the alignment issue. But if you look into the style named ```@style/StateButtonActive``` you'll see padding attribute is missing. And that is the reason of this bug. 
I hope it helps :)

**Comment by Ryggs** [comment]
@Chandra-Sekhar-Bala The padding attribute is global as we are using a wrap_content and got rid of setting a max_width, hence the button behavior

**Comment by Ryggs** [comment]
Hi @BenHenning Just checked this out and this was the fix accepted by C/O @rt4914 . What would be the workaround here? The text fits overlay when in text size LARGE on phone. 
Here's the tablet view 
![image](https://user-images.githubusercontent.com/31986629/185851944-22fa0bc4-8741-4928-b229-5f46ba52c214.png)

**Comment by Chandra-Sekhar-Bala** [comment]
> @Chandra-Sekhar-Bala The padding attribute is global as we are using a wrap_content and got rid of setting a max_width, hence the button behavior

So do you prefer adding padding attribute to the style?

**Comment by Chandra-Sekhar-Bala** [comment]
I've added padding attribute which tends to solve this one I guess 
Here's an example, when padding is enabled with text size as ```Medium``` and ```Extra large```.
>Medium:
<img width="202" alt="M" src="https://user-images.githubusercontent.com/57448981/186243728-5f5706e0-7a73-4577-bbe4-4520d6687979.png">

>Extra Large:
<img width="202" alt="XL" src="https://user-images.githubusercontent.com/57448981/186243804-59cdc444-c2f7-459c-afcb-bcb9d89096ce.png">

Looking forward to know your opinion about this @Ryggs  @BenHenning !

**Comment by BenHenning** [comment]
I haven't been as involved with the nature of this particular issue or the different solutions considered. @rt4914 since you have more context, could you share your thoughts on the ongoing discussion here?

**Comment by rt4914** [comment]
@Chandra-Sekhar-Bala Yes adding padding is a better way to solve this. Basically follow these guidelines:
- Avoid giving fixed width/height
- Add padding to all sides of text -- inside button
- Use `sp` for textsize and dp for everything else.

These guidelines should be sufficient to solve this issue.

**Comment by Chandra-Sekhar-Bala** [comment]
@rt4914 Got it, thanks. I will make a PR :-)
