### ISSUE TITLE
Profile names with numbers are needed in Kenya user study

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4505]

**Comment by BenHenning** [comment]
This replaces #4002 as the priority for Alpha MR5.

**Comment by KolliAnitha** [comment]
@BenHenning, Unable to create a profile with numbers in it.

https://user-images.githubusercontent.com/101634267/186805562-14b595c1-d5c6-473a-99a5-d752e40ac8d9.mp4

**Comment by seanlip** [comment]
Hi @KolliAnitha -- I just had a chat with Ben about this. It seems that the app you tested is a different "flavour" than the one used for the Kenya study, so everything should be fine here after all. 

Thanks for filing and checking though -- we should have mentioned this at the point of kicking off the test run, but forgot!
