### ISSUE TITLE
Upgrade CI to Ubuntu 20.04

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4512]
Per https://github.com/actions/runner-images/issues/6002, Ubuntu 18.04 is now deprecated on GitHub Actions and will be fully turned down before EOY. Given the upcoming planned brownouts, it would be nice to avoid these periodic failures by migrating first.

This migration should be done in one PR for all workflows, and the PR should re-run the full workflow suites **ten** times to ensure there are no observed flakes (with no more than 3 runs per change to develop to ensure the Bazel cache continues to change, or with force-flushing of the cache and delays between runs to increase the likelihood of different CI hosts picking up the workers over time). I'm not expecting any flakes to come up from the Ubuntu upgrade, but we should plan as though they might.

**Comment by seanlip** [comment]
Just an FYI, I think @gp201 just looked into this for Oppia-Web. It seems to have gone smoothly. See https://github.com/oppia/oppia/pull/15879

/cc @U8NWXD

**Comment by BenHenning** [comment]
Thanks @seanlip. I'll probably fast track this and just keep an eye out for flakes rather than waiting on getting it merged (since it seems to be affecting folks broadly in the community).
