### ISSUE TITLE
Add Dark Mode support for BottomSheetFragment (Exploration + Revision Card)

### ISSUE THREAD

**Issue by vrajdesai78** [oppia/oppia-android#4513]
Add Dark Mode support for BottomSheetFragment in both Exploration and Revision Card. 

### Current UI

https://user-images.githubusercontent.com/43074241/185469039-24e440da-69f9-4885-938c-688e3ff3ecf6.mp4

**Comment by mahmood199** [comment]
Would like to work on this
can I be assigned to this?
