### ISSUE TITLE
Concept card is blank for a question in chapter Multiplying by multiples of ten

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4515]
**Describe the bug**
Concept card is empty for a question in chapter Multiplying by multiples of ten

**To Reproduce**
1. Go to Multiplication - Multiplying by multiples of ten
2. Click on Continue till you reach the page "What is 3264*10"
3. Enter wrong answer to get the concept card link
4. Click on Conceptc card
5. See the page

**Expected behavior**
Concept card is blank on opening the link 

**Demonstration**
![Screenshot_2022-08-20-15-13-54-24_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/185741187-211d83ef-43c3-4b25-9739-e7ffa3e3c717.jpg)
![Screenshot_2022-08-20-15-13-58-77_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/185741206-d2a3ac6d-4112-421d-bfb3-645decad3a64.jpg)

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.8-alpha-091b45a188

**Comment by seanlip** [comment]
Thanks for catching this, @KolliAnitha! The link was pointing to the wrong concept card. I have fixed it on the Oppia website.

@BenHenning -- just letting you know that the content is updated, and assigning you so that this issue can be resolved when the new content is pulled.

**Comment by KolliAnitha** [comment]
@seanlip, observed the same behavior on clicking divide a decimal by a power of 10 link in What is a percentage chapter in Percentages.
![Screenshot_2022-08-20-21-17-27-24_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/185755991-06ce5d96-597b-4e73-8cae-32d3c84b1b18.jpg)
![Screenshot_2022-08-20-21-15-12-09_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/185755995-6af53c0a-8321-47c7-a838-780e830b5239.jpg)

**Comment by seanlip** [comment]
Thanks @KolliAnitha. I think that, unfortunately, this last one will remain a bit broken until Decimals is published, since that is the topic that the concept card link is pointing to.

**Comment by BenHenning** [comment]
Per @seanlip's comment above, this should be fixed in the latest beta since it contains newly pulled content. Please verify.
