### ISSUE TITLE
Concept card link is not showing up in hints.

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4519]
**Describe the bug**
Content issue is seen for one of the hints in a question in Multi digit multiplication Part 1

**To Reproduce**
1. Go to 'Multiplication'
2. Click on 'Multi-Digit Multiplication, Part 1'
3. Click on Continue till you reach the question 'There are 3829 people in our small town'
4. Enter wrong answers to get 5hints

**Expected behavior**
If you need help adding numbers with carrying, take a look at this <link> for a refresher. should be seen

**Demonstration**
![Screenshot_2022-08-20-18-31-44-54_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/185777877-c3761b06-fc7d-4b8f-aba0-b034c390b9f5.jpg)
![Screenshot_2022-08-20-18-26-09-40_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/185777880-59cc54f6-b03e-48cc-848b-34c7c3e4e54d.jpg)

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.8-alpha-091b45a188

**Comment by seanlip** [comment]
@BenHenning Confirming this is an Android platform issue and is actually quite important because we do this a lot. Can the concept card be enabled in the hints display?

**Comment by BenHenning** [comment]
So it seems like we simply never enabled concept cards in hints. Seems like an oversight that is, fortunately, trivial to fix. We simply need to:
- Update https://github.com/oppia/oppia-android/blob/6bab4820176496c1497321ef4e8c251ced40ad5a/app/src/main/java/org/oppia/android/app/hintsandsolution/HintsAndSolutionDialogFragmentPresenter.kt#L222 to set supportsConceptCards to true (per https://github.com/oppia/oppia-android/blob/091b45a1885562752f6d25da8e5494e4a331bdb4/utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt#L51)
- Update one of the test data hints to include a concept card link
- Add a new hint test to validate that the concept card reference is correctly linkified, and that the link opens the correct hint

The only issue I see is that this will result in stacked dialogs (which is a bit of a mobile antipattern), but I don't see a good alternative. This could be, perhaps, an area for improved UX in the future.
