### ISSUE TITLE
Concept card link is missing for one of the questions in fractions

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4520]
**Describe the bug**
Concept card link is missing for one of the questions in fractions

**To Reproduce**
1. Go to 'Fractions' - Fractions of a group
2. Click on 'Continue' till you reach the question "Very good! Last one to remind you about fractions!"
3. Enter the wrong answer

**Expected behavior**
'Take a look at the <link> to see what that is' should be seen

**Demonstration**
![Screenshot_2022-08-21-22-17-15-92_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/185835350-8a592a58-5704-46a1-a7f3-da2f45a9bd92.jpg)

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.8-alpha-091b45a188

**Comment by seanlip** [comment]
Thanks for reporting @KolliAnitha. This was a content issue (it was pointing to a refresher exploration ID) and has now been fixed on the website. It should be corrected in the next pull of content to the app.
