### ISSUE TITLE
Unknown indication box size is large in Problem solving Revision card in Topic division

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4521]
**Describe the bug**
Unknown indication box size is large in Problem solving Revision card in Topic division

**To Reproduce**
1. Go to 'Division'
2. Click on 'Revision' - Select Problem Solving
3. Scroll down to 'Finding unknowns in equations'

**Expected behavior**
Unknown indication box should be in same size as the other text

**Demonstration**
![Screenshot_2022-08-21-15-18-40-34_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/185839604-d5a5aef9-6803-4139-a756-341927d7cf63.jpg)

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.8-alpha-091b45a188

**Comment by seanlip** [comment]
@BenHenning Is this an Android rendering issue, or do you need the box to be changed to a different character on Web here?

**Comment by BenHenning** [comment]
@seanlip do you know if that box is a unicode symbol or LaTeX?

**Comment by seanlip** [comment]
Unicode, specifically  ⃞. Though looking at it on Web, it's not rendering correctly there as well
![Screenshot from 2022-08-21 21-47-43](https://user-images.githubusercontent.com/10575562/185841459-9f5c9d92-568c-497c-bbab-3036242ec32e.png)

I think I'm going to replace it with this one instead, let's see if that works: [▢](https://en.wikipedia.org/wiki/%E2%96%A2)

**Comment by seanlip** [comment]
(Note: The original square wasn't a square, it was the "Combining Diacritical Marks for Symbols" symbol, so it's probably no surprise it didn't render correctly. Unfortunately the standard unicode white square looks too small in the context so I opted for U+25A2 instead.)

**Comment by adhiamboperes** [comment]
This displays fine in latest beta @seanlip, cc @KolliAnitha  
![image](https://github.com/oppia/oppia-android/assets/59600948/9d36b8bd-1f42-4b2e-9256-22d983d15f01)

**Comment by seanlip** [comment]
Great! I think we can close this then, thanks @adhiamboperes.
