### ISSUE TITLE
Concept card link is not showing up in concept cards (possibly revision cards, too).

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#4522]
**Describe the bug**
Concept card links do not show up in concept cards.

**To Reproduce**
1. Go to 'Percentages'- Open What is a Percentage
2. Click on 'add', subtract

**Expected behavior**
There should be a concept card after "(i.e., changing it to its ..."). This indicates a missing concept card.

**Note**:
- This is likely related to #4519.
- Additionally, for safety, please check revision cards as well -- they should support opening concept card links too. (Given that this was missed in hints and concept cards, it seems possible that it was missed there too.)

**Demonstration**
![Screenshot_2022-08-20-21-15-21-80_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/185776261-6b4dd360-40f7-4e21-bf47-5cc381661be0.jpg)

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.8-alpha-091b45a188

**Comment by seanlip** [comment]
@BenHenning  Flagging this for Alpha MR5, though it is slightly less serious than #4519 and can be deprioritized if needed.

**Comment by BenHenning** [comment]
FWIW concept cards definitely show up from revision cards if they're present, but are broken for regular concept cards.
