### ISSUE TITLE
User icon is not seen for image while opening add profile page for the second time 

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4524]
**Describe the bug**
User icon is not seen for image while creating a profile on opening it for the second time

**To Reproduce**
1. Click on + icon to create profile
2. Enter admin pin then add profile page opens with user icon
4. Go back to the user login page and click on + icon to create profile
5. See the image icon 

**Expected behavior**
User icon should be seen instead of + icon

**Demonstration**
https://user-images.githubusercontent.com/101634267/185974348-2bb82fa5-1f27-4bed-b8e9-09ab60c46cde.mp4

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.8-alpha-091b45a188

**Comment by pratyaksh1610** [comment]
@BenHenning I would like to work on this, please assign this issue to me.
Thanks .

**Comment by BenHenning** [comment]
Done @pratyaksh1610.
