### ISSUE TITLE
The audio is taking time to play if we stopped audio in the previous page

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4544]
**Describe the bug**
The audio is taking time to play if we stopped audio in the previous page

**To Reproduce**
1. Go to 'Multiplication' - Open Parts of Multiplication Expressions
2. Click on 'Audio' symbol 
3. Click on Play - Play for sometime and then click on Continue
4. Play Audio

**Expected behavior**
Audio should start playing after clicking Continue

**Demonstration**
https://user-images.githubusercontent.com/101634267/187426789-6acffe5d-59f0-4835-a0c1-479beb93bd28.mp4

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.8-alpha-091b45a188

**Comment by BenHenning** [comment]
@KolliAnitha does it seem inconsistently slow or is it consistent (i.e. playing audio always has a delay)?

I suspect this is a side effect of always streaming and never caching audio.

**Comment by KolliAnitha** [comment]
@BenHenning, audio seems to be consistently slow across the pages in the chapter. Earlier on clicking continue the audio played instantly, but now it is taking time and as a user I am not aware of it and clicking on the play button to start the audio.

**Comment by KolliAnitha** [comment]
The Audio is working properly, there is no pause as earlier in beta version of the app

**Comment by BenHenning** [comment]
Interesting. I'm not sure why the beta changes affected this. It may be worth checking this behavior in future releases of the app, too, just to make sure that it isn't an environment issue (e.g. temporary poor network connectivity, or the like).
