### ISSUE TITLE
Improve test cases for HtmlParser and UrlImageParser

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#455]
HtmlParser and UrlImageParser code was updated to improve the UI, which needs new test cases to check these improvements.

Also, check this comment: https://github.com/oppia/oppia-android/pull/454#pullrequestreview-320146921

**Comment by manas-yu** [comment]
Hi @adhiamboperes,
I would like to work on this issue. I'll start by adding tests for the updates made in PRs #404 and #454. If there are any additional tests you'd like me to include, please let me know.
