### ISSUE TITLE
Doesn't have Dark Mode Mock for the newly implemented Text view in audio_fragment.xml.

### ISSUE THREAD

**Issue by Akshatkamboj14** [oppia/oppia-android#4561]
**Newly Implemented TextView doesn't have Dark Mode Mock in the audio_fragment.xml.**

**To Reproduce**
1. Go to `audio_fragment.xml`
2. Scroll down to Bottom, there you will find the newly implemented TextView.

![image](https://user-images.githubusercontent.com/92685493/188682379-ac6ff6ce-9718-4ed9-8496-8d0a02d39048.png)

**Comment by iampradeep-hr** [comment]
can i work on this feature ?

**Comment by BenHenning** [comment]
This seems to be available to work on @iampradeep-hr if you're still interested (given that you asked on other issue threads--you should start with one issue rather than multiple).

**Comment by iampradeep-hr** [comment]
Ok Thanks, I would take this issue up.
