### ISSUE TITLE
The home screen is blank on opening beta app

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4579]
**Describe the bug**
The home screen is blank on opening beta app

**To Reproduce**
1. Go to 'Playstore'
2. Install Oppia
3. Open Oppia app

**Expected behavior**
Home page should open with Explorations

**Demonstration**
![Screenshot_2022-09-10-10-14-59-71_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/189469317-fa198c4a-8e8d-41dd-9c4d-6ad0e755e046.jpg)

**Environment**
Mobile: One Plus Nord2 5G
Android Version: 11
App Version: 0.9-beta-3f935261e0

**Comment by BenHenning** [comment]
I'm aware of this issue, and beta users shouldn't hit it unless they're upgrading from alpha (which I don't think we're expecting anyone to, but this is a good FYI @isalooo).

This will happen if you have saved progress for the one topic we had to drop from the release (Multiplication), so it's more likely to affect you @KolliAnitha. You can work around it by either clear data for the app, or by adding a new profile.

Please let me know if you still run into the issue even with those workarounds as that would be unexpected.

Also, this is worth keeping open and maybe hotfixing if we're worried about the alpha->beta upgrade flow.

**Comment by dika1osune** [comment]
Experienced the same issue but only on admin profile. I was upgrading from alpha. The other user displays all 5 Topics

**Comment by BenHenning** [comment]
Thanks @dika1osune.

It looks per another issue that was filed that we may need to release another version of MR1, so I'll take this to see if I can opportunistically fix it.

**Comment by BenHenning** [comment]
Hmm I am actually unable to repro this issue locally, so now I'm wondering if I was wrong about the root cause here.

**Comment by BenHenning** [comment]
Aha, this is a more specific situation than I expected. One needs to have progress in a topic that was switched from a fully available topic to an upcoming one. I suspect that's because we make certain assumptions when a topic exists and there's progress for that topic which, in light of the possibility of "unpublishing" a topic, is probably wrong.

**Comment by KolliAnitha** [comment]
Working fine in the latest beta build 0.10-beta-5e64fae55e
