### ISSUE TITLE
Privacy policy hyperlink is not opening in Terms of Service

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4581]
**Describe the bug**
Privacy policy hyperlink is not opening in Terms of Service

**To Reproduce**
1. Install Oppia and Open it
2. Click on Next to get to the last page where Terms of Service link is present
3. Click on Terms of Service
4. Scroll down and click on Privacy policy link

**Expected behavior**
On clicking Privacy policy link it should open the privacy policy

**Demonstration**

https://user-images.githubusercontent.com/101634267/189470966-82a2fa66-9f53-4417-b041-e6226e845edb.mp4

**Environment**
Mobile: One Plus Nord2 5G
Android Version: 11
App Version: 0.9-beta-3f935261e0

**Comment by pratyaksh1610** [comment]
@KolliAnitha It should open the web page of privacy policy on the web or the privacy policy page which is in the app itself ?

**Comment by BenHenning** [comment]
Thanks @KolliAnitha, this is a good catch.

The link in this case should open in the app.

@veena14cs this looks like a bug with your recent PR--can you PTAL?

**Comment by KolliAnitha** [comment]
Working fine in 0.10-beta-5e64fae55e
