### ISSUE TITLE
Deprecated protobuf version

### ISSUE THREAD

**Issue by Smarshal21** [oppia/oppia-android#4583]
**Describe the bug**
Could not resolve all files for configuration ":model:protobufToolsLocator_protoc'

**To Reproduce**

1. Go to the oppia android repository 
2. Clone the project to your system 
3. Try Running the app on your physical device/emulator

**Expected behavior**
The app should run perfectly with the updated protobuf version 

**Demonstration**
<img width="1440" alt="Screenshot 2022-08-29 at 3 53 12 PM" src="https://user-images.githubusercontent.com/99678760/189494265-9c091918-57b8-4f0f-92f6-de9ce01eaa13.png">

<img width="1440" alt="Screenshot 2022-08-29 at 3 53 20 PM" src="https://user-images.githubusercontent.com/99678760/189494263-a6fbaa8b-f7c5-40ca-bf41-995aa2d4a904.png">

**Environment**
- Device/emulator being used: Pixel 5 API 33
- Android or SDK version (e.g. Android 5 or SDK 21): 11
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.9-beta-3f935261e0

**Comment by Smarshal21** [comment]
Hi @BenHenning,

I have found the solution of this bug for mac m1 chip.
Basically it's like for the older versions of the protobuf there is no executable jars for the mac m1 arm architecture so we need to update the protobuf version for the project so that we can also support arm based architecture chips.

Shall I make a Pull Request for this issue or do you like to further discuss about the solutions for this issue.

Thanks,
Samanwith

**Comment by BenHenning** [comment]
> Hi @BenHenning,
> 
> I have found the solution of this bug for mac m1 chip. Basically it's like for the older versions of the protobuf there is no executable jars for the mac m1 arm architecture so we need to update the protobuf version for the project so that we can also support arm based architecture chips.
> 
> Shall I make a Pull Request for this issue or do you like to further discuss about the solutions for this issue.
> 
> Thanks, Samanwith

Nice find @Samanwith21. Sure, we can try to update protoc, though it may cause issues with the Gradle build since that protoc setup has historically been finicky when we change versions.

**Comment by Smarshal21** [comment]
@BenHenning  
i have tried updating the protobuf and the app is running fine,
shall i create a PR depicting the solution ???

**Comment by BenHenning** [comment]
> @BenHenning i have tried updating the protobuf and the app is running fine, shall i create a PR depicting the solution ???

Yep @Samanwith21. CI will help indicate if everything is working as expected (particularly since we use both Gradle and Bazel for building, and both will need to be updated to move off of the old protoc version).

**Comment by Smarshal21** [comment]
@BenHenning can i get the access to push the changes into a new branch ?

**Comment by seanlip** [comment]
You can make a PR the standard way. See instructions [here](https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android).

**Comment by adhiamboperes** [comment]
This was fixed in https://github.com/oppia/oppia-android/pull/4675
