### ISSUE TITLE
On logging in for the first time, Recommended stories are not displayed in the home page

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4588]
**Describe the bug**
On logging in for the first time, Recommended stories are not displayed in the home page

**To Reproduce**
1. Install Oppia and open it
2. Login as Admin and create a profile
3. In the Home page under Good morning, <user name> verify that Recommended story is displayed

**Expected behavior**
As earlier Recommended story section with Place values as default topic should be displayed

**Demonstration**
![Screenshot_2022-09-12-10-17-41-78_943a62cb4c6fb83e010e1c2e82766a17](https://user-images.githubusercontent.com/101634267/189576107-1b302e7c-f5ab-4bb3-93d4-14228b46394c.jpg)

**Environment**
Mobile: One Plus Nord2 5G
Android Version: 11
App Version: 0.9-beta-3f935261e0

Note: In Alpha version, Recommended stories with Place Value is displayed under the greeting message and above Select a Topic to Start

**Comment by BenHenning** [comment]
This is the new, expected behavior so we can update the corresponding test case. Recommended stories only appear after the first visit by a profile (so they should show up in all subsequent visits).
