### ISSUE TITLE
Select a Topic to Start is seen instead of All Stories in the Home page

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4589]
**Describe the bug**
Select a Topic to Start is seen instead of All Stories in the Home page

**To Reproduce**
1. Go to 'Oppia'
2. Login as Admin
3. Scroll down to 'Select a Topic to start'

**Expected behavior**
All Topics must be displayed 

**Demonstration**
![Screenshot_2022-09-12-10-17-41-78_943a62cb4c6fb83e010e1c2e82766a17](https://user-images.githubusercontent.com/101634267/189587470-0290c556-cfbc-421c-a82f-9425f99c82be.jpg)

**Environment**
Mobile: One Plus Nord2 5G
Android Version: 11
App Version: 0.9-beta-3f935261e0

**Comment by BenHenning** [comment]
This is the new behavior, so we can update the corresponding test case. "Select a Topic to Start" is the new header to replace the old "All Topics" wording.
