### ISSUE TITLE
Doesn't have dark mode mock for promoted story cards

### ISSUE THREAD

**Issue by bhaktideshmukh** [oppia/oppia-android#4600]
Need to add dark mode mock for `Promoted Story Cards`.

**To reproduce**
Once logged in, home activity comes under view and promoted story cards.

**Comment by rt4914** [comment]
This can be solved in a bit different way.

Although we don't have mocks for the promoted cards item but we can still implement the dark-mode designs based on how it has been implemented in other screens.

[Promoted Story Cards - Light Mode](https://xd.adobe.com/view/3dca36c2-5115-419c-b25e-0f10526b077c-6899/screen/eabb7da8-e5e5-418d-b3d9-d59ae0b5f585/specs/) designs are similar to that of [Stories Completed](https://xd.adobe.com/view/3dca36c2-5115-419c-b25e-0f10526b077c-6899/screen/f54ae7d1-9530-44d6-8783-21559b13635c/specs/) or [Recently Played](https://xd.adobe.com/view/3dca36c2-5115-419c-b25e-0f10526b077c-6899/screen/2b6c8e95-5ac7-4472-bc2b-1c318a3f7e5c/). In these cases all of these are stories (not topics) and there designs are somewhat similar. 

Also, we do have designs for [Completed Stories - Dark Mode](https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/f54ae7d1-9530-44d6-8783-21559b13635c/specs/) and [Recently Played Stories](https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/2b6c8e95-5ac7-4472-bc2b-1c318a3f7e5c/specs/)

Therefore by using the theme of above two dark-mode screens we can implement Promoted Stories too.

**Comment by MohitGupta121** [comment]
> 

Okay we take reference from these mockup to solve this issue. Thanks You @rt4914
