### ISSUE TITLE
Develop branch is broken

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4602]
**Describe the bug**
Two PRs were merged in succession that led to develop breaking, despite no conflicts.

**To Reproduce**
See develop branch.

**Expected behavior**
Develop shouldn't be broken.

**Demonstration**
N/A

**Environment**
N/A

**Additional context**
N/A

**Comment by KevinGitonga** [comment]
@BenHenning Had updated my branch and came across this error that might be causing the breakage https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/values/color_defs.xml 
<color name="color_def_bright_green">#009C8A</color> has two entries causing error during build

**Comment by seanlip** [comment]
Great catch, @KevinGitonga -- thanks! 

@JishnuGoyal @Akshatkamboj14 Per the blame file, it looks like this relates to both your PRs colliding: https://github.com/oppia/oppia-android/blame/develop/app/src/main/res/values/color_defs.xml. Would one of you be able to fix it, please?

**Comment by BenHenning** [comment]
This was fixed in #4603.
