### ISSUE TITLE
[Developer Video] How to use an Accessibility Scanner?

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#4607]
We should create a youtube video for `How to use an Accessibility Scanner?` so that contributors can easily follow the video for better understanding.

- [ ] Create a script for the video @MohitGupta121 
- [ ] Create slides for the video @MohitGupta121 
- [ ] Review/edit script and slides - Ben
- [ ] Record the video

Reference:
- https://dev.to/rajatt/accessibility-scanner-in-android-4mb1

**Comment by rt4914** [comment]
@adhiamboperes I have added few references to the issue description. Feel free to use them if you need to. Thanks.

**Comment by MohitGupta121** [comment]
@rt4914 Sorry, but you already made video for [Accessibility](https://youtu.be/wjI9UWB5NcY) and [TalkBack](https://youtu.be/1fMGURSVp0g) that is prefect is that not works here?

**Comment by MohitGupta121** [comment]
@rt4914 we not use your videos tutorials video for [Accessibility](https://youtu.be/wjI9UWB5NcY) and [TalkBack](https://youtu.be/1fMGURSVp0g) as I think that's prefect. I also learned from your videos.

Sorry, But I not sure what this "Script for video" means? Can you please brief which type of script? And what is the need of script as that video is created manually?

**Comment by seanlip** [comment]
@MohitGupta121 I think it's just preparation for the video, i.e. an outline of what you want to say in it. This is just personal prep and it may be fine not to do it, as long as the final delivery in the video is coherent and understandable by others. Hope that helps!

**Comment by MohitGupta121** [comment]
@seanlip Thanks, understand means we need script (outline) or content that what we say in whole video guide which along with PPT which finally officially Publish in Oppia-Developers YouTube channel. So that the video is completely dedicated to oppia-android? Am I understand Right?

**Comment by seanlip** [comment]
This particular video is Oppia Android specific. The YouTube channel you mention is for Oppia Web + Android.

**Comment by MohitGupta121** [comment]
So where the video goes @seanlip? or We can make separate playlist for oppia-android in that channel.

**Comment by seanlip** [comment]
You can host it on the Oppia Developers youtube channel and link to the specific playlist / video on the wiki.
