### ISSUE TITLE
[Developer Video] How to enable RTL and check for issues in the app?

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#4609]
We should create a youtube video for `How to enable RTL and check for issues in the app?` so that contributors can easily follow the video for better understanding.

**Comment by adhiamboperes** [comment]
@MohitGupta121, maybe add a comment here explaining why we didn't create a video for this?

**Comment by MohitGupta121** [comment]
We've included instructions in the wiki on how to enable Right-to-Left (RTL) in two different ways. Additionally, there's a quick screen recording demonstrating the process for both methods. Given the comprehensive coverage in the wiki, I believe a full YouTube video isn't necessary for this minor task. Thanks!
