### ISSUE TITLE
[A11YS] Increase color contrast ratio between foreground and background in thumbnail image

### ISSUE THREAD

**Issue by vrajdesai78** [oppia/oppia-android#4614]
**Describe the bug**
In accessibility scanner, it is suggesting to improve color contrast ratio between foreground and background in thumbnail image

**Expected behavior**
Accessibility scanner should not show any improvements. 

**Demonstration**
<img src="https://user-images.githubusercontent.com/43074241/191743827-c2798515-fc3e-437d-ae06-4e492b97454a.png" width="250" />  <img src="https://user-images.githubusercontent.com/43074241/191743849-77be9e84-90ba-4347-885a-827068308645.png" width="250" />

**Environment**
- Device used: Realme GT Master Edition
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version: 1.0.0

**Comment by BenHenning** [comment]
Hmm. Why is this even being triggered? It seems to be inconsistent in which thumbnails are actually triggering the scanner. Is this a case where the scanner is reading a foreground or background color that's not actually being used?

**Comment by BenHenning** [comment]
Also @pratyaksh1610 is working on this.

**Comment by vrajdesai78** [comment]
> Hmm. Why is this even being triggered? It seems to be inconsistent in which thumbnails are actually triggering the scanner. Is this a case where the scanner is reading a foreground or background color that's not actually being used?

@BenHenning even I don't know why scanner is triggering this may be because we have created our own thumbnail with xml instead of getting it as a image from backend.

**Comment by BenHenning** [comment]
> > Hmm. Why is this even being triggered? It seems to be inconsistent in which thumbnails are actually triggering the scanner. Is this a case where the scanner is reading a foreground or background color that's not actually being used?
> 
> @BenHenning even I don't know why scanner is triggering this may be because we have created our own thumbnail with xml instead of getting it as a image from backend.

@vrajdesai78 that describes the environment, but not why that environment causes the issue. I think whoever works on this will need to figure out why it's happening before we can introduce a sensible fix.

**Comment by adhiamboperes** [comment]
@aayushimathur6, could you please perform a check and confirm whether this issue is still present?

**Comment by aayushimathur6** [comment]
> @aayushimathur6, could you please perform a check and confirm whether this issue is still present?

@adhiamboperes sure, I'll let you know by tomorrow

**Comment by aayushimathur6** [comment]
@adhiamboperes, The Accessibility scanner still shows the suggestions, I think this issue is open. I am attaching the screenshot you can have a look.

![before1](https://github.com/oppia/oppia-android/assets/92685651/cf2f1f96-c2d0-437f-b280-f7d6a012c5f6)


![after1](https://github.com/oppia/oppia-android/assets/92685651/37184b6d-4f64-4914-9f8e-de8a5c9267ee)

![after2](https://github.com/oppia/oppia-android/assets/92685651/26d12c51-e341-41fd-b13c-d7f689908ad0)

**Comment by aayushimathur6** [comment]
> @aayushimathur6, could you please perform a check and confirm whether this issue is still present?

**It is still showing the suggestions, I performed you can have a look** 

![a11y](https://github.com/oppia/oppia-android/assets/92685651/4cdc4326-69a2-4ce1-9f29-a1d30c16b051)

**Comment by aayushimathur6** [comment]
**A more detailed view of the suggestions**  
                                                                                                                                       
 ![a111y](https://github.com/oppia/oppia-android/assets/92685651/d18854fb-34e0-47bf-bea9-37b68e9f0958)

**Comment by aayushimathur6** [comment]
@adhiamboperes PTAL

**Comment by adhiamboperes** [comment]
Thanks for verifying this @aayushimathur6!

**Comment by suyashshenoi** [comment]
Hey, pls assign this issue to me. I have already changed to code to make the necessary fix. Will create the PR as soon as I'm assigned.

**Comment by adhiamboperes** [comment]
> Hey, pls assign this issue to me. I have already changed to code to make the necessary fix. Will create the PR as soon as I'm assigned.

Please create the PR and link it to the issue. Thanks.

**Comment by suyashshenoi** [comment]
@adhiamboperes created the PR and have linked it to this issue. Pls, go through it. Thanks.
