### ISSUE TITLE
Migrate Android wiki to store source files in oppia-android repository

### ISSUE THREAD

**Issue by U8NWXD** [oppia/oppia-android#4622]

**Comment by U8NWXD** [comment]
@BenHenning I don't have permission to edit the assignees of this issue. Since it's being handled by the welfare team, which spans the oppia-web and oppia-android projects, could you give me triage access so I can manage issues in oppia-android that are being handled by the welfare team?

**Comment by BenHenning** [comment]
Apologies @U8NWXD I forgot to do that after our meeting--it should be done now. Please let me know if you run into any problems, though.
