### ISSUE TITLE
Add dark mode support to Lesson Tab

### ISSUE THREAD

**Issue by MohitGupta121** [oppia/oppia-android#4624]
Add dark mode support to Lesson Tab.

**This issue is part of #4177 but Blocked due to the new design of Lesson Tab and the Dark mode mockups for Lesson Tab are not prepared yet.**

Go through this [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode) to get started.

Location in the app

1. Open the app
2. Go to All Topics
3. Open any topic
4. Go to Lesson Tab

**Comment by chetanmuliya** [comment]
can you assign me this task?

**Comment by MohitGupta121** [comment]
@chetanmuliya actually this issue is blocked due to dark mode mockups, which is not prepared yet.

**Comment by chetanmuliya** [comment]
okay

**Comment by MohitGupta121** [comment]
https://xd.adobe.com/view/3dca36c2-5115-419c-b25e-0f10526b077c-6899/screen/558af437-bec4-4719-8d30-291da10bbc9d/specs/

Please provide colors for Dark Mode for above mockup. So that to complete this issue as I block on this issue as dark mode mockup for these new design are not present. 

If you provide respective colors for these it's very helpful to complete this issue.
