### ISSUE TITLE
[A11YS] Improve Text scaling of Marquee text in toolbar title 

### ISSUE THREAD

**Issue by vrajdesai78** [oppia/oppia-android#4640]
**Describe the bug**
Accessibility scanner is showing suggestion to improve text scaling of Marquee text i.e. toolbar title as it has fixed width and scalable text. Here, Marquee library is creating issue as, marquee library is changing the width of text. This [line](https://github.com/ened/Android-MarqueeView/blob/master/library/src/main/java/asia/ivity/android/marqueeview/MarqueeView.java#L335) in MarqueeView.java file is changing width of textView. 

**To Reproduce**
1. Go to 'Topic Activity'
2. Take a snapshot in accessbility scanner

**Expected behavior**
Accessibility scanner should not suggest any improvements related to text scaling. 

**Screenshot of A11YS showing suggestion**
![image](https://user-images.githubusercontent.com/43074241/194386874-a12c32e0-1738-4008-a29f-b1d239aca55a.png)

**Environment**
- Device being used: Realme GT Master Edition
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0 

**Additional context**
Marquee text is introduced in PR #4392

**Comment by KevinGitonga** [comment]
@vrajdesai78 not able to reproduce this on my devices. Getting no suggestions in regards to this issue. I am not sure if this accessibility scanner suggestions may be specific to your device specs. This is on my Google pixel 3XL and Samsung galaxy s9 plus. @BenHenning any thought on this.

| Image           |  scanner results |
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/20886444/194519691-4fb70a63-6255-4f84-bc73-bc845c2ec049.jpeg" width="300"/> | <img src="https://user-images.githubusercontent.com/20886444/194519631-911d3146-6f20-4d37-8c57-e17a0fea3a2e.jpeg" width="300"/> 

<img src="https://user-images.githubusercontent.com/20886444/194519774-d73e98d4-f017-4ab0-aae1-b37e1bfc3afa.png" width="300"/> | <img src="https://user-images.githubusercontent.com/20886444/194519749-84260607-2a84-4463-b968-89b7e696af08.png" width="300"/>

**Comment by vrajdesai78** [comment]
@KevinGitonga What is your Android version. I have checked on Android 12

**Comment by KevinGitonga** [comment]
@vrajdesai78 i have checked on both Android 10 and 12.

**Comment by BenHenning** [comment]
What versions of the a11y scanner are you both using @vrajdesai78 and @KevinGitonga? Perhaps there's a difference in the scanner itself.

**Comment by vrajdesai78** [comment]
> What versions of the a11y scanner are you both using @vrajdesai78 and @KevinGitonga? Perhaps there's a difference in the scanner itself.

I am using the latest version of Accessibility Scanner

![Screenshot_2022-10-11-08-16-49-36_f7aa348215f5d566f9e4ca860f474209.jpg](https://user-images.githubusercontent.com/43074241/194985668-4bbcffcd-d41c-414b-affa-88c83a0ac8fc.jpg)

**Comment by KevinGitonga** [comment]
Using the latest version of Accessibility scanner on my devices. 

| Pixel 3xl            |  Samsung galaxy s9 plus |
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/20886444/195024027-a5e09d5a-39d5-4f53-a4a9-79333db3cbcc.png" width="300"/> | <img src="https://user-images.githubusercontent.com/20886444/195024085-716d23d2-3dd8-464a-aa44-52c95d8daaba.jpeg" width="300"/>

**Comment by BenHenning** [comment]
Interesting. @vrajdesai78 are you able to repro the issue only on a real device, or also on an emulator? I wonder whether we can find a way to isolate the problem to an environment both of you can see it on. Though, at this point, I also really want to understand where the discrepancy is coming in.

**Comment by vrajdesai78** [comment]
Sorry for the late response @BenHenning, I have checked in emulator (Pixel 2) with Android 12 and it's showing a suggestion to improve text scaling. For reference you can check out the below screenshot which I have taken from emulator. 

I have also checked on Emulator with Android 9 and in that accessibility scanner is not showing any improvement, so I guess this issue is specific to Android 12 devices. 

![image](https://user-images.githubusercontent.com/43074241/196422254-3b91e8ea-f4ba-4296-8c29-3c90ee083413.png)

**Comment by BenHenning** [comment]
Thanks @vrajdesai78.

@KevinGitonga can you confirm that you also see this warning on Android 12 with the latest version of Talkback?

**Comment by BenHenning** [comment]
Ah, actually I just realized that Kevin has already tried with Android 12. @KevinGitonga and @vrajdesai78 could you chat to figure out what the difference is between your two Android 12 devices? I think we need to further isolate to understand what specifically is different.

**Comment by KevinGitonga** [comment]
@BenHenning @vrajdesai78 I am now able to reproduce this on my Android 12 device for Android 9 still not able even after using .apk from the related branch directly.

![Screenshot (Oct 19, 2022 11_51_18)](https://user-images.githubusercontent.com/20886444/196644758-dfaa2aed-d7c6-4276-9bf9-b3ff5fc2e32f.png)

**Comment by KevinGitonga** [comment]
@BenHenning this Android 12 accessibility issue still comes to play even after changing the width parameters to MATCH_PARENT on the library itself.

**Comment by BenHenning** [comment]
Ah, really glad to hear you can repro it now @KevinGitonga.

@vrajdesai78 do you have a suggestion for how @KevinGitonga can fix this per his comment above?

**Comment by BenHenning** [comment]
I think this is obsolete since we ended up reverting the custom marquee library that was used.
