### ISSUE TITLE
Terms of Use needs updating

### ISSUE THREAD

**Issue by partha-basu** [oppia/oppia-android#4641]
**Describe the bug**
The Terms of Use need to be updated.
I assume the same Terms are applicable for android app as well.

**To Reproduce**
Navigate to https://www.oppia.org/terms

**Expected behavior**
The terms shouldn't disallow children from using the app/site

**Demonstration**
_IF YOU DO NOT AGREE TO THE TERMS, OR IF YOU ARE UNDER THE AGE OF 13 YEARS OLD AND DO NOT HAVE THE APPROVAL OF A LEGAL PARENT OR GUARDIAN, YOU MUST NOT REGISTER FOR OR ACCESS THIS WEBSITE._

**Environment**
-N/A

**Comment by BenHenning** [comment]
I think the solution here is just to strike that phrasing from the app TOS. @seanlip do you have any concerns with that?

**Comment by seanlip** [comment]
Discussed this with Ben and he'll update the app terms. Thanks!

**Comment by KolliAnitha** [comment]
Terms of service content updated in 0.10-beta-5e64fae55e. refer below screenshot.
![terms of service](https://user-images.githubusercontent.com/101634267/201586810-43b65fbe-01c0-47ff-805d-529f94949eac.jpg)
