### ISSUE TITLE
Does not build with the default setup on M1.

### ISSUE THREAD

**Issue by antonmagnus** [oppia/oppia-android#4644]
The project does not build with the default setup.
Running macOS Monterey 12.1 M1 building for pixel3a API 29

Following the setup for mac [here](https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android)
Install oppia-android and Run the app from Android Studio.

`Execution failed for task ':model:generateProto'.
> Could not resolve all files for configuration ':model:protobufToolsLocator_protoc'.
   > Could not find protoc-3.8.0-osx-aarch_64.exe (com.google.protobuf:protoc:3.8.0).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.8.0/protoc-3.8.0-osx-aarch_64.exe`

Expected to build without issue.

The issue seems like the same one mentioned here #3912 
It was fixed by adding the proto platform to local.properties using the setup script (mentioned here #3943)

In the build Gradle model file the variable is fetched from root project variables and not from the local.properties.
I solved the issue by correcting this. It still remains to be tested on other environments.

**Comment by BenHenning** [comment]
Thanks @antonmagnus for the context, and the notes on remediation. This should be straightforward for someone to address.

**Comment by antonmagnus** [comment]
@BenHenning I have a fix now! Just gonna make a PR and have it tested on different OS
