### ISSUE TITLE
"Continue Studying" texts keeps showing even when there is no next revision card

### ISSUE THREAD

**Issue by JishnuGoyal** [oppia/oppia-android#4645]
In the revision card fragment, the continue button header is shown even when there is no next/previous revision navigation card.

**Comment by AbhaySota** [comment]
Please assign this to me. I think I can solve this.
@JishnuGoyal

**Comment by BenHenning** [comment]
Thanks for your interest @AbhaySota. This issue is already assigned to @JishnuGoyal so you should pick another issue that's not yet assigned from among our starter issues.
