### ISSUE TITLE
Add navigation buttons at the end onboarding screen

### ISSUE THREAD

**Issue by vrajdesai78** [oppia/oppia-android#4647]
**Describe the bug**
In the last screen of onboarding screen (where we have to click Get Started), there should be navigation buttons. 

**To Reproduce**
1. Go to 'Start App from fresh (If app is already installed clear data)'
2. Navigate to the end screen of Onboarding

**Expected behavior**
In the end screen of onboarding screen we should have navigation button to go back and ahead. 

**Demonstration**
![image](https://user-images.githubusercontent.com/43074241/195399126-2741a9c4-32da-4313-99c1-549731c43603.png)

**Comment by mahmood199** [comment]
Hi @vrajdesai78 
Can i pick up this issue?

**Comment by mahmood199** [comment]
My concern is that when user is on the second last screen but both skip and arrow button will redirect to last onboarding screen.
But what should be the icon and message that we need to show if the user is on the last screen?

**Comment by mahmood199** [comment]
Wouldn;t it be nice if we show left and right navigation and skip button below the dots indicator?
Left right can be used for navigating across onboarding screens and skip would just redirect to last screen where right button will be hidden but left button will be visible

**Comment by BenHenning** [comment]
Apologies for the delayed response.

You bring up good points @mahmood199. This may require some consulting with our design team. That being said, would you be willing to create a simple mock demonstrating what you're thinking? Seeing an actual visual can better help explain one's ideas, and it generally leads to more productive discussion when trying to determine what solution to go with.

**Comment by Akshatkamboj14** [comment]
Hey, @mahmood199 are you working on it? If yes please let me know I'll assign it to you.

**Comment by mahmood199** [comment]
Yess Akshat
You can assign it on me. I will inform here regarding my research on the
same.

**Comment by adhiamboperes** [comment]
This is also a candidate for closing.

**Comment by seanlip** [comment]
I agree that we can close this since the onboarding experience is being redesigned.
