### ISSUE TITLE
Change option name for "Default Audio" to "Preferred Audio Language"

### ISSUE THREAD

**Issue by vrajdesai78** [oppia/oppia-android#4649]
**Describe the bug**
Change the "Default audio" text in the Options menu to be clearer.

**To Reproduce**
1. Open exploration player
2. Click on Options

**Expected behavior**
The "default audio" text should be changed to "Preferred Audio Language".

**Current Screen**
![image](https://user-images.githubusercontent.com/43074241/200877586-0fd49422-5f3c-47d5-902f-78d3a6d25922.png)

[Note: This was edited by @seanlip from the original content description based on https://github.com/oppia/oppia-android/issues/4649#issuecomment-1731676351]

**Comment by rt4914** [comment]
@vrajdesai78 not part of GSoC

**Comment by geektan123** [comment]
Assign#4649

**Comment by adhiamboperes** [comment]
@BenHenning do we still need to work on this given the proposed changes in the revised onboarding flow?

**Comment by seanlip** [comment]
From the PM side: I think it is worth making this menu clearer regardless of the onboarding flow. I think "Reading Text Size" is fine but "Default Audio" is unclear. Could we change it to "Preferred Audio Language" instead?

**Comment by adhiamboperes** [comment]
I am fine with rewording to `Preferred Audio Language`

**Comment by seanlip** [comment]
Thanks @adhiamboperes -- updated the title and description of the issue accordingly. This should be a pretty good starter issue, I think!

**Comment by adhiamboperes** [comment]
Sure, @geektan123, if you'd like to attempt to fix this, please let me have a description of your proposed solution.

**Comment by theMr17** [comment]
Hi @adhiamboperes, I would like to work on this issue. I will fix this by changing the `audio_language` string in `strings.xml` file to `Preferred Audio Language`. Also, the string needs to be changed in other translations as well.

According to me, the toolbar title also needs to be changed accordingly.

<img src="https://github.com/oppia/oppia-android/assets/84731134/7ee209b4-e123-4825-9865-0831862a297a" width="300"/>

**Comment by adhiamboperes** [comment]
@the-mr17, you only need to update the text in the english strings file. @translatewiki will update any translations. Otherwise the approach sg.

**Comment by adhiamboperes** [comment]
@the-mr17 I had assigned https://github.com/oppia/oppia-android/issues/5079 to you. If you won't be working on it please let me know.

**Comment by theMr17** [comment]
> @the-mr17 I had assigned #5079 to you. If you won't be working on it please let me know.

@adhiamboperes My apologies for the delay. I have just added a [PR](https://github.com/oppia/oppia-android/pull/5162) addressing that [issue](https://github.com/oppia/oppia-android/issues/5079). PTAL.
