### ISSUE TITLE
Focus is lost on double clicking toggle switch 

### ISSUE THREAD

**Issue by vrajdesai78** [oppia/oppia-android#4650]
**Describe the bug**
When we double-click on the "download and update only on Wifi" toggle switch it is losing focus of talkback reader

**To Reproduce**
1. Go to 'Administrator Controls'.
2. Turn on the Talkback reader.
3. Double-click on the "Download and update only on Wifi" toggle switch.

**Expected behavior**
The toggle switch should not lose focus on double-clicking it, focus should remain on the toggle even after double-clicking it. 

**Demonstration**
https://user-images.githubusercontent.com/43074241/195432204-129d6086-08be-4b82-a684-e3a74b8f4c04.mp4

**Environment**
- Device/emulator being used: Realme GT Master Edition
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0

**Comment by rt4914** [comment]
I have tested it on latest develop branch and it has been fixed.
1. We don't show these download related options currently but we can enabled them from [here](https://github.com/oppia/oppia-android/blob/ac4eb44b29103f07b4d2b35f3dbf5859becbf386/utility/src/main/java/org/oppia/android/util/platformparameter/PlatformParameterConstants.kt#L20).
2. Earlier we were focusing only on the switch to toggle but now we are focusing on entire item to toggle and that's where the problem has been fixed. 
3. We can switch between ON/OFF multiple times and the screen-reader will not loose focus.


Closing this issue as it has been fixed.
