### ISSUE TITLE
Error in answers blocking learners' progress during lessons

### ISSUE THREAD

**Issue by Chidindu06F** [oppia/oppia-android#4657]
**Describe the bug**
Some of the answers provided by the app are wrong. So even even when a user provides a right answer, the app marks it wrong thereby blocking the progress of the user.

**To Reproduce**
1. Go to 'Home screen'
2. Click on 'Ratio and proportional reasoning'
3. Click on the 'Lesson' tab
4. Click on the lesson card
5. Select Chapter 1
6. Progress through the lesson
7. See error.

**Expected behavior**
The app keeps marking the user wrong.

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.

**Environment**
![Oppia lesson- Ratio](https://user-images.githubusercontent.com/115376874/196030625-16408492-ff61-44e4-9946-e81c4d1854b4.jpeg)
![Oppia lesson- Ratio 2](https://user-images.githubusercontent.com/115376874/196030639-05db17ec-9bb9-4881-a45f-9273341743ef.jpeg)
![Oppia lesson- Ratio 3](https://user-images.githubusercontent.com/115376874/196030652-9e37f135-198e-46f5-b182-ec2a05dbaa89.jpeg)

- Device/emulator being used: <device version/emulator>
- Android or SDK version (e.g. Android 5 or SDK 21): <Android version 7.6.0>
- App version (you can get this through system app settings or via the admin controls menu in-app): <0.9-beta-3f035261e0>

**Additional context**

**Comment by seanlip** [comment]
Hi @Chidindu06F, I think this needs a bit more clarification. Could you please show the full question that is getting a wrong answer, and explain why the answer 3:2:1:2 is correct? Thanks.

**Comment by Chidindu06F** [comment]
> Hi @Chidindu06F, I think this needs a bit more clarification. Could you please show the full question that is getting a wrong answer, and explain why the answer 3:2:1:2 is correct? Thanks.

Hi @seanlip, The question says "What will be ratio of milk to blueberry puree to strawberry puree to mango puree be?"
From the image, milk=3, blueberry=2, strawberry=1, mango=2
So the answer is 3:2:1:2

**Comment by seanlip** [comment]
For the question in which you are answering 3:2:1:2, could you please provide a screenshot of the whole question? It is cut off at the top.

The image seems to be for the previous question.

**Comment by Chidindu06F** [comment]
Hi Sean Lip,

I have gone back to replay the lesson and I just realized that the question
isn't related to the image in the previous question. I'm sorry about that. I
will be more careful next time.

Thanks.

**Comment by seanlip** [comment]
That's fine. Thanks for confirming. I'm closing this issue as invalid, then.
