### ISSUE TITLE
Hints screen content contrast is low

### ISSUE THREAD

**Issue by Ronnie-Mercy** [oppia/oppia-android#4659]
The hints page content contrast is low so words are not easy to read

Go to the home page on the Oppia app, click on place values lesson, scroll to pick a chapter, start the lesson, during the lesson, click on the "hints tab" below, and see low contrast issues with content.

Contents are supposed to be very visible with a contrast of PassMark 5:0 so kids can easily read the contents and continue with the lessons

![image](https://user-images.githubusercontent.com/115509229/196119393-d1f2fc99-df19-4b83-b86a-12601363d937.png)

This is a mockup I came up with to explain what I mean by contrast issues. I also added a few icons to help the kids understand directions when using a button.

**Comment by BenHenning** [comment]
Thanks @Ronnie-Mercy. I suspect that this is an artifact from us recently changing the hint screen & being mid-migration for dark mode.

@rt4914 could you confirm?

**Comment by Ronnie-Mercy** [comment]
@BenHenning I figured it while conducting a user test study and I decided to further the contribution with an idea. I hope this helps!

**Comment by MohitGupta121** [comment]
@rt4914 is this issue is same as #4671 ?

**Comment by rt4914** [comment]
Fixed in https://github.com/oppia/oppia-android/pull/4779
