### ISSUE TITLE
Hint screen contrast should be improved

### ISSUE THREAD

**Issue by Adefeyisayo** [oppia/oppia-android#4671]
**Describe the bug**
The contrast of the text and background color on the hint screen prevented the learner from having the best experience.

**To Reproduce**
1. Go to "Home, "select a topic to start"
2. Click on "Place Values"
3. Start a lesson "Chapter 2"
4. To see error "Click on the hint icon"

**Expected behavior**
The contrast of the text and background color on the hint screen prevented the learner from having the best experience which shouldn't be. The texts should be more readable.

**Demonstration**
![image](https://user-images.githubusercontent.com/105318377/202919487-7f994f34-dd0c-4d22-9c9f-56d016644156.png)

**Environment**
-Device Used: Android
-App version: 0.9-beta-3f935261e0

**Comment by BenHenning** [comment]
@Adefeyisayo could you perhaps update your main comment to follow our normal bug issue template & full fill it out? Without that, it's hard to actually triage and work on this issue.

**Comment by Adefeyisayo** [comment]
Hi Ben, sorry for my late response. The issue has been updated.

**Comment by BenHenning** [comment]
Thanks @Adefeyisayo!

This is definitely a dark mode issue, moving to the correct task force.

**Comment by MohitGupta121** [comment]
This issue is fixed in PR #4779
