### ISSUE TITLE
Exploration titles aren't showing up

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4709]
**Describe the bug**
Exploration titles are no longer showing up correctly.

**To Reproduce**
1. Open the Prototype exploration
2. Observe that the title bar is blank.

**Expected behavior**
Exploration titles should show.

**Demonstration**
Here's an example of this behavior on the latest beta version of the app (with production assets):
![image](https://user-images.githubusercontent.com/12983742/201472360-818d3599-6d43-4184-a957-ed808158557d.png)

**Environment**
- Device/emulator being used: Nexus 5X (real device)
- Android or SDK version (e.g. Android 5 or SDK 21): SDK 27
- App version (you can get this through system app settings or via the admin controls menu in-app): latest develop (5e64fae55e0024529ac7eb48de401c2035d2e4f3).

**Additional context**
Found this during Beta MR2 testing.

**Comment by BenHenning** [comment]
It looks like this regressed in 87f0e981245229f894dcbf85db190391f7f08ed8 per git bisect, introduced in #4482.

**Comment by BenHenning** [comment]
Oddly, this might be caused by a combination of #4482 and #4392, it's a bit tricky to understand exactly what the toolbar is doing here. I'll explain in more details in my PR once it's ready.

**Comment by BenHenning** [comment]
So I've spent quite a bit of time mulling this one over and investigating at various potential solutions. As I see it, here's the situation:
- #2581 describes the state of marquee view handled by default in Android. Sometimes marquee restarts in cases when it isn't desired, and could be potentially confusing to users. We aimed to try and fix this.
- Android's TextView provides no obvious way to override default marquee functionality (as it's built into TextView's [onDraw](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/widget/TextView.java;l=8208;drc=e13851556bcfecff6de4b3a1a99be4dcaa5853a1)), nor a way to augment its behavior (there's no callback for when the marquee finishes or changes state).
- We could use reflection to introspect TextView to bolt on a detection mechanism for marquee state, but this introduces potential compatibility and performance problems (we strongly err away from reflection-based solutions for this reason).
- This basically leaves us with either: (1) creating a custom view to perform our own marquee handling, or (2) building a view-based component on top of TextView to manipulate it into showing marquee in a more predictable way.
- (1) Is what I've been looking into. I originally hoped I could derive a solution that extends TextView, but performing a marquee either involves layout & measure work (which turns into (2)), or creating a TextView from scratch and performing the text drawing ourselves. The latter is really not ideal--text drawing is complex, and reinventing TextView's functionality is very likely going to be difficult and a maintenance nightmare.
- (2) Is the way https://github.com/oppia/Android-MarqueeView (introduced in #4392) tries to solve. However, I think the original implementation has issues that are not obvious to fix (which led to the text not showing up at all after #4482 was introduced). It seems that per [this line](https://github.com/oppia/Android-MarqueeView/blob/a935a78c88a01958716396e6f2cb4abf4559eccc/library/src/main/java/asia/ivity/android/marqueeview/MarqueeView.java#L304) the wrapping layout regenerates the marquee whenever the text changes (such as updating the title, as we do in the case of exploration title). Now, for reasons I don't fully understand, something about #4482 led to the TextView not fully measuring by the time we set the text, resulting in the above marquee reset not having the proper dimensions.
- I was hoping I could introduce a smarter delay than just "post" to try and address the issue (i.e. using doOnPreDraw). This actually does fix the problem, but it then subsequently fails on rotation. I think this is because pre-draw isn't a guaranteed time to know the size is available.
- Another idea I had was to use a layout change listener on the TextView, but this introduces a circular issue since MarqueeView itself changes the bounds of the TextView.
- I thought of passing in the exploration title instead of loading it asynchronously, but this will actually exacerbate the issue--we need a longer delay, not a shorter one.
- I verified that putting in an artificially timed delay of a few seconds always works, but it's gross--we don't know how long to wait (as it may be device dependent), and longer waits will result in visual jank.
- From the perspective of MarqueeView, technically the text and/or layout can change at any time. Also, the original library doesn't properly account for the fact that it may be made aware of a text change before that text may change its measured width (if it's using match_content or constraints).

Overall, this is actually quite a tricky problem to solve. Given the time already sunk into it (between @KevinGitonga and my own work), I actually think that we might need to consider the marquee issues as infeasible. Until we have direct user evidence to suggest that the marquee restarting issues described in #2581 are causing usability issues, I think we should just live with them.

**Comment by KolliAnitha** [comment]
Working fine in RC02 version of MR2 build.
![Screenshot_20221124-110148](https://user-images.githubusercontent.com/101634267/203702132-a2e48046-5c75-43c4-9188-0c00d0b69d77.jpg)
