### ISSUE TITLE
Improve support for scaling in resume lesson screen

### ISSUE THREAD

**Issue by vrajdesai78** [oppia/oppia-android#4710]
**Describe the bug**
When we increase the font size to very large and open resume lesson screen the button's won't scaled properly. 

**To Reproduce**
1. Increase font size to very large (largest)
2. Open resume lesson's screen

**Expected behavior**
Buttons in resume lesson screen should scale properly when we have maximum font size. 

**Demonstration**
![image](https://user-images.githubusercontent.com/43074241/201493956-2807b5d1-ce28-4494-893e-9850b09e74f1.png)

**Environment**
- Device/emulator being used: Nexus 5X
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0

**Comment by iampradeep-hr** [comment]
I would like to work on this issue.

**Comment by BenHenning** [comment]
@rt4914 are you actively working on this or is it something @iampradeep-hr could look into?

**Comment by BenHenning** [comment]
De-assigning @rt4914 since it doesn't seem like he's actively working on this issue.

**Comment by KevinGitonga** [comment]
Hi @BenHenning not able to reproduce this from the current develop branch.  PTAL on demo video below from Nexus 5X emulator device. Also i am myself not noticing the text size changes after updating on Reading Text Size options to start with for some reason. Or was this feature gated due to this issue? Please advice.

https://user-images.githubusercontent.com/20886444/218440186-3489883d-16c6-4d53-b78b-2d34888704da.mp4

**Comment by BenHenning** [comment]
@KevinGitonga the in-lesson reading text size only affects the text size within a lesson (which is why it changes when navigating back). Can you try reproing the issue after increasing display and text size both to max via system settings (rather than using the in-app reading text size)?

**Comment by KevinGitonga** [comment]
Thanks @BenHenning I am able to reproduce this on a Nexus 5X Api 29 and Google pixel 3xl device, by setting both max display and max font.
![Screenshot_1678090500](https://user-images.githubusercontent.com/20886444/223054210-ced4b94e-3b85-4954-8ca4-907c84894caf.png)

**Comment by XichengSpencer** [comment]
I think a workaround to this is that we can use the shorter text on the button. For example, use "redo" or"restart" to replace "start over" and "next" to replace "continue". If those replacements make sense to everyone.

**Comment by Ayush-865** [comment]
I understood the issue but I am not able to reproduce the issue.

**Comment by adhiamboperes** [comment]
Reopening this as the fixing PR was reverted in #5090.

@XichengSpencer, PTAL as discussed.
