### ISSUE TITLE
Info tab is not seen on opening a Topic

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4713]
**Describe the bug**
Info tab is not seen on opening a Topic

**To Reproduce**
1. Open any Topic 'Place Values'
2. See error

**Expected behavior**
Info tab with a short description of chapter and an image, Topic Downloaded and size of the story should be displayed 

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.
![Screenshot 2022-11-13 1 48 02 PM](https://user-images.githubusercontent.com/101634267/201512527-478d1c29-3328-4f7f-8717-927cfae5344c.png)

**Environment**
Device/emulator being used: Infinix SMART 5
Android or SDK version (e.g. Android 5 or SDK 21): Android version 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by BenHenning** [comment]
Thanks for filing @KolliAnitha. Confirming this is working as intended--please update corresponding tests in the test matrix (the info tab is no longer part of the app).
