### ISSUE TITLE
Does not build with the default setup on M2

### ISSUE THREAD

**Issue by Subhadiptech** [oppia/oppia-android#4720]
The project does not build with the default setup.
Running macOS Ventura M2 building for pixel3a API 29

Following the setup for mac [here](https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android)
Install oppia-android and Run the app from Android Studio.

`Execution failed for task ':model:generateProto'.

Could not resolve all files for configuration ':model:protobufToolsLocator_protoc'.
Could not find protoc-3.8.0-osx-aarch_64.exe (com.google.protobuf:protoc:3.8.0).
Searched in the following locations:
[https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.8.0/protoc-3.8.0-osx-aarch_64.exe`](https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.8.0/protoc-3.8.0-osx-aarch_64.exe%60)

Expected to build without issue.

The issue seems like the same one mentioned here https://github.com/oppia/oppia-android/issues/4644
There was a solution of adding proto to local.properties but it should be contained in documentations so that user can easily setup the project locally.

**Comment by BenHenning** [comment]
Thanks for reporting this @Subhadiptech.

Moving this over to be a discussion so that we can investigate where the gap is here.
