### ISSUE TITLE
Portugese: In edit profile page the created date is not seen completely

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4722]
**Describe the bug**
Portugese: In edit profile page the created date is not seen completely

Pre-Requisite:
Change system language to Portugese

**To Reproduce**
1. Go to Administrator Controls
2. Click on Edit Profiles
3. Select any profile
4. See Created date time and year

**Expected behavior**
The year 2022 should also be seen completely

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.
![edit profiles](https://user-images.githubusercontent.com/101634267/201819386-d1f58cb7-8d01-425b-966b-1376e6526388.jpg)

**Environment**
Device/emulator being used: Infinix SMART 5
Android or SDK version (e.g. Android 5 or SDK 21): Android version 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by antonmagnus** [comment]
Can I be assigned this issue?

**Comment by BenHenning** [comment]
I think we don’t need to block MR2 on this issue. 

Feel free to work on this @antonmagnus! I’ve assigned you.
