### ISSUE TITLE
Grammatical mistake seen in a question in Rounding Numbers Part 1- Place Values

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4728]
**Describe the bug**
Grammatical mistake seen in a question in Rounding Numbers Part 1- Place Values

**To Reproduce**
1. Go to 'Topic- Place Values'
2. Click on 'Rounding numbers part 1'
3. Click on Continue till you get to the page 'Ok said Jaime. We're rounding to the tens place...'
4. See that So when we round down 172, we leave the the tens place alone.

**Expected behavior**
the is displayed twice in that sentence

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.
![Screenshot (Nov 16, 2022 2_28_45 PM)](https://user-images.githubusercontent.com/101634267/202162145-60e96eb0-0664-4370-b657-bb372a91b4d3.jpg)

Environment
Device/emulator being used: Infinix SMART 5
Android or SDK version (e.g. Android 5 or SDK 21): Android version 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by BenHenning** [comment]
Routing to the curated lessons team to confirm whether this wording is correct and fix accordingly.

**Comment by seanlip** [comment]
This is now fixed on Oppia.org. Closing (and thanks for reporting)!
