### ISSUE TITLE
Contrast issue in show/hide password icon

### ISSUE THREAD

**Issue by JishnuGoyal** [oppia/oppia-android#4734]
**Describe the bug**

The show/hide button on the user profile pin page has a contrast issue in dark mode when run through the accessibility scanner.

**To Reproduce**
1. Go to a user profile which has a pin
2. In dark mode, the show/hide button has contrast issues

**Environment**
- Device/emulator being used: <Vivo V25 pro>
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Mocks**
Although the mocks are not fully correct because the design for this screen has been changed locally but the icon color is incorrect for sure. 

https://xd.adobe.com/view/3dca36c2-5115-419c-b25e-0f10526b077c-6899/screen/81c45a9d-5c70-46f0-8b02-b57a3df3ff50/specs/

https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/686c27d1-f07b-4680-95da-7767d71558a4/specs/

The correct icon color that can be used here is:

Light mode: #00645C
Dark mode: #3BD1C4

**Comment by BenHenning** [comment]
Dark-mode specific issue, doesn't need to block the release.
