### ISSUE TITLE
Text unit is set in dp instead of sp 

### ISSUE THREAD

**Issue by JishnuGoyal** [oppia/oppia-android#4735]
**Describe the bug**

The text unit is dp instead sp which results in an accessibility error.

<img src="https://user-images.githubusercontent.com/64526117/202462510-225b5d6f-017b-4f99-9e67-26fadf732e68.png" width="250" />

**To Reproduce**
1. On profiles page, click on add user profile option
2. Toolbar text has accessibility issue

**Suggested Solution**:
If you notice code of https://github.com/oppia/oppia-android/blob/da80fab4a78997cb8ab190292f0676117f2722fc/app/src/main/res/layout/admin_pin_activity.xml
 we are not using any `Toolbar in this xml file`. Instead we are setting the title from https://github.com/oppia/oppia-android/blob/da80fab4a78997cb8ab190292f0676117f2722fc/app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt#L119
 What we can do is that instead of using the toolbar/action-bar of activity we can introduce our own `Toolbar` in xml file and can use it in activity & its presenter to set the text. This way we can easily control sp vs dp metric. 
[Similar Implementation](https://github.com/oppia/oppia-android/blob/da80fab4a78997cb8ab190292f0676117f2722fc/app/src/main/res/layout/add_profile_activity.xml)

**Environment**
- Device/emulator being used: <Vivo V25 pro>
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by BenHenning** [comment]
Android 12-specific issue, and one that has marginal benefits so considering it an a11y nice-to-have. Not release blocking.

**Comment by BenHenning** [comment]
Ah actually, this might not be 12-specific if the text itself is using the wrong unit. That being said, we just changed the way titles work back to the old flow so this may no longer be an issue.

**Comment by rt4914** [comment]
> Ah actually, this might not be 12-specific if the text itself is using the wrong unit. That being said, we just changed the way titles work back to the old flow so this may no longer be an issue.

Just tested it and its still an issue and I have updated the issue description to mention one possible solution.

**Comment by Akshatkamboj14** [comment]
Hey @rt4914 when I am trying to add toolbar as proposed in the example, the system toolbar and my toolbar both are displayed simultaneously and plus when I am changing the title https://github.com/oppia/oppia-android/blob/da80fab4a78997cb8ab190292f0676117f2722fc/app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt#L119 to let's suppose something else it's not changing that even.

**Comment by rt4914** [comment]
@Akshatkamboj14 I cannot confirm the exact issue without the PR, but the main changes that you will need to apply in are the activity file, its corresponding xml file and may need to change `AndroidManifest.xml` file and may need to add `android:theme="@style/OppiaThemeWithoutActionBar"` to corresponding activity. 

Also, I am a bit inactive these days, so please assign these issues to @MohitGupta121 or @BenHenning or any other active team-member for faster replies. Thanks.

**Comment by prafulbbandre** [comment]
Hi @adhiamboperes,
I would like to work on this issue.

**Comment by MohitGupta121** [comment]
@prafulbbandre can you give a brief description of how you are tackling this? What files have you changed, what is the actual cause of the issue, do you have a screenshot or video showing that your fix works?
Feel free to post any of the above here and if it looks like it is in the right direction, we can assign this to you. Thanks!

**Comment by adityamishra9** [comment]
Hi @adhiamboperes , please allow me to work on this issue

**Comment by adhiamboperes** [comment]
Hi @void-iish, thanks for your interest in contributing to this issue, but it is already assigned to @prafulbbandre. Why don't you take a look at other unassigned issues [here](https://github.com/oppia/oppia-android/issues?q=is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee), and let me know which one interests you?

**Comment by Vishwajith-Shettigar** [comment]
can i work on this issue ?

**Comment by adhiamboperes** [comment]
> can i work on this issue ?


@Vishwajith-Shettigar, we ask that you give us a brief description of how you would go about solving the issue, or otherwise put up a draft pull request.

**Comment by Vishwajith-Shettigar** [comment]
> 

yeah i'm trying to figure out, new to open source and i will try my best

**Comment by Vishwajith-Shettigar** [comment]
> > can i work on this issue ?
> 
> @Vishwajith-Shettigar, we ask that you give us a brief description of how you would go about solving the issue, or otherwise put up a draft pull request.

Here is my approach 
1) Setting noActionbar for admin_pin_activity.
2) setting up own toolbar  in admin_pin_activity.
3) using AdminPinActivityPresenter we can set the title 

Can you tell me am I going right please, that would be really helpful.

**Comment by Vishwajith-Shettigar** [comment]
can you assign me this issue please !

**Comment by Vishwajith-Shettigar** [comment]
i have made a draft pull request #5132, please guide me.
Thank you

**Comment by Vishwajith-Shettigar** [comment]
Here is a new pull request #5134. Hope this works.
