### ISSUE TITLE
[a11y] TextView has fixed width and scalable text

### ISSUE THREAD

**Issue by JishnuGoyal** [oppia/oppia-android#4736]
**Describe the bug**

On revision screen, the toolbar text and navigation cards have accessibility issues: TextViews have fixed width and scalable text. Attaching a screenshot of the accessibility scanner output for reference.

<img src="https://user-images.githubusercontent.com/64526117/202466320-4b5ddb97-d004-4c70-9841-810c8552e3dd.png" width="250" /> <img src="https://user-images.githubusercontent.com/64526117/202466345-86092399-dbfe-48f9-8357-125a6adbefde.png" width="250" />

**To Reproduce**
1. Go to `Fractions` topic
2. Click on `Revision` tab
3. Select `Fractions of a group`
4. Now take screenshot from [accessibility scanner](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide#using-a11y-scanner-in-android) to test the issue.

**Note for assignees**
 This issue will need some debugging to exactly understand the issues and also to find a viable solution. A good starting point can be [Ben's comment](https://github.com/oppia/oppia-android/issues/4736#issuecomment-1376603778)

**Environment**
- Device/emulator being used: <Vivo V25 pro>
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by BenHenning** [comment]
Android 12-specific issue, and one that has marginal benefits so considering it an a11y nice-to-have. Not release blocking.

**Comment by anmolkulshrestha** [comment]
@BenHenning pls can u assign me to this issue? also, this will be my first contribution

**Comment by seanlip** [comment]
@anmolkulshrestha Would you please explain in more detail how exactly you plan to fix this? We are moving towards only assigning folks if they have a clear plan of action that looks correct.

**Comment by anmolkulshrestha** [comment]
@seanlip Try setting previous_navigation_card and next_navigation_card width to 0dp in revision_card_fragment and setting minWidth =144dp. After that add margins around each card. This way, the width will expand horizontally and keep the height at its minimum (wrap_content). 
This is Working fine.

**Comment by anmolkulshrestha** [comment]
@seanlip pls reply so that i can start working on it , above i have mentioned my solution

**Comment by seanlip** [comment]
Thanks, I checked with @JishnuGoyal. This is what he says:

> I think this approach might create a problem when the card title text would be long. In case of a long text, this approach could probably expand the nav card.
> To clarify, the ID mentioned in the suggested solution targets the cards themselves, not the text view.
> The approach mentioned there might work for some cases, but could break in others.

So I don't think we can assign you this yet. That said, if you like, you can try coding something locally that addresses the above concerns, and posting a screenshot to show that it works correctly as proof.

**Comment by anmolkulshrestha** [comment]
@seanlip pls can you suggest something on how should i approach it

**Comment by JishnuGoyal** [comment]
@seanlip @anmolkulshrestha FYI this issue shows the accessibility scanner output for the screen, and solving it would require free expansion of the navigation card itself (in order to accomodate the title of the nav card). This is something similar to what @anmolkulshrestha suggested,  and upon cross checking through the code myself, I think there is nothing more required at the moment to resolve the issue. 

In the event when there is a long title, the textView shall expand its height to accomodate the text.

Waiting for @BenHenning's thoughts before closing this issue.

**Comment by BenHenning** [comment]
@JishnuGoyal I think the issue for the card is coming from the fact that the title is match_parent and the card view itself has a fixed width. This means that the container won't scale with the text (so larger text would cause less of it to appear/more to be ellipsized). This introduces a potential accessibility issue: users who need to enlarge the text will not be able to see as much of it.

In fact, we probably *should* be line-wrapping the text here and not ellipsizing it.

The toolbar issue might be fine, though. It's possible the scanner doesn't understand text marqueeing, but it would be nice to figure out a way to silence this error (otherwise we can't ever reach 0 accessibility scanner problems found).

**Comment by Abinash6000** [comment]
Adding the following two lines to revision_card_fragment solves the issue. 
```
 android:autoSizeTextType="uniform"
 android:autoSizeMaxTextSize="15sp"
```
Can I work on this ?  @rt4914 @adhiamboperes @MohitGupta121 @seanlip

**Comment by adhiamboperes** [comment]
> Adding the following two lines to revision_card_fragment solves the issue.
> 
> ```
>  android:autoSizeTextType="uniform"
>  android:autoSizeMaxTextSize="15sp"
> ```
> 
> Can I work on this ? @rt4914 @adhiamboperes @MohitGupta121 @seanlip

Why max size of 15sp? How would this display in a large device like a tablet, ?

**Comment by Abinash6000** [comment]
> > Adding the following two lines to revision_card_fragment solves the issue.
> > ```
> >  android:autoSizeTextType="uniform"
> >  android:autoSizeMaxTextSize="15sp"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can I work on this ? @rt4914 @adhiamboperes @MohitGupta121 @seanlip
> 
> Why max size of 15sp? How would this display in a large device like a tablet, ?

@adhiamboperes less than 15sp doesn't solves the problem and these are the before and after images in a tablet. 
(after)
![image](https://github.com/oppia/oppia-android/assets/110354418/5a357a42-70f4-4031-a6f7-d3343dfe01c7)
(before)
![image](https://github.com/oppia/oppia-android/assets/110354418/6e7d3d1a-059d-400e-af84-f719b19f7f4f)

**Comment by adhiamboperes** [comment]
> > > Adding the following two lines to revision_card_fragment solves the issue.
> > > ```
> > >  android:autoSizeTextType="uniform"
> > >  android:autoSizeMaxTextSize="15sp"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Can I work on this ? @rt4914 @adhiamboperes @MohitGupta121 @seanlip
> > 
> > 
> > Why max size of 15sp? How would this display in a large device like a tablet, ?
> 
> less than 15sp doesn't solves the problem

Max size means the biggest size the text is allowed to have. This would limit any scaling implementations from growing the text appropriately. Could you please investigate the approach mentioned in https://github.com/oppia/oppia-android/issues/4736#issuecomment-1376603778?

**Comment by Abinash6000** [comment]
ok I'll try that

**Comment by Abinash6000** [comment]
> > > > Adding the following two lines to revision_card_fragment solves the issue.
> > > > ```
> > > >  android:autoSizeTextType="uniform"
> > > >  android:autoSizeMaxTextSize="15sp"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Can I work on this ? @rt4914 @adhiamboperes @MohitGupta121 @seanlip
> > > 
> > > 
> > > Why max size of 15sp? How would this display in a large device like a tablet, ?
> > 
> > 
> > less than 15sp doesn't solves the problem
> 
> Max size means the biggest size the text is allowed to have. This would limit any scaling implementations from growing the text appropriately. Could you please investigate the approach mentioned in [#4736 (comment)](https://github.com/oppia/oppia-android/issues/4736#issuecomment-1376603778)?

ok I'll try that

**Comment by Abinash6000** [comment]
If we were to line wrap instead of ellipsize. We will need to remove ``` android:lines="3" ``` and set  ```android:maxLines="30"``` to a high value. But the TextView's height becomes wrap_content.
![image](https://github.com/oppia/oppia-android/assets/110354418/d65317b7-7a36-4458-b6b3-33469d0e476d)
Is it a good solution ? @adhiamboperes

**Comment by adhiamboperes** [comment]
> If we were to line wrap instead of ellipsize. We will need to remove `android:lines="3"` and set `android:maxLines="30"` to a high value. But the TextView's height becomes wrap_content. ![image](https://user-images.githubusercontent.com/110354418/253936427-d65317b7-7a36-4458-b6b3-33469d0e476d.png) Is it a good solution ? @adhiamboperes

Hi @Abinash6000, sorry for replying late:
Yes, we can replace ellipsize with line wrap, but there's probably no need to remove `android:lines="3"`. It is used here to specify how tall the textview will be, for uniformity. Also `android:maxLines="30"` is large(and not necessary).

My suggestion here is:
Since both`previous_navigation_card` and `next_navigation_card` cardviews are within a ConstraintLayout, you can do the following:
- change  both of their widths to `wrap_content`
- Constrain them to start or end of parent respectively. 
- Add a minimum width attribute with value of 144dp so they never become smaller than that for accessibility reasons.
- Change the width of the textviews under consideration to wrap content

**Comment by adhiamboperes** [comment]
@Abinash6000 I am assigning this issue to you. Please let me know if you have any questions.

**Comment by Abinash6000** [comment]
@adhiamboperes If we do that then the cardView expands to wrap_content, that makes the views seem inconsistent. Is that okay ?
![image](https://github.com/oppia/oppia-android/assets/110354418/68a6a169-5ad4-4c67-95d2-93c300a5dd8a)

I think the line wrapping is already handled, (see below image)
![image](https://github.com/oppia/oppia-android/assets/110354418/9972f861-5dbd-4e5e-a14d-a14dad2c441d)

As https://github.com/oppia/oppia-android/issues/4736#issuecomment-1376603778 mentions that "(so larger text would cause less of it to appear/more to be ellipsized). users who need to enlarge the text will not be able to see as much of it." 
To address this issue we can replace ```android:lines="3"``` with ```android:minLines="3"``` which does the job of specifying how tall the textview will be (see left cardView in below image). And add another attribute ```android:maxLines="5"``` which automatically increases the lines of textView if lines become greater than 3.
![image](https://github.com/oppia/oppia-android/assets/110354418/33940594-7037-4488-8bad-1fdfddde515d)

Which solution should I pursue ?

**Comment by adhiamboperes** [comment]
> @adhiamboperes If we do that then the cardView expands to wrap_content, that makes the views seem inconsistent. Is that okay ? ![image](https://user-images.githubusercontent.com/110354418/254252482-68a6a169-5ad4-4c67-95d2-93c300a5dd8a.png)
> 
> I think the line wrapping is already handled, (see below image) ![image](https://user-images.githubusercontent.com/110354418/254253720-9972f861-5dbd-4e5e-a14d-a14dad2c441d.png)
> 
> As [#4736 (comment)](https://github.com/oppia/oppia-android/issues/4736#issuecomment-1376603778) mentions that "(so larger text would cause less of it to appear/more to be ellipsized). users who need to enlarge the text will not be able to see as much of it." To address this issue we can replace `android:lines="3"` with `android:minLines="3"` which does the job of specifying how tall the textview will be (see left cardView in below image). And add another attribute `android:maxLines="5"` which automatically increases the lines of textView if lines become greater than 3. ![image](https://user-images.githubusercontent.com/110354418/254255678-33940594-7037-4488-8bad-1fdfddde515d.png)
> 
> Which solution should I pursue ?

You could try the second option, per your suggestion.

**Comment by Abinash6000** [comment]
@adhiamboperes This solves accessibility scanner issue.
- Change both of their `layout_width` to wrap_content. (cardViews)
- Add a `maxWidth` attribute with value of 144dp. (cardViews)
- Add a `minWidth` attribute with value of 144dp. (textViews) So the cardViews never become smaller than that for accessibility reasons.

This is same as setting `android:layout_width="144dp"` in cardView, which was there initially.

**Comment by adhiamboperes** [comment]
> 

Sounds good, please attach screenshots of the accessibility scanner?

**Comment by Abinash6000** [comment]
@adhiamboperes here are the screenshots.
![image](https://github.com/oppia/oppia-android/assets/110354418/0d9e4800-65a4-4425-be5f-cfce0740bb0a)![image](https://github.com/oppia/oppia-android/assets/110354418/064dfd7b-c4b7-45b9-b352-25bba076eaf0)

**Comment by adhiamboperes** [comment]
This Looks good to me, thanks!
