### ISSUE TITLE
Contrast issue in Continue Studying text on revision screen

### ISSUE THREAD

**Issue by JishnuGoyal** [oppia/oppia-android#4741]
**Describe the bug**

The "Continue Studying"  text on the revision screen contrast issue in dark mode when run through the accessibility scanner.

**To Reproduce**
1. Go to Home screen and select any topic
2. Go to revision tab
3. Start any revision card in dark mode.
4. Scroll to the bottom. Continue Studying text has very low visibility.

**Environment**
- Device/emulator being used: <Vivo V25 pro>
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by BenHenning** [comment]
Doesn't need to be release blocking since this seems like a dark mode-specific issue.

**Comment by iampradeep-hr** [comment]
I would like to work on this.

**Comment by MohitGupta121** [comment]
@iampradeep-hr you need to fix this "Continue Studying"  Text.

https://user-images.githubusercontent.com/76530270/204619699-06ce68af-f390-4c28-9f54-59a90343658d.png

**Comment by MohitGupta121** [comment]
@iampradeep-hr  Go through this [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode) to get started with dark mode. 
Please make fix this issue according to the wiki.

**Comment by iampradeep-hr** [comment]
Ok here's the [PR](https://github.com/oppia/oppia-android/pull/4776)
