### ISSUE TITLE
Playstore description for beta version needs to be updated as it doesnt support Arabic now

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4744]
**Describe the bug**
Playstore description for beta version needs to be updated as it doesnt support Arabic now

**To Reproduce**
1. Go to 'Playstore'
2. Click on 'What's new'
3. See 'This release includes support for Arabic and Portuguese app & content translations, and limited app support on KitKat devices.'

**Expected behavior**
Arabic shouldnt be present as it is not supported language for this beta version

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.
![Screenshot_2022-11-17-09-54-11-00_b5a5c5cb02ca09c784c5d88160e2ec24 (1)](https://user-images.githubusercontent.com/101634267/202613523-996c2fe5-a3fc-4c01-8629-7075c5ac8809.jpg)

**Environment**
Device/emulator being used: Infinix SMART 5
Android or SDK version (e.g. Android 5 or SDK 21): Android version 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Additional context**

**Comment by BenHenning** [comment]
Ah, I missed this before. The wording that has issues is actually the change list (i.e. what's changed for that release). The new change wording has been replaced with something specific to MR2, so this should actually be fixed with the outgoing release.

**Comment by KolliAnitha** [comment]
Working fine in RC02 version of beta MR2. Please find the below screenshot.
![playstorr](https://user-images.githubusercontent.com/101634267/203693040-4de14a16-c54c-4c57-a159-dd1331e5327f.jpg)
