### ISSUE TITLE
App crashes intermittently while trying to Switch profile

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4759]
**Describe the bug**
App crashes (few times) on clicking Switch profile

**To Reproduce**
1. Login to Oppia as Admin
2. Click on Menu bar- Click on Switch Profile
3. Click on Exit

**Expected behavior**
User should be able to switch profiles without any issue

**Note**: This is not consistently seen. this behavior is observed only a few times  

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.

https://user-images.githubusercontent.com/101634267/203717166-315d73ad-7762-4a86-a393-d56e99ac29e4.mp4

**Environment**
Device/emulator being used: Infinix smart 5A
Android or SDK version (e.g. Android 5 or SDK 21): Android version 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by BenHenning** [comment]
Hmm we'll need to look into the base stack trace, but I don't think I want to block the outgoing beta release on this as it's both a secondary user experience, and is intermittent.

**Comment by priyatanu** [comment]
Hi @BenHenning ,
Could I work on this issue ?

**Comment by BenHenning** [comment]
Sure @priyatanu. Assigning this over to you.

**Comment by BenHenning** [comment]
@priyatanu are you still working on this?

**Comment by BenHenning** [comment]
@KolliAnitha are you still able to repro it? If so, could you send me a system-captured bug report after reproing it (please don't upload it directly here since bug reports include system logs)? I want to pull out the stack trace to try and root cause what might be happening here.

**Comment by KolliAnitha** [comment]
@BenHenning, Currently I am not seeing this behavior. I am not able to reproduce this issue.

**Comment by BenHenning** [comment]
Thanks for checking @KolliAnitha. Closing this as infeasible, then, since we can't make progress without at least one more repro.
