### ISSUE TITLE
In Terms of Service the website should be displayed as link and should be clickable

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4760]
**Describe the bug**
In Terms of Service the website should be displayed as link and should be clickable

**To Reproduce**
1. Go to Menu - Help
2. Click on Terms of Service
3. In the 1st paragraph look at the website link 

**Expected behavior**
The link https://www.oppia.org should be displayed as a link and it should be clickable.
The sentence ' Thanks for your interest in Oppia Foundation Inc., a nonprofit that operates the website located at https://www.oppia.org (the Website).'

Website is mentioned twice in the statement.

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.
![Screenshot_20221124-143700](https://user-images.githubusercontent.com/101634267/203742523-63fab8f5-7686-484b-879d-9cd7093bde71.jpg)

**Environment**
Device/emulator being used: Infinix smart 5A
Android or SDK version (e.g. Android 5 or SDK 21): Android version 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by BenHenning** [comment]
This seems like a reasonable thing to fix with auto links.

**Comment by SidharthMudgil** [comment]
Hi, can you assign this issue to me

**Comment by SidharthMudgil** [comment]
Can you assign this task to me?

**Comment by seanlip** [comment]
@SidharthMudgil Please follow the instructions [here](https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android#finding-something-to-do) for claiming an issue. You will need to provide an explanation of how you would fix it, and (if possible) a demo of the working fix.

I would also recommend reading and following the other instructions on that page if you haven't already done so. Thanks!

**Comment by SidharthMudgil** [comment]
Hi @BenHenning, Can I work on this issue?

### Solution
Surrounding the link in `a` tag in the _line 7_ of _app/src/main/res/values/terms_of_service.xml_ solve the issue.

**Old Code**
```
operates the website located at https://www.oppia.org (the "Website"). The
```
**New Code**
```
operates the website located at <a href="https://www.oppia.org">https://www.oppia.org</a> (the "Website"). The
```

### Output

https://user-images.githubusercontent.com/68889544/219298998-b485b959-9c90-4101-aca5-11e73de03e23.mp4

**Comment by SidharthMudgil** [comment]
Hi, I have replied in the comment that how I can fix the issue

link:
https://github.com/oppia/oppia-android/issues/4760#issuecomment-1432650578

**Comment by BenHenning** [comment]
@SidharthMudgil this wasn't mentioned earlier, but the solution needs to be done without changing the XML files for the content (since we'll eventually be generating it based on the versions stored in https://github.com/oppia/oppia). This should be solvable without changing the XML.

**Comment by SidharthMudgil** [comment]
Hi, @BenHenning I solved the issue by adding these 2 lines in **_app/src/main/res/layout/policies_fragment.xml_**
```
android:linksClickable="true"
android:autoLink="web"
```

**Output**

https://user-images.githubusercontent.com/68889544/219578378-c96c257d-5697-4692-b01c-b38c66b191b9.mp4

**Comment by MohitGupta121** [comment]
@BenHenning as we see @pratyaksh1610 is make PR #4771 which is now Stale due to inactivity.
So can we assign this issue to @SidharthMudgil as per his solution https://github.com/oppia/oppia-android/issues/4760#issuecomment-1434230475  ?

**Comment by MohitGupta121** [comment]
@SidharthMudgil I think make PR for this directly if it's looks good then reviewers will automatically merge it.
What do you think @BenHenning @seanlip ?

**Comment by seanlip** [comment]
Yup, it's fine to make a PR any time if there aren't any existing viable PRs for a given issue (and you can assign the contributor to the issue if you agree with the proposed solution approach).

**Comment by MohitGupta121** [comment]
Okay sure @seanlip Thanks for your reply.
@SidharthMudgil please go ahead and feel free to make PR for this issue that approach you mentioned. And if you have any query then feel free to comment in the issue thread or PR thread. Thanks.

**Comment by SidharthMudgil** [comment]
Hi @BenHenning @MohitGupta121, Adding the `autolink` make the URL clickable but overrides the `setMovementMethod` property. Hence, other links like `<a href="https://www.google.com">here</a>` no longer work, same as if we remove the `autolink` the HTML links will work but the URL no longer will work. The only possible solution I can think of is to wrap all the URLs we want to make clickable around the `a` tag in all versions stored in  [ https://github.com/oppia/oppia](https://github.com/oppia/oppia)

**Comment by BenHenning** [comment]
@SidharthMudgil you may need to look at how Android's TextView handles the attribute. We manually set the movement method today, so I suspect we can use something like HtmlCompat linkify programmatically to get the links to have correct URLSpans.

**Comment by SidharthMudgil** [comment]
@BenHenning How about this solution? https://stackoverflow.com/a/34793313/16177121

**Comment by BenHenning** [comment]
> @BenHenning How about this solution? https://stackoverflow.com/a/34793313/16177121

@SidharthMudgil I think that approach makes sense and is in-line with what I was thinking (though as a nit we should use LinkifyCompat rather than Linkify).

**Comment by shakivhussain** [comment]
@BenHenning As per your suggestion, 
I have resolved this issue without changing XML files.

Please check my PR #4917

**Comment by BenHenning** [comment]
@shakivhussain this issue is currently assigned to @Uticodes.

**Comment by adhiamboperes** [comment]
Note to developers: Please see https://github.com/oppia/oppia-android/pull/4918 and comments for the proposed solution to this issue.

**Comment by theMr17** [comment]
@Tejas-67 Please explain how you plan to solve the issue, so that the issue can be assigned to you. As per your [comment](https://github.com/oppia/oppia-android/issues/5188#issuecomment-1768419994).

**Comment by Tejas-67** [comment]
Hey @theMr17, this issue can be solved using the SpannableStringBuilder object.

**Comment by adhiamboperes** [comment]
@Tejas-67, in #4918, we were trying to use `LinkifyCompat` to solve this. Could you tell me why `SpannableStringBuilder` is better, or put up a draft pr with demo video to demonstrate your solution.

**Comment by Tejas-67** [comment]
@adhiamboperes SpannableStringBuilder should be preferred because we can have the flexibility to decide what happens when the link is clicked, not just opening a link. Plus, it's easier to change the appearance of the link (colors, textStyles). Also SpannableStringBuilder is faster and more efficient because it won't scan the whole string ( we can simply pass a span range i.e. start index to end index)

**Comment by Tejas-67** [comment]
@adhiamboperes I am facing an error 
"unmappable character (0x90) for encoding windows-1252
   * Corresponds to the Arabic (اَلْعَرَب�?يَّة�?‎) macro language. IETF BCP 47 language tag: ar." . Can you please guide me on how to fix this?
