### ISSUE TITLE
SpotlightFragmentTest is very flaky

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4775]
**Describe the bug**
SpotlightFragmentTest is flaky and is causing incorrect failures both on develop and in individual PR CI runs.

**To Reproduce**
1. Check out the latest develop (780e3671ad48e9e3f3cd1f01a84c43d733445466 as of this issue)
2. Run ``bazel test //app:src/sharedTest/java/org/oppia/android/app/spotlight/SpotlightFragmentTest --runs_per_test=8``
3. Observe that the test fails a lot (4/8 times for my run)

**Expected behavior**
The test run should pass for all 8 runs.

**Demonstration**
![image](https://user-images.githubusercontent.com/12983742/204616944-e8f458da-af7e-4c63-9cf6-6efcf18fb7a9.png)

**Environment**
Linux Mint 20.3 (Una)

**Additional context**
None

**Comment by BenHenning** [comment]
Note that I'm going to run a larger batch of parallel runs (100) to get an idea on a more accurate flakiness percentage.

**Comment by BenHenning** [comment]
(For Gradle users, you should be able to run the test multiple times locally as well but it may not be as reliable for detecting flakes as using Bazel).

**Comment by BenHenning** [comment]
From a local run of 100 tests, 32/100 failed where the following tests were flaky:
1. testSpotlightQueuing_requestTwoSpotlights_checkFirstSpotlightShown (failed 17 times)
2. testSpotlightQueuing_requestTwoSpotlights_pressDone_checkSecondSpotlightShown (failed 20 times)

Given that the test suite has 7 tests overall, this indicates a flakiness of ~5.3% among all tests, and per the results, about 32% flakiness per test suite. Individually, test (1) has a 17% chance of failing and test (2) has a 20% chance of failing.

An overall failure rate of 32% is too flaky, so considering this a high priority issue as it will cause a lot of confusion among developers making changes.

**Comment by JishnuGoyal** [comment]
Thanks for providing these details and stats @BenHenning. I'm looking into where this problem is stemming from. Will reach out soon after finding a solution.
