### ISSUE TITLE
Talkback shouldn't read double tap to activate for the labels that are not clickable

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4790]
**Describe the bug**
Talkback shouldn't read double tap to activate for the labels that are not clickable

**To Reproduce**
Enable Talkback
1. Login to Oppia as Admin
2. Click on any of the topic 'Place Values'
3. Focus will be on the Nav bar topic title

**Expected behavior**
Talkback should read topic title and not double tap to activate as it is not clickable

**Environment**
Device/emulator being used: Oneplus nord2 5g
Android or SDK version (e.g. Android 5 or SDK 21): Android version 12
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by BenHenning** [comment]
Ah, is this just specific to the title part of the nav bar @KolliAnitha? I'm not sure why that's marked as clickable since you're correct in that it doesn't do anything. This might have to do with text marqueeing.

**Comment by KolliAnitha** [comment]
@BenHenning, For Topic: title, Chapter title talkback reads double tap to activate but they are not performing any action.

**Comment by BenHenning** [comment]
Got it. Thanks for clarifying @KolliAnitha.

In this case, I think we should look into why such toolbars are not clickable and see if we can disable it to avoid the confusion.

**Comment by XichengSpencer** [comment]
Hi @BenHenning, in the code there is a listener added to the entire toolbar which causes this issue. And the only thing this listener does is set the title.isSelected to true. I didn't see anywhere else use this listener to do something and by removing this listener the app works fine. Should I go ahead to remove the listener?

**Comment by XichengSpencer** [comment]
Hi @BenHenning, I think that listener is served for the marquee effect. As it is designed when tapping the topic, the marquee effect will happen once, therefore the listener and "double tap to activate" will be there. 

However, a minor bug here will be that the effect is triggered by textview.isSelected=true in the listener, but we never set it back to false. So if there is a long title, users only have one chance to see the entire title as they enter the activity/fragment. The marquee will only be triggered again if they go back and reenter.

**Comment by rt4914** [comment]
The reason why it is clickable is as follows:
- If the title / topic name is too long that it does not fit in the toolbar, then the title will perform a marquee effect which means that the title will move from right-left to show the full title. Now once it has finished one full cycle, it will stop but the user can again play it by clicking on the title/toolbar. 
- That's the reason why it is clickable and therefore the talkback is giving correct output. We can update the implementation of toolbar to be something to fix this but the talkback is working as expected.

cc: @BenHenning @XichengSpencer @KolliAnitha @seanlip

**Comment by adhiamboperes** [comment]
> The reason why it is clickable is as follows:
> 
> * If the title / topic name is too long that it does not fit in the toolbar, then the title will perform a marquee effect which means that the title will move from right-left to show the full title. Now once it has finished one full cycle, it will stop but the user can again play it by clicking on the title/toolbar.
> * That's the reason why it is clickable and therefore the talkback is giving correct output. We can update the implementation of toolbar to be something to fix this but the talkback is working as expected.
> 
> cc: @BenHenning @XichengSpencer @KolliAnitha @seanlip

From my own investigation into the issue, there's not really much we can do to override the "double tap to activate" announcement. This is controlled by device-side VERBOSITY settings, and it is recommended that as developers we should not remove these, as users need them to understand the app. If the user sets the Verbosity to "Low" in `Accessibility -> Talkback -> Settings -> Verbosity -> Speak usage hints`, this would not be read.

**Comment by BenHenning** [comment]
Can we disable marquee when an accessibility manager is active? That seems like the ideal approach since a marquee effect is likely to not be very helpful, anyway, and the readout will probably be more useful.

**Comment by XichengSpencer** [comment]
Thanks Ben for the suggestion, I will look into it.

**Comment by BenHenning** [comment]
@adhiamboperes this is marked as blocked, but the blocked columns aren't filled in--could you clarify what this is blocked on?
