### ISSUE TITLE
In Dark Mode the white corners of Stories Cards are visible.

### ISSUE THREAD

**Issue by MohitGupta121** [oppia/oppia-android#4791]
In dark mode if you notice closely at the edges, you will see that there are white corners which are visible. They should not be visible.

For example in `prmoted_story_card` this is happening because we are using `app:roundedRectDrawableWithColor="@{viewModel.promotedStory.lessonThumbnail.backgroundColorRgb}"`
So basically to fix this in `promoted_story_card`, we first need to remove `app:roundedRectDrawableWithColor="@{viewModel.promotedStory.lessonThumbnail.backgroundColorRgb}"` and then in `PromotedStoryCardView` we should add `app:cardBackgroundColor="@android:color/transparent"` which should give correct results in both dark mode and light mode.

This above solution is for `promoted_story_card` only but we have various other cards too like `topics`, `ongoing_topic`, `completed_story`, etc so please focus on them too.

<img src="https://user-images.githubusercontent.com/76530270/206967336-8d2ffdaa-9e69-4295-ba65-1a456996a702.png" height="400" style="max-width: 100%"> 

**To reproduce**
Once logged in, Switch to Dark Mode, and notice the various Story/Topics Cards Corners.

**Comment by PratyushSingh07** [comment]
hey @bladebunny @MohitGupta121 @sierisimo @yurilev can i work on this issue?

**Comment by MohitGupta121** [comment]
@PratyushSingh07 great to see your interest to contribute in oppia. Actually this issue is a part of dark-mode-project and I'm already working on this.
You feel free to pick another [issue](https://github.com/oppia/oppia-android/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee) .
