### ISSUE TITLE
In dark mode for few of the questions the partition in milk portions is not clearly visible in what is a ratio chapter

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4792]
**Describe the bug**
In dark mode for few of the questions the partition is not clearly visible in what is a ratio chapter

**To Reproduce**
Enable dark mode
1. Go to 'What is a Ratio' chapter in Ratios and Proportional Reasoning topic
2. Click on Continue till you reach the question which of the following pictures show a 3:2 ratio of orange puree to milk
3. See screen

**Expected behavior**
In dark mode the partition in milk portions should be clearly visible for users

**Demonstration**
![IMG_20221219_111154_954](https://user-images.githubusercontent.com/101634267/208357020-8ba6d43a-cde1-4e8a-a23d-dc23bf7d838c.jpg)

**Environment**
Device/emulator being used: Oneplus nord2 5g
Android or SDK version (e.g. Android 5 or SDK 21): Android version 12
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by BenHenning** [comment]
I think we'll either need to invert the colors for content images when using dark mode, or put a lighter background behind the images while in dark mode to ensure sufficient contrast. A longer term solution might be to have dark mode-specific assets for lessons, but this will double the number of assets needed to be produced & maintained by the team, and largely affects Android exclusively. It would be much better to try and find a general solution, instead.

@MohitGupta121 @rt4914 do you have any thoughts?

**Comment by rt4914** [comment]
@BenHenning I do think your approach is correct here. The best solution for our case would be to invert the colors.

@MohitGupta121 As discussed, can you look into this. The solution should be such that it should apply to png as well as svg files, ideally.

Maybe this can help https://github.com/oppia/oppia-android/issues/3122

**Comment by rt4914** [comment]
Maybe we will somehow from code turn on "Invert Color" option for user in dark mode.

**Comment by ShubhadeepKarmakar** [comment]
![oppia ui](https://user-images.githubusercontent.com/99060332/208736906-afa5a886-97d1-45f5-8d86-854fae5b9803.jpg)
Device: Redmi Note 9pro

Everything is fine in dark mode.

**Comment by rt4914** [comment]
# Dark Mode - OFF and Invert Colors - OFF
<img src="https://user-images.githubusercontent.com/9396084/216603529-0f55a04d-acfe-432d-ae77-e0fe3b85ca56.JPG" width="250" />

# Dark Mode - ON and Invert Colors - OFF

<img src="https://user-images.githubusercontent.com/9396084/216603792-ba3c2a33-7846-4b2c-a7c1-5172915faa66.JPG" width="250" />


# Dark Mode - OFF and Invert Colors - ON

<img src="https://user-images.githubusercontent.com/9396084/216603924-65625c03-d146-42a9-bd78-cb26184d66cb.JPG" width="250" />

# Dark Mode - ON and Invert Colors - ON

<img src="https://user-images.githubusercontent.com/9396084/216604053-21a4ffeb-4c18-4fa0-aff7-10eeb22f37a6.JPG" width="250" />

**Device used**: Motorola G60
**Android Version**: 12

Based on this I think we actually don't need to solve this as it might create issues for other images too. **Or** if want to solve this then also we should observe it on multiple devices and across multiple questions.


@MohitGupta121 Can you generate similar images and post it here?

**Comment by MohitGupta121** [comment]
# Dark Mode - OFF and Invert Colors - OFF

<img src="https://user-images.githubusercontent.com/76530270/216760878-c04a39f8-88ca-403a-b993-01d21b614647.jpg" height="400" style="max-width: 100%">

# Dark Mode - ON and Invert Colors - OFF

<img src="https://user-images.githubusercontent.com/76530270/216760906-f6207e00-2660-422a-a27a-f1467f2176cc.jpg" height="400" style="max-width: 100%">


# Dark Mode - OFF and Invert Colors - ON

<img src="https://user-images.githubusercontent.com/76530270/216760929-5302452d-cd31-4ff6-a60b-578f94183fc5.jpg" height="400" style="max-width: 100%">

# Dark Mode - ON and Invert Colors - ON

<img src="https://user-images.githubusercontent.com/76530270/216760944-8bd28503-0a76-4407-adfa-658dac20f85a.jpg" height="400" style="max-width: 100%">


**Device used**: Poco X2
**Android Version**: 11


@rt4914 Please look at my images how is it?

**Comment by rt4914** [comment]
@MohitGupta121 from the screenshots it looks like that the dark-mode mocks are working correctly.

@BenHenning IMO, lets keep this issue open and if possible test it on more device and get more results especially **Redmi Note 9 pro** and once we can confirm across multiple devices then we can take final conclusion.

**Comment by MohitGupta121** [comment]
Okay Thanks @rt4914 I try to get results from multiple devices. And also try to get results from **Redmi Note 9 pro** in my connections.

**Comment by MohitGupta121** [comment]
> @BenHenning IMO, lets keep this issue open and if possible test it on more device and get more results especially **Redmi Note 9 pro** and once we can confirm across multiple devices then we can take final conclusion.


@rt4914 I think we have to get screenshots from **Oneplus nord2 5g** as we see @KolliAnitha having issue in that device instead of Readmi note 9 ?

**Comment by KolliAnitha** [comment]
The image i took are with Dark mode-ON and Invert color mode - ON. But however, with only dark mode on are the partitions clearly visible.

![Screenshot_2023-03-01-11-55-17-32_943a62cb4c6fb83e010e1c2e82766a17](https://user-images.githubusercontent.com/101634267/222061553-ddee3b83-ae96-451e-8728-1f7338b2be5c.jpg)

**Comment by MohitGupta121** [comment]
> The image i took are with Dark mode-ON and Invert color mode - ON. But however, with only dark mode on are the partitions clearly visible.
> 
> ![Screenshot_2023-03-01-11-55-17-32_943a62cb4c6fb83e010e1c2e82766a17](https://user-images.githubusercontent.com/101634267/222061553-ddee3b83-ae96-451e-8728-1f7338b2be5c.jpg)

Thanks @KolliAnitha 

So from this screenshot it's clear that this is issue is not part of Dark Mode. 

@rt4914 now we can close this issue as not part of dark-mode because this issue is separate related to Invert color? 
As you suggests in mail.

**Comment by rt4914** [comment]
Considering that this issue is only because of invert-colors and does work correctly when dark-mode is on. Closing it as the implementation is correct.
