### ISSUE TITLE
Talkback is reading close icon as navigator button in Hints page

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4793]
**Describe the bug**
Talkback is reading close icon as navigator icon in Hints page

**To Reproduce**
Enable Talkback
1. Go to 'Placevalues' - What are the place values
2. Click on Continue till you reach the question 'how many place values does your score have, Jaime'
3. Wait till you get a hint

**Expected behavior**
Talkback should read close icon instead of navigator button

**Demonstration**
https://user-images.githubusercontent.com/101634267/208364800-d327449c-e829-4a1d-9d1b-8c99fe0a6134.mp4

**Environment**
Device/emulator being used: Infinix smart 5A
Android or SDK version (e.g. Android 5 or SDK 21): Android version 12
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by BenHenning** [comment]
Hmm this might be partly out of our control as it largely depends on Talkback preferring to start in the upper left corner, and it may not actually be an issue since that's standard & expected behavior by the screenreader.

That being said, let's keep this open and look into how other, popular apps with known good accessibility support handle these sorts of transitions.

**Comment by rt4914** [comment]
Update: We can actually fix this by changing the content description of close icon. We might need to check other similar screens too like ConceptCard, Revision Card etc which uses close icon and decide whether to read `Navigate up` or `Close`

**Comment by prafulbbandre** [comment]
Hi @rt4914 @adhiamboperes @MohitGupta121 I would like to work on this.
I will update the strings.xml file by changing Navigate up text to Close Button text.

**Comment by adhiamboperes** [comment]
Hi @prafulbbandre, I have assigned the issue to you.

**Comment by Abinash6000** [comment]
Hi @rt4914 @adhiamboperes @MohitGupta121,
Can I do something here?

**Comment by adhiamboperes** [comment]
Hi @Abinash6000, this issue is currently assigned. Please look at one of [these](https://github.com/oppia/oppia-android/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) that has not yet been assigned.

**Comment by Abinash6000** [comment]
Ok! Thanks for replying.
