### ISSUE TITLE
Add dark mode support to Equations Text 

### ISSUE THREAD

**Issue by MohitGupta121** [oppia/oppia-android#4845]
**Describe the bug**

Equations Color in dark mode is still black need to change to white so that it visible in dark mode.

**To Reproduce**
1. Turn on your emulator dark-mode
2. Go to 'Fractions Card'
3. Click on 'Revision' in top menu
4. Click on 'What is Fraction Card'
5. See error

![image](https://user-images.githubusercontent.com/76530270/213153964-13df044c-45bb-4fde-bea8-db2b2157d579.png)

**Comment by PratyushSingh07** [comment]
hey @MohitGupta121 are you still working on it? If not then i would like to work on it

**Comment by MohitGupta121** [comment]
@PratyushSingh07 Yes I'll changing the library code.

**Comment by MohitGupta121** [comment]
@BenHenning I make the PR #4866 for this issue as we discuss in last meeting also done with the [kotlitex](https://github.com/oppia/kotlitex) library changes only PR for that left soon I will do that.

**Comment by MohitGupta121** [comment]
@BenHenning I make PR for Kotlitex Library Please first review and merge that to avoid build and workflow tests failures https://github.com/oppia/kotlitex/pull/1
