### ISSUE TITLE
Bullet points show up weirdly in the app

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#4855]
**Describe the bug**
Bullet points seem to show up misaligned in the app.

**To Reproduce**

I only know how to reproduce this on the alpha-kenya build. Here are screenshots from a few places:

(a) Multiplication > Revision Card > Techniques of Multiplication
![Screenshot_20230125-172138](https://user-images.githubusercontent.com/10575562/214551182-3ffe0083-0c98-42c5-881b-90f4297c903c.png)

(b) Multiplication > Lesson 1 > Final Card

![Screenshot_20230125-172708](https://user-images.githubusercontent.com/10575562/214551386-c93df959-ef95-4f00-b600-d9f8f0b5a141.png)

**Expected behavior**
The inner white bullet points should be closer to their text.

**Environment**
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-alpha_kenya

**Comment by Parth27904** [comment]
Hey @seanlip ! I am a beginner at android and I would like to work on this problem. Can you please assign this to me? I plan on the usage of BulletSpan.

**Comment by seanlip** [comment]
@Parth27904 Can you try doing this locally and show a screenshot/video of it working, as well as describe the approach you're taking? If it looks good and the approach is sound, we can assign it to you.

Thanks!

**Comment by Parth27904** [comment]
@seanlip I am a beginner so can you help me with some hints or resources about this problem

**Comment by seanlip** [comment]
@Parth27904 I'm afraid not -- this is an issue which requires investigation. If you would like to help out, I would suggest following the instructions on the [wiki](https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android) and focusing mainly on good first issues that you are confident you can tackle.

Note that, before assigning you to an issue, we will always ask you for an explanation/proof of how you plan to do it, so it might be worth trying to see if you can get it working locally first.

**Comment by Abhinav-1111** [comment]
I want to work on this issue . Please assign me this issue.

**Comment by seanlip** [comment]
@Abhinav-1111 Please see the second paragraph of the previous comment. Feel free to post if you have an explanation of how you plan to solve it (please provide details of which files you plan to change etc.) -- thanks.

**Comment by Abinash6000** [comment]
@seanlip I built the app from android studio but it doesn't have any multiplication section in it. Am I missing something?
![image](https://user-images.githubusercontent.com/110354418/215341354-34ea35ec-b3be-47b3-b9a2-ea52f7e87d7f.png)

**Comment by seanlip** [comment]
@Abinash6000 Ah yes, sorry, I think this needs access to a revision card with bullet points or the prod build mentioned in the description. I think @BenHenning is currently working on fixing it though (for a study we are running) so perhaps finding a different issue would be better. You can see our good first issues at https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 -- maybe pick one of those?

Thanks!

**Comment by sumanbmondal** [comment]
@seanlip This issue can also be reproduced by navigating to FAQs or Privacy Policy in the Help Section.
![bulletpts](https://user-images.githubusercontent.com/94859440/215720283-3987bf3d-f54c-4bd2-96c7-2bb9763f8643.jpg)
![bulletpts2](https://user-images.githubusercontent.com/94859440/215720329-110f5d5f-59c2-446e-a6d9-4e16e70f2a1c.jpg)

**Comment by seanlip** [comment]
Thanks @sumanbmondal -- yup, good catch. I think @BenHenning is fixing this in #4846 ... it might be worth checking if this issue is resolved once you merge those changes in?

**Comment by sumanbmondal** [comment]
@seanlip Yup, I'm definitely watching and learning as much as I can.
