### ISSUE TITLE
Provide a tap-and-zoom feature for images.

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#4857]
**Is your feature request related to a problem? Please describe.**
Some of the images in the lessons on the app are small and hard to read. Examples include the following from Multiplication lesson 3:

![Screenshot_20230125-173248](https://user-images.githubusercontent.com/10575562/214553015-6313bb1d-d956-444f-9aa0-345b5cc36ff6.png)

![Screenshot_20230125-173403](https://user-images.githubusercontent.com/10575562/214553020-bc68a313-f0b8-436a-ab2e-932e6a745e10.png)

**Describe the solution you'd like**

Long-pressing on the image should show a full-screen version (with an X at the top right to close it) which can be pinched-to-zoom and panned.

**Alternatives considered**

Another idea might be to allow pinch-to-zoom that allows the user to expand the size of the page contents -- currently, those are locked to a fixed size. But this might raise other issues.

**Additional context**
Some research on what other apps do might be a good idea (perhaps e-readers). I'm not certain about how discoverable the long-press interaction is.

**Comment by BenHenning** [comment]
Is this a duplicate of #4093?

**Comment by seanlip** [comment]
Ah, yes it is, thanks. Closing.
