### ISSUE TITLE
Configure Firebase, Firestore and BigQuery on the Development Environment

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#4878]
## Set Up Requirements

- [x] Upgrading the project plan to Blaze. This is necessary to be able to stream data to BigQuery in realtime, and to install the extension that supports this.

### Enable Firestore for the Project
- [x] Owner role, or Editor role with Firebase Role: Develop Admin.
- Navigate to the Cloud Firestore section of the [Firebase console](https://console.firebase.google.com/project/_/firestore).
- You'll be prompted to create a database. Follow the database creation workflow.
   - Under _secure rules for Cloud Firestore_, select **Start in production mode**. This prevents external reads and writes.
   - For _Set Cloud Firestore location_, select region as **US**, which is the same as the existing Firebase configuration for analytics and crashlytics.
   - Click **enable**.

### Add Security Rules
- Once in the Cloud Firestore Console, navigate to the **Rules** tab.
- Change the rules to:

```
rules_version = '2';
// Scopes the rules to the firestore product
service cloud.firestore {
  // Specifies that rules should match any Cloud Firestore database
 match /databases/{database}/documents {
   // Specifies that the rule applies to any document in the nps_survey_open_feedback collection
   // As a result, they also deny access to documents in all other collections, which would have to be granted explicitly.
  match /nps_survey_open_feedback/{document} {
    allow read, write: if request.auth != null;
  	}
    }
}
```
- Click publish.

## Stream Collections to BigQuery Integration
- In the Cloud Firestore Console, navigate to the **Extensions** tab.
- Click **Install** on the **Stream Collections to BigQuery** extension.
- [x] The project billing has already been set, so click on **Next**.
- [x] Review APIs enabled and resources created and enable **Cloud Functions** and **Artifact Registry** which are required for this extension to function properly.
- [x] Review access granted to this extension. No action is required.
- [x] Configure extension
       - Cloud Functions location, which is the same as the Cloud Firestore location above
       - BigQuery Dataset location: `United States(multi-regional)`
       - Project Id: `oppia-android-dev`. In production this will correspond to the prod project id.
       - Collection path: `nps_survey_open_feedback`. This is the name our collection will have on Firestore.
       - Dataset ID: `nps_survey_open_feedback_export`
       - Table ID: `nps_survey_open_feedback`.  This is what our collection will be called once exported to BigQuery. We need this since we haven't actually created the collection in Firestore, but the extension will create it in BigQuery. 
       -  We don't need to configure any of the optionals. 
       - Click to **Install Extension**
       
Extension Documentation: [Stream Collections to BigQuery](https://extensions.dev/extensions/firebase/firestore-bigquery-export?authuser=0&hl=en)

**Note** - in production, we will also configure our data retention time to live per our retention policy. Ref #4904 

### Enable Anonymous Auth
In the Firebase console, Open the **Build/Authentication** menu.

- [x] On the **Sign-in Methods** page, enable the **Anonymous** sign-in method.

**Comment by BenHenning** [comment]
Thanks for organizing all of these steps @adhiamboperes! A few questions:
1. Where does oppia-android-dev-nps-survey-feedback come from? Is it a new project that we need to create?
2. For the project ID, collection path, dataset ID, and table ID, we presumably need different versions of these for dev vs. production--how do we do that & what names should we be using?

**Comment by adhiamboperes** [comment]
Hi @BenHenning,
The Project Id for our linked firebase project on BigQuery is `oppia-android-dev`, which is where we should send the exported data. I tested with creating a new project id( hence, oppia-android-dev-nps-survey-feedback) and it does not actually create a new project on BigQuery. I have updated the project id in the instructions.

For (2). Since  the prod and dev projects are seperate with unique project IDs, the collection path, dataset ID, and table ID as well as the corresponding names can be the same without causing conflict. 
Just to clarify that since these are 2 different projects on BigQuery, the export extension  will send data to the respective project id when configured.

**Comment by seanlip** [comment]
Just an update, I've done all the steps in "Set Up Cloud Firestore" and "Stream Collections to BigQuery Integration" but not the rules part yet since allowing all reads/writes from anyone might be too open. Will do the latter once I have confirmation from @adhiamboperes on how to set up something more restricted.

**Comment by adhiamboperes** [comment]
Thanks @seanlip. I have updated the security rules in the description.

**Comment by seanlip** [comment]
Thanks @adhiamboperes -- I've made those updates in the dev project.

Just to check one thing: I notice this is for /mycollection/... . Where is "mycollection" defined? I don't see it in the rest of the config, so just wanted to make sure the name is correct (it seems a bit generic).

**Comment by seanlip** [comment]
(Also, in the future, please assign me to the issue if I'm supposed to take the next action. Thanks!)

**Comment by adhiamboperes** [comment]
> Thanks @adhiamboperes -- I've made those updates in the dev project.
> 
> Just to check one thing: I notice this is for /mycollection/... . Where is "mycollection" defined? I don't see it in the rest of the config, so just wanted to make sure the name is correct (it seems a bit generic).

@seanlip,  "mycollection" references the traget collection, which in our case is `nps_survey_open_feedback`. I have also updated the rules and added some explanations.

**Comment by adhiamboperes** [comment]
I have added the instructions for setting up Automatic Account Cleanup for anonymous accounts.

**Comment by PasunuriSrinidhi** [comment]
The instructions provided outline the necessary steps to set up the required components for streaming data from Cloud Firestore to BigQuery in real-time

**Comment by seanlip** [comment]
Note: Assigning to @BenHenning instead as he'll be carrying out the last set of steps (after a decision is made on what to do here).

**Comment by adhiamboperes** [comment]
Screenshots for this in action can be found in https://github.com/oppia/oppia-android/pull/5087
