### ISSUE TITLE
Add CI checks to ensure Kotlin files are only referencing colors from component_colors.xml

### ISSUE THREAD

**Issue by MohitGupta121** [oppia/oppia-android#4883]
According to newer color conventions, all Kotlin files (Activities, Activity Presenters, Fragments, Fragment Presenters, Views, and View Presenters) should only access colors from `component_colors.xml`.
Add a CI check ensuring the same.

**Comment by BenHenning** [comment]
Reopening since #4942 is left to fix this.

**Comment by MohitGupta121** [comment]
@BenHenning we can Close this issue now, since #4942 is merged.
