### ISSUE TITLE
Gender-Neutral Profile Image 

### ISSUE THREAD

**Issue by nicoleSosa** [oppia/oppia-android#4923]
**Is your feature request related to a problem?**
We would like to suggest a new feature that would make our platform more inclusive for all users. Currently, when creating a profile, there is only a male profile option available, leaving no option for those who identify as female or gender non-conforming.

**Describe the solution you'd like**
To address this issue, we suggest the introduction of a default gender-neutral profile image that users can choose when creating their profiles. We also suggest having a female profile image option in addition to the existing male profile image option.

**Additional context**

**This is the gender neutral option we propose:**

<img width="200" height="200" alt="Screen Shot 2023-03-25 at 9 42 24 PM" src="https://user-images.githubusercontent.com/83420994/227750669-0a80fe4f-a4ea-40ef-b77f-2f03b91c08ad.png">

**Before:**
<img src="https://user-images.githubusercontent.com/83420994/227750516-838d9cdf-a916-4cbb-81a0-3bed7d6c1336.png" width="200" height="400">

**After:**
<img src="https://user-images.githubusercontent.com/83420994/227750522-db27a8ca-915e-4f7e-99d6-ea0ba16eadb9.png" width="200" height="400">

**Comment by prafulbbandre** [comment]
I would like to work on it.

**Comment by BenHenning** [comment]
Thanks for filing this @nicoleSosa! I think it's a nice suggestion, and something that should be straightforward to implement. I think https://fonts.google.com/icons?selected=Material%20Icons%3Aperson_outline%3A would work as a replacement icon--it seems to be the material icon representing what you're suggesting.

@prafulbbandre before we assign issues, we'd like people to provide an explanation for how they'd approach solving an issue (e.g. what files need to be changed & roughly how). How would you approach this?

**Comment by XichengSpencer** [comment]
Hi @BenHenning I think I can work on this by replacing the existing drawable resource with the one you provided in the link.
