### ISSUE TITLE
Addition of a revision tab 

### ISSUE THREAD

**Issue by ivutha2** [oppia/oppia-android#4924]
### Is your feature request related to a problem? Please describe.

Its always frustrating when one taps on the  revision tab beside the lesson tab and instead of getting tests they end up getting a summary of what they are about to encounter in the different chapters.

### Describe the solution you'd like

I would like to have revision tab beside the lesson tab renamed to ‘Summary ‘  and a new tab be introduced ‘Revision questions’ tab that contains the tests to help the students gauge their level of understanding. And if a tutor uses it and the students are done with the test, it will also help him/her know on the area he/she will have to revisit.

### Additional context

![Uploading 1E2AA3DD-4208-45DD-89D1-3149E795B8B5.jpeg…]()

**Comment by prafulbbandre** [comment]
@ivutha2  Screenshot provided by you is not opening.
Can you please reupload it.

**Comment by ivutha2** [comment]
![image](https://user-images.githubusercontent.com/117735796/227716439-b3be04aa-4388-4cd4-8bb8-bb5f83f67f3b.jpeg)

**Comment by ivutha2** [comment]
When you tap on them this is what is presented to you
![image](https://user-images.githubusercontent.com/117735796/227716794-4bb9457e-a1d9-47af-82dc-69044e19a02b.jpeg)
![image](https://user-images.githubusercontent.com/117735796/227716807-1ba0e5a1-5426-4232-ae55-c0fb49c34a23.jpeg)

**Comment by prafulbbandre** [comment]
@ivutha2 Is this an ANDROID app issue.

**Comment by ivutha2** [comment]
Yeah @prafulbbandre

**Comment by prafulbbandre** [comment]
@ivutha2 @seanlip I think Android app issues must be open on https://github.com/oppia/oppia-android.

**Comment by seanlip** [comment]
Yup, moved to the Oppia Android repository.

I don't mind using "Summary" instead of "Revision", but some user research might be needed to confirm that this is the right label. Will follow up with the learner feedback team on this.

**Comment by ivutha2** [comment]
Thank you for the feedback @seanlip and @prafulbbandre 
Much appreciated

**Comment by BenHenning** [comment]
Assigning this to you @seanlip since I think you're the next person to act on this. The team can't act upon this until we have confirmation on the new language to use.

**Comment by seanlip** [comment]
Ack -- thanks @BenHenning. Closing this and tracking it on the design team's repo instead: https://github.com/oppia/design-team/issues/74 . We'll file a new issue once we know what should be done here.
