### ISSUE TITLE
README.md file is not updated.

### ISSUE THREAD

**Issue by prafulbbandre** [oppia/oppia-android#4934]
**Describe the bug**
The opia android app is launch but the readme.md app says that it is not yet launch.

![Screenshot from 2023-03-31 23-39-26](https://user-images.githubusercontent.com/109658545/229197992-9d9cf7f3-48ef-4548-b0c6-a37cf45352db.png)

**Now as the android app is launched it must be updated as**

![Screenshot from 2023-03-31 23-47-42](https://user-images.githubusercontent.com/109658545/229198938-512c586a-13f4-4886-af0a-f98fd161f857.png)

**Comment by BenHenning** [comment]
I think it's fine to update the README text (nice find!), but the app is technically not broadly launched yet (since it's still in beta). Perhaps instead:

```markdown
The Android app is frontend for Oppia that provides...household. The app is now available in beta and can be installed from the [Play Store](https://play.google.com/store/apps/details?id=org.oppia.android).
```

This provides the actual link to the app listing, and clarifies it's in beta (and no longer new).

**Comment by prafulbbandre** [comment]
@BenHenning so should i replace the old lines with the new one you provided.

**Comment by BenHenning** [comment]
> @BenHenning so should i replace the old lines with the new one you provided.

Yep I think that would be clearer @prafulbbandre.

**Comment by prafulbbandre** [comment]
@BenHenning can you assign this task to me?
