### ISSUE TITLE
Text overlapping  with image

### ISSUE THREAD

**Issue by Maryann-01** [oppia/oppia-android#4956]
The text is placed on the image and no space between them.

To Reproduce
 1. Go to "Place Values"
 2. Click on "Place Values 5 Lessons"
 3. See error

Observed behavior
There is no space between the image and the text "Place Values"

Expected behavior
There should be spacing between the image and the text and no overlap.

Screenshots / Videos
![Screenshot_20221011-052939_Oppia](https://user-images.githubusercontent.com/89715739/195058980-28b448f3-787a-40dd-bb07-fd1218eda342.jpg)

Smartphone
 - Device: [Samsung A02]
 - OS: [Android v10]
 - Browser: [Chrome]
 - Browser-version: [81.0.4044.138]

**Comment by aaryan-verma** [comment]
I can fix this issue. Pls assign it to me

**Comment by Maryann-01** [comment]
Hi @aaryan-verma ,I do not think I am the one to assign issues. I think you should ask @seanlip ,our mentor.

**Comment by prafulbbandre** [comment]
@seanlip I think that it is related to oppia-android.

**Comment by seanlip** [comment]
Thanks -- it is, but this is also fixed (we dropped the Info tab). I'll close and move it!
