### ISSUE TITLE
Oppia's android app voiceover button is too small

### ISSUE THREAD

**Issue by yigakpoa** [oppia/oppia-android#4959]
### Is your feature request related to a problem? Please describe.

During my user research, I noticed that the design of the play button/icon was small and our different users kept clicking multiple times before they got it to play. This made them frustrated.

### Describe the solution you'd like

The solution will be to increase the size of the "play" button by making it as big as the chat bubble on the right.

### Describe alternatives you've considered

I've had to continue playing it like that and reporting it in my UX Research for consolidation.

### Additional context

![image](https://user-images.githubusercontent.com/99066793/233794969-9001863e-0671-464e-b052-281aad336592.png)

**Comment by prafulbbandre** [comment]
@seanlip Could you please transfer it to oppia android repo

**Comment by seanlip** [comment]
@prafulbbandre Thanks, I moved it.

**Comment by MohitGupta121** [comment]
@yigakpoa @seanlip Thanks for the issue,
I little increase the icon size and now it's look like this:

<img src="https://user-images.githubusercontent.com/76530270/234305749-912c5391-cd62-4966-9db5-02a3e0dc82a7.png" height="400" style="max-width: 100%">

@yigakpoa Can you please now have a look (please open screenshot in new tab to see exact difference). What's your suggestions?

**Comment by yigakpoa** [comment]
Hi Mohit,

Thank you for increasing it a bit. However If it’s not too much to ask, I
think the size of the bubble on the right will be perfect for our users.

Thank you so much.

Best Regards,
Yigakpoa

**Comment by MohitGupta121** [comment]
@yigakpoa I think now it's look same as bubble icon size as per screenshot.
Thanks

**Comment by yigakpoa** [comment]
Thank you for your feedback.
