### ISSUE TITLE
UI fixes issue 

### ISSUE THREAD

**Issue by justankiit** [oppia/oppia-android#4963]
**Describe the bug**
In the " Topic: Places Values " Section where the Sentence is written " Stories You Can Play " is in White font color on Same White Background color , It Seems to look not Visible.

**Expected behavior**
,The font should be in Black color on White background Color

**Demonstration**
![Oppia](https://user-images.githubusercontent.com/111564362/235982765-389a0daa-860f-4e0c-9003-ac8ea93d5321.jpg)

**Environment**
- Device/emulator being used: <device version/emulator>
- Android or SDK version (e.g. Android 5 or SDK 21): 1.72.5
- App version:  0.10-beta-5e64fae55e

**Comment by Pankaj055** [comment]
unable to find "topic:place value". please help

**Comment by Pankaj055** [comment]
There is no issue as such in the app

**Comment by MohitGupta121** [comment]
This issue is already fixed in https://github.com/oppia/oppia-android/pull/4796
Thanks @Pankaj055
