### ISSUE TITLE
Right alignment of submitted answers looks wrong

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#499]
See:

![image](https://user-images.githubusercontent.com/12983742/69921798-b41a9d80-144a-11ea-939c-553b80f6108f.png)

and

![image](https://user-images.githubusercontent.com/12983742/69921810-c98fc780-144a-11ea-8bd6-c640bea537a8.png)

**Comment by veena14cs** [comment]
@BenHenning in the mock it is right justified https://xd.adobe.com/view/6384f092-e16a-4214-5a1a-f10ee0ef4f04-15b5/screen/b7069e13-ae14-44ca-ac1c-c96d43c8f3c4/PM-Q2-CA-Continue-

**Comment by veena14cs** [comment]
If it shouldn't be as per mock. This is how it looks.

![Screenshot_20191202-111247](https://user-images.githubusercontent.com/16301028/69933473-eb458900-14f4-11ea-9f33-46ed07131080.png)
![Screenshot_20191202-111348](https://user-images.githubusercontent.com/16301028/69933475-eda7e300-14f4-11ea-86bc-b76c330081ea.png)

**Comment by veena14cs** [comment]
Fixed this issue in PR #504 .
