### ISSUE TITLE
[Feature Request]: Header Text Not Readable On Mobile App In Dark Mode

### ISSUE THREAD

**Issue by rufaida99-k** [oppia/oppia-android#4998]
### Is your feature request related to a problem? Please describe.

I would like to suggest a new feature that would make our platform more accessible for all users. Currently, when a user clicks on a lesson, for instance, ‘Place Values’, some portion of the header as shown below “Stories You Can Play” is not immediately readable. It is white-colored text on a light grey background. 

### Describe the solution you'd like

We can just make the text color darker specifically for dark mode this this specific header. 

### Additional context

![Screenshot](https://user-images.githubusercontent.com/112827402/228610425-576fe014-796e-4aa2-a3ec-c79a336f934d.jpg)

**Comment by ShimpiTejas** [comment]
I want to Work on this, please assign this to me !
A pointer to the code segment would help

**Comment by seanlip** [comment]
@ShimpiTejas Per the guidance at https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue, please provide an explanation of what your PR will do (with names of files you're changing, what you plan to change in each file, etc.). If it looks good, we can assign you to this issue.

Please also follow the other instructions on that wiki page if you have not yet done so. Thanks!

**Comment by seanlip** [comment]
Moving this to oppia-android since this is an Android issue. @MohitGupta121 do you know if this has been addressed already?

**Comment by MohitGupta121** [comment]
@seanlip Yes, this issue is already fixed at initial stage of dark-mode. Only waiting for new release to rollout to reflect these changes in playstore app.

**Comment by seanlip** [comment]
OK thanks. Should we close it as fixed then? (If so, feel free to do that.)

**Comment by MohitGupta121** [comment]
Okay sure @seanlip.
This issue is fixed by https://github.com/oppia/oppia-android/pull/4796
Screenshots of fixed attach in PR description.
Thanks!
