### ISSUE TITLE
Add support for early exiting in the question player

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#501]
If a learner gets their first five answers correct on their first try, they should be able to end the question training session early. See mocks: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/ec286faf-3a4f-4779-984a-17ca470842e6/TM-EN-5-out-of-10-.

**Comment by rt4914** [comment]
In the mocks there is one line `It looks like you may need to revisit certain things.`
I think this line needs to be removed in this case.

**Comment by ChiragKalra** [comment]
I would like to work on this issue.

**Comment by rt4914** [comment]
@BenHenning Is this still valid issue?

**Comment by rt4914** [comment]
@ChiragKalra Suggest picking some other issue as it might be blocked on discussion.

**Comment by BenHenning** [comment]
See https://github.com/oppia/oppia-android/issues/502#issuecomment-1248915147.

**Comment by BenHenning** [comment]
The AI here is the remove the TODO and close this issue.
