### ISSUE TITLE
[BUG]: Images are not displayed for lesson cards in Division Topic

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#5026]
**Describe the bug**
Images are not displayed for lesson cards in Division Topic

**To Reproduce**
1. Go to 'Division'
2. Click on 'Nina Visits the Market'
3. Scroll down to the page to see images on each chapter card
4. See that there are no images except on the last card
5. Go back to Home page and see the Recently Played stories, see that no image is on What is Division card

**Expected behavior**
Images should be loaded properly as in web

**Demonstration**
![Screenshot_2023-06-07-23-35-44-21_943a62cb4c6fb83e010e1c2e82766a17](https://github.com/oppia/oppia-android/assets/101634267/7663baba-1b85-4c12-92b7-a239749427d2)

**Environment**
Device/emulator being used: Infinix SMART 5
Android or SDK version (e.g. Android 5 or SDK 21): Android 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.11-beta-8c81c98d8b

**Comment by seanlip** [comment]
This probably has the same cause as oppia/lessons-team#718

**Comment by BenHenning** [comment]
d3e2fd2ce3bcc9a5cdbe6fb577e4251ebfc80283 from oppia/oppia-android#4885 addresses this. The fixed lesson data will be included in the next beta RC.

**Comment by KolliAnitha** [comment]
Working fine in 0.11-beta-8e0fcf19ac.
![Screenshot_20230612-150320](https://github.com/oppia/oppia-android/assets/101634267/effd8f37-06e1-40b8-a50e-1163e04cdfb0)
