### ISSUE TITLE
[Localization][BUG]: Terms of Service and Privacy policy content is not translated to the translated language

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#5028]
**Describe the bug**
Terms of Service and Privacy policy content is not translated to the translated language

**To Reproduce**
1. Go to 'Home' - Options
2. Select App language as Arabic
3. Go back and click on Help - Terms of Service/ Privacy policy
4. See the content is not translated

**Expected behavior**
Content in it should be translated to the respective language

**Demonstration**
![Screenshot_20230608-080139](https://github.com/oppia/oppia-android/assets/101634267/d2ee703c-0526-42ca-9284-82e7c32da984)

**Environment**
Device/emulator being used: Infinix SMART 5
Android or SDK version (e.g. Android 5 or SDK 21): Android 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.11-beta-8c81c98d8b

**Comment by seanlip** [comment]
Closing -- we aren't planning to translate these two screens.
