### ISSUE TITLE
[BUG]: Arabic lessons are missing bullet points

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#5031]
**Describe the bug**
Bullet points are not rendering in Arabic (RTL) versions of the lessons.

**To Reproduce**

1. Download the 0.11-beta release.
2. Set the language of the app to Arabic.
3. Play the first card of Fractions 1. The first card is supposed to have bullet points, but they do not show up.

**Expected behavior**
The bullet points in the first card should be displayed in Arabic.

**Demonstration**

Note: There is also a missing image in Arabic. This is a separate issue that is being tracked in oppia/lessons-team#719.

| Arabic cards  | English cards  |
|---|---|
| ![Screenshot_20230608-191448](https://github.com/oppia/oppia-android/assets/10575562/77208a8d-4e22-40c0-8ae2-f09b826989e5)  |  ![Screenshot_20230608-191822](https://github.com/oppia/oppia-android/assets/10575562/7ce258ee-3b50-47c3-8b2f-b98a29586d86) | 

**Environment**
- Device/emulator being used: Moto device
- Android or SDK version (e.g. Android 5 or SDK 21): Android 8
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.11-beta-8c81c98d8b

**Comment by KolliAnitha** [comment]
Working fine in latest build 0.11-beta-8e0fcf19ac 

![subject (5)](https://github.com/oppia/oppia-android/assets/101634267/9a361979-1676-494a-b2b8-0f14fb6147ed)
