### ISSUE TITLE
[BUG]: Bullet lists aren't showing in FAQs for all non-English languages

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#5034]
**Describe the bug**
See title--keeping this short.

**To Reproduce**
1. Go to FAQ in any app language other than English
2. Open the second from the bottom item (help with audio).
3. Observe no bullets (as compared to English).

**Expected behavior**
There are supposed to be bullets.

**Demonstration**
English (don't mind the 10x-sized bullets, I'm currently debugging them):
![image](https://github.com/oppia/oppia-android/assets/12983742/216214fa-c703-481e-b0c4-91ccc5c0894b)

Swahili:
![image](https://github.com/oppia/oppia-android/assets/12983742/d30e572a-4809-4b98-b9e0-744c95a1382a)

**Environment**
- Device/emulator being used: Nexus 5X
- Android or SDK version (e.g. Android 5 or SDK 21): SDK 23
- App version (you can get this through system app settings or via the admin controls menu in-app): latest as of 8c81c98d8bdeaca167190b99df793efafa7cf9fd plus some local changes

**Additional context**
None.

**Comment by BenHenning** [comment]
I'm pretty sure this is because the FAQ answers are in CDATA blocks yet have escaped angle brackets--this is incorrect since CDATA preempts needing to escape (and, in fact, ignores escape sequences).

**Comment by BenHenning** [comment]
Actually, it's a bit interesting because the CDATA block itself seems to have been stripped from the translations, too (in which case the escaped tags are actually correct). It's a bit odd to me that this is happening.

**Comment by BenHenning** [comment]
Aha, this has nothing to do with CDATA. It appears that the list tags were stripped out during translations, so various \<ul\>s need to be re-added.

**Comment by BenHenning** [comment]
Unfortunately, this is a bit difficult for me to fix manually for each language, so it'd probably be better to fix this on the Translatewiki side by making sure that all HTML tags are kept & kept in the correct locations.

@seanlip could you follow up with the translators re: this?

**Comment by seanlip** [comment]
@BenHenning Could you please confirm that the format for the strings in the resources files are correct?

E.g. in Arabic it is:

https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/values-ar/strings.xml#L533

with the tags `&lt;p&gt;`. But in English it is:

https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/values/strings.xml#L579

with CDATA being used. Should the translated resource files also be using CDATA or is their current format fine?

(Also I noticed that [this conversation](https://github.com/oppia/oppia-android/pull/3852#discussion_r737154691) in #3852 was stated as fixed and marked as resolved, but the privacy_policy_web_link text does not seem to be fixed -- https://github.com/oppia/oppia-android/pull/3852/files#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103R532.)

**Comment by seanlip** [comment]
I've done a parsing of the strings (using the parser in https://gist.github.com/seanlip/6cb7678c612983cb94d0bf254855ca13) to identify the ones that need changing. There are 5 pt-br strings that are affected, 5 Arabic ones, 0 Nigerian Pidgin ones, and 6 Swahili ones.

My next step will be to both update the strings on translatewiki and also create a PR to push the updated strings to the Android repo.

**Comment by BenHenning** [comment]
They don't have to use CDATA @seanlip though that does make it easier for us to read. The problem here is that there are missing tags and it's a bit difficult for us to detect those without tooling (in the vain of the plans from #4562 though I'm not sure if that issue covers it all).

**Comment by seanlip** [comment]
Sorry, what image are you referring to?

Also, for future reference, we can probably use the parser in my previous comment as an interim tool (for future reference) until this becomes part of the CI checks.

**Comment by BenHenning** [comment]
Erm, I meant issue. :) Corrected the original comment.

**Comment by BenHenning** [comment]
NB: While #5040 fixes bullets in RTL, that fix shouldn't actually impact the FAQ bullets since they won't run into the bug (or, rather, they won't be affected by it sufficiently that they're fully cut off the screen).
