### ISSUE TITLE
[BUG]: Multiplication expression after submitting the answer is not seen in the response section

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#5052]
**Describe the bug**
Multiplication expression after submitting the answer is not seen in the response section

**To Reproduce**
1. Go to 'Multiplication' - Parts of Multiplication
2. Click on Continue till you reach the page with question 'Which multiplication expression could we use to find the total number of apples in these bags?'
3. Enter 4*3 and click on Submit
4. See that the response is blank 

**Expected behavior**
The response should have the multiplication expression entered

**Demonstration**
![Screenshot_20230612-191941](https://github.com/oppia/oppia-android/assets/101634267/6bcd4dff-5424-40f2-8934-a523d2d3e598)

**Environment**
Device/emulator being used: Infinix SMART 5
Android or SDK version (e.g. Android 5 or SDK 21): Android 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.11-beta-8e0fcf19ac

**Comment by adhiamboperes** [comment]
Hey @KolliAnitha, I am unable to reprduce this issue in either the beta release candidate or on my development build for any language. Could you please verify the repro steps? 

I did notice, however, some micro delay in loading.

|State with 5*5| State with 4*3|
|---|---|
|![Screenshot_1686668274](https://github.com/oppia/oppia-android/assets/59600948/33d3a747-8737-4521-ba67-f493c4c75648)|![Screenshot_1686668282](https://github.com/oppia/oppia-android/assets/59600948/2f12f921-990a-4b22-bc70-e3fcfd9d052e)|

**Comment by KolliAnitha** [comment]
Its working fine now. Hence closing the bug.
