### ISSUE TITLE
[Feature Request]: Add a "hint/solution viewed" event to complement the existing "offered"/"unlocked" events.

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#5069]
**Is your feature request related to a problem? Please describe.**
We currently have two events for each of hints and solutions, which state:
- When the hint/solution was first offered
- When the hint/solution was first unlocked

**Describe the solution you'd like**
The aim of this issue is to add a third "hint/solution viewed" event, to handle the case where the learner refers to a hint after initially unlocking it. Unlike the other two events, this event can trigger more than once for each hint/solution (the other two only trigger at most once in an "exploration session").

The first view of a hint/solution (immediately after it has been unlocked) should count as a view here.

If possible, it would be nice to also send the view_count with the "hint/solution viewed" event (e.g. is this the first view, the second view, the fifth view, etc.) but this is optional.

**Describe alternatives you've considered**
N/A

**Comment by Chandra-Mauli-Sharma** [comment]
@seanlip I would like to work on this. Can you please assign this issue to me.

**Comment by adhiamboperes** [comment]
@Chandra-Mauli-Sharma This issue does require a bit of knowledge about this code base, but if you can provide a brief description of how you would go about it, we can assign it to you.

My recommendation though, would be to pick an issue from [here](https://github.com/oppia/oppia-android/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) that is not currently assigned to someone.

**Comment by Vishwajith-Shettigar** [comment]
Hi @seanlip, can you please look at this screen recording and tell me if I am going right?

[hintandsolutionviews.webm](https://github.com/oppia/oppia-android/assets/76042077/c028a7e4-5089-4a9b-ae96-f7d7954312fa)

**Comment by adhiamboperes** [comment]
@Vishwajith-Shettigar, this LGTM.

**Comment by Vishwajith-Shettigar** [comment]
Thank you @adhiamboperes
