### ISSUE TITLE
[Feature Request]: Disable the submit button until an answer option is selected or an answer is typed

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#5070]
**Is your feature request related to a problem? Please describe.**

We've received some learner feedback that:
- The student did not understand that she is expected to tap on an answer option before she can proceed.
- The student did not understand that she is expected to input an answer in the input field. She was confused about not seeing the Continue button like in the previous cards.

**Describe the solution you'd like**

We plan to disable the Submit button until an answer/response is selected and provide "help text" to instruct the learner on what to do. Once the learner modifies the answer field, the Submit button should become active again.

Please see the [Mock up ](https://www.figma.com/proto/dHUz2vH8M0Tms4t0xwz3sj/Oppia-Anroid-App_HL?type=design&node-id=189-10117&scaling=min-zoom&page-id=1%3A17539&starting-point-node-id=189%3A10117&show-proto-sidebar=1) and the [Figma file](https://www.figma.com/file/dHUz2vH8M0Tms4t0xwz3sj/Oppia-Anroid-App_HL?type=design&node-id=1-17539&t=Y6WcnkfhuVIRBaCg-0) created by @Himali07, as well as [this design thread comment](https://github.com/oppia/design-team/issues/71#issuecomment-1581232000) for all the error messages.

This issue can be collaborated on by multiple contributors, by updating one interaction at a time. Here is the list of interactions:

- [ ] Number with units (e.g. 4 km)

- [x] Fraction input @masclot in https://github.com/oppia/oppia-android/pull/5224
- [x] Ratio input @theMr17 in https://github.com/oppia/oppia-android/pull/5263
- [x] Checkbox input @theMr17 https://github.com/oppia/oppia-android/pull/5319
- [x] Multiple choice input @theMr17 https://github.com/oppia/oppia-android/pull/5319
- [x] Math equation (e.g. 2x + 3y = 5) @Vishwajith-Shettigar https://github.com/oppia/oppia-android/pull/5317
- [x] Algebraic expression (e.g. 2x + 3y) @Vishwajith-Shettigar https://github.com/oppia/oppia-android/pull/5317
- [x] Number input @theMr17  https://github.com/oppia/oppia-android/pull/5310
- [x] Numeric expression (e.g. 5 + 2) @Vishwajith-Shettigar https://github.com/oppia/oppia-android/pull/5317
- [x] Text input @Vishwajith-Shettigar https://github.com/oppia/oppia-android/pull/5311
- [x] Click on image @Vishwajith-Shettigar https://github.com/oppia/oppia-android/pull/5316
- [x] Drag-and-drop sort @theMr17  https://github.com/oppia/oppia-android/pull/5323

**Comment by adityabarodiya** [comment]
I want to work on this issue. Please assign this issue to me.

**Comment by adityabarodiya** [comment]
can I work on this issue?

**Comment by adhiamboperes** [comment]
> can I work on this issue?

Hi @adityabarodiya, thanks for your interest in contributing at oppia-android. This issue requires a bit of context about interactions in the app, and I would suggest you start with a [good first issue](https://github.com/oppia/oppia-android/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) to farmiliarize. Could you please look at this: #3930

**Comment by BenHenning** [comment]
I think we need clarity from the product team here. The current the app already keeps the submit button disabled until an answer is selected. Should we be enabling it and then showing the requested errors for each interaction type if the submit button is clicked without an answer being entered?

**Comment by BenHenning** [comment]
@seanlip could you please provide context?

**Comment by seanlip** [comment]
Yup, the plan is to enable the button and show the requested errors for each interaction type if the submit button is clicked without an answer being entered. However, I'm going to adjust the impact of this to "low" since it looks like the button is already disabled until an answer is selected (so this is not as big an issue as it seems to have been before).

I think in the longer run, it would be good for this to match the behaviour on Web: https://github.com/oppia/oppia/pull/18379. The reason for this is that it is helpful to show a message to instruct the learner on what to do, but we can't do this when clicking on a disabled button for accessibility reasons (see https://github.com/oppia/design-team/issues/71#issuecomment-1570552877). So this seemed like the best option.

**Comment by masclot** [comment]
I created a draft PR #5197 for a single interaction: fraction interaction. It contains a demo with the UI changes. Please review and let me know if the direction is good; I will then finalize the PR with tests.
Once this PR is approved, I can also work on other interaction view models in separate PRs.

**Comment by theMr17** [comment]
Continuing with `Number input`.

**Comment by Vishwajith-Shettigar** [comment]
I would like to work on **Text input**.

**Comment by theMr17** [comment]
Continuing with **Selection Input** which includes both `Checkbox input` and `Multiple choice input`.

**Comment by Vishwajith-Shettigar** [comment]
Working on **Click on image**.

**Comment by Vishwajith-Shettigar** [comment]
Working on **MathExpressionInteractionsView**, which includes Math equation, Algebraic expression, Numeric expression.

**Comment by theMr17** [comment]
Continuing with `Drag-and-drop sort`.

**Comment by Vishwajith-Shettigar** [comment]
Going with **Number with units**

**Comment by Vishwajith-Shettigar** [comment]
Can anybody help me find the topic where `Number with units` is discussed on the app?

**Comment by Vishwajith-Shettigar** [comment]
Can anybody help me find the topic where `Number with units` is discussed in the app?

**Comment by theMr17** [comment]
> Can anybody help me find the topic where `Number with units` is discussed in the app?

Hi @Vishwajith-Shettigar, I did a bit of searching in the codebase. I believe **NumberWithUnitsInteractionView** is not yet implemented in the app as per issue https://github.com/oppia/oppia-android/issues/30.

**Comment by Vishwajith-Shettigar** [comment]
> Hi @Vishwajith-Shettigar, I did a bit of searching in the codebase. I believe **NumberWithUnitsInteractionView** is not yet implemented in the app as per issue #30.

Great finding, thank you.

**Comment by adhiamboperes** [comment]
@seanlip, FYI for product--this issue has been addressed with the exception of number with units, which we currently don't have in the app.

**Comment by adhiamboperes** [comment]
This has been fully implemented except `Number with units (e.g. 4 km)` which we currently do not have in the beta assets.

Moving to backlog.

**Comment by adhiamboperes** [comment]
Marking as complete because we don't have number with units yet.
