### ISSUE TITLE
[BUG]: CI Check for color usage in vectors will never pass until minSdk is updated

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5072]
### Describe the bug

File Content Validation CI check that prohibits usages of colors other than component_colors in drawable files fails correctly on CI when violated, but the pattern that is being enforced cannot be supported by our current codebase, since we have not yet removed support for kitkat.

The CI error is:
```
app/src/main/res/drawable/rounded_primary_button_grey_shadow_color.xml:5: Only colors from component_colors.xml may be used in drawables except vector assets.
app/src/main/res/drawable/survey_nps_radio_selected_color.xml:4: Only colors from component_colors.xml may be used in drawables except vector assets.
app/src/main/res/drawable/survey_nps_radio_selected_color.xml:8: Only colors from component_colors.xml may be used in drawables except vector assets.
app/src/main/res/drawable/survey_nps_radio_unselected_color.xml:4: Only colors from component_colors.xml may be used in drawables except vector assets.
app/src/main/res/drawable/survey_nps_radio_unselected_color.xml:8: Only colors from component_colors.xml may be used in drawables except vector assets.
app/src/main/res/values/color_palette.xml:256: All color declarations in component_color.xml and color_palette.xml should end with _color suffix following snake_case naming convention.
```

Upon applying the recommended fix, the project build fails with error:
```
Cause 1: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
	...
Caused by: java.lang.RuntimeException: Error while processing /Users/adhiambooyier/opensource/oppia-android/app/src/main/res/drawable/survey_nps_radio_selected_color.xml : Can't process attribute android:fillColor="@color/component_color_survey_primary_button_background_color": references to other resources are not supported by build-time PNG generation.
File was preprocessed as vector drawable support was added in Android 5.0 (API level 21)
See http://developer.android.com/tools/help/vector-asset-studio.html for details.
.android.ide.common.resources.MergedResourceWriter$FileGenerationWorkAction.run(MergedResourceWriter.java:412)
	... 34 more
```

### Steps To Reproduce

In any vector file in res/drawable, replace a `<path>` tag `fillColor` attribute color hex (e.g. #ffffff) with a color resource (e.g. @color/component_color_shared_screen_secondary_background_color) and then rebuild the app.

### Expected Behavior

I expect the project to build without errors.

### Screenshots/Videos

![Screenshot 2023-06-27 at 05 24 29](https://github.com/oppia/oppia-android/assets/59600948/5af99b96-9ff2-401e-943e-fc4235e4ebc8)

### Additional Context

This  check was introduced in #4960

**Comment by adhiamboperes** [comment]
Hi @MohitGupta121, could you please take a look at disabling this CI check as it blocks my PR? Additionally, could you please also file a seperate issue that tracks adding that check back once we deprecate support for kitkat?

**Comment by MohitGupta121** [comment]
@adhiamboperes one solution is to add those failing files in the exempted test. After that KitKat thing is done we can remove that. Can I do this in the new PR or are you doing it in your PR?

**Comment by adhiamboperes** [comment]
I don't know whether exempting files is a robust solution, since I cannot say when KitKat deprecation will be prioritized. Could you give me a rough estimate of how much work it would be to disable the check (are tests involved, are there potential breakages) vs the exemption solution. I think it is fine to go with the simplest solution here.
In case of adding the files to exemptions, I will do it in my PR since they are new resources being introduced in that PR.

**Comment by MohitGupta121** [comment]
@adhiamboperes disabling the tests means removing the condition regex for drawables.

**Comment by adhiamboperes** [comment]
Do you estimate that it will involve a lot of work to remove it?

**Comment by MohitGupta121** [comment]
No it take few lines change

**Comment by adhiamboperes** [comment]
I would prefer that we go with that solution. Could you please put up a PR for that?

**Comment by MohitGupta121** [comment]
@adhiamboperes okay sure today I'll make PR.
