### ISSUE TITLE
[BUG]: Gradle Build Failed - Task :utility:kaptGenerateStubsDebugKotlin FAILED

### ISSUE THREAD

**Issue by MohitGupta121** [oppia/oppia-android#5079]
### Describe the bug

New contributors try to build oppia-android getting this error:

### Error Log

```bash
> Task :utility:kaptGenerateStubsDebugKotlin FAILED
Execution failed for task ':utility:kaptGenerateStubsDebugKotlin'.
> Could not resolve all files for configuration ':utility:debugCompileClasspath'.
   > Failed to transform model.jar (project :model) to match attributes {artifactType=android-classes, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=15, org.gradle.libraryelements=jar, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: E:\Android\open-source\oppia-android\model\build\libs\model.jar.
         > Failed to transform 'E:\Android\open-source\oppia-android\model\build\libs\model.jar' using Jetifier. Reason: Unsupported class file major version 59. (Run with --stacktrace for more details.)
```

### Steps To Reproduce

1. Clone oppia-android
2. Run gradle build 1st time in Android studio

### Expected Behavior

Gradle build successful

**Comment by Abinash6000** [comment]
Just wanted to let you know that I had the exact same error. 
The solution was suggested by android studio itself. (below image)
![image](https://github.com/oppia/oppia-android/assets/110354418/a20730db-619a-46fa-bf6d-36ae4d2b84ce)
When I clicked on `Insert JDK8 language level directives`. This added the following lines to `build.gradle(:model)`
```
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
```
Hope it helps.

**Comment by MohitGupta121** [comment]
Thanks @Abinash6000, I think @adhiamboperes is working on this issue. So it helpful to her.

**Comment by theMr17** [comment]
@adhiamboperes I was having the same issue, but it got fixed by following [this](https://github.com/oppia/oppia-android/issues/5079#issuecomment-1645812143). Can I create a PR on this, if you are not working on this issue ?

> Just wanted to let you know that I had the exact same error. The solution was suggested by android studio itself. (below image) ![image](https://user-images.githubusercontent.com/110354418/255225125-a20730db-619a-46fa-bf6d-36ae4d2b84ce.png) When I clicked on `Insert JDK8 language level directives`. This added the following lines to `build.gradle(:model)`
> 
> ```
> java {
>     sourceCompatibility = JavaVersion.VERSION_1_8
>     targetCompatibility = JavaVersion.VERSION_1_8
> }
> ```
> 
> Hope it helps.

**Comment by adhiamboperes** [comment]
@the-mr17, I think it would be okay.
