### ISSUE TITLE
[BUG]: Bazel build failed in mac m1 

### ISSUE THREAD

**Issue by MohitGupta121** [oppia/oppia-android#5094]
### Describe the bug

This bug is faced by me when I updated my Mac OS from Monterey to Ventura, I got this error while building Bazel:

```
ERROR: /Users/OpenSource/oppia-android/model/src/main/proto/BUILD.bazel:167:20: Generating JavaLite proto_library //model/src/main/proto:profile_proto failed: (Segmentation fault): protoc failed: error executing command bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc '--proto_path=bazel-out/android-armeabi-v7a-fastbuild/bin/model/src/main/proto/_virtual_imports/languages_proto' ... (remaining 8 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox protoc failed: error executing command bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc '--proto_path=bazel-out/android-armeabi-v7a-fastbuild/bin/model/src/main/proto/_virtual_imports/languages_proto' ... (remaining 8 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Target //:oppia failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 70.242s, Critical Path: 12.83s
INFO: 282 processes: 21 internal, 261 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

### Describe the solution you'd like

The solution that I found is when we update Mac OS to  Ventura then some Xcode terms changed and some setup files is missing for that we have to mannually install again that files and accept the terms.

So here the steps that I thinking to add into wiki as solution of this bug:

  ```
   xcode-select --install
   sudo xcodebuild -licence
   sudo xcode-select -r 
   sudo xcode-select -s /Library/Developer/CommandLineTools
   xcode-select -p 
  ```
After this Build bazel with this command:

```
bazel clean --expunge
bazel build //:oppia --noexperimental_check_desugar_deps
```

### Steps To Reproduce

1. Setup Bazel in Mac OS M1 - version Ventura 
2. Run Bazel build command

### Expected Behavior

Bazel build successful

**Comment by MohitGupta121** [comment]
@kkmurerwa @adhiamboperes PTAL on the issue desciption, please suggest if something need change or add. Thanks!

**Comment by kkmurerwa** [comment]
Hi @MohitGupta121. The issue looks good. It is similar to issue #4391 and PR #5111 should be able to fix it. I think I can reference this issue as well in my PR. What do you think @adhiamboperes?

**Comment by adhiamboperes** [comment]
Hey @kkmurerwa, yes, you can reference this issue in your PR. However, it is not a full fix.

Can you both @kkmurerwa and @MohitGupta121 add your MacOs and Xcode versions to the issues for further debugging?

**Comment by adhiamboperes** [comment]
@MohitGupta121, thanks for proposing these steps. I think it is okay to incorporate them into the setup instructions for Mac.

**Comment by kkmurerwa** [comment]
@adhiamboperes I see. It would need a change to the Wiki to be a full fix. I will add part of so that it can be easily referenced. You can add Mohit's suggestions as part of your ongoing fixes for the Wiki.

**Comment by MohitGupta121** [comment]
Okay Thanks @kkmurerwa @adhiamboperes

**Comment by MohitGupta121** [comment]
@kkmurerwa or we can also mention the error here in a section of wiki [Bazel-Issues](https://github.com/oppia/oppia-android/wiki/Troubleshooting-Installation#bazel-issues). What do you think?
