### ISSUE TITLE
[Feature Request]: Reorganize the Project Setup Documentation

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5099]
### Is your feature request related to a problem? Please describe.

Many new contributors run into issues setting up the project, especially on a Windows SDE. Having run tthrough the setup instructions myself, I noticed that while all the information needed to setup is present, a bit of reorganization would be useful to minimize skipping some important setup steps, which will in turn minimize the number of reported setup issues.

Some problems I noticed with the current instructions are:
- The [main setup page](https://github.com/oppia/oppia-android/wiki/Installing-Oppia-Android) contains instructions for setting up the development environment for all the OSes together with a number of external links. This means contributors have to keep going back and forth between tabs, and may lose their place, which often results into skipping steps.
- The current setup steps advise to install the latest Android Studio version, but our project does not support the latest gradle  versions bundled with newer IDE versions.
- Steps [2 and 3 ](https://github.com/oppia/oppia-android/wiki/Installing-Oppia-Android#prepare-developer-environment)of the setup instructions involve setting up Java 8. This is not an actual pre-requisite to getting the project running, yet it is a non-trivial task. Android Studio comes with its own embedded JDK, and it is possible to install additional versions from within the IDE if needed. Our project can build on gradle with JDKs 8-11, which are sufficient for getting started on a first issue.
- In relation to the JDK step above, there are missing instructions on specifying the compile jdk version from within Android studio --- even if you set the java home variable, Android Studio defaults to its embedded jdk.
- Most contributors never run the `bash setup.sh` command, missing out on important pre-push checks.

### Describe the solution you'd like

I do think that, pre full bazel migration, we should allow our contributors to get started with just gradle as this lowers the barriers to start contributing. Most of the starter issues for the foreseable future do not need interaction with Bazel.

Some changes we can make to improve the setup Wiki:
- From the onset, split the setup instructions per OS. This means that the [first page](https://github.com/oppia/oppia-android/wiki/Installing-Oppia-Android#prepare-developer-environment) of setup instructions will have a format like this:
   ```
    - Select your operating system to get the setup instructions:
       - Linux
       - Windows
       - MacOs
    ```
Then on each OSs page, we will have the complete OS specific setup instructions, numbered.
- Update the required Android Studio Version instructions to Bumblee Bee Patch 3 ([direct  download url)](https://redirector.gvt1.com/edgedl/android/studio/install/2021.1.1.23/android-studio-2021.1.1.23-windows.exe)
- Move the Java 8 and `$JAVA_HOME` setup instructions to the Bazel set up section on each page, since they are only relevant there.
- Add instructions on how to select the compile JDK from within Android Studio Settings.
- Update outdated instructions related to SDK path in Android studio and that of downloading the `google files check` file. 
- Include a post-setup checklist to verify all the setup steps have been completed. 

### Describe alternatives you've considered

- Adding instructions about common set up issues, their causes and how to fix them.

This option is reactive rather than preventive.

We can still however have a section for this, especially for issues that cannot be prevented such as https://github.com/oppia/oppia-android/discussions/4966#discussioncomment-6524813.

### Additional context

https://github.com/oppia/oppia-android/discussions/5061

https://github.com/oppia/oppia-android/discussions/4858

https://github.com/oppia/oppia-android/discussions/4432

**Comment by adhiamboperes** [comment]
@seanlip, @MohitGupta121, could you please review my suggested Wiki updatates and let me know your thoughts?

**Comment by MohitGupta121** [comment]
@adhiamboperes Thanks that's a very great issue. We have to complete this as High Priority as per my suggestions because now in the upcoming months, many new GSOC contributors are coming. So we have to solve and document all setup instructions properly.

**Comment by adhiamboperes** [comment]
> @adhiamboperes Hey, are you working on this issue or we both work on this issue? What do you suggest?

Hey @MohitGupta121, I will take the lead on this to set up the format that I have in mind.

**Comment by MohitGupta121** [comment]
Okay, Thanks @adhiamboperes LGTM. These changes were very helpful to Windows users as most of them facing these issues. let's see what's @seanlip thoughts are to improve it more.

**Comment by seanlip** [comment]
All this sounds good to me. Let's please go ahead with it. Thanks @adhiamboperes!

**Comment by kkmurerwa** [comment]
Hi @adhiamboperes. In your update be sure to include setting JDK 11 as the default compile JDK on Android Studio since the project has trouble compiling with any other JDK.
