### ISSUE TITLE
[BUG]: TopicActivity Has Dark Mode Inconsistencies in Large Screens

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5119]
### Describe the bug

In large screen devices/tablets, the `Topic` screen shows an incorrect color for both `Topic` and `Revision` tabs.

![Screenshot_1690497871](https://github.com/oppia/oppia-android/assets/59600948/b51715e9-3159-4cd2-aa39-6fca1966b52b)

![Screenshot_1690497898](https://github.com/oppia/oppia-android/assets/59600948/4d9248a7-c17b-4d4b-b35e-a7b9126d3367)

![Screenshot_1690497901](https://github.com/oppia/oppia-android/assets/59600948/9ca0ce74-6388-42b5-85f3-8e4cd5b887e7)

### Steps To Reproduce

1. Install Oppia on a real tablet or emulator such as a `Nexus 9` device.
2. On a profile home screen, click on any topic.
3. On the topic list screen, see that the viewpager color is not Oppia green.
4. Switch to the *Revision* tab and observe the same outcome.

### Expected Behavior

The color should be consistent with the toolbar color above it, as seen in small screen layouts in the screenshot below:

![Screenshot_1691302060](https://github.com/oppia/oppia-android/assets/59600948/71bc0502-78f2-4c6d-8d8f-d2b8d7bc1f2b)

### What device/emulator are you using?

Nexus 9 emulator

### Which Android version is your device/emulator running?

Android 10

### Which version of the Oppia Android app are you using?

Developer build

**Comment by MohitGupta121** [comment]
@adhiamboperes if it's urgent can I make PR?

**Comment by adhiamboperes** [comment]
Hi @MohitGupta121, the impact here is low, let's keep this as a good first issue for new contributors.

**Comment by ShubhadeepKarmakar** [comment]
Hey, @adhiamboperes can you assign it to me?

**Comment by adhiamboperes** [comment]
> Hey, @adhiamboperes can you assign it to me?

Sure, do you have an idea of how to go about it? Please describe it here. In case you need some help, we have a section on our wiki about [working with dark mode](https://github.com/oppia/oppia-android/wiki/Dark-Mode), but feel free to ask questions.

**Comment by ShubhadeepKarmakar** [comment]
I think this is not a color_palette.xml or night/color_palette.xml related issue.

If you're working with a tab layout and want to differentiate the appearance of the tabs from the overall background, you should use **app:tabBackground**. If you want to set the background for an entire view or layout, you should use **android:background**. 
And thats the issue.

After changing the attribute app:tabBackground to android:background the problem will be solved.
![doneeee](https://github.com/oppia/oppia-android/assets/99060332/737866d8-dcf0-4425-bf67-7a62c313b014)

Would I make a PR @adhiamboperes?

**Comment by adhiamboperes** [comment]
> I think this is not a color_palette.xml or night/color_palette.xml related issue.
> 
> If you're working with a tab layout and want to differentiate the appearance of the tabs from the overall background, you should use **app:tabBackground**. If you want to set the background for an entire view or layout, you should use **android:background**. And thats the issue.
> 
> After changing the attribute app:tabBackground to android:background the problem will be solved. ![doneeee](https://user-images.githubusercontent.com/99060332/259403329-737866d8-dcf0-4425-bf67-7a62c313b014.png)
> 
> Would I make a PR @adhiamboperes?


Okay,  but does this fix the issue for landscape, tablet and small screens as well?

**Comment by ShubhadeepKarmakar** [comment]
Yeah

**Comment by ShubhadeepKarmakar** [comment]
@adhiamboperes am I going the right way?
