### ISSUE TITLE
Itemselection Interaction allows to submit answer when no any selection is done.

### ISSUE THREAD

**Issue by veena14cs** [oppia/oppia-android#512]
![Screenshot_20191204-161436](https://user-images.githubusercontent.com/16301028/70140373-918ebb80-16ba-11ea-9fd1-c9c54eb5cdab.png)

![Screenshot_20191204-161312](https://user-images.githubusercontent.com/16301028/70140181-2cd36100-16ba-11ea-9f19-4999593b9f25.png)

**Comment by rt4914** [comment]
This has been finished as a part of https://github.com/oppia/oppia-android/pull/1330
