### ISSUE TITLE
In Some explorations expressions are missing.

### ISSUE THREAD

**Issue by veena14cs** [oppia/oppia-android#513]
In "Meaning of Equal Parts" exploration, mathematical expression is not present or its a LaTeX expression, which makes question or explanation unclear. May be this was fixed in #458.

![Screenshot_20191204-160515](https://user-images.githubusercontent.com/16301028/70140667-3f01cf00-16bb-11ea-9f06-81d1f5607c89.png)
![Screenshot_20191204-160733](https://user-images.githubusercontent.com/16301028/70140686-4b862780-16bb-11ea-8fd7-61b1699683c9.png)

**Comment by rt4914** [comment]
@veena14cs yes you are correct.
Web screenshot
<img width="539" alt="Screenshot 2019-12-04 at 7 13 07 PM" src="https://user-images.githubusercontent.com/9396084/70147428-31077a80-16ca-11ea-99c4-1b4cbfd135f6.png">

**Comment by BenHenning** [comment]
This should work once LaTeX is properly sent as an SVG from the backend.
