### ISSUE TITLE
[Feature Request]: Remove all-caps for all buttons on Android app and change to sentence case

### ISSUE THREAD

**Issue by jlevick** [oppia/oppia-android#5136]
### Is your feature request related to a problem? Please describe.

We are currently using all-caps for buttons (ex: CONTINUE, CANCEL) and the UX writing team, with the approval of the Android design team leads, would like to move forward with changing to sentence case (ex: Continue, Cancel, Ok, Submit, Close, Skip). **This is for all buttons on the app.** 
Please see the updated Android style guide: 

https://www.figma.com/file/G0jHrMaopFzk2ZksuynBjS/Android-style-guide?type=design&node-id=2-8412&mode=design&t=7wp6FDWE94kPhUVw-0

### Describe the solution you'd like

Changing all-caps buttons to sentence case for all buttons on the Android app. Thank you!

### Additional context

If there is confusion on a specific button, please reach out to @jlevick.

**Comment by AbhishekPSingh07** [comment]
Can I work on this Issue

**Comment by jlevick** [comment]
Hi @seanlip! Just confirming if I need to do anything else for this? Thank you!

**Comment by seanlip** [comment]
@jlevick No, I think what you've written is fine. Thanks!

@AbhishekPSingh07 (or anyone else who'd like to take this up) -- per the guidance at https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android#3-pick-your-first-starter-issue, please provide an explanation of what your PR will do (with names of files you're changing, what you plan to change in each file, etc.). If it looks good, we can assign you to this issue. Please also follow the other instructions on that wiki page if you have not yet done so. Thanks!

**Comment by theMr17** [comment]
Hi @seanlip, I'd like to tackle this issue. I'll search for all button elements in the codebase and update `android:textAllCaps` to `false`. Will work on files which contains the button layouts. Thanks!

**Comment by adhiamboperes** [comment]
> Hi @seanlip, I'd like to tackle this issue. I'll search for all button elements in the codebase and update `android:textAllCaps` to `false`. Will work on files which contains the button layouts. Thanks!

Hi,
The first step in resolving this is to make a list of all the buttons that we have that arr in all caps.
Can you do that and add it as a comment here. Please Indicate the screen/dialog.

**Comment by theMr17** [comment]
@adhiamboperes Here is the list of all buttons in the app that are currently in all caps.

# _layout_

|Screen / Dialog|Button ID|
|--|--|
|`activity_input_interaction_view_test.xml`|`submit_button`|
|`add_profile_activity.xml`|`add_profile_activity_create_button`|
|`admin_auth_activity.xml`|`admin_auth_submit_button`|
|`admin_pin_activity.xml`|`submit_button`|
|`concept_card_fragment_test_activity.xml`|`open_dialog_0` `open_dialog_1`|
|`exploration_test_activity.xml`|`play_exploration_button`|
|`hint_summary.xml`|`reveal_hint_button`|
|`math_expression_parser_fragment.xml`|`parse_math_expression_button`|
|`onboarding_slide_final.xml`|`get_started_button`|
|`profile_list_control_buttons.xml`|`learner_analytics_share_ids_and_events_button` `learner_analytics_upload_logs_now_button`|
|`profile_rename_fragment.xml`|`profile_rename_save_button`|
|`profile_reset_pin_fragment.xml`|`profile_reset_save_button`|
|`replay_button_item.xml`|`replay_button`|
|`return_to_lesson_button_item.xml`|`return_to_lesson_button`|
|`return_to_topic_button_item.xml`|`return_to_topic_button`|
|`solution_summary.xml`|`show_solution_button`|
|`state_fragment_test_activity.xml`|`play_test_exploration_button`|
|`submit_button_item.xml`|`submit_answer_button`|
|`topic_practice_footer_view.xml`|`topic_practice_start_button`|
|`walkthrough_welcome_fragment.xml`|`walkthrough_welcome_next_button`|

# _layout-land_
|Screen / Dialog|Button ID|
|--|--|
|`onboarding_slide_final.xml`|`get_started_button`|
|`walkthrough_welcome_fragment.xml`|`walkthrough_welcome_next_button`|

# _layout-sw600dp-land_
|Screen / Dialog|Button ID|
|--|--|
|`onboarding_slide_final.xml`|`get_started_button`|

# _layout-sw600dp-port_
|Screen / Dialog|Button ID|
|--|--|
|`onboarding_slide_final.xml`|`get_started_button`|

**Comment by adhiamboperes** [comment]
Thanks @the-mr17.  Looks good, you can put up a PR for this.
