### ISSUE TITLE
[BUG]: Edit text foreground and background contrast ratio issue in Light mode

### ISSUE THREAD

**Issue by Vishwajith-Shettigar** [oppia/oppia-android#5142]
### Describe the bug

 Edit text foreground and background contrast ratio issue in admin_pin_activity

### Steps To Reproduce

1. Click on set up Multiple Profiles.
2. Edit text has accessibility issue (foreground and background contrast ratio issue) in light mode.

### Expected Behavior

Accessability scanner should not show accessability issue for Edit text.

### Screenshots/Videos

![afterlightmode](https://github.com/oppia/oppia-android/assets/76042077/528add56-0ed6-49dd-8c6d-68fc9b1a8e72)

**Comment by Vishwajith-Shettigar** [comment]
Can I work on this issue ?

**Comment by adhiamboperes** [comment]
> Can I work on this issue ? 


Yes. I'm assigning it to you

**Comment by Vishwajith-Shettigar** [comment]
> > Can I work on this issue ?
> 
> Yes. I'm assigning it to you

Thank you
