### ISSUE TITLE
[Feature Request]: Display some kind of loading animation/graphic when topics are loading in Home Page

### ISSUE THREAD

**Issue by theMr17** [oppia/oppia-android#5170]
### Is your feature request related to a problem? Please describe.

A loading bar would be good to indicate the user that the topics are being loaded on the home page.

### Describe the solution you'd like

I would like to have a simple indeterminate circular progress at the center of the screen when the topics are loading.

### Additional context

https://github.com/oppia/oppia-android/assets/84731134/11e91377-6da3-45ee-8764-030c59bc375a

**Comment by Vishwajith-Shettigar** [comment]
i have made a draft PR oppia/oppia-android#5167 for this feature request.
@adhiamboperes Could you please take a look at this?

**Comment by adhiamboperes** [comment]
> i have made a draft PR oppia/oppia-android#5167 for this feature request. @adhiamboperes Could you please take a look at this?


We don't have loading progressbars in our current [design system,](https://www.figma.com/file/G0jHrMaopFzk2ZksuynBjS/Android-style-guide?type=design&node-id=2-8412&mode=design&t=3OmIhr4GvoecNpBu-0) so I don't think we can add a solution for this without product and design team input, to decide whether we want this in the first place.

**Comment by adhiamboperes** [comment]
@seanlip, PTAL for product.

**Comment by seanlip** [comment]
This needs design input. Moving it to the design team, thanks for the suggestion @the-mr17.

**Comment by seanlip** [comment]
Note to design team ( /cc @jiwonc26 ) -- @Vishwajith-Shettigar made a PR with this fix:

https://github.com/oppia/oppia-android/assets/76042077/b0c8f4cc-b5c5-4122-b5a0-d779ee652493

What do you think about it?

**Comment by jiwonc26** [comment]
> Note to design team ( /cc @jiwonc26 ) -- @Vishwajith-Shettigar made a PR with this fix:
> 
>  Record_2023-10-01-22-53-42_943a62cb4c6fb83e010e1c2e82766a17.mp4 
> 
> What do you think about it?

I like this! Looks def better

**Comment by seanlip** [comment]
OK, thanks! Moving this back to the oppia-android repo then since the proposed solution looks good to the design team.
