### ISSUE TITLE
BUG: Fix All warnings in "Accessibility" category

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5171]
## Description 
 We would like to fix all the remaining lint issues on Oppia Android in "Accessibility" category.

## Steps To Reproduce
Run the following command from a terminal in a checked-out Oppia Android repo:

`./gradlew :app:lint`

Output:  All warnings in "Accessibility" category

Under this category, the warnings are mainly of 3 types.

**Warning: Image without contentDescription.**
Fix: Add a contentDescription to each of those ImageView, or android:importantForAccessibility="no" for views that are safe to ignore.

**Warning: 'onTouch' lambda should call 'View#performClick' when a click is detected**
Fix: Call customView.performClick( ).

**Warning: 'clickable' attribute found, please also add 'focusable'.**
Fix: Set android:focusable="true" to allow keyboard navigation per: https://android.googlesource.com/platform/tools/base/+/studio-master-dev/lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks/KeyboardNavigationDetector.java?autodive=0%2F.

## Expected Behavior
Running the command above should not show any errors.

**Comment by adhiamboperes** [comment]
@the-mr17, PTAL.

**Comment by adhiamboperes** [comment]
@the-mr17, could you also please fill this out: https://docs.google.com/forms/d/e/1FAIpQLSes4wj7oKtiN0iyUwd-Xt_DAOr1b-MHG9_YYIavWBF4G6g8uA/viewform

**Comment by theMr17** [comment]
> @the-mr17, could you also please fill this out: https://docs.google.com/forms/d/e/1FAIpQLSes4wj7oKtiN0iyUwd-Xt_DAOr1b-MHG9_YYIavWBF4G6g8uA/viewform

@adhiamboperes Sure, But I have some queries regarding this:
1. Here, it asks me to provide links of PRs merged on `Oppia Web` repo and also mentions about the teams in `Oppia Web`. Can you please clarify this?

    <img src="https://github.com/oppia/oppia-android/assets/84731134/6bd3e4c4-17d9-4d85-9233-133c1983cb39" height="400" />

2. Will it be okay if I am not able to join team meetings, incase I am committed to some other work at that time?

    <img src="https://github.com/oppia/oppia-android/assets/84731134/9d6d5a12-a6d1-402c-b2fb-f93e75951ed5" height="150">

**Comment by MohitGupta121** [comment]
@the-mr17 if you select oppia-android then it give right section.
And be sure you filled this [form](https://goo.gl/forms/otv30JV3Ihv0dT3C3) also before collaborator form. Thanks!

**Comment by seanlip** [comment]
Sorry -- the form was incorrectly configured, if you refresh it it should show you the Android section now.
