### ISSUE TITLE
All warnings in "Internationalization" and "Internationalization:Bidirectional Text" category

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5182]
## Description 
 We would like to fix all the remaining lint issues on Oppia Android in "Internationalization" category.

## Steps To Reproduce
Run the following command from a terminal in a checked-out Oppia Android repo:

`./gradlew :app:lint`

Output:  All warnings in "Internationalization" category

## Expected Behavior
Running the command above should not show any errors.

**Comment by adhiamboperes** [comment]
@Rd4dev, PTAL. 
 
The approach you have suggested in https://github.com/Rd4dev/oppia-android/commit/9e47b96bbdc24e6d128a3b2a3b38f1b633ac522b sounds good, but we need to work on the naming of the strings. Consider using a pattern that follows `stringname_stringtype`, e.g. `concept_card_two_button_text`

**Comment by Rd4dev** [comment]
Thank you for the initial review @adhiamboperes. I have made modifications to certain `string resources` to enhance their clarity in terms of data type. However, I have retained the `title` and `hint variables` in their existing state. If it is deemed necessary, I will make the adjustments to them as well, based on any suggestions provided.
