### ISSUE TITLE
[BUG]: Textview contrast issue in locked lesson 

### ISSUE THREAD

**Issue by Vishwajith-Shettigar** [oppia/oppia-android#5187]
### Describe the bug

Text and background contrast ratio issue

### Steps To Reproduce

1. Select any topic
2. Use accessibility scanner 

### Expected Behavior

Accessibility scanner should not show any suggestions

### Screenshots/Videos

![testdark](https://github.com/oppia/oppia-android/assets/76042077/9eb031a1-ed7e-472e-98ab-adc65003756a)

![textcontrast](https://github.com/oppia/oppia-android/assets/76042077/13e8b94a-37d2-42dc-901f-f06348eeb7ec)

**Comment by Tejas-67** [comment]
Hey @Vishwajith-Shettigar , I would like to work on this issue if still open.

**Comment by adhiamboperes** [comment]
> Hey @Vishwajith-Shettigar , I would like to work on this issue if still open.

This issue is assigned and has an open pull request. Please pick another issue

**Comment by Vishwajith-Shettigar** [comment]
> Hey @Vishwajith-Shettigar , I would like to work on this issue if still open.

Hey @Tejas-67, as @adhiamboperes mentioned, there is an open PR. Please proceed with other issue.
