### ISSUE TITLE
All warnings in "Usability:Typography", "Usability:Icons", and "Usability" categories

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5194]
## Description
We would like to fix all the remaining lint issues on Oppia Android in the "Usability:Typography", "Usability:Icons", and "Usability" categories.

## Steps To Reproduce
Run the following command from a terminal in a checked-out Oppia Android repo:

./gradlew :app:lint

## Expected Behavior
Running the command above should not show any errors in this category

**Comment by adhiamboperes** [comment]
@Rd4dev, per https://github.com/oppia/oppia-android/issues/5169#issuecomment-1763510504, could you please list some of the borderless buttons that need to be changed? We can consider creating a theme or a style that is applied globally.

For text capitalization, we use sentence case in buttons, not lowercase or uppercase.

**Comment by adhiamboperes** [comment]
@BenHenning, do we want to create per hdpi image assets for this repository? see commit: https://github.com/Rd4dev/oppia-android/commit/f6b21febe328fbd434ac43900ce327ca2e61ddfe? If not, we need to supress this lint check. 

I am also concerned that replacing ... and - instances in Arabic translations with unicode may make it difficult for translators to understand the strings.

**Comment by Rd4dev** [comment]
@adhiamboperes The warning about the borderless button emerged in the [**XML File**](https://github.com/Rd4dev/oppia-android/blob/69d2b822ae1e3287447d4e031088dca95b682ca4/app/src/main/res/layout/concept_card_fragment_test_activity.xml) -> `concept_card_fragment_test_activity.xml`, for the two buttons with IDs `open_dialog_0` and `open_dialog_1`. If recommended, I can work on a separate theme or style for these buttons and incorporate them instead.

The lint warning regarding capitalization suggested that the standard Android convention for "Ok" is "OK" (tip: use '@android:string/ok' instead). In accordance with the sentence case used in oppia-android's coding practices, I can suppress this warning by using the following code snippet:
`<string name="audio_language_select_dialog_okay_button" tools:ignore="ButtonCase,Typos">Ok</string>`

**Comment by adhiamboperes** [comment]
Since the buttons here are test class buttons, your original proposed approach should be okay...no need to theme them.

**Comment by BenHenning** [comment]
> @BenHenning, do we want to create per hdpi image assets for this repository? [Rd4dev@f6b21fe](https://github.com/Rd4dev/oppia-android/commit/f6b21febe328fbd434ac43900ce327ca2e61ddfe)? If not, we need to supress this lint check.
> 
> I am also concerned that replacing ... and - instances in Arabic translations with unicode may make it difficult for translators to understand the strings.

HDPI are fine to add for everything except our baked-in lesson thumbnails (mostly since those are going to go away as soon as we can remove them), but aside from that we may need to suppress the warning until such time that we can remove those images. Perhaps we can file a follow-up issue to do that work once it's understood what's involved?

Re: the ``...`` and ``-`` issues, what exactly is the warning that Android Lint is outputting?

**Comment by Rd4dev** [comment]
@BenHenning 
About the unicode warnings,
The warnings were under the `Typography` category claiming:
- Ellipsis string can be replaced with ellipsis character
  Replace "..." with ellipsis character(..., &#8230;)?
  Link: **[strings.xml](https://github.com/Rd4dev/oppia-android/blob/69d2b822ae1e3287447d4e031088dca95b682ca4/app/src/main/res/values-ar/strings.xml#L414)**
- Hyphen can be replaced with dash
  Replace "-" with an "en dash" character(-, &#8211;)?
  Link: **[strings.xml](https://github.com/Rd4dev/oppia-android/blob/69d2b822ae1e3287447d4e031088dca95b682ca4/app/src/main/res/values-ar/strings.xml#L170)**

**Comment by adhiamboperes** [comment]
Assigning @BenHenning for follow up.

**Comment by BenHenning** [comment]
Sorry, missed this. Thanks @Rd4dev that helps. I think we can go ahead and make the suggested Unicode changes. Those characters *should* show up correctly in Translatewiki, and thus hopefully not confuse our translators. 

Just to check: @adhiamboperes why were you specifically concerned for Arabic translations?

**Comment by adhiamboperes** [comment]
@BenHenning, my concern was that the unicode may not show up correctly on translatewiki. Per your comment, this may not be a concern.
