### ISSUE TITLE
InvalidPackage + NewApi +  FragmentLiveDataObserve + RestrictedApi

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5195]
## Description
We would like to fix all the remaining lint issues on Oppia Android. There are currently 195 errors and 1009 warnings. Also, 38 checks are currently disabled.

This issue tracks fixing all "InvalidPackage + NewApi + FragmentLiveDataObserve + RestrictedApi"

## Steps To Reproduce
Run the following command from a terminal in a checked-out Oppia Android repo:

./gradlew :app:lint

## Expected Behavior
Running the command above should not show any errors in this category

**Comment by adhiamboperes** [comment]
@sichchurov, please take a look at this issue and update your PR #5169 to reference it instead. If you are fixing part of an issue, reference it as "fix part of #issuenumber".

**Comment by adhiamboperes** [comment]
Linking your comments from the main issue:

https://github.com/oppia/oppia-android/issues/5169#issuecomment-1762884121

https://github.com/oppia/oppia-android/issues/5169#issuecomment-1765770017

**Comment by adhiamboperes** [comment]
In https://github.com/oppia/oppia-android/issues/5169#issuecomment-1762884121, you suggest using branching logic for ControlButtonsViewModel. Is this the only class with this warning?

**Comment by adhiamboperes** [comment]
As for https://github.com/oppia/oppia-android/issues/5169#issuecomment-1765770017, when you change to your suggested line of code, do you not get a resolution error?

**Comment by sichchurov** [comment]
> In [#5169 (comment)](https://github.com/oppia/oppia-android/issues/5169#issuecomment-1762884121), you suggest using branching logic for ControlButtonsViewModel. Is this the only class with this warning?

According to the lint report - this is the only class with this error

**Comment by sichchurov** [comment]
> As for [#5169 (comment)](https://github.com/oppia/oppia-android/issues/5169#issuecomment-1765770017), when you change to your suggested line of code, do you not get a resolution error?

This solution doesn't work. I've passed a test and it failed. I'd have to think more about the new solution

**Comment by adhiamboperes** [comment]
> > As for [#5169 (comment)](https://github.com/oppia/oppia-android/issues/5169#issuecomment-1765770017), when you change to your suggested line of code, do you not get a resolution error?
> 
> This solution doesn't work. I've passed a test and it failed. I'd have to think more about the new solution


Could you please explain what you mean by this? What test? What is the failure/error

**Comment by sichchurov** [comment]
> > > As for [#5169 (comment)](https://github.com/oppia/oppia-android/issues/5169#issuecomment-1765770017), when you change to your suggested line of code, do you not get a resolution error?
> > 
> > 
> > This solution doesn't work. I've passed a test and it failed. I'd have to think more about the new solution
> 
> Could you please explain what you mean by this? What test? What is the failure/error

To test  this [#5169 (comment)](https://github.com/oppia/oppia-android/issues/5169#issuecomment-1765770017) changes

I have started this test `AppCompatCheckBoxBindingAdaptersTest`

and it is failed

> expected: 65536
> but was : null

I've found another solution
I'll make a PR later to show my mind

**Comment by adhiamboperes** [comment]
@sichchurov, are you still working on this issue? If not, can you please add a comment explaining the remaining part and then unassign yourself, so someone else can take over?

**Comment by rishav2404** [comment]
@adhiamboperes, can you please explain me what is remaining in this issue as a lot get merged and also i want to work on this.
