### ISSUE TITLE
[BUG]: good first issue link redirects to wrong page.

### ISSUE THREAD

**Issue by AhzamAkhtar** [oppia/oppia-android#5214]
### Describe the bug

good first issue link redirects to oppia-android testing page under Next Steps in wiki/Installing-Oppia-Android page.

### Steps To Reproduce

1- Go to https://github.com/oppia/oppia-android/wiki/Installing-Oppia-Android

2- Scroll down to Next Steps at the bottom

3- Click on good first issues 

### Expected Behavior

It should redirect to the good first issue page not the Oppia-Android-Testing page.

### Screenshots/Videos

![oppi1](https://github.com/oppia/oppia-android/assets/94620460/68e238b1-5b51-46d2-8f72-69185b66d59e)

**Comment by adhiamboperes** [comment]
Thanks for filing this @AhzamAkhtar, but I am going to assign this to @MohitGupta121 who already has a PR editing the wiki. I'll go ahead and close your PR.

@MohitGupta121, PTAL and fix this as part of your PR.

**Comment by MohitGupta121** [comment]
@adhiamboperes I already make changes of this in my PR. Thanks.
