### ISSUE TITLE
[Feature Request]: Remove the EnableLanguageSelectionUi Feature Flag

### ISSUE THREAD

**Issue by kkmurerwa** [oppia/oppia-android#5225]
### Is your feature request related to a problem? Please describe.

Since the EnableLanguageSelectionUi has been officially rolled out, the related feature flag can now be removed.

### Describe the solution you'd like

I would like to have the EnableLanguageSelectionUi feature flag removed from the FeatureFlagConstants file since the feature it was gating has officially been released and is stable. Any of its related constants and dagger module declarations should also be removed. Lastly, I would like the if statements surrounding any functionality that is gated using this feature flag to be removed as well.

**Comment by kmanikanta335** [comment]
can i work on this issue ?

**Comment by adhiamboperes** [comment]
@kmanikanta335 can you please give an overview of how you plan to solve the issue, including the files that need to be changed.

**Comment by kmanikanta335** [comment]
@adhiamboperes Here is the overview 
1. first file [OptionControlsViewModel.kt.kt](https://github.com/kmanikanta335/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/options/OptionControlsViewModel.kt) I would to like remove
i) the imports of EnableLanguageSelectionUi 
ii) line 35
iii) the if condition in line 115
2. second file [sharedTestOptionsFragmentList.kt](https://github.com/kmanikanta335/oppia-android/blob/develop/app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt) I would like to remove
 i) lines 149 and 373
3. third file [OptionsFragemgtTest.kt](https://github.com/kmanikanta335/oppia-android/blob/develop/app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt) i would like to remove 
i) lines 116 and 174

**Comment by adhiamboperes** [comment]
@kmanikanta335, your solution describes removing usages of this platform param, but you must also remove its declaration. Please see https://github.com/oppia/oppia-android/issues/5226#issuecomment-1812367104 on removing the parameter from the constants file and the dagger modules.

**Comment by adhiamboperes** [comment]
@kmanikanta335, are you still putting up a PR for this issue?

**Comment by kmanikanta335** [comment]
@adhiamboperes yes i have made a PR please review it
