### ISSUE TITLE
Issues in Select Profile page

### ISSUE THREAD

**Issue by veena14cs** [oppia/oppia-android#523]
Tested on device Pixel 3a XL. Profiles are not loaded when the app is running for the first time or when the phone is locked while the app is running.

![Screenshot_20191206-105903](https://user-images.githubusercontent.com/16301028/70298406-93ba5c80-1817-11ea-8ce3-bdaae4a1472f.png)

**Comment by BenHenning** [comment]
@veena14cs is this still an issue?

**Comment by veena14cs** [comment]
@BenHenning this is been fixed, I checked in develop it works fine. I will close this issue.
