### ISSUE TITLE
VectorDrawableCompat

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5230]
Fix lint warnings related to VectorDrawableCompat

**Comment by adhiamboperes** [comment]
@DeonWaju per your comment on https://github.com/oppia/oppia-android/issues/5169#issuecomment-1812098449, I would go against updating the minimum sdk version because that will have broad effects on the app and can cause compatibility issues. I believe we also have a seperate issue tracking that work. Prefer the second proposal.

**Comment by deonwaju** [comment]
Ok, noted. Thanks @adhiamboperes

**Comment by deonwaju** [comment]
Warning: VectorDrawableCompat
Fix: open the app's build.gradle file.
Inside the android block, add or update the vectorDrawables section under defaultConfig:
`android { ... defaultConfig { ... vectorDrawables { useSupportLibrary true } } }`
