### ISSUE TITLE
[Bug]: Fix "ImpliedQuantity" lint warning in pt-rBR strings.

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5231]
### Steps To Reproduce

Run the following command from a terminal in a checked-out Oppia Android repo:

`./gradlew :app:lint`

### Expected Behavior

Running the command above should not show any **ImpliedQuantity**. warnings.

**Comment by adhiamboperes** [comment]
@DeonWaju contrary to the suggestion in https://github.com/oppia/oppia-android/issues/5169#issuecomment-1812098449: 
- the "one" quantity plural should not take a variable, because it is always just one. 
- we use string templates %s, usually not %d

An approach that might be worth testing based on my examination of the ptBr strings file, is fixing the formatting in the plurals by removing the newlines(\n). Please see https://github.com/oppia/oppia-android/issues/5164 for expected correct string formats for quantity and plurals. Might be worth checking other langauge string files for similar formatting errors.

**Comment by deonwaju** [comment]
Hi @adhiamboperes, This issue seems to persist, i have tried the above methods and checked on comment #5164, also tried a few ways. The issue lies "The warning you're seeing is related to internationalization and localization (i18n/l10n) of your application, specifically dealing with pluralization in different languages.". The only solution that seemed to `    <item quantity="one">%d Capítulo\n</item>
` as earlier stated.

**Comment by adhiamboperes** [comment]
Hi @DeonWaju, can you confirm that this plural is formatted in the same way in all translations?

**Comment by deonwaju** [comment]
No it wasn't at first, It was like below:

<img width="981" alt="Screenshot 2023-11-21 at 23 52 46" src="https://github.com/oppia/oppia-android/assets/54560535/842e9e73-3cb3-45dd-a122-f617fa88f884">



Then, I formatted it the same way like below, but still same error:



<img width="1020" alt="Screenshot 2023-11-21 at 23 52 28" src="https://github.com/oppia/oppia-android/assets/54560535/1f6803f4-09e7-4f3a-955d-232373633a2c">

**Comment by adhiamboperes** [comment]
Based on https://googlesamples.github.io/android-custom-lint-rules/checks/ImpliedQuantity.md.html and the lint report, it seems that adding the string template as you are suggesting should be fine. But use `%s` not `%d`, since we are passing a string value.

My concern is, how will we pass the value "1" in the code where the plural is used, if the default English translation is not in the same format? (You can change the locale on your device and test this out). Are you going to change the string in english too?

Additionally, are you going to modify the other plurals in the file too?

Lastly, I would still prefer the plurals formatting fixed in general, per my earlier comment.

**Comment by deonwaju** [comment]
@adhiamboperes Your concerns are valid, But I didnt make the changes in the other languages, I cant change my the locale on my phone for some reason, Also for concerns in passing the value "1" in the code where the plural is used. I dont know if the below function does that automatically. Finally, I am leaning towards leaving this issue and picking up another issue and leaving this issue till a proper solution with fewer unknowns arrives. 
<img width="854" alt="Screenshot 2023-11-22 at 18 59 38" src="https://github.com/oppia/oppia-android/assets/54560535/292b6daa-86f9-4159-96d0-4623b07a39c0">

**Comment by deonwaju** [comment]
Hello @adhiamboperes

**Comment by adhiamboperes** [comment]
@DeonWaju, feel free to work on something else

**Comment by adhiamboperes** [comment]
Hi @DeonWaju, I looked into this some more, and per https://developer.android.com/guide/topics/resources/string-resource#Plurals, we can fix this by changing the plural strings for one in pt-rBR to include a %d as discussed. No aditional change would be required where the string is called.  It should be easy to verify this by changing your phone language to spanish and confirming that it displays correctly in the app. 
The solution will be complete if you also fix the newline formatting of the plurals in thaat file.

**Comment by deonwaju** [comment]
> The solution will be complete if you also fix the newline formatting of the plurals in thaat file.

Hello @adhiamboperes, I understand the rest, but could you please explain this? Do you mean removing the \n right?

**Comment by adhiamboperes** [comment]
> Hello @adhiamboperes, I understand the rest, but could you please explain this? Do you mean removing the \n right?

Yes, that is correct.
