### ISSUE TITLE
[BUG]: ConsoleLogger overwrites local log file for each line write

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#5232]
### Describe the bug

``ConsoleLogger`` has support for logging output lines to a local log (rather than just logcat). However, it seems that this is currently configured such that each line will completely overwrite the original log file.

### Steps To Reproduce

- Build & install a developer version of Oppia Android.
- Play around in the app for a bit to generate logs.
- Pull logs from logcat (e.g. either in Android Studio or via ``adb logcat | grep org.oppia.android``).
- Pull the logs file: ``$ANDROID_HOME/platform-tools/adb pull /data/data/org.oppia.android/files/oppia_app.log ~/opensource/oppia_app.log``
- Compare these logs. Notice that the last entry in oppia_app.log is just the last log written in the logcat log.

### Expected Behavior

All lines should be kept, not just the most recent.

### What device/emulator are you using?

Pixel 6a emulator

### Which Android version is your device/emulator running?

SDK 33

### Which version of the Oppia Android app are you using?

0.11-dev-80a9a09723

### Additional Context

From the logic in ``ConsoleLogger``:

https://github.com/oppia/oppia-android/blob/6006277f33af2e981964fc4ab58e366c7f39e21a/utility/src/main/java/org/oppia/android/util/logging/ConsoleLogger.kt#L108

I suspect this is caused by the open ``FileWriter`` just always, by default, overwriting the file. We should, instead, open the writer in append mode & add tests to verify that this functionality now works.

Also, it's probably a good idea to keep a long-lived ``PrintStream`` open for the log file rather than reopening it for each line (which is going to be less performant). We _should_ overwrite the file in this case (to avoid indefinitely using more disk space for debug logs). This includes adding tests for verifying that multiple ``ConsoleLogger`` instances _do_ overwrite the file from the previous logger.

**Comment by BenHenning** [comment]
Suggest that this is a good potential starter issue since it should be straightforward to investigate, fix, and add tests for it.

**Comment by kmanikanta335** [comment]
can i work on this issue @adhiamboperes

**Comment by adhiamboperes** [comment]
Hi @kmanikanta335. Could you please share an overview of your proposed solution?

**Comment by kmanikanta335** [comment]
@adhiamboperes 
proposed solution

1. Open ConsoleLogger.kt:
    Locate the file ConsoleLogger.kt in the Oppia Android project.

2. Modify File Opening Mode:
   Change the file opening mode to append. Replace the existing line:
  blockingScope.launch { logDirectory.printWriter().use { out -> out.println(text) } }
 with:
  blockingScope.launch { logDirectory.appendText("$text\n") }

3. Use Long-Lived PrintStream:
    Maintain a long-lived PrintStream for the log file. You can create it during the initialization of the ConsoleLogger or at an 
   appropriate point where it won't be repeatedly opened. For example:

   private val logPrintStream: PrintStream = logDirectory.appendText().bufferedWriter().use { it }

   // ...

   blockingScope.launch { logPrintStream.println(text) }

**Comment by adhiamboperes** [comment]
@kmanikanta335, you can put up a draft PR with these changes that you have proposed.

**Comment by Saifuddin53** [comment]
Can I work on this issue as @kmanikanta335 has not posted any PR till now?

**Comment by manas-yu** [comment]
Hi @adhiamboperes can i work on this issue?
The issue seems to stem from how PrintWriter is used in the logToFileInBackground() method within the ConsoleLogger class.
we can modify the logToFileInBackground function to use appendText() to add content to the log file instead of overwriting it. and it seems to resolve the issue
```kotlin
private fun logToFileInBackground(text: String) {
    blockingScope.launch {
      if (printWriter == null) {
        printWriter = PrintWriter(FileWriter(logDirectory, true)) // Open in append mode
      }
      printWriter?.println(text)
      printWriter?.flush()
    }
  }

  /** Close the log file when logging is finished. */
  fun closeLogFile() {
    printWriter?.close()
    printWriter = null
  }
}

**Comment by adhiamboperes** [comment]
Hi @manas-yu, I have assigned the issue to you. Please feel free to put up a PR!
