### ISSUE TITLE
What should be the maximum number of characters allowed in input edit text.

### ISSUE THREAD

**Issue by veena14cs** [oppia/oppia-android#524]
Whether Edittext text should be multiline input or single line input. It also crashed on entering long input.

![Screenshot_20191206-140217](https://user-images.githubusercontent.com/16301028/70308408-33d0af80-1831-11ea-881b-47a58b2898b0.png)

<img width="1625" alt="Screenshot 2019-12-06 at 2 05 20 PM" src="https://user-images.githubusercontent.com/16301028/70308561-8f02a200-1831-11ea-8ca4-52923a1b2220.png">

**Comment by anandwana001** [comment]
Currently, we are handling this issue like this. Should we close this issue?

![Screenshot_1594212370](https://user-images.githubusercontent.com/25057618/86920270-26710000-c147-11ea-8e03-2aee9f1c181d.png)

**Comment by rt4914** [comment]
This issue has been fixed in develop. 

This was done in https://github.com/oppia/oppia-android/pull/640 , https://github.com/oppia/oppia-android/pull/674 , https://github.com/oppia/oppia-android/pull/419
