### ISSUE TITLE
[Feature Request]: Update the Android FAQ

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#5246]
### Is your feature request related to a problem? Please describe.

The UX Writing team has done a review of the Android app FAQ and would like to propose updates to it.

### Describe the solution you'd like

FAQ items should be arranged in this order:

- What is Oppia?
- Who is an Administrator?
- How can I create a new profile?
- How do I get the app in my language?
- I found a bug. How can I report it?
- Why are there only math lessons?
- Will you be making more lessons?
- Why is the Exploration player not loading?
- Why is my audio not playing?
- How can I delete a profile?
- How can I change my email/phone number?
- How do I update the app?
- How do I update my Android OS?
- I can’t find my question here. What now?

**Updates to existing questions:**

Q: How can I create a new profile? -- should be updated:
- Current: If it is your first time creating a profile and not have a PIN:
- Updated: If it is your first time creating a profile and you do not have a PIN:

**New questions:**

- **Why are there only math lessons?**
Oppia’s mission is to help learners gain necessary life skills. Math is an essential skill in everyday life. Oppia will be offering new lessons on science and other subjects soon!

- **Will you be making more lessons?**
Yes, Oppia will be offering new lessons on science and other subjects soon. Please check back for updates!

- **I found a bug. How can I report it?**

1. From your Oppia app home screen, tap the menu in the top left corner.
2. Tap **Share feedback**.
3. Follow the instructions to report the bug or share feedback.

- **How do I get the app in my language?**
The Oppia app currently supports English, Brazilian Portuguese, Arabic, and Nigerian Pidgin. Choose one of these languages in the menu, under Options. To request the app in your language, please contact us at _email address_.

- **How do I update the app?**

1. Open the Google Play Store app.
2. Search for the Oppia app. 
3. Tap **Update**.

- **How do I update my Android OS?** 

1. Tap your phone's **Settings** app.
2. Tap **System updates**.
3. Tap **System updates** and follow the instructions to update your Android operating system. 

### Describe alternatives you've considered

N/A

### Additional context

See the original design issue at https://github.com/oppia/design-team/issues/75 for the discussion.

**Comment by seanlip** [comment]
Also copying @jlevick, the UX Writer, here, in case there are any questions about the above. Thanks!

**Comment by adhiamboperes** [comment]
@DeonWaju, PTAL at this issue.

**Comment by deonwaju** [comment]
Warning: Update the Android FAQ
Fix: (A)Go to the strings.xml file and update the name property of the strings by refactoring question numbers,(B) also add the new questions to the strings.xml file,
(C)finally change QUESTION_INDEX_WITH_OPPIA_REFERENCE to correlate with new index of the question in FAQListViewModel.

Please review if this aligns so I can make a PR. @adhiamboperes

**Comment by adhiamboperes** [comment]
Hi @DeonWaju, could you please review the issue requirements again? I am not sure there is need for updating the name property of the strings. Its seems like you just need to update the text of a few strings, create a few new ones per issue description and finally make sure that the FAQs display in the app in then requested order. 
Could you please let me know if I can explain something further?

Additionally, you only need to make these changes in the english string files. Translations are handled externally.

**Comment by deonwaju** [comment]
> Hi @DeonWaju, could you please review the issue requirements again? I am not sure there is need for updating the name property of the strings. Its seems like you just need to update the text of a few strings, create a few new ones per issue description and finally make sure that the FAQs display in the app in then requested order. Could you please let me know if I can explain something further?
> 
> Additionally, you only need to make these changes in the english string files. Translations are handled externally.

No I meant the name property of the string, to change it e.g, the current FAQ1 is "How can I create a new profile?"

<img width="809" alt="Screenshot 2023-11-27 at 21 43 15" src="https://github.com/oppia/oppia-android/assets/54560535/bb26d942-fd8d-439c-bcd0-5a0c421a50cc">

FAQ1 needs to be "What is Oppia?" and so on, the proper arrangement

<img width="374" alt="Screenshot 2023-11-27 at 21 45 32" src="https://github.com/oppia/oppia-android/assets/54560535/bc785aa4-837c-4484-887f-ffeb55517473">

So I do understand the task, thanks for clarifying this though >Additionally, you only need to make these changes in the english string files. Translations are handled externally.

**Comment by adhiamboperes** [comment]
Great, you can put up a PR for this.

**Comment by adhiamboperes** [comment]
Just to clarify-- you don't need to translate the strings, but you may need to reorder the questions in the translations as well.

**Comment by deonwaju** [comment]
> Just to clarify-- you don't need to translate the strings, but you may need to reorder the questions in the translations as well.

Yeah, Thanks, I understand better now.

**Comment by shashijaiswal1** [comment]
Could someone please tell me how to solve issues. what is the procedure? I am new to open source. Thanks.

**Comment by kkmurerwa** [comment]
Hi @shashijaiswal1, welcome to Oppia-Android. The first step would be to identify an issue. I recommend looking at the  [list of unassigned first issues](https://github.com/oppia/oppia-android/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee) and see one that you could work on. Once you find one, comment under it and tag me or @adhiamboperes and we will guide you on the next steps.

**Comment by adhiamboperes** [comment]
> Could someone please tell me how to solve issues. what is the procedure? I am new to open source. Thanks.

Hi @shashijaiswal1,  Our [wiki](https://github.com/oppia/oppia-android/wiki/) is great place to get started contributing to opensource at Oppia.
