### ISSUE TITLE
[Feature Request]: Add support for logging device DPI for events

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#5250]
### Is your feature request related to a problem? Please describe.

Events need to include the device's (unscaled) DPI as part of its log so that we can get an idea on how devices span different density formats.

### Describe the solution you'd like

An integer for dpi (e.g. 320) should be logged as an event dimension (e.g. in EventBundleCreator). This should NOT be affected by display zoom.

### Describe alternatives you've considered

There isn't a good alternative to get display density (one would need to manually look up the device specs).

### Additional context

Needed to determine whether we need to address #360, plus it'll help with other decisions in the future.

**Comment by Tejas-67** [comment]
Hi @BenHenning , I would like to work on this issue. Please assign this to me.

In the EventBundleCreator.kt file, we can have something like: 
`private val screenDensity by lazy {
    context.resources.displayMetrics.densityDpi
  }`
and in the fillEventBundle function:
`bundle.putInt(
      "screen_density", screenDensity
   )`

rest all remains same.

**Comment by Tejas-67** [comment]
Should I work on this issue? @BenHenning @adhiamboperes

**Comment by adhiamboperes** [comment]
@Tejas-67, how would you address this:

> An integer for dpi (e.g. 320) should be logged as an event dimension (e.g. in EventBundleCreator). This should NOT be affected by display zoom.

**Comment by Tejas-67** [comment]
As mentioned in the previous comment, we can use resources.displayMetrics.densityDpi to get the device density. 
@adhiamboperes

**Comment by adhiamboperes** [comment]
@BenHenning, does this value need to be inclu ded for every eventlog?
