### ISSUE TITLE
Feature Request: Modify Feature Flag Names to reflect those on Oppia Web

### ISSUE THREAD

**Issue by kkmurerwa** [oppia/oppia-android#5251]
### Is your feature request related to a problem? Please describe.

Some of the feature flags used to gate feature on Oppia-Android need to be updated to  reflect new android-specific feature flag names from oppia-web so that remote enabling and disabling of these features is possible.

### Describe the solution you'd like

The feature flag names in the [FeatureFlagConstants](https://github.com/oppia/oppia-android/blob/develop/utility/src/main/java/org/oppia/android/util/platformparameter/FeatureFlagConstants.kt) file need to be modified and to the new respective names as shown below.

| Feature Flag | Current Feature Flag Name | Proposed Feature Flag Name |
| ------------- | ------------------ | ------------------ |
| EnableDownloadsSupport | downloads_support | android_enable_downloads_support |
| EnableExtraTopicTabsUi | extra_topic_tabs_ui | android_enable_extra_topic_tabs_ui |
| EnableLearnerStudyAnalytics | learner_study_analytics | android_enable_learner_study_analytics |
| EnableFastLanguageSwitchingInLesson | fast_language_switching_in_lesson | android_enable_fast_language_switching_in_lesson |
| EnableLoggingLearnerStudyIds | logging_learner_study_ids | android_enable_logging_learner_study_ids |
| EnableEditAccountsOptionsUi | edit_accounts_options_ui | android_enable_edit_accounts_options_ui |
| EnablePerformanceMetricsCollection | performance_metrics_collection |  android_enable_performance_metrics_collection |
| EnableSpotlightUi | spotlight_ui | android_enable_spotlight_ui |
| EnableInteractionConfigChangeStateRetention | interaction_config_change_state_retention | android_enable_interaction_config_change_state_retention |
| EnableAppAndOsDeprecation | app_and_os_deprecation | android_enable_app_and_os_deprecation |

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by kkmurerwa** [comment]
Hi @adhiamboperes. I decided not to do this as part of #5240 since it could be a good first issue and it poses little risk to the functionality of the rest of the codebase. Let me know what you think.

**Comment by Tejas-67** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by adhiamboperes** [comment]
Thanks @kkmurerwa! Looks good as a gfi.

@Tejas-67, could you please describe the changes required to solve this issue?

**Comment by Tejas-67** [comment]
@adhiamboperes the issue require changing the value of feature flags from the current name to the proposed name. 
eg; from `const val DOWNLOADS_SUPPORT = "downloads_support"` to `const val DOWNLOADS_SUPPORT = "android_enable_downloads_support" `

**Comment by adhiamboperes** [comment]
> @adhiamboperes the issue require changing the value of feature flags from the current name to the proposed name. eg; from `const val DOWNLOADS_SUPPORT = "downloads_support"` to `const val DOWNLOADS_SUPPORT = "android_enable_downloads_support" `

You can submit a draft PR for this issue. I think the issue description is already pretty specific on the required changes, @Tejas-67

**Comment by Tejas-67** [comment]
@adhiamboperes done.
