### ISSUE TITLE
DisableBaselineAlignment + InefficientWeight + Overdraw + UseCompoundDrawables + UselessLeaf + UselessParent

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5261]

**Comment by adhiamboperes** [comment]
@DeonWaju , Re: your comment:

> 1. Fix part of [DisableBaselineAlignment + InefficientWeight + Overdraw + UseCompoundDrawables + UselessLeaf + UselessParent]
>    Fix for DisableBaselineAlignment: (A) Add android:baselineAligned="false" to LinearLayout on line 12 in "layout-sw600dp-land/topic_info_fragment.xml"
>    (B) Add android:baselineAligned="false" to LinearLayout on line 91 in "
>    "layout/topic_lessons_story_summary.xml"
>    (C) Add android:baselineAligned="false" to LinearLayout on line 93 in "
>    "layout-sw600dp-land/topic_lessons_story_summary.xml"
>    Example below:
>    Warning: Addressing DisableBaselineAlignment warning on the 13th issue on the list [DisableBaselineAlignment + InefficientWeight + Overdraw + UseCompoundDrawables + UselessLeaf + UselessParent]


I have checked [this](https://stackoverflow.com/questions/9319916/how-does-setting-baselinealigned-to-false-improve-performance-in-linearlayout) for an explanation of this lint warning. I'm curious about the usage of weight in these layouts. Is it necessary?

**Comment by deonwaju** [comment]
> I have checked [this](https://stackoverflow.com/questions/9319916/how-does-setting-baselinealigned-to-false-improve-performance-in-linearlayout) for an explanation of this lint warning. I'm curious about the usage of weight in these layouts. Is it necessary?


I think the weight assignment indicates that the TextView should take up a proportional amount of space horizontally in the linear layout. An alternative would be to use a constraint layout. 

<img width="681" alt="Screenshot 2023-12-06 at 23 43 28" src="https://github.com/oppia/oppia-android/assets/54560535/6184d097-de80-4bd4-9472-33a07877c48d">

**Comment by adhiamboperes** [comment]
@DeonWaju, Sure, let's go with your approach.

**Comment by deonwaju** [comment]
> @DeonWaju, Sure, let's go with your approach.

Sorry not clear, the first approach or using a constraint layout?

**Comment by adhiamboperes** [comment]
The first one for baseline alignment. Pere the SO link, it seems to be a performance improvement, and will require the least effort.

**Comment by adhiamboperes** [comment]
Closing this due to lack of context in the decription. It will be tracked by the main issue - #5169
