### ISSUE TITLE
[BUG]: Navigation drawer icon is not working after returning from topics.

### ISSUE THREAD

**Issue by Vishwajith-Shettigar** [oppia/oppia-android#5266]
### Describe the bug

Navigation drawer icon is not working after returning from topics, even though user can use swipe to open navigation drawer.

### Steps To Reproduce

1.  Go to home
2.  Open any topic 
3.  Return to home
4.  Click on navigation drawer icon.

### Expected Behavior

Clicking drawer icon should open  navigation drawer.

### Screenshots/Videos

[navdrawerissue.webm](https://github.com/oppia/oppia-android/assets/76042077/14ee4063-e0e6-4a45-8d1d-57749151cf6c)

**Comment by Vishwajith-Shettigar** [comment]
Hi @MohitGupta121, can you please tell me if this issue is able to be reproduced or not?

**Comment by theMr17** [comment]
Hi @Vishwajith-Shettigar, I was able to reproduce the issue. This is probably caused by PR https://github.com/oppia/oppia-android/pull/5191. I am working on it.

**Comment by Vishwajith-Shettigar** [comment]
@theMr17 Thank you for confirming.
