### ISSUE TITLE
[BUG]: Not able to navigate back from story.

### ISSUE THREAD

**Issue by Vishwajith-Shettigar** [oppia/oppia-android#5267]
### Describe the bug

when user click on view all in **stories for you** and open any story, user will be stuck, there is no way to go back to home.

### Steps To Reproduce

1. Click on view all
2. open any story
3. click on close icon and try to go back.

### Expected Behavior

Clicking back or close button should navigate back.

### Screenshots/Videos

[storyissue.webm](https://github.com/oppia/oppia-android/assets/76042077/b2c3c316-80bd-4aa4-8b0f-ba879706df7d)

**Comment by Cyclotron17** [comment]
Hello I want to work in this issue

**Comment by MohitGupta121** [comment]
@Cyclotron17 please brief your approach, if that's look good then we assign you the issue.

**Comment by prabhakar0304** [comment]
I tried to reproduce the bug but everything was working fine.

### Device Info
Device : Galaxy S21 FE
Android Version : 13
App Version: 0.11-beta-3343155232

**Comment by Vishwajith-Shettigar** [comment]
> I tried to reproduce the bug but everything was working fine.
> 
> ### Device Info
> Device : Galaxy S21 FE Android Version : 13 App Version: 0.11-beta-3343155232

 @prabhakar0304, are you trying to reproduce the issue with Play Store version?

**Comment by predator313** [comment]
hey is this issue still remain?? I want to work on this

**Comment by Vishwajith-Shettigar** [comment]
Hi @predator313, this issue already has PR, can you go with other issues ?
