### ISSUE TITLE
[BUG]: Revision cards overlapping.

### ISSUE THREAD

**Issue by Vishwajith-Shettigar** [oppia/oppia-android#5283]
### Describe the bug

Revision cards overlapping .
PR https://github.com/oppia/oppia-android/pull/5095 causing the issue.

### Steps To Reproduce

1.go to any topic 
2.click on revision
3.click on any revision card
4.scroll down

### Expected Behavior

Cards should be displayed without overlapping.

### Screenshots/Videos

![concept_card_overlaping](https://github.com/oppia/oppia-android/assets/76042077/81dcc144-9eef-4d25-b90d-89dcec4bf2ed)

**Comment by shalenMathew** [comment]
hey, can I contribute to this issue?

**Comment by Vishwajith-Shettigar** [comment]
> hey, can I contribute to this issue?

Hi @shalenMathew, this issue already assigned and has PR, so you can look at other issues.

**Comment by adhiamboperes** [comment]
Moving this to 0.12 Release Blockers.
