### ISSUE TITLE
[BUG]: Bazel Setup Instructions for Linux Missing Java Home Instructions

### ISSUE THREAD

**Issue by crmz2032** [oppia/oppia-android#5293]
### Describe the bug

The setup steps for Bazel, Linux, fail to mention that the JAVA_HOME env variable should be set.

### Steps To Reproduce

run any command without setting up the JAVA_HOME env variable 

### Expected Behavior

Set up instructions should include step for JAVA_HOME env variable, or links to resources on how to do it.

**Comment by adhiamboperes** [comment]
@MohitGupta121, PTAL.

**Comment by adhiamboperes** [comment]
This is no longer needed, as `.bazelrc` was updated to configure tools, tests, and builds to all use the remote JDK 11 available via Bazel rather than ever using the user's local JDK.
