### ISSUE TITLE
[BUG]: Static Analysis Checks not running locally

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5301]
### Describe the bug

Some Static Analysis Checks  are not running locally with error `scripts/static_checks.sh: line 100: bazel: command not found`

### Steps To Reproduce

In a checked out `oppia-android` folder path on terminal, run ` bash scripts/static_checks.sh `.

This requires a working bazel set up.

### Expected Behavior

All checks to run successfully.

### Screenshots/Videos

<img width="1379" alt="Screenshot 2024-01-16 at 09 34 43" src="https://github.com/oppia/oppia-android/assets/59600948/5c2e5ced-d019-46bc-a3c5-674070a7e18c">

### What device/emulator are you using?

N/A

### Which Android version is your device/emulator running?

MacOs Sononoma 14.2.1

### Additional Context

Need to repro this on Linux to confirm it is not a Mac only issue.

**Comment by adhiamboperes** [comment]
Hi @kkmurerwa, could you please try to repro this on your end? Feel free to unassign yourself afterwards if you are unable to put up a PR.

**Comment by kkmurerwa** [comment]
@adhiamboperes I believe the only reason this could happen is if Bazel is not installed. Are other Bazel commands running?

**Comment by adhiamboperes** [comment]
> @adhiamboperes I believe the only reason this could happen is if Bazel is not installed. Are other Bazel commands running?

Yes, but I will need to check maybe the bazel path is not set correctly.

**Comment by manas-yu** [comment]
> > @adhiamboperes I believe the only reason this could happen is if Bazel is not installed. Are other Bazel commands running?
> 
> Yes, but I will need to check maybe the bazel path is not set correctly.

I attempted to reproduce the issue, and everything works fine on my end. I have Bazel set up correctly, and the check is running without any issues locally.

**Comment by adhiamboperes** [comment]
Thanks @manas-yu! This works correctly for me now as well. I believe I had earlier not completed my Bazel configuration, and a lot has changed since then to simplify Bazel setup.
