### ISSUE TITLE
[BUG]: [Wiki] Bazel Setup Instructions on Windows Need Refinement.

### ISSUE THREAD

**Issue by Rd4dev** [oppia/oppia-android#5324]
### Describe the bug

While attempting to set up Oppia-Android with Bazel, the provided instructions in [Bazel Setup Instructions for Windows](https://github.com/oppia/oppia-android/wiki/Bazel-Setup-Instructions-for-Windows) lack several key components:

1. **Prerequisite debian packages:**
   - Java 8 is required for building Oppia-Android, but it throws a JNI error with sdkmanager.

2. **Python 2:**
    - The Python installation command needs updation to install Python2.

3. **Installing the Android SDK:**
    - The path provided in the copy command for the Linux command line tools should be like `mnt/c/...` and not `c/mnt/....`
    - sdkmanager requires platform tools for SDK 33 (currently provided at 28).

4. **Installing Bazel:**
    - Bazel installation instructions need updation; the provided command doesn't work to install the particular version 4.0.0.

5. **Preparing build environment for Oppia Android**
    - No instructions are provided for cloning the repo to the opensource directory, from which the command should be run to build Oppia.
    
6. **Verifying the build:**
    - If Java is set to any other version while executing sdkmanager commands, it needs to be reconfigured to Java 8 to build Oppia via Bazel.
    
7. **Additional info:**
    - The installation of GCC is necessary for successful building, but no instructions are provided.

These are a few notable issues found in the Bazel setup instructions for Windows.

### Steps To Reproduce

Follow instructions on: https://github.com/oppia/oppia-android/wiki/Bazel-Setup-Instructions-for-Windows

1. **Python 2**
`sudo apt install python `
Python installation throws error suggesting other alternatives!
**Error:** Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  2to3 python2-minimal python2 dh-python python-is-python3
 
2. **Copying Command Line Tools**
`cp /c/mnt/Users/<Name>/Downloads/commandlinetools*.zip $HOME/Android/Sdk`
No files exists as wrong path is provided
**Error:** $ ls /c/mnt
ls: cannot access '/c/mnt': No such file or directory

3. **Platform Tools**
`sdkmanager --install "platforms;android-28"`
Throws warning at the end to use android-33

4. **Bazel Installation**
`sudo apt install bazel-4.0.0`
Throws error saying:
E: Unable to locate package bazel-4.0.0
E: Couldn't find any package by glob 'bazel-4.0.0'

### Expected Behavior

To build oppia-android successfully with bazel!

### Screenshots/Videos

**Bazel Installation Error:**

![image](https://github.com/oppia/oppia-android/assets/122200035/ade4f6b5-44aa-4aad-a8e6-6740985b9095)

**Python Installation Error:**

![image](https://github.com/oppia/oppia-android/assets/122200035/e1437cec-3583-4659-a77d-cda494ddeeb8)

**JNI Error while running sdkmanager with Java 8:**

![image](https://github.com/oppia/oppia-android/assets/122200035/824ec8ca-2c5d-4793-8d1e-1c74c5f3ed8f)

### What device/emulator are you using?

Windows 11

### Which Android version is your device/emulator running?

-

### Which version of the Oppia Android app are you using?

develop branch up-to-date as of 26/01/2024 

### Additional Context

Doesn't include instructions for Fedora 25+

**Comment by theMr17** [comment]
> 2. **Python 2:**
>    * The Python installation command needs updation to install Python2.

I would like to add on to this, installing python2 might give an error: `/usr/bin/env: 'python': No such file or directory` while building the project.

![photo1706411435](https://github.com/oppia/oppia-android/assets/84731134/0acacfcd-d38b-4a4a-961e-e8d823c23673)

This can be fixed by either installing `python-is-python3` instead of `python2`, or by creating a symlink: `sudo ln -s /usr/bin/python2 /usr/bin/python`. Reference: https://stackoverflow.com/a/61608129/16107797.

**Comment by Rd4dev** [comment]
@theMr17, Thanks for the additional context. I encountered the same issue and utilized the symbolic reference to address it. I'll ensure to include these details in the upcoming wiki update pull request.
