### ISSUE TITLE
[Feature Request]: Color Formatting Static Checks Messages

### ISSUE THREAD

**Issue by kkmurerwa** [oppia/oppia-android#5329]
### Is your feature request related to a problem? Please describe.

Currently, the output of static checks is presented uniformly in the same color, making it challenging to quickly distinguish failed checks from successful ones. To enhance the experience, color-formatted messages should be implemented for static checks. Specifically, if a static check fails, the corresponding error message should be displayed in red, providing an immediate visual cue for attention while, if the check succeeds, the message should be presented in green, indicating a positive outcome. Warning messages can also be output in yellow for easy scanning.

### Describe the solution you'd like

Shell provides a way to format the color of the output and we can use this to implement the feature. Using color codes, we can be able to implement a printer that takes in a string as a variable and formats it based on the type of message it is. Here is a shell script that can be used as a printer.

```sh
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

function echo_error() {
    echo -e "${RED}$1${NC}"
}

function echo_success() {
    echo -e "${GREEN}$1${NC}"
}

function echo_warning() {
    echo -e "${YELLOW}$1${NC}"
}
```

Example usage of this printer is as shown below;

```sh
# Import the printer file
source ./path/to/shell_printer.sh

echo_warning "This is a warning message" # Prints a yellow message

echo_error "This is an error message" # Prints a red message

echo_success "This is a success message" # Prints a green message
```

This [blog post](https://ioflood.com/blog/bash-color/) provides more insight on color formatting in shell.

**Comment by adhiamboperes** [comment]
@Tejas-67, PTAL.

**Comment by snehalchaudhari98** [comment]
Hi @adhiamboperes , if this issue is still available then I would love to work on this. This looks like a good point for someone new to start. If it's possible, can you please assign this issue to me?

**Comment by adhiamboperes** [comment]
@snehalchaudhari98, this issue is available. Could you please give an overview of you proposed solution? You can also open a draft pull request.

**Comment by aadityaguptaa** [comment]
Hi @adhiamboperes can I work on this Issue?

**Comment by adhiamboperes** [comment]
Hi,
Please tell us your idea of how to solve this, then we will assign it to you once we're aligned!

**Comment by aadityaguptaa** [comment]
Sure @adhiamboperes,

Here's a proposed solution: 

We'll refactor the color-formatting logic into a separate script, for ex. formatting_utils.sh. This script will contain the echo_error, echo_success, and other formatting functions. We can then source this script within all the scripts that static check script is executing. For example, Static_Checks.sh file is executing, checkstyle_lint_check.sh file. 
![image](https://github.com/oppia/oppia-android/assets/52538173/c5d2d491-dede-4686-aaf9-2d54041eeaaf)

So, in checkstyle_lint_check,sh file, 
![image](https://github.com/oppia/oppia-android/assets/52538173/944320c3-ef3a-4050-9eaa-abe8658ae523)
instead of calling "echo "Checkstyle issue found."" on line 26, we can call 
echo_error "CheckStyle issue found."

**Comment by aadityaguptaa** [comment]
@adhiamboperes
Sorry, the line no is not mentioned in the above Image, 

This is what I am trying to suggest:
![image](https://github.com/oppia/oppia-android/assets/52538173/15d820c8-4104-4726-9c35-033ccffbf659)

PS: ignore my bad handwriting, thanks

**Comment by aadityaguptaa** [comment]
Hey @adhiamboperes can I?

**Comment by dattasneha** [comment]
Hey @adhiamboperes I would like to work on this next by referring to the explanation provided in the issue description and previous comments. My approach would be creating 3 different functions to format the color for success, failure and warning messages in a  separate file and calling them from the necessary file.

**Comment by theMr17** [comment]
De-assigning @snehalchaudhari98 due to inactivity.

@dattasneha assigning you the issue, feel free to work on this next.
