### ISSUE TITLE
[BUG]: Background doesn't update with theme change in Lessons Screen

### ISSUE THREAD

**Issue by dmdbilal** [oppia/oppia-android#5340]
### Describe the bug

When I change the theme from light to dark, the background color remains in white. 

### Steps To Reproduce

Go to any topic > Lessons

### Expected Behavior

The background should change as like the Revision tab.

## Light Theme:
<img src="https://github.com/oppia/oppia-android/assets/91405690/058159aa-a9f2-4403-ac79-40d8c20f0ce5" width="200" alt="Screenshot 1">

## Dark Theme:
<img src="https://github.com/oppia/oppia-android/assets/91405690/46703930-16fb-42c1-a25d-d54a9fd8ee4b" width="200" alt="Screenshot 2">

### What device/emulator are you using?

Vivo S1 Pro

### Which Android version is your device/emulator running?

Android 12

### Which version of the Oppia Android app are you using?

1.0

**Comment by ShubhadeepKarmakar** [comment]
https://github.com/oppia/oppia-android/assets/99060332/4bf03805-3a58-497c-87c6-3e7b74379d0f

I have run this app on multiple devices(Pixel 3a, Nexus 9, Redmi Note 9 Pro) and everything works fine. I mean there is no error in dark mode compatibility.

**Comment by dmdbilal** [comment]
Yup, Actually my local repo is not updated to the latest. That's why this happened,
