### ISSUE TITLE
[BUG]: Weird characters in Fractions lessons 

### ISSUE THREAD

**Issue by quebrale** [oppia/oppia-android#5346]
### Describe the bug

Text from Fractions lessons is incorrect

### Steps To Reproduce

**Goto Lesson Fractions --> Lesson 3 --> Keep going until you issue image below**

![Screenshot_20240218_170053_org oppia android](https://github.com/oppia/oppia-android/assets/77162808/f8f1de58-39d8-4aa0-81f8-0f5b0bbd3d6b)

**Goto Lesson Fractions --> Lesson 4 --> Keep going until you issue image below**
![Screenshot_20240218_170728_org oppia android](https://github.com/oppia/oppia-android/assets/77162808/41284e99-4225-40bd-8f8c-38c574a82f15)

### Expected Behavior

Lesson 3 bug should be replaced by the word: "são"
Lesson 4 bug should be replaced by the word: "não" 

All with small case!

### What device/emulator are you using?

Huawei 9 Pro Lite 

### Which Android version is your device/emulator running?

Android 12

**Comment by seanlip** [comment]
Thanks for flagging, @quebrale, and sorry about that! Both of these have been fixed on the website. They should be fixed in the next release of the Android app as well.

Please do let us know if you find any other issues, thanks!
