### ISSUE TITLE
[BUG]: Error in addition and subtraction post test google form

### ISSUE THREAD

**Issue by EvaFunsho** [oppia/oppia-android#5359]
### Describe the bug

The 8th question on the addition and subtraction post test google form has an answer attached to it, and the answer is wrong. It says 89 -17= 23

### Steps To Reproduce

1. Go to task 1 contributor guide. 2. Scroll to instructions and click on 'pre and post-tests' link. 3. Scroll and click on 'Post test - Addition & Subtraction' 4. Scroll to question 8

### Expected Behavior

I expect to see a question without an answer attached to it to avoid distracting any student taking the test

### Screenshots/Videos

![1710366275509](https://github.com/oppia/oppia-android/assets/162186174/b279194f-c83d-40ef-a4a4-a07e1ca15d9f)

### Which Android version is your device/emulator running?

Android 11

### Which version of the Oppia Android app are you using?

0.12-beta-01f4111508

### Additional Context

If not resolved as soon as possible, it can affect the credibility of the tests.

**Comment by seanlip** [comment]
Thanks for reporting this @EvaFunsho. This is now fixed.

Also please note that, in future, bugs not related to the app should be filed at lessons-team instead: https://github.com/oppia/lessons-team/issues . Thanks!
