### ISSUE TITLE
The "Close" tab in the exploration player is not working

### ISSUE THREAD

**Issue by ivutha2** [oppia/oppia-android#5363]
The close tab is not working ![image](https://user-images.githubusercontent.com/117735796/227208569-1476d241-a5f9-4f4e-a526-6457f54d3625.jpeg)

**Comment by Chidinma-Egwuogu** [comment]
Hi @ivutha2, this might not be the right place to raise issues. The Outreachy/Oppia Project Site says issues should be raised here: https://github.com/oppia/oppia/issues

**Comment by ivutha2** [comment]
Thank you @Chidinma-Egwuogu

**Comment by Chidinma-Egwuogu** [comment]
You're welcome @ivutha2 , no worries

**Comment by seanlip** [comment]
Note: Moved to CLaM team from the lessons-team repo, since this issue is platform-related.

**Comment by theMr17** [comment]
It appears that the author might have misunderstood the intent of the close button. The button is meant to close only the `BottomSheetOptionsMenu`, rather than closing the entire exploration. Based on my analysis, it seems that the button is working as intended by closing the menu when clicked.

**Comment by seanlip** [comment]
Ah ok, thanks @theMr17! I think we can close this for now, then.
