### ISSUE TITLE
[Feature Request]: Make Changes to Download Script

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5365]
### Is your feature request related to a problem? Please describe.

There are changes required in the download script in https://github.com/oppia/oppia-android/pull/4885 to incorporate classroom-specific workflows. Because the script relies on farmiliarity with multiple repositories, we want to streamline some parts of the script in order to simplify work for the GSoC multiple classrooms project.

### Describe the solution you'd like

We want to modify the classroom structure so that the topic dependecy graph is baked in to it. We want to make changes to the TopicDto to pass in classroom name and other known information like the dependency graph.

This issue tracks defining the classroom structure and incorporating the topic dependency list into the download script.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by BenHenning** [comment]
So I've been working on addressing this. While the changes aren't yet final, I think my work will cover all of the following:
- Introducing a new ClassroomRecord to include the topic dependencies graph & other classroom information.
- Remove TopicIdList in favor of the above.
- Updating TopicController and TopicListController to use this dependency graph, and to assume exactly one classroom by default (to load the list of topic IDs).
- Updating the JSON loading pipeline & affected tests, where needed, to load correctly.
- Update the download asset script to include:
  - A proper GAE DTO for classroom data.
  - A v2 representation (as part of oppia-proto-api) that correctly encapsulates classroom changes and topic dependencies (this is a WIP and not yet pushed).
  - Correct conversion to the new v1 protos being introduced in the Oppia Android proto folder (see above).

What's NOT being included:
- Localization work for classroom data (the structures are being added for v2 for correctness, but nothing extra is being done for v1 objects).
- Classroom-specific tests for the topic loading pipeline.

Note also that the topic dependency graph for test topics will be hardcoded in the script as we don't yet have a way to load them from a local instance of Oppia web (though this is a long-term plan).

The above should remove any need to make changes to the download script, ensure a working app version with classroom data, and remove a pretty large chunk of the classroom changes in the domain and data layers (but not all of it).

**Comment by BenHenning** [comment]
This was actually completed in the commit linked above, so closing this now.
