### ISSUE TITLE
Talkback reads 14 underscore in a question in What is a ratio chapter

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#5381]
**Describe the bug**
Talkback reads 14 underscore in a question in What is a ratio chapter

**To Reproduce**
Pre- requisite: Enable Talkback
1. Go to 'Ratios and Proportions'
2. Click on 'What is Ratio'
3. Click on Continue till you reach to page 'James turned the page and saw a recipe for banana smoothie.'

Actual behavior:
Talkback is reading 14 underscores. This might be a bit difficult for users to understand that it is a blank left for a question

**Demonstration**
![Screenshot_2022-12-12-15-39-57-27_943a62cb4c6fb83e010e1c2e82766a17](https://user-images.githubusercontent.com/101634267/207021790-f06bec14-05b5-4e47-993c-b388e666a4e7.jpg)

Device/emulator being used: One plus nord2 5g
Android or SDK version (e.g. Android 5 or SDK 21): Android version 12
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by BenHenning** [comment]
Is this also an issue with ChromeVox or other web screenreaders for Oppia web @KolliAnitha?

**Comment by KolliAnitha** [comment]
@BenHenning, Chromevox also reads 'We’ll need to mix milk and banana puree in the ratio 14 underscores.'

**Comment by BenHenning** [comment]
Thanks @KolliAnitha.

This seems like a content issue that needs to be addressed, then. Sending over to the content team to figure out how they want to handle this.

**Comment by Kebith** [comment]
Confirming from the lesson review team that this issue has been fixed.

**Comment by seanlip** [comment]
@Kebith Just wanted to double-check this one -- could you please confirm how Talkback currently reads the sentence? Thanks!

**Comment by Kebith** [comment]
@seanlip 
Reads as "We'll need to mix milk and banana puree in the ratio (silence).

Can you complete..."

**Comment by seanlip** [comment]
Thanks @Kebith! Just to double-check, are you listening to the voiceovers, or to Talkback? 

Voiceovers are human-created recordings of the content in the app, but Talkback refers to functionality on the app specifically for e.g. screenreader users (and it has to be enabled through the Accessibility menu). So just wanted to make sure we're looking at the right thing here before closing it.

**Comment by Kebith** [comment]
Oh! I was listening to the voiceovers, not talkback. Sorry!

Not sure I know how to access the talkback.

**Comment by seanlip** [comment]
Ah ok, thanks! I'll discuss it with @BenHenning when we meet next.

**Comment by seanlip** [comment]
Discussed with @BenHenning -- let's treat "2+ underscores, with space/punctuation on both sides" as a single token for speech purposes, and read it as "blank". This representation should be generated as part of the Android data import pipeline, so moving this issue back to the Android repo.

**Comment by Nik-09** [comment]
> 2+ underscores, with space/punctuation on both sides

@seanlip Can you please help me to understand the rationale behind 2+ underscores? If the lessons contain only '__' (two underscores) between words, how do we want the voiceover to say this?

This is important for understanding the requirements for designing the [Automatic voiceover project](https://github.com/oppia/oppia/issues/16837).

Thank you

**Comment by seanlip** [comment]
@Nik-09 I think we would still say "blank" in that case. Only for a single underscore would we say "underscore".
