### ISSUE TITLE
[BUG]: Setup instructions for JDK 8 on Mac no longer work

### ISSUE THREAD

**Issue by kkmurerwa** [oppia/oppia-android#5384]
### Describe the bug

When working with the [Bazel setup instructions for Mac](https://github.com/oppia/oppia-android/wiki/Bazel-Setup-Instructions-for-Mac), the step involving installing JDK 8 using AdoptOpenJDK and Homebrew no longer works and gives the error below.
<img width="1440" alt="image" src="https://github.com/oppia/oppia-android/assets/18438114/3869bbd6-52f6-47e3-84dd-08340771af93">

This issue happens because the adoptopenjdk cask is being deprecated in favour of temurin.

### Steps To Reproduce

Uninstall your AdoptOpenJDK8 and try to reinstall it using the instructions on step 3 of the [Bazel Mac setup page](https://github.com/oppia/oppia-android/wiki/Bazel-Setup-Instructions-for-Mac).

### Expected Behavior

I expect the installation to go on as expected.

To fix this issue, follow the steps below as described in the solution [for this issue](https://github.com/devhubapp/homebrew-devhub/issues/5).

1. Untap the AdoptOpenJDK Cask 
```bash
brew untap AdoptOpenJDK/openjdk
```

2. Update cask versions
```bash
brew tap homebrew/cask-versions
```

3. Install Temurin in the place of the AdoptOpenJDK cask
```bash
brew install --cask temurin8
```

### What device/emulator are you using?

Pixel 3a

### Which Android version is your device/emulator running?

Android 10

### Additional Context

To work on this Issue, you need a Macbook. Test out the wiki instructions and apply the suggestion in this issue. If it works, create a PR to update the wiki.

While working on this issue, be sure to note down any issues you encounter during bazel set up.

**Comment by adhiamboperes** [comment]
@kkmurerwa, per the information you have provided in the issue, What changes need to be made? Is it only updating the documentation to point to temurin instead of openjdk?

**Comment by kkmurerwa** [comment]
@adhiamboperes that is correct. The only change needed is switching from AdoptOpenJDK to Temurin.

**Comment by adhiamboperes** [comment]
@kkmurerwa, https://github.com/oppia/oppia-android/pull/4886 updates Bazel to 6.5, and openjdk11. Has support for adoptopenjdk11 also been deprecated?

**Comment by BenHenning** [comment]
Is this still needed @kkmurerwa / @adhiamboperes now that we're no longer using the local JDK for anything in Bazel?

**Comment by adhiamboperes** [comment]
@BenHenning, closing this since the jdk setup step has already been removed from the wiki.
