### ISSUE TITLE
[Feature Request]: Migrate away from onBackPressed()

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#5404]
### Is your feature request related to a problem? Please describe.

API 33 (introduced in #5222) deprecated onBackPressed: https://developer.android.com/reference/android/app/Activity#onBackPressed().

#5402 helped reveal which activities need updating:
- [x] app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity
- [x] app/src/main/java/org/oppia/android/app/administratorcontrols/appversion/AppVersionActivity
- [x] app/src/main/java/org/oppia/android/app/administratorcontrols/learneranalytics/ProfileAndDeviceIdActivity
- [x] app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedActivity
- [x] app/src/main/java/org/oppia/android/app/devoptions/markstoriescompleted/MarkStoriesCompletedActivity
- [x] app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/MarkTopicsCompletedActivity
- [x] app/src/main/java/org/oppia/android/app/options/ReadingTextSizeActivityPresenter
- [x] app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivityPresenter
- [x] app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter
- [x] app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivity
- [x] app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter
- [x] app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerActivityPresenter
- [x] app/src/main/java/org/oppia/android/app/walkthrough/end/WalkthroughFinalFragmentPresenter

### Describe the solution you'd like

As mentioned in https://developer.android.com/reference/android/app/Activity#onBackPressed(), the solution here seems to be to:
- No longer override ``onBackPressed`` directly.
- To use AndroidX (via ``androidx.activity.ComponentActivity#getOnBackPressedDispatcher()``) to register a backward-compatible back pressed handler.
- Migrate existing ``onBackPressed`` calls to the new dispatcher.

### Describe alternatives you've considered

The only alternative is not using AndroidX, but this isn't compatible with Oppia Android since the new deprecation started in SDK 33 (and the app's min supported SDK in 21).

### Additional context

Folks who work on this issue should ensure that back navigation behavior continues to work on changed activities & fragments, specifically:
- Using the back arrow or x button in the toolbar (if present) correctly navigates back to the previous activity.
- Using the system back button correctly navigates to the previous activity.
- If there's any special handling in the changed activity/fragment for tablets, navigation and split fragment displays should be verified on a tablet version of Android.

NB: The first work on this issue will require updating AndroidX core to a newer version.

**Comment by Tejas-67** [comment]
hey @BenHenning, I would like to work in this issue. please assign this to me.

**Comment by adhiamboperes** [comment]
Hi @Tejas-67, as you can see from the description, the issue has been broken down into activities. Please select 3-5 activities at a time, and raise a PR for those.

Please indicate which ones you are working on.

**Comment by uphargaur** [comment]
Hi @adhiamboperes  i would like  to work on this as @Tejas-67  is already working on them , can you please assign below 3 activities to me :- 

1. app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivity
2.  app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter
3.  app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerActivityPresenter
4.  app/src/main/java/org/oppia/android/app/walkthrough/end/WalkthroughFinalFragmentPresenter

**Comment by uphargaur** [comment]
@BenHenning  @adhiamboperes  can i work complete this task in all the activities

**Comment by adhiamboperes** [comment]
@uphargaur it looks like @Tejas-67 is working on all the activities as per https://github.com/oppia/oppia-android/pull/5427. PTAL at other good first issues here: https://github.com/oppia/oppia-android/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22. A similar issue is https://github.com/oppia/oppia-android/issues/5405

**Comment by uphargaur** [comment]
@adhiamboperes  okay sure, i would work on issue #5405

**Comment by Vishwajith-Shettigar** [comment]
Hi @uphargaur, would you like to work on this ?

**Comment by uphargaur** [comment]
@Vishwajith-Shettigar  i am working on another issue ,once it get complete i will love to work on it

**Comment by dattasneha** [comment]
Hi @adhiamboperes, I'd like to work on the remaining activities, excluding the 4 being handled in PR #5441. I'm creating a draft PR to share my approach.

/cc @Vishwajith-Shettigar

**Comment by TanishMoral11** [comment]
Hey @BenHenning ,  I would like to work on this issue. please assign this to me.
-> app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivity

**Comment by adhiamboperes** [comment]
Hi @TanishMoral11, unfortunately, all the action items for this issue have been taken up.

**Comment by TanishMoral11** [comment]
Hi @adhiamboperes ,
No problem at all! If this issue needs to be assigned in the future, please feel free to send me a message. I'd be happy to help.

Thanks!
