### ISSUE TITLE
[Feature Request]: Provide instructions for updating the app's target API level and verifying compatibility.

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#5473]
### Describe the bug

We are getting regular emails from the Play Store roughly once a year that say:

"[Action required] Your app is affected by Google Play's target API level requirements"

These emails tell us that the app is targeting an old version of Android, and that we need to "meet target API level requirements".

The aim of this issue is threefold:

- [x] Write a wiki page that gives instructions on how to do this in the future (including the data-gathering process), so that any developer on the team can do it. (@BenHenning to do this.) 
- ~Fix the current app to correct the target API level requirements. Per the Google Play email, this must be done by 31 Aug 2024.~
- ~Establish an annual cadence for making these updates, such that they are completed well before we are warned about them by the Play Store.~

### Steps To Reproduce

N/A

### Expected Behavior

We should hopefully stop getting these emails if the app API level requirements are always correctly up-to-date.

### What device/emulator are you using?

N/A

### Which Android version is your device/emulator running?

N/A

### Which version of the Oppia Android app are you using?

N/A

**Comment by thanushree267** [comment]
Hi @seanlip , I just have a simple suggestion regarding the issue, just check for current Google Play's API requirements.
In 'build.gradle', update 'targetSdkVersion' to the latest required API level. Also, consider updating 'compileSdkVersion' to match or exceed the 'targetSdkVersion' .
Finally update the app's dependencies using Gradle dependency tool.

**Comment by adhiamboperes** [comment]
Thanks for the suggestion @thanushree267! If you'd like to contribute to Oppia Android, please take a look at our starter issues [here](https://github.com/oppia/oppia-android/issues?page=1&q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22), as well as more advance issues [here](https://github.com/orgs/oppia/projects/4/views/3?filterQuery=-status%3ADone), that are currently not assigned. Do also check out the [wiki](https://github.com/oppia/oppia-android/wiki) on how to get started.

**Comment by BenHenning** [comment]
NB: #5137 is useful to see what the upgrade process can look like, though we'll want to be more prescriptive in exactly the investigation and documentation steps that we take so that a general process may be defined.

**Comment by BenHenning** [comment]
FYI I removed the second item under the original task list since #5535 is tracking it separately.

As for the regular cadence, I'm not actually sure of a good way to do this short of responding to the reminder from Google Play Console. I'm not sure that GitHub has a good mechanism for "recurring audit"-type reminders. Do you have any suggestions @seanlip?

Edit: I spent a few minutes combing the GitHub extensions/actions marketplace for a tool like this, and didn't find anything that would directly help. It seems like a reasonable thing to exist, though.

**Comment by seanlip** [comment]
@BenHenning (and @adhiamboperes) I think it suffices for the Android tech leads to have a regular annual event on their calendar that says "[REMINDER] Update the target API level requirements for the Android app" (and perhaps this is shared with the Android team as well). 

This would presumably be scheduled for around the same time each year, about 3 or 6 months before the expected date of the Google reminder (depending on how long the update process typically takes). Do you think that would work?

**Comment by adhiamboperes** [comment]
> @BenHenning (and @adhiamboperes) I think it suffices for the Android tech leads to have a regular annual event on their calendar that says "[REMINDER] Update the target API level requirements for the Android app" (and perhaps this is shared with the Android team as well).
> 
> This would presumably be scheduled for around the same time each year, about 3 or 6 months before the expected date of the Google reminder (depending on how long the update process typically takes). Do you think that would work?

@seanlip, 3 months(around May) should suffice.

**Comment by BenHenning** [comment]
As a post-update: we now have https://github.com/oppia/oppia-android/wiki/Upgrading-Target-Sdk-Guide as the standard guide for performing SDK upgrades moving forward (with #5535 being the first SDK upgrade going through this process).

As for the regular cadence, I don't think it needs to be explicitly tracked as we already have a pretty good forcing function in the Play Console forcing us to upgrade each year. It's also a bit historically unusual to force SDK upgrades for subsequent years. It may be more important to address this on a regular cadence it this does become a regular thing for the Play Console moving forward.
