### ISSUE TITLE
Full UI: Options Navigation Drawer

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#550]
This issue is tracking hi-fi work of https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/2776cbb1-22b0-42c9-b70b-2136bdb361da/OP-Options-Menu-

**Comment by EdOates84** [comment]
@rt4914 I would like to work on this issue

**Comment by rt4914** [comment]
@EdOates84 This issue is currently blocked on some other work items. I will assign you some other issue and email you.

**Comment by EdOates84** [comment]
@rt4914 ok

**Comment by seanlip** [comment]
@EdOates84: welcome! Just a heads-up: please make sure to follow [these instructions](https://github.com/oppia/oppia-android/wiki) to get started before working on any issues.

**Comment by EdOates84** [comment]
@seanlip Ok I've done.

**Comment by rt4914** [comment]
Closed via #902
