### ISSUE TITLE
[BUG]: Limit repeated code coverage and APK/AAB report generations in PRs

### ISSUE THREAD

**Issue by Rd4dev** [oppia/oppia-android#5508]
### Describe the bug

The current implementation for generating code coverage and APK/AAB difference reports can lead to excessive noise in PR threads. This issue primarily affects the visibility and clarity of PR discussions.

#

### 1. Code Coverage Reports:
- **Current Behavior:** When a PR does not contain changes to .kt files, the code coverage report generated shows a "SKIP" status. This report is generated with every commit, regardless of whether there are changes in .kt files. Consequently, if there are no relevant changes in the PR, this can result in a flood of "SKIP" status updates, cluttering the PR thread.
- **Proposed Solution:** Implement a mechanism to check for changes in .kt files between commits. If no changes are detected, suppress the "SKIP" status report to avoid excessive notifications, while ensuring that developers are not confused about missing or outdated reports for subsequent commits if no new reports are uploaded.

**Skip coverage report:**

![image](https://github.com/user-attachments/assets/60cf1d68-0908-4db2-ab05-daf1d038192d)

<details>
<summary>An overloaded skip coverage report thread</summary>

![image](https://github.com/user-attachments/assets/60cf1d68-0908-4db2-ab05-daf1d038192d)

![image](https://github.com/user-attachments/assets/4205addd-dbd6-4c7e-9797-a86fa2a4c741)

![image](https://github.com/user-attachments/assets/081d25f7-ba3f-4759-8568-5c4fe19f174b)

![image](https://github.com/user-attachments/assets/b0f42ed4-c8cc-4e73-bca4-39d5f8f6f589)

![image](https://github.com/user-attachments/assets/930cbb60-debe-41bc-972a-9646b4c5701b)

![image](https://github.com/user-attachments/assets/9f8bb7b3-85a8-4afb-8863-d4e37843f1bf)

![image](https://github.com/user-attachments/assets/4841cb70-a550-4855-8449-10d32760f416)

![image](https://github.com/user-attachments/assets/798d57a3-1183-4ebf-b33f-3cdc56986036)

![image](https://github.com/user-attachments/assets/b53ed046-dc16-4c08-9fd0-57ba9f9b7cf7)

</details>

#

### 2. APK/AAB Difference Reports:
- **Current Behavior:** The APK/AAB diff report, as of filing the issue, is scheduled to run every day at 2:30 AM UTC (8:00 AM IST, 7:30 PM PT, daylight saving time). This aligns with the similar issue described above, as the reports posted to the PR thread could eventually become noisy.

**APK/AAB difference report:**

![image](https://github.com/user-attachments/assets/e13bc271-042b-4330-a94d-77906112c5d5)

<details>
<summary>An overloaded APK/AAB report thread</summary>

![image](https://github.com/user-attachments/assets/f419c77b-c41a-41ce-8bb2-875f27adf672)

![image](https://github.com/user-attachments/assets/8abdd326-88ed-47a8-95df-dd6b4a6ab61b)

![image](https://github.com/user-attachments/assets/b14503ed-37b4-4c6f-a57a-ab69d5b647ff)

![image](https://github.com/user-attachments/assets/062b0bd4-bdba-4974-8a83-f2d0f574638e)

</details>

#

### Intent

The goal is to enhance the developer experience by reducing unnecessary noise while ensuring that important updates are communicated effectively. Implementing these changes will help keep PR threads cleaner and more focused on relevant discussions.

#

### Steps To Reproduce

**Coverage Report:**
- Create a new pull request or update an existing one without making changes to .kt files.
- Add and commit changes to the PR.
- Wait for the CI/CD pipeline to run and observe the code coverage report. Note if it shows a "SKIP" status.
- Look at the PR thread to find the "SKIP" coverage status report is posted, even though no .kt files were changed.

**APK/AAB Report:**
- This open PR will produce APK/AAB reports at 2:30 AM UTC. 
- Observe if this results in excessive notifications in the PR thread.

### Expected Behavior

Both code coverage and APK/AAB reports should only post meaningful updates based on changes, ensuring clear and relevant updates in the PR thread.

**Comment by manas-yu** [comment]
@adhiamboperes We can check for changed Kotlin files using `KT_FILES_CHANGED=$(echo "$FILE_BUCKET_LIST" | grep -E '\.kt$' || true)` in compute_changed_files section in code_coverage.yml and set the can_skip_files property accordingly, which will help suppress unnecessary SKIP status updates.
cc: @Rd4dev

**Comment by Rd4dev** [comment]
@manas-yu, thanks for the suggestion! I’m currently working on this fix, including the adjustments for the duplicate coverages and AAB/APK comments, but feel free to explore other unassigned issues if you're interested.
