### ISSUE TITLE
[BUG][CRITICAL]: Github Actions upload artifact deprecated 

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5533]
### Describe the bug

All module test runs are failing with error:

`Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/`

### Steps To Reproduce

Push a commit to a new or existing PR.

### Expected Behavior

The actions should run to completion.

### Screenshots/Videos

<img width="1423" alt="Screenshot 2024-09-11 at 15 04 16" src="https://github.com/user-attachments/assets/6f20c458-b342-4188-a5e2-3e73effb453e">

### What device/emulator are you using?

CI

### Additional Context

https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

**Comment by theMr17** [comment]
For anyone planning to work on this, refer to commit https://github.com/oppia/oppia-android/pull/5528/commits/060caea5d34be1036294215b52996880f8c1ce1b for a quick fix.
