### ISSUE TITLE
[Feature Request]: Implement messages to celebrate successful first- and second-PR contributions

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#5547]
### Is your feature request related to a problem? Please describe.

On Web, we now have functionality (thanks to @HardikGoyal2003!) to send a congratulatory note when contributors submit their first and second PRs. See the following examples:

- https://github.com/oppia/oppia/pull/20998#issuecomment-2377774491
- https://github.com/oppia/oppia/pull/20999#issuecomment-2380747745

Per discussion with @BenHenning, we'd like to do this for Oppia Android too, so I'm filing this issue to track it.

### Describe the solution you'd like

Provide congratulatory messages when a new contributor submits their first and second PRs.

**Comment by HardikGoyal2003** [comment]
Reference: [Web repo issue](https://github.com/oppia/oppia/issues/20381) was fixed by this [PR](https://github.com/oppia/oppia/pull/20683)

Hello everyone, feel free to ask for help with this issue. I'm also available for developer onboarding discussions to plan management once the workflow is active. Thanks!

**Comment by Mayank77maruti** [comment]
Hello @HardikGoyal2003 , please assign this issue to me i am eager to complete it.

**Comment by HardikGoyal2003** [comment]
@MohitGupta121 PTAL!! Thanks!

**Comment by adhiamboperes** [comment]
Hi @Mayank77maruti, thanks for your interest in this issue! Could you please give a brief breakdown of how you propose to solve this issue? Then we can assign it to you.

**Comment by Mayank77maruti** [comment]
Hello @adhiamboperes Sir,

We can add a GitHub Action that will trigger when a PR gets merged into the develop branch. The action can be configured as follows:

In the .github/workflow directory, we will add this YAML file:

yaml
```

name: PR Merge Comment

on:
  pull_request_target:
    types: [closed]

permissions: write-all

jobs:
  comment-on-merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        env:
          AUTHOR: ${{ github.event.pull_request.user.login }}
          REPO: ${{ github.event.repository.name }}
          OWNER: ${{ github.event.repository.owner.login }}
        run: |
          echo "AUTHOR=${AUTHOR}" >> $GITHUB_ENV
          echo "REPO=${REPO}" >> $GITHUB_ENV
          echo "OWNER=${OWNER}" >> $GITHUB_ENV

      - name: Count merged PRs
        id: count-prs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const author = process.env.AUTHOR;
            const repo = process.env.REPO;
            const owner = process.env.OWNER;
            const { data } = await github.rest.search.issuesAndPullRequests({
              q: `repo:${owner}/${repo} type:pr state:closed author:${author}`
            });
            const prCount = data.items.filter(pr => pr.pull_request.merged_at).length;
            core.exportVariable('PR_COUNT', prCount);

      - name: Comment on the PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prCount = parseInt(process.env.PR_COUNT);
            const author = process.env.AUTHOR;
            const mention = 'HardikGoyal2003';  // Update this if the mention needs to change
            const prNumber = context.payload.pull_request.number;

            let message;
            if (prCount === 1) {
              message = `✨ **Fantastic work @${author}!** Your very first PR to Oppia has been merged! 🎉🥳\n\n` +
              `You've just taken your first step into open-source, and we couldn’t be happier to have you onboard. 🙌\n` +
              `If you're feeling adventurous, why not dive into another issue and keep contributing? The community would love to see more from you! 🚀\n\n` +
              `For any support, feel free to reach out to the developer onboarding lead: @${mention}. Happy coding! 👩‍💻👨‍💻`;
            } else if (prCount === 2) {
              message = `👏 **Well done @${author}!** Two PRs merged already! 🎉🥳\n\n` +
              `With your second PR, you're on a roll, and your contributions are already making a difference. 🌟\n` +
              `This means you may be eligible to join the Oppia dev team as a collaborator! 🎉 If you're interested, please fill out [this form](https://forms.gle/NxPjimCMqsSTNUgu5) and become an even more integral part of the community. 🌱\n\n` +
              `Looking forward to seeing even more contributions from you. The developer onboarding lead: @${mention} is here if you need any help! Keep up the great work! 🚀`;
            }
              
            if (prCount === 1 || prCount === 2) {
              await github.rest.issues.createComment({
                owner: process.env.OWNER,
                repo: process.env.REPO,
                issue_number: prNumber,
                body: message
              });
            }

```
This GitHub Action will be triggered by a pull request event, fetch the source and base branches, and perform a merge into the base branch. It will also handle authentication and sets a custom user name and email for the merge commit.

**Comment by HardikGoyal2003** [comment]
Hey @Mayank77maruti, please ensure the workflow includes the username of the Android developer onboarding lead, not the web lead. Thanks!

cc: @adhiamboperes

**Comment by Mayank77maruti** [comment]
Ok sir , I would make sure.

**Comment by Mayank77maruti** [comment]
Hey @HardikGoyal2003 sir should i make a pr regarding this issue or wait to be assigned for the issue.

**Comment by adhiamboperes** [comment]
@Mayank77maruti, please create a Par and assign it to me.

**Comment by Mayank77maruti** [comment]
Hey @adhiamboperes , I have made a pr regarding this issue,
please do have a look.
Thank you.
