### ISSUE TITLE
Create one central utility file from where we should access date format or even convert date timestamp to string from that file.

### ISSUE THREAD

**Issue by jamesxu0** [oppia/oppia-android#555]

**Comment by jamesxu0** [comment]
This issue was brought up in PR #543. We need to move all date timestamp conversion to one file to have consistency across the app.

**Comment by anandwana001** [comment]
is this issue solved?

**Comment by rt4914** [comment]
> is this issue solved?

@anandwana001 No, and now it would be nice time to do it. You can self assign this issue to yourself.

**Comment by anandwana001** [comment]
I tried with this issue, got few points before making a PR. 

We have two things here: 
1. multiple date formats to choose from
```
val dd_MMM_yyyy = "dd MMM yyyy"
val hh_mm_a = "hh:mm a"
val dd_MMMM_yyyy = "dd MMMM yyyy"
val dd_MMMM_yyyy_zzzz = "dd MMMM yyyy zzzz"
```

2. Convert timestamp to string
```
fun formatDateFromDateString(
    inputDateFormat: String,
    timestamp: Long,
    locale: Locale = Locale.getDefault()
  ): String {
    return try {
      val sdf = SimpleDateFormat(inputDateFormat, locale)
      val dateTime = Date(timestamp)
      sdf.format(dateTime)
    } catch (e: Exception) {
      e.toString()
    }
  }
```

Now, using this singleton class anywhere in the codebase we can have consistency across the app.

**Comment by rt4914** [comment]
> I tried with this issue, got few points before making a PR.
> 
> We have two things here:
> 
> 1. multiple date formats to choose from
> 
> ```
> val dd_MMM_yyyy = "dd MMM yyyy"
> val hh_mm_a = "hh:mm a"
> val dd_MMMM_yyyy = "dd MMMM yyyy"
> val dd_MMMM_yyyy_zzzz = "dd MMMM yyyy zzzz"
> ```
> 
> 1. Convert timestamp to string
> 
> ```
> fun formatDateFromDateString(
>     inputDateFormat: String,
>     timestamp: Long,
>     locale: Locale = Locale.getDefault()
>   ): String {
>     return try {
>       val sdf = SimpleDateFormat(inputDateFormat, locale)
>       val dateTime = Date(timestamp)
>       sdf.format(dateTime)
>     } catch (e: Exception) {
>       e.toString()
>     }
>   }
> ```
> 
> Now, using this singleton class anywhere in the codebase we can have consistency across the app.

@anandwana001 I think this should work directly.

**Comment by anandwana001** [comment]
> > I tried with this issue, got few points before making a PR.
> > 
> > We have two things here:
> > 
> > 1. multiple date formats to choose from
> > 
> > ```
> > val dd_MMM_yyyy = "dd MMM yyyy"
> > val hh_mm_a = "hh:mm a"
> > val dd_MMMM_yyyy = "dd MMMM yyyy"
> > val dd_MMMM_yyyy_zzzz = "dd MMMM yyyy zzzz"
> > ```
> > 
> > 1. Convert timestamp to string
> > 
> > ```
> > fun formatDateFromDateString(
> >     inputDateFormat: String,
> >     timestamp: Long,
> >     locale: Locale = Locale.getDefault()
> >   ): String {
> >     return try {
> >       val sdf = SimpleDateFormat(inputDateFormat, locale)
> >       val dateTime = Date(timestamp)
> >       sdf.format(dateTime)
> >     } catch (e: Exception) {
> >       e.toString()
> >     }
> >   }
> > ```
> > 
> > Now, using this singleton class anywhere in the codebase we can have consistency across the app.
> 
> @anandwana001 I think this should work directly.

This may help if in future we need multiple date formats like showing date time to user in exploration and much more. Bringing all types at one place will help. 
Should we proceed with it?

**Comment by rt4914** [comment]
> > > I tried with this issue, got few points before making a PR.
> > > We have two things here:
> > > 
> > > 1. multiple date formats to choose from
> > > 
> > > ```
> > > val dd_MMM_yyyy = "dd MMM yyyy"
> > > val hh_mm_a = "hh:mm a"
> > > val dd_MMMM_yyyy = "dd MMMM yyyy"
> > > val dd_MMMM_yyyy_zzzz = "dd MMMM yyyy zzzz"
> > > ```
> > > 
> > > 
> > > 
> > > 1. Convert timestamp to string
> > > 
> > > ```
> > > fun formatDateFromDateString(
> > >     inputDateFormat: String,
> > >     timestamp: Long,
> > >     locale: Locale = Locale.getDefault()
> > >   ): String {
> > >     return try {
> > >       val sdf = SimpleDateFormat(inputDateFormat, locale)
> > >       val dateTime = Date(timestamp)
> > >       sdf.format(dateTime)
> > >     } catch (e: Exception) {
> > >       e.toString()
> > >     }
> > >   }
> > > ```
> > > 
> > > 
> > > Now, using this singleton class anywhere in the codebase we can have consistency across the app.
> > 
> > 
> > @anandwana001 I think this should work directly.
> 
> This may help if in future we need multiple date formats like showing date time to user in exploration and much more. Bringing all types at one place will help.
> Should we proceed with it?

Yeah, this does work, you can create a PR for this.

**Comment by anandwana001** [comment]
I just checked and found a class called `DateTimeUtil`, I think rather than creating a new file for this we can put our method in this class. This class is also responsible for doing things with Date and Time.

**Comment by anandwana001** [comment]
**Seeking suggestion**

 I had created a utility class making it a `@Singleton`, which makes it hard to inject in binding adapters file. This will require to create an object everywhere in all methods. 
`val oppiaDateTimeFormatter = OppiaDateTimeFormatter()`

Also, tried using the `object` for creating this utility class which makes everything easily accessible. 
But, I didn't find anywhere in the whole codebase where object files are used. 

Is there anything specific regarding object usage? As far as I know, `object` bring some issues with testing and also not allow dagger injection.
