### ISSUE TITLE
[BUG]: Static Checks Developer Video Link is Broken

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5578]
### Describe the bug

The link to the explainer videos for static checks to support developers is broken.

### Steps To Reproduce

1. Go to https://github.com/oppia/oppia-android/wiki/Interpreting-CI-Results
2. Click on the link to the developer video
3. See that the video is missing

### Expected Behavior

Open the Youtube video.

### Screenshots/Videos

![Screenshot 2024-11-18 at 14 48 16](https://github.com/user-attachments/assets/15dbb5d7-0ed8-4e56-9fb3-12dff84a6027)

**Comment by adhiamboperes** [comment]
@MohitGupta121, I cross checked the [developer channel](https://www.youtube.com/@oppiadeveloperteam5755) but the Static checks video is not there. Could you please work with Sean to upload the video so we can fix the Wiki?

**Comment by MohitGupta121** [comment]
@adhiamboperes Yes, I know these all videos now moves to Oppia offical channel. I making PR for that. Thanks for filing this issue.

**Comment by adhiamboperes** [comment]
@MohitGupta121, the Accessibilty video links are working correctly. Only the CI one is missing.

**Comment by seanlip** [comment]
Is this what you are looking for? https://www.youtube.com/watch?v=HLzHQULZbJE

**Comment by MohitGupta121** [comment]
@adhiamboperes basically I pinged Sean already when these videos moved from Oppia-Developer to Oppia official channel, basically they now completely deleting devloper channel. That's why now I replaced links with Oppia offical channel to be in safer side. Now this is [Developers Playlists](https://youtube.com/playlist?list=PLZv00rFZtOxW9ozKxHj7DHIz4IlMR2Yhj&si=MAivTXvsa8QsOT2a) where we find all videos

**Comment by adhiamboperes** [comment]
> Is this what you are looking for? https://www.youtube.com/watch?v=HLzHQULZbJE


Yes, thanks @seanlip.

**Comment by adhiamboperes** [comment]
> @adhiamboperes basically I pinged Sean already when these videos moved from Oppia-Developer to Oppia official channel, basically they now completely deleting devloper channel. That's why now I replaced links with Oppia offical channel to be in safer side. Now this is [Developers Playlists](https://youtube.com/playlist?list=PLZv00rFZtOxW9ozKxHj7DHIz4IlMR2Yhj&si=MAivTXvsa8QsOT2a) where we find all videos


Seen, thanks!
