### ISSUE TITLE
[BUG]: The sentence "Before you start, make sure you know how to count to 100 "is duplicated when translating to Portuguese language

### ISSUE THREAD

**Issue by cam-pinheiro** [oppia/oppia-android#5590]
### Describe the bug

The sentence "Before you start, make sure you know how to count to 100" is duplicate when switching English to Portuguese language.

### Steps To Reproduce

1. In Home, select a Topic Place Values
2. Select the Chapter "What are the Place Values?"
3. In menu button select "Options"
4. Chenge the App language to Portuguese
5. Go back to the Chapter
6. See the sentence "Antes de comecar, certrifique-se de que voce sabe contar a te 100" is been shown twice.

### Expected Behavior

It is expected not see duplicated sentences after switch the language to Portuguese. 

### Screenshots/Videos

![oppia-sentence](https://github.com/user-attachments/assets/f8d7ffde-037f-412d-bc19-0dff70fef894)

### Which Android version is your device/emulator running?

Android 14

### Which version of the Oppia Android app are you using?

0.13-beta-dcde7b359e

**Comment by KaranJoshi1208** [comment]
I am working on it .

**Comment by seanlip** [comment]
@KaranJoshi1208 This is not the way to claim an issue. Please see the instructions on our [wiki](https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android#3-pick-your-first-starter-issue) and follow them for all future issues.

@cam-pinheiro Thanks for reporting this! It was a content issue and I confirm it's been fixed on the website. It will be added to the Android app in the next Android app release. Moving this to the lessons-team repo and marking as fixed.
