### ISSUE TITLE
[BUG]: Submit Button Stays Disabled After Linking Items in Drag-and-Drop Input

### ISSUE THREAD

**Issue by Rd4dev** [oppia/oppia-android#5592]
### Describe the bug

In the Drag and Drop Sort Interaction when items are linked to represent equivalence (e.g., 0.6 and 3/5), the linked states are not recognized as different from the unlinked states, keeping the submit button disabled.

### Steps To Reproduce

1. Open the "Prototype Exploration".
2. Play through to the "Second Drag & Drop interaction".
3. Arrange the items in the order: 0.6, (unlinked) 3/5, 0.46, 0.35 and attempt to submit.
4. The app will indicate that the order is incorrect.
5. Click submit again with unchanged solution.
6. The Submit button will be disabled mentioning to arrange first.
7. Link 0.6 and 3/5, arranging them as 0.6, (linked) 3/5, 0.46, 0.35.
8. Despite the correct arrangement or change in the link states, the submit button will still remain disabled, preventing the successful submission of the answer.

### Expected Behavior

The submit button should enable immediately after there is a change in the link states.

### Screenshots/Videos

https://github.com/user-attachments/assets/191e8b52-7c74-4f9d-b721-7b967813c5e1

### What device/emulator are you using?

Pixel 2 [Emulator]

### Which Android version is your device/emulator running?

API 28

**Comment by adhiamboperes** [comment]
Suggested fix to follow example in https://github.com/oppia/oppia-android/pull/5323.

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes , Can I work on it?
