### ISSUE TITLE
Wiki needs a new page for Assignees and Reviewers Flow

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#571]
The difference between Assignees and Reviewers role in PR is not that obvious in document. TO make sure that the use of Assignees and Reviewers is understood clearly we need a separate page with an example in which it gets clear how to use them.

**Comment by BenHenning** [comment]
@rt4914 does https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section solve this issue?

**Comment by rt4914** [comment]
@BenHenning It does solves the issue. I created this issues, updated the wiki but forgot to close this issue. Thanks. Closing it now.
