### ISSUE TITLE
Keyboard should be visible by default in Admin PIN

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#572]
![Screenshot_1577256328](https://user-images.githubusercontent.com/9396084/71435781-886c9980-2710-11ea-9893-8a12857b093f.png)

In the above screen, the user will need to click the first edittext box to make the keyboard visible and then start typing the PIN.

To improve the UX, the keyboard should be directly visible to reduce that one extra click.
Also, write test case for this functionality in the respective file too.

**Comment by PrarabdhGarg** [comment]
@Luffy18346 can I solve this issue?

**Comment by rt4914** [comment]
@PrarabdhGarg this has already been solved by @Luffy18346 the PR is already out there. Also those issues which are not assigned to someone you can take that.Also for now I have assigned you a new issue you can work on that for now.
