### ISSUE TITLE
Full UI: Switch Profile Option in Navigation Drawer

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#590]
The Navigation Drawer needs `Switch Profile` option. (The svg file for the icon will be shared on email.)
<img width="368" alt="Screenshot 2020-01-06 at 2 58 29 PM" src="https://user-images.githubusercontent.com/9396084/71809219-a08bd380-3095-11ea-92c3-73e1970d4e9a.png">

When learner clicks on this option, it should open the alert dialog which is shown when learner presses back button on home screen.
<img width="367" alt="Screenshot 2020-01-06 at 2 58 39 PM" src="https://user-images.githubusercontent.com/9396084/71809270-be593880-3095-11ea-8f09-734e0f441afd.png">

Also, add test cases to test this functionality.

## Checklist
- [ ] Change the text of `home_activity_back_dialog_message` in strings.xml file as per mocks.
- [ ] Add `Switch Profile` option along with its functionality.
- [ ] Add test cases for the `Switch Profile` options. (Check `NavigationDrawerTestActivity` and `NavigationDrawerTestActivityTest` files for writing test cases)

**Comment by rt4914** [comment]
This PR is assigned to new contributor @maheshpaliwal

**Comment by rt4914** [comment]
Unassigning @maheshpaliwal from this PR as it has been too long. Also, he has one more assigned PR to him so will wait for that to finish.

**Comment by rt4914** [comment]
Assigning this to @PrarabdhGarg now.

**Comment by PrarabdhGarg** [comment]
@rt4914 From where can I get the icon?

**Comment by rt4914** [comment]
> @rt4914 From where can I get the icon?

I have emailed you an SVG file just now.

**Comment by PrarabdhGarg** [comment]
Also, I feel that the flow would be much better if we showed the dialog after closing the side navigation drawer instead of the current flow

**Comment by rt4914** [comment]
> Also, I feel that the flow would be much better if we showed the dialog after closing the side navigation drawer instead of the current flow

Thanks a lot for the suggestion. For now, you can finish this task as mentioned in the mocks and I will discuss that with the designer about this.
