### ISSUE TITLE
In admin auth screen in add profile submit button and actionDone button issue and test cases.

### ISSUE THREAD

**Issue by nikitamarysolomanpvt** [oppia/oppia-android#591]
In admin auth screen in add profile submit button should be visible above keyboard, when keyboard is displayed.
`DONE` / `TICK` in keyboard should submit the pin automatically.

Also, we need to add test cases too, like:

1. Submit button is displayed by default
2. Submit button is active only when 5 characters are entered.

**Comment by anandwana001** [comment]
Same issue in the `AdminPinActivity`
1. Save button should be visible above the keyboard, when the keyboard is displayed
2. `DONE` / `TICK` in keyboard should submit the pin automatically
