### ISSUE TITLE
Issue in Domain on-boarding flow

### ISSUE THREAD

**Issue by nikitamarysolomanpvt** [oppia/oppia-android#599]
Fix #565: Domain on-boarding flag #574
<img width="1628" alt="small" src="https://user-images.githubusercontent.com/54615666/72054448-02934580-32ef-11ea-9201-56d28622a978.png">

**Comment by rt4914** [comment]
@nikitamarysolomanpvt please write steps to reproduce this issue.

**Comment by nikitamarysolomanpvt** [comment]
@rt4914 Just need to run test-cases.

**Comment by anandwana001** [comment]
@rt4914 Looks like `OnBoardingFlowControllerTest` file doesn't exist anymore.

**Comment by rt4914** [comment]
This file was renamed in https://github.com/oppia/oppia-android/pull/1397/files .
Also, this is no more an issue the last reference that we have for this is #1397 which must have fixed this automatically. Therefore closing this issue.
