### ISSUE TITLE
Low fi Landscape: Add Admin Password screen

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#620]
Mock:
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/acdbeb30-745f-46da-b0fd-3d6a83f83937/PC-SP-Add-PIN-Dialog-Empty-

Landscape design for Add admin password is needed. 

## Checklist
- [ ] Landscape working correctly
- [ ] Test cases for landscape mode.

**Comment by rt4914** [comment]
Assigned to @netomarin

**Comment by netomarin** [comment]
Hi @rt4914, can you assign the issue to me?
You commented but assigned to yourself.

Thanks

**Comment by rt4914** [comment]
@netomarin Assigned it to you. Thanks

**Comment by rt4914** [comment]
> @netomarin Assigned it to you. Thanks

Unassigned @netomarin from this issue.

**Comment by rt4914** [comment]
Assigned to @NullByte08

**Comment by Kushal-Gera** [comment]
can you please assign it to me

**Comment by rt4914** [comment]
> can you please assign it to me

This has been assigned to @NullByte08
