### ISSUE TITLE
Shift StoryTesting files to testing package

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#623]
`StoryFragmentTestActivity` and `StoryFragmentTestActivityPresenter` files are currently in **app** module -> **story** -> **testing** package. 

Shift this to **app** module -> **testing** package. 

Also, where these files are getting used like `story_fragment_test_activity.xml`, fix those usage too.

**Comment by netomarin** [comment]
@rt4914 if nobody is currently working on this issue, I can take it.

**Comment by seanlip** [comment]
Hi @netomarin, go for it, I've assigned you!

**Comment by rt4914** [comment]
> Hi @netomarin, go for it, I've assigned you!

Unassigned @netomarin from this issue.

**Comment by rt4914** [comment]
Assigned to @NullByte08
