### ISSUE TITLE
Lowfi Landscape: Admin Auth Screen

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#628]
Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/a0c84710-3970-4488-beea-6fe6abbdb38a/PC-MP-Admin-Authorization-Admin-Controls-Empty-

Landscape design of admin auth screen. Also add tests case for this implementation.

**Comment by rt4914** [comment]
Assigning this to @PrarabdhGarg

**Comment by PrarabdhGarg** [comment]
Currently, do I have to implement only the UI, or add functionality to the screen as well?

**Comment by PrarabdhGarg** [comment]
@rt4914 for the resource directory, should I keep only the device orientation as the qualifier, or should I also specify some other qualifiers?

**Comment by rt4914** [comment]
> Currently, do I have to implement only the UI, or add functionality to the screen as well?

UI and functionality already exists in the code in portrait mode. You just need to make sure that the UI works on landscape mode too. Along with test cases.

For reference you can have a look at these PRs: https://github.com/oppia/oppia-android/pull/625
https://github.com/oppia/oppia-android/pull/611

Do keep in mind that these PRs are not yet finished, but you can get the idea from these.

**Comment by PrarabdhGarg** [comment]
@rt4914 the text in the mockup seems to be of a different screen. Should I keep the same text as that of the portrait screen, or should I keep it according to the mockup?

**Comment by rt4914** [comment]
> @rt4914 the text in the mockup seems to be of a different screen. Should I keep the same text as that of the portrait screen, or should I keep it according to the mockup?

Yes, feel free to change the text. Match the text with mock in landscape as well as portrait mode.
