### ISSUE TITLE
Limitation of ActivityScenario's Launch Method - Found in Kitkat 

### ISSUE THREAD

**Issue by nikitamarysolomanpvt** [oppia/oppia-android#629]
The test-cases which use ActivityScenario are failing throughout oppia-android tests when tested in Kitkat.
<img width="1375" alt="small" src="https://user-images.githubusercontent.com/54615666/73167454-e4ff1200-411d-11ea-8227-85cd935736a4.png">

**Comment by nikitamarysolomanpvt** [comment]
@BenHenning found two use full links, please suggest.
https://stackoverflow.com/questions/53598321/androidx-test-activityscenario-java-lang-assertionerror-activity-never-becomes

https://github.com/android/android-test/issues/143

**Comment by MaskedCarrot** [comment]
May I work on it ?

**Comment by MaskedCarrot** [comment]
@anandwana001 I would like to work on it.

**Comment by anandwana001** [comment]
@MaskedCarrot Any update on this?

**Comment by MaskedCarrot** [comment]
@anandwana001 I have not been able to figure out the cause of this behavior.

**Comment by anandwana001** [comment]
Looking into this, will send a starter pr, and you can follow after that.

**Comment by seanlip** [comment]
Per https://github.com/oppia/oppia-android/issues/5012, we are deprecating support for Android KitKat, so this issue is no longer valid.
