### ISSUE TITLE
Lowfi Landscape mode for StoryActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#634]
Mock Link:
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/cce938d6-e079-4761-bac0-8bde22ac6348/TP-CL-Auto-Scroll-Button-

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/2cf61633-3197-4445-adb0-b58fbe418b11/TP-CL-Auto-Scroll-Button-

## Checklist
- [ ] Landscape mode UI
- [ ] Test cases for landscape mode.

**Comment by rt4914** [comment]
Assigning this to @PrarabdhGarg

**Comment by PrarabdhGarg** [comment]
@rt4914 where do I write the tests for the Story Activity? In the file that is present in the app package, or the file present in the sharedTest package?
Also, why are there two files serving the same purpose?

**Comment by rt4914** [comment]
> @rt4914 where do I write the tests for the Story Activity? In the file that is present in the app package, or the file present in the sharedTest package?
> Also, why are there two files serving the same purpose?

The file which is present in the sharedTest `StoryFragmentTest` https://github.com/oppia/oppia-android/blob/develop/app/src/sharedTest/java/org/oppia/app/story/StoryFragmentTest.kt

The testing package in app module is actually for those items which needs to be tested separately and cannot be tested in regular android app structure. So in such cases, we create a dummy activity which has some fake implementation and then the test cases for that dummy activity is written in `sharedTest`
