### ISSUE TITLE
Add pre-submit checks file for the project

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#637]
Oppia-Android should have pre-submit checks file similar to the web so that while making a push the file will run all the test cases, check the PR guidelines which will ensure that PRs are working in terms on test cases.

 - [x] Buf - https://github.com/oppia/oppia-android/issues/2097 (issue)
 - [x] Bazel - https://github.com/oppia/oppia-android/issues/2107 (issue)
 - [x] XML
 - [x] Kotlin - https://github.com/oppia/oppia-android/pull/2002 (pull request)
 - [x] Java - https://github.com/oppia/oppia-android/pull/2101 (pull request)

**Comment by anandwana001** [comment]
Reference of Oppia-web: [here](https://github.com/oppia/oppia/wiki/If-your-presubmit-check-fails)

**Comment by anandwana001** [comment]
@rt4914 This could be a good tracker issue,

 - [ ] Buf - https://github.com/oppia/oppia-android/issues/2097 (issue)
 - [ ] Bazel - https://github.com/oppia/oppia-android/issues/2107 (issue)
 - [ ] XML
 - [ ] Kotlin - https://github.com/oppia/oppia-android/pull/2002 (pull request)
 - [ ] Java

**Comment by Sparsh1212** [comment]
@anandwana001 I would like to work on the pre-submit checks for the `XML` files. Please assign this to me if possible and also, your guidance on how to get started on this will be much help. Thanks!

**Comment by anandwana001** [comment]
@Sparsh1212 PTAL https://github.com/oppia/oppia-android/issues/970
and let me know if you want to work on this, it's a separate issue for this XML one mentioned in this issue. 

The tricky part is we have to lint XML file without using Gradle.

**Comment by Sparsh1212** [comment]
> @Sparsh1212 PTAL #970
> and let me know if you want to work on this, it's a separate issue for this XML one mentioned in this issue.
> 
> The tricky part is we have to lint XML file without using Gradle.

Yes, I would like to work on this. Please guide me on how to approach this. Any references or anything will be of great help to me.  Also, I had a look at the discussion on #970, but I see, that no conclusion was made regarding the finalization of the approach. Please clear that too. 
Thanks!

**Comment by anandwana001** [comment]
unassigning myself as this might cover under GSoC this year.

**Comment by BenHenning** [comment]
I think we've addressed basically all of the original goals of this issue, except maybe XML (though it's partially verified in static_checks.sh):

https://github.com/oppia/oppia-android/blob/0ef7a460ce1e41546f2ba1510ff12bbf88ad8177/scripts/static_checks.sh#L58

I think, overall, we can consider the presubmit checks completed for the project.
