### ISSUE TITLE
Lowfi Landscape: AdminAuth Screen

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#645]
Mock Link: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/6722d327-0ea3-4a80-8370-69ce85f308f5/RG-MN-Register-Empty-22

Helpful Resource: https://github.com/oppia/oppia-android/wiki/Working-on-UI

Currently Admin Auth Screen does not support Landscape mode, we need to update the code to make it landscape compatible.

**Comment by rt4914** [comment]
Assigned to @EdOates84

**Comment by EdOates84** [comment]
ok @rt4914  I'm working on it

**Comment by EdOates84** [comment]
Hey @rt4914 
### fix: Lowfi Landscape: AdminAuth Screen

### Before

![Screenshot_20200212_172508](https://user-images.githubusercontent.com/46043645/74333406-e6873600-4dbd-11ea-88ca-73bbc183a8f6.jpg)

### After

![Screenshot_20200212_172527](https://user-images.githubusercontent.com/46043645/74333434-f272f800-4dbd-11ea-9232-779c24e2b479.jpg)

**Comment by rt4914** [comment]
> Hey @rt4914
> ### fix: Lowfi Landscape: AdminAuth Screen
> ### Before
> 
> ![Screenshot_20200212_172508](https://user-images.githubusercontent.com/46043645/74333406-e6873600-4dbd-11ea-88ca-73bbc183a8f6.jpg)
> ### After
> 
> ![Screenshot_20200212_172527](https://user-images.githubusercontent.com/46043645/74333434-f272f800-4dbd-11ea-9232-779c24e2b479.jpg)

@EdOates84 Once issue is assigned, please do not post these things in the issue thread. Instead show these screenshots in your Pull Request.

**Comment by rt4914** [comment]
Unassigned @EdOates84

**Comment by rt4914** [comment]
Closed via #650
