### ISSUE TITLE
Nullability check in GAE Models [Blocked #5]

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#65]
For all the models in GAE check whether the objects can be null or not. For example "exploration_id" in ExplorationContainer cannot be null but "correctness_feedback_enabled" can be null.
Add kotlin null support with "?" wherever null data is allowed.
This is important because if a particular object is not in null model and the JSON data gives null value for that object, then complete model will fail to deserialize.

**Comment by BenHenning** [comment]
I agree that going with optional by default seems reasonable since we're eventually moving to protobuf and everything in proto3 is optional.

However, I think we should solve this immediately with the GAE abstraction rather than waiting to solve it.

**Comment by rt4914** [comment]
This will be fixed within GAE PRs therefore closing this issue now.
