### ISSUE TITLE
Numeric input - "number too long" validation error message change 

### ISSUE THREAD

**Issue by nikitamarysolomanpvt** [oppia/oppia-android#652]
Numeric input: **number too long** validation error message change.
https://github.com/oppia/oppia-android/pull/640#discussion_r377431118
https://github.com/oppia/oppia-android/pull/640#discussion_r377459088

**Comment by mschanteltc** [comment]
As Sean mentioned in #640, we will use the following message:
"The answer can contain at most 15 digits (0-9) or symbols (. or -)."

**Comment by BenHenning** [comment]
Resolution: we just need to change the string number_error_larger_than_fifteen_characters to fix this. While we're changing that, we should also fix number_error_starting_with_floating_point to be consistent.
