### ISSUE TITLE
Lowfi Landscape: Add Profile

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#653]
Mock Link:
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/645052fe-103b-4ca0-8250-e3b0d50bb169/PC-SP-Add-Profile-

## Checklist
- [ ] Lowfi Landscape
- [ ] Test cases for Landscape

**Comment by rt4914** [comment]
Assigned to @MohamedMedhat1998

**Comment by MohamedMedhat1998** [comment]
I finished the landscape design.
What do you mean by test cases, unit tests?
If so, which library should I use

**Comment by PrarabdhGarg** [comment]
@MohamedMedhat1998 yes you have to write unit tests. We are using the Espresso library for testing. 
You can refer this https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing for help.

**Comment by MohamedMedhat1998** [comment]
@rt4914 I've created a pull request, please check it and tell me if that is what I'm supposed to do or not

**Comment by rt4914** [comment]
Unassigned @MohamedMedhat1998

**Comment by SayantanBanerjee16** [comment]
@rt4914 Can you please assign me this issue? This issue really took my interest. @chrk2205 Can you shift to another issue if you hadn't started working on this? Thanks :)

**Comment by rt4914** [comment]
> @rt4914 Can you please assign me this issue? This issue really took my interest. @chrk2205 Can you shift to another issue if you hadn't started working on this? Thanks :)

Will wait for @chrk2205 's reply on this.

**Comment by chrk2205** [comment]
> @rt4914 Can you please assign me this issue? This issue really took my interest. @chrk2205 Can you shift to another issue if you hadn't started working on this? Thanks 

@SayantanBanerjee16 @rt4914  
I started working on this but if your really interested, you can take up this issue. :+1: 
 Instead can I take up this https://github.com/oppia/oppia-android/issues/833 issue :)

**Comment by SayantanBanerjee16** [comment]
> > @rt4914 Can you please assign me this issue? This issue really took my interest. @chrk2205 Can you shift to another issue if you hadn't started working on this? Thanks
> 
> @SayantanBanerjee16 @rt4914
> I started working on this but if your really interested, you can take up this issue. 👍
> Instead can I take up this #833 issue :)

@chrk2205 Okay, I am fine with switching issues.

**Comment by rt4914** [comment]
Great. Thanks for your mutual understanding. Let's exchange your issues.
