### ISSUE TITLE
Topic should have navigation drawer icon in it

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#654]
Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/c718fc6d-b336-475a-b31b-fd3bc84882a8/PM-EN-Play-Tab-Progress-1-

In mocks, the topic has a hamburger icon at top left corner of the screen which opens the navigation drawer.

**Comment by PrarabdhGarg** [comment]
@rt4914 for including the navigation drawer in the topic fragment, should I move the toolbar from within the fragment to the activity?
It would be easier to navigate that way.

**Comment by rt4914** [comment]
> @rt4914 for including the navigation drawer in the topic fragment, should I move the toolbar from within the fragment to the activity?
> It would be easier to navigate that way.

@PrarabdhGarg Yes that i fine. At the same time I think the implementation that you are suggesting is similar to what is done in HomeFragment.

**Comment by Sarthak2601** [comment]
@PrarabdhGarg @rt4914 Can I work on this issue? I had a duplicate issue(#680 ) and have generated a PR(#681) for it as well.
Also, we can implement navigation without moving the toolbar out of the fragment.

**Comment by PrarabdhGarg** [comment]
@Sarthak2601 I am currently working on this

**Comment by rt4914** [comment]
> @PrarabdhGarg @rt4914 Can I work on this issue? I had a duplicate issue(#680 ) and have generated a PR(#681) for it as well.
> Also, we can implement navigation without moving the toolbar out of the fragment.

@Sarthak2601 This issue has already been assign to @PrarabdhGarg and he is working on it.

At the same time the navigation icon in topics has been kept intentionally, so we tend not to remove it.

Also, I think you are assigned to [oppia-web](https://github.com/oppia/oppia) project but if you are interested in Oppia-Android. Feel free to inform us in [gitter-group](https://gitter.im/oppia/oppia-android) 

Also, we will assigning you issues in start to keep everything organised.

**Comment by Sarthak2601** [comment]
@rt4914 Okay, got it. 
I am interested in Oppia-Android. I'll inform the same in the gitter group. 
Thanks !
