### ISSUE TITLE
Lowfi Admin Controls (Part 3): AppVersion and Logout

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#659]
https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/71345025-f19e-4cac-a63f-e94442540e8f/Settings-6

## Checklist
- [ ] App version should be fully functional
- [ ] Logout should be fully functional
- [ ] Test cases

**Comment by virajpatel2411** [comment]
Can I work on this?
@rt4914

**Comment by PrarabdhGarg** [comment]
@virajpatel2411 have you checked out the [wiki](https://github.com/oppia/oppia-android/wiki)? At oppia, you are assigned tasks only after you have filled up the CLA.

**Comment by virajpatel2411** [comment]
@PrarabdhGarg I have already filled the CLA and survey form. Now, can I be asigned?

**Comment by PrarabdhGarg** [comment]
@virajpatel2411 In that case, please ask @rt4914
