### ISSUE TITLE
Lowfi Admin Controls (Part 4): Edit Profiles

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#660]
Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/71345025-f19e-4cac-a63f-e94442540e8f/Settings-6

https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/ddc3dadf-10e4-45f6-aeea-eb8a330e00ff/Settings-1-Profile-1

## Checklist
- [ ] Complete Edit Profiles Functionalities
- [ ] Test cases

**Comment by AminullahTajMuhammad** [comment]
@rt4914 Would you explain more this issue.

**Comment by rt4914** [comment]
> @rt4914 Would you explain more this issue.

Actually this PR is blocked on its other parts so we cannot work on it write now.

Also, please go through this https://github.com/oppia/oppia-android/wiki and sign the CLA and fill the survey form. Once that is done, we will assign you issues to get started. Thanks :)

**Comment by AminullahTajMuhammad** [comment]
@rt4914 Done CLA Servey and Thanks :)

**Comment by AminullahTajMuhammad** [comment]
@rt4914 I want to contribute in this project for GSoC. Would you guide that what is the procedure to made a proposal for this repo.

**Comment by rt4914** [comment]
> @rt4914 I want to contribute in this project for GSoC. Would you guide that what is the procedure to made a proposal for this repo.

I cannot guide you on the proposal, that is something that you will have to work on your own as a part of GSoC. I can only assign you work items to work on Oppia, so that when you writing your proposal the knowledge you have gathered during your code contribution will help you write a better proposal.
Also, these type of questions should be asked in `https://gitter.im/oppia/oppia-android` as it helps everyone.

**Comment by AminullahTajMuhammad** [comment]
Okay Thanks.
