### ISSUE TITLE
UX issues with switch profile of navigation drawer

### ISSUE THREAD

**Issue by PrarabdhGarg** [oppia/oppia-android#664]
If we click on the switch profile button present in the navigation drawer and then close the dialog by clicking somewhere else on the screen, the dialog box gets dismissed, but the navigation drawer still remains open, with the switch profile option highlighted.

In this, if the dialog button is canceled or the dialog disappears by clicking somewhere else, then the last selection option should get re-selected. 
Example:
If you are in HomeFragment and click on `Switch Profile` in NavigationDrawer then the dialog disappears (like after clicking Cancel), in this case, HomeFragment should get re-selected. Similarly for other cases too. 

![Screenshot_1581622192](https://user-images.githubusercontent.com/42096726/74471268-f2f6b600-4ec5-11ea-84d0-c1d08ba7d3de.png)

**Comment by abhinavraj23** [comment]
@rt4914 Are you working on this? Otherwise, I would love to do it

**Comment by rt4914** [comment]
@abhinavraj23 This will be a fairly difficult task for now, let's focus on the work that has been assigned to you and as time progresses this can be done. Thanks for your interest.

**Comment by rt4914** [comment]
> @rt4914 Are you working on this? Otherwise, I would love to do it

@abhinavraj23  As requested earlier, you can work on this one now

**Comment by abhinavraj23** [comment]
Sure @rt4914,  I would start working on it ASAP!
