### ISSUE TITLE
Lowfi Landscape: ContinuePlaying Screen

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#666]
Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/0e6ba726-1930-4f39-9c73-51df10a1c766/HP-Continue-Playing-

Portrait Mock: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/2b6c8e95-5ac7-4472-bc2b-1c318a3f7e5c/HP-Continue-Playing-

Note that we are currently not focusing on "Download" information on top right corner. So do not create UI for that.

## Checklist
- [ ] Landscape Layout
- [ ] Test cases

**Comment by rt4914** [comment]
Assigning this to @abhinavraj23

**Comment by abhinavraj23** [comment]
@rt4914 I have made the PR, I have tested it as well, it is working, please review it and let me know!
