### ISSUE TITLE
Update fraction error message.

### ISSUE THREAD

**Issue by iamprayush** [oppia/oppia-android#672]
To keep parity between Android and web, an error validation in the fraction input interaction that was present in the android version but not in the web, is being added by [#8671](https://github.com/oppia/oppia/pull/8671).
During this addition, it was suggested by [@aks681](https://github.com/aks681) that the error message should be changed to 'None of the numbers in the fraction should have more than 7 digits' instead of 'None of the numbers of the fraction should be larger than 7 digits.'.
I have implemented this change in my PR for the web. Please do so for the android version as well.

I believe the change needs to be made [here](https://github.com/oppia/oppia-android/blob/d705580e1fae1556ef828c4b6757b6855fcbb8e8/app/src/main/res/values/strings.xml#L80).

**Comment by seanlip** [comment]
@rt4914 @nikitamarysolomanpvt could one of you take a look at this, please? I am supportive of this wording change.

Thanks!

**Comment by rt4914** [comment]
@seanlip Will do this. Thanks.

**Comment by rt4914** [comment]
Closed via #674
