### ISSUE TITLE
Track whether atleast 1 child profile has been created or not

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#676]
Domain layer needs to have functionality where we can keep track whether atleast 1 child profile has been added or not. Even if that child profile is deleted later on, its fine. This functionality will be used in app module to control the UI in following ways:

[ProfileChooser - If no profile has been added yet](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/8cdde1f8-daae-438c-8fdd-084e5d227080/PC-SP-Profile-Chooser-v2)
[ProfileChooser - General](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/18e69208-8528-424a-a368-b2c5d530d235/PC-SP-Profile-Chooser-)

**Comment by Sarthak2601** [comment]
Hi @rt4914, can I work on this next ?

**Comment by rt4914** [comment]
> Hi @rt4914, can I work on this next ?

Actually this requires some work on other modules too. This work will involve model, domain layer and app module. So better not work on this for now, as it can be very complicated.

**Comment by Sarthak2601** [comment]
> > Hi @rt4914, can I work on this next ?
> 
> Actually this requires some work on other modules too. This work will involve model, domain layer and app module. So better not work on this for now, as it can be very complicated.

Okay 👍
