### ISSUE TITLE
Lowfi: ProfileChooser Different Screen Scenarios [Blocked on #676]

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#677]
[ProfileChooser - If no profile has been added yet](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/8cdde1f8-daae-438c-8fdd-084e5d227080/PC-SP-Profile-Chooser-v2)
[ProfileChooser - General](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/18e69208-8528-424a-a368-b2c5d530d235/PC-SP-Profile-Chooser-)

Add test cases for this functionality.

In `ProfileProgressController`, there is one value `wasProfileEverCreated`. If this value is true, show `ProfileChooser - General` else show `ProfileChooser - If no profile has been added yet`

**Comment by Sarthak2601** [comment]
Hi @rt4914, can you please explain this issue a bit.

**Comment by Sarthak2601** [comment]
@rt4914 Is this functionality currently working ? Because when I ran the app on my device, it wasn't. 
And in this issue I have to write only the test cases or there's more to it ?

**Comment by rt4914** [comment]
> @rt4914 Is this functionality currently working ? Because when I ran the app on my device, it wasn't.
> And in this issue I have to write only the test cases or there's more to it ?

This functionality is not in develop yet. And so you have to first finish this functionality and then add test cases according to your code.

**Comment by Sarthak2601** [comment]
> > @rt4914 Is this functionality currently working ? Because when I ran the app on my device, it wasn't.
> > And in this issue I have to write only the test cases or there's more to it ?
> 
> This functionality is not in develop yet. And so you have to first finish this functionality and then add test cases according to your code.

Oh great ! On it :)

**Comment by rt4914** [comment]
Unassigned @Sarthak2601

**Comment by rt4914** [comment]
Closed via https://github.com/oppia/oppia-android/pull/952
