### ISSUE TITLE
Landscape Lowif: Onboarding Flow

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#678]
Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/1f86ca4e-795e-4a75-8784-fea53864b94b/RG-OB-Onboarding-1-

Also, write test cases for landscape mode.

Images link: https://drive.google.com/open?id=1BVmATijZcOvBWksXeCSism-ZQvohCkLn

**Comment by Sarthak2601** [comment]
Hi @rt4914, would like to contribute. Can you please explain the issue a bit..

**Comment by seanlip** [comment]
Hi @Sarthak2601 -- welcome to Oppia! To get started, please follow [these instructions](https://github.com/oppia/oppia-android/wiki) first. Thanks!

**Comment by rt4914** [comment]
@Sarthak2601 You have been assigned #600 for now. Also, this PR is a bit lengthy one and considering that your current assigned issue will also take time, its better if do not assign this one to you for now.

**Comment by AminullahTajMuhammad** [comment]
Hello @rt4914 I want to know that is there any communication channel for repository discussion.

**Comment by rt4914** [comment]
> Hello @rt4914 I want to know that is there any communication channel discussion.

Hello @AminullahTajMuhammad You can start first by going through this: https://github.com/oppia/oppia-android/wiki

Also, you can join https://gitter.im/oppia/oppia-android

**Comment by AminullahTajMuhammad** [comment]
Thanks @rt4914
