### ISSUE TITLE
Remove unused functions and code StoryProgressController and TopicController

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#686]
Once the progress is correctly connected to app module, remove previous written functions and test cases from `StoryProgressController` and `TopicController`

**Comment by viktoriias** [comment]
@rt4914 Is this available now? Would it qualify as "good second/third issue"?

**Comment by rt4914** [comment]
@viktoriias You can have a look. I think that it might not need any change. But have a look at the domain layer functions and feel free to comment whether we need to solve this or we don't need any change and we can directly close this?

**Comment by viktoriias** [comment]
@rt4914 I checked all the functions in StoryProgressController and TopicController and didn't find any unused ones.
I think we can close this.

**Comment by rt4914** [comment]
Thanks @viktoriias 

Closing this issue: https://github.com/oppia/oppia-android/issues/686#issuecomment-752205135
