### ISSUE TITLE
Lowfi: Update topic_lessons_story_summary

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#688]
Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/c718fc6d-b336-475a-b31b-fd3bc84882a8/PM-EN-Play-Tab-Progress-1-

In new mock the `topic_lessons_story_summary` has been updated to remove the extra space before chapter names.

Current Develop implementation:
<img width="334" alt="Screenshot 2020-02-22 at 5 49 27 PM" src="https://user-images.githubusercontent.com/9396084/75092229-bd279080-559b-11ea-84c3-066cc4142ffb.png">

New updated implementation:
<img width="322" alt="Screenshot 2020-02-22 at 5 49 33 PM" src="https://user-images.githubusercontent.com/9396084/75092239-c6b0f880-559b-11ea-993b-ec276223679b.png">

So if you see, the space before the chapter names is different in both the mocks.

**Comment by rt4914** [comment]
Assigned to @gunishjain

**Comment by gunishjain** [comment]
Oh thanks now I understood the problem. Sorry to trouble you for this silly doubt. @rt4914

**Comment by rt4914** [comment]
> Oh thanks now I understood the problem. Sorry to trouble you for this silly doubt. @rt4914

No doubt is silly. Feel free to ask questions. Thanks :)

**Comment by rt4914** [comment]
Closed via #707
