### ISSUE TITLE
Refactor use of constant strings

### ISSUE THREAD

**Issue by PrarabdhGarg** [oppia/oppia-android#690]
Instead of using string constants in this manner:
```
<string name="topic_prefix">Topic:</string>
fragment.getString(R.string.topic_prefix) + " " + topicName
```
it would be better if we used parameterized string resources. The required changes in the above case, for example would be :
```
<string name="topic_prefix">Topic: %1$s</string>
fragment.getString(R.string.topic_prefix, topicName).
```
For more details, refer Formatting Strings section of https://developer.android.com/guide/topics/resources/string-resource

**Comment by rt4914** [comment]
@PrarabdhGarg Go ahead any create a PR for this. Thanks.
