### ISSUE TITLE
Landscape Lowfi: Reset PIN

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#691]
Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/6f83fcd9-e72d-4941-a16f-6754a869e083/RG-MN-Register-Empty-37

Write tests too.

**Comment by rt4914** [comment]
Assigning this to @gunishjain

**Comment by AminullahTajMuhammad** [comment]
@rt4914 Is this only UI to Implement?

**Comment by rt4914** [comment]
> @rt4914 Is this only UI to Implement?

For now yes, but actually in this the important thing is test cases, once your UI is ready for landscape you will need to write test cases which are important.

**Comment by iaminamkhan** [comment]
@rt4914 Can i Work on this?

**Comment by rt4914** [comment]
> @rt4914 Can i Work on this?

Please check `Assignees` section on the right. If it has been assigned to something that means that other person cannot work on this. Also, you will find that most of the issues are already assigned to someone, so in that case you can mention that you need more issues to work on in https://gitter.im/oppia/oppia-android

For now you have already been assigned one issue, but that PR was created on a wrong fork. So please create a fresh PR on `https://github.com/oppia/oppia-android`

**Comment by rt4914** [comment]
Unassign @gunishjain
