### ISSUE TITLE
Lowfi: HelpActivity (Part 1)

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#692]
Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/8e1bbf3c-3287-4149-b599-5d5a5486809d/HL-Help-Menu-

In this we don't need to include Send. Feedback feature.

Also, create an empty FAQActivity with its fragment and presenter in this PR and write test cases too.

**Comment by PrarabdhGarg** [comment]
@rt4914 in this should I add a recycler view, considering extra option might be added in the future? Or should I just add a single text view for now?

**Comment by rt4914** [comment]
> @rt4914 in this should I add a recycler view, considering extra option might be added in the future? Or should I just add a single text view for now?

Yes.

**Comment by rt4914** [comment]
> @rt4914 in this should I add a recycler view, considering extra option might be added in the future? Or should I just add a single text view for now?

Actually considering that you have not worked on recyclerview yet in this Project and you already have one task assigned regarding the recyclerview, lets unassign you from this because you have very less time to work on right now.

**Comment by PrarabdhGarg** [comment]
@rt4914 sure. No problem

**Comment by aggarwalpulkit596** [comment]
@rt4914 can I take this one?

**Comment by rt4914** [comment]
> @rt4914 can I take this one?

Hello @aggarwalpulkit596 before we get started on any task, please go through this https://github.com/oppia/oppia-android/wiki and also, make sure that you sign the CLA and fill the survey form. Once that is done, we will assign you some issues to get started.

**Comment by aggarwalpulkit596** [comment]
okay 👍

**Comment by aggarwalpulkit596** [comment]
@rt4914 Hey, I've already completed the survey as well as signed the CLA. Can you take a look at it so that I can start contributing

**Comment by rt4914** [comment]
Assigning this to @SayantanBanerjee16 now.

**Comment by SayantanBanerjee16** [comment]
> Assigning this to @SayantanBanerjee16 now.

Okay sir, am on it.
