### ISSUE TITLE
Lowfi: HelpActivity (Part 2) - FAQ [Blocked part-1]

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#694]
Mock:
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/63a98a9c-3b46-4ba6-87d0-2f6e7c70bbe4/HL-FAQ-No-Category-current-

For working on FAQs, first we need a recyclerview implementation in FAQs and the content for this should be coming from strings.xml file (something like an strings array - https://stackoverflow.com/a/4161645), this is done to make sure that the strings are converted easily to other languages in future.

Also, avoid `Current Mocks` button in FAQ it is actually not a part of development and instead it has been kept just of reference to show what this screen will look like in future.

**Comment by SayantanBanerjee16** [comment]
@rt4914 Thanks for assigning me this issue.

Few queries,

1) What implementation related to the search button in the toolbar?
2) What should happen when I select a question in the FAQ List?

**Comment by PrarabdhGarg** [comment]
@SayantanBanerjee16 the functionality for the search button does not have to be implemented as of now. 
Also,  as far as I am aware,  we don't have to add an on click functionality on the FAQ's as of now.
