### ISSUE TITLE
Add thumbnails in Subtopic Domain layer to show in Revision tab.

### ISSUE THREAD

**Issue by veena14cs** [oppia/oppia-android#703]
### Explanation
Add dummy thumbnails in subtopic list of Topic Json data. Update TopicController in domain layer to fetch thumbnails and display it in Topic Revision Tab.

### Mock
https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/1adacef0-f245-4115-a0e0-d1c2e7d5a0bb/TP-Review-

**Comment by rt4914** [comment]
@veena14cs Please add description along with mock link. Also, In title, mention "Domain" as the first task will be to introduce that in domain layar.

**Comment by rt4914** [comment]
Also, assign it to yourself.

**Comment by veena14cs** [comment]
> @veena14cs Please add description along with mock link. Also, In title, mention "Domain" as the first task will be to introduce that in domain layar.

Okay.

**Comment by veena14cs** [comment]
This is fixed in the PR #710 & #711 .
