### ISSUE TITLE
Lowfi: Updated picture selection 

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#712]
Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/62215bbd-1f4e-448e-b370-19c4a06fa814/PC-MP-Add-Profile-PINs-Match-Error-1

Current:
<img width="174" alt="Screenshot 2020-02-25 at 4 22 35 PM" src="https://user-images.githubusercontent.com/9396084/75240909-23562280-57eb-11ea-8692-e2ac6be80733.png">

New as per mock:
<img width="160" alt="Screenshot 2020-02-25 at 4 22 42 PM" src="https://user-images.githubusercontent.com/9396084/75240924-2a7d3080-57eb-11ea-80d0-66ee27fd32de.png">

**Comment by rt4914** [comment]
Assigning this to @aggarwalpulkit596

**Comment by aggarwalpulkit596** [comment]
You self assigned this

**Comment by rt4914** [comment]
> You self assigned this

That was done because the list was not showing your name, now it is visible. Thanks.
