### ISSUE TITLE
Lowfi Landscape Topic Practice

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#713]
Mock Link: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/0fa47d7c-e10d-4097-8773-0efa665a323f/TP-Practice-

## Checklist
- [ ] Landscape lowfi mock
- [ ] Test cases

**Comment by rt4914** [comment]
Assigning this to @Sarthak2601

**Comment by Sarthak2601** [comment]
@rt4914 please check the ui changes. Also please tell me what all test cases are required here ?
