### ISSUE TITLE
Lowfi landscape Topic Revision

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#714]
Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/dad2a9ff-ce33-4f00-894a-ec07dbb12797/TP-Revision-

Add test cases for the same.

**Comment by rt4914** [comment]
@abhinavraj23 This is not regular landscape UI, in this you will need to manage the layout manager and test cases will be critical. Test this across various device sizes.

**Comment by abhinavraj23** [comment]
Sure @rt4914 I would start working on it ASAP!

**Comment by rt4914** [comment]
> Sure @rt4914 I would start working on it ASAP!

Thanks.

**Comment by abhinavraj23** [comment]
@rt4914 I think here we have to make the landscape layout for fragment inside a fragment, it's a bit complicated I guess, will take time, will try to complete it by tomorrow

**Comment by rt4914** [comment]
@abhinavraj23 Any updates on this issue.

**Comment by abhinavraj23** [comment]
@rt4914 sorry for the delay, will make the PR ASAP!
