### ISSUE TITLE
Missing test cases for AddProfileActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#721]
AddProfileActivity is missing some test cases mainly related to profile selection.

`AddProfileActivityTest` does not include any test case related to image selection. Need to add test cases to make sure that on click on `default-avatar / profile-picture` it opens the Camera intent and image can be selected from there.

**Comment by anandwana001** [comment]
@rt4914 Could you please elaborate it, what test cases? profile selection is a part of `ProfileChooserFragment`

Are you talking about adding test cases for the following code unit from `ProfileChooserFragmentPresenter`?
```
if (it.isSuccess()) {
     activity.startActivity((HomeActivity.createHomeActivity(activity, model.profile.id.internalId)))
}
```
Clicking on a profile takes to the `HomeActivity` when the pin is empty and not admin. This is the test cases which I found missing. If this is the one, can I work on it?

**Comment by rt4914** [comment]
@anandwana001 I have updated the description, Thanks.

Also, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by anandwana001** [comment]
Can I work on this issue?

**Comment by rt4914** [comment]
> Can I work on this issue?

Please, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by rt4914** [comment]
Assigned to @anandwana001
