### ISSUE TITLE
Lowfi Landscape: ProfileEditActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#727]
Mock:
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/5b8a8202-6081-4855-8c49-94a8a5b4c559/RG-MN-Register-Empty-35/

Currently app supports only portrait mode for ProfileEditActivity, so add landscape mode too.
Add test cases for landscape mode too.

**Comment by vaibhavjain30699** [comment]
@rt4914 I would like to work on this issue.

**Comment by rt4914** [comment]
> @rt4914 I would like to work on this issue.

Hello @vaibhavjain30699 Thanks for showing your interest. Have a look at this https://github.com/oppia/oppia-android/wiki.

Once you sign the CLA and finish the survey form, we can assign you issues.

**Comment by vaibhavjain30699** [comment]
Done

**Comment by rt4914** [comment]
@vaibhavjain30699 You can work on this, I will be sending you an email soon. Thanks & Welcome to Oppia :)

**Comment by rt4914** [comment]
Assigning this to @vaibhavjain30699

**Comment by Kushal-Gera** [comment]
I would love to work on this issue

**Comment by rt4914** [comment]
Assigning this to @Scarlet0103 as there has been no updates in this in 2 weeks.

**Comment by Luffy18346** [comment]
@Scarlet0103 Here are the mocks for both landscape and portrait mode for ProfileEditActivity. You can start working on the issue.

Landscape Mode: 

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/5b8a8202-6081-4855-8c49-94a8a5b4c559/RG-MN-Register-Empty-35/

Portrait Mode: 

https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/1c3f250f-32e5-4299-8187-75d7c3dbe6b6/Settings-1-Profile-Chantel-Disabled-5

**Comment by rt4914** [comment]
@Luffy18346 Thanks for this.

**Comment by Scarlet0103** [comment]
Rajat,
       Can you please review this issue
https://github.com/oppia/oppia-android/pull/803
can you please check whether the mentioned test cases are correct

Thanks...
