### ISSUE TITLE
Lowfi Landscape: ProfileRenameActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#728]
Mock:
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/b7447549-a7c3-48a9-8ad2-876d0a347708/RG-MN-Register-Empty-36/

Currently app supports only portrait mode for `ProfileRenameActivity`, so add landscape mode too.
Add test cases for landscape mode too.

**Comment by rob729** [comment]
@rt4914 Can I work on this issue?

**Comment by rt4914** [comment]
> @rt4914 Can I work on this issue?

Actually this has been assigned to @aggarwalpulkit596 

Also, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.
