### ISSUE TITLE
Introduce StoryProgress in app module

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#736]
For introducing `StoryProgess` in app module successfully we need to make changes in following ways:

- [x] Create ProfileProrgessActivity
- [x] Create OngoingTopicListActivity
- [x] Create CompletedStoryListActivity
- [x] Set livedata in Navigation Drawer Header
- [x] PromotedStory should be dynamic and update test cases too.
- [x] Change test cases for TopicLessonsFragment
- [x] Change test cases for StoryActivity
- [x] Change test cases for ContinuePlayingActivity

**Comment by BenHenning** [comment]
Tracking & representing completed chapters is now complete.
