### ISSUE TITLE
Hifi: Admin Auth Screen

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#739]
Admin Auth Screen UI needs to be pixel perfect with the mocks.
Portrait Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/a2dbcfcd-3bb4-4fe7-b746-fe867b6c4915/PC-MP-Admin-Authorization-Admin-Controls-Empty-/
Landscape Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/a0c84710-3970-4488-beea-6fe6abbdb38a/PC-MP-Admin-Authorization-Admin-Controls-Empty-

Mocks have been created for MDPI Devices.
Make sure that the screen passes the accessibility test also.
For reference you can checkout: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by rt4914** [comment]
Assigning this to @anandwana001

**Comment by anandwana001** [comment]
@rt4914  Does this issue mean creating a complete flow, starting from creating [Administrator Controls](https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/ad1de6e2-1d5d-4ac3-888c-58d036c7ede4/PC-MP-Profile-Chooser-) button on ProfileChooserFragment, clicking on which opens the [Administrator Controls Screen](https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/a2dbcfcd-3bb4-4fe7-b746-fe867b6c4915/PC-MP-Admin-Authorization-Admin-Controls-Empty-) or just the screens (UI) mentioned by you in the description?

**Comment by PrarabdhGarg** [comment]
@anandwana001 the basic UI for these screens is already ready. However, you can consider the current UI as a rough version of the final UI we want.
Since this is a Hifi issue, the aim of this issue is to polish these UI screens and make them pixel perfect as per the given mocks

**Comment by anandwana001** [comment]
I was checking the layout files, `admin_auth_activity.xml`. The flow I understand from the current code in develop branch is clicking on add profile button open these screen. Its portrait version has a different title(_Add Profile_) on toolbar than landscape(_Administrator Authorization Required_). Just to confirm, are these the basic UI file which is needed to work on this issue?

<img width="935" alt="Screenshot 2020-03-05 at 18 27 01" src="https://user-images.githubusercontent.com/25057618/75983846-4b423600-5f0f-11ea-8af6-49dad71b942f.png">
<img width="675" alt="Screenshot 2020-03-05 at 18 26 49" src="https://user-images.githubusercontent.com/25057618/75983852-4f6e5380-5f0f-11ea-8cae-0e68b3d84702.png">

**Comment by PrarabdhGarg** [comment]
@anandwana001 yes, they are the layout files you need to work on

**Comment by rt4914** [comment]
> I was checking the layout files, `admin_auth_activity.xml`. The flow I understand from the current code in develop branch is clicking on add profile button open these screen. Its portrait version has a different title(_Add Profile_) on toolbar than landscape(_Administrator Authorization Required_). Just to confirm, are these the basic UI file which is needed to work on this issue?
> 
> <img alt="Screenshot 2020-03-05 at 18 27 01" width="935" src="https://user-images.githubusercontent.com/25057618/75983846-4b423600-5f0f-11ea-8af6-49dad71b942f.png">
> 
> <img alt="Screenshot 2020-03-05 at 18 26 49" width="675" src="https://user-images.githubusercontent.com/25057618/75983852-4f6e5380-5f0f-11ea-8cae-0e68b3d84702.png">

Don't worry about the title just focus on pixel perfect UI part. Once this is done, we will finalise the Toolbar title too.

**Comment by anandwana001** [comment]
1. What about the Submit button in the landscape mock?
Landscape Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/a0c84710-3970-4488-beea-6fe6abbdb38a/PC-MP-Admin-Authorization-Admin-Controls-Empty-

2. Just to confirm, In the given mock colour of subtitle _Enter the Administrator’s PIN to access Administrator Controls._ is different for Landscape(#333333) and Portrait(#0000008A)

**Comment by anandwana001** [comment]
We have custom `org.oppia.app.profile.ProfileInputView` view used at multiple places which do not give us more modification area. Current start margin of TextView inside it is 32dp(28+4) whereas according to the mock we need 36dp(28+8) margin.

![Screenshot_2020-03-07-06-51-51-659_org oppia app](https://user-images.githubusercontent.com/25057618/76134198-8abd6f00-6042-11ea-80d2-328b24a03abe.jpg)
![Screenshot_2020-03-07-06-51-55-277_org oppia app](https://user-images.githubusercontent.com/25057618/76134203-901ab980-6042-11ea-93c2-6c222a23f55f.jpg)

after using `bindingAdapter` and change the margin start of `Administrator's Pin` to required 36dp as per the mock

![Screenshot_2020-03-07-07-06-51-176_org oppia app](https://user-images.githubusercontent.com/25057618/76134207-95780400-6042-11ea-9091-dbf37c36a9b6.jpg)

**Comment by anandwana001** [comment]
After using the Accessibility Scanner, the report I get having few suggestions for the cancel button, input and submit button from our `org.oppia.app.profile.ProfileInputView`. 

1. Item label - this suggestion can be fulfilled if we add `hint` to our input. 
**What hint we should add? Should we add label text as it is?**

2. Text Contrast - if we use `oppiaSecondaryText=#666666` as `hintTextColor` for input, this suggestion can be fulfilled

**Comment by rt4914** [comment]
> 1. What about the Submit button in the landscape mock?
>    Landscape Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/a0c84710-3970-4488-beea-6fe6abbdb38a/PC-MP-Admin-Authorization-Admin-Controls-Empty-
> 2. Just to confirm, In the given mock colour of subtitle _Enter the Administrator’s PIN to access Administrator Controls._ is different for Landscape(#333333) and Portrait(#0000008A)

What about submit button? I am not able to understand.

2. If case of disparities use portrait mode colors/texts.

**Comment by rt4914** [comment]
> After using the Accessibility Scanner, the report I get having few suggestions for the cancel button, input and submit button from our `org.oppia.app.profile.ProfileInputView`.
> 
> 1. Item label - this suggestion can be fulfilled if we add `hint` to our input.
>    **What hint we should add? Should we add label text as it is?**
> 2. Text Contrast - if we use `oppiaSecondaryText=#666666` as `hintTextColor` for input, this suggestion can be fulfilled

@anandwana001

Don't add hint for now.

Instead you can do one thing:
1. Create a PR in whichever way you find it correct.
2. In PR mention all the points which are confusing and which are at disparities, so once that is done, we can talk with the designer and take her suggestions.
