### ISSUE TITLE
Highfi: Topic Overview

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#742]
TopicOverview needs to be pixel perfect with the mocks.
Portrait Mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/19cfbacf-854c-4c7d-8691-3b3d117e1866/TP-Overview-

Landscape Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/4e4d2aec-fd30-4c20-91ed-daf434f47a89/TP-Info-

Mocks have been created for MDPI Devices.
Make sure that the screen passes the accessibility test also.
For reference you can checkout: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by rt4914** [comment]
Assigning this to @Chrk2205

**Comment by chrk2205** [comment]
while pushing the following error is showing up. what should i do??

>  **Remote: Permission to oppia/oppia-android.git denied to chrk2205. unable to access 'https://github.com/oppia/oppia-android.git/': The requested URL returned error: 403**

**Comment by chrk2205** [comment]
![bp](https://user-images.githubusercontent.com/44704035/76140160-89f5fe80-607d-11ea-9d36-51bfbb69680f.jpeg)
![bL](https://user-images.githubusercontent.com/44704035/76140162-8c585880-607d-11ea-91ad-5274dde2cc52.jpeg)
before editing.

![Ap](https://user-images.githubusercontent.com/44704035/76140171-a72acd00-607d-11ea-87e8-6fb421adba03.jpeg)
![Al](https://user-images.githubusercontent.com/44704035/76140175-a98d2700-607d-11ea-92fc-8b784c727c8d.jpeg)

After

Their are no much changes but i changed them according to UI-guide

**Comment by chrk2205** [comment]
@rt4914  please check my PR.
