### ISSUE TITLE
Highfi: Topic Practice

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#744]
TopicPractice needs to be pixel perfect with the mocks.
Portrait Mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/f403add1-079a-4202-9975-efe04c076290/TP-Practice-Unchecked-
Landscape Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/0fa47d7c-e10d-4097-8773-0efa665a323f/TP-Practice-

Mocks have been created for MDPI Devices.
Make sure that the screen passes the accessibility test also.
For reference you can checkout: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by rt4914** [comment]
Assigned to @virajpatel2411

**Comment by virajpatel2411** [comment]
Thanks @rt4914, On it. Will text you once I have created a PR.

**Comment by virajpatel2411** [comment]
@rt4914  Do I just have to change the list of checkboxes?
Because other things look right.

**Comment by rt4914** [comment]
> @rt4914 Do I just have to change the list of checkboxes?
> Because other things look right.

You don't need to change the content, content is dynamic. You need to make sure that the UI is matching as per the mocks.

Check this: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by rt4914** [comment]
@virajpatel2411 Any updates on this issue?

**Comment by virajpatel2411** [comment]
@rt4914 Was busy last few days. Will complete it by tomorrow. Sorry.
