### ISSUE TITLE
Replace ProfileChooserActivity to LoginActivity where necessary. 

### ISSUE THREAD

**Issue by Luffy18346** [oppia/oppia-android#762]
~This issue was brought up in PR #755 .~  

~As the login functionality is not implemented till now, currently we are redirecting user to ProfileActivity (Soon to be ProfileChooserActivity) in case if user wants to logout or exit the current account. So, once Login functionality is implemented, we need to redirect user to LoginActivity~

To resolve this issue, remove the TODO corresponding to it per the TODO findings below.

**Comment by Luffy18346** [comment]
As the login functionality is not implemented till now, currently we are redirecting user to `ProfileActivity` (Soon to be `ProfileChooserActivity`) in case if user wants to logout or exit the current account. So, once Login functionality is implemented, we need to redirect user to LoginActivity

**Comment by BenHenning** [comment]
I think this isn't quite worth tracking at this point since remote profile support is not on the team's planned roadmap. Once it is, we'll need to revisit the integration with the entire app, including ProfileChooserActivity.

**Comment by BenHenning** [comment]
Ah, we'll need to remove that TODO. Triaging for now.

**Comment by seanlip** [comment]
Note to contributors: this is a very easy good first issue! It just involves removing the TODO.
