### ISSUE TITLE
Full Highfi: HelpActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#765]
`HelpActivity` needs to be pixel perfect with the mocks.
Portrait Mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/8e1bbf3c-3287-4149-b599-5d5a5486809d/HL-Help-Menu-
Landscape Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/a949ea57-5166-4081-bec8-ed4c16d319d0/HL-Help-Menu-

Note: Avoid `Send Feedback` option.

Mocks have been created for HDPI Devices.
Make sure that the screen passes the accessibility test also.
For reference you can checkout: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by rt4914** [comment]
@SayantanBanerjee16 Update your PR title also.

**Comment by SayantanBanerjee16** [comment]
> @SayantanBanerjee16 Update your PR title also.

Done :)
