### ISSUE TITLE
Replace ProfileActivity to ProfileChooserActivity where needed

### ISSUE THREAD

**Issue by Luffy18346** [oppia/oppia-android#766]
Currently, the activity in which user chooses the profile is named as `ProfileActivity` in code which is not appropriate according to the functionality of that activity. So, all the files corrensponding to choosing user profiles need to be changed to `ProfileChooserActivity`

Changes that are need to done: 

Rename `ProfileActivity` to `ProfileChooserActivity`
Rename `ProfileActivityPresenter` to `ProfileChooserActivityPresenter`
Rename `profile_activity.xml` to `profile_chooser_activity.xml`

Also check the test files too.

**Comment by prayutsu** [comment]
I want to work on this issue.
