### ISSUE TITLE
Lowfi Landscape: OptionsActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#771]
Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/7d442317-dd5a-40e7-adbd-25285d010874/OP-Options-Menu-

OptionsActivity should support landscape mode. Also add test cases for landscape mode too.

**Comment by rt4914** [comment]
Assigned to @thelosergeek

**Comment by Kushal-Gera** [comment]
I would love to work on OptionsActivity #771

**Comment by Kushal-Gera** [comment]
#771 landscape activity is made with absolute ease

**Comment by rt4914** [comment]
@thelosergeek is already working on this PR. I will assign you some other PR.

**Comment by Kushal-Gera** [comment]
Oh
Ok sir.

**Comment by Kushal-Gera** [comment]
Ok sir

**Comment by iaminamkhan** [comment]
@rt4914 Please review PR!

**Comment by rt4914** [comment]
Unassigned @thelosergeek
