### ISSUE TITLE
Lowfi Landscape: AppLanguageActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#772]
Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/2b8387b0-5ec6-4e42-bffa-c039128b2f12/OP-App-Language-/

`AppLanguageActivity` should support landscape mode. Also add test cases for landscape mode too.

This issue is currently blocked because the landscape mode mocks are not ready yet.

**Comment by Kushal-Gera** [comment]
I would love to work on this issue

**Comment by rt4914** [comment]
Unassigned @Kushal-Gera

**Comment by rt4914** [comment]
Assigned this to @MohamedMedhat1998

**Comment by MohamedMedhat1998** [comment]
@rt4914  Where is the "AppLanguageActivity" ?  
I can't find it (I'm currently in a new branch that is created from the develop branch)

**Comment by rt4914** [comment]
> @rt4914 Where is the "AppLanguageActivity" ?
> I can't find it (I'm currently in a new branch that is created from the develop branch)

https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/app/options/AppLanguageActivity.kt

**Comment by MohamedMedhat1998** [comment]
@rt4914 I have finished the implementation of the landscape mode  
What test cases should I write?

**Comment by rt4914** [comment]
> @rt4914 I have finished the implementation of the landscape mode
> What test cases should I write?

Actually I cannot provide you direct test cases otherwise it would be spoon-feeding.
Hint: https://github.com/oppia/oppia-android/blob/develop/app/src/sharedTest/java/org/oppia/app/options/OptionsFragmentTest.kt

In this file, there are two test cases which are related to orientation change. Try to implement similar test cases in this file for your `AppLanguageActivity`
