### ISSUE TITLE
Lowfi Landscape Review Card

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#773]
Mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/5d907b23-a75e-4f8b-8c59-afd3c734c53e/RM-Revision-Mode-/

Review card is missing dummy data, also `Return to Topic` button is also missing at the bottom of the page.
Also, finish the landscape mode for the same, with proper test cases.

**Comment by abhinavraj23** [comment]
@rt4914 I have made the landscape version of the revision card please update regarding what dummy data do we need to add and what should be the layout for Return to Topic Button?

**Comment by rt4914** [comment]
> @rt4914 I have made the landscape version of the revision card please update regarding what dummy data do we need to add and what should be the layout for Return to Topic Button?

@abhinavraj23 
1. I will take care of dummy data, so you can avoid that for now.
2. If you scroll the mock, you will see `Return to Topic` button at the bottom.
