### ISSUE TITLE
Lowfi: ProfileProgress - profile picture and edit

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#777]
Mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/7fb5929e-4652-4412-bf8c-64d94f4159f9/UP-User-Profile-
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/7fcddeef-4d62-4565-b763-81e89f064a5d/UP-O-Forgot-PIN-Dialog-

Click on the image and edit should show a popup to either view the image or to edit the change.

Also, write test cases for this.

**Comment by aggarwalpulkit596** [comment]
@rt4914 pop-up here means a dialog box with 2 buttons right ?

**Comment by aggarwalpulkit596** [comment]
@rt4914 nm i've updated the mock url

**Comment by rt4914** [comment]
> @rt4914 nm i've updated the mock url

Actually previous link was more correct as it helps to know where we are showing that popup. Please update to that link only.

**Comment by rt4914** [comment]
> @rt4914 pop-up here means a dialog box with 2 buttons right ?

Actually those are two options to be clear. You can check implementation of `CellularAudioDialogFragment`, `LanguageDialogFragment`, `StopExplorationDialogFragment`

**Comment by aggarwalpulkit596** [comment]
> > @rt4914 nm i've updated the mock url
> 
> Actually previous link was more correct as it helps to know where we are showing that popup. Please update to that link only.

should i add both of the mocks?

**Comment by rt4914** [comment]
@aggarwalpulkit596 yeah sure. BTW, reviewed your previous PR
