### ISSUE TITLE
Lowfi Landscape: StoryTextSize

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#788]
Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/2eaf085a-c2a7-4b1d-b515-5b32f8642669/OP-Story-Text-Size-/

Also add test cases for this implementation.

**Comment by rt4914** [comment]
Assigned to @chrk2205

**Comment by rob729** [comment]
@rt4914 Can I work on this issue?
