### ISSUE TITLE
Logging system

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#8]
There should be an easy-to-use (preferable via fluent pattern) logging system on top of logcat that will be used throughout the app. This should log to a local file specific for the app so that app-level logs can be uploaded with user feedback reports. It's highly preferable to use an existing logging API if one is available rather than building this from scratch.

**Comment by BenHenning** [comment]
This is blocked on #4.

**Comment by BenHenning** [comment]
NB: Logs also need to be retrievable (e.g. for user feedback reporting & for displaying in the developer menu).

Although not explicitly blocking, all downstream work will likely introduce logs using this system so it should be implemented as early in the project as possible.

**Comment by BenHenning** [comment]
@veena14cs can you document your findings here about why you chose the logging solution that you did? Also, note that one requirement in this issue is to find a fluent logger (https://dzone.com/articles/fluent-builder-pattern). Flogger (https://google.github.io/flogger/) is one such example, but I believe it's not compatible with Android  (this may require further investigation on your part if Flogger looks promising for us).

**Comment by veena14cs** [comment]
I am going through flogger. I will let you know about it once I get enough
information.

And also I want to know that whether we need to have only specific logs?

**Comment by BenHenning** [comment]
What do you mean by specific logs? I'm not sure that I understand.

**Comment by veena14cs** [comment]
I mean to say messages that we add to the app with the Log
<https://developer.android.com/reference/android/util/Log.html> class.

**Comment by BenHenning** [comment]
@veena14cs per our meeting last week, what's your proposed solution for logging? Please document your thoughts in this issue.

**Comment by BenHenning** [comment]
Pushing this back to the prototype milestone. We can live with Android's Log class in the meantime.

**Comment by BenHenning** [comment]
Similarly, we can probably live without this until MVP or GA when deeper investigations become more important.
