### ISSUE TITLE
Highfi: ProfileEditActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#805]
<FILE NAME> needs to be pixel perfect with the mocks.
Portrait Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/1c3f250f-32e5-4299-8187-75d7c3dbe6b6/Settings-1-Profile-Chantel-Disabled-5/
Landscape Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/5b8a8202-6081-4855-8c49-94a8a5b4c559/RG-MN-Register-Empty-35/

Mocks have been created for HDPI Devices.
Make sure that the screen passes the accessibility test also.
For reference you can checkout: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by rt4914** [comment]
Assigning this to @Scarlet0103 considering that lowfi landscape was done perfectly by @Scarlet0103 . While working on this follow everything mentioned on https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by Scarlet0103** [comment]
@rt4914 should I keep the top_margin and bottom_margin for profile_delete button in the land-scape view as mentioned in the mocks?
which is 60dp and 108dp

**Comment by rt4914** [comment]
> @rt4914 should I keep the top_margin and bottom_margin for profile_delete button in the land-scape view as mentioned in the mocks?
> which is 60dp and 108dp

@Scarlet0103 Yes. Also, please do not mention these things in issue as it become hard to understand. For best practices, create a PR and in that mention your doubts so that we can check the code also to understand things in better way.
