### ISSUE TITLE
Lowfi: Walkthrough Fragment - Part 1

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#811]
Mock : https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/9bb5c0e5-f77e-4c28-8d79-18515d0e9711/WT-Introduction-

WalkthroughWelcomeFragment implementation should match as per mocks.

**Comment by aggarwalpulkit596** [comment]
Should I make these in Landscape as well?

**Comment by rt4914** [comment]
> Should I make these in Landscape as well?

Not in these issues, once portrait is finalised, changing to landscape won't be that hard.
