### ISSUE TITLE
Lowfi: WalkthrougTopicListFragment Part 2

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#812]
Mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/92becc49-3a10-498b-885c-4cde95f73d51/WT-Topic-List-

WalkthroughTopicListFragment implementation should match as per mocks.

**Comment by aggarwalpulkit596** [comment]
@rt4914 Can you please explain this workflow how to display the list what action to do perform on user selection etc

**Comment by rt4914** [comment]
> @rt4914 Can you please explain this workflow how to display the list what action to do perform on user selection etc

Actually this implementation resembles the implementation of `HomeFragment` in a lot of ways because in that also we are showing list of topics. But I would suggest you to focus on part-1 first as the concept which you will use in that can easily be used in here too. If you want to work on this right now, you can check various implementations of such lists in `OngoingTopicListActivity`, `CompletedStoryListActivity`, `StoryActivity`.

**Comment by aggarwalpulkit596** [comment]
@rt4914 should I make a separate adapter for this or should reuse the existing code because TopicListViewHolder will be exactly same as before

**Comment by aggarwalpulkit596** [comment]
@rt4914 also how do I have to handle the selection of a topic because in this PR I have to make things in order to fulfill the needs of the last walkthrough fragment

**Comment by rt4914** [comment]
> @rt4914 should I make a separate adapter for this or should reuse the existing code because TopicListViewHolder will be exactly same as before

There are two approaches to this:
1. We can create a new adapter, but in long run we will definitely replace that adapter with a `BindableAdapter`.
2. We can directly use `BindableAdapter` at this stage only.

I would suggest you to apply step 2 instead of 1, as learning about `BindableAdapter` is important for this project.
Now as a reference you can actually see the implementation in `StoryActivity` where we are using a bindable adapter. In that implementation you will see that there are two different types of views:
a. VIEW_TYPE_HEADER and b. VIEW_TYPE_CHAPTER now similar to this you will have two views VIEW_TYPE_HEADER (containing text `What do you want to learn?`) and `VIEW_TYPE_TOPIC` which will contain each topic.

The above description is for Adapter/data only.

Second part of this implementation is how data is arranged because the index0 item is the text and other items are a grid layout manager. So it looks like it is a combination of LinearLayoutManager and GridLayoutManager. So for this you can take help from https://github.com/oppia/oppia-android/blob/04f074ebfd7c0cdc271abbfacd3f6fcb929f29c0/app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt#L69

**Comment by aggarwalpulkit596** [comment]
@rt4914 actually I was using the second approach and already gone through all these files /codes
Thanks anyway

**Comment by rt4914** [comment]
> @rt4914 actually I was using the second approach and already gone through all these files /codes
> Thanks anyway

@aggarwalpulkit596 Okay, so where you are exactly stuck right now?

**Comment by aggarwalpulkit596** [comment]
Nowhere just trying to implement without taking multiple reviews this time😅

**Comment by rt4914** [comment]
> Nowhere just trying to implement without taking multiple reviews this time😅

Great to know that. :-)

**Comment by aggarwalpulkit596** [comment]
@rt4914 should I make a separate file for topic_summary view as well?
Because that is bind to some ViewModel and i can't use that
