### ISSUE TITLE
Lowfi: WalkthroughFinalFragment - Part 3

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#813]
Mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/25ac193c-0645-4872-9e46-a408cdf2d5b7/WT-Topic-Confirmation-Unchosen-

`WalkthroughFinalFragment` implementation should match mocks.

**Comment by aggarwalpulkit596** [comment]
@rt4914 Starting this today
