### ISSUE TITLE
Question Player Content item UI update -Hi-fi

### ISSUE THREAD

**Issue by nikitamarysolomanpvt** [oppia/oppia-android#823]
Question Player Content item UI update -Hi-fi
## Mock
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/8fbb663a-39aa-4be1-83bd-73bde6f85dcc/PM-Q1-Fraction-Input-No-Answer-

**Comment by rt4914** [comment]
Closed via https://github.com/oppia/oppia-android/pull/1529
