### ISSUE TITLE
Landscape Lowfi: CompletedStoryList

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#833]
Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/48c041b4-dad1-4972-8564-4783766e8af7/UP-Stories-Completed-

For reference you can check implementation https://github.com/oppia/oppia-android/pull/827/files

Also add test cases for the same.

**Comment by SayantanBanerjee16** [comment]
Thanks for assigning, I will start working on this ASAP.

**Comment by SayantanBanerjee16** [comment]
@rt4914 I couldn't understand what to implement. There is neither portrait mode present nor any view model or recycler view present. So what exactly I need to implement?

**Comment by rt4914** [comment]
> @rt4914 I couldn't understand what to implement. There is neither portrait mode present nor any view model or recycler view present. So what exactly I need to implement?

Yeah, actually this is tricky, now logically if understand, you cannot have a `CompletedStoriesList` because you haven't finished the chapters yet and you haven't made any progress in that. So this is what you can do, you can mark some fake progress using `StoryProgressTestHelper`.
Reference: https://gist.github.com/rt4914/5258375c8d2cca81b6a5b62ccab8e143 (Line number: 39, 92, 93) This is just for dummy purposes and should not be included in your final PR and also if you will run the current test cases you will notice that it does show some items because of this code:
https://github.com/oppia/oppia-android/blob/82ec1c7bde3435737006107efe9def1ced034ac4/app/src/sharedTest/java/org/oppia/app/completedstorylist/CompletedStoryListActivityTest.kt#L56

**Comment by SayantanBanerjee16** [comment]
@rt4914 I have assigned @chrk2205 this issue considering I will work in #653

**Comment by rt4914** [comment]
Unassigning @chrk2205 as he is focused towards GSoC proposal and has already finished two PRs.
