### ISSUE TITLE
Reordering in Android Manifest file.

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#856]
In android manifest file we have been following the alphabetical convention in activity declaration.

Some of these activities are not in alphabetical order. Rearrange them.

```
    <activity android:name=".testing.RecentlyPlayedFragmentTestActivity" />
    <activity
      android:name=".testing.NavigationDrawerTestActivity"
      android:screenOrientation="portrait"
      android:theme="@style/OppiaThemeWithoutActionBar" />
```

**Comment by rt4914** [comment]
Assigned to @MohamedMedhat1998

**Comment by MohamedMedhat1998** [comment]
Will the sort be case sensitive?  
For example,  
`.help.HelpActivity` should come before `.help.faq.FAQActivity` because the capital "H" is before the lower "f" in the ASCII code?

**Comment by rt4914** [comment]
> Will the sort be case sensitive?
> For example,
> `.help.HelpActivity` should come before `.help.faq.FAQActivity` because the capital "H" is before the lower "f" in the ASCII code?

no.
