### ISSUE TITLE
Introduce Retrofit abstraction for a single Oppia endpoint

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#88]
This effort involves introducing a single endpoint (topics) to demonstrate a complete Retrofit integration with the Oppia Android app.

See #5 for details on the complete integration effort that follows from this work.

**Comment by rt4914** [comment]
@BenHenning Can this issue be closed? We have already finished the TopicService Retrofit integration along with test cases.

**Comment by BenHenning** [comment]
Yep, this has been resolved with your PRs. Thanks @rt4914!
