### ISSUE TITLE
Highfi Navigation Drawer

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#899]
Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/79c56b13-218b-48fc-a403-b085d46953f3/Settings-Side-Menu-1

Landscape mock is not available but this mock is enough to convert the layout to landscape mock.

**Comment by rt4914** [comment]
Closing this PR as it has a duplicate issue.

**Comment by seanlip** [comment]
Hi @rt4914 -- when closing PRs due to duplicates, please could you state the number of the original issue? Thanks!
