### ISSUE TITLE
Implement TopicListController

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#9]
A management system is needed for the list of topics available to the user, including tracking when this list needs to be updated and replaced with a new copy downloaded from the Oppia backend.

Consumers of this system will want to enumerate the list of topics available to the user, slice that by the user's own activity and progress on those topics, and jump to the topic viewer for a specific topic in the list. Topics sould support organization by their subject. Note that this system is not responsible for tracking progress--a separate system will do that as described below.

**Comment by BenHenning** [comment]
This is blocked on #5, #6, and #7.

**Comment by BenHenning** [comment]
This is actually blocked on #88, and was blocked on #86 and #87.

**Comment by BenHenning** [comment]
This is blocked on #117.

**Comment by rt4914** [comment]
@BenHenning Is this not finished yet? I was using this from `domain` layer

**Comment by BenHenning** [comment]
Should be done.
