### ISSUE TITLE
Highfi and content for FAQSingleActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#907]
Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/195a7967-e7f0-4f62-a99c-8fac560e41d8/HL-FAQ-How-can-I-delete-v2-/

Data: https://docs.google.com/spreadsheets/d/1O9B8oZSXAS3RUm8w2JxHmWRHsh4bNHMOYSRCYLRFK84/edit#gid=0

**Comment by BenHenning** [comment]
Suggest not blocking on #1022 for alpha--let's get the content in.
