### ISSUE TITLE
Update TopicInfo test cases for XHDPI and XXHDPI and XXXHDPI devices

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#914]
Updates test cases for XHDPI and XXHDPI and XXXHDPI devices.

`TopicInfo` contains `See More` textview which follows following UI condition:
1. If the topic description is of 5 or less lines. -> Do not show `See More`
2. If the topic description is more than 5 lines -> Show `See More` which is clickable and changable to `See Less`

Now we need robust tests to check this functionality in `TopicInfoFragmentTest`.

**Comment by anandwana001** [comment]
Here is the gif of `See More` and `See Less` feature for reference

![oppia_feature_see_mpore_less](https://user-images.githubusercontent.com/25057618/78874586-3b67c580-7a6a-11ea-9641-614929feff49.gif)

**Comment by virajpatel2411** [comment]
@rt4914 There are already test cases written for See more and See Less in `TopicInfoFragmentTest`.
Now, for xHDPI, xxHDPI and xxxHDPI, what exactly do I need to do?
Do I have to write a test case checking with textview containing more text so that see more and see less can be checked for the required devices?

**Comment by rt4914** [comment]
> @rt4914 There are already test cases written for See more and See Less in `TopicInfoFragmentTest`.
> Now, for xHDPI, xxHDPI and xxxHDPI, what exactly do I need to do?
> Do I have to write a test case checking with textview containing more text so that see more and see less can be checked for the required devices?

@virajpatel2411 Those tests do not make sure that whether 5 lines are visible or 3 lines are visible or 12 lines are visible. Also, based on number of lines  how does the `See More` textview visibility changes that is also not written in test cases.

You will need to write test cases like `testTopicInfoFragment_loadFragment_clickSeeMore_fullTopicDescriptionIsVisible`
`testTopicInfoFragment_loadFragment_clickSeeLess_onlyFirstFiveLinesAreVisible`

You can add more test cases these are just for example.

**Comment by virajpatel2411** [comment]
> > @rt4914 There are already test cases written for See more and See Less in `TopicInfoFragmentTest`.
> > Now, for xHDPI, xxHDPI and xxxHDPI, what exactly do I need to do?
> > Do I have to write a test case checking with textview containing more text so that see more and see less can be checked for the required devices?
> 
> @virajpatel2411 Those tests do not make sure that whether 5 lines are visible or 3 lines are visible or 12 lines are visible. Also, based on number of lines how does the `See More` textview visibility changes that is also not written in test cases.
> 
> You will need to write test cases like `testTopicInfoFragment_loadFragment_clickSeeMore_fullTopicDescriptionIsVisible`
> `testTopicInfoFragment_loadFragment_clickSeeLess_onlyFirstFiveLinesAreVisible`
> 
> You can add more test cases these are just for example.

Got it....Thanks @rt4914

**Comment by virajpatel2411** [comment]
@rt4914 There also is also a test case for checking if 5 lines are visible or not. Also, the change in visibility on clicking See More and See Less is also checked in two test cases. In the file, in a comment, it is written that add more data to Topic Description so that the test cases pass for the required devices.
Saying this, I can add more test cases which check both the number of lines i.e 5 and also the change in visibility, but aren't that already in the test cases?

**Comment by rt4914** [comment]
> @rt4914 There also is also a test case for checking if 5 lines are visible or not. Also, the change in visibility on clicking See More and See Less is also checked in two test cases. In the file, in a comment, it is written that add more data to Topic Description so that the test cases pass for the required devices.
> Saying this, I can add more test cases which check both the number of lines i.e 5 and also the change in visibility, but aren't that already in the test cases?

I am actually not able to understand what do you mean?
From my perspective you can do following thing:
1. Start test case
2. Change the topic description during the running test case so that the description is long enough and now write following test cases:
`testTopicInfoFragment_loadFragment_clickSeeMore_fullTopicDescriptionIsVisible`
`testTopicInfoFragment_loadFragment_clickSeeLess_onlyFirstFiveLinesAreVisible `
`testTopicInfoFragment_loadFragment_ifLinesAreLessThanFive_seeMoreIsNotVisible`

**Comment by virajpatel2411** [comment]
@rt4914 Okay. So, I need to change the topic description just for the new test cases only. Right?

**Comment by rt4914** [comment]
> @rt4914 Okay. So, I need to change the topic description just for the new test cases only. Right?

@virajpatel2411 Yes, it would be realtime testing change.

**Comment by virajpatel2411** [comment]
> > @rt4914 Okay. So, I need to change the topic description just for the new test cases only. Right?
> 
> @virajpatel2411 Yes, it would be realtime testing change.

Okayy. Thanks @rt4914
