### ISSUE TITLE
Selected Language in `AppLanguageActivity` should get reflected in entire app

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#915]
Currently the language selected in `AppLanguageActivity` is not getting set in the application on per profile basis. This functionality is need to make entire use of this activity.

**Comment by BenHenning** [comment]
Out of scope for alpha; we don't have any other languages to translate to yet.

**Comment by rt4914** [comment]
Unassigned myself as I am not working on this currently.

**Comment by BenHenning** [comment]
Should be addressed as part of #4606, so marking this as closed.

Note that we also have hidden this UI so that users don't get confused until the full functionality is implemented.
