### ISSUE TITLE
Optimise OngoingStoryList / Recommended Stories

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#936]
<img width="371" alt="Screenshot 2020-04-02 at 11 40 31 AM" src="https://user-images.githubusercontent.com/9396084/78216121-c418bb80-74d6-11ea-9748-a5236500c30c.png">

On `Home` screen there are list of ongoing stories/promoted stories. All these stories are promoted based on two factors:
1. If learner has opened one chapter but has never finished it, in that case that chapter will get promoted.
2. If the learner has finished CHAPTER 1 from STORY 1 then, CHAPTER 2 from STORY 1 will get promoted.

If the learner is completely new then in that case we are showing default recommended stories which promoted Chapter 1 in Fractions as well as Ratios.

So the algorithm `TopicListController.createOngoingStoryListFromProgress()` can be optimised to keep these story list in timestamp order meaning the recent story should get promoted first.

Pointers on optimising the algorithm:
- Introduce percentage of exploration finished in proto/domain layer and promote the story which is more finished.
-  Ordered list via timestamp
- Anything else that you feel can make the user experience better, you can suggest that too.

NOTE: [Design doc ](https://github.com/oppia/oppia/wiki/Writing-design-docs) is  necessary before creating a PR for this issue.

**Comment by BenHenning** [comment]
@rt4914 is this part of @veena14cs's project?

**Comment by rt4914** [comment]
> @rt4914 is this part of @veena14cs's project?

@BenHenning Partially yes. In optimisation tips there are three points and out of which @veena14cs has to focus on the timestamp part only. The percentage/scoring of exploration is not a part of @veena14cs 's project.
