### ISSUE TITLE
Add radar effect in Hints and solution.

### ISSUE THREAD

**Issue by veena14cs** [oppia/oppia-android#941]
Add radar effect in hints and solution whenever a new hint appears.

Mock Links
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/e789f7c6-c677-4c76-b3e5-d603fd84d1e1/LM-Q5-HS-Hint-1-Notification-Dot-End-

Focus on animation and hifi of this yellow radar:
<img width="65" alt="Screenshot 2020-04-13 at 10 39 55 AM" src="https://user-images.githubusercontent.com/9396084/79093850-2beec200-7d73-11ea-992b-f545e7c6518c.png">

**Comment by chrk2205** [comment]
@rt4914 @veena14cs 
am i supposed to create animation for that??

**Comment by rt4914** [comment]
> @rt4914 @veena14cs
> am i supposed to create animation for that??

@chrk2205 Yes, thats part of this issue.

**Comment by BenHenning** [comment]
Reopening since the underlying change was reverted. Also, moving to M3 since M2 is now over.
