### ISSUE TITLE
Highfi ProfileProgressActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#949]
This issue tracks the highfi work of `ProfileProgressActivity`

Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/7fb5929e-4652-4412-bf8c-64d94f4159f9/UP-User-Profile-/

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/8509e066-bfbb-4140-b329-3d43a4d20c9d/UP-User-Profile-/

**Comment by chrk2205** [comment]
@rt4914 @nikitamarysolomanpvt 
I would like to work on this. can i?

**Comment by rt4914** [comment]
> @rt4914 @nikitamarysolomanpvt
> I would like to work on this. can i?

@chrk2205 This issue has already been assigned to @nikitamarysolomanpvt . You can work on https://github.com/oppia/oppia-android/issues/941
