### ISSUE TITLE
IME_ACTIONS doesn't work properly in ProfileInputView

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#962]
When using the IME_ACTIONS from the soft-keyboard like `next` and `done`  with the custom view `ProfileInputView`, they don't work properly.  
Instead of moving to the next input field, the `next` action opens a new soft-keyboard.  

![next](https://user-images.githubusercontent.com/8533363/78993984-5a845700-7b3f-11ea-887e-4770ddf11e82.gif)

This problem makes unit tests related to IME_ACTIONS fail.

![test](https://user-images.githubusercontent.com/8533363/78994009-6b34cd00-7b3f-11ea-9bce-55506957926d.gif)

**Comment by anandwana001** [comment]
To solve this issue, we might need to introduce `imeOption` feature in the `ProfileInputView`. So, if we have a series of `ProfileInputView` which is our custom Linear Layout consisting of 3 things - 1. Lable(TextView), 2. Error(TextView) and 3. Input(EditText), we have to create some helper methods which can have `IME_ACTION_NEXT` and `IME_ACTION_DONE` to hop between these multiple `ProfileInputView` and set focus accordingly.

**Comment by MohamedMedhat1998** [comment]
> 
> 
> To solve this issue, we might need to introduce `imeOption` feature in the `ProfileInputView`. So, if we have a series of `ProfileInputView` which is our custom Linear Layout consisting of 3 things - 1. Lable(TextView), 2. Error(TextView) and 3. Input(EditText), we have to create some helper methods which can have `IME_ACTION_NEXT` and `IME_ACTION_DONE` to hop between these multiple `ProfileInputView` and set focus accordingly.

For some reason, the soft keyboard changes from numbers only to the normal one whenever the `IME_ACTION` is clicked regardless of the currently focused item.  
You can notice that clearly in the second GIF. It happens during testing with Espresso.

**Comment by FareesHussain** [comment]
I tried this using request focus and show soft input using InputMethodManager but it doesn't work

**Comment by anandwana001** [comment]
It's a Custom View so might need some tweaks in the custom side.

**Comment by anandwana001** [comment]
closing this issue as we have successfully migrated to `TextInputLayout` and removed `ProfileInputView` completely.
