### ISSUE TITLE
Reenable all landscape tests in app module

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#968]
In app module there are test cases which are getting ignored right now because of landscape feature. Now we can reenable all these test cases. You can find these test cases by this line in various files:
`@Ignore("Landscape not properly supported") // TODO(#56): Reenable once landscape is supported.`

Note: You have to focus on `app` module tests only.

**Comment by SayantanBanerjee16** [comment]
@rt4914 Can I work on this issue?

**Comment by rt4914** [comment]
> @rt4914 Can I work on this issue?

@SayantanBanerjee16 Yeah sure. Update: I do think that it should be almost finished but this issue has been kept to verify that correctly. Thanks.
