### ISSUE TITLE
Add a Protobuf linter to the project

### ISSUE THREAD

**Issue by vinitamurthi** [oppia/oppia-android#971]
We currently rely on reviewers to enforce the style guide for protobuf files. We would like to add a linter to automate this task. 
[Buf](https://github.com/bufbuild/buf) seems to be a good fit for our requirements and we would like to use that for our project. If you have recommendations for some other linter, please reach out to me to discuss if we can use it in our project before adding it.

Steps that need to be completed to add the linter:

- [x] Run the linter on our existing protobuf files. Create a PR that fixes all lint problems that the linter catches

- [x] Add steps in the linter job of our CircleCI workflow (similar to the Kotlin linting step) that will install and run the linter on our protobuf files

- [x] Add documentation on how to install the linter in the prerequisites section of our wiki

**Comment by vinitamurthi** [comment]
@anandwana001 Would you be interested in taking this up?

**Comment by anandwana001** [comment]
> @anandwana001 Would you be interested in taking this up?

Sure, I will go through it.

**Comment by vinitamurthi** [comment]
Great! I will assign it to you then

**Comment by anandwana001** [comment]
Could you please update me with the command you are using to compile the proto files? I did some update in import statements and I need to update proto files in build folder as well.

<img width="1440" alt="Screenshot 2020-05-28 at 10 38 50" src="https://user-images.githubusercontent.com/25057618/83101237-7cc23c00-a0cf-11ea-980b-ae9f7b6dc9c8.png">

If I exclude the `model/build`, it seems like this:

<img width="1440" alt="Screenshot 2020-05-28 at 10 57 33" src="https://user-images.githubusercontent.com/25057618/83102451-1e4a8d00-a0d2-11ea-8444-10224c22c46e.png">

**Comment by vinitamurthi** [comment]
I actually think your second screenshot shows that it is working right? We may have to update the lint checks to allow for certain things its shouting about

**Comment by anandwana001** [comment]
ok. I am checking why are these proto files are there in build folder and what is their use if we will exclude them in `buf.yaml`.


<img width="1440" alt="Screenshot 2020-05-28 at 11 43 38" src="https://user-images.githubusercontent.com/25057618/83105549-81d7b900-a0d8-11ea-9cab-82447c090756.png">

Now, step 2, to add it to the config.yaml.

**Comment by anandwana001** [comment]
Step2 - `Add steps in the linter job of our CircleCI workflow (similar to the Kotlin linting step) that will install and run the linter on our protobuf files`

@vinitamurthi  Just wanted to check with you before PR, as I can't test locally if it is correct or not.
```
anchor_for_install_buf: &install_buf
  name: Download latest buf
  command: >
        get_latest_or_prerelease() {
             curl --silent "https://api.github.com/repos/$1/releases" |
             grep '"tag_name":' |
             sed -E 's/.*"([^"]+)".*/\1/'
        }

        BUFBUILD=$(get_latest_or_prerelease bufbuild/buf)

        echo Using Bufbuild $BUFBUILD

        PROJECT="oppia-android"
        UNAME_OS=$(shell uname -s)
        UNAME_ARCH=$(shell uname -m)
        CACHE_BASE=$(HOME)/.cache/$(PROJECT)
        CACHE=$(CACHE_BASE)/$(UNAME_OS)/$(UNAME_ARCH)
        CACHE_BIN=$(CACHE)/bin

        curl -sSL \
        "https://github.com/bufbuild/buf/releases/download/v$BUFBUILD/buf-$(UNAME_OS)-$(UNAME_ARCH)" \
        -o "$(CACHE_BIN)/buf"

        chmod +x "$(CACHE_BIN)/buf"
```

Adding the step inside `linters` job as an another step after it completed the `Kotlin tests` step.
 ```
- run:
       name: Kotlin tests - Data, Utility
       command: ./ktlint utility/**/*.kt data/**/*.kt && echo "Lint completed successfully"
- run:
       <<: *install_buf
- run:
       name: Buf check - proto files
       command: buf check lint
```

at CircleCi it should run something like:
```
curl -sSL \
	"https://github.com/bufbuild/buf/releases/download/v0.13.0/buf-Linux-x86_64" \
	-o "/home/circleci/.cache/oppia-android/Linux/x86_64/bin/buf"
chmod +x "/home/circleci/.cache/oppia-android/Linux/x86_64/bin/buf"
buf check lint
```

**Comment by vinitamurthi** [comment]
That looks good to me, only one thing - do the installation of linters together and then run tests together. i.e. let the steps be : install ktlint, install buf, run ktlint, run buf

As for testing, yes we cannot test locally but you can make these changes in circleci config and create a PR and see what happens with the continuous integration tests in that PR
