### ISSUE TITLE
Fix lint issues in the kotlin files

### ISSUE THREAD

**Issue by vinitamurthi** [oppia/oppia-android#972]
After enabling ktlint in our repository, we noticed that there are several files that have lint errors being caught by ktlint. We would like to fix all the lint errors.

[Ktlint](https://github.com/pinterest/ktlint) has an auto-formatter that can fix most of the lint errors, whatever it cannot fix will need to be fixed manually.  You can run ktlint with the auto-formatter in the following way:
`ktlint -F "file.kt"`

To run ktlint (with the auto-formatter) on an entire module:
`ktlint -F "<module_name>/src/**/java"`
For example, this is how you can run ktlint on all files in the utility module:
`ktlint -F "utility/src/**/java"`

Fix lint errors in the following modules:

- [x] Utility

- [x] Data

- [x] Domain

- [x] App (check with @rt4914 , @BenHenning , and @vinitamurthi before tackling this module)

**Comment by anandwana001** [comment]
@vinitamurthi Seems like this is done, could we close this issue?

**Comment by vinitamurthi** [comment]
Yep, closing it!
