### ISSUE TITLE
Issue with Profile picture.

### ISSUE THREAD

**Issue by veena14cs** [oppia/oppia-android#988]
When 1st time profile picture is added it is updated in all the places like navigation drawer, profile edit page and profile chooser page.  Next time when we edit that profile picture it is only updated in profile chooser. Navigation drawer and profile edit page has old image.

![Screenshot_20200415-155540](https://user-images.githubusercontent.com/16301028/79327266-cdbc0d80-7f31-11ea-895a-15ddebcf36fa.png)
![Screenshot_20200415-155548](https://user-images.githubusercontent.com/16301028/79327273-d0b6fe00-7f31-11ea-9e85-891a17c7cd25.png)
![Screenshot_20200415-155531](https://user-images.githubusercontent.com/16301028/79327280-d3195800-7f31-11ea-8362-2ce7645b566e.png)

**Comment by NullByte08** [comment]
@veena14cs Can I work on this ?
